CREATE TABLE [Compliance].[ComplaintsRegister] (
    [ComplaintRegisterId]         INT              IDENTITY (1, 1) NOT NULL,
    [ComplainantClientName]       VARCHAR (128)    NOT NULL,
    [PartyComplaintAgainst]       VARCHAR (2048)   NOT NULL,
    [ReferenceNumbers]            VARCHAR (2048)   NULL,
    [ComplaintStatus]             VARCHAR (25)     NULL,
    [RecordedByPersonId]          SMALLINT         NOT NULL,
    [ReportedBy]                  VARCHAR (2048)   NULL,
    [ReportedByCompany]           VARCHAR (2048)   NULL,
    [ComplaintCategoryId]         SMALLINT         NULL,
    [FundsAffected]               VARCHAR (2048)   NULL,
    [ComplaintDetails]            VARCHAR (MAX)    NOT NULL,
    [ComplaintDate]               DATE             NULL,
    [ReportedToWIMDate]           DATE             NULL,
    [CompOrRestitutionSummary]    VARCHAR (MAX)    NULL,
    [ComplaintRootCauseId]        SMALLINT         NULL,
    [RootCauseDetails]            VARCHAR (MAX)    NULL,
    [RemedialAction]              NVARCHAR (MAX)   NULL,
    [MitigationSteps]             NVARCHAR (MAX)   NULL,
    [ComplaintClosed]             BIT              CONSTRAINT [DF_CR_COC] DEFAULT ((0)) NOT NULL,
    [ThirdPartyId]                SMALLINT         NULL,
    [ExternalPartyFwdTo]          VARCHAR (128)    NULL,
    [JIRAIssueKey]                VARCHAR (255)    NULL,
    [DocumentationFolderLink]     VARCHAR (2000)   NULL,
    [SubflowJoinGUID]             VARCHAR (2000)   NULL,
    [JoinGUID]                    UNIQUEIDENTIFIER NOT NULL,
    [ComplaintCreationDate]       DATETIME         CONSTRAINT [DF_CR_CCDT] DEFAULT (getdate()) NOT NULL,
    [ComplaintLastModifiedDate]   DATETIME         CONSTRAINT [DF_CR_CLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]       DATETIME         CONSTRAINT [DF_CR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]        DATETIME         CONSTRAINT [DF_CR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]      NVARCHAR (50)    CONSTRAINT [DF_CR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]       INT              CONSTRAINT [DF_CR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]      ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]   DATETIME         CONSTRAINT [DF_CR_CSL] DEFAULT (getdate()) NULL,
    [ThirdPartyComplaintReceived] BIT              NULL,
    CONSTRAINT [PKComplaintsRegister] PRIMARY KEY CLUSTERED ([ComplaintRegisterId] ASC),
    CONSTRAINT [ComplaintsRegisterComplaintCategoryId] FOREIGN KEY ([ComplaintCategoryId]) REFERENCES [Compliance].[ComplaintCategories] ([CategoryId]),
    CONSTRAINT [ComplaintsRegisterComplaintRootCauseId] FOREIGN KEY ([ComplaintRootCauseId]) REFERENCES [Compliance].[ComplaintRootCauses] ([RootCauseId]),
    CONSTRAINT [ComplaintsRegisterRecordedByPersonId] FOREIGN KEY ([RecordedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ComplaintsRegisterThirdPartyId] FOREIGN KEY ([ThirdPartyId]) REFERENCES [Core].[ThirdParties] ([ThirdPartyId])
);

