CREATE TABLE [Compliance].[ConflictsRegisterPotential] (
    [ConflictId]                            INT              IDENTITY (1, 1) NOT NULL,
    [NotifyingPersonId]                     SMALLINT         NOT NULL,
    [ConflictEntryDate]                     DATETIME         CONSTRAINT [DF_CRP_CED] DEFAULT (getdate()) NOT NULL,
    [PotentialConflictClientSalesforceId]   VARCHAR (18)     NULL,
    [PotentialConflictClientSalesforceName] VARCHAR (127)    NULL,
    [PotentialConflictSummary]              NVARCHAR (511)   NOT NULL,
    [PotentialConflictDetails]              NVARCHAR (MAX)   NOT NULL,
    [RecognitionDate]                       DATE             NOT NULL,
    [JIRAIssueKey]                          VARCHAR (255)    NULL,
    [WorkflowVersionGUID]                   UNIQUEIDENTIFIER NULL,
    [JoinGUID]                              UNIQUEIDENTIFIER NOT NULL,
    [CreatedByPersonId]                     SMALLINT         NOT NULL,
    [ConflictStatusId]                      INT              NOT NULL,
    [ConflictCategory1ID]                   SMALLINT         NULL,
    [ConflictCategory2ID]                   SMALLINT         NULL,
    [HuddleEventID]                         INT              NULL,
    [DocumentationLink]                     NVARCHAR (255)   NULL,
    [NextReviewDate]                        DATETIME         NULL,
    [ConflictClosedDate]                    DATETIME         NULL,
    [CADIS_SYSTEM_INSERTED]                 DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                  DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PKConflictsRegisterPotential] PRIMARY KEY CLUSTERED ([ConflictId] ASC),
    CONSTRAINT [CategoryConflictCategory1ID] FOREIGN KEY ([ConflictCategory1ID]) REFERENCES [Compliance].[ConflictsRegisterCategories] ([ConflictsRegisterCategoryId]),
    CONSTRAINT [CategoryConflictCategory2ID] FOREIGN KEY ([ConflictCategory2ID]) REFERENCES [Compliance].[ConflictsRegisterCategories] ([ConflictsRegisterCategoryId]),
    CONSTRAINT [ConflictsRegisterPotentialCreatedByPersonId] FOREIGN KEY ([CreatedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ConflictsRegisterPotentialNotifyingPersonId] FOREIGN KEY ([NotifyingPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [FlowStatusConflictId] FOREIGN KEY ([ConflictStatusId]) REFERENCES [Core].[FlowStatus] ([FlowStatusId])
);

