CREATE TABLE [Compliance].[EBIRegister] (
    [EBIRegisterId]                     INT              IDENTITY (1, 1) NOT NULL,
    [EBIExternalReference]              VARCHAR (100)    NULL,
    [DateIdentified]                    DATE             NOT NULL,
    [ReportedByPersonId]                SMALLINT         NOT NULL,
    [RecordedByPersonId]                SMALLINT         NOT NULL,
    [EBITypeCode]                       VARCHAR (25)     NULL,
    [EBIBreachTypeId]                   SMALLINT         NULL,
    [EBIImpactTypeId]                   SMALLINT         NULL,
    [EBICategorisationId]               SMALLINT         NULL,
    [EBISummary]                        NVARCHAR (MAX)   NOT NULL,
    [EBIStartDate]                      DATE             NOT NULL,
    [EBIEndDate]                        DATE             NULL,
    [EBIClosureDate]                    DATE             NULL,
    [EBIResolvedYesNo]                  BIT              NULL,
    [RemedyAction]                      NVARCHAR (MAX)   NULL,
    [MitigationSteps]                   NVARCHAR (MAX)   NULL,
    [IncidentReportFinalizationDate]    DATE             NULL,
    [ExternalNotificationRequiredYesNo] BIT              NULL,
    [ExternalBodyId]                    SMALLINT         NULL,
    [ExternalNotificationDetails]       NVARCHAR (MAX)   NULL,
    [NotifiedDepartmentHeadId]          SMALLINT         NULL,
    [ReimbursementRequiredYesNo]        BIT              NULL,
    [ReimbursementAmount]               DECIMAL (19, 2)  NULL,
    [ReimbursementComments]             NVARCHAR (MAX)   NULL,
    [ReimbursementDate]                 DATE             NULL,
    [SentBackYesNo]                     BIT              NULL,
    [DisputedPendingLitigationYesNo]    BIT              NULL,
    [InvestmentRelatedYesNo]            BIT              NULL,
    [DataProtectionRelatedYesNo]        BIT              NULL,
    [RegulatoryRelatedYesNo]            BIT              NULL,
    [ReportableYesNo]                   BIT              NULL,
    [ServiceIssueID]                    VARCHAR (18)     NULL,
    [ServiceProviderName]               VARCHAR (128)    NULL,
    [ClientsNotifiedYesNo]              BIT              NULL,
    [Status]                            VARCHAR (50)     NULL,
    [WorkflowVersionGUID]               UNIQUEIDENTIFIER NULL,
    [JIRAIssueKey]                      VARCHAR (255)    NULL,
    [JoinGUID]                          UNIQUEIDENTIFIER NOT NULL,
    [EBIRegisterCreationDatetime]       DATETIME         CONSTRAINT [DF_EBIR_EBIRCDT] DEFAULT (getdate()) NOT NULL,
    [EBIRegisterLastModifiedDatetime]   DATETIME         CONSTRAINT [DF_EBIR_EBIRLMDT] DEFAULT (getdate()) NOT NULL,
    [HuddleEventId]                     SMALLINT         NULL,
    [ActiveInvestmentBreachYesNo]       BIT              CONSTRAINT [DF_EBIR_AIBYN] DEFAULT ((0)) NOT NULL,
    [RiskSubcategoryID]                 SMALLINT         NULL,
    CONSTRAINT [PKEBIRegister] PRIMARY KEY CLUSTERED ([EBIRegisterId] ASC),
    CONSTRAINT [EBIRegisterEBIBreachTypeId] FOREIGN KEY ([EBIBreachTypeId]) REFERENCES [Compliance].[EBIBreachTypes] ([EBIBreachTypeId]),
    CONSTRAINT [EBIRegisterEBICategorisationId] FOREIGN KEY ([EBICategorisationId]) REFERENCES [Compliance].[EBICategorisations] ([EBICategorisationId]),
    CONSTRAINT [EBIRegisterEBIImpactTypeId] FOREIGN KEY ([EBIImpactTypeId]) REFERENCES [Compliance].[EBIImpactTypes] ([EBIImpactTypeId]),
    CONSTRAINT [EBIRegisterExternalBodyId] FOREIGN KEY ([ExternalBodyId]) REFERENCES [Compliance].[EBIExternalBodies] ([EBIExternalBodyId]),
    CONSTRAINT [EBIRegisterNotifiedDepartmentHeadId] FOREIGN KEY ([NotifiedDepartmentHeadId]) REFERENCES [Core].[Roles] ([RoleId]),
    CONSTRAINT [EBIRegisterRecordedByPersonId] FOREIGN KEY ([RecordedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [EBIRegisterReportedByPersonId] FOREIGN KEY ([ReportedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

