CREATE TABLE [Compliance].[GiftEntertainmentExpenses] (
    [ExpenseId]            INT             IDENTITY (1, 1) NOT NULL,
    [ExpenseReference]     VARCHAR (25)    NOT NULL,
    [CurrencyCode]         CHAR (3)        NOT NULL,
    [ExpenseAmount]        DECIMAL (19, 2) NOT NULL,
    [ExpenseCategory]      VARCHAR (128)   NULL,
    [ExpenseIncurredDate]  DATETIME        NULL,
    [Description]          VARCHAR (MAX)   NULL,
    [GivenOrReceived]      VARCHAR (100)   NULL,
    [GiftOrEntertainment]  VARCHAR (100)   NULL,
    [ExpenseApproved]      BIT             NOT NULL,
    [ApprovedByPersonId]   SMALLINT        NULL,
    [ComplianceComments]   VARCHAR (MAX)   NULL,
    [CreatedByETL]         BIT             NOT NULL,
    [InCurrentYear]        BIT             NOT NULL,
    [ExpenseReportable]    BIT             NOT NULL,
    [RelatesToPersonId]    SMALLINT        NULL,
    [LastName]             VARCHAR (128)   NULL,
    [FirstName]            VARCHAR (128)   NULL,
    [Title]                VARCHAR (128)   NULL,
    [Salutation]           VARCHAR (25)    NULL,
    [AccountName]          VARCHAR (128)   NULL,
    [AccountOwnerPersonId] SMALLINT        NULL,
    [CreatedByPersonId]    SMALLINT        NULL,
    [ExpenseCreationDate]  DATETIME        NOT NULL,
    [ExpenseModifiedDate]  DATETIME        NOT NULL,
    CONSTRAINT [PKGiftEntertainmentExpenses] PRIMARY KEY CLUSTERED ([ExpenseId] ASC),
    CONSTRAINT [GiftEntertainmentExpensesAccountOwnerPersonId] FOREIGN KEY ([AccountOwnerPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [GiftEntertainmentExpensesApprovedByPersonId] FOREIGN KEY ([ApprovedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [GiftEntertainmentExpensesCreatedByPersonId] FOREIGN KEY ([CreatedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [GiftEntertainmentExpensesRelatesToPersonId] FOREIGN KEY ([RelatesToPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

