CREATE TABLE [Compliance].[RegulatoryCorrespondenceRegister] (
    [RegulatoryCorrespondenceId]                           INT              IDENTITY (1, 1) NOT NULL,
    [RegulatoryInteractionId]                              INT              NULL,
    [SubmittedByPersonId]                                  SMALLINT         CONSTRAINT [DF_RCR_RCRSP] DEFAULT ((-1)) NOT NULL,
    [CorrespondenceDate]                                   DATETIME         CONSTRAINT [DF_RCR_RCRID] DEFAULT (getdate()) NOT NULL,
    [CorrespondenceType]                                   VARCHAR (50)     NULL,
    [Status]                                               VARCHAR (50)     NULL,
    [SummaryDescription]                                   NVARCHAR (MAX)   NULL,
    [Comments]                                             NVARCHAR (MAX)   NULL,
    [ContactedBy]                                          VARCHAR (MAX)    NULL,
    [ContactTitle]                                         VARCHAR (50)     NULL,
    [RegulatoryBody]                                       VARCHAR (256)    NULL,
    [BoxFolderId]                                          VARCHAR (25)     NULL,
    [JIRAIssueKey]                                         VARCHAR (255)    NULL,
    [DocumentationFolderLink]                              VARCHAR (2000)   NULL,
    [JoinGUID]                                             UNIQUEIDENTIFIER NOT NULL,
    [RegulatoryCorrespondenceRegisterCreationDatetime]     DATETIME         CONSTRAINT [DF_RCR_RCRCDT] DEFAULT (getdate()) NOT NULL,
    [RegulatoryCorrespondenceRegisterLastModifiedDatetime] DATETIME         CONSTRAINT [DF_RCR_RCRLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                                DATETIME         CONSTRAINT [DF_RCR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                                 DATETIME         CONSTRAINT [DF_RCR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                               NVARCHAR (50)    CONSTRAINT [DF_RCR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                                INT              CONSTRAINT [DF_RCR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                               ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                            DATETIME         CONSTRAINT [DF_RCR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKRegulatoryCorrespondenceRegister] PRIMARY KEY CLUSTERED ([RegulatoryCorrespondenceId] ASC),
    CONSTRAINT [RegulatoryCorrespondenceRegisterRegulatoryInteractionId] FOREIGN KEY ([RegulatoryInteractionId]) REFERENCES [Compliance].[RegulatoryInteractionRegister] ([RegulatoryInteractionId]),
    CONSTRAINT [RegulatoryCorrespondenceRegisterSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

