CREATE TABLE [Compliance].[StopListReasonType] (
    [ReasonTypeId]           SMALLINT      IDENTITY (1, 1) NOT NULL,
    [ReasonName]             VARCHAR (100) NOT NULL,
    [IsActive]               BIT           CONSTRAINT [DF_SLRS_IA] DEFAULT ((1)) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF_SLRS_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF_SLRS_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF_SLRS_CSCB] DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PKStopListReasonType] PRIMARY KEY CLUSTERED ([ReasonTypeId] ASC) WITH (FILLFACTOR = 80)
);

