CREATE TABLE [Compliance].[TraderAuthorisation] (
    [TraderAuthorisationId]                   INT              IDENTITY (1, 1) NOT NULL,
    [TraderName]                              VARCHAR (128)    NOT NULL,
    [TrainedByPersonId]                       SMALLINT         NULL,
    [TrainingCompletedDate]                   DATETIME         NULL,
    [ApprovedByPersonId]                      SMALLINT         NULL,
    [ApprovalDate]                            DATETIME         NULL,
    [DecisionDate]                            DATETIME         NULL,
    [FCAResponseDate]                         DATETIME         NULL,
    [ReasonForRequest]                        VARCHAR (MAX)    NOT NULL,
    [RequestedByPersonId]                     SMALLINT         NOT NULL,
    [RequiredByDate]                          DATETIME         NOT NULL,
    [ReviewerNotes]                           VARCHAR (MAX)    NULL,
    [Status]                                  VARCHAR (255)    NULL,
    [JiraParentKey]                           VARCHAR (2000)   NULL,
    [DocumentationFolderLink]                 VARCHAR (2000)   NULL,
    [JoinGUID]                                UNIQUEIDENTIFIER NOT NULL,
    [TraderAuthorisationCreationDatetime]     DATETIME         CONSTRAINT [DF_TA_TACDT] DEFAULT (getdate()) NOT NULL,
    [TraderAuthorisationLastModifiedDatetime] DATETIME         CONSTRAINT [DF_TA_TALMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                   DATETIME         CONSTRAINT [DF_TA_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                    DATETIME         CONSTRAINT [DF_TA_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                  NVARCHAR (50)    CONSTRAINT [DF_TA_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                   INT              CONSTRAINT [DF_TA_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                  ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]               DATETIME         CONSTRAINT [DF_TA_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKTraderAuthorisation] PRIMARY KEY CLUSTERED ([TraderAuthorisationId] ASC),
    CONSTRAINT [TraderAuthorisationApprovedByPersonId] FOREIGN KEY ([ApprovedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [TraderAuthorisationRequestedByPersonId] FOREIGN KEY ([RequestedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [TraderAuthorisationTrainedByPersonId] FOREIGN KEY ([TrainedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

