CREATE TYPE [CADIS_SYS].[MULTIPLESOURCE_AUDITINS_TBLTYPE] AS TABLE (
    [PROCESSNAME] NVARCHAR (260) NULL,
    [SOURCENAME]  NVARCHAR (200) NULL,
    [RUNID]       INT            NULL,
    [STATUS]      INT            NULL,
    [ORDERBY]     INT            NULL);

