CREATE FUNCTION [wct].[ACCRINTM]
(@Issue DATETIME NULL, @Settlement DATETIME NULL, @Rate FLOAT (53) NULL, @Par FLOAT (53) NULL, @Basis NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ACCRINTM]

