CREATE FUNCTION [wct].[ADJCURRYIELD]
(@Settlement DATETIME NULL, @Maturity DATETIME NULL, @Price FLOAT (53) NULL, @Rate FLOAT (53) NULL, @Basis NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ADJCURRYIELD]

