CREATE FUNCTION [wct].[BASE2DECIMAL]
(@text NVARCHAR (4000) NULL, @Radix INT NULL)
RETURNS BIGINT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BASE2DECIMAL]

