CREATE FUNCTION [wct].[BETAI]
(@A FLOAT (53) NULL, @B FLOAT (53) NULL, @X FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BETAI]

