CREATE FUNCTION [wct].[BIVAR]
(@z1 FLOAT (53) NULL, @z2 FLOAT (53) NULL, @rho FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BIVAR]

