CREATE FUNCTION [wct].[BUSDAYSWE]
(@StartDate DATETIME NULL, @EndDate DATETIME NULL, @Holidays NVARCHAR (MAX) NULL, @WE1 INT NULL, @WE2 INT NULL)
RETURNS INT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BUSDAYSWE]

