CREATE FUNCTION [wct].[BUSDAYS]
(@StartDate DATETIME NULL, @EndDate DATETIME NULL, @Holidays NVARCHAR (MAX) NULL)
RETURNS INT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BUSDAYS]

