CREATE FUNCTION [wct].[BUSINESSDATE]
(@StartDate DATETIME NULL, @DatePart NVARCHAR (4000) NULL, @Number INT NULL, @DateRollRule NVARCHAR (4000) NULL, @Holidays NVARCHAR (MAX) NULL)
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BUSINESSDATE]

