CREATE FUNCTION [wct].[BUSINESSDATEWE]
(@StartDate DATETIME NULL, @DatePart NVARCHAR (4000) NULL, @Number INT NULL, @DateRollRule NVARCHAR (4000) NULL, @Holidays NVARCHAR (MAX) NULL, @WE1 INT NULL, @WE2 INT NULL)
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BUSINESSDATEWE]

