CREATE AGGREGATE [wct].[CFMDURATION](@Disc_rate FLOAT (53) NULL, @VDate DATETIME NULL, @CFamt FLOAT (53) NULL, @CFdate DATETIME NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.CFMDURATION];

