CREATE AGGREGATE [wct].[CHITESTN](@expr1 NVARCHAR (4000) NULL, @expr2 NVARCHAR (4000) NULL, @obs FLOAT (53) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.CHITESTN];

