CREATE FUNCTION [wct].[CONFIDENCE_NORM]
(@Alpha FLOAT (53) NULL, @Standard_dev FLOAT (53) NULL, @Size FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[CONFIDENCE_NORM]

