CREATE FUNCTION [wct].[DAYS360]
(@StartDate DATETIME NULL, @EndDate DATETIME NULL, @Method INT NULL)
RETURNS INT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[DAYS360]

