CREATE FUNCTION [wct].[DB]
(@Cost FLOAT (53) NULL, @Salvage FLOAT (53) NULL, @Life FLOAT (53) NULL, @Per FLOAT (53) NULL, @Month FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[DB]

