CREATE AGGREGATE [wct].[DFINTERP](@DFdate DATETIME NULL, @DF FLOAT (53) NULL, @NewDate DATETIME NULL, @StartDate DATETIME NULL, @RV NVARCHAR (4000) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.DFINTERP];

