CREATE FUNCTION [wct].[ED_FUT_CONV_ADJ_HL]
(@Price FLOAT (53) NULL, @Vol FLOAT (53) NULL, @T1 FLOAT (53) NULL, @T2 FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ED_FUT_CONV_ADJ_HL]

