CREATE AGGREGATE [wct].[EQVOLATILITY](@PDate DATETIME NULL, @PValue FLOAT (53) NULL, @Scale FLOAT (53) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.EQVOLATILITY];

