CREATE FUNCTION [wct].[EXPONDIST]
(@X FLOAT (53) NULL, @Lambda FLOAT (53) NULL, @Cumulative BIT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[EXPONDIST]

