CREATE FUNCTION [wct].[EXPPRED]
(@Coef NVARCHAR (MAX) NULL, @New_x NVARCHAR (MAX) NULL, @UseNames BIT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[EXPPRED]

