CREATE FUNCTION [wct].[F_INV_RT]
(@p FLOAT (53) NULL, @df1 FLOAT (53) NULL, @df2 FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[F_INV_RT]

