CREATE FUNCTION [wct].[FACTORIALPOWER]
(@x INT NULL, @n INT NULL, @h INT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[FACTORIALPOWER]

