CREATE FUNCTION [wct].[GAMMADIST]
(@X FLOAT (53) NULL, @Alpha FLOAT (53) NULL, @BETA FLOAT (53) NULL, @Cumulative BIT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[GAMMADIST]

