CREATE FUNCTION [wct].[GESTEP]
(@Number FLOAT (53) NULL, @Step_value FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[GESTEP]

