CREATE FUNCTION [wct].[HESSIAN]
(@Func NVARCHAR (MAX) NULL, @VarNames NVARCHAR (4000) NULL, @X NVARCHAR (4000) NULL, @H FLOAT (53) NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[HESSIAN]

