CREATE FUNCTION [wct].[IAM]
(@A FLOAT (53) NULL, @B FLOAT (53) NULL, @D_IM FLOAT (53) NULL, @DSM FLOAT (53) NULL, @R FLOAT (53) NULL, @P FLOAT (53) NULL, @Y FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[IAM]

