CREATE FUNCTION [wct].[ICC]
(@InputData_RangeQuery NVARCHAR (MAX) NULL, @TypeTest NVARCHAR (4000) NULL, @Alpha FLOAT (53) NULL, @R0 FLOAT (53) NULL, @RV NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ICC]

