CREATE FUNCTION [wct].[IIFSTR]
(@Condition BIT NULL, @TrueValue NVARCHAR (MAX) NULL, @FalseValue NVARCHAR (MAX) NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[IIFSTR]

