CREATE FUNCTION [wct].[INSTRREV]
(@Text NVARCHAR (MAX) NULL, @SearchString NVARCHAR (MAX) NULL, @Start INT NULL, @CaseSensitive BIT NULL)
RETURNS INT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[INSTRREV]

