CREATE AGGREGATE [wct].[INTERP2](@X FLOAT (53) NULL, @Y FLOAT (53) NULL, @Z FLOAT (53) NULL, @New_x FLOAT (53) NULL, @New_y FLOAT (53) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.INTERP2];

