CREATE AGGREGATE [wct].[IPR](@x FLOAT (53) NULL, @kl FLOAT (53) NULL, @ku FLOAT (53) NULL, @mthd NVARCHAR (4000) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.IPR];

