CREATE FUNCTION [wct].[ISREGULARPAY]
(@IssueDate DATETIME NULL, @FirstPaymentDate DATETIME NULL, @PmtPerYear INT NULL)
RETURNS BIT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ISREGULARPAY]

