CREATE FUNCTION [wct].[KAPPA_COHEN]
(@InputData_RangeQuery NVARCHAR (MAX) NULL, @RV NVARCHAR (4000) NULL, @Weighting NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[KAPPA_COHEN]

