CREATE FUNCTION [wct].[KENDALLW]
(@InputData_RangeQuery NVARCHAR (MAX) NULL, @CorrectTies BIT NULL, @RV NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[KENDALLW]

