CREATE FUNCTION [wct].[LESSEROF]
(@Val1 SQL_VARIANT NULL, @Val2 SQL_VARIANT NULL)
RETURNS SQL_VARIANT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[LESSEROF]

