CREATE FUNCTION [wct].[LOGITPRED]
(@B NVARCHAR (MAX) NULL, @New_x NVARCHAR (MAX) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[LOGITPRED]

