CREATE FUNCTION [wct].[MCNEMAR]
(@InputData_RangeQuery NVARCHAR (MAX) NULL, @Correct BIT NULL, @RV NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[MCNEMAR]

