CREATE FUNCTION [wct].[MCOLUMN]
(@Matrix NVARCHAR (MAX) NULL, @n INT NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[MCOLUMN]

