CREATE FUNCTION [wct].[NCTCDF]
(@X FLOAT (53) NULL, @DF FLOAT (53) NULL, @Delta FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[NCTCDF]

