CREATE FUNCTION [wct].[NELSONSIEGEL]
(@Maturity FLOAT (53) NULL, @B0 FLOAT (53) NULL, @B1 FLOAT (53) NULL, @B2 FLOAT (53) NULL, @Tau FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[NELSONSIEGEL]

