CREATE FUNCTION [wct].[NETWORKDAYS_q]
(@StartDate DATETIME NULL, @EndDate DATETIME NULL, @HolidayDates_RangeQuery NVARCHAR (MAX) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[NETWORKDAYS_q]

