CREATE FUNCTION [wct].[NEWTON]
(@Func NVARCHAR (MAX) NULL, @VarName NVARCHAR (4000) NULL, @X FLOAT (53) NULL, @DFunc NVARCHAR (MAX) NULL, @MaxIter INT NULL, @tol FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[NEWTON]

