CREATE AGGREGATE [wct].[NMATRIX2STRING](@Row INT NULL, @Col INT NULL, @Value FLOAT (53) NULL)
    RETURNS NVARCHAR (MAX)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.NMATRIX2STRING];

