CREATE FUNCTION [wct].[NPD]
(@SettDate DATETIME NULL, @FirstPayDate DATETIME NULL, @Pmtpyr INT NULL, @NumPmts INT NULL)
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[NPD]

