CREATE FUNCTION [wct].[PARSE]
(@Text NVARCHAR (MAX) NULL, @Delimiters NVARCHAR (4000) NULL, @WordNo INT NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PARSE]

