CREATE FUNCTION [wct].[PCT2FRAC]
(@Number FLOAT (53) NULL, @Digits INT NULL)
RETURNS NVARCHAR (4000)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PCT2FRAC]

