CREATE FUNCTION [wct].[PERCENTILE_q]
(@Values_RangeQuery NVARCHAR (MAX) NULL, @K FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PERCENTILE_q]

