CREATE FUNCTION [wct].[PERCENTRANK_q]
(@Values_RangeQuery NVARCHAR (MAX) NULL, @X FLOAT (53) NULL, @Significance FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PERCENTRANK_q]

