CREATE FUNCTION [wct].[POISSON_DIST]
(@X FLOAT (53) NULL, @Mean FLOAT (53) NULL, @Cumulative BIT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[POISSON_DIST]

