CREATE FUNCTION [wct].[PPNO]
(@SettDate DATETIME NULL, @FirstPayDate DATETIME NULL, @pmtpyr INT NULL, @NumPmts INT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PPNO]

