CREATE FUNCTION [wct].[PSIGNRANK]
(@X FLOAT (53) NULL, @N FLOAT (53) NULL, @Exact BIT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PSIGNRANK]

