CREATE FUNCTION [wct].[QR]
(@Matrix NVARCHAR (MAX) NULL, @MatrixName NVARCHAR (4000) NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[QR]

