CREATE FUNCTION [wct].[QUADDE]
(@Func NVARCHAR (MAX) NULL, @VarName NVARCHAR (4000) NULL, @A SQL_VARIANT NULL, @B SQL_VARIANT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[QUADDE]

