CREATE AGGREGATE [wct].[RANKAVG](@number FLOAT (53) NULL, @x FLOAT (53) NULL, @order INT NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.RANKAVG];

