CREATE FUNCTION [wct].[RPI]
(@A FLOAT (53) NULL, @DSC FLOAT (53) NULL, @E FLOAT (53) NULL, @N FLOAT (53) NULL, @R FLOAT (53) NULL, @Y FLOAT (53) NULL, @P FLOAT (53) NULL, @F INT NULL, @RV FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[RPI]

