CREATE FUNCTION [wct].[SPEARMAN]
(@x_y_Query NVARCHAR (MAX) NULL, @RV NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[SPEARMAN]

