CREATE FUNCTION [wct].[SPECRAD]
(@MatrixQuery NVARCHAR (MAX) NULL, @IS3N BIT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[SPECRAD]

