CREATE FUNCTION [wct].[SUBSTITUTE]
(@Text NVARCHAR (MAX) NULL, @Old_text NVARCHAR (MAX) NULL, @New_text NVARCHAR (MAX) NULL, @Instance_num INT NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[SUBSTITUTE]

