CREATE FUNCTION [wct].[TBILLYIELD]
(@Settlement DATETIME NULL, @Maturity DATETIME NULL, @Pr FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[TBILLYIELD]

