CREATE FUNCTION [wct].[TBILLEQ]
(@Settlement DATETIME NULL, @Maturity DATETIME NULL, @Discount FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[TBILLEQ]

