CREATE FUNCTION [wct].[TENOR2DATE]
(@Tenor NVARCHAR (4000) NULL, @StartDate DATETIME NULL, @SpotDate DATETIME NULL, @Holidays NVARCHAR (MAX) NULL)
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[TENOR2DATE]

