CREATE AGGREGATE [wct].[TTEST_PAIRED](@X1 FLOAT (53) NULL, @X2 FLOAT (53) NULL, @Statistic NVARCHAR (4000) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.TTEST_PAIRED];

