CREATE AGGREGATE [wct].[TWROR](@CF FLOAT (53) NULL, @CFdate DATETIME NULL, @TType NVARCHAR (4000) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.TWROR];

