CREATE FUNCTION [wct].[UNIFORMINV]
(@P FLOAT (53) NULL, @Min FLOAT (53) NULL, @Max FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[UNIFORMINV]

