CREATE FUNCTION [wct].[WEIBULL]
(@X FLOAT (53) NULL, @Alpha FLOAT (53) NULL, @Beta FLOAT (53) NULL, @Cumulative BIT NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[WEIBULL]

