CREATE FUNCTION [wct].[WORKDAY_q]
(@StartDate DATETIME NULL, @Days INT NULL, @HolidayDates_RangeQuery NVARCHAR (MAX) NULL)
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[WORKDAY_q]

