CREATE FUNCTION [wct].[XLDB_SUITEPLUS_VERSION]
(@InfoType NVARCHAR (4000) NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[XLDB_SUITEPLUS_VERSION]

