CREATE AGGREGATE [wct].[XNPV](@Disc_rate FLOAT (53) NULL, @CF_Amt FLOAT (53) NULL, @CF_Date DATETIME NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.XNPV];

