CREATE FUNCTION [wct].[XPV]
(@Rate FLOAT (53) NULL, @StartDate DATETIME NULL, @EndDate DATETIME NULL, @Cashflow FLOAT (53) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[XPV]

