CREATE FUNCTION [wct].[YIELDDISC]
(@Settlement DATETIME NULL, @Maturity DATETIME NULL, @Pr FLOAT (53) NULL, @Redemption FLOAT (53) NULL, @Basis NVARCHAR (4000) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[YIELDDISC]

