CREATE FUNCTION [wct].[ZEROCOUPON]
(@InputData_RangeQuery NVARCHAR (MAX) NULL, @vDate DATETIME NULL, @ReturnValue NVARCHAR (4000) NULL, @StartDate DATETIME NULL, @Frequency FLOAT (53) NULL, @SpotDate DATETIME NULL, @CashBasis NVARCHAR (4000) NULL, @FuturesBasis NVARCHAR (4000) NULL, @SwapsBasis NVARCHAR (4000) NULL, @InterpMethod NVARCHAR (4000) NULL, @DateRoll NVARCHAR (4000) NULL, @Holidays NVARCHAR (MAX) NULL)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ZEROCOUPON]

