CREATE AGGREGATE [wct].[ZTEST](@known_x FLOAT (53) NULL, @mu FLOAT (53) NULL, @sigma FLOAT (53) NULL)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.ZTEST];

