
CREATE VIEW [Reporting].Matrix_AccountPriorityVw
AS

With SFAccountLockedPriority
AS
(
	SELECT ACCSALESFORCEID,
		   ACCSIVID,
		   ACCMATRIXOUTLETID,
		   ACCPARENTSIVID,
		   ACCOWNERID,
		   ACCOWNERNAME,
		   ACCNAME,
		   ACCOUTLETTYPE,
		   ACCBILLINGSTREET,
		   ACCBILLINGCITY,
		   ACCBILLINGSTATE,
		   ACCBILLINGPOSTCODE,
		   ACCBILLINGCOUNTRY,
		   ACCLANDLINE,
		   ACCFAX,
		   ACCWEBSITE,
		   ACCEMAIL,
		   ACCFIRMSEGMENT,
		   ACCPLATFORMSUSED,
		   ACCAUTHSTATUS,
		   MX_PRIMARY_BUSINESS				as PRIMARYBUSINESS,
		   ACCVERIFIEDBY,
		   ACCEXISTINGCOMPANYRELATIONSHIP,
		   ACCPRIORITYCLIENT,
		   ACCISLOCKED
	FROM [STAGING.SALESFORCE.BP].[SFACCOUNTRAW]
	WHERE (ACCPRIORITYCLIENT = 'TRUE'
	OR ACCISLOCKED = 'TRUE')
),
MXAccount
AS
(
	SELECT SALESFORCE_ACCOUNT_ID			as ACCSALESFORCEID,
		   MX_MATRIX_ACCOUNT_SIV_ID			as ACCSIVID,
		   MX_MATRIX_OUTLET_ID				as ACCMATRIXOUTLETID,
		   MX_PARENT_ACCOUNT_SIV_ID			as ACCPARENTSIVID,
		   MX_OWNER_ID						as ACCOWNERID,
		   MX_OWNER_NAME					as ACCOWNERNAME,
		   MX_NAME							as ACCNAME,
		   MX_OUTLET_TYPE					as ACCOUTLETTYPE,
		   MX_BILLINGSTREET					as ACCBILLINGSTREET,
		   MX_BILLINGCITY					as ACCBILLINGCITY,
		   MX_BILLINGSTATE					as ACCBILLINGSTATE,
		   MX_POSTALCODE					as ACCBILLINGPOSTCODE,
		   MX_COUNTRY						as ACCBILLINGCOUNTRY,
		   MX_PHONE							as ACCLANDLINE,
		   MX_FAX							as ACCFAX,
		   MX_WEBSITE						as ACCWEBSITE,
		   MX_FIRM_SEGMENT					as ACCFIRMSEGMENT,
		   MX_PLATFORMS_USED				as ACCPLATFORMSUSED,
		   MX_AUTHORISATION_STATUS			as ACCAUTHSTATUS,
		   MX_PRIMARY_BUSINESS				as PRIMARYBUSINESS,
		   MX_VERIFIED_BY					as ACCVERIFIEDBY,
		   MX_EXISTING_COMPANY_RELATIONSHIP	as ACCEXISTINGCOMPANYRELATIONSHIP,
		   MX_ACCOUNT_FSR_FRN				as ACCOUNTFSRFRN,
		   AS_AT_DATE						as ASATDATE
	FROM [dbo].[T_MATRIX_ACCOUNT]
)
SELECT MX.* FROM SFAccountLockedPriority SF
INNER JOIN MXAccount MX
ON SF.ACCSIVID = MX.ACCSIVID