CREATE VIEW Reporting.vw_Security_Risk_Metrics
AS
SELECT
  D_Date,
  C_SECURITY,
  PX_LAST,
  VOLUME,
  PE_RATIO,
  PX_TO_BOOK_RATIO,
  FREE_CASH_FLOW_YIELD,
  EQY_DVD_YLD_12M,
  PX_TO_SALES_RATIO,
  [6MO_CALL_IMP_VOL],
  [12MO_CALL_IMP_VOL],
  REL_SHR_PX_MOMENTUM,
  PX_CLOSE_1D,
  TURNOVER,
  VWAP_AUTOMATED_VOLUME,
  VWAP_LIT_VOLUME,
  [CFWEIAA LN Equity],
  [CWHIAGA LN Equity],
  [WPCT LN Equity],
  [CO1 Comdty],
  [XAU BGN Curncy],
  [HG1 COMB Comdty],
  [RBT1 COMB Comdty],
  [API2YR1 Equity],
  [ASX Equity],
  [CRB RIND Equity],
  [EUCRBRDT Equity],
  [GUKG10 Equity],
  [MCX Index],
  [NKY Index],
  [NYM1CNCN Index],
  [SHCOMP Equity],
  [SPX Index],
  [SX5E Equity],
  [UKX Index],
  [USGG10YR Equity],
  [GBPUSD Equity],
  [XAG BGN Curncy],
  [XPT BGN Curncy]
FROM [dbo].[T_Security_Risk_Metrics]
