
CREATE VIEW [Reporting].[vw_Trade_Security_Risk_Metrics_Raw]
AS
SELECT
	A.D_DATE, A.C_SECURITY, A.C_SIDE, A.I_TSORDNUM
	,A.F_FULLQUANTITY AS F_FULLQUANTITY
	,A.F_PRINCIPAL AS F_PRINCIPAL
	,A.F_QUANTITY AS F_QUANTITY
	,A.F_PRICE AS F_PRICE
	,A.C_CURRENCY AS C_CURRENCY
	, ISNULL(CONVERT(varchar(50), M.[PX_LAST]), '') AS [PX_LAST]
	, ISNULL(CONVERT(varchar(50), M.[VOLUME]), '') AS [VOLUME]
	, ISNULL(CONVERT(varchar(50), M.[PE_RATIO]), '') AS [PE_RATIO]
	, ISNULL(CONVERT(varchar(50), M.[PX_TO_BOOK_RATIO]), '') AS [PX_TO_BOOK_RATIO]
	, ISNULL(CONVERT(varchar(50), M.[FREE_CASH_FLOW_YIELD]), '') AS [FREE_CASH_FLOW_YIELD]
	, ISNULL(CONVERT(varchar(50), M.[EQY_DVD_YLD_12M]), '') AS [EQY_DVD_YLD_12M]
	, ISNULL(CONVERT(varchar(50), M.[PX_TO_SALES_RATIO]), '') AS [PX_TO_SALES_RATIO]
	, ISNULL(CONVERT(varchar(50), M.[6MO_CALL_IMP_VOL]), '') AS [6MO_CALL_IMP_VOL]
	, ISNULL(CONVERT(varchar(50), M.[12MO_CALL_IMP_VOL]), '') AS [12MO_CALL_IMP_VOL]
	, ISNULL(CONVERT(varchar(50), M.[REL_SHR_PX_MOMENTUM]), '') AS [REL_SHR_PX_MOMENTUM]
	, ISNULL(CONVERT(varchar(50), M.[PX_CLOSE_1D]), '') AS [PX_CLOSE_1D]
	, ISNULL(CONVERT(varchar(50), M.[TURNOVER]), '') AS [TURNOVER]
	, ISNULL(CONVERT(varchar(50), M.[VWAP_AUTOMATED_VOLUME]), '') AS [VWAP_AUTOMATED_VOLUME]
	, ISNULL(CONVERT(varchar(50), M.[VWAP_LIT_VOLUME]), '') AS [VWAP_LIT_VOLUME]
	, M.[CFWEIAA LN Equity] AS [CFWEIAA LN Equity]
	, M.[CWHIAGA LN Equity] AS [CWHIAGA LN Equity]
	, M.[WPCT LN Equity] AS [WPCT LN Equity]
	, M.[CO1 Comdty] AS [CO1 Comdty]
	, M.[XAU BGN Curncy] AS [XAU BGN Curncy]
	, M.[HG1 COMB Comdty] AS [HG1 COMB Comdty]
	, M.[RBT1 COMB Comdty] AS [RBT1 COMB Comdty]
	, M.[API2YR1 Equity] AS [API2YR1 Equity]
	, M.[ASX Equity] AS [ASX Equity]
	, M.[CRB RIND Equity] AS [CRB RIND Equity]
	, M.[EUCRBRDT Equity] AS [EUCRBRDT Equity]
	, M.[GUKG10 Equity] AS [GUKG10 Equity]
	, M.[MCX Index] AS [MCX Index]
	, M.[NKY Index] AS [NKY Index]
	, M.[NYM1CNCN Index] AS [NYM1CNCN Index]
	, M.[SHCOMP Equity] AS [SHCOMP Equity]
	, M.[SPX Index] AS [SPX Index]
	, M.[SX5E Equity] AS [SX5E Equity]
	, M.[UKX Index] AS [UKX Index]
	, M.[USGG10YR Equity] AS [USGG10YR Equity]
	, ISNULL(CONVERT(varchar(50), M.[GBPUSD Equity]), '') AS [GBPUSD Equity]
	, M.[XAG BGN Curncy] AS [XAG BGN Curncy]
	, M.[XPT BGN Curncy] AS [XPT BGN Curncy]
	, ISNULL(S.BBG_Sector, '') AS BBG_Sector
	, ISNULL(S.BBG_Group, '')  AS BBG_Group
	, ISNULL(S.RISK_ISO_CTY, '') AS RISK_ISO_CTY
	, ISNULL(A.C_REASONCODE, '') AS C_REASONCODE
	, ISNULL(M.CURRENT_EV_TO_T12M_EBITDA, '') AS CURRENT_EV_TO_T12M_EBITDA
FROM 
	[dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT] A
LEFT OUTER  JOIN 
	[dbo].[T_Security_Risk_Metrics] M ON A.D_Date = M.[D_Date] AND A.C_SECURITY = M.C_SECURITY
LEFT OUTER JOIN 
	[dbo].[T_MASTER_SEC] S ON A.C_SECURITY + ' Equity' = S.PARSEKEYABLE_DESCRIPTION
WHERE A.c_event in ('ORDER ALLOCATED')