
CREATE VIEW [Reporting].[vw_Trade_Security_Risk_Metrics]
AS
SELECT
	A.D_DATE, A.C_SECURITY, A.C_SIDE
	,SUM(A.F_FULLQUANTITY) AS F_FULLQUANTITY
	,SUM(A.F_PRINCIPAL) AS F_PRINCIPAL
	,SUM(A.F_QUANTITY) AS F_QUANTITY
	,AVG(A.F_PRICE) AS F_PRICE
	,MIN(A.C_CURRENCY) AS C_CURRENCY
	, MIN(ISNULL(CONVERT(varchar(50), M.[PX_LAST]), '')) AS [PX_LAST]
	, MIN(ISNULL(CONVERT(varchar(50), M.[VOLUME]), '')) AS [VOLUME]
	, MIN(ISNULL(CONVERT(varchar(50), M.[PE_RATIO]), '')) AS [PE_RATIO]
	, MIN(ISNULL(CONVERT(varchar(50), M.[PX_TO_BOOK_RATIO]), '')) AS [PX_TO_BOOK_RATIO]
	, MIN(ISNULL(CONVERT(varchar(50), M.[FREE_CASH_FLOW_YIELD]), '')) AS [FREE_CASH_FLOW_YIELD]
	, MIN(ISNULL(CONVERT(varchar(50), M.[EQY_DVD_YLD_12M]), '')) AS [EQY_DVD_YLD_12M]
	, MIN(ISNULL(CONVERT(varchar(50), M.[PX_TO_SALES_RATIO]), '')) AS [PX_TO_SALES_RATIO]
	, MIN(ISNULL(CONVERT(varchar(50), M.[6MO_CALL_IMP_VOL]), '')) AS [6MO_CALL_IMP_VOL]
	, MIN(ISNULL(CONVERT(varchar(50), M.[12MO_CALL_IMP_VOL]), '')) AS [12MO_CALL_IMP_VOL]
	, MIN(ISNULL(CONVERT(varchar(50), M.[REL_SHR_PX_MOMENTUM]), '')) AS [REL_SHR_PX_MOMENTUM]
	, MIN(ISNULL(CONVERT(varchar(50), M.[PX_CLOSE_1D]), '')) AS [PX_CLOSE_1D]
	, MIN(ISNULL(CONVERT(varchar(50), M.[TURNOVER]), '')) AS [TURNOVER]
	, MIN(ISNULL(CONVERT(varchar(50), M.[VWAP_AUTOMATED_VOLUME]), '')) AS [VWAP_AUTOMATED_VOLUME]
	, MIN(ISNULL(CONVERT(varchar(50), M.[VWAP_LIT_VOLUME]), '')) AS [VWAP_LIT_VOLUME]
	, MIN(M.[CFWEIAA LN Equity]) AS [CFWEIAA LN Equity]
	, MIN(M.[CWHIAGA LN Equity]) AS [CWHIAGA LN Equity]
	, MIN(M.[WPCT LN Equity]) AS [WPCT LN Equity]
	, MIN(M.[CO1 Comdty]) AS [CO1 Comdty]
	, MIN(M.[XAU BGN Curncy]) AS [XAU BGN Curncy]
	, MIN(M.[HG1 COMB Comdty]) AS [HG1 COMB Comdty]
	, MIN(M.[RBT1 COMB Comdty]) AS [RBT1 COMB Comdty]
	, MIN(M.[API2YR1 Equity]) AS [API2YR1 Equity]
	, MIN(M.[ASX Equity]) AS [ASX Equity]
	, MIN(M.[CRB RIND Equity]) AS [CRB RIND Equity]
	, MIN(M.[EUCRBRDT Equity]) AS [EUCRBRDT Equity]
	, MIN(M.[GUKG10 Equity]) AS [GUKG10 Equity]
	, MIN(M.[MCX Index]) AS [MCX Index]
	, MIN(M.[NKY Index]) AS [NKY Index]
	, MIN(M.[NYM1CNCN Index]) AS [NYM1CNCN Index]
	, MIN(M.[SHCOMP Equity]) AS [SHCOMP Equity]
	, MIN(M.[SPX Index]) AS [SPX Index]
	, MIN(M.[SX5E Equity]) AS [SX5E Equity]
	, MIN(M.[UKX Index]) AS [UKX Index]
	, MIN(M.[USGG10YR Equity]) AS [USGG10YR Equity]
	, MIN(ISNULL(CONVERT(varchar(50), M.[GBPUSD Equity]), '')) AS [GBPUSD Equity]
	, MIN(M.[XAG BGN Curncy]) AS [XAG BGN Curncy]
	, MIN(M.[XPT BGN Curncy]) AS [XPT BGN Curncy]
	, MIN(ISNULL(S.BBG_Sector, '')) AS BBG_Sector
	, MIN(ISNULL(S.BBG_Group, '') ) AS BBG_Group
	, MIN(ISNULL(S.RISK_ISO_CTY, '')) AS RISK_ISO_CTY
	, MIN(ISNULL(M.CURRENT_EV_TO_T12M_EBITDA, '')) AS CURRENT_EV_TO_T12M_EBITDA
FROM 
	[dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT] A
LEFT OUTER  JOIN 
	[dbo].[T_Security_Risk_Metrics] M ON A.D_Date = M.[D_Date] AND A.C_SECURITY = M.C_SECURITY
LEFT OUTER JOIN 
	[dbo].[T_MASTER_SEC] S ON A.C_SECURITY + ' Equity' = S.PARSEKEYABLE_DESCRIPTION
WHERE A.c_event in ('ORDER ALLOCATED')
AND ISNULL(A.C_REASONCODE, '') NOT IN ('5') -- Exclude cross-trades
GROUP BY 
	A.D_DATE, A.C_SECURITY, A.C_SIDE