CREATE VIEW [Access.ManyWho].[BPSFundDividendRatesYearlySummaryVw]
AS
--/******************************
--** Desc:
--** Auth: R.Dixon
--** Date: 25/04/2018
--**************************
--** Change History
--**************************
--** JIRA		  Date		  Author	Description 
--** ----		  ----------  -------	------------------------------------
--** DAP-1836     25/04/2018  R.Dixon	Replaces [Access.ManyWho].[DividendsQuarterlySummaryVw] by extracting from table of calculated values
--*******************************/

SELECT	T.FUND_SHORT_NAME,
		T.INCOME_PERIOD_YR,
		MAX(T.AS_AT_DATE) AS AS_AT_DATE,
		MAX(T.FUND_DVD_RATE_PER_YEAR) AS FUND_DVD_RATE_PER_YEAR,
		MAX(Y.FUND_DVD_RATE_PER_YEAR) AS FUND_DVD_RATE_PER_YEAR_PREV,
		MAX(T.FUND_DVD_RATE_PER_YEAR) - MAX(Y.FUND_DVD_RATE_PER_YEAR) AS FUND_DVD_RATE_PER_YEAR_CHG,
		MAX(T.CADIS_SYSTEM_INSERTED) AS CADIS_SYSTEM_INSERTED,
		MAX(T.CADIS_SYSTEM_UPDATED) AS CADIS_SYSTEM_UPDATED,
		MAX(T.CADIS_SYSTEM_CHANGEDBY) AS CADIS_SYSTEM_CHANGEDBY
FROM	[dbo].[T_BPS_DVD_QTR_SUMMARY] T
LEFT	OUTER JOIN 
		(
		SELECT	FUND_SHORT_NAME,
				INCOME_PERIOD_YR,
				MAX(FUND_DVD_RATE_PER_YEAR) AS FUND_DVD_RATE_PER_YEAR,
				MAX(CADIS_SYSTEM_INSERTED) AS CADIS_SYSTEM_INSERTED,
				MAX(CADIS_SYSTEM_UPDATED) AS CADIS_SYSTEM_UPDATED,
				MAX(CADIS_SYSTEM_CHANGEDBY) AS CADIS_SYSTEM_CHANGEDBY
		FROM	[dbo].[T_BPS_DVD_QTR_SUMMARY]
		WHERE	AS_AT_DATE = (SELECT	MAX(AS_AT_DATE)
									FROM	[DBO].[T_BPS_DVD_QTR_SUMMARY]
									WHERE	AS_AT_DATE NOT IN
											(SELECT	MAX(AS_AT_DATE)
											FROM	[DBO].[T_BPS_DVD_QTR_SUMMARY]
											)
								)
		GROUP	BY FUND_SHORT_NAME, INCOME_PERIOD_YR
		) Y
ON		T.FUND_SHORT_NAME = Y.FUND_SHORT_NAME
AND		T.INCOME_PERIOD_YR = Y.INCOME_PERIOD_YR
WHERE	AS_AT_DATE = (SELECT	MAX(AS_AT_DATE)
						FROM	[DBO].[T_BPS_DVD_QTR_SUMMARY]
					)
GROUP	BY T.FUND_SHORT_NAME, T.INCOME_PERIOD_YR

