


CREATE VIEW
[Access.ManyWho].[CircleProcessScheduledTasks]
AS
SELECT
	 CPST.[Id]
	,CPST.[CircleProcessId]
	,CP.[Name] AS CircleProcessName
    ,CPST.[Frequency]
	,CPST.[FrequencyDay]
	,CPST.[FrequencyStart]
	,CONVERT(date,
	 CASE   
		WHEN Frequency = 'Daily'         THEN GETDATE()
		WHEN Frequency = 'Weekdays'      THEN CASE WHEN DATEPART(WEEKDAY, GETDATE()) = '7' THEN DATEADD(day, -1, GETDATE()) WHEN DATEPART(WEEKDAY, GETDATE() ) = '1' THEN DATEADD(day, -2, GETDATE()) ELSE GETDATE() END
		WHEN Frequency = 'Weekends'      THEN CASE WHEN DATEPART(WEEKDAY, GETDATE()) in ('2','3','4','5','6') THEN GETDATE() - DATEPART(WEEKDAY, GETDATE()) + 1 ELSE GETDATE() END
		WHEN Frequency = 'Weekly'        THEN CASE WHEN DATEPART(WEEKDAY, GETDATE()) > FrequencyDay THEN GETDATE() - DATEPART(WEEKDAY, GETDATE()) + FrequencyDay WHEN DATEPART(WEEKDAY, GETDATE() ) < FrequencyDay THEN GETDATE() - DATEPART(WEEKDAY, GETDATE()) + FrequencyDay - 7 ELSE GETDATE() END
		WHEN Frequency = 'Bi-Weekly'     THEN CASE WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay > DATEPART(WEEKDAY, GETDATE()) THEN DATEADD(day, -(14 + DATEPART(WEEKDAY, GETDATE()) - FrequencyDay), GETDATE()) WHEN FrequencyDay < DATEPART(WEEKDAY, GETDATE()) THEN DATEADD(day, -(DATEPART(WEEKDAY, GETDATE()) - FrequencyDay), GETDATE()) ELSE GETDATE() END WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay != DATEPART(WEEKDAY, GETDATE()) THEN DATEADD(day, -(7 + DATEPART(WEEKDAY, GETDATE()) - FrequencyDay), GETDATE()) ELSE DATEADD(day, -7, GETDATE()) END ELSE NULL END
		WHEN Frequency = 'Monthly'       THEN CASE WHEN DATEPART(DAY, GETDATE()) > FrequencyDay THEN DATEFROMPARTS(year(GETDATE()), month(GETDATE()), FrequencyDay) WHEN DATEPART(DAY, GETDATE() ) < FrequencyDay THEN DATEFROMPARTS(year(DATEADD(month, -1, GETDATE())), month(DATEADD(month, -1, GETDATE())), FrequencyDay) ELSE GETDATE() END
		WHEN Frequency = 'Bi-Monthly'    THEN CASE WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay > DATEPART(DAY, GETDATE()) THEN DATEFROMPARTS(year(DATEADD(month, -2, GETDATE())), month(DATEADD(month, -2, GETDATE())), FrequencyDay) WHEN FrequencyDay < DATEPART(DAY, GETDATE()) THEN DATEFROMPARTS(year(GETDATE()), month(GETDATE()), FrequencyDay) ELSE GETDATE() END WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay != DATEPART(DAY, GETDATE()) THEN DATEFROMPARTS(year(DATEADD(month, -1, GETDATE())), month(DATEADD(month, -1, GETDATE())), FrequencyDay) ELSE DATEFROMPARTS(year(DATEADD(month, -1, GETDATE())), month(DATEADD(month, -1, GETDATE())), FrequencyDay) END ELSE NULL END
		WHEN Frequency = 'Quarterly'     THEN CASE WHEN (DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) =  FrequencyStart) OR DATEPART(MONTH, GETDATE()) <  FrequencyStart THEN DATEFROMPARTS(year(DATEADD(year,-1,GETDATE())),FrequencyStart,FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) =  FrequencyStart) OR DATEPART(MONTH, GETDATE()) > FrequencyStart) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 3)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 3)) THEN DATEFROMPARTS(year(GETDATE()),FrequencyStart,FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 3)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 3)) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 6)) THEN DATEFROMPARTS(year(GETDATE()),FrequencyStart + 3,FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 6)) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 9)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 9)) THEN DATEFROMPARTS(year(GETDATE()),FrequencyStart + 6,FrequencyDay) WHEN (DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 9)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 9) THEN DATEFROMPARTS(year(GETDATE()),FrequencyStart + 9,FrequencyDay) ELSE GETDATE() END
		WHEN Frequency = 'Semi-Annually' THEN CASE WHEN (DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) < FrequencyStart THEN DATEFROMPARTS(year(DATEADD(year, -1, GETDATE())), FrequencyStart + 6, FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) > FrequencyStart) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 6)) THEN DATEFROMPARTS(year(GETDATE()), FrequencyStart, FrequencyDay) WHEN  (DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 6) THEN DATEFROMPARTS(year(GETDATE()), FrequencyStart + 6, FrequencyDay) ELSE GETDATE() END
		WHEN Frequency = 'Annually'      THEN CASE WHEN (DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) > FrequencyStart THEN DATEFROMPARTS(year(GETDATE()), FrequencyStart, FrequencyDay) WHEN (DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) < FrequencyStart THEN DATEFROMPARTS(year(DATEADD(year, -1, GETDATE())), FrequencyStart, FrequencyDay) ELSE GETDATE() END
		ELSE NULL
	 END) AS LastRunDate
	,CONVERT(date,
	 CASE 
		WHEN Frequency = 'Daily'         THEN DATEADD(day, 1, GETDATE())
		WHEN Frequency = 'Weekdays'      THEN CASE WHEN DATEPART(WEEKDAY, GETDATE() ) = '6' THEN DATEADD(day, 3, GETDATE()) WHEN DATEPART(WEEKDAY, GETDATE() ) = '7' THEN DATEADD(day, 2, GETDATE()) ELSE DATEADD(day, 1, GETDATE()) END
		WHEN Frequency = 'Weekends'      THEN CASE WHEN DATEPART(WEEKDAY, GETDATE() ) in ('2','3','4','5','6') THEN GETDATE() - DATEPART(WEEKDAY, GETDATE()) + 7 ELSE GETDATE() + 1 END
		WHEN Frequency = 'Weekly'        THEN CASE WHEN DATEPART(WEEKDAY, GETDATE() ) > FrequencyDay THEN GETDATE() - DATEPART(WEEKDAY, GETDATE()) + FrequencyDay + 7 WHEN DATEPART(WEEKDAY, GETDATE() ) < FrequencyDay THEN GETDATE() - DATEPART(WEEKDAY, GETDATE()) + FrequencyDay ELSE GETDATE() + 7 END
		WHEN Frequency = 'Bi-Weekly'     THEN CASE WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay > DATEPART(WEEKDAY, GETDATE()) THEN DATEADD(day, (FrequencyDay - DATEPART(WEEKDAY, GETDATE())), GETDATE()) WHEN FrequencyDay < DATEPART(WEEKDAY, GETDATE()) THEN DATEADD(day, (14 - DATEPART(WEEKDAY, GETDATE()) + FrequencyDay), GETDATE()) ELSE DATEADD(day, 14, GETDATE()) END WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(WEEK, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay != DATEPART(WEEKDAY, GETDATE()) THEN DATEADD(day, (7 - DATEPART(WEEKDAY, GETDATE()) + FrequencyDay), GETDATE()) ELSE DATEADD(day, 7, GETDATE()) END ELSE NULL END
		WHEN Frequency = 'Monthly'       THEN CASE WHEN DATEPART(DAY, GETDATE() ) > FrequencyDay THEN datefromparts(year(DATEADD(month, 1, GETDATE())), month(DATEADD(month, 1, GETDATE())), FrequencyDay) WHEN DATEPART(DAY, GETDATE() ) < FrequencyDay THEN datefromparts(year(GETDATE()), month(GETDATE()), FrequencyDay) ELSE GETDATE() END
		WHEN Frequency = 'Bi-Monthly'    THEN CASE WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay > DATEPART(DAY, GETDATE()) THEN DATEFROMPARTS(year(GETDATE()), month(GETDATE()), FrequencyDay) WHEN FrequencyDay < DATEPART(DAY, GETDATE()) THEN DATEFROMPARTS(year(DATEADD(month, 2, GETDATE())), month(DATEADD(month, 2, GETDATE())), FrequencyDay) ELSE DATEFROMPARTS(year(DATEADD(month, 2, GETDATE())), month(DATEADD(month, 2, GETDATE())), FrequencyDay) END WHEN ((FrequencyStart = '1' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 = ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2))) OR (FrequencyStart = '2' AND (CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2 != ceiling(CAST((DATEPART(MONTH, GetDate())) AS DECIMAL(3,1))/2)))) THEN CASE WHEN FrequencyDay != DATEPART(DAY, GETDATE()) THEN DATEFROMPARTS(year(DATEADD(month, 1, GETDATE())), month(DATEADD(month, 1, GETDATE())), FrequencyDay) ELSE DATEFROMPARTS(year(DATEADD(month, 1, GETDATE())), month(DATEADD(month, 1, GETDATE())), FrequencyDay) END ELSE NULL END
		WHEN Frequency = 'Quarterly'     THEN CASE WHEN (DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) =  FrequencyStart)      OR DATEPART(MONTH, GETDATE()) <  FrequencyStart THEN DATEFROMPARTS(year(DATEADD(year,-1,GETDATE())),FrequencyStart,FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) =  FrequencyStart)      OR DATEPART(MONTH, GETDATE()) > FrequencyStart) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 3)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 3)) THEN DATEFROMPARTS(year(GETDATE()),FrequencyStart + 3,FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 3)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 3)) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 6)) THEN DATEFROMPARTS(year(GETDATE()),FrequencyStart + 6,FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 6)) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 9)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 9)) THEN DATEFROMPARTS(year(GETDATE()),FrequencyStart + 9,FrequencyDay) WHEN (DATEPART(DAY, GETDATE()) > FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 9)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 9) THEN DATEFROMPARTS(year(DATEADD(year,1,GETDATE())),FrequencyStart,FrequencyDay) ELSE DATEFROMPARTS(year(DATEADD(month,3,GETDATE())),month(DATEADD(month,3,GETDATE())),FrequencyDay) END
		WHEN Frequency = 'Semi-Annually' THEN CASE WHEN (DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) < FrequencyStart THEN DATEFROMPARTS(year(GETDATE()), FrequencyStart, FrequencyDay) WHEN ((DATEPART(DAY, GETDATE()) >= FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) > FrequencyStart) AND ((DATEPART(DAY, GETDATE()) < FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) < (FrequencyStart + 6)) THEN DATEFROMPARTS(year(GETDATE()), FrequencyStart + 6, FrequencyDay) WHEN  (DATEPART(DAY, GETDATE()) >= FrequencyDay AND DATEPART(MONTH, GETDATE()) = (FrequencyStart + 6)) OR DATEPART(MONTH, GETDATE()) > (FrequencyStart + 6) THEN DATEFROMPARTS(year(DATEADD(year, 1, GETDATE())), FrequencyStart, FrequencyDay) ELSE GETDATE() END
		WHEN Frequency = 'Annually'      THEN CASE WHEN (DATEPART(DAY, GETDATE()) >= FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) > FrequencyStart THEN DATEFROMPARTS(year(DATEADD(year, 1, GETDATE())), FrequencyStart, FrequencyDay) WHEN (DATEPART(DAY, GETDATE()) <= FrequencyDay AND DATEPART(MONTH, GETDATE()) = FrequencyStart) OR DATEPART(MONTH, GETDATE()) < FrequencyStart THEN DATEFROMPARTS(year(GETDATE()), FrequencyStart, FrequencyDay) ELSE GETDATE() END
		ELSE NULL
	 END) AS NextRunDate
    ,CPST.[ProjectKey]
    ,CPST.[EpicKey]
    ,CPST.[IssueType]
    ,CPST.[ReporterPersonId]
	,P1.[PersonsName] AS ReporterPersonsName
	,P1.[JiraUsername] AS ReporterPersonsJiraUsername
    ,CPST.[AssigneePersonId]
	,P2.PersonsName AS AssigneePersonsName
	,P2.[JiraUsername] AS AssigneePersonsJiraUsername
	,CPST.[DueDateOffset]
    ,CPST.[Summary]
    ,CPST.[Purpose]
    ,CPST.[Outcome]
    ,CPST.[Description]
    ,CPST.[IsActive]
	,CPST.[CADIS_SYSTEM_INSERTED]
	,CPST.[CADIS_SYSTEM_UPDATED]
	,CPST.[CADIS_SYSTEM_CHANGEDBY]
FROM [dbo].[CircleProcessScheduledTasks] CPST
LEFT JOIN [dbo].[CircleProcesses] CP ON CP.Id = CPST.CircleProcessId
LEFT JOIN [Access.ManyWho].[PersonsActiveVw] P1 ON P1.PersonId = CPST.ReporterPersonId
LEFT JOIN [Access.ManyWho].[PersonsActiveVw] P2 ON P2.PersonId = CPST.AssigneePersonId


