CREATE VIEW [Access.ManyWho].[CorporateActionsRegisterVw]
	AS
SELECT CAR.[CorporateActionsRegisterId]
      ,CAR.[OperationsSalesforceId]
      ,CAR.[SecurityNameBK]
      ,CAR.[OperationRoleId]
      ,CAR.[RecorderNameId]
      ,CAR.[FiledDate]
      ,CAR.[ISIN]
      ,CAR.[CorporateActionDate]
      ,CAR.[RecordDate]	  
      ,CAR.[DeadlineDate]
      ,CAR.[InvestmentRoleId]
      ,CAR.[FundManagerSalesforceId]
      ,CAR.[DecisionMakerId]
      ,CAR.[Decision]
	  ,CAR.[OperationsNotes]
	  ,CAR.[InvestmentNotes]
	  ,CAR.[NTReportDocumentationLink]
	  ,CAR.[Status]
	  ,CAR.[EventType]
      ,CAR.[DocumentationFolderLink]
      ,CAR.[WorkflowVersionGUID]
      ,CAR.[JoinGUID]
      ,CAR.[CorporateActionsCreationDatetime]
      ,CAR.[CorporateActionsLastModifiedDatetime]
  FROM [Operation].[CorporateActionsRegister] CAR
  ;
