CREATE view [Access.ManyWho].[FinPromsRegisterActivityChecklistReadOnlyVw]
as
SELECT [FinPromRegisterId]
      ,case [ResultofLegalOrCompliance] when 'Yes' then 1 when 'No' then 0 else null end as [ResultofLegalOrCompliance]
      ,case [AllChannelsExamined] when 'Yes' then 1 when 'No' then 0 else null end as [AllChannelsExamined]
      ,case [ResultOfSpecificClient] when 'Yes' then 1 when 'No' then 0 else null end as [ResultOfSpecificClient]
      ,case [ExpectCompetitorsToDo] when 'Yes' then 1 when 'No' then 0 else null end as [ExpectCompetitorsToDo]
      ,case [StoryboardCompletedApproved] when 'Yes' then 1 when 'No' then 0 else null end as [StoryboardCompletedApproved]
      ,case [ExecuteDifferently] when 'Yes' then 1 when 'No' then 0 else null end as [ExecuteDifferently]
      ,case [ActivityTransformational] when 'Yes' then 1 when 'No' then 0 else null end as [ActivityTransformational]
      ,case [ActivityConsistent] when 'Yes' then 1 when 'No' then 0 else null end as [ActivityConsistent]
      ,case [ValueOutweighsCost] when 'Yes' then 1 when 'No' then 0 else null end as [ValueOutweighsCost]
      ,case [DoOneOrMoreOfThree] when 'Yes' then 1 when 'No' then 0 else null end as [DoOneOrMoreOfThree]
      ,case [ActivityFurthersConversation] when 'Yes' then 1 when 'No' then 0 else null end as [ActivityFurthersConversation]
      ,case [TailoredLanguagePatterns] when 'Yes' then 1 when 'No' then 0 else null end as [TailoredLanguagePatterns]
      ,case [TailoredRespondingSentiment] when 'Yes' then 1 when 'No' then 0 else null end as [TailoredRespondingSentiment]
      ,case [AllCommMethodsEvaluated] when 'Yes' then 1 when 'No' then 0 else null end as [AllCommMethodsEvaluated]
      ,case [StoryboardCompletedApproved2] when 'Yes' then 1 when 'No' then 0 else null end as [StoryboardCompletedApproved2]
      ,case [OptimalTimeToExecute] when 'Yes' then 1 when 'No' then 0 else null end as [OptimalTimeToExecute]
      ,[JoinGUID]
      ,[FinPromsRegisterActivityChecklistCreationDatetime]
      ,[FinPromsRegisterActivityChecklistLastModifiedDatetime]
      ,[CADIS_SYSTEM_INSERTED]
      ,[CADIS_SYSTEM_UPDATED]
      ,[CADIS_SYSTEM_CHANGEDBY]
      ,[CADIS_SYSTEM_PRIORITY]
      ,[CADIS_SYSTEM_TIMESTAMP]
      ,[CADIS_SYSTEM_LASTMODIFIED]
  FROM [Investment].[FinPromsRegisterActivityChecklist]
