CREATE VIEW [Access.ManyWho].[FundManagerSignOffVw]
	AS 
SELECT [FundManagerSignOffId]
      ,[SubmittedByPersonId]
      ,[SubmittedDate]
      ,[ReviewedByPersonId]
      ,[ReviewDate]
      ,[Status]
	  ,[MandateId]
      ,[ValuationDate]
      ,[Notes]
      ,[JiraIssueKey]
	  ,[BoxFolderId]
      ,[DocumentationFolderLink]
      ,[JoinGUID]
      ,[FundManagerSignOffCreationDatetime]
      ,[FundManagerSignOffLastModifiedDatetime]
  FROM [Sales].[FundManagerSignOff]
  ;
