CREATE VIEW [Access.ManyWho].[UnquotedCompanyRevaluationVw]
AS
SELECT 
		[UnquotedCompanyRevaluationId]
	  , [UnquotedCompanyId]
      , [EventType]
	  , [EventOverview]
	  , [EventDate]
      , [FurtherFundingAmount]
	  , [Notes]
      , [BoxUrl]
      , [PresentedToPricingCommitee]
      , [RevaluationPreviousPrice]
      , [RevaluationPrice]
	  , [RevaluationEndDate]
	  , [IsActive]
	  , [Status]
	  , [JiraIssueKey]
	  , [CurrencyCode]
	  , [IsComplete]
      , [WorkflowVersionGUID]
      , [JoinGUID]
      , [UnquotedSecuritiesCreationDate]
      , [UnquotedSecuritiesCreatedByPersonId]
      , [UnquotedSecuritiesLastModifiedDate]
      , [UnquotedSecuritiesLastModifiedByPersonId]
  FROM [Organisation].[UnquotedCompanyRevaluation]
  ;
