CREATE VIEW [Access.ManyWho].[UnquotedSecuritiesVw]
AS

SELECT [UnquotedSecuritiesId]
      ,[UnquotedCompanyId]
      ,[CurrencyCode]
      ,[AssetType]
      ,[StockName]
      ,[ShareClass]
	  ,[Tranche]
      ,[BrokerSalesforceId]
      ,[EstimatedPrice]
      ,[EstimatedPriceDate]
      ,[InitialPrice]
      ,[InitialPriceDate]
      ,[LatestPrice]
      ,[LatestPriceDate]
      ,[ClosingDate]
      ,[CountryOfRisk]
      ,[CountryOfIncorporation]
      ,[BBGSetup]
      ,[Ticker]
      ,[BBGID]
      ,[BBGSecurityId]
      ,[BBGCompanyId]
      ,[NTSent]
      ,[BBGUniqueId/FOID] AS FOID
      ,[CustodianId]
      ,[Notes]
      ,[WorkflowVersionGUID]
      ,[JoinGUID]
      ,[UnquotedSecuritiesCreationDate]
      ,[UnquotedSecuritiesCreatedByPersonId]
      ,[UnquotedSecuritiesLastModifiedDate]
      ,[UnquotedSecuritiesLastModifiedByPersonId]
  FROM [Organisation].[UnquotedSecurities]
