CREATE VIEW [Access.ManyWho].[UnquotedSecuritiesOperationsSetupReadOnlyVw]
AS
SELECT us.[UnquotedSecuritiesId]
      ,us.[UnquotedCompanyId]
	  ,uc.UnquotedCompanyName AS [CompanyName]
      ,uc.[CurrencyCode]
      ,[AssetType]
      ,[StockName]
      ,[ShareClass]
	   ,[Tranche]
      ,[BrokerSalesforceId]
      ,[EstimatedPrice]
      ,[EstimatedPriceDate]
      ,[InitialPrice]
      ,[InitialPriceDate]
      ,[LatestPrice]
      ,[LatestPriceDate]
	  ,fiWEIF.NumberOfShares AS [WEIFNumberOfShares]
	  ,fiWEIF.FundAllocation AS [WEIFFundAllocation]
	  ,fiWPCT.NumberOfShares AS [WPCTNumberOfShares]
	  ,fiWPCT.FundAllocation AS [WPCTFundAllocation]
	  ,fiWEIF.TotalAmountInvested AS [WEIFTotalAmountInvested]
	  ,fiWPCT.TotalAmountInvested AS [WPCTTotalAmountInvested]
	  ,fiWEIF.PercentageHeldAtClosing AS [WEIFPercentHeldAtClosing]
	  ,fiWPCT.PercentageHeldAtClosing AS [WPCTPercentHeldAtClosing]
      ,[ClosingDate]
	  ,p.PersonsName AS [FundManagerCompanyOwner]
      ,[CountryOfRisk]
      ,[CountryOfIncorporation]
      ,[BBGSetup]
      ,[Ticker]
      ,[BBGID]
      ,[BBGSecurityId]
      ,[BBGCompanyId]
      ,[NTSent]
      ,[BBGUniqueId/FOID]
      ,[CustodianId]
	  ,[Notes]
      ,us.[WorkflowVersionGUID]
      ,us.[JoinGUID]
      ,us.[UnquotedSecuritiesCreationDate]
      ,us.[UnquotedSecuritiesCreatedByPersonId]
      ,us.[UnquotedSecuritiesLastModifiedDate]
      ,us.[UnquotedSecuritiesLastModifiedByPersonId]
  FROM [Organisation].[UnquotedSecurities] us
  INNER JOIN [Organisation].[UnquotedCompanies] uc ON us.UnquotedCompanyId = uc.UnquotedCompanyId
  INNER JOIN [Core].[Persons] p ON p.PersonId = uc.InvestmentManagerOwnerPersonId
  LEFT JOIN [Organisation].[UnquotedSecuritiesFundInvestments] fiWEIF ON fiWEIF.UnquotedSecuritiesId = us.UnquotedSecuritiesId AND fiWEIF.FundCode = 'WEIF'
  LEFT JOIN [Organisation].[UnquotedSecuritiesFundInvestments] fiWPCT ON fiWPCT.UnquotedSecuritiesId = us.UnquotedSecuritiesId AND fiWEIF.FundCode = 'WPCT'
