CREATE TABLE [CADIS_PROC].[DM_INPUT213_PROCESSKEYS] (
    [MODEL_CODE]     VARCHAR (20) NOT NULL,
    [MODEL_DATE]     DATETIME     NOT NULL,
    [INSTRUMENT_UII] VARCHAR (12) NOT NULL,
    PRIMARY KEY CLUSTERED ([MODEL_CODE] ASC, [MODEL_DATE] ASC, [INSTRUMENT_UII] ASC) WITH (FILLFACTOR = 80)
);

