CREATE TABLE [CADIS_PROC].[DM_MP2_SOURCE215] (
    [MODEL_CODE]     VARCHAR (20)   NOT NULL,
    [MODEL_DATE]     DATETIME       NOT NULL,
    [INSTRUMENT_UII] VARCHAR (12)   NOT NULL,
    [CADISID]        INT            NOT NULL,
    [CADISPRIORITY]  TINYINT        CONSTRAINT [DF_DM_MP2_SOURCE215_PRIORITY] DEFAULT ((2)) NOT NULL,
    [CADISINSERTED]  DATETIME       NOT NULL,
    [CADISUPDATED]   DATETIME       NOT NULL,
    [CADISCHANGEDBY] NVARCHAR (100) NOT NULL,
    [CADISROWID]     INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CK_DM_MP2_SOURCE215_PRIORITY] CHECK ([CADISPRIORITY]=(1) OR [CADISPRIORITY]=(2) OR [CADISPRIORITY]=(3))
);


GO
CREATE CLUSTERED INDEX [IDXDM_MP2_SOURCE215_PKRID2]
    ON [CADIS_PROC].[DM_MP2_SOURCE215]([MODEL_CODE] ASC, [MODEL_DATE] ASC, [INSTRUMENT_UII] ASC, [CADISROWID] ASC, [CADISID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE215]
    ON [CADIS_PROC].[DM_MP2_SOURCE215]([MODEL_CODE] ASC, [MODEL_DATE] ASC, [INSTRUMENT_UII] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE215_CRID]
    ON [CADIS_PROC].[DM_MP2_SOURCE215]([CADISROWID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE215_CID]
    ON [CADIS_PROC].[DM_MP2_SOURCE215]([CADISID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE215_PKID]
    ON [CADIS_PROC].[DM_MP2_SOURCE215]([MODEL_CODE] ASC, [MODEL_DATE] ASC, [INSTRUMENT_UII] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE215_PKRID]
    ON [CADIS_PROC].[DM_MP2_SOURCE215]([MODEL_CODE] ASC, [MODEL_DATE] ASC, [INSTRUMENT_UII] ASC, [CADISROWID] ASC) WITH (FILLFACTOR = 80);


GO
	
		CREATE TRIGGER [CADIS_PROC].[TRGDM_MP2_SOURCE215_REVISION] ON "CADIS_PROC"."DM_MP2_SOURCE215" 
		FOR INSERT,UPDATE
		AS
			INSERT
			INTO	"CADIS_PROC"."DM_MP2_SOURCE215_REVISION"
				(
					"MODEL_CODE","MODEL_DATE","INSTRUMENT_UII"	,
					[REVISION] 	,
					[REVISIONEFFECTIVE],
					[CADISID],
					[CADISROWID]
				)
				SELECT	MP."MODEL_CODE",MP."MODEL_DATE",MP."INSTRUMENT_UII",
					ISNULL(RV.REVISION,0) + 1,
					MP.CADISUPDATED,
					MP.CADISID,
					MP.CADISROWID
				FROM	INSERTED AS MP
					LEFT OUTER JOIN DELETED AS SR
								ON SR."MODEL_CODE" = MP."MODEL_CODE" AND SR."MODEL_DATE" = MP."MODEL_DATE" AND SR."INSTRUMENT_UII" = MP."INSTRUMENT_UII"
					LEFT OUTER JOIN (	SELECT	"MODEL_CODE","MODEL_DATE","INSTRUMENT_UII", MAX(REVISION) AS REVISION
								FROM	"CADIS_PROC"."DM_MP2_SOURCE215_REVISION" 
								GROUP BY "MODEL_CODE","MODEL_DATE","INSTRUMENT_UII"	) RV
						ON RV."MODEL_CODE" = MP."MODEL_CODE" AND RV."MODEL_DATE" = MP."MODEL_DATE" AND RV."INSTRUMENT_UII" = MP."INSTRUMENT_UII"
				WHERE	MP.CADISID <> ISNULL(SR.CADISID,0)
		