CREATE TABLE [CADIS_PROC].[DM_MATCHPOINT2] (
    [ID]        INT            IDENTITY (1, 1) NOT NULL,
    [PRIORITY]  TINYINT        CONSTRAINT [DF_DM_MATCHPOINT2_PRIORITY] DEFAULT ((2)) NOT NULL,
    [INSERTED]  DATETIME       NOT NULL,
    [UPDATED]   DATETIME       NOT NULL,
    [CHANGEDBY] NVARCHAR (100) NOT NULL,
    [OBSOLETE]  TINYINT        CONSTRAINT [DF_DM_MATCHPOINT2_OBSOLETE] DEFAULT ((0)) NOT NULL,
    [NEWID]     INT            NULL,
    CONSTRAINT [PK_DM_MATCHPOINT2] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CK_DM_MATCHPOINT2_OBSOLETE] CHECK ([OBSOLETE]=(1) OR [OBSOLETE]=(0)),
    CONSTRAINT [CK_DM_MATCHPOINT2_PRIORITY] CHECK ([PRIORITY]=(1) OR [PRIORITY]=(2) OR [PRIORITY]=(3)),
    CONSTRAINT [FK_DM_MATCHPOINT2] FOREIGN KEY ([NEWID]) REFERENCES [CADIS_PROC].[DM_MATCHPOINT2] ([ID])
);

