CREATE TABLE [CADIS_PROC].[DM_MP2_SOURCE213] (
    [MODEL_CODE]     VARCHAR (20)   NOT NULL,
    [CADISID]        INT            NOT NULL,
    [CADISPRIORITY]  TINYINT        CONSTRAINT [DF_DM_MP2_SOURCE213_PRIORITY] DEFAULT ((2)) NOT NULL,
    [CADISINSERTED]  DATETIME       NOT NULL,
    [CADISUPDATED]   DATETIME       NOT NULL,
    [CADISCHANGEDBY] NVARCHAR (100) NOT NULL,
    [CADISROWID]     INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CK_DM_MP2_SOURCE213_PRIORITY] CHECK ([CADISPRIORITY]=(1) OR [CADISPRIORITY]=(2) OR [CADISPRIORITY]=(3))
);


GO
CREATE CLUSTERED INDEX [IDXDM_MP2_SOURCE213_PKRID2]
    ON [CADIS_PROC].[DM_MP2_SOURCE213]([MODEL_CODE] ASC, [CADISROWID] ASC, [CADISID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE213]
    ON [CADIS_PROC].[DM_MP2_SOURCE213]([MODEL_CODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE213_CRID]
    ON [CADIS_PROC].[DM_MP2_SOURCE213]([CADISROWID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE213_CID]
    ON [CADIS_PROC].[DM_MP2_SOURCE213]([CADISID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE213_PKID]
    ON [CADIS_PROC].[DM_MP2_SOURCE213]([MODEL_CODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE213_PKRID]
    ON [CADIS_PROC].[DM_MP2_SOURCE213]([MODEL_CODE] ASC, [CADISROWID] ASC) WITH (FILLFACTOR = 80);


GO
	
		CREATE TRIGGER [CADIS_PROC].[TRGDM_MP2_SOURCE213_REVISION] ON "CADIS_PROC"."DM_MP2_SOURCE213" 
		FOR INSERT,UPDATE
		AS
			INSERT
			INTO	"CADIS_PROC"."DM_MP2_SOURCE213_REVISION"
				(
					"MODEL_CODE"	,
					[REVISION] 	,
					[REVISIONEFFECTIVE],
					[CADISID],
					[CADISROWID]
				)
				SELECT	MP."MODEL_CODE",
					ISNULL(RV.REVISION,0) + 1,
					MP.CADISUPDATED,
					MP.CADISID,
					MP.CADISROWID
				FROM	INSERTED AS MP
					LEFT OUTER JOIN DELETED AS SR
								ON SR."MODEL_CODE" = MP."MODEL_CODE"
					LEFT OUTER JOIN (	SELECT	"MODEL_CODE", MAX(REVISION) AS REVISION
								FROM	"CADIS_PROC"."DM_MP2_SOURCE213_REVISION" 
								GROUP BY "MODEL_CODE"	) RV
						ON RV."MODEL_CODE" = MP."MODEL_CODE"
				WHERE	MP.CADISID <> ISNULL(SR.CADISID,0)
		