CREATE TABLE [CADIS_PROC].[DM_MP1_SOURCE5_REVISION] (
    [BROKER]            VARCHAR (40) NOT NULL,
    [REVISION]          INT          NOT NULL,
    [REVISIONEFFECTIVE] DATETIME     NOT NULL,
    [CADISID]           INT          NOT NULL,
    [CADISROWID]        INT          NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXDM_MP1_SOURCE5_REVISION]
    ON [CADIS_PROC].[DM_MP1_SOURCE5_REVISION]([BROKER] ASC, [REVISION] ASC);

