CREATE TABLE [CADIS_PROC].[DM_MP2_SOURCE243_REVISION] (
    [INSTRUMENT_UII]    VARCHAR (12) NOT NULL,
    [REVISION]          INT          NOT NULL,
    [REVISIONEFFECTIVE] DATETIME     NOT NULL,
    [CADISID]           INT          NOT NULL,
    [CADISROWID]        INT          NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXDM_MP2_SOURCE243_REVISION]
    ON [CADIS_PROC].[DM_MP2_SOURCE243_REVISION]([INSTRUMENT_UII] ASC, [REVISION] ASC) WITH (FILLFACTOR = 80);

