CREATE TABLE [CADIS_PROC].[DM_MP2_SOURCE215_REVISION] (
    [MODEL_CODE]        VARCHAR (20) NOT NULL,
    [MODEL_DATE]        DATETIME     NOT NULL,
    [INSTRUMENT_UII]    VARCHAR (12) NOT NULL,
    [REVISION]          INT          NOT NULL,
    [REVISIONEFFECTIVE] DATETIME     NOT NULL,
    [CADISID]           INT          NOT NULL,
    [CADISROWID]        INT          NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXDM_MP2_SOURCE215_REVISION]
    ON [CADIS_PROC].[DM_MP2_SOURCE215_REVISION]([MODEL_CODE] ASC, [MODEL_DATE] ASC, [INSTRUMENT_UII] ASC, [REVISION] ASC) WITH (FILLFACTOR = 80);

