CREATE TABLE [CADIS_PROC].[DM_MP2_SOURCE207_REVISION] (
    [MODEL_CODE]        VARCHAR (20) NOT NULL,
    [PROCESS_DATE]      DATETIME     NOT NULL,
    [INSTRUMENT_CODE]   VARCHAR (12) NOT NULL,
    [REVISION]          INT          NOT NULL,
    [REVISIONEFFECTIVE] DATETIME     NOT NULL,
    [CADISID]           INT          NOT NULL,
    [CADISROWID]        INT          NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXDM_MP2_SOURCE207_REVISION]
    ON [CADIS_PROC].[DM_MP2_SOURCE207_REVISION]([MODEL_CODE] ASC, [PROCESS_DATE] ASC, [INSTRUMENT_CODE] ASC, [REVISION] ASC) WITH (FILLFACTOR = 80);

