CREATE TABLE [CADIS_PROC].[DM_MP2_SOURCE207] (
    [MODEL_CODE]      VARCHAR (20)   NOT NULL,
    [PROCESS_DATE]    DATETIME       NOT NULL,
    [INSTRUMENT_CODE] VARCHAR (12)   NOT NULL,
    [CADISID]         INT            NOT NULL,
    [CADISPRIORITY]   TINYINT        CONSTRAINT [DF_DM_MP2_SOURCE207_PRIORITY] DEFAULT ((2)) NOT NULL,
    [CADISINSERTED]   DATETIME       NOT NULL,
    [CADISUPDATED]    DATETIME       NOT NULL,
    [CADISCHANGEDBY]  NVARCHAR (100) NOT NULL,
    [CADISROWID]      INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CK_DM_MP2_SOURCE207_PRIORITY] CHECK ([CADISPRIORITY]=(1) OR [CADISPRIORITY]=(2) OR [CADISPRIORITY]=(3))
);


GO
CREATE CLUSTERED INDEX [IDXDM_MP2_SOURCE207_PKRID2]
    ON [CADIS_PROC].[DM_MP2_SOURCE207]([MODEL_CODE] ASC, [PROCESS_DATE] ASC, [INSTRUMENT_CODE] ASC, [CADISROWID] ASC, [CADISID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE207]
    ON [CADIS_PROC].[DM_MP2_SOURCE207]([MODEL_CODE] ASC, [PROCESS_DATE] ASC, [INSTRUMENT_CODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE207_CRID]
    ON [CADIS_PROC].[DM_MP2_SOURCE207]([CADISROWID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE207_CID]
    ON [CADIS_PROC].[DM_MP2_SOURCE207]([CADISID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE207_PKID]
    ON [CADIS_PROC].[DM_MP2_SOURCE207]([MODEL_CODE] ASC, [PROCESS_DATE] ASC, [INSTRUMENT_CODE] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP2_SOURCE207_PKRID]
    ON [CADIS_PROC].[DM_MP2_SOURCE207]([MODEL_CODE] ASC, [PROCESS_DATE] ASC, [INSTRUMENT_CODE] ASC, [CADISROWID] ASC) WITH (FILLFACTOR = 80);


GO
	
		CREATE TRIGGER [CADIS_PROC].[TRGDM_MP2_SOURCE207_REVISION] ON "CADIS_PROC"."DM_MP2_SOURCE207" 
		FOR INSERT,UPDATE
		AS
			INSERT
			INTO	"CADIS_PROC"."DM_MP2_SOURCE207_REVISION"
				(
					"MODEL_CODE","PROCESS_DATE","INSTRUMENT_CODE"	,
					[REVISION] 	,
					[REVISIONEFFECTIVE],
					[CADISID],
					[CADISROWID]
				)
				SELECT	MP."MODEL_CODE",MP."PROCESS_DATE",MP."INSTRUMENT_CODE",
					ISNULL(RV.REVISION,0) + 1,
					MP.CADISUPDATED,
					MP.CADISID,
					MP.CADISROWID
				FROM	INSERTED AS MP
					LEFT OUTER JOIN DELETED AS SR
								ON SR."MODEL_CODE" = MP."MODEL_CODE" AND SR."PROCESS_DATE" = MP."PROCESS_DATE" AND SR."INSTRUMENT_CODE" = MP."INSTRUMENT_CODE"
					LEFT OUTER JOIN (	SELECT	"MODEL_CODE","PROCESS_DATE","INSTRUMENT_CODE", MAX(REVISION) AS REVISION
								FROM	"CADIS_PROC"."DM_MP2_SOURCE207_REVISION" 
								GROUP BY "MODEL_CODE","PROCESS_DATE","INSTRUMENT_CODE"	) RV
						ON RV."MODEL_CODE" = MP."MODEL_CODE" AND RV."PROCESS_DATE" = MP."PROCESS_DATE" AND RV."INSTRUMENT_CODE" = MP."INSTRUMENT_CODE"
				WHERE	MP.CADISID <> ISNULL(SR.CADISID,0)
		