CREATE TABLE [CADIS_PROC].[DM_MP1_SOURCE5] (
    [BROKER]         VARCHAR (40)   NOT NULL,
    [CADISID]        INT            NOT NULL,
    [CADISPRIORITY]  TINYINT        CONSTRAINT [DF_DM_MP1_SOURCE5_PRIORITY] DEFAULT ((2)) NOT NULL,
    [CADISINSERTED]  DATETIME       NOT NULL,
    [CADISUPDATED]   DATETIME       NOT NULL,
    [CADISCHANGEDBY] NVARCHAR (100) NOT NULL,
    [CADISROWID]     INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CK_DM_MP1_SOURCE5_PRIORITY] CHECK ([CADISPRIORITY]=(1) OR [CADISPRIORITY]=(2) OR [CADISPRIORITY]=(3))
);


GO
CREATE CLUSTERED INDEX [IDXDM_MP1_SOURCE5_PKRID2]
    ON [CADIS_PROC].[DM_MP1_SOURCE5]([BROKER] ASC, [CADISROWID] ASC, [CADISID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDXDM_MP1_SOURCE5]
    ON [CADIS_PROC].[DM_MP1_SOURCE5]([BROKER] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP1_SOURCE5_CRID]
    ON [CADIS_PROC].[DM_MP1_SOURCE5]([CADISROWID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP1_SOURCE5_CID]
    ON [CADIS_PROC].[DM_MP1_SOURCE5]([CADISID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP1_SOURCE5_PKID]
    ON [CADIS_PROC].[DM_MP1_SOURCE5]([BROKER] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXDM_MP1_SOURCE5_PKRID]
    ON [CADIS_PROC].[DM_MP1_SOURCE5]([BROKER] ASC, [CADISROWID] ASC);


GO
	
		CREATE TRIGGER [CADIS_PROC].[TRGDM_MP1_SOURCE5_REVISION] ON "CADIS_PROC"."DM_MP1_SOURCE5" 
		FOR insert/*sp_password*/,update/*sp_password*/
		AS
			insert/*sp_password*/
			INTO	"CADIS_PROC"."DM_MP1_SOURCE5_REVISION"
				(
					"BROKER"	,
					[REVISION] 	,
					[REVISIONEFFECTIVE],
					[CADISID],
					[CADISROWID]
				)
				select/*sp_password*/	MP."BROKER",
					ISNULL(RV.REVISION,0) + 1,
					MP.CADISUPDATED,
					MP.CADISID,
					MP.CADISROWID
				FROM	INSERTED AS MP
					LEFT OUTER JOIN DELETED AS SR
								ON SR."BROKER" = MP."BROKER"
					LEFT OUTER JOIN (	select/*sp_password*/	"BROKER", MAX(REVISION) AS REVISION
								FROM	"CADIS_PROC"."DM_MP1_SOURCE5_REVISION" 
								GROUP BY "BROKER"	) RV
						ON RV."BROKER" = MP."BROKER"
				WHERE	MP.CADISID <> ISNULL(SR.CADISID,0)
		