CREATE TABLE [CADIS_PROC].[DM_MP2_SOURCE20_REVISION] (
    [UNIQUE_IDENTIFIER] VARCHAR (30) NOT NULL,
    [REVISION]          INT          NOT NULL,
    [REVISIONEFFECTIVE] DATETIME     NOT NULL,
    [CADISID]           INT          NOT NULL,
    [CADISROWID]        INT          NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXDM_MP2_SOURCE20_REVISION]
    ON [CADIS_PROC].[DM_MP2_SOURCE20_REVISION]([UNIQUE_IDENTIFIER] ASC, [REVISION] ASC);

