CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION461_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @PRIORITY VARCHAR (20), @EXCEPTION_NAME VARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


