CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION441_INBOXSELROWNUMBER]
@PositionDate DATE, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


