CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION491_INBOXSELSINGLEROW]
@ROW_UNIQUE_ID BIGINT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


