CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION488_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATE, @CURRENCY VARCHAR (20), @SOURCE_TYPE VARCHAR (20), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


