CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION463_INBOXSELSINGLEROW]
@SOURCE_TABLE VARCHAR (50), @SOURCE_KEY VARCHAR (50), @SOURCE_COLUMN VARCHAR (50), @EXCEPTION_CODE INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


