CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION470_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CommentaryId INT, @CommentaryId_UPDATE BIT, @SecurityName NVARCHAR (255), @SecurityName_UPDATE BIT, @SecurityValue DECIMAL (19, 5), @SecurityValue_UPDATE BIT, @Rank INT, @Rank_UPDATE BIT, @Fund NVARCHAR (255), @Fund_UPDATE BIT, @EventType NVARCHAR (255), @EventType_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


