CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION511_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @QuarterId SMALLINT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @QuarterEndingName NVARCHAR (15), @QuarterEndingName_UPDATE BIT, @ReviewTaskJiraKey NVARCHAR (255), @ReviewTaskJiraKey_UPDATE BIT, @DocusignTaskJiraKey NVARCHAR (255), @DocusignTaskJiraKey_UPDATE BIT, @SendLetterTaskJiraKey NVARCHAR (255), @SendLetterTaskJiraKey_UPDATE BIT, @UploadInvoiceTaskJiraKey NVARCHAR (255), @UploadInvoiceTaskJiraKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


