CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION41_AUDITLATESTCHANGE]
@FXRATE_ID VARCHAR (16), @DATE DATETIME, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


