CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION39_INBOXSELSINGLEROW]
@STORE_DATE DATETIME, @FXRATE_ID VARCHAR (16), @DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


