CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION460_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @SOURCE_TABLE VARCHAR (50), @SOURCE_KEY VARCHAR (50), @SOURCE_COLUMN VARCHAR (50), @EXCEPTION_CODE INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


