CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION468_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @D_GL_POST DATE, @ACCOUNT_NUMBER VARCHAR (6), @SEDOL VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


