CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION497_INBOXUPD]
@CompanyEventId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CompanyId INT, @CompanyId_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @EventDetails VARCHAR (500), @EventDetails_UPDATE BIT, @EventDateTime DATETIME, @EventDateTime_UPDATE BIT, @Description VARCHAR (500), @Description_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


