CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION41_INBOXDEL]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @FXRATE_ID VARCHAR (16), @DATE DATETIME, @CADIS_SYSTEM_TIMESTAMP ROWVERSION
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


