CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION467_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (20), @Qtr CHAR (5)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


