CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION462_INBOXSELSINGLEROW]
@PRIORITY VARCHAR (20), @EXCEPTION_NAME VARCHAR (40), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


