CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION414_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @AnnualBudgetId INT, @AnnualBudgetId_UPDATE BIT, @ReviewTypeId INT, @ReviewTypeId_UPDATE BIT, @ReviewComments VARCHAR (MAX), @ReviewComments_UPDATE BIT, @ReviewDate DATETIME, @ReviewDate_UPDATE BIT, @BudgetApproved BIT, @BudgetApproved_UPDATE BIT, @ReviewedByPersonId SMALLINT, @ReviewedByPersonId_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @ReviewLastModifiedDatetime DATETIME, @ReviewLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


