CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION489_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @DVD_Fund_Overrides_ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FUND_SHORT_NAME VARCHAR (50), @FUND_SHORT_NAME_UPDATE BIT, @OVERRIDE_DATE DATETIME, @OVERRIDE_DATE_UPDATE BIT, @OVERRIDE_UNITS DECIMAL (18, 2), @OVERRIDE_UNITS_UPDATE BIT, @OVERRIDE_GROSS_DVD_VALUE DECIMAL (18, 2), @OVERRIDE_GROSS_DVD_VALUE_UPDATE BIT, @OVERRIDE_NET_DVD_VALUE DECIMAL (18, 2), @OVERRIDE_NET_DVD_VALUE_UPDATE BIT, @OVERRIDE_COMMENTARY VARCHAR (50), @OVERRIDE_COMMENTARY_UPDATE BIT, @OVERRIDE_REASON VARCHAR (50), @OVERRIDE_REASON_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @Qtr INT, @Qtr_UPDATE BIT, @Yr INT, @Yr_UPDATE BIT, @LAST_UPDATED_BY VARCHAR (50), @LAST_UPDATED_BY_UPDATE BIT, @LAST_UPDATED DATETIME, @LAST_UPDATED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


