CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION469_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @ACCOUNT_NUMBER VARCHAR (50), @SEDOL VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


