CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION464_INBOXSELSINGLEROW]
@STOCK VARCHAR (20), @ROW_ID INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


