CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION477_INBOXUPD]
@SfAccountId VARCHAR (18), @Sector VARCHAR (10), @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @MakeContact BIT, @MakeContact_UPDATE BIT, @OverrideStatus VARCHAR (10), @OverrideStatus_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


