CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION468_INBOXSELSINGLEROW]
@D_GL_POST DATE, @ACCOUNT_NUMBER VARCHAR (6), @SEDOL VARCHAR (20), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


