CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION524_INBOXGROUPSEL]
@BENCHMARK_NAME VARCHAR (100), @WEEK_END_DATE DATETIME, @TOP_OR_BOTTOM VARCHAR (6), @WhereSQL NVARCHAR (MAX), @GroupColumns NVARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


