CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION41_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @FXRATE_ID VARCHAR (16), @DATE DATETIME, @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FROM_ISO_CURRENCY_CODE VARCHAR (3), @FROM_ISO_CURRENCY_CODE_UPDATE BIT, @TO_ISO_CURRENCY_CODE VARCHAR (3), @TO_ISO_CURRENCY_CODE_UPDATE BIT, @SPOT_RATE DECIMAL (24, 16), @SPOT_RATE_UPDATE BIT, @1_MONTH_FORWARD_RATE DECIMAL (24, 16), @1_MONTH_FORWARD_RATE_UPDATE BIT, @2_MONTH_FORWARD_RATE DECIMAL (24, 16), @2_MONTH_FORWARD_RATE_UPDATE BIT, @3_MONTH_FORWARD_RATE DECIMAL (24, 16), @3_MONTH_FORWARD_RATE_UPDATE BIT, @6_MONTH_FORWARD_RATE DECIMAL (24, 16), @6_MONTH_FORWARD_RATE_UPDATE BIT, @1_YEAR_FORWARD_RATE DECIMAL (24, 16), @1_YEAR_FORWARD_RATE_UPDATE BIT, @DATA_QUALITY VARCHAR (20), @DATA_QUALITY_UPDATE BIT, @OVERRIDE_COMMENT VARCHAR (255), @OVERRIDE_COMMENT_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


