CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION467_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (20), @Qtr CHAR (5), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


