CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION392_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CriticalProcess VARCHAR (MAX), @CriticalProcess_UPDATE BIT, @Summary VARCHAR (MAX), @Summary_UPDATE BIT, @RecoveryTimeFrame VARCHAR (255), @RecoveryTimeFrame_UPDATE BIT, @Status VARCHAR (50), @Status_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @OwnerPersonId SMALLINT, @OwnerPersonId_UPDATE BIT, @RecordedByPersonId SMALLINT, @RecordedByPersonId_UPDATE BIT, @DepartmentId SMALLINT, @DepartmentId_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @BCPCriticalProcessLastModifiedDatetime DATETIME, @BCPCriticalProcessLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


