CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION469_INBOXSELSINGLEROW]
@ACCOUNT_NUMBER VARCHAR (50), @SEDOL VARCHAR (20), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


