CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION524_INBOXSELSINGLEROW]
@BENCHMARK_NAME VARCHAR (100), @WEEK_END_DATE DATETIME, @TOP_OR_BOTTOM VARCHAR (6), @ROW_NUM INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


