CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION495_INBOXSELSINGLEROW]
@STORE_DATE DATETIME, @CASH_LADDER_ID INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


