CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION475_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @DataChannelID INT, @DataChannelName VARCHAR (60), @DataChannelName_UPDATE BIT, @SOURCE VARCHAR (30), @SOURCE_UPDATE BIT, @ENTITY VARCHAR (50), @ENTITY_UPDATE BIT, @DESCRIPTION VARCHAR (150), @DESCRIPTION_UPDATE BIT, @DIRECTION VARCHAR (3), @DIRECTION_UPDATE BIT, @MARKIT_SOLUTION VARCHAR (150), @MARKIT_SOLUTION_UPDATE BIT, @MORNING_CHECK VARCHAR (50), @MORNING_CHECK_UPDATE BIT, @EXPECTED_DELIVERY_TIME TIME (7), @EXPECTED_DELIVERY_TIME_UPDATE BIT, @EXPECTED_SLA_COMPLETION TIME (7), @EXPECTED_SLA_COMPLETION_UPDATE BIT, @IS_ACTIVE BIT, @IS_ACTIVE_UPDATE BIT, @DELIVERY_SCHEDULE_ID INT, @DELIVERY_SCHEDULE_ID_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


