CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION506_INBOXSELSINGLEROW]
@FundName VARCHAR (8), @PositionDate DATE, @FUND_SHORT_NAME VARCHAR (50), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


