CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION490_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @DVD_Overrides_ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @EDM_SEC_ID INT, @EDM_SEC_ID_UPDATE BIT, @BBG_EX_DATE DATETIME, @BBG_EX_DATE_UPDATE BIT, @OVERRIDE_EX_DATE DATETIME, @OVERRIDE_EX_DATE_UPDATE BIT, @OVERRIDE_DVD_VALUE DECIMAL (18, 4), @OVERRIDE_DVD_VALUE_UPDATE BIT, @OVERRIDE_COMMENTARY VARCHAR (50), @OVERRIDE_COMMENTARY_UPDATE BIT, @OVERRIDE_REASON VARCHAR (50), @OVERRIDE_REASON_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @LAST_UPDATED_BY VARCHAR (50), @LAST_UPDATED_BY_UPDATE BIT, @LAST_UPDATED DATETIME, @LAST_UPDATED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


