CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION455_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (15), @EDM_SEC_ID INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


