CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION506_INBOXSELROWNUMBER]
@FundName VARCHAR (8), @PositionDate DATE, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


