CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION493_INBOXSELSINGLEROW]
@ROW_UNIQUE_ID BIGINT, @EDM_SEC_ID INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


