CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION494_INBOXSELSINGLEROW]
@TDate DATE, @Fund VARCHAR (10), @MaxDate DATE, @ReportDate DATETIME, @Fund1 VARCHAR (15), @CCY VARCHAR (3), @AsOfDate DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


