CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION488_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATE, @CURRENCY VARCHAR (20), @SOURCE_TYPE VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


