CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION441_INBOXSELSINGLEROW]
@PositionDate DATE, @FUND_SHORT_NAME VARCHAR (256), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


