CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION524_INBOXSELROWNUMBER]
@BENCHMARK_NAME VARCHAR (100), @WEEK_END_DATE DATETIME, @TOP_OR_BOTTOM VARCHAR (6), @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @ROW_NUM INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


