CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION393_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @BCPTestPlanEventId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @BCPTestPlanRegisterId INT, @BCPTestPlanRegisterId_UPDATE BIT, @TestPlanStatus VARCHAR (25), @TestPlanStatus_UPDATE BIT, @RecordedByPersonId SMALLINT, @RecordedByPersonId_UPDATE BIT, @EventDetails VARCHAR (MAX), @EventDetails_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @TestPlanResult VARCHAR (25), @TestPlanResult_UPDATE BIT, @CalendarYear CHAR (4), @CalendarYear_UPDATE BIT, @IsReTest BIT, @IsReTest_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @BCPTestPlanEventLastModifiedDatetime DATETIME, @BCPTestPlanEventLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


