CREATE TABLE [Staging].[CompanyJobRolesSrc] (
    [Company: ID]                             [Staging].[SalesforceIdDom] NOT NULL,
    [Company: Company name]                   [sysname]                   NOT NULL,
    [Company Job Role: ID]                    [Staging].[SalesforceIdDom] NULL,
    [Company Job Role: Job role]              [sysname]                   NULL,
    [Annual salary Currency]                  NVARCHAR (255)              NULL,
    [Annual salary]                           NVARCHAR (255)              NULL,
    [Annual salary (converted) Currency]      NVARCHAR (255)              NULL,
    [Annual salary (converted)]               NVARCHAR (255)              NULL,
    [Commission / bonus Currency]             NVARCHAR (255)              NULL,
    [Commission / bonus]                      NVARCHAR (255)              NULL,
    [Commission / bonus (converted) Currency] NVARCHAR (255)              NULL,
    [Commission / bonus (converted)]          NVARCHAR (255)              NULL,
    [Compensation notes]                      NVARCHAR (255)              NULL,
    [Department]                              [sysname]                   NULL,
    [Educational requirements]                NVARCHAR (255)              NULL,
    [FCA Approved Person]                     NVARCHAR (255)              NULL,
    [FCA CPD]                                 NVARCHAR (255)              NULL,
    [Functional area]                         NVARCHAR (255)              NULL,
    [Hours per week]                          NVARCHAR (255)              NULL,
    [Job code]                                [sysname]                   NULL,
    [Job description]                         NVARCHAR (255)              NULL,
    [Job role location]                       NVARCHAR (255)              NULL,
    [Job role notes]                          NVARCHAR (255)              NULL,
    [Max OTE Currency]                        NVARCHAR (255)              NULL,
    [Max OTE]                                 NVARCHAR (255)              NULL,
    [Max OTE (converted) Currency]            NVARCHAR (255)              NULL,
    [Max OTE (converted)]                     NVARCHAR (255)              NULL,
    [No longer in use]                        NVARCHAR (255)              NULL,
    [Responsibilities]                        NVARCHAR (255)              NULL,
    [Skills required]                         NVARCHAR (255)              NULL,
    [Target OTE Currency]                     NVARCHAR (255)              NULL,
    [Target OTE]                              NVARCHAR (255)              NULL,
    [Target OTE (converted) Currency]         NVARCHAR (255)              NULL,
    [Target OTE (converted)]                  NVARCHAR (255)              NULL,
    [Travel required]                         NVARCHAR (255)              NULL,
    [Company Job Role: Currency]              NVARCHAR (255)              NULL,
    [Company Job Role: Created By]            NVARCHAR (255)              NULL,
    [Company Job Role: Created Alias]         NVARCHAR (255)              NULL,
    [Company Job Role: Created Date]          DATETIME                    NULL,
    [Company Job Role: Last Modified By]      NVARCHAR (255)              NULL,
    [Company Job Role: Last Modified Alias]   NVARCHAR (255)              NULL,
    [Company Job Role: Last Modified Date]    DATETIME                    NULL,
    [JobId]                                   NVARCHAR (255)              NULL
);

