CREATE TABLE [Staging].[EmployeesSrc] (
    [Employee: Employee name]          [sysname]                   NOT NULL,
    [Employee: ID]                     [Staging].[SalesforceIdDom] NOT NULL,
    [Assign SF licence]                NVARCHAR (255)              NULL,
    [Company]                          NVARCHAR (255)              NULL,
    [Company L]                        NVARCHAR (255)              NULL,
    [Continuous service date]          DATETIME                    NULL,
    [Contractual hours]                FLOAT (53)                  NULL,
    [Date notice of termination given] DATETIME                    NULL,
    [Department]                       NVARCHAR (255)              NULL,
    [Employee number]                  NVARCHAR (255)              NULL,
    [Employment status]                NVARCHAR (255)              NULL,
    [Employment type]                  NVARCHAR (255)              NULL,
    [Fire marshall]                    NVARCHAR (255)              NULL,
    [First aider]                      NVARCHAR (255)              NULL,
    [Home worker]                      NVARCHAR (255)              NULL,
    [HR user status]                   NVARCHAR (255)              NULL,
    [Image]                            NVARCHAR (255)              NULL,
    [IsManager]                        NVARCHAR (255)              NULL,
    [IsNewJoiner]                      NVARCHAR (255)              NULL,
    [Job role]                         NVARCHAR (255)              NULL,
    [Job title]                        NVARCHAR (255)              NULL,
    [Last working day]                 DATETIME                    NULL,
    [Leaver type]                      NVARCHAR (255)              NULL,
    [Leaving date]                     DATETIME                    NULL,
    [Leaving reason notes]             NVARCHAR (255)              NULL,
    [Length of service]                NVARCHAR (255)              NULL,
    [Length of service anniversary]    DATETIME                    NULL,
    [Length of service on exit]        NVARCHAR (255)              NULL,
    [Location]                         NVARCHAR (255)              NULL,
    [Location L]                       NVARCHAR (255)              NULL,
    [Management Team]                  NVARCHAR (255)              NULL,
    [Manager]                          NVARCHAR (255)              NULL,
    [Manager email]                    NVARCHAR (255)              NULL,
    [Manager email - formatted]        NVARCHAR (255)              NULL,
    [Notice period]                    FLOAT (53)                  NULL,
    [On probation]                     NVARCHAR (255)              NULL,
    [Pattern type]                     NVARCHAR (255)              NULL,
    [Payroll end date]                 DATETIME                    NULL,
    [Payroll start date]               DATETIME                    NULL,
    [Probation period end date]        DATETIME                    NULL,
    [Reason for leaving]               NVARCHAR (255)              NULL,
    [Start date]                       DATETIME                    NULL,
    [Student loan]                     NVARCHAR (255)              NULL,
    [User]                             NVARCHAR (255)              NULL,
    [Weeks/months]                     NVARCHAR (255)              NULL,
    [Work email address]               NVARCHAR (255)              NULL,
    [Work phone number]                NVARCHAR (255)              NULL,
    [Employee: Currency]               NVARCHAR (255)              NULL,
    [Employee: Owner Name]             NVARCHAR (255)              NULL,
    [Employee: Owner Alias]            NVARCHAR (255)              NULL,
    [Employee: Owner Role]             NVARCHAR (255)              NULL,
    [Employee: Created By]             NVARCHAR (255)              NULL,
    [Employee: Created Alias]          NVARCHAR (255)              NULL,
    [Employee: Created Date]           DATETIME                    NULL,
    [Employee: Last Modified By]       NVARCHAR (255)              NULL,
    [Employee: Last Modified Alias]    NVARCHAR (255)              NULL,
    [Employee: Last Modified Date]     DATETIME                    NULL,
    [Employee: Last Activity Date]     NVARCHAR (255)              NULL,
    [UserId]                           NVARCHAR (255)              NULL,
    [JobId]                            NVARCHAR (255)              NULL
);

