CREATE TABLE [Staging].[FinancialClarity] (
    [As_at_Date]                                   NVARCHAR (256) NULL,
    [MTX_ACCOUNT_SIV_ID]                           NVARCHAR (256) NULL,
    [Matrix_Outlet_ID]                             NVARCHAR (256) NULL,
    [Outlet_Own_Gross_Sales]                       NVARCHAR (256) NULL,
    [Outlet_Market_Gross_Sales]                    NVARCHAR (256) NULL,
    [Outlet_Own_Net_Sales]                         NVARCHAR (256) NULL,
    [Outlet_Market_Net_Sales]                      NVARCHAR (256) NULL,
    [UK_Equity_Income_Own_Gross_Sales]             NVARCHAR (256) NULL,
    [UK_Equity_Income_Market_Gross_Sales]          NVARCHAR (256) NULL,
    [UK_Equity_Income_Own_Net_Sales]               NVARCHAR (256) NULL,
    [UK_Equity_Income_Market_Net_Sales]            NVARCHAR (256) NULL,
    [Specialist_Own_Gross_Sales]                   NVARCHAR (256) NULL,
    [Specialist_Market_Gross_Sales]                NVARCHAR (256) NULL,
    [Specialist_Own_Net_Sales]                     NVARCHAR (256) NULL,
    [Specialist_Market_Net_Sales]                  NVARCHAR (256) NULL,
    [UK_Equity_and_Bond_Income_Own_Gross_Sales]    NVARCHAR (256) NULL,
    [UK_Equity_and_Bond_Income_Market_Gross_Sales] NVARCHAR (256) NULL,
    [UK_Equity_and_Bond_Income_Own_Net_Sales]      NVARCHAR (256) NULL,
    [UK_Equity_and_Bond_Income_Market_Net_Sales]   NVARCHAR (256) NULL,
    [UK_All_Companies_Own_Gross_Sales]             NVARCHAR (256) NULL,
    [UK_All_Companies_Market_Gross_Sales]          NVARCHAR (256) NULL,
    [UK_All_Companies_Own_Net_Sales]               NVARCHAR (256) NULL,
    [UK_All_Companies_Market_Net_Sales]            NVARCHAR (256) NULL,
    [Global_Equity_Income_Own_Gross_Sales]         NVARCHAR (256) NULL,
    [Global_Equity_Income_Market_Gross_Sales]      NVARCHAR (256) NULL,
    [Global_Equity_Income_Own_Net_Sales]           NVARCHAR (256) NULL,
    [Global_Equity_Income_Market_Net_Sales]        NVARCHAR (256) NULL,
    [CADIS_SYSTEM_INSERTED]                        DATETIME       CONSTRAINT [DF_sfc_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                         DATETIME       CONSTRAINT [DF_sfc_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                       NVARCHAR (50)  CONSTRAINT [DF_sfc_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                        INT            CONSTRAINT [DF_sfc_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                       ROWVERSION     NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                    DATETIME       CONSTRAINT [DF_sfc_CSL] DEFAULT (getdate()) NULL
);

