CREATE TABLE [Staging].[FinancialsFact] (
    [FinancialFactId]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [DepartmentId]        SMALLINT      NOT NULL,
    [PostingDateId]       INT           NOT NULL,
    [TransactionDateId]   INT           NOT NULL,
    [BudgetAmount]        MONEY         NULL,
    [ActualAmount]        MONEY         NULL,
    [ControlId]           BIGINT        NOT NULL,
    [SourceSystemId]      SMALLINT      NOT NULL,
    [FinancialLineTypeId] SMALLINT      NOT NULL,
    [AccountRef]          VARCHAR (20)  NULL,
    [NominalCode]         INT           NOT NULL,
    [TransactionNo]       INT           CONSTRAINT [DF_FF_TN] DEFAULT ((-1)) NOT NULL,
    [TaxCode]             CHAR (3)      NULL,
    [DetailNotes]         VARCHAR (255) NULL,
    [ProjectCode]         VARCHAR (31)  NULL,
    [TransactionTypeId]   SMALLINT      CONSTRAINT [DF_FF_TTI] DEFAULT ((-1)) NOT NULL,
    [IsDiscretionary]     BIT           NULL,
    [CountOf]             INT           CONSTRAINT [DF_FF_CO] DEFAULT ((1)) NOT NULL,
    [CurrentRow]          BIT           CONSTRAINT [DF_FF_CR] DEFAULT ((1)) NOT NULL,
    [CurrentRowSwitchId]  BIGINT        CONSTRAINT [DF_FF_CRSI] DEFAULT ((-1)) NOT NULL,
    [DeletedRow]          BIT           CONSTRAINT [DF_FF_DR] DEFAULT ((0)) NOT NULL,
    [JournalLineID]       VARCHAR (100) NOT NULL
);

