CREATE TABLE [Staging].[GL_LLP] (
    [TRAN_NUMBER]       NVARCHAR (255) NOT NULL,
    [TYPE]              NVARCHAR (255) NULL,
    [DATE]              VARCHAR (255)  NULL,
    [Account_Ref]       NVARCHAR (255) NULL,
    [NOMINAL_CODE]      NVARCHAR (255) NULL,
    [BANK_CODE]         NVARCHAR (255) NULL,
    [INV_REF]           NVARCHAR (255) NULL,
    [DETAILS]           NVARCHAR (255) NULL,
    [DEPT_NUMBER]       NVARCHAR (255) NULL,
    [DEPT_NAME]         NVARCHAR (255) NULL,
    [TAX_CODE]          NVARCHAR (255) NULL,
    [AMOUNT]            NVARCHAR (255) NULL,
    [EXTRA_REF]         NVARCHAR (255) NULL,
    [Month]             NVARCHAR (255) NULL,
    [Year]              NVARCHAR (255) NULL,
    [Period]            NVARCHAR (255) NULL,
    [Supplier/Customer] NVARCHAR (255) NULL,
    [PnL/BS]            NVARCHAR (255) NULL,
    [Account Category]  NVARCHAR (255) NULL,
    [F20]               NVARCHAR (255) NULL,
    [RowId]             INT            IDENTITY (1, 1) NOT NULL,
    [IncludeInFact]     BIT            CONSTRAINT [DF_GL_IIF] DEFAULT ((1)) NOT NULL,
    [TransactionNo]     INT            CONSTRAINT [DF_GL_TN] DEFAULT ((-1)) NOT NULL,
    [NominalCode]       INT            CONSTRAINT [DF_GL_NC] DEFAULT ((-1)) NOT NULL,
    [Supplier]          VARCHAR (50)   NULL,
    [YearPeriod]        VARCHAR (20)   NULL,
    [JournalLineID]     VARCHAR (100)  NOT NULL,
    CONSTRAINT [XPKGLLLP] PRIMARY KEY CLUSTERED ([TRAN_NUMBER] ASC, [RowId] ASC)
);

