CREATE TABLE [Staging].[JobRolesSrc] (
    [Employee: ID]                            [Staging].[SalesforceIdDom] NOT NULL,
    [Employee: Employee name]                 [sysname]                   NOT NULL,
    [Job Role: ID]                            [Staging].[SalesforceIdDom] NOT NULL,
    [Job Role: Job title]                     [sysname]                   NOT NULL,
    [Additional contractual leave]            FLOAT (53)                  NULL,
    [Additional leave for job role/seniority] FLOAT (53)                  NULL,
    [Assignment date]                         NVARCHAR (255)              NULL,
    [Authorised for overtime]                 NVARCHAR (255)              NULL,
    [Company (role)]                          NVARCHAR (255)              NULL,
    [Company (role) L]                        NVARCHAR (255)              NULL,
    [Company hours per week]                  FLOAT (53)                  NULL,
    [Contract end date]                       NVARCHAR (255)              NULL,
    [Contractual hours]                       FLOAT (53)                  NULL,
    [Country]                                 NVARCHAR (255)              NULL,
    [Current]                                 NVARCHAR (255)              NULL,
    [Department]                              [sysname]                   NULL,
    [Department code]                         [sysname]                   NULL,
    [Department L]                            NVARCHAR (255)              NULL,
    [Effective from]                          DATETIME                    NULL,
    [Effective to]                            DATETIME                    NULL,
    [Employment type]                         NVARCHAR (255)              NULL,
    [Final job role]                          NVARCHAR (255)              NULL,
    [First job role]                          NVARCHAR (255)              NULL,
    [FTE ratio]                               FLOAT (53)                  NULL,
    [Future manager]                          NVARCHAR (255)              NULL,
    [Job code]                                NVARCHAR (255)              NULL,
    [Location]                                NVARCHAR (255)              NULL,
    [Manager]                                 NVARCHAR (255)              NULL,
    [Manager1]                                NVARCHAR (255)              NULL,
    [No# working days/week]                   FLOAT (53)                  NULL,
    [Normal hours worked]                     NVARCHAR (255)              NULL,
    [Notes]                                   NVARCHAR (255)              NULL,
    [Pattern type]                            NVARCHAR (255)              NULL,
    [Profile]                                 NVARCHAR (255)              NULL,
    [Reason for change]                       NVARCHAR (255)              NULL,
    [Role]                                    NVARCHAR (255)              NULL,
    [Update manager automation]               NVARCHAR (255)              NULL,
    [Working days]                            NVARCHAR (255)              NULL,
    [Job Role: Currency]                      NVARCHAR (255)              NULL,
    [Job Role: Created By]                    NVARCHAR (255)              NULL,
    [Job Role: Created Alias]                 NVARCHAR (255)              NULL,
    [Job Role: Created Date]                  DATETIME                    NULL,
    [Job Role: Last Modified By]              NVARCHAR (255)              NULL,
    [Job Role: Last Modified Alias]           NVARCHAR (255)              NULL,
    [Job Role: Last Modified Date]            DATETIME                    NULL,
    [Job Role: Last Activity Date]            NVARCHAR (255)              NULL,
    [CompanyJobRoleId]                        NCHAR (10)                  NULL
);

