CREATE TABLE [Staging].[LearningHistorySrc] (
    [Id]                      VARCHAR (25)  NOT NULL,
    [IsDeleted]               VARCHAR (5)   NULL,
    [Name]                    VARCHAR (MAX) NULL,
    [CurrencyIsoCode]         VARCHAR (25)  NULL,
    [CreatedDate]             DATETIME      NULL,
    [CreatedById]             VARCHAR (20)  NULL,
    [LastModifiedDate]        DATETIME      NULL,
    [LastModifiedById]        VARCHAR (20)  NULL,
    [SystemModstamp]          DATETIME      NULL,
    [Employee]                VARCHAR (20)  NULL,
    [Provider]                VARCHAR (25)  NULL,
    [Result]                  VARCHAR (35)  NULL,
    [Status]                  VARCHAR (55)  NULL,
    [Type]                    VARCHAR (35)  NULL,
    [CourseName]              VARCHAR (MAX) NULL,
    [ExpiryDate]              DATETIME      NULL,
    [Line_Manager]            VARCHAR (20)  NULL,
    [CourseApproverEmail]     VARCHAR (50)  NULL,
    [Manager]                 VARCHAR (20)  NULL,
    [DateApproved]            DATETIME      NULL,
    [RequestApproved]         VARCHAR (5)   NULL,
    [AttestationComplete]     VARCHAR (5)   NULL,
    [AttestationDate]         DATETIME      NULL,
    [ManagerComments]         VARCHAR (50)  NULL,
    [AttestationRequired]     VARCHAR (5)   NULL,
    [EmployeeActionsRequired] VARCHAR (5)   NULL,
    [AttendanceApprover]      VARCHAR (20)  NULL,
    [EstimatedCost]           VARCHAR (20)  NULL,
    [ProposedDate]            DATETIME      NULL,
    [StartDate]               DATETIME      NULL,
    [EmploymentStatus]        VARCHAR (25)  NULL,
    [EmploymentType]          VARCHAR (25)  NULL,
    [HRUserStatus]            VARCHAR (15)  NULL
);

