CREATE TABLE [Staging].[Matrix_FCDataFeed] (
    [MTX_ACCOUNT_SIV_ID]                           VARCHAR (100)   NOT NULL,
    [AS_AT_DATE]                                   DATETIME        NOT NULL,
    [MATRIX_OUTLET_ID]                             VARCHAR (50)    NULL,
    [OUTLET_OWN_GROSS_SALES]                       DECIMAL (18, 2) NULL,
    [OUTLET_MARKET_GROSS_SALES]                    DECIMAL (18, 2) NULL,
    [OUTLET_OWN_NET_SALES]                         DECIMAL (18, 2) NULL,
    [OUTLET_MARKET_NET_SALES]                      DECIMAL (18, 2) NULL,
    [UK_EQUITY_INCOME_OWN_GROSS_SALES]             DECIMAL (18, 2) NULL,
    [UK_EQUITY_INCOME_MARKET_GROSS_SALES]          DECIMAL (18, 2) NULL,
    [UK_EQUITY_INCOME_OWN_NET_SALES]               DECIMAL (18, 2) NULL,
    [UK_EQUITY_INCOME_MARKET_NET_SALES]            DECIMAL (18, 2) NULL,
    [UK_EQUITY_AND_BOND_INCOME_OWN_GROSS_SALES]    DECIMAL (18, 2) NULL,
    [UK_EQUITY_AND_BOND_INCOME_MARKET_GROSS_SALES] DECIMAL (18, 2) NULL,
    [UK_EQUITY_AND_BOND_INCOME_OWN_NET_SALES]      DECIMAL (18, 2) NULL,
    [UK_EQUITY_AND_BOND_INCOME_MARKET_NET_SALES]   DECIMAL (18, 2) NULL,
    [UK_ALL_COMPANIES_OWN_GROSS_SALES]             DECIMAL (18, 2) NULL,
    [UK_ALL_COMPANIES_MARKET_GROSS_SALES]          DECIMAL (18, 2) NULL,
    [UK_ALL_COMPANIES_OWN_NET_SALES]               DECIMAL (18, 2) NULL,
    [UK_ALL_COMPANIES_MARKET_NET_SALES]            DECIMAL (18, 2) NULL,
    [GLOBAL_EQUITY_INCOME_OWN_GROSS_SALES]         DECIMAL (18, 2) NULL,
    [GLOBAL_EQUITY_INCOME_MARKET_GROSS_SALES]      DECIMAL (18, 2) NULL,
    [GLOBAL_EQUITY_INCOME_OWN_NET_SALES]           DECIMAL (18, 2) NULL,
    [GLOBAL_EQUITY_INCOME_MARKET_NET_SALES]        DECIMAL (18, 2) NULL,
    [SPECIALIST_OWN_GROSS_SALES]                   DECIMAL (18, 2) NULL,
    [SPECIALIST_MARKET_GROSS_SALES]                DECIMAL (18, 2) NULL,
    [SPECIALIST_OWN_NET_SALES]                     DECIMAL (18, 2) NULL,
    [SPECIALIST_MARKET_NET_SALES]                  DECIMAL (18, 2) NULL,
    [FILE_NAME]                                    VARCHAR (100)   NOT NULL,
    [FILE_DATE]                                    DATETIME        NOT NULL,
    [FILE_TYPE]                                    VARCHAR (20)    NOT NULL,
    [CADIS_SYSTEM_INSERTED]                        DATETIME        CONSTRAINT [DF_staging_Matrix_FCDataFeed_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                         DATETIME        CONSTRAINT [DF_staging_Matrix_FCDataFeed_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                       VARCHAR (50)    CONSTRAINT [DF_staging_Matrix_FCDataFeed_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                        INT             CONSTRAINT [DF_staging_Matrix_FCDataFeed_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                       ROWVERSION      NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                    DATETIME        CONSTRAINT [DF_staging_Matrix_FCDataFeed_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__staging_Matrix_FCDataFeed] PRIMARY KEY CLUSTERED ([MTX_ACCOUNT_SIV_ID] ASC, [AS_AT_DATE] ASC) WITH (FILLFACTOR = 90)
);

