CREATE TABLE [Staging].[PrePay_LLP] (
    [Date]                VARCHAR (255) NULL,
    [Supplier]            VARCHAR (255) NULL,
    [Ref]                 VARCHAR (255) NULL,
    [Trans_Number]        VARCHAR (255) NULL,
    [Nominal_Code]        VARCHAR (255) NULL,
    [ShortDescription]    VARCHAR (255) NULL,
    [InvoiceFrom]         VARCHAR (255) NULL,
    [InvoiceTo]           VARCHAR (255) NULL,
    [DaysApportionment]   VARCHAR (255) NULL,
    [NetValue]            VARCHAR (255) NULL,
    [April]               VARCHAR (255) NULL,
    [May]                 VARCHAR (255) NULL,
    [June]                VARCHAR (255) NULL,
    [July]                VARCHAR (255) NULL,
    [August]              VARCHAR (255) NULL,
    [September]           VARCHAR (255) NULL,
    [October]             VARCHAR (255) NULL,
    [November]            VARCHAR (255) NULL,
    [December]            VARCHAR (255) NULL,
    [January]             VARCHAR (255) NULL,
    [February]            VARCHAR (255) NULL,
    [March]               VARCHAR (255) NULL,
    [CD]                  VARCHAR (255) NULL,
    [RowId]               INT           IDENTITY (1, 1) NOT NULL,
    [DepartmentNo]        SMALLINT      DEFAULT ((-1)) NOT NULL,
    [DepartmentId]        SMALLINT      DEFAULT ((-1)) NOT NULL,
    [NominalCode]         INT           DEFAULT ((-1)) NOT NULL,
    [AccountHierarchyId]  SMALLINT      DEFAULT ((-1)) NOT NULL,
    [SupplierName]        [sysname]     DEFAULT ('-1') NOT NULL,
    [SupplierId]          SMALLINT      DEFAULT ((-1)) NOT NULL,
    [FinancialLineTypeId] SMALLINT      DEFAULT ((-1)) NOT NULL,
    [AccountCategoryId]   SMALLINT      DEFAULT ((-1)) NOT NULL,
    [TransactionTypeId]   SMALLINT      DEFAULT ((-1)) NOT NULL,
    [TransactionNo]       INT           DEFAULT ((-1)) NOT NULL,
    [TaxCode]             CHAR (3)      DEFAULT ('-1') NOT NULL,
    [TaxCode2]            CHAR (3)      DEFAULT ('-1') NOT NULL,
    [TaxCode3]            CHAR (3)      DEFAULT ('-1') NOT NULL,
    CONSTRAINT [XPKPrePay_LLP] PRIMARY KEY CLUSTERED ([RowId] ASC)
);

