CREATE TABLE [Staging].[SALESFORCE_PRINCIPALLINK] (
    [CHILD_SF_ID]       VARCHAR (100) NOT NULL,
    [PARENT_SF_ID]      VARCHAR (100) NOT NULL,
    [AS_AT_DATE]        DATETIME      DEFAULT (CONVERT([datetime],CONVERT([varchar](12),getdate()))) NOT NULL,
    [RELATIONSHIP_TYPE] VARCHAR (20)  NULL,
    [SOURCE]            VARCHAR (20)  NULL,
    [URL]               VARCHAR (MAX) NULL,
    CONSTRAINT [PK__T_MATRIX_PRINCIPALLINK] PRIMARY KEY CLUSTERED ([CHILD_SF_ID] ASC, [PARENT_SF_ID] ASC, [AS_AT_DATE] ASC) WITH (FILLFACTOR = 90)
);

