CREATE TABLE [TCA].[EMSX_Trade_Fill_Output] (
    [DecisionDateTime]          DATETIME        NULL,
    [OrderId]                   INT             NULL,
    [OrderStartDateTime]        DATETIME        NULL,
    [OrderSize]                 DECIMAL (19, 4) NULL,
    [ReleaseId]                 VARCHAR (40)    NULL,
    [ReleaseDateTime]           DATETIME        NULL,
    [TraderBlockId]             INT             NULL,
    [TraderDateTime]            DATETIME        NULL,
    [TraderSize]                DECIMAL (19, 4) NULL,
    [BrokerBlockId]             VARCHAR (50)    NULL,
    [BrokerId]                  VARCHAR (20)    NULL,
    [BrokerDateTime]            DATETIME        NULL,
    [BrokerSize]                DECIMAL (19, 4) NULL,
    [TransactionSequence]       INT             NULL,
    [Symbol]                    VARCHAR (12)    NULL,
    [SymbolType]                VARCHAR (10)    NULL,
    [Side]                      VARCHAR (5)     NULL,
    [Shares]                    DECIMAL (19, 4) NULL,
    [TradeDateTime]             DATETIME        NULL,
    [Price]                     DECIMAL (19, 4) NULL,
    [Trader]                    VARCHAR (12)    NULL,
    [Exchange]                  VARCHAR (20)    NULL,
    [Country]                   VARCHAR (10)    NULL,
    [UDMPMLIMITPRICE]           DECIMAL (18, 6) NULL,
    [UDMSTRATEGY]               VARCHAR (15)    NULL,
    [UDMPMINSTRUCTIONS]         VARCHAR (511)   NULL,
    [UDMPMORDERREASON]          VARCHAR (15)    NULL,
    [UDMBROKERVENUE]            VARCHAR (15)    NULL,
    [UDMBROKERORDERTYPE]        VARCHAR (7)     NULL,
    [ALGONAME]                  VARCHAR (15)    NULL,
    [LASTLIQUIDITYIND]          INT             NULL,
    [LASTCAPACITY]              INT             NULL,
    [AggregatedTo]              VARCHAR (10)    NULL,
    [AggregatedFrom]            VARCHAR (10)    NULL,
    [Instructions]              VARCHAR (511)   NULL,
    [TIF]                       VARCHAR (7)     NULL,
    [SEDOL]                     VARCHAR (15)    NULL,
    [Order_Type]                VARCHAR (7)     NULL,
    [PM_Name]                   VARCHAR (15)    NULL,
    [Exec_Brkr]                 VARCHAR (255)   NULL,
    [Route_Instructions]        VARCHAR (511)   NULL,
    [Tran_Limit_Price]          DECIMAL (18, 6) NULL,
    [Tran_Account]              VARCHAR (15)    NULL,
    [Tran_Handling_Instruction] VARCHAR (7)     NULL,
    [Tran_Exec_Instruction]     INT             NULL,
    [CFD_Flag]                  VARCHAR (1)     NULL,
    [Exec_Seq_Number]           INT             NULL,
    [Exec_Prev_Seq_Number]      INT             NULL
);

