CREATE TABLE [TCA].[T_TCAOrderRegister_AggregatedArchive] (
    [OrderId]                           INT              NOT NULL,
    [IsResolved]                        BIT              NULL,
    [SECURITY_NAME]                     VARCHAR (255)    NULL,
    [SIDE]                              VARCHAR (7)      NULL,
    [ORDERSHARES]                       DECIMAL (24, 10) NULL,
    [IsOrderFilled]                     BIT              NULL,
    [TOTAL_VALUE]                       DECIMAL (38, 10) NULL,
    [TRADER]                            VARCHAR (15)     NULL,
    [TraderPersonId]                    SMALLINT         NULL,
    [TCAException]                      VARCHAR (100)    NULL,
    [COUNTRY]                           VARCHAR (7)      NULL,
    [DAYSTOCOMPLETION]                  INT              NULL,
    [FILLED_PERCENT_OF_INTERVAL_VOLUME] DECIMAL (38, 10) NULL,
    [ORDER_PERCENT_OF_INTERVAL_VOLUME]  DECIMAL (38, 10) NULL,
    [PM_ORDER_TYPE]                     VARCHAR (255)    NULL,
    [B1ORIGBENCHPRICE]                  DECIMAL (24, 10) NULL,
    [B1PRETRADECOST]                    DECIMAL (24, 10) NULL,
    [B2ORIGBENCHPRICE]                  DECIMAL (24, 10) NULL,
    [B2PRETRADECOST]                    DECIMAL (24, 10) NULL,
    [ORDER_START_DATE_TIME]             DATETIME         NULL,
    [ORDER_END_DATE_TIME]               DATETIME         NULL,
    [Brokers]                           VARCHAR (2000)   NOT NULL,
    [Accounts]                          VARCHAR (2000)   NOT NULL,
    [ORIG_PRICE]                        DECIMAL (24, 10) NULL,
    [FILLED_PERCENT_OF_DAILY_VOLUME]    DECIMAL (38, 10) NULL,
    [B1REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B1NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B1NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B1TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B1MODELADJUSTEDARRIVAL]            DECIMAL (38, 10) NULL,
    [B2REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B2NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B2NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B2TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B3REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B3NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B3MODELADJUSTEDARRIVAL]            DECIMAL (38, 10) NULL,
    [B3NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B3TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B4REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B4NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B4NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B4TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B5REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B5NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B5NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B5TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B6REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B6NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B6NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B6TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B7REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B7NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B7NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B7TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B8REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B8NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B8NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B8TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B9REALISEDCOSTBPS]                 DECIMAL (38, 10) NULL,
    [B9NETPCTCST]                       DECIMAL (38, 10) NULL,
    [B9NETREALDOLLAR]                   DECIMAL (38, 10) NULL,
    [B9TOTALDLRCOST]                    DECIMAL (38, 10) NULL,
    [B10REALISEDCOSTBPS]                DECIMAL (38, 10) NULL,
    [B10NETPCTCST]                      DECIMAL (38, 10) NULL,
    [B10NETREALDOLLAR]                  DECIMAL (38, 10) NULL,
    [B10TOTALDLRCOST]                   DECIMAL (38, 10) NULL,
    [ChannelName]                       VARCHAR (100)    NULL,
    [ChannelId]                         VARCHAR (50)     NULL,
    [DocumentationFolderLink]           VARCHAR (2000)   NULL,
    [JoinGUID]                          UNIQUEIDENTIFIER NOT NULL,
    [CADIS_SYSTEM_INSERTED]             DATETIME         NULL,
    [CADIS_SYSTEM_UPDATED]              DATETIME         NULL,
    [CADIS_SYSTEM_CHANGEDBY]            NVARCHAR (50)    NULL,
    [CADIS_SYSTEM_PRIORITY]             INT              NULL,
    [CADIS_SYSTEM_TIMESTAMP]            ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]         DATETIME         NULL
);

