CREATE TABLE [TCA].[Trade_Order_Output] (
    [DecisionDateTime]   DATETIME        NULL,
    [OrderId]            INT             NULL,
    [OrderStartDateTime] DATETIME        NULL,
    [OrderSize]          DECIMAL (19, 4) NULL,
    [ReleaseId]          VARCHAR (40)    NULL,
    [ReleaseDateTime]    DATETIME        NULL,
    [TraderBlockId]      INT             NULL,
    [TraderDateTime]     DATETIME        NULL,
    [TraderSize]         DECIMAL (19, 4) NULL,
    [BrokerId]           VARCHAR (20)    NULL,
    [BrokerDateTime]     DATETIME        NULL,
    [BrokerSize]         DECIMAL (19, 4) NULL,
    [Symbol]             VARCHAR (12)    NULL,
    [SymbolType]         VARCHAR (10)    NULL,
    [Side]               VARCHAR (5)     NULL,
    [Shares]             DECIMAL (19, 4) NULL,
    [AllocationDateTime] DATETIME        NULL,
    [Price]              DECIMAL (19, 4) NULL,
    [Account]            VARCHAR (20)    NULL,
    [Trader]             VARCHAR (12)    NULL,
    [Exchange]           VARCHAR (20)    NULL,
    [Country]            VARCHAR (10)    NULL,
    [Currency]           VARCHAR (10)    NULL,
    [UDMFUND]            VARCHAR (20)    NULL,
    [UDMSTRATEGY]        VARCHAR (60)    NULL,
    [UDMPMINSTRUCTIONS]  VARCHAR (50)    NULL,
    [UDMPMORDERREASON]   VARCHAR (5)     NULL,
    [UDMTRADEDESK]       VARCHAR (20)    NULL,
    [UDMPROGRAMID]       VARCHAR (20)    NULL,
    [TRADEID]            VARCHAR (10)    NULL,
    [SalesCommission]    DECIMAL (19, 4) NULL,
    [BrokerCommission]   DECIMAL (19, 4) NULL,
    [ExchangeFee]        DECIMAL (19, 4) NULL,
    [WithholdingTax]     DECIMAL (19, 4) NULL,
    [TransferTax]        DECIMAL (19, 4) NULL,
    [StampDuty]          DECIMAL (19, 4) NULL,
    [MiscellaneousFee]   DECIMAL (19, 4) NULL,
    [Dividend]           VARCHAR (20)    NULL,
    [DividendCCY]        VARCHAR (20)    NULL,
    [SpecialDividend]    VARCHAR (20)    NULL,
    [SpecialDividendCCY] VARCHAR (20)    NULL,
    [Note1]              VARCHAR (20)    NULL,
    [Note2]              VARCHAR (20)    NULL,
    [Note3]              VARCHAR (20)    NULL,
    [C_EVENT]            VARCHAR (30)    NULL,
    [AggregatedTo]       VARCHAR (10)    NULL,
    [AggregatedFrom]     VARCHAR (10)    NULL,
    [C_SECURITY]         VARCHAR (30)    NULL
);

