CREATE PROCEDURE [CADIS_PROC].[SPDM_MP2_SOURCE207_REALIGN_REALIGNPROVISIONAL]
@OldCADISId INT, @CADISRowId INT, @ChangedBy NVARCHAR (100), @ChangedDate DATETIME, @Comment NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


