CREATE PROCEDURE [CADIS_PROC].[SPDM_MP2_SOURCE207_REALIGN_MATCH]
@OldCADISId INT, @NewCADISId INT, @ChangedBy NVARCHAR (100), @ChangedDate DATETIME, @AssignedCADISId INT OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


