CREATE TABLE [Operation].[CorporateActionsRegister] (
    [CorporateActionsRegisterId] INT              IDENTITY (1, 1) NOT NULL,
    [OperationsSalesforceId]     VARCHAR (18)     NULL,
    [SecurityNameBK]             [sysname]        NOT NULL,
    [OperationRoleId]            SMALLINT         NULL,
    [RecorderNameId]             SMALLINT         NULL,
    [FiledDate]                  DATE             NULL,
    [ISIN]                       VARCHAR (25)     NULL,
    [CorporateActionDate]        DATE             NULL,
    [RecordDate]                 DATE             NULL,
    [DeadlineDate]               DATETIME         NULL,
    [InvestmentRoleId]           SMALLINT         NULL,
    [FundManagerSalesforceId]    VARCHAR (18)     NULL,
    [DecisionMakerId]            SMALLINT         NULL,
    [Decision]                   VARCHAR (2048)   NULL,
    [OperationsNotes]            VARCHAR (MAX)    NULL,
    [InvestmentNotes]            VARCHAR (MAX)    NULL,
    [NTReportDocumentationLink]  VARCHAR (2000)   NULL,
    [Status]                     VARCHAR (50)     NULL,
    [EventType]                  VARCHAR (50)     NULL,
    [DocumentationFolderLink]    VARCHAR (2000)   NULL,
    [WorkflowVersionGUID]        UNIQUEIDENTIFIER NULL,
    [JoinGUID]                   UNIQUEIDENTIFIER NOT NULL,
    [CADIS_SYSTEM_INSERTED]      DATETIME         CONSTRAINT [DF_CAR_CACDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_UPDATED]       DATETIME         CONSTRAINT [DF_CAR_CALMDT] DEFAULT (getdate()) NOT NULL,
    [EDM_SEC_ID]                 INT              NULL,
    [CADIS_SYSTEM_CHANGEDBY]     NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PKCorporateActionsRegister] PRIMARY KEY CLUSTERED ([CorporateActionsRegisterId] ASC),
    CONSTRAINT [CorporateActionsDecisionMakerId] FOREIGN KEY ([DecisionMakerId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [CorporateActionsInvestmentRoleID] FOREIGN KEY ([InvestmentRoleId]) REFERENCES [Core].[Roles] ([RoleId]),
    CONSTRAINT [CorporateActionsRecorderNameId] FOREIGN KEY ([RecorderNameId]) REFERENCES [Core].[Persons] ([PersonId])
);

