CREATE TABLE [Operation].[PlacingsRegister] (
    [PlacingRegisterId]            INT              IDENTITY (1, 1) NOT NULL,
    [PlacingName]                  VARCHAR (128)    NOT NULL,
    [PlacingStatus]                VARCHAR (128)    NOT NULL,
    [IsThisThroughABroker]         BIT              NULL,
    [BrokerContactName]            VARCHAR (128)    NULL,
    [BrokerSalesforceId]           VARCHAR (128)    NULL,
    [SubmitterPersonId]            SMALLINT         NOT NULL,
    [ProjectLeadId]                SMALLINT         NOT NULL,
    [InitialAllocations]           VARCHAR (2048)   NULL,
    [FundCode]                     VARCHAR (16)     NULL,
    [SettlementType]               VARCHAR (25)     NULL,
    [SettlementInstructions]       VARCHAR (MAX)    NULL,
    [SettlementDate]               DATETIME         NULL,
    [TradeDate]                    DATETIME         NULL,
    [EstimatedDate]                DATETIME         NULL,
    [ApprovalDate]                 DATETIME         NULL,
    [PaymentMethod]                VARCHAR (128)    NULL,
    [Ticker]                       VARCHAR (20)     NULL,
    [IsStopRequiredYesNo]          BIT              NULL,
    [AddedToStopListYesNo]         BIT              NULL,
    [DateStopped]                  DATETIME         NULL,
    [IPOorPlacing]                 VARCHAR (128)    NOT NULL,
    [Notes]                        VARCHAR (MAX)    NULL,
    [JiraIssueKey]                 VARCHAR (128)    NULL,
    [IrrevocableYesNo]             BIT              NULL,
    [OperationsComments]           VARCHAR (MAX)    NULL,
    [DealDocumentationFolderLink]  VARCHAR (2000)   NULL,
    [AllocDocumentationFolderLink] VARCHAR (2000)   NULL,
    [AdditionalFolderLink]         VARCHAR (2000)   NULL,
    [RaiseAmount]                  DECIMAL (18, 6)  NULL,
    [Exchange]                     VARCHAR (100)    NULL,
    [WestJiraTaskKey]              VARCHAR (20)     NULL,
    [PreMoneyRange]                VARCHAR (100)    NULL,
    [IsFCARegulated]               BIT              NULL,
    [IsSRARegulated]               BIT              NULL,
    [JoinGUID]                     UNIQUEIDENTIFIER NOT NULL,
    [PlacingCreationDatetime]      DATETIME         CONSTRAINT [DF_PR_PCDT] DEFAULT (getdate()) NOT NULL,
    [PlacingLastModifiedDatetime]  DATETIME         CONSTRAINT [DF_PR_PLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]        DATETIME         CONSTRAINT [DF_PR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]         DATETIME         CONSTRAINT [DF_PR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]       NVARCHAR (50)    CONSTRAINT [DF_PR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]        INT              CONSTRAINT [DF_PR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]       ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]    DATETIME         CONSTRAINT [DF_PR_CSL] DEFAULT (getdate()) NULL,
    [IsUnquoted]                   BIT              NULL,
    CONSTRAINT [PKPlacingsRegister] PRIMARY KEY CLUSTERED ([PlacingRegisterId] ASC),
    CONSTRAINT [PlacingsRegisterProjectLeadId] FOREIGN KEY ([ProjectLeadId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [PlacingsRegisterSubmitterPersonId] FOREIGN KEY ([SubmitterPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

