CREATE TABLE [Operation].[WEIFFeederFundPrice] (
    [ValuationDate]             DATE            NOT NULL,
    [PriorDate]                 DATE            NULL,
    [Account]                   BIGINT          NOT NULL,
    [Class]                     INT             NOT NULL,
    [Series]                    NVARCHAR (127)  NOT NULL,
    [Name]                      NVARCHAR (127)  NOT NULL,
    [SEDOL]                     NVARCHAR (63)   NULL,
    [Currency]                  CHAR (3)        NULL,
    [Units]                     DECIMAL (18, 6) NOT NULL,
    [NetAssets]                 DECIMAL (18, 2) NOT NULL,
    [PriorNetAssets]            DECIMAL (18, 2) NULL,
    [NAVperUnit]                FLOAT (53)      NULL,
    [PriorNAVperUnit]           FLOAT (53)      NULL,
    [NAVChange]                 FLOAT (53)      NULL,
    [BidSpread]                 FLOAT (53)      NULL,
    [BidPrice]                  FLOAT (53)      NULL,
    [OfferSpread]               FLOAT (53)      NULL,
    [OfferPrice]                FLOAT (53)      NULL,
    [IndexChange]               FLOAT (53)      NULL,
    [Filename]                  NVARCHAR (511)  NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        CONSTRAINT [DF_wffp_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        CONSTRAINT [DF_wffp_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   CONSTRAINT [DF_wffp_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             CONSTRAINT [DF_wffp_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION      NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        CONSTRAINT [DF_wffp_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKWEIFFeederFundPrice] PRIMARY KEY CLUSTERED ([ValuationDate] DESC, [Account] ASC, [Class] ASC)
);

