CREATE TABLE [Investment].[DvdForecastCalcOverride] (
    [DvdForecastCalcOverrideId]                   INT              IDENTITY (1, 1) NOT NULL,
    [FUND_SHORT_NAME]                             VARCHAR (20)     NULL,
    [EDM_SEC_ID]                                  INT              NOT NULL,
    [SECURITY_NAME]                               VARCHAR (100)    NULL,
    [Qtr]                                         CHAR (5)         NULL,
    [EX_DATE]                                     DATE             NULL,
    [PrevDvdValue]                                DECIMAL (18, 6)  NULL,
    [DVD_VALUE]                                   DECIMAL (18, 6)  NULL,
    [POSITION]                                    DECIMAL (15, 2)  NULL,
    [DIVIDEND_CCY]                                VARCHAR (10)     NULL,
    [WITHHOLDING_TAX]                             DECIMAL (26, 6)  NULL,
    [OverrideExDate]                              DATE             NULL,
    [OverrideDvdValue]                            DECIMAL (18, 6)  NULL,
    [OverrideSpecialCumShares]                    DECIMAL (15, 2)  NULL,
    [GrossDvdValue]                               DECIMAL (28, 6)  NULL,
    [NetDvdValue]                                 DECIMAL (28, 6)  NULL,
    [SpecialCumTrades]                            DECIMAL (28, 6)  NULL,
    [PrevTotalNetDvd]                             DECIMAL (28, 6)  NULL,
    [TotalNetDvd]                                 DECIMAL (28, 6)  NULL,
    [NTCustodyNetAmountBase]                      DECIMAL (28, 6)  NULL,
    [NTCustodyReconDiff]                          DECIMAL (18, 2)  NULL,
    [NTCustodyCommentary]                         VARCHAR (MAX)    NULL,
    [NTCustodyDvdChangeReasonId]                  INT              NULL,
    [UseNTCustodyValue]                           VARCHAR (10)     CONSTRAINT [DF_DFCO_DFCOUNTCV] DEFAULT ('TDB') NOT NULL,
    [NTFAValueBase]                               DECIMAL (28, 6)  NULL,
    [NTFAReconDiff]                               DECIMAL (18, 2)  NULL,
    [NTFACommentary]                              VARCHAR (MAX)    NULL,
    [UseNTFAValue]                                VARCHAR (10)     CONSTRAINT [DF_DFCO_DFCOUFAV] DEFAULT ('TDB') NOT NULL,
    [SubmittedByPersonId]                         SMALLINT         CONSTRAINT [DF_DFCO_DFCOSP] DEFAULT ((-1)) NOT NULL,
    [OverrideDvdChangeReasonId]                   INT              NULL,
    [OverrideCommentary]                          VARCHAR (MAX)    NULL,
    [IsActive]                                    BIT              CONSTRAINT [DF_DFCO_DFCOIA] DEFAULT ((1)) NOT NULL,
    [JoinGUID]                                    UNIQUEIDENTIFIER NOT NULL,
    [DvdForecastCalcOverrideCreationDatetime]     DATETIME         CONSTRAINT [DF_DFCO_DFCOCDT] DEFAULT (getdate()) NOT NULL,
    [DvdForecastCalcOverrideLastModifiedDatetime] DATETIME         CONSTRAINT [DF_DFCO_DFCOLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                       DATETIME         CONSTRAINT [DF_DFCO_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                        DATETIME         CONSTRAINT [DF_DFCO_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                      NVARCHAR (50)    CONSTRAINT [DF_DFCO_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                       INT              CONSTRAINT [DF_DFCO_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                      ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                   DATETIME         CONSTRAINT [DF_DFCO_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKDvdForecastCalcOverride] PRIMARY KEY CLUSTERED ([DvdForecastCalcOverrideId] ASC),
    CONSTRAINT [DvdForecastCalcOverrideNTCustodyDvdChangeReasonId] FOREIGN KEY ([NTCustodyDvdChangeReasonId]) REFERENCES [Investment].[DvdChangeReasons] ([DvdChangeReasonId]),
    CONSTRAINT [DvdForecastCalcOverrideOverrideDvdChangeReasonId] FOREIGN KEY ([OverrideDvdChangeReasonId]) REFERENCES [Investment].[DvdChangeReasons] ([DvdChangeReasonId]),
    CONSTRAINT [DvdForecastCalcOverrideSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

