CREATE TABLE [Investment].[DvdFundSecurityCalc] (
    [FUND_SHORT_NAME]                         VARCHAR (20)     NOT NULL,
    [DvdForecastCalcOverrideId]               INT              NOT NULL,
    [POSITION]                                DECIMAL (15, 2)  NULL,
    [GrossDvdValue]                           DECIMAL (28, 6)  NULL,
    [NetDvdValue]                             DECIMAL (28, 6)  NULL,
    [SpecialCumTrades]                        DECIMAL (28, 6)  NULL,
    [TotalNetDvd]                             DECIMAL (28, 6)  NULL,
    [NTCustodyNetAmountBase]                  DECIMAL (28, 6)  NULL,
    [NTCustodyReconDiff]                      DECIMAL (18, 2)  NULL,
    [NTCustodyCommentary]                     VARCHAR (MAX)    NULL,
    [NTCustodyDvdChangeReasonId]              INT              NULL,
    [UseNTCustodyValue]                       VARCHAR (10)     CONSTRAINT [DF_DFSC_DFCOUNTCV] DEFAULT ('TDB') NOT NULL,
    [NTFAValueBase]                           DECIMAL (28, 6)  NULL,
    [NTFAReconDiff]                           DECIMAL (18, 2)  NULL,
    [NTFACommentary]                          VARCHAR (MAX)    NULL,
    [UseNTFAValue]                            VARCHAR (10)     CONSTRAINT [DF_DFSC_DFCOUFAV] DEFAULT ('TDB') NOT NULL,
    [SubmittedByPersonId]                     SMALLINT         CONSTRAINT [DF_DFSC_DFCOSP] DEFAULT ((-1)) NOT NULL,
    [IsActive]                                BIT              CONSTRAINT [DF_DFSC_DFSCIA] DEFAULT ((1)) NOT NULL,
    [JoinGUID]                                UNIQUEIDENTIFIER NOT NULL,
    [DvdFundSecurityCalcCreationDatetime]     DATETIME         CONSTRAINT [DF_DFSC_DFSCCDT] DEFAULT (getdate()) NOT NULL,
    [DvdFundSecurityCalcLastModifiedDatetime] DATETIME         CONSTRAINT [DF_DFSC_DFSCLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                   DATETIME         CONSTRAINT [DF_DFSC_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                    DATETIME         CONSTRAINT [DF_DFSC_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                  NVARCHAR (50)    CONSTRAINT [DF_DFSC_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                   INT              CONSTRAINT [DF_DFSC_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                  ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]               DATETIME         CONSTRAINT [DF_DFSC_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKDvdFundSecurityCalc] PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [DvdForecastCalcOverrideId] ASC),
    CONSTRAINT [DvdFundSecurityCalcDvdForecastCalcOverrideId] FOREIGN KEY ([DvdForecastCalcOverrideId]) REFERENCES [Investment].[DvdForecastCalcOverride] ([DvdForecastCalcOverrideId]),
    CONSTRAINT [DvdFundSecurityCalcSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

