CREATE TABLE [Investment].[DvdNTCalcHighLevelOverride] (
    [FUND_SHORT_NAME]                                VARCHAR (20)     NOT NULL,
    [Qtr]                                            CHAR (5)         NOT NULL,
    [DATE]                                           DATE             NULL,
    [NetIncome]                                      DECIMAL (28, 6)  NULL,
    [UnitsInIssue]                                   DECIMAL (18, 4)  NULL,
    [PrevDvdRate]                                    DECIMAL (18, 6)  NULL,
    [DvdRate]                                        DECIMAL (18, 6)  NULL,
    [NTFAReconDiff]                                  DECIMAL (18, 2)  NULL,
    [OverrideNetIncome]                              DECIMAL (28, 6)  NULL,
    [OverrideUnitsInIssue]                           DECIMAL (18, 4)  NULL,
    [OverrideDvdChangeReasonId]                      INT              NULL,
    [OverrideCommentary]                             VARCHAR (MAX)    NULL,
    [SubmittedByPersonId]                            SMALLINT         CONSTRAINT [DF_DNTCHLO_DNTCHLOSP] DEFAULT ((-1)) NOT NULL,
    [IsActive]                                       BIT              CONSTRAINT [DF_DNTCHLO_DNTCHLOIA] DEFAULT ((1)) NOT NULL,
    [JoinGUID]                                       UNIQUEIDENTIFIER NOT NULL,
    [DvdNTCalcHighLevelOverrideCreationDatetime]     DATETIME         CONSTRAINT [DF_DNTCHLO_DNTCHLOCDT] DEFAULT (getdate()) NOT NULL,
    [DvdNTCalcHighLevelOverrideLastModifiedDatetime] DATETIME         CONSTRAINT [DF_DNTCHLO_DNTCHLOLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                          DATETIME         CONSTRAINT [DF_DNTCHLO_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                           DATETIME         CONSTRAINT [DF_DNTCHLO_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                         NVARCHAR (50)    CONSTRAINT [DF_DNTCHLO_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                          INT              CONSTRAINT [DF_DNTCHLO_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                         ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                      DATETIME         CONSTRAINT [DF_DNTCHLO_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKDvdNTCalcHighLevelOverride] PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [Qtr] ASC),
    CONSTRAINT [DvdNTCalcHighLevelOverrideOverrideDvdChangeReasonId] FOREIGN KEY ([OverrideDvdChangeReasonId]) REFERENCES [Investment].[DvdChangeReasons] ([DvdChangeReasonId]),
    CONSTRAINT [DvdNTCalcHighLevelOverrideSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

