CREATE TABLE [Investment].[EstablishedEvergreenVentures] (
    [Id]                        INT           NOT NULL,
    [Name]                      VARCHAR (63)  NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF_EEV_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF_EEV_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF_EEV_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF_EEV_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF_EEV_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [XPKEstablishedEvergreenVentures] PRIMARY KEY CLUSTERED ([Id] ASC)
);

