CREATE TABLE [Investment].[ShareClassWaiverRegister] (
    [ShareClassWaiverId]                           INT              IDENTITY (1, 1) NOT NULL,
    [AgentName]                                    NVARCHAR (256)   NOT NULL,
    [AccountName]                                  VARCHAR (256)    NULL,
    [Designation]                                  VARCHAR (50)     NULL,
    [AccountSalesforceId]                          VARCHAR (128)    NULL,
    [ContactSalesforceId]                          VARCHAR (128)    NULL,
    [SalesforceNoteId]                             VARCHAR (128)    NULL,
    [RequestedByPersonId]                          SMALLINT         NOT NULL,
    [RequestedDate]                                DATETIME         NOT NULL,
    [Status]                                       VARCHAR (50)     NULL,
    [BusinessCase]                                 VARCHAR (MAX)    NULL,
    [Decision]                                     VARCHAR (MAX)    NULL,
    [DecisionDate]                                 DATETIME         NULL,
    [DecisionByPersonId]                           SMALLINT         NULL,
    [SummaryDetails]                               VARCHAR (MAX)    NULL,
    [IndicativeFlowImmediately]                    VARCHAR (128)    NULL,
    [IndicativeFlowWithin12Months]                 VARCHAR (128)    NULL,
    [IsUSInvestor]                                 BIT              NULL,
    [IsUnregulated]                                BIT              NULL,
    [IsIndividual]                                 BIT              NULL,
    [MandateId]                                    INT              NULL,
    [BloombergId]                                  VARCHAR (31)     NULL,
    [ShareClassId]                                 INT              NULL,
    [JiraTaskKey]                                  VARCHAR (128)    NULL,
    [DocumentationFolderLink]                      VARCHAR (2000)   NULL,
    [JoinGUID]                                     UNIQUEIDENTIFIER NOT NULL,
    [ShareClassWaiverRegisterCreationDatetime]     DATETIME         CONSTRAINT [DF_SCWR_SCWRCDT] DEFAULT (getdate()) NOT NULL,
    [ShareClassWaiverRegisterLastModifiedDatetime] DATETIME         CONSTRAINT [DF_SCWR_SCWRLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                        DATETIME         CONSTRAINT [DF_SCWR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                         DATETIME         CONSTRAINT [DF_SCWR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                       NVARCHAR (50)    CONSTRAINT [DF_SCWR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                        INT              CONSTRAINT [DF_SCWR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                       ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                    DATETIME         CONSTRAINT [DF_SCWR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKShareClassWaiverRegister] PRIMARY KEY CLUSTERED ([ShareClassWaiverId] ASC),
    CONSTRAINT [ShareClassWaiverRegisterDecisionByPersonId] FOREIGN KEY ([DecisionByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ShareClassWaiverRegisterMandateId] FOREIGN KEY ([MandateId]) REFERENCES [Investment].[Mandates] ([MandateId]),
    CONSTRAINT [ShareClassWaiverRegisterRequestedByPersonId] FOREIGN KEY ([RequestedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ShareClassWaiverRegisterShareClassId] FOREIGN KEY ([ShareClassId]) REFERENCES [Investment].[ShareClass] ([ShareClassId])
);

