CREATE TABLE [Investment].[T_MASTER_PTY_RELATIONSHIP] (
    [EDM_PTY_ID]                INT           NOT NULL,
    [RELATED_EDM_PTY_ID]        INT           NOT NULL,
    [RELATIONSHIP_TYPE]         VARCHAR (50)  NOT NULL,
    [RELATIONSHIP_DESCRIPTION]  VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__0B54F04E] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__0C491487] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__0D3D38C0] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_MASTER___CADIS__0E315CF9] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__0F258132] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER__F87F2B11CC2C6285] PRIMARY KEY CLUSTERED ([EDM_PTY_ID] ASC, [RELATED_EDM_PTY_ID] ASC, [RELATIONSHIP_TYPE] ASC)
);

