CREATE TABLE [Investment].[T_MASTER_PTY_ROLE] (
    [EDM_PTY_ID]                INT           NOT NULL,
    [ROLE_TYPE]                 VARCHAR (50)  NOT NULL,
    [ACTIVE]                    VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__1201EDDD] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__12F61216] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__13EA364F] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_MASTER___CADIS__14DE5A88] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__15D27EC1] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER__83CF1AF61CE5F2DC] PRIMARY KEY CLUSTERED ([EDM_PTY_ID] ASC, [ROLE_TYPE] ASC)
);

