CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION545_INBOXINS]
@ENTITY VARCHAR (50), @SUB_ENTITY VARCHAR (50), @FIELD VARCHAR (100), @FIELD_VALUE VARCHAR (100), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @LOOKUP_VALUE VARCHAR (100), @LOOKUP_VALUE_UPDATE BIT, @CHAR_VALUE VARCHAR (50), @CHAR_VALUE_UPDATE BIT, @INT_VALUE INT, @INT_VALUE_UPDATE BIT, @SORT INT, @SORT_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


