CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION657_INBOXSELSINGLEROW]
@Sector VARCHAR (20), @CITI_CODE VARCHAR (4), @SECTOR1 VARCHAR (20), @PRICE_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


