CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION628_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @ORDER_ID INT, @BB_ACCOUNT VARCHAR (100), @TCA_ACCOUNT VARCHAR (50), @BB_ALLOCATED_QUANTITY DECIMAL (38, 6), @TCA_ALLOCATED_QUANTITY DECIMAL (38, 6)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


