CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION64_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @User_Login NVARCHAR (200), @GROUPNAME NVARCHAR (200)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


