CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION637_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @WatchlistEventId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @WatchlistRegisterId INT, @WatchlistRegisterId_UPDATE BIT, @EventTypeid INT, @EventTypeid_UPDATE BIT, @EventDetails VARCHAR (MAX), @EventDetails_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @EventTrueFalse BIT, @EventTrueFalse_UPDATE BIT, @JiraIssueKey VARCHAR (128), @JiraIssueKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


