CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION573_INBOXUPD]
@ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Name VARCHAR (100), @Name_UPDATE BIT, @SubsectorID SMALLINT, @SubsectorID_UPDATE BIT, @StatusID SMALLINT, @StatusID_UPDATE BIT, @Description VARCHAR (1000), @Description_UPDATE BIT, @InternalNotes VARCHAR (1000), @InternalNotes_UPDATE BIT, @SFAccountID VARCHAR (18), @SFAccountID_UPDATE BIT, @ReferrerSFContactID VARCHAR (18), @ReferrerSFContactID_UPDATE BIT, @BoxFolderID VARCHAR (15), @BoxFolderID_UPDATE BIT, @SubmittedBy VARCHAR (100), @SubmittedBy_UPDATE BIT, @CountryID INT, @CountryID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


