CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION546_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @ENTITY VARCHAR (50), @SUB_ENTITY VARCHAR (50), @FIELD VARCHAR (100), @FIELD_VALUE VARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


