CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION532_INBOXGROUPSEL]
@PCTGROWTH DECIMAL (20, 10), @DAYSFWD INT, @DAYSBCK INT, @FLOW DECIMAL (20, 2), @OVERDRAFT_AMT DECIMAL (20, 2), @OVERDRAFT_DATE DATETIME, @TRANSFER_AMT DECIMAL (20, 2), @TRANSFER_DATE DATETIME, @FLOWLAG INT, @CASH DECIMAL (20, 2), @WhereSQL NVARCHAR (MAX), @GroupColumns NVARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


