CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION611_INBOXUPD]
@ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @LegalName VARCHAR (255), @LegalName_UPDATE BIT, @CountryID INT, @CountryID_UPDATE BIT, @CurrencyID SMALLINT, @CurrencyID_UPDATE BIT, @SubsectorID SMALLINT, @SubsectorID_UPDATE BIT, @SFAccountID VARCHAR (18), @SFAccountID_UPDATE BIT, @BoxFolderID VARCHAR (18), @BoxFolderID_UPDATE BIT, @JiraEpicKey VARCHAR (18), @JiraEpicKey_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @FundManagerPersonID SMALLINT, @FundManagerPersonID_UPDATE BIT, @InvestmentAnalystPersonID SMALLINT, @InvestmentAnalystPersonID_UPDATE BIT, @CompanyNumber VARCHAR (255), @CompanyNumber_UPDATE BIT, @CompanyType VARCHAR (255), @CompanyType_UPDATE BIT, @KnownName VARCHAR (255), @KnownName_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


