CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION610_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATETIME, @FLOW_TYPE VARCHAR (100), @RECOGNITION_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


