CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION537_INBOXSELSINGLEROW]
@DAYSBCK INT, @DAYSFWD INT, @FUND_SHORT_NAME VARCHAR (6), @POSITION_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


