CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION628_INBOXSELSINGLEROW]
@ORDER_ID INT, @BB_ACCOUNT VARCHAR (100), @TCA_ACCOUNT VARCHAR (50), @BB_ALLOCATED_QUANTITY DECIMAL (38, 6), @TCA_ALLOCATED_QUANTITY DECIMAL (38, 6), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


