CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION666_INBOXSELSINGLEROW]
@GDPRRequestID INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


