CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION594_INBOXSELROWNUMBER]
@TDate DATE, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @Fund VARCHAR (10), @AsOfDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


