CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION642_INBOXUPD]
@ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FundingID INT, @FundingID_UPDATE BIT, @SecurityID INT, @SecurityID_UPDATE BIT, @AllocationAmount DECIMAL (18, 2), @AllocationAmount_UPDATE BIT, @RevaluationID INT, @RevaluationID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


