CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION537_INBOXSELROWNUMBER]
@DAYSBCK INT, @DAYSFWD INT, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (6), @POSITION_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


