CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION64_INBOXSELSINGLEROW]
@User_Login NVARCHAR (200), @GROUPNAME NVARCHAR (200), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


