CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION612_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Name VARCHAR (255), @Name_UPDATE BIT, @Ticker VARCHAR (20), @Ticker_UPDATE BIT, @IssuerID INT, @IssuerID_UPDATE BIT, @CurrencyID SMALLINT, @CurrencyID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


