CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION557_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @RiskOwnerId SMALLINT, @RiskOwnerId_UPDATE BIT, @SubCategoryID SMALLINT, @SubCategoryID_UPDATE BIT, @ProposedRiskAppetite VARCHAR (10), @ProposedRiskAppetite_UPDATE BIT, @StatusID INT, @StatusID_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @CreatedDate DATETIME, @CreatedDate_UPDATE BIT, @LastModifiedDate DATETIME, @LastModifiedDate_UPDATE BIT, @JiraIssueKey NVARCHAR (50), @JiraIssueKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @IndividualReview BIT, @IndividualReview_UPDATE BIT, @CurrentRiskAppetite VARCHAR (10), @CurrentRiskAppetite_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


