CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION600_INBOXINS]
@PLATFORM VARCHAR (50), @SOURCE VARCHAR (50), @ENTITY VARCHAR (50), @SUB_ENTITY VARCHAR (50), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @DESCRIPTION VARCHAR (200), @DESCRIPTION_UPDATE BIT, @DIRECTION VARCHAR (200), @DIRECTION_UPDATE BIT, @RECORDS INT, @RECORDS_UPDATE BIT, @TOLERANCE_PRECENT INT, @TOLERANCE_PRECENT_UPDATE BIT, @SOLUTION VARCHAR (200), @SOLUTION_UPDATE BIT, @TABLE_NAME VARCHAR (200), @TABLE_NAME_UPDATE BIT, @EXPECTED_TIME_GMT TIME (7), @EXPECTED_TIME_GMT_UPDATE BIT, @EXPECTED_TIME_TOLERANCE_MINUTES INT, @EXPECTED_TIME_TOLERANCE_MINUTES_UPDATE BIT, @EMAIL_RECIPIENT VARCHAR (200), @EMAIL_RECIPIENT_UPDATE BIT, @OWNER SMALLINT, @OWNER_UPDATE BIT, @SEND_SLACK BIT, @SEND_SLACK_UPDATE BIT, @SEND_EMAIL BIT, @SEND_EMAIL_UPDATE BIT, @IS_ACTIVE BIT, @IS_ACTIVE_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


