CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION534_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ISSUER VARCHAR (80), @ISSUER_UPDATE BIT, @EDM_SEC_ID INT, @EDM_SEC_ID_UPDATE BIT, @TRADE_DATE DATETIME, @TRADE_DATE_UPDATE BIT, @SETTLEMENT_DATE DATETIME, @SETTLEMENT_DATE_UPDATE BIT, @FUNDING_STATUS VARCHAR (20), @FUNDING_STATUS_UPDATE BIT, @IS_LEGAL BIT, @IS_LEGAL_UPDATE BIT, @IS_REPUTATIONAL BIT, @IS_REPUTATIONAL_UPDATE BIT, @FUNDING_TYPE VARCHAR (20), @FUNDING_TYPE_UPDATE BIT, @FUNDING_SUB_TYPE VARCHAR (20), @FUNDING_SUB_TYPE_UPDATE BIT, @PUSH_BACK_UNIT VARCHAR (1), @PUSH_BACK_UNIT_UPDATE BIT, @PUSH_BACK_MAGNITUDE INT, @PUSH_BACK_MAGNITUDE_UPDATE BIT, @PULL_FORWARD_UNIT VARCHAR (1), @PULL_FORWARD_UNIT_UPDATE BIT, @PULL_FORWARD_MAGNITUDE INT, @PULL_FORWARD_MAGNITUDE_UPDATE BIT, @TECH_STATUS VARCHAR (20), @TECH_STATUS_UPDATE BIT, @JiraIssueKey VARCHAR (18), @JiraIssueKey_UPDATE BIT, @IssuerID INT, @IssuerID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


