CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION668_INBOXUPD]
@SfAccountId VARCHAR (18), @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY VARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @AccountOwnerId VARCHAR (18), @AccountOwnerId_UPDATE BIT, @OverrideStatus VARCHAR (10), @OverrideStatus_UPDATE BIT, @Revert BIT, @Revert_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


