CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION636_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Identifier VARCHAR (100), @Identifier_UPDATE BIT, @WatchlistId INT, @WatchlistId_UPDATE BIT, @ReasonTypeId SMALLINT, @ReasonTypeId_UPDATE BIT, @StatusId INT, @StatusId_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @ReviewedByPersonId SMALLINT, @ReviewedByPersonId_UPDATE BIT, @AnticipatedRemovalDate DATETIME, @AnticipatedRemovalDate_UPDATE BIT, @DateSubmitted DATETIME, @DateSubmitted_UPDATE BIT, @JIRAIssueKey VARCHAR (255), @JIRAIssueKey_UPDATE BIT, @BoxLink VARCHAR (255), @BoxLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @Description VARCHAR (MAX), @Description_UPDATE BIT, @IdentifierTypeId SMALLINT, @IdentifierTypeId_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


