CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION646_INBOXSELSINGLEROW]
@CLIENT VARCHAR (50), @SamAccountName VARCHAR (150), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


