CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION584_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @OrderID INT, @Ticker VARCHAR (15), @Account VARCHAR (15)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


