CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION545_INBOXDEL]
@ENTITY VARCHAR (50), @SUB_ENTITY VARCHAR (50), @FIELD VARCHAR (100), @FIELD_VALUE VARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


