CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION560_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ClientRequestID INT, @ClientRequestID_UPDATE BIT, @EventType VARCHAR (120), @EventType_UPDATE BIT, @ReviewerID SMALLINT, @ReviewerID_UPDATE BIT, @SubmittedByPersonID INT, @SubmittedByPersonID_UPDATE BIT, @EventDetails VARCHAR (MAX), @EventDetails_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @EventStatus VARCHAR (50), @EventStatus_UPDATE BIT, @JiraIssueKey VARCHAR (120), @JiraIssueKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @EventTrueFalse BIT, @EventTrueFalse_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


