CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION590_INBOXSELSINGLEROW]
@PLATFORM VARCHAR (50), @SOURCE VARCHAR (50), @ENTITY VARCHAR (50), @SUB_ENTITY VARCHAR (50), @RUN_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


