CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION649_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @NAME NVARCHAR (100), @PARENTGROUPNAME NVARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


