CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION621_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @StopListId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @StoppedCompanyName NVARCHAR (128), @StoppedCompanyName_UPDATE BIT, @Ticker VARCHAR (50), @Ticker_UPDATE BIT, @StopListStatusId INT, @StopListStatusId_UPDATE BIT, @StoppedDate DATETIME, @StoppedDate_UPDATE BIT, @CleansedDate DATETIME, @CleansedDate_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


