CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION653_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (20), @INCOME_PERIOD_QTR INT, @INCOME_PERIOD_YR INT, @AS_AT_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


