CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION595_INBOXSELROWNUMBER]
@TDate DATE, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @Fund VARCHAR (10)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


