CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION535_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @NEW_ISSUER_ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @NEW_ISSUER VARCHAR (80), @NEW_ISSUER_UPDATE BIT, @SECURITY_ISO_CCY VARCHAR (3), @SECURITY_ISO_CCY_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


