CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION648_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @MemberName NVARCHAR (128), @RoleName NVARCHAR (128)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


