CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION531_VALUEDIST]
@PCTGROWTH DECIMAL (20, 10), @DAYSFWD INT, @DAYSBCK INT, @FLOW DECIMAL (20, 2), @OVERDRAFT_AMT DECIMAL (20, 2), @OVERDRAFT_DATE DATETIME, @TRANSFER_AMT DECIMAL (20, 2), @TRANSFER_DATE DATETIME, @FLOWLAG INT, @WhereSQL NVARCHAR (MAX), @FieldName NVARCHAR (250), @SampleSize INT, @PercentageSample BIT, @MaxRows INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


