CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION65_INBOXSELSINGLEROW]
@GUID NCHAR (32), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


