CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION617_INBOXSELSINGLEROW]
@CADIS_RUN_ID INT, @CADIS_ROW_ID INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


