CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION643_INBOXUPD]
@ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @SecurityAllocationID INT, @SecurityAllocationID_UPDATE BIT, @PortfolioID INT, @PortfolioID_UPDATE BIT, @AllocationAmount DECIMAL (18, 2), @AllocationAmount_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


