CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION675_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @UBOControllersID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @ChecklistID INT, @ChecklistID_UPDATE BIT, @Name VARCHAR (50), @Name_UPDATE BIT, @PersonType VARCHAR (2000), @PersonType_UPDATE BIT, @Details VARCHAR (2000), @Details_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @Controller BIT, @Controller_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


