CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION537_INBOXGROUPSEL]
@DAYSBCK INT, @DAYSFWD INT, @WhereSQL NVARCHAR (MAX), @GroupColumns NVARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


