CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION654_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (20), @INCOME_PERIOD_YR INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


