CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION647_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @CLIENT VARCHAR (50), @USER_NAME VARCHAR (250), @GROUPNAME VARCHAR (150)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


