CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION579_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ToolName NVARCHAR (255), @ToolName_UPDATE BIT, @ToolPurpose NVARCHAR (MAX), @ToolPurpose_UPDATE BIT, @ToolOwnerId SMALLINT, @ToolOwnerId_UPDATE BIT, @StatusId INT, @StatusId_UPDATE BIT, @LastReviewDate DATETIME, @LastReviewDate_UPDATE BIT, @NextReviewDate DATETIME, @NextReviewDate_UPDATE BIT, @TargetRetirementDate DATETIME, @TargetRetirementDate_UPDATE BIT, @ToolLink NVARCHAR (255), @ToolLink_UPDATE BIT, @IncludedInBIAAssessment BIT, @IncludedInBIAAssessment_UPDATE BIT, @JIRAIssueKey NVARCHAR (255), @JIRAIssueKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


