CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION671_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @EventTypeID SMALLINT, @EventTypeID_UPDATE BIT, @EventDetails VARCHAR (2000), @EventDetails_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @ChecklistID INT, @ChecklistID_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @JiraIssueKey NVARCHAR (50), @JiraIssueKey_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


