CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION529_INBOXSELROWNUMBER]
@REPORT_DATE DATETIME, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


