CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION616_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @YEAR INT, @MONTH INT, @Benchmark VARCHAR (6)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


