CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION53_AUDITLATESTCHANGE]
@SOURCE VARCHAR (30), @DESCRIPTION VARCHAR (50), @DIRECTION VARCHAR (3), @RUN_DATE DATETIME, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


