CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION649_INBOXSELSINGLEROW]
@NAME NVARCHAR (100), @PARENTGROUPNAME NVARCHAR (100), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


