CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION53_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @SOURCE VARCHAR (30), @DESCRIPTION VARCHAR (50), @DIRECTION VARCHAR (3), @RUN_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


