CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION607_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATETIME, @FLOW_TYPE VARCHAR (100), @RECOGNITION_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


