CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION559_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @RequestTypeID SMALLINT, @RequestTypeID_UPDATE BIT, @ClientName VARCHAR (150), @ClientName_UPDATE BIT, @ClientCompanyName VARCHAR (150), @ClientCompanyName_UPDATE BIT, @RelationshipManagerID SMALLINT, @RelationshipManagerID_UPDATE BIT, @ReviewerID SMALLINT, @ReviewerID_UPDATE BIT, @ClientAssessmentID VARCHAR (150), @ClientAssessmentID_UPDATE BIT, @JiraEpicKey VARCHAR (120), @JiraEpicKey_UPDATE BIT, @Status VARCHAR (50), @Status_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @CEOSignOffRequired BIT, @CEOSignOffRequired_UPDATE BIT, @DueDateOverride BIT, @DueDateOverride_UPDATE BIT, @DueDate DATETIME, @DueDate_UPDATE BIT, @SlackChannelName VARCHAR (150), @SlackChannelName_UPDATE BIT, @CoachingRequired BIT, @CoachingRequired_UPDATE BIT, @DocumentsRequired BIT, @DocumentsRequired_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


