CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION594_INBOXSELSINGLEROW]
@TDate DATE, @Fund VARCHAR (10), @AsOfDate DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


