CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION547_INBOXSELSINGLEROW]
@POST_CODE VARCHAR (20), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


