CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION536_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FUND_SHORT_NAME VARCHAR (20), @FUND_SHORT_NAME_UPDATE BIT, @ALLOCATION DECIMAL (24, 10), @ALLOCATION_UPDATE BIT, @FUNDING_ID INT, @FUNDING_ID_UPDATE BIT, @REVALUATION_ID INT, @REVALUATION_ID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


