CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION53_INBOXSELSINGLEROW]
@SOURCE VARCHAR (30), @DESCRIPTION VARCHAR (50), @DIRECTION VARCHAR (3), @RUN_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


