CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION633_INBOXSELSINGLEROW]
@TICKER VARCHAR (100), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


