CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION535_AUDITLATESTCHANGE]
@NEW_ISSUER_ID INT, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


