CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION533_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @REVALUATION_ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FUNDING_ID INT, @FUNDING_ID_UPDATE BIT, @ISSUER VARCHAR (80), @ISSUER_UPDATE BIT, @EDM_SEC_ID INT, @EDM_SEC_ID_UPDATE BIT, @REVALUATION_TYPE VARCHAR (255), @REVALUATION_TYPE_UPDATE BIT, @REVALUATION_SUB_TYPE VARCHAR (255), @REVALUATION_SUB_TYPE_UPDATE BIT, @EXPECTED_ENACTMENT_DATE DATETIME, @EXPECTED_ENACTMENT_DATE_UPDATE BIT, @ACTUAL_ENACTMENT_DATE DATETIME, @ACTUAL_ENACTMENT_DATE_UPDATE BIT, @FM_LOW DECIMAL (6, 3), @FM_LOW_UPDATE BIT, @FM_HIGH DECIMAL (6, 3), @FM_HIGH_UPDATE BIT, @DP_LOW DECIMAL (24, 10), @DP_LOW_UPDATE BIT, @DP_HIGH DECIMAL (24, 10), @DP_HIGH_UPDATE BIT, @ACD DECIMAL (24, 10), @ACD_UPDATE BIT, @STATUS_INTERNAL VARCHAR (255), @STATUS_INTERNAL_UPDATE BIT, @STATUS_EXTERNAL VARCHAR (255), @STATUS_EXTERNAL_UPDATE BIT, @TECH_STATUS VARCHAR (255), @TECH_STATUS_UPDATE BIT, @JiraIssueKey VARCHAR (18), @JiraIssueKey_UPDATE BIT, @IssuerID INT, @IssuerID_UPDATE BIT, @EDM_ISSUER_ID INT, @EDM_ISSUER_ID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


