CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION664_INBOXUPD]
@ReasonTypeId SMALLINT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ReasonName VARCHAR (100), @ReasonName_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


