CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION617_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @CADIS_RUN_ID INT, @CADIS_ROW_ID INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


