CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION574_INBOXSELSINGLEROW]
@ID SMALLINT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


