CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION665_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @RelatedPersonName VARCHAR (50), @RelatedPersonName_UPDATE BIT, @DateCreated DATETIME, @DateCreated_UPDATE BIT, @NextReviewDate DATETIME, @NextReviewDate_UPDATE BIT, @Summary VARCHAR (50), @Summary_UPDATE BIT, @Description VARCHAR (2000), @Description_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


