CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION673_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ChecklistID INT, @ChecklistID_UPDATE BIT, @FullName VARCHAR (50), @FullName_UPDATE BIT, @PersonDetails VARCHAR (2000), @PersonDetails_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @PoliticalPositionID INT, @PoliticalPositionID_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


