CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION598_INBOXSELROWNUMBER]
@TDate DATE, @Fund VARCHAR (10), @MaxDate DATE, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @Fund1 VARCHAR (15), @CCY VARCHAR (3), @CCY_NAME VARCHAR (30), @AsOfDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


