CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION623_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @StopListId INT, @StopListId_UPDATE BIT, @ReasonTypeId SMALLINT, @ReasonTypeId_UPDATE BIT, @StopListStatusId SMALLINT, @StopListStatusId_UPDATE BIT, @ReasonOwnerId SMALLINT, @ReasonOwnerId_UPDATE BIT, @RequesterPersonId SMALLINT, @RequesterPersonId_UPDATE BIT, @ReviewerPersonId SMALLINT, @ReviewerPersonId_UPDATE BIT, @InteractionId VARCHAR (20), @InteractionId_UPDATE BIT, @ComplianceJiraIssueKey VARCHAR (255), @ComplianceJiraIssueKey_UPDATE BIT, @JIRAIssueKey VARCHAR (255), @JIRAIssueKey_UPDATE BIT, @AnticipatedCleanseDate DATETIME, @AnticipatedCleanseDate_UPDATE BIT, @StoppedDate DATETIME, @StoppedDate_UPDATE BIT, @AdvisedDate DATETIME, @AdvisedDate_UPDATE BIT, @CleansedDate DATETIME, @CleansedDate_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


