CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION529_INBOXGROUPSEL]
@REPORT_DATE DATETIME, @WhereSQL NVARCHAR (MAX), @GroupColumns NVARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


