CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION553_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @RiskAppetiteKRIRegisterId INT, @RiskAppetiteKRIRegisterId_UPDATE BIT, @RiskKRIEventTypeID INT, @RiskKRIEventTypeID_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @RiskKRIEventDate DATETIME, @RiskKRIEventDate_UPDATE BIT, @RiskKRIEventDetails VARCHAR (2000), @RiskKRIEventDetails_UPDATE BIT, @JiraIssueKey NVARCHAR (50), @JiraIssueKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


