CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION591_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @SOURCE VARCHAR (50), @ENTITY VARCHAR (50), @SUB_ENTITY VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


