CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION558_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @SubCategoryId SMALLINT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CategoryId SMALLINT, @CategoryId_UPDATE BIT, @SubCategory NVARCHAR (127), @SubCategory_UPDATE BIT, @RiskAppetite NVARCHAR (25), @RiskAppetite_UPDATE BIT, @CreatedDate DATETIME, @CreatedDate_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


