CREATE TABLE [Unquoted].[CompanyStages] (
    [CompanyStage]              VARCHAR (5)   NOT NULL,
    [CompanyStageDescription]   VARCHAR (256) NOT NULL,
    [Sequence]                  SMALLINT      NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF_CS_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DFUCS_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF_CS_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF_CS_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF_CS_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKCompanyStages] PRIMARY KEY CLUSTERED ([CompanyStage] ASC)
);

