CREATE TABLE [Unquoted].[SecurityRevaluation] (
    [SecurityRevaluationId]               INT              IDENTITY (1, 1) NOT NULL,
    [SecurityBloombergId]                 VARCHAR (30)     NOT NULL,
    [EventType]                           VARCHAR (128)    NOT NULL,
    [EventOverview]                       VARCHAR (2000)   NOT NULL,
    [EventDate]                           DATETIME         NOT NULL,
    [FurtherFundingAmount]                DECIMAL (18, 6)  NULL,
    [Notes]                               NVARCHAR (MAX)   NULL,
    [PresentedToPricingCommittee]         BIT              NULL,
    [RevaluationPreviousPrice]            DECIMAL (18, 6)  NULL,
    [RevaluationPrice]                    DECIMAL (18, 6)  NULL,
    [RevaluationEndDate]                  DATETIME         NULL,
    [IsActive]                            BIT              NULL,
    [Status]                              VARCHAR (25)     NULL,
    [CurrencyCode]                        CHAR (3)         NULL,
    [IsComplete]                          BIT              NULL,
    [JiraIssueKey]                        VARCHAR (128)    NULL,
    [SubmittedByPersonId]                 SMALLINT         CONSTRAINT [DF_SR_CPI] DEFAULT ((-1)) NOT NULL,
    [DocumentationFolderLink]             VARCHAR (2000)   NULL,
    [JoinGUID]                            UNIQUEIDENTIFIER NOT NULL,
    [SecurityRevaluationCreationDate]     DATETIME         CONSTRAINT [DF_SR_SRCDT] DEFAULT (getdate()) NOT NULL,
    [SecurityRevaluationLastModifiedDate] DATETIME         CONSTRAINT [DF_SR_SRLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]               DATETIME         CONSTRAINT [DF_SR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                DATETIME         CONSTRAINT [DF_SR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]              NVARCHAR (50)    CONSTRAINT [DF_SR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]               INT              CONSTRAINT [DF_SR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]              ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]           DATETIME         CONSTRAINT [DF_SR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKSecurityRevaluation] PRIMARY KEY CLUSTERED ([SecurityRevaluationId] ASC),
    CONSTRAINT [SecurityRevaluationSecurityBloombergId] FOREIGN KEY ([SecurityBloombergId]) REFERENCES [Investment].[CompanySecurities] ([SecurityBloombergId]),
    CONSTRAINT [SecurityRevaluationSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

