CREATE TABLE [Unquoted].[Status] (
    [StatusId]               INT           IDENTITY (1, 1) NOT NULL,
    [StatusCode]             VARCHAR (300) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF_US_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF_US_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF_US_CSCB] DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PKStatus] PRIMARY KEY CLUSTERED ([StatusId] ASC)
);

