
CREATE FUNCTION [Access.WebDev].[ufn_GetAUMs]
(
	@PositionDate DATE = NULL
)
RETURNS  @Output TABLE (
	[FUND_SHORT_NAME] VARCHAR(256) NULL,
	[VALUATION_DATE] DATETIME NULL,
	[DESCRIPTION] VARCHAR(255) NULL,
	[VALUE] DECIMAL(18,2) NULL,
	[IsEstimate] BIT DEFAULT 1,
	[LastUpdatedDate] DATETIME NULL
	)
AS
BEGIN
	DECLARE @Date DATE

	IF @PositionDate IS NULL
	BEGIN
		SET @PositionDate = CONVERT(DATE,GETDATE())
	END

	SELECT @Date = MAX(POSITION_DATE) FROM [dbo].[T_MASTER_FND_MARKET_VALUE]
	WHERE CONVERT(DATE,POSITION_DATE) <= @PositionDate

  INSERT INTO @OUTPUT ([FUND_SHORT_NAME], [VALUATION_DATE], [DESCRIPTION], [VALUE], [IsEstimate], [LastUpdatedDate])
	SELECT LEFT([FUND_SHORT_NAME],6), POSITION_DATE, 'NT AUM', [TOTAL_ACCRUED_MARKET_VALUE_BASE], 0, [CADIS_SYSTEM_LASTMODIFIED]
	FROM [dbo].[T_MASTER_FND_MARKET_VALUE]
	WHERE CONVERT(DATE, [POSITION_DATE]) = @Date

UPDATE	i
SET		i.[VALUE] = ISNULL(i.[VALUE],0) - ISNULL(o.[VALUE],0)
FROM	@Output i
INNER	JOIN @output o
ON		i.VALUATION_DATE = o.VALUATION_DATE
AND		i.FUND_SHORT_NAME = 'WIMEIF'
AND		o.FUND_SHORT_NAME = 'WIMOFF'

	RETURN
END

