
CREATE	FUNCTION [Access.WebDev].[ufn_UnquotedConcHeadroomProjectionByFund] 
		(
		@DAYSBCK int,
		@DAYSFWD int
		)
RETURNS	TABLE

AS
RETURN
SELECT top 10000 FUND_SHORT_NAME, POSITION_DATE, CONCENTRATION_EOD, HEADROOM  FROM 
(
SELECT 'WIMEIF' AS FUND_SHORT_NAME, POSITION_DATE, CONCENTRATION_EOD, HEADROOM FROM [DBO].[UFN_UNQUOTED_PROJECTION_WIMEIF] (0, @DAYSBCK, @DAYSFWD, 0, 0, GETDATE(), 0, GETDATE(), 0)
UNION
SELECT 'OMNIS1' AS FUND_SHORT_NAME, POSITION_DATE, CONCENTRATION_EOD, HEADROOM FROM [DBO].[UFN_UNQUOTED_PROJECTION_OMNIS] (0, @DAYSBCK, @DAYSFWD, 0, 0, GETDATE(), 0, GETDATE(), 0)
UNION
SELECT 'WIMPCT' AS FUND_SHORT_NAME, POSITION_DATE, UQ_VS_GAV, GAV_HEADROOM FROM [DBO].[UFN_UNQUOTED_PROJECTION_WIMPCT] (0, @DAYSBCK, @DAYSFWD, 0, 0, GETDATE(), 0, GETDATE(), 0, 0)
) X
ORDER BY FUND_SHORT_NAME DESC, POSITION_DATE DESC

