CREATE PROCEDURE [CADIS_SYS].[SPCO_PACKAGELOGINS]
@GUID NCHAR (32), @NAME NVARCHAR (100), @DESCRIPTION NVARCHAR (500), @TYPE TINYINT, @VERSION NVARCHAR (100), @IMPORTMODE TINYINT, @PREIMPORTWARNINGS INT, @COMMANDLINEIMPORT BIT, @RETURNCODE TINYINT, @XMLDETAILS TEXT, @CHANGEDBY NVARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


