CREATE PROCEDURE CADIS_SYS.SPCO_ROLEUSERS
	@RoleName nvarchar(256)
AS
SELECT ROLENAME=R.NAME, USERNAME=U.NAME, U.ISNTUSER
FROM SYSUSERS R
JOIN sys.database_role_members M ON M.ROLE_PRINCIPAL_ID=R.UID
JOIN SYSUSERS U ON U.UID=M.MEMBER_PRINCIPAL_ID
WHERE R.NAME=@RoleName
AND U.ISSQLROLE = 0
AND (U.ISNTUSER=1 OR U.ISNTGROUP=1 OR U.ISSQLUSER=1)
