CREATE PROCEDURE [CADIS_SYS].[SPDBROLEUSERINS]
@ROLENAME NVARCHAR (128), @MEMBERNAME NVARCHAR (128), @CHANGEDBY NVARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


