CREATE PROCEDURE [CADIS_SYS].[SPDF_MULTIPLESOURCE_AUDITINS]
@Data [CADIS_SYS].[MULTIPLESOURCE_AUDITINS_TBLTYPE] READONLY
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


