CREATE PROCEDURE [CADIS_SYS].[SPDM_OBJECTKEYINFO]
@ObjectName NVARCHAR (128), @ObjectKeys NVARCHAR (250), @Prefix1 NVARCHAR (128), @Prefix2 NVARCHAR (128), @KeySQL NVARCHAR (1000) OUTPUT, @KeyDefSQL NVARCHAR (1000) OUTPUT, @JoinSQL NVARCHAR (1000) OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


