CREATE PROCEDURE [CADIS_SYS].[SPDM_TABLEPKEYINFO]
@SourceTableName NVARCHAR (128), @Prefix1 NVARCHAR (128), @Prefix2 NVARCHAR (128), @PKSQL NVARCHAR (1000) OUTPUT, @PKDefSQL NVARCHAR (1000) OUTPUT, @JoinSQL NVARCHAR (1000) OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


