CREATE PROCEDURE [CADIS_SYS].[SPEDMGROUPUSERINS]
@GroupId UNIQUEIDENTIFIER, @UserId UNIQUEIDENTIFIER
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


