CREATE PROCEDURE [CADIS_SYS].[SPEDMGROUPMEMBERAUDITINS]
@GROUPID UNIQUEIDENTIFIER, @CHILDGROUPID UNIQUEIDENTIFIER, @DESCRIPTION NVARCHAR (600), @TYPE TINYINT, @CHANGEDBY NVARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


