CREATE PROCEDURE [CADIS_SYS].[SPEDMGROUPMEMBERINS]
@ParentId UNIQUEIDENTIFIER, @ChildId UNIQUEIDENTIFIER
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


