CREATE PROCEDURE [CADIS_SYS].[SPGROUPUSERINS]
@GROUPID INT, @NAME NVARCHAR (200), @USERTYPE TINYINT, @PERMISSION SMALLINT, @CHANGEDBY NVARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


