CREATE PROCEDURE [CADIS_SYS].[SPGROUPINS]
@NAME NVARCHAR (100), @ORDER INT, @PARENTGROUP INT, @CHANGEDBY NVARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


