CREATE PROCEDURE [CADIS_SYS].[SPGROUPPROCESSUSERPERMUPD]
@ID INT, @PERMISSION SMALLINT, @CHANGEDBY NVARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


