CREATE PROCEDURE [CADIS_SYS].[SPGROUPUPD]
@GROUPID INT, @NAME NVARCHAR (100), @ORDER INT, @PARENTGROUP INT, @CHANGEDBY NVARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


