CREATE PROCEDURE [CADIS_SYS].[SPGROUPPROCESSUSERPERMINS]
@GUID NVARCHAR (32), @COMPONENTID INT, @NAME NVARCHAR (200), @USERTYPE TINYINT, @PERMISSION SMALLINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


