CREATE PROCEDURE [CADIS_SYS].[SPGROUPPROCESSSEL]
@GROUPID INT, @GUID NVARCHAR (32), @COMPONENTID INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


