CREATE PROCEDURE [CADIS_SYS].[SPGROUPPROCESSUSERPERMDEL]
@GUID NVARCHAR (32), @NAME NVARCHAR (200), @COMPONENTID INT, @USERTYPE TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


