CREATE PROCEDURE [CADIS_SYS].[SPMONITOR_UNUSEDDBOBJECTS]
AS
DECLARE @CompleteLog TABLE
(
	[REPORT] [nvarchar](MAX) NOT NULL
)
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPDI_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPDM_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPDP_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPDC_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPDG_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPIL_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPRB_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
INSERT INTO @CompleteLog EXEC CADIS_SYS.SPVB_DROPOBSOLETEOBJECTS @REPORT_ONLY = 'Y', @PRINT_TO_DATATABLE = 'Y'
SELECT [REPORT] FROM @CompleteLog;
