CREATE PROCEDURE [CADIS_SYS].[SPMQ_QUEUEINS]
(
	@QUEUENAME NVARCHAR(50)
)
AS
SET XACT_ABORT ON
BEGIN TRAN
IF EXISTS(SELECT * FROM CADIS_SYS.MQ_QUEUE WHERE NAME=@QUEUENAME)
BEGIN
	ROLLBACK
	SELECT ID=-1
	RETURN
END
INSERT CADIS_SYS.MQ_QUEUE (NAME) VALUES (@QUEUENAME)
SELECT ID=SCOPE_IDENTITY()
COMMIT
