CREATE PROCEDURE [CADIS_SYS].[SPMQ_QUEUEDEL]
(
	@QUEUENAME NVARCHAR(50)
)
AS
SET XACT_ABORT ON
BEGIN TRAN
IF EXISTS(SELECT * FROM CADIS_SYS.MQ_MESSAGE M JOIN CADIS_SYS.MQ_QUEUE Q ON Q.ID=M.QUEUEID AND Q.NAME=@QUEUENAME)
BEGIN
	ROLLBACK
	SELECT RESULT=-1
	RETURN
END
DELETE CADIS_SYS.MQ_QUEUE WHERE NAME = @QUEUENAME
COMMIT
SELECT RESULT = 0
