CREATE PROCEDURE [CADIS_SYS].[SPPROCESSDBOBJECT_DEL]
@COMPONENTTYPE INT, @GUID NCHAR (32), @DIRECTION TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


