CREATE PROCEDURE [CADIS_SYS].[SPPROCESSMONITOR_SELBYRUNID]
(
	@RunId int
)
AS
	set NOCOUNT OFF
	-- We want all the records for the specified user which have not been manually hidden
	-- Runs can be merged into another run token by the PL grouping messages.  We automatically return the merged row's status, not our own in this case
	-- THIS QUERY IS PRACTICALLY IDENTICAL TO THE ONE IN SELBYUSER - KEEP THEM IN SYNC
	select M.RUNTOKEN, M.PROCESSTYPE, PROCESSNAME=A.NAME, M.WORKFLOWDATA, M.CRC, M.UPDATED,
		M.[STATUS], M.RUNID, M.[TIMESTAMP], H.RUNSTART, H.RUNEND, H.RUNSUCCESSFUL, H.RETURNCODE, M.CMDLINE, H.TOPLEVELRUNID
	FROM CADIS_SYS.CO_PROCESSMONITOR M
	JOIN CADIS_SYS.VW_ALL_PROCESSES A ON A.COMPONENTID=M.PROCESSTYPE AND A.GUID=M.GUID AND A.OBSOLETE=0
	LEFT JOIN CADIS_SYS.CO_PROCESSHISTORY H ON H.RUNID = M.RUNID
	WHERE NOT M.RUNID IS NULL
	AND M.RUNID = @RunId
