CREATE PROCEDURE [CADIS_SYS].[SPPROCESSDBOBJECT_INS]
@COMPONENTTYPE INT, @GUID NCHAR (32), @DIRECTION TINYINT, @TYPE TINYINT, @SCHEMA NVARCHAR (50), @NAME NVARCHAR (250), @CADISCREATED BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


