CREATE PROCEDURE [CADIS_SYS].[SPPROCESS_RECURSIVEELEMENTSCHECK]
@PROCESSNAME NVARCHAR (260), @COMPONENTTYPE INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


