CREATE PROCEDURE [CADIS_SYS].[SPPROCESS_DEPENDENCIESWITHFLAGS]
@COMPONENTTYPE INT, @GUID NVARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


