CREATE PROCEDURE [CADIS_SYS].[SPPR_AUDITMESSAGE]
@QUEUE_NAME NVARCHAR (100), @MESSAGE_ID NVARCHAR (200), @OWNER_RUNID INT, @TIMEOUT_SEC INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


