CREATE PROCEDURE [CADIS_SYS].[SPPROCESSLINK_INS]
@FROMCOMPONENTTYPE INT, @FROMNAME NVARCHAR (260), @TOCOMPONENTTYPE INT, @TONAME NVARCHAR (260), @OWNERCOMPONENTTYPE INT, @OWNERGUID NCHAR (32), @LINKTYPE TINYINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


