CREATE PROCEDURE [CADIS_SYS].[SPPROCESSDBOBJECT_SELINPUTS]
@COMPONENTTYPE INT, @NAME NVARCHAR (260), @CADISCREATEDONLY BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


