CREATE PROCEDURE [CADIS_SYS].[SPPROCESSMONITOR_UPDCMDLINE]
@RunToken INT, @CMDLINE NVARCHAR (2000), @PLGUID NVARCHAR (32)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


