CREATE PROCEDURE [CADIS_SYS].[SPPROCESS_INSERTWEBUSERACTIVITY]
@ACTIVITY NVARCHAR (25), @USERNAME NVARCHAR (100), @TOKEN NVARCHAR (120), @DETAIL NVARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


