CREATE PROCEDURE [CADIS_SYS].[SPPROCESSLINK_DEL]
@OWNERCOMPONENTTYPE INT, @OWNERGUID NCHAR (32), @ALLREFS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


