CREATE PROCEDURE [CADIS_SYS].[SPPROCESSDBOBJECT_SELPROCESSESWITHFLAGS]
@SCHEMA NVARCHAR (50), @DBOBJECTNAME NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


