CREATE PROCEDURE [CADIS_SYS].[SPPROCESSDBOBJECT_SELDEPENDENCIES]
@COMPONENTTYPE INT, @NAME NVARCHAR (260)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


