CREATE PROCEDURE [CADIS_SYS].[SPPR_AUDITINS]
@INSTANCE INT, @COMPONENTID INT, @GUID NCHAR (32), @MESSAGETYPE TINYINT, @HEADER NVARCHAR (500), @MESSAGE NVARCHAR (1024), @MACHINENAME NVARCHAR (100), @USERNAME NVARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


