CREATE PROCEDURE [CADIS_SYS].[SPPROCESSMONITOR_INS]
@PROCESSTYPE INT, @PROCESSNAME NVARCHAR (260), @WORKFLOWDATA XML, @STATUS INT, @CHANGEDBY NVARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


