CREATE PROCEDURE [CADIS_SYS].[SPWEBUSERINS]
@USERNAME NVARCHAR (100), @EMAIL NVARCHAR (512), @DISPLAYNAME NVARCHAR (512), @WEBUSER BIT, @ACTIVE BIT, @CHANGEDBY NVARCHAR (256)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


