CREATE PROCEDURE [CADIS_SYS].[SPWEBUSERPERMISSIONSPROPOSALINS]
@PROPOSAL_ID INT, @ACTION SMALLINT, @GROUP_ID INT, @PERMISSIONS INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


