CREATE PROCEDURE [CADIS_SYS].[SPWEBUSERPROPOSALCOMMIT]
@ID INT, @APPROVER NVARCHAR (100), @APPROVED BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


