CREATE PROCEDURE [CADIS_SYS].[SPWEBUSERPROPOSALINS]
@USERNAME NVARCHAR (100), @ACTION SMALLINT, @PROPOSER NVARCHAR (100), @SI INT OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


