CREATE TABLE [ChangeManagement].[ChangeManagementRegister] (
    [ChangeID]                                     INT              IDENTITY (1, 1) NOT NULL,
    [ServiceTypeID]                                SMALLINT         NOT NULL,
    [StatusID]                                     SMALLINT         NOT NULL,
    [ChangeTitle]                                  NVARCHAR (MAX)   NOT NULL,
    [PriorityID]                                   SMALLINT         NOT NULL,
    [UrgencyID]                                    SMALLINT         NULL,
    [DueLiveDate]                                  DATETIME         NULL,
    [PlanDueDate]                                  DATETIME         NULL,
    [ChangeTypeID]                                 SMALLINT         NOT NULL,
    [Description]                                  NVARCHAR (MAX)   NOT NULL,
    [ReasonJustification]                          NVARCHAR (MAX)   NULL,
    [ImpactID]                                     SMALLINT         NULL,
    [ImpactDesc]                                   NVARCHAR (MAX)   NULL,
    [ComplexityID]                                 SMALLINT         NULL,
    [RiskID]                                       SMALLINT         NULL,
    [EstimatedHoursRequired]                       INT              NULL,
    [BuildInstruction]                             NVARCHAR (MAX)   NULL,
    [ProgressNote]                                 NVARCHAR (MAX)   NULL,
    [IsBuildComplete]                              BIT              NULL,
    [TesterPersonID]                               SMALLINT         NULL,
    [JIRAIssueKey]                                 NVARCHAR (255)   NULL,
    [IsDocumentationProvided]                      BIT              NULL,
    [AttachmentsFolder]                            NVARCHAR (MAX)   NULL,
    [IsChangeReady]                                BIT              NULL,
    [IncidentId]                                   NVARCHAR (255)   NULL,
    [IncidentTitle]                                NVARCHAR (255)   NULL,
    [CreatedDate]                                  DATETIME         NOT NULL,
    [SubmittedByPersonID]                          SMALLINT         CONSTRAINT [DF_CMR_CMRSP] DEFAULT ((-1)) NOT NULL,
    [PlanApproverPersonID]                         SMALLINT         NULL,
    [TestCompleteDueDate]                          DATETIME         NULL,
    [TestPlan]                                     NVARCHAR (MAX)   NULL,
    [TestingComplete]                              BIT              NULL,
    [DeploymentApproverPersonID]                   SMALLINT         NULL,
    [ComplexityDesc]                               NVARCHAR (MAX)   NULL,
    [RiskDesc]                                     NVARCHAR (MAX)   NULL,
    [Backout]                                      NVARCHAR (255)   NULL,
    [DocumentationFolderLink]                      VARCHAR (2000)   NULL,
    [JoinGUID]                                     UNIQUEIDENTIFIER NOT NULL,
    [ChangeManagementRegisterCreationDatetime]     DATETIME         CONSTRAINT [DF_CMR_CMRCDT] DEFAULT (getdate()) NOT NULL,
    [ChangeManagementRegisterLastModifiedDatetime] DATETIME         CONSTRAINT [DF_CMR_CMRLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                        DATETIME         CONSTRAINT [DF_CMR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                         DATETIME         CONSTRAINT [DF_CMR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                       NVARCHAR (50)    CONSTRAINT [DF_CMR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                        INT              CONSTRAINT [DF_CMR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                       ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                    DATETIME         CONSTRAINT [DF_CMR_CSL] DEFAULT (getdate()) NULL,
    [RuleID]                                       NVARCHAR (8)     NULL,
    [RuleDescription]                              VARCHAR (MAX)    NULL,
    [DashboardUpdate]                              BIT              NULL,
    CONSTRAINT [PKChangeManagementRegister] PRIMARY KEY CLUSTERED ([ChangeID] ASC),
    CONSTRAINT [ChangeManagementRegisterApproverPersonID] FOREIGN KEY ([PlanApproverPersonID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ChangeManagementRegisterChangeTypeID] FOREIGN KEY ([ChangeTypeID]) REFERENCES [ChangeManagement].[ChangeTypes] ([ChangeTypeID]),
    CONSTRAINT [ChangeManagementRegisterComplexityID] FOREIGN KEY ([ComplexityID]) REFERENCES [ChangeManagement].[ChangeComplexity] ([ChangeComplexityID]),
    CONSTRAINT [ChangeManagementRegisterDeploymentApproverPersonID] FOREIGN KEY ([DeploymentApproverPersonID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ChangeManagementRegisterImpactID] FOREIGN KEY ([ImpactID]) REFERENCES [ChangeManagement].[ChangeImpact] ([ChangeImpactID]),
    CONSTRAINT [ChangeManagementRegisterPriorityID] FOREIGN KEY ([PriorityID]) REFERENCES [ChangeManagement].[ChangePriority] ([ChangePriorityID]),
    CONSTRAINT [ChangeManagementRegisterRiskID] FOREIGN KEY ([RiskID]) REFERENCES [ChangeManagement].[ChangeRisk] ([ChangeRiskID]),
    CONSTRAINT [ChangeManagementRegisterServiceTypeID] FOREIGN KEY ([ServiceTypeID]) REFERENCES [ChangeManagement].[ChangeServiceTypes] ([ChangeServiceTypeID]),
    CONSTRAINT [ChangeManagementRegisterStatusID] FOREIGN KEY ([StatusID]) REFERENCES [ChangeManagement].[ChangeStatus] ([ChangeStatusID]),
    CONSTRAINT [ChangeManagementRegisterSubmittedByPersonID] FOREIGN KEY ([SubmittedByPersonID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ChangeManagementRegisterTesterPersonID] FOREIGN KEY ([TesterPersonID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ChangeManagementRegisterUrgencyID] FOREIGN KEY ([UrgencyID]) REFERENCES [ChangeManagement].[ChangeUrgency] ([ChangeUrgencyID])
);

