CREATE TABLE [ChangeManagement].[VisitorAccessRegister] (
    [VisitorAccessID]                           INT              IDENTITY (1, 1) NOT NULL,
    [VisitorAccessEventID]                      INT              NOT NULL,
    [Version]                                   SMALLINT         NOT NULL,
    [IsActive]                                  BIT              NOT NULL,
    [EventTitle]                                NVARCHAR (255)   NOT NULL,
    [ReasonForVisit]                            NVARCHAR (2000)  NULL,
    [EventDetails]                              NVARCHAR (2000)  NULL,
    [Comments]                                  NVARCHAR (4000)  NULL,
    [VisitorCompany]                            NVARCHAR (255)   NOT NULL,
    [VisitorName]                               NVARCHAR (255)   NOT NULL,
    [VisitorContactNumber]                      NVARCHAR (20)    NOT NULL,
    [VisitorTools]                              NVARCHAR (2000)  NULL,
    [EventStartDateTime]                        DATETIME         NOT NULL,
    [EventEndDateTime]                          DATETIME         NOT NULL,
    [ApproverID]                                SMALLINT         NOT NULL,
    [SupervisorID]                              SMALLINT         NOT NULL,
    [SubmittedByPersonID]                       SMALLINT         NOT NULL,
    [RequestStatusID]                           SMALLINT         NOT NULL,
    [JoinGUID]                                  UNIQUEIDENTIFIER NOT NULL,
    [VisitorAccessRegisterCreationDatetime]     DATETIME         CONSTRAINT [DF_VAR_VARCDT] DEFAULT (getdate()) NOT NULL,
    [VisitorAccessRegisterLastModifiedDatetime] DATETIME         CONSTRAINT [DF_VAR_VARLMDT] DEFAULT (getdate()) NOT NULL,
    [JIRAIssueKey]                              NVARCHAR (255)   NULL,
    [CADIS_SYSTEM_INSERTED]                     DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                      DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                    NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    [SupervisorJIRAIssueKey]                    NVARCHAR (255)   NULL,
    [CommentsBy]                                NVARCHAR (128)   NULL,
    CONSTRAINT [PKVisitorAccessRegister] PRIMARY KEY CLUSTERED ([VisitorAccessID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [VisitorAccessRegisterApproverID] FOREIGN KEY ([ApproverID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [VisitorAccessRegisterStatusID] FOREIGN KEY ([RequestStatusID]) REFERENCES [ChangeManagement].[ChangeStatus] ([ChangeStatusID]),
    CONSTRAINT [VisitorAccessRegisterSubmittedByPersonID] FOREIGN KEY ([SubmittedByPersonID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [VisitorAccessRegisterSupervisorID] FOREIGN KEY ([SupervisorID]) REFERENCES [Core].[Persons] ([PersonId])
);

