CREATE TABLE [Organisation].[AnnualBudget] (
    [AnnualBudgetId]                   INT              IDENTITY (1, 1) NOT NULL,
    [DepartmentId]                     SMALLINT         NOT NULL,
    [BudgetOwnerPersonId]              SMALLINT         NOT NULL,
    [FinancialYear]                    VARCHAR (25)     NOT NULL,
    [BudgetSubmittedDate]              DATE             NULL,
    [BudgetApproved]                   BIT              NULL,
    [BudgetStatus]                     VARCHAR (25)     NULL,
    [DiscrBudgetSummary]               VARCHAR (MAX)    NULL,
    [DiscrEstimatedBudgetImpact]       BIGINT           NULL,
    [DiscrBudgetImpactExceeds500K]     BIT              NULL,
    [DiscrJIRAEpicKey]                 VARCHAR (2000)   NULL,
    [DiscrReviewerComments]            VARCHAR (MAX)    NULL,
    [NonDiscrBudgetSummary]            VARCHAR (MAX)    NULL,
    [NonDiscrEstimatedBudgetImpact]    BIGINT           NULL,
    [NonDiscrBudgetImpactExceeds500K]  BIT              NULL,
    [NonDiscrJIRAEpicKey]              VARCHAR (2000)   NULL,
    [NonDiscrReviewerComments]         VARCHAR (MAX)    NULL,
    [DocumentationFolderLink]          VARCHAR (2000)   NULL,
    [SubflowJoinURL]                   VARCHAR (2000)   NULL,
    [JoinGUID]                         UNIQUEIDENTIFIER NOT NULL,
    [AnnualBudgetCreationDatetime]     DATETIME         CONSTRAINT [DF_AB_CDT] DEFAULT (getdate()) NOT NULL,
    [AnnualBudgetLastModifiedDatetime] DATETIME         CONSTRAINT [DF_AB_LMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]            DATETIME         CONSTRAINT [DF_AB_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]             DATETIME         CONSTRAINT [DF_AB_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]           NVARCHAR (50)    CONSTRAINT [DF_AB_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]            INT              CONSTRAINT [DF_AB_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]           ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]        DATETIME         CONSTRAINT [DF_AB_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKAnnualBudget] PRIMARY KEY CLUSTERED ([AnnualBudgetId] ASC),
    CONSTRAINT [AnnualBudgetBudgetOwnerPersonId] FOREIGN KEY ([BudgetOwnerPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [AnnualBudgetDepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Core].[Departments] ([DepartmentId])
);

