CREATE TABLE [Organisation].[Approvals] (
    [ApprovalId]                INT              IDENTITY (1, 1) NOT NULL,
    [ApprovedByPersonId]        SMALLINT         NOT NULL,
    [ApprovalDate]              DATE             NULL,
    [ApproverComments]          NVARCHAR (MAX)   NULL,
    [Status]                    VARCHAR (50)     NULL,
    [Summary]                   NVARCHAR (MAX)   NULL,
    [Description]               NVARCHAR (MAX)   NULL,
    [Category]                  VARCHAR (50)     NULL,
    [SubCategory]               VARCHAR (50)     NULL,
    [ChangeID]                  INT              NULL,
    [SubmittedByPersonID]       SMALLINT         CONSTRAINT [DF_AP_SBP] DEFAULT ((-1)) NOT NULL,
    [DepartmentId]              SMALLINT         NULL,
    [ApprovalType]              VARCHAR (50)     NULL,
    [FlowId]                    UNIQUEIDENTIFIER NULL,
    [JiraIssueKey]              VARCHAR (20)     NULL,
    [FinanceRequestId]          INT              NULL,
    [SalesForceLeaveRequestId]  VARCHAR (20)     NULL,
    [GTAIncidentId]             VARCHAR (50)     NULL,
    [JoinGUID1]                 UNIQUEIDENTIFIER NULL,
    [JoinGUID2]                 UNIQUEIDENTIFIER NULL,
    [ApprovalCreationDate]      DATETIME         CONSTRAINT [DF_AP_ACDT] DEFAULT (getdate()) NOT NULL,
    [ApprovalLastModifiedDate]  DATETIME         CONSTRAINT [DF_AP_ALMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME         CONSTRAINT [DF_AP_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME         CONSTRAINT [DF_AP_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)    CONSTRAINT [DF_AP_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT              CONSTRAINT [DF_AP_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME         CONSTRAINT [DF_AP_CSL] DEFAULT (getdate()) NULL,
    [VisitorAccessRequestID]    INT              NULL,
    CONSTRAINT [PKApprovals] PRIMARY KEY CLUSTERED ([ApprovalId] ASC),
    CONSTRAINT [ApprovalsApprovedByPersonId] FOREIGN KEY ([ApprovedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ApprovalsChangeID] FOREIGN KEY ([ChangeID]) REFERENCES [ChangeManagement].[ChangeManagementRegister] ([ChangeID]),
    CONSTRAINT [ApprovalsDepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Core].[Departments] ([DepartmentId]),
    CONSTRAINT [ApprovalsFinanceRequestId] FOREIGN KEY ([FinanceRequestId]) REFERENCES [Organisation].[FinanceRequests] ([FinanceRequestId]),
    CONSTRAINT [ApprovalsSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ApprovalsVisitorAccessRequestID] FOREIGN KEY ([VisitorAccessRequestID]) REFERENCES [ChangeManagement].[VisitorAccessRegister] ([VisitorAccessID])
);

