CREATE TABLE [Organisation].[AssetRegister] (
    [AssetId]                           INT              IDENTITY (1, 1) NOT NULL,
    [AssetTypeId]                       INT              NOT NULL,
    [Supplier]                          VARCHAR (100)    NULL,
    [Reference]                         VARCHAR (100)    NULL,
    [TransactionNo]                     VARCHAR (50)     NULL,
    [Description]                       VARCHAR (MAX)    NULL,
    [AssetCost]                         DECIMAL (19, 2)  NULL,
    [PurchaseDate]                      DATETIME         NOT NULL,
    [WrittenOffDate]                    DATETIME         NULL,
    [Status]                            VARCHAR (50)     NOT NULL,
    [WritedownPeriod]                   INT              NULL,
    [DepreciationType]                  VARCHAR (50)     NULL,
    [SubmittedByPersonId]               SMALLINT         CONSTRAINT [DF_AR_ARSP] DEFAULT ((-1)) NOT NULL,
    [DocumentationFolderLink]           VARCHAR (2000)   NULL,
    [JoinGUID]                          UNIQUEIDENTIFIER NOT NULL,
    [AssetRegisterCreationDatetime]     DATETIME         CONSTRAINT [DF_AR_ARCDT] DEFAULT (getdate()) NOT NULL,
    [AssetRegisterLastModifiedDatetime] DATETIME         CONSTRAINT [DF_AR_ARLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]             DATETIME         CONSTRAINT [DF_AR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]              DATETIME         CONSTRAINT [DF_AR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]            NVARCHAR (50)    CONSTRAINT [DF_AR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]             INT              CONSTRAINT [DF_AR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]            ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]         DATETIME         CONSTRAINT [DF_AR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKAssetRegister] PRIMARY KEY CLUSTERED ([AssetId] ASC),
    CONSTRAINT [AssetRegisterAssetTypeId] FOREIGN KEY ([AssetTypeId]) REFERENCES [Organisation].[AssetTypes] ([AssetTypeId]),
    CONSTRAINT [AssetRegisterSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

