CREATE TABLE [Organisation].[BrokerReviewEventTypes] (
    [BrokerReviewEventTypeId]   SMALLINT      IDENTITY (1, 1) NOT NULL,
    [BrokerReviewEventType]     VARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF_BRET_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF_BRET_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF_BRET_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF_BRET_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF_BRET_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKBrokerReviewEventTypes] PRIMARY KEY CLUSTERED ([BrokerReviewEventTypeId] ASC)
);

