CREATE TABLE [Organisation].[FinanceRequests] (
    [FinanceRequestId]          INT              IDENTITY (1, 1) NOT NULL,
    [RequestedByPersonId]       SMALLINT         NOT NULL,
    [RequestDate]               DATE             NULL,
    [ApprovalDate]              DATE             NULL,
    [ApprovedByPersonId]        SMALLINT         NULL,
    [DepartmentId]              SMALLINT         NULL,
    [ReviewerPersonId]          SMALLINT         NULL,
    [Summary]                   NVARCHAR (MAX)   NULL,
    [Description]               NVARCHAR (MAX)   NULL,
    [Category]                  VARCHAR (50)     NULL,
    [SubCategory]               VARCHAR (50)     NULL,
    [Status]                    VARCHAR (50)     NULL,
    [Amount]                    DECIMAL (19, 2)  NULL,
    [NewTechnologyYesNo]        BIT              NULL,
    [NewResourceYesNo]          BIT              NULL,
    [UrgentRequestYesNo]        BIT              NULL,
    [RequestType]               VARCHAR (50)     NULL,
    [NominalCode]               INT              NULL,
    [JiraEPICKey]               VARCHAR (128)    NULL,
    [WorkFlowLink]              VARCHAR (2000)   NULL,
    [SupplierSalesforceId]      VARCHAR (18)     NULL,
    [SupplierName]              VARCHAR (127)    NULL,
    [Invoiced]                  BIT              CONSTRAINT [df_fr_i] DEFAULT ((0)) NOT NULL,
    [UnquotedCompanyId]         INT              NULL,
    [UnquotedDueDiligenceYesNo] BIT              NULL,
    [ResearchBrokerId]          INT              NULL,
    [BrokerResearchYesNo]       BIT              NULL,
    [CoveredByWoodfordYesNo]    BIT              NULL,
    [FlowId]                    UNIQUEIDENTIFIER NULL,
    [DocumentationFolderLink]   VARCHAR (2000)   NULL,
    [JoinGUID]                  UNIQUEIDENTIFIER NOT NULL,
    [RequestCreationDate]       DATETIME         CONSTRAINT [DF_FR_RCDT] DEFAULT (getdate()) NOT NULL,
    [RequestLastModifiedDate]   DATETIME         CONSTRAINT [DF_FR_RLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME         CONSTRAINT [DF_FR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME         CONSTRAINT [DF_FR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)    CONSTRAINT [DF_FR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT              CONSTRAINT [DF_FR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME         CONSTRAINT [DF_FR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKFinanceRequests] PRIMARY KEY CLUSTERED ([FinanceRequestId] ASC),
    CONSTRAINT [FinanceRequestsApprovedByPersonId] FOREIGN KEY ([ApprovedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [FinanceRequestsDepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Core].[Departments] ([DepartmentId]),
    CONSTRAINT [FinanceRequestsNominalCode] FOREIGN KEY ([NominalCode]) REFERENCES [Finance].[AccountNominalCodes] ([NominalCode]),
    CONSTRAINT [FinanceRequestsRequestedByPersonId] FOREIGN KEY ([RequestedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [FinanceRequestsResearchBrokerId] FOREIGN KEY ([ResearchBrokerId]) REFERENCES [Investment].[ResearchBrokerRegister_OLD] ([ResearchBrokerId]),
    CONSTRAINT [FinanceRequestsReviewerPersonId] FOREIGN KEY ([ReviewerPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [FinanceRequestsUnquotedCompanyId] FOREIGN KEY ([UnquotedCompanyId]) REFERENCES [Organisation].[UnquotedCompanies] ([UnquotedCompanyId])
);

