CREATE TABLE [Organisation].[ProjectsRegister] (
    [ProjectRegisterId]       SMALLINT         IDENTITY (1, 1) NOT NULL,
    [ProjectNameBK]           [sysname]        NOT NULL,
    [RequestorRoleId]         SMALLINT         NOT NULL,
    [RequestorPersonId]       SMALLINT         NOT NULL,
    [ProjectOwnerRoleId]      SMALLINT         NOT NULL,
    [ProjectOwnerPersonId]    SMALLINT         NOT NULL,
    [OversightRoleId]         SMALLINT         NOT NULL,
    [OversightPersonId]       SMALLINT         NOT NULL,
    [RequestDate]             DATETIME         CONSTRAINT [DF_PR_RD] DEFAULT (getdate()) NOT NULL,
    [ProposedStartDate]       DATE             NULL,
    [EstimatedDuration]       SMALLINT         NULL,
    [EstimatedDurationUnits]  VARCHAR (25)     NULL,
    [EstimatedDurationDays]   SMALLINT         NULL,
    [EstimatedCost]           DECIMAL (19, 5)  NULL,
    [TechnologyInvolved]      BIT              CONSTRAINT [DF_PR_TI] DEFAULT ((1)) NOT NULL,
    [ProjectApproved]         BIT              NULL,
    [StrategicProject]        BIT              NULL,
    [ProjectPurpose]          VARCHAR (2048)   NOT NULL,
    [ProjectScope]            VARCHAR (2048)   NOT NULL,
    [Dependences]             VARCHAR (2048)   NOT NULL,
    [ExternalResources]       VARCHAR (2048)   NULL,
    [AdditionalDetails]       VARCHAR (2048)   NOT NULL,
    [DocumentationFolderLink] VARCHAR (2000)   NULL,
    [WorkflowVersionGUID]     UNIQUEIDENTIFIER CONSTRAINT [DF_PR_WVG] DEFAULT (newid()) NOT NULL,
    [JoinGUID]                UNIQUEIDENTIFIER CONSTRAINT [DF_PR_JG] DEFAULT (newid()) NOT NULL,
    [ProjectCreationDate]     DATETIME         CONSTRAINT [DF_PR_PCD] DEFAULT (getdate()) NOT NULL,
    [ProjectLastModifiedDate] DATETIME         CONSTRAINT [DF_PR_PLMD] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PKProjectsRegister] PRIMARY KEY CLUSTERED ([ProjectRegisterId] ASC),
    CONSTRAINT [ProjectsRegisterEstimatedDurationUnits] FOREIGN KEY ([EstimatedDurationUnits]) REFERENCES [Organisation].[ProjectMeasureUnits] ([MeasureUnitBK]),
    CONSTRAINT [ProjectsRegisterOversightPersonId] FOREIGN KEY ([OversightPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ProjectsRegisterOversightRoleId] FOREIGN KEY ([OversightRoleId]) REFERENCES [Core].[Roles] ([RoleId]),
    CONSTRAINT [ProjectsRegisterProjectOwnerPersonId] FOREIGN KEY ([ProjectOwnerPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ProjectsRegisterProjectOwnerRoleId] FOREIGN KEY ([ProjectOwnerRoleId]) REFERENCES [Core].[Roles] ([RoleId]),
    CONSTRAINT [ProjectsRegisterRequestorPersonId] FOREIGN KEY ([RequestorPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ProjectsRegisterRequestorRoleId] FOREIGN KEY ([RequestorRoleId]) REFERENCES [Core].[Roles] ([RoleId])
);

