CREATE TABLE [Organisation].[UnquotedCompanyAdditionalInfo] (
    [UnquotedCompanyId]                      INT             NOT NULL,
    [Geography]                              VARCHAR (255)   NOT NULL,
    [CompanyMaturityId]                      INT             CONSTRAINT [DF_UCAI_CMI] DEFAULT ((-1)) NOT NULL,
    [WIMEIFCompanyMaturityId]                INT             CONSTRAINT [DF_UCAI_ECMI] DEFAULT ((-1)) NOT NULL,
    [WIMPCTCompanyMaturityId]                INT             CONSTRAINT [DF_UCAI_PCMI] DEFAULT ((-1)) NOT NULL,
    [InvestmentDate]                         DATE            NULL,
    [NAVatInvestment]                        DECIMAL (10, 6) NULL,
    [SectorId]                               INT             NULL,
    [SubSectorId]                            INT             NULL,
    [DevelopmentClassification]              VARCHAR (255)   NULL,
    [DevelopmentClassificationId]            INT             NULL,
    [PrimaryRelationInvestmentSource]        INT             NULL,
    [SecondaryRelationEstEvergreenVentureId] INT             NULL,
    [Notes]                                  NVARCHAR (2000) NULL,
    [UnquotedCompaniesCreationDate]          DATETIME        CONSTRAINT [DF_UCAI_CMCD] DEFAULT (getdate()) NOT NULL,
    [UnquotedCompaniesLastModifiedDate]      DATETIME        CONSTRAINT [DF_UCAI_CMLMD] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                  DATETIME        CONSTRAINT [DF_UCAI_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                   DATETIME        CONSTRAINT [DF_UCAI_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                 NVARCHAR (50)   CONSTRAINT [DF_UCAI_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                  INT             CONSTRAINT [DF_UCAI_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                 ROWVERSION      NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]              DATETIME        CONSTRAINT [DF_UCAI_CSL] DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([UnquotedCompanyId] ASC),
    CONSTRAINT [UnquotedCompanyAdditionalInfoCompanyMaturityId] FOREIGN KEY ([CompanyMaturityId]) REFERENCES [Core].[CompanyMaturities] ([CompanyMaturityId]),
    CONSTRAINT [UnquotedCompanyAdditionalInfoSectorId] FOREIGN KEY ([SectorId]) REFERENCES [Core].[Sectors] ([SectorId]),
    CONSTRAINT [UnquotedCompanyAdditionalInfoSubSectorId] FOREIGN KEY ([SubSectorId]) REFERENCES [Core].[Sectors] ([SectorId]),
    CONSTRAINT [UnquotedCompanyAdditionalInfoUnquotedCompanyId] FOREIGN KEY ([UnquotedCompanyId]) REFERENCES [Organisation].[UnquotedCompanies] ([UnquotedCompanyId]),
    CONSTRAINT [UnquotedCompanyAdditionalInfoWIMEIFCompanyMaturityId] FOREIGN KEY ([WIMEIFCompanyMaturityId]) REFERENCES [Core].[CompanyMaturities] ([CompanyMaturityId]),
    CONSTRAINT [UnquotedCompanyAdditionalInfoWIMPCTCompanyMaturityId] FOREIGN KEY ([WIMPCTCompanyMaturityId]) REFERENCES [Core].[CompanyMaturities] ([CompanyMaturityId])
);

