CREATE TABLE [Organisation].[UnquotedCompanyRevaluation] (
    [UnquotedCompanyRevaluationId]             INT              IDENTITY (1, 1) NOT NULL,
    [UnquotedCompanyId]                        INT              NOT NULL,
    [EventType]                                VARCHAR (128)    NOT NULL,
    [EventOverview]                            VARCHAR (2000)   NOT NULL,
    [EventDate]                                DATETIME         NOT NULL,
    [FurtherFundingAmount]                     DECIMAL (18, 6)  NULL,
    [Notes]                                    NVARCHAR (MAX)   NULL,
    [BoxUrl]                                   NVARCHAR (2000)  NULL,
    [PresentedToPricingCommitee]               BIT              NULL,
    [RevaluationPreviousPrice]                 DECIMAL (18, 6)  NULL,
    [RevaluationPrice]                         DECIMAL (18, 6)  NULL,
    [RevaluationEndDate]                       DATETIME         NULL,
    [IsActive]                                 BIT              NULL,
    [Status]                                   VARCHAR (50)     NULL,
    [CurrencyCode]                             CHAR (3)         NULL,
    [IsComplete]                               BIT              NULL,
    [JiraIssueKey]                             VARCHAR (128)    NULL,
    [WorkflowVersionGUID]                      UNIQUEIDENTIFIER NULL,
    [JoinGUID]                                 UNIQUEIDENTIFIER NOT NULL,
    [UnquotedSecuritiesCreationDate]           DATETIME         CONSTRAINT [DF_UCR_USCDT] DEFAULT (getdate()) NOT NULL,
    [UnquotedSecuritiesCreatedByPersonId]      SMALLINT         NOT NULL,
    [UnquotedSecuritiesLastModifiedDate]       DATETIME         CONSTRAINT [DF_UCR_USLMDT] DEFAULT (getdate()) NOT NULL,
    [UnquotedSecuritiesLastModifiedByPersonId] SMALLINT         NOT NULL,
    [CADIS_SYSTEM_INSERTED]                    DATETIME         CONSTRAINT [DF_UCR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                     DATETIME         CONSTRAINT [DF_UCR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                   NVARCHAR (50)    CONSTRAINT [DF_UCR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                    INT              CONSTRAINT [DF_UCR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                   ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                DATETIME         CONSTRAINT [DF_UCR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [XPKUnquotedCompanyRevaluation] PRIMARY KEY CLUSTERED ([UnquotedCompanyRevaluationId] ASC),
    CONSTRAINT [UnquotedCompanyRevaluationUnquotedCompanyId] FOREIGN KEY ([UnquotedCompanyId]) REFERENCES [Organisation].[UnquotedCompanies] ([UnquotedCompanyId])
);

