CREATE TABLE [Organisation].[UnquotedSecuritiesAudit] (
    [UnquotedSecuritiesAuditId]                INT              IDENTITY (1, 1) NOT NULL,
    [UnquotedSecuritiesAuditAction]            CHAR (1)         NOT NULL,
    [UnquotedSecuritiesAuditDate]              DATETIME         CONSTRAINT [DF_USA_USAD] DEFAULT (getdate()) NOT NULL,
    [UnquotedSecuritiesAuditUser]              VARCHAR (64)     CONSTRAINT [DF_USA_USAU] DEFAULT (suser_sname()) NOT NULL,
    [UnquotedSecuritiesAuditApplication]       VARCHAR (128)    CONSTRAINT [DF_USA_USAA] DEFAULT (('App=('+rtrim(isnull(app_name(),'')))+') ') NOT NULL,
    [UnquotedSecuritiesId]                     INT              NULL,
    [UnquotedCompanyId]                        INT              NULL,
    [CurrencyCode]                             CHAR (3)         NULL,
    [AssetType]                                VARCHAR (128)    NULL,
    [StockName]                                NVARCHAR (256)   NULL,
    [ShareClass]                               NVARCHAR (256)   NULL,
    [Tranche]                                  SMALLINT         CONSTRAINT [DF_USA_T] DEFAULT ((1)) NOT NULL,
    [BrokerSalesforceId]                       VARCHAR (18)     NULL,
    [EstimatedPrice]                           DECIMAL (18, 6)  NULL,
    [EstimatedPriceDate]                       DATE             NULL,
    [InitialPrice]                             DECIMAL (18, 6)  NULL,
    [InitialPriceDate]                         DATE             NULL,
    [LatestPrice]                              DECIMAL (18, 6)  NULL,
    [LatestPriceDate]                          DATE             NULL,
    [ClosingDate]                              DATE             NULL,
    [CountryOfRisk]                            VARCHAR (256)    NULL,
    [CountryOfIncorporation]                   VARCHAR (256)    NULL,
    [BBGSetup]                                 BIT              NULL,
    [Ticker]                                   VARCHAR (128)    NULL,
    [BBGID]                                    CHAR (12)        NULL,
    [BBGSecurityId]                            CHAR (7)         NULL,
    [BBGCompanyId]                             CHAR (7)         NULL,
    [NTSent]                                   BIT              NULL,
    [BBGUniqueId/FOID]                         VARCHAR (128)    NULL,
    [CustodianId]                              VARCHAR (64)     NULL,
    [Notes]                                    NVARCHAR (2000)  NULL,
    [WorkflowVersionGUID]                      UNIQUEIDENTIFIER NULL,
    [JoinGUID]                                 UNIQUEIDENTIFIER NULL,
    [UnquotedSecuritiesCreationDate]           DATETIME         CONSTRAINT [DF_USA_USCD] DEFAULT (getdate()) NULL,
    [UnquotedSecuritiesCreatedByPersonId]      SMALLINT         NULL,
    [UnquotedSecuritiesLastModifiedDate]       DATETIME         CONSTRAINT [DF_USA_USLMD] DEFAULT (getdate()) NULL,
    [UnquotedSecuritiesLastModifiedByPersonId] SMALLINT         NULL,
    [CADIS_SYSTEM_INSERTED]                    DATETIME         CONSTRAINT [DF_USA_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                     DATETIME         CONSTRAINT [DF_USA_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                   NVARCHAR (50)    CONSTRAINT [DF_USA_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                    INT              CONSTRAINT [DF_USA_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                   ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                DATETIME         CONSTRAINT [DF_USA_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [XPKUnquotedSecuritiesAudit] PRIMARY KEY CLUSTERED ([UnquotedSecuritiesAuditId] DESC)
);

