
CREATE VIEW [TCA].[V_REC_CHILD_LEVEL_BLOOMBERG_TCA_OUT]
AS

/********************************************************
-- NAME: [TCA].[V_REC_CHILD_LEVEL_BLOOMBERG_TCA_OUT]
-- DECRIPTION: RECS BLOOMBERG AGAINST TCA OUT.

** CHANGE HISTORY
**************************
** JIRA			DATE		AUTHOR		DESCRIPTION 
** ----			----------  -------		------------------------------------
-- DAP-1858		23/03/2018  V.KHATRI	INITIAL VERSION
				15/04/2018	V.KHATRI	UPDATED WITH FOLLOWING POINTS FROM MEETING WITH DOMINIC
										1. RENAME COLUMNS FROM TCA TO ITG
										2. DISPLAY ORDER_ID, ACCOUNT, SUM OF ALLOCATED QUANTITY, REASON
********************************************************/

SELECT	COMPARISON.ORDER_ID,
		BB_ORDER_ID,
		TCA_ORDER_ID,
		BB_ACCOUNT,
		TCA_ACCOUNT,
		BB_ALLOCATED_QUANTITY,
		TCA_ALLOCATED_QUANTITY,
		MATCHED_TYPE,
		CASE WHEN MATCHED_TYPE = 'UNMATCHED'
				THEN LEFT(REASON,LEN(REASON)-1)  -- Want to remove trailing comma.
				ELSE ''
		END						AS REASON
FROM
(
	SELECT  ISNULL(BB.ORDER_ID,TCA.ORDER_ID)				AS ORDER_ID,
			BB.ORDER_ID										AS BB_ORDER_ID,
			TCA.ORDER_ID									AS TCA_ORDER_ID,
			BB.ACCOUNT										AS BB_ACCOUNT,
			TCA.ACCOUNT										AS TCA_ACCOUNT,
			BB.ALLOCATED_QUANTITY							AS BB_ALLOCATED_QUANTITY,
			TCA.ALLOCATED_QUANTITY							AS TCA_ALLOCATED_QUANTITY,
			CASE
			  WHEN
				   (BB.ORDER_ID = TCA.ORDER_ID AND
				   BB.ACCOUNT = TCA.ACCOUNT  AND
				   BB.ALLOCATED_QUANTITY = TCA.ALLOCATED_QUANTITY) THEN 'MATCHED'
			  ELSE 'UNMATCHED'
		 END                                    AS MATCHED_TYPE
	FROM
	(
	SELECT 		I_TSORDNUM				AS ORDER_ID,
				C_ACCOUNT				AS ACCOUNT,
				sum(ALLOCATED_QUANTITY)	as ALLOCATED_QUANTITY
	FROM	TCA.TCAOUT
	WHERE   ALLOCATED_QUANTITY != 0
	GROUP BY  I_TSORDNUM, C_ACCOUNT
	) BB
	FULL OUTER JOIN 
	(
	SELECT	CAST(ORDERID AS INT)							AS ORDER_ID,  
			ACCOUNT											AS ACCOUNT, 
			SUM(CAST(ISNULL(SHARES,0) AS DECIMAL(18,6)))	AS ALLOCATED_QUANTITY 
	FROM [TCA].[BETA_TCAOUTPUTRESULTS]
	WHERE   CAST(ISNULL(SHARES,0) AS DECIMAL(18,6)) != 0
	GROUP BY   CAST(ORDERID AS INT), ACCOUNT
	) TCA
	ON			   BB.ORDER_ID = TCA.ORDER_ID AND
				   BB.ACCOUNT = TCA.ACCOUNT
) COMPARISON
LEFT OUTER JOIN [TCA].[V_REC_CHILD_LEVEL_BLOOMBERG_TCA_OUT_EXCEPTION_REASON] R
ON COMPARISON.ORDER_ID = R.ORDER_ID
