CREATE ROLE [CADIS_UI_ADMIN]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [rdsadmin];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [Rizwan.Malik];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [TableauReporting];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [RichardDixon];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [AlbertoCogorno];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [Wayne.Stubbs];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [billkatsadoros];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [GeorgeSabrakos];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [josephbrennan];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [EDM_DEV_SERVICE];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [Vipul.Khatri];


GO
ALTER ROLE [CADIS_UI_ADMIN] ADD MEMBER [Stuart.Burns];

