CREATE ROLE [CADIS_UPGRADER]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CADIS_UPGRADER] ADD MEMBER [rdsadmin];


GO
ALTER ROLE [CADIS_UPGRADER] ADD MEMBER [EDM_PROD_SERVICE];


GO
ALTER ROLE [CADIS_UPGRADER] ADD MEMBER [billkatsadoros];


GO
ALTER ROLE [CADIS_UPGRADER] ADD MEMBER [woodford_dev_service];


GO
ALTER ROLE [CADIS_UPGRADER] ADD MEMBER [EDM_DEV_SERVICE];


GO
ALTER ROLE [CADIS_UPGRADER] ADD MEMBER [Stuart.Burns];

