CREATE ROLE [CADIS_SUPERVISOR]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [rdsadmin];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [Rizwan.Malik];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [Oluwaseun.Adenaike];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [KenWu];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [TableauReporting];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [EDM_PROD_SERVICE];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [RichardDixon];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [AlbertoCogorno];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [DominicFernandes];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [Wayne.Stubbs];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [billkatsadoros];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [CraigWatkins];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [DavidFanning];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [GeorgeSabrakos];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [IanMcLaughlin];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [joseftapper];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [josephbrennan];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [woodford_dev_service];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [EDM_DEV_SERVICE];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [Vipul.Khatri];


GO
ALTER ROLE [CADIS_SUPERVISOR] ADD MEMBER [Stuart.Burns];

