CREATE ROLE [CADIS_TABLE_SCRIPT_EDITOR]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [rdsadmin];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [Rizwan.Malik];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [TableauReporting];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [EDM_PROD_SERVICE];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [RichardDixon];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [AlbertoCogorno];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [Wayne.Stubbs];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [billkatsadoros];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [CraigWatkins];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [EDM_DEV_SERVICE];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [Vipul.Khatri];


GO
ALTER ROLE [CADIS_TABLE_SCRIPT_EDITOR] ADD MEMBER [Stuart.Burns];

