CREATE ROLE [CADIS_INBOX_VIEWER]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [rdsadmin];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [CADIS_INBOX_EDITOR];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [Rizwan.Malik];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [Oluwaseun.Adenaike];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [KenWu];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [majid.moghel];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [ManyWhoFlowUser];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [TableauReporting];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [MarkitSupport];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [EDM_PROD_SERVICE];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [RichardDixon];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [AlbertoCogorno];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [DominicFernandes];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [ahmed.test];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [ShaneTest];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [Wayne.Stubbs];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [eddy.ferreira];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [john.farrar];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [anthony.appleby];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [phil.howley];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [patrick.fawbertmills];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [pat.gaunt];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [hasan.ahmed];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [robert.clarke];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [billkatsadoros];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [CourtenayHallwood];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [CraigWatkins];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [DavidFanning];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [GeorgeSabrakos];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [IanMcLaughlin];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [joseftapper];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [josephbrennan];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [woodford_dev_service];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [ZakirHussain];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [EDM_DEV_SERVICE];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [Vipul.Khatri];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [HenryTabe];


GO
ALTER ROLE [CADIS_INBOX_VIEWER] ADD MEMBER [Stuart.Burns];

