CREATE LOGIN [EDM_DEV_SERVICE]
    WITH PASSWORD = N'w1pvyN^bKy{ozlm%hq|w@ge.msFT7_&#$!~<p~Fsoq{u2sfa', SID = 0x28F92B06AA46A94BB8BADA443AB0CEF2, DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

