CREATE LOGIN [phil.howley]
    WITH PASSWORD = N'xpvybRGTHyb{coSzh mSzfhqmsFT7_&#$!~<|epsoXqB9{sf' MUST_CHANGE, SID = 0xCF39D76D2CBA6241B8FF21BBDC611FA8, DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

