CREATE LOGIN [robert.clarke]
    WITH PASSWORD = N'Ppvyb,5y{!ozmhq|epsoZq{kmsFT7_&#$!~<`s|1|favJzyy' MUST_CHANGE, SID = 0x4CDA8BF7BCA23B45B9618FCDA0BBC7E4, DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

