CREATE VIEW "CADIS"."DG_Override_Fund_Market_Value_Reset_AUDIT" AS 
	SELECT
		[ID]
		,[INSERTED]
		,[CHANGEDBY]
		,[FIELDNAME]
		,CASE
		 WHEN [ACTION] = 0 THEN 'Inserted'
		 WHEN [ACTION] = 1 THEN 'Updated'
		 ELSE 'Deleted' END AS [ACTION]
		,[OLDVALUE]
		,[NEWVALUE]
		,[VALIDATION]
		,[KEY_SOURCE]
		,[KEY_POSITION_TYPE]
		,[KEY_FUND_SHORT_NAME]
		,[KEY_POSITION_DATE]
	FROM "CADIS_PROC"."DG_FUNCTION_AUDIT183"
