CREATE VIEW "CADIS"."DG_Override_Account_Balance_AUDIT" AS 
	SELECT
		[ID]
		,[INSERTED]
		,[CHANGEDBY]
		,[FIELDNAME]
		,CASE
		 WHEN [ACTION] = 0 THEN 'Inserted'
		 WHEN [ACTION] = 1 THEN 'Updated'
		 ELSE 'Deleted' END AS [ACTION]
		,[OLDVALUE]
		,[NEWVALUE]
		,[VALIDATION]
		,[KEY_FUND_SHORT_NAME]
		,[KEY_POSITION_DATE]
		,[KEY_ASSET_SUB_CATEGORY]
		,[KEY_CCY]
	FROM "CADIS_PROC"."DG_FUNCTION_AUDIT144"
