CREATE VIEW "CADIS"."DG_Override_Share_Class_Fund_Flow_Expiry_AUDIT" AS 
	SELECT
		[ID]
		,[INSERTED]
		,[CHANGEDBY]
		,[FIELDNAME]
		,CASE
		 WHEN [ACTION] = 0 THEN 'Inserted'
		 WHEN [ACTION] = 1 THEN 'Updated'
		 ELSE 'Deleted' END AS [ACTION]
		,[OLDVALUE]
		,[NEWVALUE]
		,[VALIDATION]
		,[KEY_VALUATION_POINT_DATE]
		,[KEY_EXTERNAL_FUND_CODE]
		,[KEY_FUND_REFERENCE]
	FROM "CADIS_PROC"."DG_FUNCTION_AUDIT188"
