CREATE VIEW "CADIS"."DG_Override_Net_Fund_Flow_Reset_AUDIT" AS 
	SELECT
		[ID]
		,[INSERTED]
		,[CHANGEDBY]
		,[FIELDNAME]
		,CASE
		 WHEN [ACTION] = 0 THEN 'Inserted'
		 WHEN [ACTION] = 1 THEN 'Updated'
		 ELSE 'Deleted' END AS [ACTION]
		,[OLDVALUE]
		,[NEWVALUE]
		,[VALIDATION]
		,[KEY_ACCOUNT_NUMBER]
		,[KEY_TNARRLONG]
		,[KEY_NET_AMOUNT__BASE]
		,[KEY_RECOGNITION_DATE]
		,[KEY_NTRANCATG]
		,[KEY_IEXTLREF]
	FROM "CADIS_PROC"."DG_FUNCTION_AUDIT186"
