CREATE VIEW "CADIS"."DG_Override_Gross_Fund_Flow_Expiry_AUDIT" AS 
	SELECT
		[ID]
		,[INSERTED]
		,[CHANGEDBY]
		,[FIELDNAME]
		,CASE
		 WHEN [ACTION] = 0 THEN 'Inserted'
		 WHEN [ACTION] = 1 THEN 'Updated'
		 ELSE 'Deleted' END AS [ACTION]
		,[OLDVALUE]
		,[NEWVALUE]
		,[VALIDATION]
		,[KEY_FUND_SHORT_NAME]
		,[KEY_TRANSACTION_DATE]
		,[KEY_CURRENCY]
		,[KEY_FUND_FLOW_TYPE]
		,[KEY_FLOW_TYPE]
	FROM "CADIS_PROC"."DG_FUNCTION_AUDIT206"
