CREATE VIEW "CADIS"."DG_Process_Monitor_AUDIT" AS 
	SELECT
		[ID]
		,[INSERTED]
		,[CHANGEDBY]
		,[FIELDNAME]
		,CASE
		 WHEN [ACTION] = 0 THEN 'Inserted'
		 WHEN [ACTION] = 1 THEN 'Updated'
		 ELSE 'Deleted' END AS [ACTION]
		,[OLDVALUE]
		,[NEWVALUE]
		,[VALIDATION]
		,[KEY_SOURCE]
		,[KEY_DESCRIPTION]
		,[KEY_DIRECTION]
		,[KEY_RUN_DATE]
	FROM "CADIS_PROC"."DG_FUNCTION_AUDIT53"
