CREATE VIEW "CADIS"."DG_Resolution_Log_AUDIT" AS 
	SELECT
		[ID]
		,[INSERTED]
		,[CHANGEDBY]
		,[FIELDNAME]
		,CASE
		 WHEN [ACTION] = 0 THEN 'Inserted'
		 WHEN [ACTION] = 1 THEN 'Updated'
		 ELSE 'Deleted' END AS [ACTION]
		,[OLDVALUE]
		,[NEWVALUE]
		,[VALIDATION]
		,[KEY_LOG_DATE]
		,[KEY_COMPONENT_NAME]
		,[KEY_COMPONENT_TYPE]
	FROM "CADIS_PROC"."DG_FUNCTION_AUDIT2"
