CREATE VIEW "CADIS"."DI_ISSCTR_ISSCTR_RSLT" AS
SELECT
	RESULT."IsValidSEDOL",RESULT."All Tests Passed?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",RESULT."CADIS_SYSTEM_RUNID",RESULT."CADIS_SYSTEM_TOPRUNID",INPUT."SOURCE_COMPONENT",INPUT."PortfolioGroup",INPUT."ReportDate",INPUT."Issuer",INPUT."Security",INPUT."AvgWgt",INPUT."CTR",INPUT."TotRtn",INPUT."TotAttr",INPUT."Alloc",INPUT."Selec",INPUT."Curr",INPUT."ID059",INPUT."Ticker",INPUT."CUSIP",INPUT."ISIN",INPUT."SEDOL1",INPUT."FILENAME",INPUT."FileType",INPUT."CADIS_SYSTEM_INSERTED" "CADIS_SYSTEM_INSERTED0",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0"
FROM 
"CADIS_PROC"."DI_ISSCTR_RESULTS" RESULT
JOIN
(SELECT 
'Validate ISS_CTR' AS SOURCE_COMPONENT, 
*
 FROM "dbo"."T_BBG_IssuerSec_CTR_IN"
WHERE SECURITY IS NOT NULL

) AS INPUT ON
RESULT."PortfolioGroup"=INPUT."PortfolioGroup" AND
RESULT."ReportDate"=INPUT."ReportDate" AND
RESULT."Security"=INPUT."Security" AND
(1=1)
