CREATE VIEW "CADIS"."DI_VANTEIARPT_STAGE_RSLT" AS
SELECT
	RESULT."Primary Key Unique?",RESULT."Fund Short Name Mapping Exists?",RESULT."EDM_SEC_ID Mapping Exists?",RESULT."FUND_FISCAL_YEAR Populated?",RESULT."FUND_FISCAL_QUARTER Populated?",RESULT."All Tests Passed?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",INPUT."PK_RANK",INPUT."PK_COLUMNS",INPUT."PK_VALUE",INPUT."SOURCE_COMPONENT",INPUT."ID",INPUT."ACCOUNT_NUMBER",INPUT."SECURITY_NUMBER",INPUT."VALUATION_DATE",INPUT."SECURITY_DESCRIPTION",INPUT."SEDOL",INPUT."CUSIP",INPUT."COUNTRY_OF_TAXATION",INPUT."STATE_CODE",INPUT."ASSET_GROUP",INPUT."EX_DATE_SHARES",INPUT."EX_DATE",INPUT."ACCRUED_INCOME",INPUT."INCOME_RECEIVED",INPUT."PRIOR_INC_ACCRUED",INPUT."INCOME_EARNED",INPUT."AMORT_ACCRUED",INPUT."AMORT_SOLD",INPUT."PRIOR_AMORT_ACCRUED",INPUT."AMORT_EARNED",INPUT."TOTAL_INC_AND_AMORT_EARNED",INPUT."UNITS",INPUT."FUND_NET_INCOME",INPUT."RATE",INPUT."FUND_SHORT_NAME",INPUT."EDM_SEC_ID",INPUT."FUND_FISCAL_YEAR",INPUT."FUND_FISCAL_QUARTER",INPUT."CADIS_SYSTEM_INSERTED" "CADIS_SYSTEM_INSERTED0",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0",INPUT."CADIS_SYSTEM_CHANGEDBY" "CADIS_SYSTEM_CHANGEDBY0",INPUT."CADIS_SYSTEM_RUNID",INPUT."CADIS_SYSTEM_TOPRUNID"
FROM 
"CADIS_PROC"."DI_VANTEIARPT_RESULTS" RESULT
JOIN
(SELECT 
	ROW_NUMBER() OVER (PARTITION BY [FUND_SHORT_NAME],[EDM_SEC_ID],
		[FUND_FISCAL_YEAR],[FUND_FISCAL_QUARTER] 
		ORDER BY [EX_DATE] DESC)					AS [PK_RANK],
	'FUND_SHORT_NAME,EDM_SEC_ID,FUND_FISCAL_YEAR,FUND_FISCAL_QUARTER'	AS [PK_COLUMNS],
	 CAST([FUND_SHORT_NAME] AS VARCHAR(50)) + ' ' + 
		CAST([EDM_SEC_ID] AS VARCHAR(10)) + ' ' +  
		CAST([FUND_FISCAL_YEAR] AS VARCHAR(4)) + ' ' + 
		CAST([FUND_FISCAL_QUARTER] AS VARCHAR(1)) 			AS [PK_VALUE],
	'Validate NT Earned Income Typed'					AS [SOURCE_COMPONENT],
	* 
FROM "dbo"."T_NT_EARNED_INCOME_STAGE") AS INPUT ON
RESULT."ID"=INPUT."ID" AND
(1=1)
