CREATE VIEW "CADIS"."DI_VLHWPOSID_HWPOSSRC_RSLT" AS
SELECT
	RESULT."Is Valid Sedol?",RESULT."Is Valid Currency?",RESULT."Is Valid Asset Class?",RESULT."Is Valid PK?",RESULT."All Tests Passed?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",RESULT."CADIS_SYSTEM_RUNID",RESULT."CADIS_SYSTEM_TOPRUNID",INPUT."SOURCE_COMPONENT",INPUT."SEDOL",INPUT."CURRENCY",INPUT."ROW_NUMBER",INPUT."FILE_NAME",INPUT."FILE_TYPE",INPUT."FILE_DATE",INPUT."CUSTOMER_CODE",INPUT."MODEL_CODE",INPUT."MODEL_DATE",INPUT."MODEL_DESCRIPTION",INPUT."INSTRUMENT_UII",INPUT."STOCK_SHORT_NAME",INPUT."SECTOR_CODE",INPUT."UII_ALLOCATION_PCT",INPUT."CURRENT_PERCENTAGE",INPUT."CHANGE_PERCENTAGE",INPUT."START_PRICE",INPUT."START_PRICE_DATE",INPUT."CURRENT_PRICE",INPUT."CURRENT_DATE",INPUT."CADIS_SYSTEM_INSERTED" "CADIS_SYSTEM_INSERTED0",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0",INPUT."CADIS_SYSTEM_CHANGEDBY" "CADIS_SYSTEM_CHANGEDBY0",INPUT."CADIS_SYSTEM_PRIORITY",INPUT."CADIS_SYSTEM_TIMESTAMP",INPUT."CADIS_SYSTEM_LASTMODIFIED"
FROM 
"CADIS_PROC"."DI_VLHWPOSID_RESULTS" RESULT
JOIN
(SELECT 'Validate HW Position Identifiers' AS SOURCE_COMPONENT, 
	INSTRUMENT_UII AS SEDOL, 
	IIF(LEFT(INSTRUMENT_UII,1) = '9' AND ISNUMERIC(INSTRUMENT_UII) = 1,INSTRUMENT_UII,NULL) AS CURRENCY, 
	* 
FROM "dbo"."T_HW_POSITIONS_STAGE"

) AS INPUT ON
RESULT."MODEL_CODE"=INPUT."MODEL_CODE" AND
RESULT."MODEL_DATE"=INPUT."MODEL_DATE" AND
RESULT."INSTRUMENT_UII"=INPUT."INSTRUMENT_UII" AND
(1=1)
