CREATE VIEW "CADIS"."DI_VSJPGFFI_SJP_RSLT" AS
SELECT
	RESULT."Fund Short Name Populated?",RESULT."Transaction Date Populated?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",INPUT."ROW_NUMBER",INPUT."TYPE",INPUT."FUND_SHORT_NAME",INPUT."TRANSACTION_DATE",INPUT."CURRENCY",INPUT."FUND_FLOW_TYPE",INPUT."FLOW_TYPE",INPUT."MARKET_VALUE",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0"
FROM 
"CADIS_PROC"."DI_VSJPGFFI_RESULTS" RESULT
JOIN
(SELECT ROW_NUMBER,TYPE,FUND_SHORT_NAME,TRANSACTION_DATE,CURRENCY,
FUND_FLOW_TYPE, FLOW_TYPE, MARKET_VALUE, CADIS_SYSTEM_UPDATED
 FROM "dbo"."T_SJP_FUND_FLOW_POST") AS INPUT ON
RESULT."ROW_NUMBER"=INPUT."ROW_NUMBER" AND
RESULT."TYPE"=INPUT."TYPE" AND
(1=1)
