CREATE VIEW "CADIS"."DI_VITGRERC_IN_RSLT" AS
SELECT
	RESULT."Order Row Counts Match?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",INPUT."ORDERID",INPUT."FILE_DATE",INPUT."VALUE_IN",INPUT."VALUE_OUT"
FROM 
"CADIS_PROC"."DI_VITGRERC_RESULTS" RESULT
JOIN
(SELECT 	ISNULL(I.ORDERID, O.ORDERID) AS ORDERID, M.FILE_DATE, I.VALUE_IN, O.VALUE_OUT
FROM	(
	SELECT	ORDERID, ISNULL(COUNT(*),0) AS VALUE_IN 
	FROM	"DBO"."T_TCA_ITG_RESPONSE_EXECUTIONS_STAGE"  
	GROUP	BY ORDERID
	) I
FULL	OUTER JOIN 
	(
	SELECT	ORDERID, ISNULL(COUNT(*),0) AS VALUE_OUT 
	FROM	"TCA"."EMSX_Trade_Fill_Output" 
	GROUP	BY ORDERID
	) O
ON	I.ORDERID = O.ORDERID
INNER	JOIN
	(SELECT MAX(FILE_DATE) AS FILE_DATE FROM "DBO"."T_TCA_ITG_RESPONSE_EXECUTIONS_STAGE") M
ON	1=1) AS INPUT ON
RESULT."ORDERID"=INPUT."ORDERID" AND
(1=1)
