CREATE VIEW "CADIS"."DI_VLRGLMTSUM_VLRGLMTSUM_RSLT" AS
SELECT
	RESULT."Is Valid EFFECTIVE_DATE?",RESULT."Is Valid REPORT_DATE?",RESULT."Is FUND_CODE NOT NULL?",RESULT."Is RULE_ID NOT NULL?",RESULT."Is Valid RULE_NAME?",RESULT."Is Valid RULE_CCY?",RESULT."Is RULE_LIMIT not null?",RESULT."Is VALUE Not Null?",RESULT."Is ROOM Not Null?",RESULT."Is IN_VIOLATION Flag Valid?",RESULT."All Tests Passed?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",INPUT."ROW_ID",INPUT."FUND_CODE",INPUT."RULE_ID",INPUT."RULE_NAME",INPUT."RULE_CCY",INPUT."SCOPE_CONTEXT",INPUT."RISK_LABEL",INPUT."RULE_LIMIT",INPUT."VALUE",INPUT."ROOM",INPUT."IN_VIOLATION",INPUT."EFFECTIVE_DATE",INPUT."REPORT_DATE",INPUT."CONVERTED_EFFECTIVE_DATE",INPUT."CONVERTED_REPORT_DATE",INPUT."CADIS_SYSTEM_INSERTED" "CADIS_SYSTEM_INSERTED0",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0",INPUT."CADIS_SYSTEM_CHANGEDBY" "CADIS_SYSTEM_CHANGEDBY0",INPUT."CADIS_SYSTEM_PRIORITY"
FROM 
"CADIS_PROC"."DI_VLRGLMTSUM_RESULTS" RESULT
JOIN
(SELECT * FROM "dbo"."T_REGULATORY_RULE_SUMMARY_STAGE" WHERE /* remove "Scope:" RULE_ID rows from the inspection and load as these are the subtitles in the Excel ragged hierarchy */
RULE_ID NOT LIKE '%Scope:%') AS INPUT ON
RESULT."ROW_ID"=INPUT."ROW_ID" AND
(1=1)
