CREATE VIEW "CADIS"."DI_VTSJPHIYGF_SJPHIY_RSLT" AS
SELECT
	RESULT."Transaction Date Populated?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",INPUT."ROW_NUMBER",INPUT."TYPE",INPUT."FUND",INPUT."TRANSACTION_DATE",INPUT."FUND_FLOW_TYPE",INPUT."FLOW_TYPE",INPUT."SETTLEMENT_DATE",INPUT."MARKET_VALUE",INPUT."CADIS_SYSTEM_INSERTED" "CADIS_SYSTEM_INSERTED0",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0",INPUT."CADIS_SYSTEM_CHANGEDBY" "CADIS_SYSTEM_CHANGEDBY0",INPUT."CADIS_SYSTEM_PRIORITY",INPUT."CADIS_SYSTEM_LASTMODIFIED"
FROM 
"CADIS_PROC"."DI_VTSJPHIYGF_RESULTS" RESULT
JOIN
"dbo"."T_SJPHIY_GROSS_FUND_FLOW" AS INPUT ON
RESULT."ROW_NUMBER"=INPUT."ROW_NUMBER" AND
RESULT."TYPE"=INPUT."TYPE" AND
(1=1)
