CREATE VIEW "CADIS"."DI_VLNTPOSID_POS_RSLT" AS
SELECT
	RESULT."Valid Sedol?",RESULT."Valid ISIN?",RESULT."TRADE_DATE Populated?",RESULT."POSITION Populated?",RESULT."ACCOUNT Populated?",RESULT."PRICE Populated?",RESULT."UNIQUE_BLOOMBERG_ID Populated?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",INPUT."ROW_NUMBER",INPUT."EDM_SEC_ID",INPUT."FILE_NAME",INPUT."FILE_TYPE",INPUT."FILE_DATE",INPUT."NUMBER_OF_RECORDS",INPUT."TICKET_NUMBER",INPUT."TRADE_DATE",INPUT."SECURITY_IDENTIFIER_FLAG",INPUT."SECURITY_IDENTIFIER",INPUT."SETTLEMENT_DATE",INPUT."LONGSHORT_INDICATOR",INPUT."POSITION",INPUT."ACCOUNT",INPUT."PRICE_FRACTIONAL_INDICATOR",INPUT."PRICE",INPUT."EXCHANGE_CODE",INPUT."PRODUCT_CODE",INPUT."BRADY-STYLE_FACTOR",INPUT."UNIQUE_BLOOMBERG_ID",INPUT."FX_FORWARD_POINTS",INPUT."SWAP_PAYRECEIVE_FLAG",INPUT."SWAP_FEE",INPUT."PAY_NOTIONAL_AMOUNT",INPUT."RECEIVE_NOTIONAL_AMOUNT",INPUT."FX_AVERAGE_COST",INPUT."IS_SHORT",INPUT."IS_CFD",INPUT."PRIME_BROKER",INPUT."STRATEGY_NAME",INPUT."CADIS_SYSTEM_INSERTED" "CADIS_SYSTEM_INSERTED0",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0",INPUT."CADIS_SYSTEM_CHANGEDBY" "CADIS_SYSTEM_CHANGEDBY0",INPUT."CADIS_SYSTEM_PRIORITY",INPUT."CADIS_SYSTEM_LASTMODIFIED"
FROM 
"CADIS_PROC"."DI_VLNTPOSID_RESULTS" RESULT
JOIN
"dbo"."T_NT_POS_STAGE" AS INPUT ON
RESULT."ROW_NUMBER"=INPUT."ROW_NUMBER" AND
(1=1)
