CREATE VIEW "CADIS"."DI_VTOMTGFF_OMT_RSLT" AS
SELECT
	RESULT."Transaction Date Populated?",RESULT."CADIS_SYSTEM_CHANGEDBY",RESULT."CADIS_SYSTEM_INSERTED",RESULT."CADIS_SYSTEM_UPDATED",INPUT."ROW_NUMBER",INPUT."TYPE",INPUT."FUND",INPUT."TRANSACTION_DATE",INPUT."CURRENCY",INPUT."FUND_FLOW_TYPE",INPUT."FLOW_TYPE",INPUT."SETTLEMENT_DATE",INPUT."MARKET_VALUE",INPUT."SOURCE_TYPE",INPUT."CADIS_SYSTEM_INSERTED" "CADIS_SYSTEM_INSERTED0",INPUT."CADIS_SYSTEM_UPDATED" "CADIS_SYSTEM_UPDATED0",INPUT."CADIS_SYSTEM_CHANGEDBY" "CADIS_SYSTEM_CHANGEDBY0",INPUT."CADIS_SYSTEM_PRIORITY",INPUT."CADIS_SYSTEM_LASTMODIFIED"
FROM 
"CADIS_PROC"."DI_VTOMTGFF_RESULTS" RESULT
JOIN
(SELECT * FROM "dbo"."T_OMT_GROSS_FUND_FLOW") AS INPUT ON
RESULT."ROW_NUMBER"=INPUT."ROW_NUMBER" AND
RESULT."TYPE"=INPUT."TYPE" AND
(1=1)
