CREATE VIEW "CADIS"."DM_PARTY_KEYS" AS 
SELECT  DISTINCT
    MP.ID as "CADIS Id"
    ,MP.PRIORITY as "CADIS Priority"
    ,CASE 
        WHEN COALESCE(SR5.CADISID, -1) >= 0 THEN Cast(0 As Bit)
        WHEN COALESCE(SR6.CADISID, -1) >= 0 THEN Cast(0 As Bit)
        ELSE Cast(1 As Bit) END AS OBSOLETE
    ,CASE COALESCE(SR5.CADISID, -1)
        WHEN -1 THEN Cast(0 As Bit) ELSE Cast(1 As Bit) END AS BBG_BROKER_EXISTS
    ,CASE COALESCE(SR6.CADISID, -1)
        WHEN -1 THEN Cast(0 As Bit) ELSE Cast(1 As Bit) END AS BBG_MASTER_EXISTS
    ,MP.INSERTED as "CADIS_SYSTEM_INSERTED"
    ,MP.UPDATED as "CADIS_SYSTEM_UPDATED"
    ,MP.CHANGEDBY as "CADIS_SYSTEM_CHANGED_BY"
FROM    CADIS_PROC.DM_MATCHPOINT1 MP
    LEFT OUTER JOIN "CADIS_PROC"."DM_MP1_SOURCE5" SR5
        ON MP.ID = SR5.CADISID
    LEFT OUTER JOIN "CADIS_PROC"."DM_MP1_SOURCE6" SR6
        ON MP.ID = SR6.CADISID
