CREATE VIEW "CADIS"."DM_SECURITY_INBOX" AS 
SELECT convert(tinyint,1) as "DM__Status",
	S.LONGNAME as "DM__Source",
	CASE RS.SOURCEID
		WHEN 20 THEN 'UNIQUE_IDENTIFIER: '+CONVERT(VARCHAR(8000),SYSS20."UNIQUE_IDENTIFIER")
		WHEN 21 THEN 'CCY_CODE: '+CONVERT(VARCHAR(8000),SYSS21."CCY_CODE")
		WHEN 243 THEN 'INSTRUMENT_UII: '+CONVERT(VARCHAR(8000),SYSS243."INSTRUMENT_UII")
	END as "DM__Source Key",
	RS.CADISID as "Proposed Cadis Id",
	CASE
		WHEN RS.SOURCEID = 20 AND SYSS20.CADISID IS NOT NULL THEN SYSS20.CADISID
		WHEN RS.SOURCEID = 21 AND SYSS21.CADISID IS NOT NULL THEN SYSS21.CADISID
		WHEN RS.SOURCEID = 243 AND SYSS243.CADISID IS NOT NULL THEN SYSS243.CADISID
		ELSE RS.CADISID
	END as "Assigned Cadis Id",
	CONVERT(TINYINT,RS.PRIORITY) as "DM__Priority",
	RL.RULEID as "Rule Id",
	RL.DESCRIPTION as "Rule Description",
	RL.CONFIDENCELEVEL as "Rule Confidence",
CASE WHEN (RS.COMMENT IS NULL AND RL.RULETYPE = 'DefaultInsert' AND RS.CHANGEDBY='DataMatcherIdGenerator') THEN 'Created by Id Generator'
	WHEN (RS.COMMENT IS NULL AND RL.RULETYPE = 'DefaultInsert') THEN 'Default Insertion'
	WHEN (RS.COMMENT IS NULL AND RL.RULETYPE <> 'DefaultInsert' AND RL.CONFIDENCELEVEL < S.AUTOCONFIDENCELEVEL) THEN 'Low Confidence Match'
	WHEN (RS.COMMENT IS NULL AND RL.RULETYPE <> 'DefaultInsert' AND RL.CONFIDENCELEVEL >= S.AUTOCONFIDENCELEVEL) THEN 'High Confidence Match'
	WHEN (RS.COMMENT LIKE 'Remarked match as provisional as subsequent rule processing has failed%') THEN 'Subsequent Processing No Match'
	WHEN (RS.COMMENT LIKE 'Remarked match as provisional as original match rule subsequently%') THEN 'Subsequent Processing Different Match'
	WHEN (RS.COMMENT LIKE 'Default insertion required because rule%') THEN 'Default Insertion Required To Prevent Duplicates'
	WHEN (RS.COMMENT LIKE 'Automatic rule result set as provisional because duplicate%') THEN 'High Confidence but Duplicate Match Marked Provisional'
	WHEN (RS.COMMENT LIKE 'Match assigned provisionally as the rule returned multiple matches%' AND RL.CONFIDENCELEVEL >= S.AUTOCONFIDENCELEVEL) THEN 'High Confidence Match to Multiple Ids'
	WHEN (RS.COMMENT LIKE 'Match assigned provisionally as the rule returned multiple matches%' AND RL.CONFIDENCELEVEL < S.AUTOCONFIDENCELEVEL) THEN 'Low Confidence Match to Multiple Ids'
	ELSE 'Set Provisionally For Manual Verification'
	END as "Reason",	RS.INSERTED as "Matched Date",
	RS.UPDATED as "Match Updated Date",
	RS.CHANGEDBY as "Matched By",
	RS.SOURCEROWID as "Source Row Id"
	, NULL as "CADIS Inserted", NULL as "CADIS Updated"
	, NULL as "CADIS Changed By", NULL as "CADIS Row Id"
	, CASE 
		WHEN (RS.SOURCEID=20 AND SYSS20.CADISID IS NOT NULL) THEN ISNULL(CONVERT(VARCHAR(8000),S20."SEDOL1_NUMBER"),'')
		WHEN (RS.SOURCEID=21 AND SYSS21.CADISID IS NOT NULL) THEN ''
		WHEN (RS.SOURCEID=243 AND SYSS243.CADISID IS NOT NULL) THEN ISNULL(CONVERT(VARCHAR(8000),S243."INSTRUMENT_UII"),'')
		ELSE 'Obsolete Row'
	END AS "Sedol"
	, RS.SOURCEID as "DM__Source Id"
	FROM "CADIS_PROC"."DM_MP2_RESULT" RS
	INNER JOIN CADIS_SYS.DM_RULE RL ON RL.RULEID = RS.RULEID
	INNER JOIN CADIS_SYS.DM_SOURCE S ON S.SOURCEID = RS.SOURCEID
	LEFT OUTER JOIN "CADIS_PROC"."DM_MP2_SOURCE20" SYSS20 ON RS.SOURCEID = 20 AND RS.SOURCEROWID = SYSS20."CADISROWID"
	LEFT OUTER JOIN "dbo"."T_BBG_AIM_SEC" S20 ON SYSS20."UNIQUE_IDENTIFIER" = S20."UNIQUE_IDENTIFIER"
	LEFT OUTER JOIN "CADIS_PROC"."DM_MP2_SOURCE21" SYSS21 ON RS.SOURCEID = 21 AND RS.SOURCEROWID = SYSS21."CADISROWID"
	LEFT OUTER JOIN "dbo"."T_NT_CURRENCY_CODES" S21 ON SYSS21."CCY_CODE" = S21."CCY_CODE"
	LEFT OUTER JOIN "CADIS_PROC"."DM_MP2_SOURCE243" SYSS243 ON RS.SOURCEID = 243 AND RS.SOURCEROWID = SYSS243."CADISROWID"
	LEFT OUTER JOIN "dbo"."vw_HW_POSITIONS" S243 ON SYSS243."INSTRUMENT_UII" = S243."INSTRUMENT_UII"
	WHERE S.OBSOLETE = 0
	AND RS.PROVISIONAL = 1
	AND (
		(RS.SOURCEID = 20 AND S20."UNIQUE_IDENTIFIER" IS NOT NULL)
		OR
		(RS.SOURCEID = 21 AND S21."CCY_CODE" IS NOT NULL)
		OR
		(RS.SOURCEID = 243 AND S243."INSTRUMENT_UII" IS NOT NULL)
	)
