CREATE VIEW "CADIS"."DM_SECURITY_KEYS" AS 
SELECT  DISTINCT
    MP.ID as "CADIS Id"
    ,MP.PRIORITY as "CADIS Priority"
    ,CASE 
        WHEN COALESCE(SR20.CADISID, -1) >= 0 THEN Cast(0 As Bit)
        WHEN COALESCE(SR21.CADISID, -1) >= 0 THEN Cast(0 As Bit)
        WHEN COALESCE(SR243.CADISID, -1) >= 0 THEN Cast(0 As Bit)
        ELSE Cast(1 As Bit) END AS OBSOLETE
    ,CASE COALESCE(SR20.CADISID, -1)
        WHEN -1 THEN Cast(0 As Bit) ELSE Cast(1 As Bit) END AS BLOOMBERG_EXISTS
    ,CASE COALESCE(SR21.CADISID, -1)
        WHEN -1 THEN Cast(0 As Bit) ELSE Cast(1 As Bit) END AS CURRENCY_EXISTS
    ,CASE COALESCE(SR243.CADISID, -1)
        WHEN -1 THEN Cast(0 As Bit) ELSE Cast(1 As Bit) END AS HUBWISE_EXISTS
    ,MP.INSERTED as "CADIS_SYSTEM_INSERTED"
    ,MP.UPDATED as "CADIS_SYSTEM_UPDATED"
    ,MP.CHANGEDBY as "CADIS_SYSTEM_CHANGED_BY"
FROM    CADIS_PROC.DM_MATCHPOINT2 MP
    LEFT OUTER JOIN "CADIS_PROC"."DM_MP2_SOURCE20" SR20
        ON MP.ID = SR20.CADISID
    LEFT OUTER JOIN "CADIS_PROC"."DM_MP2_SOURCE21" SR21
        ON MP.ID = SR21.CADISID
    LEFT OUTER JOIN "CADIS_PROC"."DM_MP2_SOURCE243" SR243
        ON MP.ID = SR243.CADISID
