CREATE VIEW "CADIS"."IL_KPI_Groups" AS 
SELECT V."KPIGroupId" AS "KPI Group ID",V."KPIGroupName" AS "KPI Group Name",V."KPIGroupDescription" AS "KPI Group Description",V."CADIS_SYSTEM_INSERTED",V."CADIS_SYSTEM_UPDATED",V."CADIS_SYSTEM_CHANGEDBY",V."CADIS_SYSTEM_PRIORITY",V."CADIS_SYSTEM_TIMESTAMP",V."CADIS_SYSTEM_LASTMODIFIED" FROM "KPI"."KPIGroups" V
