CREATE VIEW "CADIS"."IL_Risk_Categories" AS 
SELECT V."CategoryId" AS "Category ID",V."Category" AS "Category",V."CreatedDate" AS "Created Date",V."CADIS_SYSTEM_INSERTED",V."CADIS_SYSTEM_UPDATED",V."CADIS_SYSTEM_CHANGEDBY",V."CADIS_SYSTEM_PRIORITY",V."CADIS_SYSTEM_TIMESTAMP",V."CADIS_SYSTEM_LASTMODIFIED" FROM "Risk"."Categories" V
