CREATE VIEW "CADIS"."IL_Share_Class_Income_Annual" AS 
SELECT V."FUND_SHORT_NAME" AS "Fund Short Name",V."SHARE_CLASS_NAME" AS "Share Class Name",V."FUND_FISCAL_YEAR" AS "Fund Fiscal Year",V."UNITS_IN_ISSUE" AS "Units In Issue",V."FUND_VALUE" AS "Fund Value",V."SHARE_CLASS_NET_INCOME" AS "Net Income",V."SHARE_CLASS_RATE" AS "Rate" FROM "CADIS"."VW_UI_SHARECLASS_INCOME_ANNUAL" V
