CREATE VIEW "CADIS"."IL_T_PKGD_FILE_UAT_FINAL" AS 
SELECT V."FILE_NAME" AS "Filename",V."CLIENT" AS "Client",V."ENV" AS "Env",V."TIME_STAMP" AS "Timestamp",V."STATUS_DECODE" AS "Latest Status",V."PATH" AS "UNC Path",V."CADIS_SYSTEM_INSERTED",V."CADIS_SYSTEM_UPDATED",V."CADIS_SYSTEM_CHANGEDBY" FROM "dbo"."T_PKGD_FILE_UAT_FINAL" V
