CREATE VIEW "CADIS"."IL_Unquoted_Investment_New_Issuer" AS 
SELECT V."NEW_ISSUER" AS "New Issuer", J2.DF AS "Currency",V."TECH_STATUS" AS "Complete" FROM "dbo"."T_UNQUOTED_NEW_ISSUER" V LEFT OUTER JOIN (SELECT DISTINCT "NAME" AS JF,"VALUE" AS DF FROM "dbo"."V_REF_CURRENCY_LOOKUP")  J2 ON  J2.JF=V."SECURITY_ISO_CCY"
