CREATE VIEW "CADIS"."VW_Business_Exceptions_Inboxes"
AS
SELECT 
EXCEPTION_DATE
, ENTITY
, "STATUS"
, "SOURCE"
, "PRIORITY"
, EXCEPTION_NAME
, CONVERT(VARCHAR, ENTITY) AS EDM_SEC_ID
FROM T_EXCEPTION_SEC

UNION ALL

SELECT 
EXCEPTION_DATE
, ENTITY
, "STATUS"
, "SOURCE"
, "PRIORITY"
, EXCEPTION_NAME
, CONVERT(VARCHAR, ENTITY) AS EDM_SEC_ID
FROM T_EXCEPTION_FUND

