CREATE VIEW "CADIS"."VW_Business_Exceptions_Summary_Detail"
AS
SELECT *
,CASE WHEN "PRIORITY" = 'High' THEN 1
	WHEN "PRIORITY" = 'Medium' THEN 2
	WHEN "PRIORITY" = 'Low' THEN 3
	ELSE 4 
	END AS SORT
FROM (

SELECT TOP (100)
"PRIORITY"
, ENTITY
, EXCEPTION_NAME
, [NEW], [OPEN], [CLOSED]
, (ISNULL([OPEN], 0) 
	+ ISNULL([NEW], 0) 
	+ ISNULL([CLOSED], 0)) AS [TOTAL]
FROM       
( 
 SELECT  "STATUS"
	, CASE WHEN (GROUPING(ENTITY) = 1) 
	THEN 'ALL' 
	ELSE ISNULL(ENTITY, 'UNKNOWN') END AS ENTITY
	
	, CASE WHEN (GROUPING(EXCEPTION_NAME) = 1) 
	THEN 'ALL' 
	ELSE ISNULL(EXCEPTION_NAME, 'UNKNOWN') END AS EXCEPTION_NAME
	
	, CASE WHEN (GROUPING("PRIORITY") = 1) 
	THEN 'ALL' 
	ELSE ISNULL("PRIORITY", 'UNKNOWN') END AS PRIORITY
	, COUNT(PRIORITY) AS [COUNT]

 FROM "CADIS"."VW_Business_Exceptions_Inboxes"

	GROUP BY 
	ENTITY, "STATUS" ,"PRIORITY", EXCEPTION_NAME
	WITH ROLLUP
) P 
PIVOT 
(SUM([COUNT]) FOR "STATUS" IN ( [ALL], [NEW], [OPEN], [CLOSED]) ) AS PVT
WHERE EXCEPTION_NAME <> 'ALL'

) A
WHERE NEW IS NOT NULL
