CREATE VIEW "CADIS"."VW_Console_Grouping_and_Security"
AS
SELECT A.GROUPID,A.NAME,A.PARENTGROUP, (SELECT TOP 1 NAME FROM CADIS_SYS.CO_GROUP WHERE GROUPID=A.PARENTGROUP) AS PARENTGROUPNAME,
B.NAME AS USERNAME,B.GROUPID AS GROUPID_GROUP,B.USERTYPE,B.PERMISSION,
 CASE WHEN B.PERMISSION=1 THEN 'READ'
   WHEN B.PERMISSION=2 THEN 'WRITE'
   WHEN B.PERMISSION=3 THEN 'READ,WRITE'
   WHEN B.PERMISSION=4 THEN 'EXECUTE'
   WHEN B.PERMISSION=5 THEN 'READ,EXECUTE'
   WHEN B.PERMISSION=6 THEN 'WRITE,EXECUTE'
   WHEN B.PERMISSION=7 THEN 'READ,WRITE,EXECUTE'
   WHEN B.PERMISSION=8 THEN 'CREATE'
   WHEN B.PERMISSION=9 THEN 'READ,CREATE'
   WHEN B.PERMISSION=10 THEN 'WRITE,CREATE'
   WHEN B.PERMISSION=11 THEN 'READ,WRITE,CREATE'
   WHEN B.PERMISSION=12 THEN 'EXECUTE,CREATE'
   WHEN B.PERMISSION=13 THEN 'READ,EXECUTE,CREATE'
   WHEN B.PERMISSION=14 THEN 'WRITE,EXECUTE,CREATE'
   WHEN B.PERMISSION=15 THEN 'READ,WRITE,EXECUTE,CREATE'
   WHEN B.PERMISSION=16 THEN 'DELETE'
   WHEN B.PERMISSION=17 THEN 'READ,DELETE'
   WHEN B.PERMISSION=18 THEN 'WRITE,DELETE'
   WHEN B.PERMISSION=19 THEN 'READ,WRITE,DELETE'
   WHEN B.PERMISSION=20 THEN 'EXECUTE,DELETE'
   WHEN B.PERMISSION=21 THEN 'READ,EXECUTE,DELETE'
   WHEN B.PERMISSION=22 THEN 'WRITE,EXECUTE,DELETE'
   WHEN B.PERMISSION=23 THEN 'READ,WRITE,EXECUTE,DELETE'
   WHEN B.PERMISSION=24 THEN 'CREATE,DELETE'
   WHEN B.PERMISSION=25 THEN 'READ,CREATE,DELETE'
   WHEN B.PERMISSION=26 THEN 'WRITE,CREATE,DELETE'
   WHEN B.PERMISSION=27 THEN 'READ,WRITE,CREATE,DELETE'
   WHEN B.PERMISSION=28 THEN 'EXECUTE,CREATE,DELETE'
   WHEN B.PERMISSION=29 THEN 'READ,EXECUTE,CREATE,DELETE'
   WHEN B.PERMISSION=30 THEN 'WRITE,EXECUTE,CREATE,DELETE'
   WHEN B.PERMISSION=31 THEN 'READ,WRITE,EXECUTE,CREATE,DELETE'
 END AS PERMISSIONDESCRIPTION
 FROM CADIS_SYS.CO_GROUP A
INNER JOIN CADIS_SYS.CO_GROUPUSER B
ON A.GROUPID=B.GROUPID
--ORDER BY A.GROUPID,A.NAME
