CREATE VIEW "CADIS"."VW_Console_Grouping_and_Security_Console_Folder_Only"
AS
SELECT TOP 99999 A.NAME, (SELECT TOP 1 NAME FROM CADIS_SYS.CO_GROUP WHERE GROUPID=A.PARENTGROUP) AS PARENTGROUPNAME
FROM CADIS_SYS.CO_GROUP A
ORDER BY A.NAME
