CREATE VIEW "CADIS"."VW_Master_FX_Rate_Currency_List"
AS
SELECT 	DISTINCT 
	T1.[CCY_NAME] AS NAME,
	T2.[FROM_ISO_CURRENCY_CODE] AS VALUE

FROM "dbo"."T_MASTER_FXRATE" T2
LEFT JOIN "dbo"."T_REF_CURRENCY" T1
ON T2.[FROM_ISO_CURRENCY_CODE] = T1.[ISO_CCY_CD]
WHERE T1.[CCY_NAME] IS NOT NULL
