CREATE VIEW "CADIS"."VW_Master_FX_Rate_Store_Previous_Day"
AS
SELECT * FROM (
	SELECT	ROW_NUMBER() OVER(PARTITION BY S.FXRATE_ID,S.TO_ISO_CURRENCY_CODE ORDER BY S.DATE DESC) ROW,
	S.* 
FROM "dbo"."T_MASTER_FXRATE_STORE" S
LEFT JOIN "dbo"."T_MASTER_FXRATE" P 
	ON 	S.FXRATE_ID = P.FXRATE_ID AND
		S.TO_ISO_CURRENCY_CODE = P.TO_ISO_CURRENCY_CODE
WHERE S.DATE <> P.DATE 
) STORE
WHERE ROW = 1​
