CREATE VIEW "CADIS"."VW_NT_SEC_INCOME"
AS
SELECT 
	[FUND_SHORT_NAME],
	[EDM_SEC_ID],
	[FUND_FISCAL_YEAR],
	MAX([VALUATION_DATE])	AS [VALUATION_DATE],
	MAX([I1])		AS [Q1_INCOME_EARNED],
	MAX([I2])		AS [Q2_INCOME_EARNED],
	MAX([I3])		AS [Q3_INCOME_EARNED],
	MAX([I4])		AS [Q4_INCOME_EARNED]
FROM (
	SELECT
		[VALUATION_DATE],
		[FUND_SHORT_NAME],
		[EDM_SEC_ID],
		[FUND_FISCAL_YEAR],
		[EX_DATE],
		[INCOME_EARNED],
		'I' + CAST([FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_INCOME_EARNED]
	FROM "dbo"."T_NT_EARNED_INCOME_SEC_STAGE"
) UNP
PIVOT (MAX([INCOME_EARNED]) FOR [QUARTER_INCOME_EARNED] IN ([I1],[I2],[I3],[I4])) AS [INC]
GROUP BY [FUND_SHORT_NAME],[EDM_SEC_ID],[FUND_FISCAL_YEAR]
