CREATE VIEW "CADIS"."VW_OVERRIDE_INCOME"
AS
SELECT
	UNP.[FUND_SHORT_NAME],
	UNP.[EDM_SEC_ID],
	UNP.[FUND_FISCAL_YEAR],
	UNP.[FUND_FISCAL_QUARTER],
	PRE.[DVD_CCY],
	PRE.[WITHHOLDING_TAX],
	PRE.[DECLARED_DATE],
	PRE.[POSITION_DATE],
	PRE.[POSITION],
	PRE.[BID_PRICE],
	PRE.[SPOT_RATE],
	PRE.[MARKET_VALUE],
	CASE
		WHEN UNP.[FUND_FISCAL_QUARTER] = 1 THEN [Q1_EX_DATE]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 2 THEN [Q2_EX_DATE]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 3 THEN [Q3_EX_DATE]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 4 THEN [Q4_EX_DATE]
	END								AS [EX_DATE],
	CASE
		WHEN UNP.[FUND_FISCAL_QUARTER] = 1 THEN [Q1_RATE]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 2 THEN [Q2_RATE]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 3 THEN [Q3_RATE]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 4 THEN [Q4_RATE]
	END								AS [RATE],
	CASE
		WHEN UNP.[FUND_FISCAL_QUARTER] = 1 THEN [Q1_NET_INCOME]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 2 THEN [Q2_NET_INCOME]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 3 THEN [Q3_NET_INCOME]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 4 THEN [Q4_NET_INCOME]
	END								AS [NET_INCOME],
	CASE
		WHEN UNP.[FUND_FISCAL_QUARTER] = 1 THEN [Q1_NOTES]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 2 THEN [Q2_NOTES]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 3 THEN [Q3_NOTES]
		WHEN UNP.[FUND_FISCAL_QUARTER] = 4 THEN [Q4_NOTES]
	END								AS [NOTES]
FROM (
	SELECT * FROM (
		SELECT
			OVR.[FUND_SHORT_NAME],
			OVR.[EDM_SEC_ID],
			OVR.[FUND_FISCAL_YEAR],
			OVR.[Q1_FISCAL_QUARTER],
			OVR.[Q1_EX_DATE],
			OVR.[Q1_RATE],
			OVR.[Q1_NET_INCOME],
			OVR.[Q1_NOTES],
			OVR.[Q2_FISCAL_QUARTER],
			OVR.[Q2_EX_DATE],
			OVR.[Q2_RATE],
			OVR.[Q2_NET_INCOME],
			OVR.[Q2_NOTES],
			OVR.[Q3_FISCAL_QUARTER],
			OVR.[Q3_EX_DATE],
			OVR.[Q3_RATE],
			OVR.[Q3_NET_INCOME],
			OVR.[Q3_NOTES],
			OVR.[Q4_FISCAL_QUARTER],
			OVR.[Q4_EX_DATE],
			OVR.[Q4_RATE],
			OVR.[Q4_NET_INCOME],
			OVR.[Q4_NOTES]
		FROM "dbo"."T_OVERRIDE_ANNUAL_INCOME" OVR) AS PIV
	UNPIVOT ([FUND_FISCAL_QUARTER] FOR [FUND_FISCAL_QUARTERS] IN (
			[Q1_FISCAL_QUARTER],
			[Q2_FISCAL_QUARTER],
			[Q3_FISCAL_QUARTER],
			[Q4_FISCAL_QUARTER])) AS UNP
) AS UNP CROSS APPLY (
	SELECT TOP 1 * FROM "dbo"."T_PRE_SECURITY_INCOME" PRE
	WHERE PRE.[POSITION_DATE] IS NOT NULL
		AND UNP.[FUND_SHORT_NAME] = PRE.[FUND_SHORT_NAME]
		AND UNP.[EDM_SEC_ID] = PRE.[EDM_SEC_ID]
		AND UNP.[FUND_FISCAL_YEAR] = PRE.[FUND_FISCAL_YEAR]
	ORDER BY PRE.[CADIS_SYSTEM_UPDATED] DESC
) PRE
