CREATE VIEW "CADIS"."VW_Process_Monitor_SLA_Latest"
AS
SELECT * FROM (

SELECT 
  ROW_NUMBER() OVER(PARTITION BY SOURCE, ENTITY,"DESCRIPTION", DIRECTION ORDER BY ACTUAL_DELIVERY DESC) ROWN
, SOURCE
, ENTITY
,"DESCRIPTION"
, DIRECTION
, [CURRENT_SLA_DATE]
, [EXPECTED_DELIVERY_TIME]
, [ACTUAL_DELIVERY]
, [DELIVERY_SLA_MET]
, [EXPECTED_SLA_COMPLETION]
, [ACTUAL_SLA_COMPLETION]
, [PROCESSING_SLA_MET]
, [PROCESSING_TIME]
, [DATA_CHANNEL_ID]
, [MARKIT_SOLUTION]
, [MORNING_CHECK]
FROM "CADIS"."VW_Process_Monitor_SLA" SLA


) A
WHERE ROWN = 1

