CREATE VIEW [CADIS].[VW_PROCESSAUDIT]
AS
SELECT A.*,
	CASE A.[ACTION] WHEN 0 THEN 'Created' WHEN 1 THEN 'Updated' WHEN 2 THEN 'Deleted' ELSE 'Verified' END AS ACTIONDESCRIPTION,
	C.NAME AS PROCESSTYPE, V.NAME
FROM [CADIS_SYS].[CO_PROCESSAUDIT] A
JOIN [CADIS_SYS].[CO_COMPONENT] C ON C.ID=A.COMPONENTID
LEFT JOIN [CADIS_SYS].VW_ALL_PROCESSES V ON V.COMPONENTID=A.COMPONENTID AND V.IDENTIFIER=A.IDENTIFIER AND V.GUID=A.GUID
