CREATE VIEW "CADIS"."VW_Sales_Force_Movements_Admin"
AS
select 
		 T1.[ENTITY]
		,T1.[SUB_ENTITY]
		,T1.[FIELD]
		,T1.[FIELD_VALUE]
		,T1.[INT_VALUE]
		,T1.[CADIS_SYSTEM_INSERTED]
		,T1.[CADIS_SYSTEM_UPDATED]
		,T1.[CADIS_SYSTEM_CHANGEDBY]
		,T1.[CADIS_SYSTEM_PRIORITY]
		,T1.[CADIS_SYSTEM_TIMESTAMP] AS CADIS_SYSTEM_TIMESTAMP_1
FROM		"dbo"."T_REF_LOOKUP" T1
