CREATE VIEW "CADIS"."VW_System_Space_Used"
AS
SELECT 
  CASE WHEN type_desc = 'rows' Then 'Database' else 'Logs' END AS TYPE
, CONVERT(DECIMAL(20,2), CONVERT(DECIMAL(20,2),size)/100000) AS SPACE_USED
, CONVERT(DECIMAL(20,2), CONVERT(DECIMAL(20,2),size)/CONVERT(DECIMAL(20,2),1200000) *100) PERCENT_USED
FROM sys.database_files 
