CREATE VIEW "CADIS"."VW_UI_SHARECLASS_INCOME"
AS
SELECT
	SCV.[VALUATION_DATE],
	SC.[FUND_SHORT_NAME],
	SC.[SHARECLASS],
	SCV.[UNITS_IN_ISSUE],
	SCV.[FUND_VALUE]
FROM "dbo"."T_MASTER_SHARECLASS_VALUATION" SCV
	INNER JOIN "dbo"."T_MASTER_SHARECLASS" SC ON SCV.[EDM_SHARECLASS_ID] = SC.[EDM_SHARECLASS_ID]
UNION ALL
SELECT
	SCV.[VALUATION_DATE],
	SC.[FUND_SHORT_NAME],
	'Total'				AS [SHARECLASS],
	SUM(SCV.[UNITS_IN_ISSUE])	AS [UNITS_IN_ISSUE],
	SUM(SCV.[FUND_VALUE])		AS [FUND_VALUE]
FROM "dbo"."T_MASTER_SHARECLASS_VALUATION" SCV
	INNER JOIN "dbo"."T_MASTER_SHARECLASS" SC ON SCV.[EDM_SHARECLASS_ID] = SC.[EDM_SHARECLASS_ID]
GROUP BY SCV.[VALUATION_DATE],SC.[FUND_SHORT_NAME]
