CREATE VIEW "CADIS"."VW_UI_FND_ANNUAL_INCOME"
AS
SELECT 
	[VALUATION_DATE],
	[FUND_SHORT_NAME],
	[FUND_FISCAL_YEAR],
	MAX([UNITS_IN_ISSUE])	AS [UNITS_IN_ISSUE],
	SUM([EARNED_INCOME])	AS [EARNED_INCOME],
	SUM([TO_PAY])		AS [YET_TO_GO_XD],
	SUM([NET_INCOME])	AS [NET_INCOME],
	SUM([P.P.U])		AS [P.P.U]
FROM "CADIS"."VW_UI_FND_QUARTERLY_INCOME"
GROUP BY 
	[VALUATION_DATE],
	[FUND_SHORT_NAME],
	[FUND_FISCAL_YEAR]
