CREATE VIEW "CADIS"."VW_UI_FND_QUARTERLY_INCOME"
AS
WITH FundQuarterlyIncome AS
(
	SELECT 
		[POSITION_DATE],
		[FUND_SHORT_NAME],
		[FUND_FISCAL_YEAR],
		[FUND_FISCAL_QUARTER],
		CASE 
			WHEN [FUND_FISCAL_QUARTER] = 1
			THEN [Q1_EARNED_INCOME] 
			WHEN [FUND_FISCAL_QUARTER] = 2
			THEN [Q2_EARNED_INCOME] 
			WHEN [FUND_FISCAL_QUARTER] = 3
			THEN [Q3_EARNED_INCOME] 
			WHEN [FUND_FISCAL_QUARTER] = 4
			THEN [Q4_EARNED_INCOME] 
			ELSE 0 
		END						AS [EARNED_INCOME],
		CASE
			WHEN [FUND_FISCAL_QUARTER] = 1
			THEN [Q1_TO_PAY]
			WHEN [FUND_FISCAL_QUARTER] = 2
			THEN [Q2_TO_PAY]
			WHEN [FUND_FISCAL_QUARTER] = 3
			THEN [Q3_TO_PAY]
			WHEN [FUND_FISCAL_QUARTER] = 4
			THEN [Q4_TO_PAY]
			ELSE 0
		END						AS [TO_PAY]
	FROM
	(
		SELECT 
			[POSITION_DATE],
			[FUND_SHORT_NAME],
			[FUND_FISCAL_YEAR],
			ISNULL(SUM([Q1_EARNED_INCOME]),0)	AS [Q1_EARNED_INCOME],
			ISNULL(SUM([Q1_TO_PAY]),0)		AS [Q1_TO_PAY],
			ISNULL(SUM([Q2_EARNED_INCOME]),0)	AS [Q2_EARNED_INCOME],
			ISNULL(SUM([Q2_TO_PAY]),0)		AS [Q2_TO_PAY],
			ISNULL(SUM([Q3_EARNED_INCOME]),0)	AS [Q3_EARNED_INCOME],
			ISNULL(SUM([Q3_TO_PAY]),0)		AS [Q3_TO_PAY],
			ISNULL(SUM([Q4_EARNED_INCOME]),0)	AS [Q4_EARNED_INCOME],
			ISNULL(SUM([Q4_TO_PAY]),0)		AS [Q4_TO_PAY]
		FROM "dbo"."T_MASTER_SEC_INCOME"
		GROUP BY [POSITION_DATE],[FUND_SHORT_NAME],[FUND_FISCAL_YEAR]
	) A CROSS APPLY 
	(
		SELECT 1 AS [FUND_FISCAL_QUARTER]
		UNION
		SELECT 2 AS [FUND_FISCAL_QUARTER]
		UNION
		SELECT 3 AS [FUND_FISCAL_QUARTER]
		UNION
		SELECT 4 AS [FUND_FISCAL_QUARTER]
	) Q
)
SELECT
	MFI.[VALUATION_DATE],
	FQI.[FUND_SHORT_NAME],
	FQI.[FUND_FISCAL_YEAR],
	FQI.[FUND_FISCAL_QUARTER],
	MFI.[UNITS]						AS [UNITS_IN_ISSUE],
	FQI.[EARNED_INCOME],
	FQI.[TO_PAY],
	FQI.[EARNED_INCOME] + FQI.[TO_PAY]			AS [NET_INCOME],
	(FQI.[EARNED_INCOME] + FQI.[TO_PAY]) /
		MFI.[UNITS] * 100				AS [P.P.U]
FROM FundQuarterlyIncome FQI
	INNER JOIN "dbo"."T_MASTER_FND_INCOME" MFI 
	ON FQI.[FUND_SHORT_NAME] = MFI.[FUND_SHORT_NAME]
		AND FQI.[POSITION_DATE] = MFI.[VALUATION_DATE]
