CREATE VIEW "CADIS"."VW_UI_SHARECLASS_INCOME_QUARTERLY"
AS
WITH ShareClass AS 
(
	SELECT
		F.[SHORT_NAME],
		DATEPART(YEAR,DATEADD(
			QUARTER,
			ISNULL(F.[INCOME_PERIOD_QUARTER_OFFSET] ,0),
			SCV.[VALUATION_DATE]  
		))			AS [FUND_FISCAL_YEAR],
		SC.[SHARECLASS],				
		SCV.[UNITS_IN_ISSUE],
		SCV.[FUND_VALUE]
	FROM "dbo"."T_MASTER_SHARECLASS_VALUATION" SCV
		INNER JOIN "dbo"."T_MASTER_SHARECLASS" SC ON SCV.[EDM_SHARECLASS_ID] = SC.[EDM_SHARECLASS_ID]
		INNER JOIN "dbo"."T_MASTER_FND" F ON SC.[FUND_SHORT_NAME] = F.[SHORT_NAME]
),
Total AS 
(
	SELECT
		[SHORT_NAME],
		[FUND_FISCAL_YEAR],
		SUM([UNITS_IN_ISSUE])	AS [UNITS_IN_ISSUE],
		SUM([FUND_VALUE])	AS [FUND_VALUE]
	FROM ShareClass
	GROUP BY [SHORT_NAME], [FUND_FISCAL_YEAR]
),
FundQuarterly AS
(
	SELECT 
		[FUND_SHORT_NAME],
		[FUND_FISCAL_YEAR],
		MAX([I1])		AS [Q1_NET_INCOME],
		MAX([I2])		AS [Q2_NET_INCOME],
		MAX([I3])		AS [Q3_NET_INCOME],
		MAX([I4])		AS [Q4_NET_INCOME]
	FROM (
		SELECT
			[FUND_SHORT_NAME],
			[FUND_FISCAL_YEAR],
			[NET_INCOME],
			'I' + CAST([FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_NET_INCOME]
		FROM "CADIS"."VW_UI_FND_INCOME_QUARTERLY"
	) UNP
	PIVOT (MAX([NET_INCOME]) FOR [QUARTER_NET_INCOME] IN ([I1],[I2],[I3],[I4])) AS [INC]
	GROUP BY [FUND_SHORT_NAME],[FUND_FISCAL_YEAR]
),
ShareClassQuarterlyNetIncome AS
(
SELECT
	SC.*,
	T.[UNITS_IN_ISSUE]	AS [TOTAL_UNITS_IN_ISSUE],
	T.[FUND_VALUE]		AS [TOTAL_FUND_VALUE],
	FIQ.[Q1_NET_INCOME] / T.[FUND_VALUE] * SC.[FUND_VALUE]	AS [Q1_SHARE_CLASS_NET_INCOME],
	FIQ.[Q2_NET_INCOME] / T.[FUND_VALUE] * SC.[FUND_VALUE]	AS [Q2_SHARE_CLASS_NET_INCOME],
	FIQ.[Q3_NET_INCOME] / T.[FUND_VALUE] * SC.[FUND_VALUE]	AS [Q3_SHARE_CLASS_NET_INCOME],
	FIQ.[Q4_NET_INCOME] / T.[FUND_VALUE] * SC.[FUND_VALUE]	AS [Q4_SHARE_CLASS_NET_INCOME]
FROM ShareClass SC
	INNER JOIN Total T
	ON SC.[SHORT_NAME] = T.[SHORT_NAME]
		AND SC.[FUND_FISCAL_YEAR] = T.[FUND_FISCAL_YEAR]
	INNER JOIN FundQuarterly FIQ
	ON SC.[SHORT_NAME] = FIQ.[FUND_SHORT_NAME]
		AND SC.[FUND_FISCAL_YEAR] = FIQ.[FUND_FISCAL_YEAR]
)
SELECT 
	[SHORT_NAME]						AS [FUND_SHORT_NAME],
	[SHARECLASS]						AS [SHARE_CLASS_NAME],
	[FUND_FISCAL_YEAR],
	[UNITS_IN_ISSUE],
	[FUND_VALUE],
	[Q1_SHARE_CLASS_NET_INCOME],
	[Q1_SHARE_CLASS_NET_INCOME] / [UNITS_IN_ISSUE]		AS [Q1_SHARE_CLASS_RATE],
	[Q2_SHARE_CLASS_NET_INCOME],
	[Q2_SHARE_CLASS_NET_INCOME] / [UNITS_IN_ISSUE]		AS [Q2_SHARE_CLASS_RATE],
	[Q3_SHARE_CLASS_NET_INCOME],
	[Q3_SHARE_CLASS_NET_INCOME] / [UNITS_IN_ISSUE]		AS [Q3_SHARE_CLASS_RATE],
	[Q4_SHARE_CLASS_NET_INCOME],
	[Q4_SHARE_CLASS_NET_INCOME] / [UNITS_IN_ISSUE]		AS [Q4_SHARE_CLASS_RATE]
FROM ShareClassQuarterlyNetIncome
