CREATE VIEW "CADIS"."VW_UI_SHARECLASS_ANNUAL_INCOME"
AS
SELECT
	[VALUATION_DATE],
	[FUND_SHORT_NAME],
	[SHARE_CLASS_NAME],
	[FUND_FISCAL_YEAR],
	MAX([UNITS_IN_ISSUE])				AS [UNITS_IN_ISSUE],
	MAX([FUND_VALUE])				AS [FUND_VALUE],
	MAX([Q1_SHARE_CLASS_NET_INCOME]) +
		MAX([Q2_SHARE_CLASS_NET_INCOME]) +
		MAX([Q3_SHARE_CLASS_NET_INCOME]) +
		MAX([Q4_SHARE_CLASS_NET_INCOME])	AS [SHARE_CLASS_NET_INCOME],
	MAX([Q1_SHARE_CLASS_RATE]) +
		MAX([Q2_SHARE_CLASS_RATE]) +
		MAX([Q3_SHARE_CLASS_RATE]) +
		MAX([Q4_SHARE_CLASS_RATE])		AS [SHARE_CLASS_RATE] 
FROM "CADIS"."VW_UI_SHARECLASS_QUARTERLY_INCOME"
GROUP BY 
	[VALUATION_DATE],
	[FUND_SHORT_NAME],
	[SHARE_CLASS_NAME],
	[FUND_FISCAL_YEAR]
