Create View CADIS.vwProcessHistory
--WITH ENCRYPTION--cadisbuild
As
/*
	Show details from the co_processhistory table, including component types and names
*/
Select H.*, PROCESSTYPE = c.description, PROCESSNAME = Coalesce (V.name, 'UNKNOWN'),
	RUNTIME=H.RUNEND-H.RUNSTART,
	LASTLOGENTRY=CASE WHEN H.RUNEND IS NULL THEN ISNULL(LR.LASTLOGENTRY, H.RUNSTART) ELSE NULL END,
	TIMESINCELASTENTRY=CASE WHEN H.RUNEND IS NULL THEN GetDate()-ISNULL(LR.LASTLOGENTRY, H.RUNSTART) ELSE NULL END,
	RUNCOMPLETE = CONVERT(bit, CASE WHEN H.RUNEND IS NULL THEN 0 ELSE 1 END)
From cadis_sys.CO_PROCESSHISTORY H
JOIN CADIS_SYS.CO_COMPONENT C On C.ID=H.ComponentID
Left Join CADIS_SYS.VW_ALL_PROCESSES V On V.ComponentID=H.ComponentID AND V.Guid=H.Guid
Left Join (SELECT RUNID, LASTLOGENTRY=MAX(LogTime) FROM cadis_sys.CO_PROCESSLOG GROUP BY RUNID) LR On LR.RUNID = H.RUNID
