CREATE VIEW CADIS.vwServiceProcess
AS
SELECT CASE L.COMPONENTID WHEN 26 THEN 'SilverlightHost' WHEN 27 THEN 'ServiceHost' WHEN 28 THEN 'WebServiceHost' ELSE A.COMPONENT_NAME END AS COMPONENT_NAME,
	A.NAME AS PROCESS_NAME,
	L.MACHINENAME,
	L.INSTANCE AS SERVICE_INSTANCE,
	MAX(L.LOGTIME) AS LAST_LOG_TIME
FROM [CADIS_SYS].[PR_SERVICELOG] L
LEFT JOIN CADIS_SYS.VW_ALL_PROCESSES A ON A.COMPONENTID=L.COMPONENTID AND A.GUID=L.GUID AND A.OBSOLETE = 0
GROUP BY L.COMPONENTID, L.GUID, L.MACHINENAME, L.INSTANCE, A.COMPONENT_NAME, A.NAME
