CREATE VIEW CADIS.vwServiceLog
AS
SELECT CASE L.COMPONENTID WHEN 26 THEN 'SilverlightHost' WHEN 27 THEN 'ServiceHost' WHEN 28 THEN 'WebServiceHost' ELSE A.COMPONENT_NAME END AS COMPONENT_NAME,
	A.NAME AS PROCESS_NAME,
	L.LOGTIME,
	-- System.Diagnostics.EventLogEntryType
	CASE L.MESSAGETYPE WHEN 1 THEN 'Error' WHEN 2 THEN 'Warning' WHEN 4 THEN 'Information' ELSE 'Unknown' END AS MESSAGE_TYPE,
	L.HEADER,
	L.MESSAGE,
	L.MACHINENAME,
	L.INSTANCE AS SERVICE_INSTANCE,
	L.USERNAME,
	L.LOGID -- Otherwise can't page in the DG
FROM [CADIS_SYS].[PR_SERVICELOG] L
LEFT JOIN CADIS_SYS.VW_ALL_PROCESSES A ON A.COMPONENTID=L.COMPONENTID AND A.GUID=L.GUID AND A.OBSOLETE = 0
