CREATE FUNCTION "CADIS"."IL_overdraft" (

)
RETURNS TABLE AS RETURN (
SELECT V."FUND_SHORT_NAME",V."OVERDRAFTDAYS120",V."DAYSTILLBREACH120",V."BREACHDATE120",V."OVERDRAFTDAYS180",V."DAYSTILLBREACH180",V."BREACHDATE180",V."OVERDRAFTDAYS360",V."DAYSTILLBREACH360",V."BREACHDATE360",V."LAST_UPDATED" FROM "Access.WebDev"."ufn_GetOverdraftDaysAndProjectedBreachDates"() V
)
