CREATE FUNCTION "CADIS"."Master_Income_by_Quarter"
(
	
)
RETURNS TABLE
AS
RETURN
(
SELECT 
	[FUND_SHORT_NAME],
	[EDM_SEC_ID],
	[FUND_FISCAL_YEAR],
	MAX([DVD_CCY])			AS [DVD_CCY],
	MAX([WITHHOLDING_TAX])		AS [WITHHOLDING_TAX],
	MAX([DECLARED_DATE])		AS [DECLARED_DATE],
	MAX([POSITION_DATE])		AS [POSITION_DATE],
	MAX([POSITION])			AS [POSITION],
	MAX([BID_PRICE])		AS [BID_PRICE],
	MAX([SPOT_RATE])		AS [SPOT_RATE],
	MAX([MARKET_VALUE])		AS [MARKET_VALUE],
	MAX([D1])			AS [Q1_EX_DATE],
	MAX([R1])			AS [Q1_RATE],
	MAX([A1])			AS [Q1_ACCRUED_INCOME],
	MAX([C1])			AS [Q1_INCOME_CALCULATED],
	MAX([P1])			AS [Q1_TO_PAY],
	MAX([N1])			AS [Q1_NOTES],
	MAX([D2])			AS [Q2_EX_DATE],
	MAX([R2])			AS [Q2_RATE],
	MAX([A2])			AS [Q2_ACCRUED_INCOME],
	MAX([C2])			AS [Q2_INCOME_CALCULATED],
	MAX([P2])			AS [Q2_TO_PAY],
	MAX([N2])			AS [Q2_NOTES],
	MAX([D3])			AS [Q3_EX_DATE],
	MAX([R3])			AS [Q3_RATE],
	MAX([A3])			AS [Q3_ACCRUED_INCOME],
	MAX([C3])			AS [Q3_INCOME_CALCULATED],
	MAX([P3])			AS [Q3_TO_PAY],
	MAX([N3])			AS [Q3_NOTES],
	MAX([D4])			AS [Q4_EX_DATE],
	MAX([R4])			AS [Q4_RATE],
	MAX([A4])			AS [Q4_ACCRUED_INCOME],
	MAX([C4])			AS [Q4_INCOME_CALCULATED],
	MAX([P4])			AS [Q4_TO_PAY],
	MAX([N4])			AS [Q4_NOTES]
FROM (
	SELECT
		UNP.*,
		'D' + CAST(UNP.[FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_EX_DATE],
		'R' + CAST(UNP.[FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_RATE],
		'A' + CAST(UNP.[FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_ACCRUED_INCOME],
		'C' + CAST(UNP.[FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_INCOME_CALCULATED],
		'P' + CAST(UNP.[FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_TO_PAY],
		'N' + CAST(UNP.[FUND_FISCAL_QUARTER] AS VARCHAR)	AS [QUARTER_NOTES]
	FROM "dbo"."T_MASTER_INCOME" AS UNP
) AS DVD
PIVOT (MAX([EX_DATE]) FOR [QUARTER_EX_DATE] IN ([D1],[D2],[D3],[D4])) AS DAT
PIVOT (MAX([RATE]) FOR [QUARTER_RATE] IN ([R1],[R2],[R3],[R4])) AS RAT
PIVOT (MAX([ACCRUED_INCOME]) FOR [QUARTER_ACCRUED_INCOME] IN ([A1],[A2],[A3],[A4])) AS INC
PIVOT (MAX([INCOME_CALCULATED]) FOR [QUARTER_INCOME_CALCULATED] IN ([C1],[C2],[C3],[C4])) AS INC
PIVOT (MAX([TO_PAY]) FOR [QUARTER_TO_PAY] IN ([P1],[P2],[P3],[P4])) AS PAY
PIVOT (MAX([NOTES]) FOR [QUARTER_NOTES] IN ([N1],[N2],[N3],[N4])) AS [NOT]
GROUP BY [FUND_SHORT_NAME],[EDM_SEC_ID],[FUND_FISCAL_YEAR]
)
