CREATE TABLE [Trading].[AccountPositions] (
    [AccountPositionId]               INT             IDENTITY (1, 1) NOT NULL,
    [TicketNumber]                    INT             NULL,
    [TradeDate]                       DATE            NOT NULL,
    [SecurityIdentifierFlag]          INT             NOT NULL,
    [SecurityIdentifier]              VARCHAR (25)    NULL,
    [SettlementDate]                  DATE            NULL,
    [ISLong]                          BIT             CONSTRAINT [DF_AP_IL] DEFAULT ((1)) NOT NULL,
    [Position]                        DECIMAL (19, 5) NULL,
    [AccountName]                     VARCHAR (25)    NULL,
    [Price]                           DECIMAL (19, 9) NULL,
    [ExchangeCode]                    INT             NULL,
    [ProductCode]                     INT             NULL,
    [BradyStyleFactor]                INT             NULL,
    [UniqueBloombergID]               VARCHAR (25)    NULL,
    [FXForwardPoints]                 INT             NULL,
    [SwapPay_ReceiveFlag]             VARCHAR (25)    NULL,
    [SwapFee]                         DECIMAL (19, 5) NULL,
    [PayNotionalAmount]               DECIMAL (19, 5) NULL,
    [ReceiveNotionalAmount]           DECIMAL (19, 5) NULL,
    [FXAverageCost]                   DECIMAL (19, 8) NULL,
    [ISShort]                         BIT             CONSTRAINT [DF_AP_IS] DEFAULT ((0)) NOT NULL,
    [ISCFD]                           BIT             CONSTRAINT [DF_AP_ICFD] DEFAULT ((0)) NOT NULL,
    [PrimeBroker]                     VARCHAR (25)    NULL,
    [StrategyName]                    VARCHAR (128)   NULL,
    [AccountPositionCreatedDatetime]  DATETIME        CONSTRAINT [DF_AP_APCDT] DEFAULT (getdate()) NOT NULL,
    [AccountPositionModifiedDatetime] DATETIME        CONSTRAINT [DF_AP_APMDT] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PKAccountPositions] PRIMARY KEY CLUSTERED ([AccountPositionId] ASC)
);

