CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION272_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @KPIBreachId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @KPIValue DECIMAL (19, 5), @KPIValue_UPDATE BIT, @ThresholdValue DECIMAL (19, 5), @ThresholdValue_UPDATE BIT, @RAGName VARCHAR (10), @RAGName_UPDATE BIT, @BreachDate DATETIME, @BreachDate_UPDATE BIT, @FollowUpAction VARCHAR (MAX), @FollowUpAction_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @KPIBreachLastModifiedDatetime DATETIME, @KPIBreachLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


