CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION38_INBOXDEL]
@KPIId SMALLINT, @KPIGroupId SMALLINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


