CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION268_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @RiskReturnId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @RiskOwnerRoleId SMALLINT, @RiskOwnerRoleId_UPDATE BIT, @JiraKey VARCHAR (128), @JiraKey_UPDATE BIT, @CreatedForPersonId SMALLINT, @CreatedForPersonId_UPDATE BIT, @DueDate DATETIME, @DueDate_UPDATE BIT, @CompletionDate DATETIME, @CompletionDate_UPDATE BIT, @CompletedByPersonId SMALLINT, @CompletedByPersonId_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @RiskRAG VARCHAR (10), @RiskRAG_UPDATE BIT, @RiskRAGRationale VARCHAR (MAX), @RiskRAGRationale_UPDATE BIT, @ManagementActivities VARCHAR (MAX), @ManagementActivities_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @RiskReturnLastModifiedDatetime DATETIME, @RiskReturnLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


