CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION317_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CommentaryDate DATETIME, @CommentaryDate_UPDATE BIT, @WEIFCOD DECIMAL (19, 5), @WEIFCOD_UPDATE BIT, @BenchMarkCOD DECIMAL (19, 5), @BenchMarkCOD_UPDATE BIT, @WPCTCOD DECIMAL (19, 5), @WPCTCOD_UPDATE BIT, @WIMIFFCOD DECIMAL (19, 5), @WIMIFFCOD_UPDATE BIT, @WIMIFFBenchmarkCOD DECIMAL (19, 5), @WIMIFFBenchmarkCOD_UPDATE BIT, @SharePriceClose DECIMAL (19, 5), @SharePriceClose_UPDATE BIT, @NAVClose DECIMAL (19, 5), @NAVClose_UPDATE BIT, @Commentary NVARCHAR (MAX), @Commentary_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @CommentaryType NVARCHAR (24), @CommentaryType_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


