CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION31_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @MeasureDateId INT, @MeasureDateId_UPDATE BIT, @KPIId SMALLINT, @KPIId_UPDATE BIT, @MeasureValue DECIMAL (19, 5), @MeasureValue_UPDATE BIT, @ControlId BIGINT, @ControlId_UPDATE BIT, @SourceSystemId SMALLINT, @SourceSystemId_UPDATE BIT, @RecordedBy NVARCHAR (128), @RecordedBy_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


