CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION355_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @PAHoldingsRequestId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @RequestDetails VARCHAR (MAX), @RequestDetails_UPDATE BIT, @OwnerId SMALLINT, @OwnerId_UPDATE BIT, @ReviewerId SMALLINT, @ReviewerId_UPDATE BIT, @Status VARCHAR (128), @Status_UPDATE BIT, @BoxFolderId VARCHAR (25), @BoxFolderId_UPDATE BIT, @JIRAIssueKey VARCHAR (255), @JIRAIssueKey_UPDATE BIT, @Active BIT, @Active_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @PAHoldingsRequestLastModifiedDatetime DATETIME, @PAHoldingsRequestLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


