CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION255_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @SignatoryOwnerId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ProcDocumentId INT, @ProcDocumentId_UPDATE BIT, @PolicyId INT, @PolicyId_UPDATE BIT, @RoleId SMALLINT, @RoleId_UPDATE BIT, @PersonId SMALLINT, @PersonId_UPDATE BIT, @IsOwner BIT, @IsOwner_UPDATE BIT, @IsSignatory BIT, @IsSignatory_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @SignatoryOwnerLastModifiedDatetime DATETIME, @SignatoryOwnerLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


