CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION353_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @PAAccountRegisterId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @AccountName VARCHAR (255), @AccountName_UPDATE BIT, @AccountNumber VARCHAR (255), @AccountNumber_UPDATE BIT, @Entity VARCHAR (255), @Entity_UPDATE BIT, @OwnerId SMALLINT, @OwnerId_UPDATE BIT, @Active BIT, @Active_UPDATE BIT, @InActiveDate DATETIME, @InActiveDate_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @PAAccountLastModifiedDatetime DATETIME, @PAAccountLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


