CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION282_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @MandateName VARCHAR (255), @MandateName_UPDATE BIT, @Status VARCHAR (255), @Status_UPDATE BIT, @ShareClass VARCHAR (255), @ShareClass_UPDATE BIT, @CommissionRate VARCHAR (255), @CommissionRate_UPDATE BIT, @RegulatorName VARCHAR (255), @RegulatorName_UPDATE BIT, @RegulatorNumber VARCHAR (255), @RegulatorNumber_UPDATE BIT, @Decision VARCHAR (255), @Decision_UPDATE BIT, @ReviewedByPersonId SMALLINT, @ReviewedByPersonId_UPDATE BIT, @ReviewedDate DATE, @ReviewedDate_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


