CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION328_INBOXSELROWNUMBER]
@PositionDate DATE, @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @POSITION_DATE DATE, @EDM_SEC_ID BIGINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


