CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION38_AUDITLATESTCHANGE]
@KPIId SMALLINT, @KPIGroupId SMALLINT, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


