CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION296_INBOXSELSINGLEROW]
@AccountId NVARCHAR (1000), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


