CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION38_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @KPIId SMALLINT, @KPIGroupId SMALLINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


