CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION354_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @SecurityName VARCHAR (255), @SecurityName_UPDATE BIT, @SecurityType VARCHAR (255), @SecurityType_UPDATE BIT, @SecurityIdentifier VARCHAR (255), @SecurityIdentifier_UPDATE BIT, @OwnerId SMALLINT, @OwnerId_UPDATE BIT, @Active BIT, @Active_UPDATE BIT, @InActiveDate DATETIME, @InActiveDate_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @PAHoldingLastModifiedDatetime DATETIME, @PAHoldingLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


