CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION328_INBOXSELSINGLEROW]
@PositionDate DATE, @POSITION_DATE DATE, @EDM_SEC_ID BIGINT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


