CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION276_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @ChangeID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @ChangeManagementRegisterLastModifiedDatetime DATETIME, @ChangeManagementRegisterLastModifiedDatetime_UPDATE BIT, @ServiceTypeID SMALLINT, @ServiceTypeID_UPDATE BIT, @StatusID SMALLINT, @StatusID_UPDATE BIT, @ChangeTitle NVARCHAR (MAX), @ChangeTitle_UPDATE BIT, @PriorityID SMALLINT, @PriorityID_UPDATE BIT, @UrgencyID SMALLINT, @UrgencyID_UPDATE BIT, @DueLiveDate DATETIME, @DueLiveDate_UPDATE BIT, @PlanDueDate DATETIME, @PlanDueDate_UPDATE BIT, @ChangeTypeID SMALLINT, @ChangeTypeID_UPDATE BIT, @Description NVARCHAR (MAX), @Description_UPDATE BIT, @ReasonJustification NVARCHAR (MAX), @ReasonJustification_UPDATE BIT, @ImpactID SMALLINT, @ImpactID_UPDATE BIT, @ImpactDesc NVARCHAR (MAX), @ImpactDesc_UPDATE BIT, @ComplexityID SMALLINT, @ComplexityID_UPDATE BIT, @RiskID SMALLINT, @RiskID_UPDATE BIT, @EstimatedHoursRequired INT, @EstimatedHoursRequired_UPDATE BIT, @BuildInstruction NVARCHAR (MAX), @BuildInstruction_UPDATE BIT, @ProgressNote NVARCHAR (MAX), @ProgressNote_UPDATE BIT, @IsBuildComplete BIT, @IsBuildComplete_UPDATE BIT, @TesterPersonID SMALLINT, @TesterPersonID_UPDATE BIT, @JIRAIssueKey NVARCHAR (255), @JIRAIssueKey_UPDATE BIT, @IsDocumentationProvided BIT, @IsDocumentationProvided_UPDATE BIT, @AttachmentsFolder NVARCHAR (MAX), @AttachmentsFolder_UPDATE BIT, @IsChangeReady BIT, @IsChangeReady_UPDATE BIT, @CreatedDate DATETIME, @CreatedDate_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @TestCompleteDueDate DATETIME, @TestCompleteDueDate_UPDATE BIT, @TestPlan NVARCHAR (MAX), @TestPlan_UPDATE BIT, @TestingComplete BIT, @TestingComplete_UPDATE BIT, @PlanApproverPersonID SMALLINT, @PlanApproverPersonID_UPDATE BIT, @DeploymentApproverPersonID SMALLINT, @DeploymentApproverPersonID_UPDATE BIT, @ComplexityDesc NVARCHAR (MAX), @ComplexityDesc_UPDATE BIT, @RiskDesc NVARCHAR (MAX), @RiskDesc_UPDATE BIT, @IncidentId NVARCHAR (255), @IncidentId_UPDATE BIT, @IncidentTitle NVARCHAR (255), @IncidentTitle_UPDATE BIT, @Backout NVARCHAR (255), @Backout_UPDATE BIT, @RuleID NVARCHAR (8), @RuleID_UPDATE BIT, @RuleDescription VARCHAR (MAX), @RuleDescription_UPDATE BIT, @DashboardUpdate BIT, @DashboardUpdate_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


