CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION257_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @AccName NVARCHAR (100), @AccPostcode NVARCHAR (20), @AccFcaId INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


