CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION269_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @SubCategoryId SMALLINT, @SubCategoryId_UPDATE BIT, @RMFStatus VARCHAR (128), @RMFStatus_UPDATE BIT, @RMFStatusRationale VARCHAR (MAX), @RMFStatusRationale_UPDATE BIT, @ManagementActivities VARCHAR (MAX), @ManagementActivities_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @SubmittedDate DATETIME, @SubmittedDate_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @RMFReviewLastModifiedDatetime DATETIME, @RMFReviewLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


