CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION303_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CntFcaId CHAR (8), @CntFcaId_UPDATE BIT, @CntSalesforceId CHAR (18), @CntSalesforceId_UPDATE BIT, @CntMatrixId CHAR (5), @CntMatrixId_UPDATE BIT, @CntSivId NVARCHAR (100), @CntSivId_UPDATE BIT, @CntSalutation NVARCHAR (100), @CntSalutation_UPDATE BIT, @CntFirstName NVARCHAR (100), @CntFirstName_UPDATE BIT, @CntLastName NVARCHAR (100), @CntLastName_UPDATE BIT, @CntJobTitle NVARCHAR (100), @CntJobTitle_UPDATE BIT, @CntLandline NVARCHAR (100), @CntLandline_UPDATE BIT, @CntMobile NVARCHAR (100), @CntMobile_UPDATE BIT, @CntFax NVARCHAR (100), @CntFax_UPDATE BIT, @CntEmail NVARCHAR (100), @CntEmail_UPDATE BIT, @CntIsCf1 BIT, @CntIsCf1_UPDATE BIT, @CntIsCf2 BIT, @CntIsCf2_UPDATE BIT, @CntIsCf3 BIT, @CntIsCf3_UPDATE BIT, @CntIsCf4 BIT, @CntIsCf4_UPDATE BIT, @CntIsCf10 BIT, @CntIsCf10_UPDATE BIT, @CntIsCf11 BIT, @CntIsCf11_UPDATE BIT, @CntIsCf30 BIT, @CntIsCf30_UPDATE BIT, @WoodfordLastUpdate DATETIME, @WoodfordLastUpdate_UPDATE BIT, @MatrixLastUpdate DATETIME, @MatrixLastUpdate_UPDATE BIT, @IsConfirmRequired BIT, @IsConfirmRequired_UPDATE BIT, @IsReviewed BIT, @IsReviewed_UPDATE BIT, @StartDateTime DATETIME, @StartDateTime_UPDATE BIT, @EndDateTime DATETIME, @EndDateTime_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @ModifiedByPersonId SMALLINT, @ModifiedByPersonId_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


