CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION324_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @InvestmentOpsDailyTasksRegisterId INT, @InvestmentOpsDailyTasksRegisterId_UPDATE BIT, @InvestmentOpsEventDate DATETIME, @InvestmentOpsEventDate_UPDATE BIT, @InvestmentOpsEventStatus VARCHAR (10), @InvestmentOpsEventStatus_UPDATE BIT, @JIRAIssueKey VARCHAR (128), @JIRAIssueKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


