CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION380_INBOXSELSINGLEROW]
@SHORT_NAME VARCHAR (20), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


