CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION274_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @ApproverID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @ServiceID SMALLINT, @ServiceID_UPDATE BIT, @ApprovalTypeID SMALLINT, @ApprovalTypeID_UPDATE BIT, @ApproverPersonID SMALLINT, @ApproverPersonID_UPDATE BIT, @ChangeManagementRegisterLastModifiedDatetime DATETIME, @ChangeManagementRegisterLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


