CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION387_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (256), @IN_FLOW_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


