CREATE TABLE [PolicyProc].[Events] (
    [EventId]                   INT              IDENTITY (1, 1) NOT NULL,
    [PolicyId]                  INT              NULL,
    [ProcDocumentId]            INT              NULL,
    [EventTypeId]               SMALLINT         NOT NULL,
    [SubmittedByPersonId]       SMALLINT         CONSTRAINT [DF_EVT_SP] DEFAULT ((-1)) NOT NULL,
    [EventDetails]              VARCHAR (MAX)    NULL,
    [EventDate]                 DATETIME         NULL,
    [EventStatus]               VARCHAR (25)     NULL,
    [EventTrueFalse]            BIT              NULL,
    [JiraTaskKey]               VARCHAR (128)    NULL,
    [IsLegalStatusChange]       BIT              NULL,
    [IsRebrand]                 BIT              NULL,
    [IsContentChange]           BIT              NULL,
    [BoxFileId]                 VARCHAR (255)    NULL,
    [BoxFilename]               VARCHAR (255)    NULL,
    [DocumentationFolderLink]   VARCHAR (2000)   NULL,
    [JoinGUID]                  UNIQUEIDENTIFIER NOT NULL,
    [EventCreationDatetime]     DATETIME         CONSTRAINT [DF_EVT_EVTCDT] DEFAULT (getdate()) NOT NULL,
    [EventLastModifiedDatetime] DATETIME         CONSTRAINT [DF_EVT_EVTLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME         CONSTRAINT [DF_EVT_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME         CONSTRAINT [DF_EVT_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)    CONSTRAINT [DF_EVT_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT              CONSTRAINT [DF_EVT_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME         CONSTRAINT [DF_EVT_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKEvents] PRIMARY KEY CLUSTERED ([EventId] ASC),
    CONSTRAINT [EventsEventTypeId] FOREIGN KEY ([EventTypeId]) REFERENCES [PolicyProc].[EventTypes] ([EventTypeId]),
    CONSTRAINT [EventsPolicyId] FOREIGN KEY ([PolicyId]) REFERENCES [PolicyProc].[PolicyRegister] ([PolicyId]),
    CONSTRAINT [EventsProcDocumentId] FOREIGN KEY ([ProcDocumentId]) REFERENCES [PolicyProc].[ProceduresDocument] ([ProcDocumentId]),
    CONSTRAINT [EventsSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

