CREATE TABLE [Sales.BP].[MxAccount_bak] (
    [SfAccountId]                   VARCHAR (18)    NULL,
    [AccountName]                   NVARCHAR (1000) NULL,
    [FcaId]                         VARCHAR (100)   NOT NULL,
    [MatrixOutletId]                VARCHAR (50)    NOT NULL,
    [OutletType]                    VARCHAR (100)   NULL,
    [AccountSivId]                  VARCHAR (100)   NULL,
    [ParentAccountSivId]            VARCHAR (100)   NULL,
    [AccountOwnerId]                VARCHAR (18)    NULL,
    [AccountOwnerName]              VARCHAR (100)   NULL,
    [Phone]                         VARCHAR (50)    NULL,
    [Fax]                           VARCHAR (50)    NULL,
    [Website]                       VARCHAR (128)   NULL,
    [EmailAddress]                  VARCHAR (128)   NULL,
    [IsPriorityClient]              BIT             NOT NULL,
    [FirmSegment]                   VARCHAR (100)   NULL,
    [PlatformsUsed]                 VARCHAR (1000)  NULL,
    [AuthStatus]                    VARCHAR (100)   NULL,
    [BillingStreet]                 NVARCHAR (1000) NULL,
    [BillingCity]                   NVARCHAR (100)  NULL,
    [BillingState]                  NVARCHAR (100)  NULL,
    [BillingPostcode]               NVARCHAR (100)  NOT NULL,
    [BillingCountry]                NVARCHAR (100)  NULL,
    [VerifiedBy]                    NVARCHAR (100)  NULL,
    [IsExistingCompanyRelationship] BIT             NOT NULL,
    [ModifiedBy]                    VARCHAR (100)   NOT NULL,
    [LastModifiedDatetime]          DATETIME        NOT NULL,
    [IsActive]                      BIT             NOT NULL,
    [StartDatetime]                 DATETIME        NOT NULL,
    [EndDatetime]                   DATETIME        NOT NULL,
    [WF_PRIMARY_BUSINESS]           VARCHAR (MAX)   NULL,
    [MX_PRIMARY_BUSINESS]           VARCHAR (MAX)   NULL
);

