CREATE TABLE [Sales.BP].[MxContact_bak] (
    [SfContactId]                   VARCHAR (18)    NULL,
    [SfAccountId]                   VARCHAR (18)    NULL,
    [LastName]                      NVARCHAR (100)  NULL,
    [FirstName]                     NVARCHAR (100)  NULL,
    [Salutation]                    VARCHAR (100)   NULL,
    [JobTitle]                      VARCHAR (100)   NULL,
    [FcaId]                         VARCHAR (100)   NOT NULL,
    [AccountFcaId]                  VARCHAR (100)   NOT NULL,
    [ContactOwnerId]                VARCHAR (18)    NULL,
    [ContactOwnerName]              VARCHAR (100)   NULL,
    [AccountSivId]                  VARCHAR (100)   NULL,
    [ContactSivId]                  VARCHAR (100)   NULL,
    [ContactMatrixId]               VARCHAR (100)   NULL,
    [MailingStreet]                 NVARCHAR (1000) NULL,
    [MailingCity]                   NVARCHAR (100)  NULL,
    [MailingState]                  NVARCHAR (100)  NULL,
    [MailingPostcode]               NVARCHAR (100)  NULL,
    [MailingCountry]                NVARCHAR (100)  NULL,
    [Phone]                         VARCHAR (50)    NULL,
    [Mobile]                        VARCHAR (50)    NULL,
    [Fax]                           VARCHAR (50)    NULL,
    [EmailAddress]                  VARCHAR (128)   NULL,
    [IsCf1]                         BIT             NOT NULL,
    [IsCf2]                         BIT             NOT NULL,
    [IsCf3]                         BIT             NOT NULL,
    [IsCf4]                         BIT             NOT NULL,
    [IsCf10]                        BIT             NOT NULL,
    [IsCf11]                        BIT             NOT NULL,
    [IsCf30]                        BIT             NOT NULL,
    [VerifiedBy]                    NVARCHAR (100)  NULL,
    [IsExistingCompanyRelationship] BIT             NOT NULL,
    [ModifiedBy]                    VARCHAR (100)   NOT NULL,
    [LastModifiedDatetime]          DATETIME        NOT NULL,
    [IsActive]                      BIT             NOT NULL,
    [StartDatetime]                 DATETIME        NOT NULL,
    [EndDatetime]                   DATETIME        NOT NULL
);

