
CREATE VIEW [Staging].[zzz_MatrixParentAccountUpdateVw]
AS

-- Unknown salesforce parents need to be loaded.
SELECT MX_MATRIX_ACCOUNT_SIV_ID         AS MX_ACCOUNT_SIV_ID,
       MX_MATRIX_OUTLET_ID              AS MATRIX_OUTLET_ID,
       MX_PARENT_ACCOUNT_SIV_ID         AS PARENT_ACCOUNT_SIV_ID,
       MX_OWNER_ID                      AS OWNER_ID,
       MX_OWNER_NAME                    AS OWNER_NAME,
       MX_NAME                          AS NAME,
       MX_OUTLET_TYPE                   AS OUTLET_TYPE,
       MX_BILLINGSTREET                 AS BILLING_STREET,
       MX_BILLINGCITY                   AS BILLING_CITY,
       MX_BILLINGSTATE                  AS BILLING_STATE,
       MX_POSTALCODE                    AS BILLING_POSTCODE,
       MX_COUNTRY                       AS BILLING_COUNTRY,
       MX_PHONE                         AS BILLING_PHONE,
       MX_FAX                           AS FAX,
       MX_WEBSITE                       AS WEBSITE,
       MX_FIRM_SEGMENT                  AS FIRM_SEGMENT,
       MX_PLATFORMS_USED                AS PLATFORMS_USED,
       MX_AUTHORISATION_STATUS          AS AUTHORISATION_STATUS,
       MX_PRIMARY_BUSINESS              AS PRIMARY_BUSINESS,
       MX_VERIFIED_BY                   AS VERIFIED_BY,
       MX_EXISTING_COMPANY_RELATIONSHIP AS EXISTING_COMPANY_RELATIONSHIP
FROM STAGING.T_MATRIX_ACCOUNT B
WHERE MX_MATRIX_ACCOUNT_SIV_ID IN (
     SELECT MX_PARENT_ACCOUNT_SIV_ID
     FROM STAGING.T_MATRIX_ACCOUNT A
     LEFT OUTER JOIN [STAGING.SALESFORCE.BP].[MXACCOUNTEXTRACT] AE
          ON A.MX_PARENT_ACCOUNT_SIV_ID = AE.ACCSIVID
     WHERE SALESFORCE_ACCOUNT_ID = ''
     AND IS_PROSPECT = 'Y'
     AND MX_PARENT_ACCOUNT_SIV_ID IS NOT NULL
     AND AE.ACCSALESFORCEID IS NULL
)
AND SALESFORCE_ACCOUNT_ID = ''