
CREATE VIEW [Staging].[zzz_MatrixContactUpdateVw]
AS

     SELECT MX.SALESFORCE_CONTACT_ID,
			MX.SALESFORCE_ACCOUNT_ID,
			MX.OWNER_ID,
			MX.OWNER_NAME,
			MX.ACCOUNT_SIV_ID,
			MX.CONTACT_SIV_ID,
			MX.MATRIX_CONTACT_ID,
			MX.SALUTATION,
			MX.FIRST_NAME,
			MX.LAST_NAME,
			MX.TITLE,
			MX.MAILING_STREET,
			MX.MAILING_CITY,
			MX.MAILING_STATE,
			MX.MAILING_POSTCODE,
			MX.MAILING_COUNTRY,
			MX.PHONE,
			MX.MOBILE_PHONE,
			MX.FAX,
			MX.EMAIL,
			MX.CONTACT_IS_CF1,
			MX.CONTACT_IS_CF2,
			MX.CONTACT_IS_CF3,
			MX.CONTACT_IS_CF4,
			MX.CONTACT_IS_CF10,
			MX.CONTACT_IS_CF11,
			MX.CONTACT_IS_CF30,
			MX.VERIFIED_BY
     FROM (
          SELECT SALESFORCE_CONTACT_ID AS SALESFORCE_CONTACT_ID,
				SALESFORCE_ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
				MX_OWNER_ID AS OWNER_ID,
				MX_OWNER_NAME AS OWNER_NAME,
				MX_ACCOUNT_SIV_ID AS ACCOUNT_SIV_ID,
				MX_CONTACT_SIV_ID AS CONTACT_SIV_ID,
				MX_MATRIX_CONTACT_ID AS MATRIX_CONTACT_ID,
				MX_SALUTATION AS SALUTATION,
				MX_FIRST_NAME AS FIRST_NAME,
				MX_LAST_NAME AS LAST_NAME,
				MX_TITLE AS TITLE,
				MX_MAILING_STREET AS MAILING_STREET,
				MX_MAILING_CITY AS MAILING_CITY,
				MX_MAILING_STATE AS MAILING_STATE,
				MX_MAILING_POSTCODE AS MAILING_POSTCODE,
				MX_MAILING_COUNTRY AS MAILING_COUNTRY,
				MX_PHONE AS PHONE,
				MX_MOBILE_PHONE AS MOBILE_PHONE,
				MX_FAX AS FAX,
				MX_EMAIL AS EMAIL,
				MX_CONTACT_IS_CF1 AS CONTACT_IS_CF1,
				MX_CONTACT_IS_CF2 AS CONTACT_IS_CF2,
				MX_CONTACT_IS_CF3 AS CONTACT_IS_CF3,
				MX_CONTACT_IS_CF4 AS CONTACT_IS_CF4,
				MX_CONTACT_IS_CF10 AS CONTACT_IS_CF10,
				MX_CONTACT_IS_CF11 AS CONTACT_IS_CF11,
				MX_CONTACT_IS_CF30 AS CONTACT_IS_CF30,
				MX_VERIFIED_BY AS VERIFIED_BY
          FROM STAGING.T_MATRIX_CONTACT
          WHERE (SALESFORCE_CONTACT_ID <> '' AND SALESFORCE_ACCOUNT_ID <> '')
     ) MX
     INNER JOIN (
          SELECT CntSalesforceId AS SALESFORCE_CONTACT_ID,
				CntAccountSalesforceId AS SALESFORCE_ACCOUNT_ID,
				CntOwnerId AS OWNER_ID,
				CntOwnerName AS OWNER_NAME,
				CntAccountSivId AS ACCOUNT_SIV_ID,
				CntSivId AS CONTACT_SIV_ID,
				CntMatrixId AS MATRIX_CONTACT_ID,
				CntSalutation AS SALUTATION,
				CntFirstName AS FIRST_NAME,
				CntLastName AS LAST_NAME,
				CntJobTitle AS TITLE,
				CntMailingStreet AS MAILING_STREET,
				CntMailingCity AS MAILING_CITY,
				CntMailingState AS MAILING_STATE,
				CntMailingPostcode AS MAILING_POSTCODE,
				CntMailingCountry AS MAILING_COUNTRY,
				CntLandline AS PHONE,
				CntMobile AS MOBILE_PHONE,
				CntFax AS FAX,
				CntEmail AS EMAIL,
				CntIsCf1 AS CONTACT_IS_CF1,
				CntIsCf2 AS CONTACT_IS_CF2,
				CntIsCf3 AS CONTACT_IS_CF3,
				CntIsCf4 AS CONTACT_IS_CF4,
				CntIsCf10 AS CONTACT_IS_CF10,
				CntIsCf11 AS CONTACT_IS_CF11,
				CntIsCf30 AS CONTACT_IS_CF30,
				CntVerifiedBy AS VERIFIED_BY
				--CntExistingCompanyRelationship AS ?? -- Can't compare as it doesn't exist in table STAGING.T_MATRIX_CONTACT.
          FROM [STAGING.SALESFORCE.BP].[SFCONTACTRAW]
     ) SF
          ON MX.SALESFORCE_CONTACT_ID = SF.SALESFORCE_CONTACT_ID
          AND (COALESCE(MX.SALESFORCE_ACCOUNT_ID,'') = COALESCE(SF.SALESFORCE_ACCOUNT_ID,'') OR
			COALESCE(MX.OWNER_ID, '')  <> COALESCE(SF.OWNER_ID, '') OR 
			COALESCE(MX.OWNER_NAME, '')  <> COALESCE(SF.OWNER_NAME, '') OR 
			COALESCE(MX.ACCOUNT_SIV_ID, '')  <> COALESCE(SF.ACCOUNT_SIV_ID, '') OR 
			COALESCE(MX.CONTACT_SIV_ID, '')  <> COALESCE(SF.CONTACT_SIV_ID, '') OR 
			COALESCE(MX.MATRIX_CONTACT_ID, '')  <> COALESCE(SF.MATRIX_CONTACT_ID, '') OR 
			COALESCE(MX.SALUTATION, '')  <> COALESCE(SF.SALUTATION, '') OR 
			COALESCE(MX.FIRST_NAME, '')  <> COALESCE(SF.FIRST_NAME, '') OR 
			COALESCE(MX.LAST_NAME, '')  <> COALESCE(SF.LAST_NAME, '') OR 
			COALESCE(MX.TITLE, '')  <> COALESCE(SF.TITLE, '') OR 
			COALESCE(MX.MAILING_STREET, '')  <> COALESCE(SF.MAILING_STREET, '') OR 
			COALESCE(MX.MAILING_CITY, '')  <> COALESCE(SF.MAILING_CITY, '') OR 
			COALESCE(MX.MAILING_STATE, '')  <> COALESCE(SF.MAILING_STATE, '') OR 
			COALESCE(MX.MAILING_POSTCODE, '')  <> COALESCE(SF.MAILING_POSTCODE, '') OR 
			COALESCE(MX.MAILING_COUNTRY, '')  <> COALESCE(SF.MAILING_COUNTRY, '') OR 
			COALESCE(MX.PHONE, '')  <> COALESCE(SF.PHONE, '') OR 
			COALESCE(MX.MOBILE_PHONE, '')  <> COALESCE(SF.MOBILE_PHONE, '') OR 
			COALESCE(MX.FAX, '')  <> COALESCE(SF.FAX, '') OR 
			COALESCE(MX.EMAIL, '')  <> COALESCE(SF.EMAIL, '') OR 
			COALESCE(MX.CONTACT_IS_CF1, '')  <> COALESCE(SF.CONTACT_IS_CF1, '') OR 
			COALESCE(MX.CONTACT_IS_CF2, '')  <> COALESCE(SF.CONTACT_IS_CF2, '') OR 
			COALESCE(MX.CONTACT_IS_CF3, '')  <> COALESCE(SF.CONTACT_IS_CF3, '') OR 
			COALESCE(MX.CONTACT_IS_CF4, '')  <> COALESCE(SF.CONTACT_IS_CF4, '') OR 
			COALESCE(MX.CONTACT_IS_CF10, '')  <> COALESCE(SF.CONTACT_IS_CF10, '') OR 
			COALESCE(MX.CONTACT_IS_CF11, '')  <> COALESCE(SF.CONTACT_IS_CF11, '') OR 
			COALESCE(MX.CONTACT_IS_CF30, '')  <> COALESCE(SF.CONTACT_IS_CF30, '') OR 
			COALESCE(MX.VERIFIED_BY, '')  <> COALESCE(SF.VERIFIED_BY, '') 
          )

