CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION682_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @OVERRIDE_ID INT, @FUND_SHORT_NAME VARCHAR (15)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


