CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION682_INBOXUPD]
@OVERRIDE_ID INT, @FUND_SHORT_NAME VARCHAR (15), @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @VALUE DECIMAL (38, 15), @VALUE_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


