CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION768_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @VALUATION_DATE DATETIME, @FUND_SHORT_NAME VARCHAR (20), @FUND_FISCAL_YEAR INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


