CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION753_AUDITLATESTCHANGE]
@FUND_SHORT_NAME VARCHAR (20), @EDM_SEC_ID INT, @FUND_FISCAL_YEAR INT, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


