CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION86_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @ClientTakeOnStageId SMALLINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


