CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION753_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @FUND_SHORT_NAME VARCHAR (20), @EDM_SEC_ID INT, @FUND_FISCAL_YEAR INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


