CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION735_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CircleId SMALLINT, @CircleId_UPDATE BIT, @TensionSummary NVARCHAR (MAX), @TensionSummary_UPDATE BIT, @TensionDescription NVARCHAR (MAX), @TensionDescription_UPDATE BIT, @TensionResolution VARCHAR (MAX), @TensionResolution_UPDATE BIT, @ResolutionDate DATETIME, @ResolutionDate_UPDATE BIT, @RaisedByPersonId SMALLINT, @RaisedByPersonId_UPDATE BIT, @JIRAKey NVARCHAR (50), @JIRAKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @SlackChannel NVARCHAR (21), @SlackChannel_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


