CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION731_INBOXDEL]
@EDM_SEC_ID INT, @FUND_SHORT_NAME VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


