CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION742_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Ticker_exchange VARCHAR (250), @Ticker_exchange_UPDATE BIT, @Country_Of_Risk VARCHAR (250), @Country_Of_Risk_UPDATE BIT, @Country_Of_Domicile VARCHAR (250), @Country_Of_Domicile_UPDATE BIT, @LEI VARCHAR (250), @LEI_UPDATE BIT, @ID_BB_GLOBAL_CO VARCHAR (250), @ID_BB_GLOBAL_CO_UPDATE BIT, @Country_Of_Incorporation VARCHAR (4), @Country_Of_Incorporation_UPDATE BIT, @CompanyType VARCHAR (250), @CompanyType_UPDATE BIT, @Salesforce_Account_Id VARCHAR (250), @Salesforce_Account_Id_UPDATE BIT, @BoxFolderID VARCHAR (250), @BoxFolderID_UPDATE BIT, @JiraEpicKey VARCHAR (250), @JiraEpicKey_UPDATE BIT, @PrimaryAnalystPersonID SMALLINT, @PrimaryAnalystPersonID_UPDATE BIT, @SecondaryAnalystPersonID SMALLINT, @SecondaryAnalystPersonID_UPDATE BIT, @Currency VARCHAR (3), @Currency_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


