CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION762_INBOXSELROWNUMBER]
@SEDOL VARCHAR (10), @RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @Sector VARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


