CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION705_INBOXSELSINGLEROW]
@CircleId SMALLINT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


