CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION756_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @EDM_Issuer_ID INT, @EDM_Issuer_ID_UPDATE BIT, @Recommendation VARCHAR (250), @Recommendation_UPDATE BIT, @EventType VARCHAR (250), @EventType_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @EventSummary VARCHAR (MAX), @EventSummary_UPDATE BIT, @BoxFileID VARCHAR (250), @BoxFileID_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @RAG VARCHAR (10), @RAG_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


