CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION689_INBOXUPD]
@SUBSCRIBER_ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @DESCRIPTION VARCHAR (50), @DESCRIPTION_UPDATE BIT, @EMAIL_ADDRESS VARCHAR (100), @EMAIL_ADDRESS_UPDATE BIT, @NOTIFY_BY_EMAIL BIT, @NOTIFY_BY_EMAIL_UPDATE BIT, @SLACK_ADDRESS VARCHAR (50), @SLACK_ADDRESS_UPDATE BIT, @NOTIFY_BY_SLACK BIT, @NOTIFY_BY_SLACK_UPDATE BIT, @ACTIVE BIT, @ACTIVE_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


