CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION757_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (50), @EDM_SEC_ID INT, @FUND_FISCAL_YEAR INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


