CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION768_INBOXSELSINGLEROW]
@VALUATION_DATE DATETIME, @FUND_SHORT_NAME VARCHAR (20), @FUND_FISCAL_YEAR INT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


