CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION9_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @EBIRegisterId INT, @EBIExternalReference VARCHAR (100), @EBIExternalReference_UPDATE BIT, @DateIdentified DATE, @DateIdentified_UPDATE BIT, @ReportedByPersonId SMALLINT, @ReportedByPersonId_UPDATE BIT, @RecordedByPersonId SMALLINT, @RecordedByPersonId_UPDATE BIT, @EBITypeCode VARCHAR (25), @EBITypeCode_UPDATE BIT, @EBIBreachTypeId SMALLINT, @EBIBreachTypeId_UPDATE BIT, @EBIImpactTypeId SMALLINT, @EBIImpactTypeId_UPDATE BIT, @EBICategorisationId SMALLINT, @EBICategorisationId_UPDATE BIT, @EBISummary NVARCHAR (MAX), @EBISummary_UPDATE BIT, @EBIStartDate DATE, @EBIStartDate_UPDATE BIT, @EBIEndDate DATE, @EBIEndDate_UPDATE BIT, @EBIClosureDate DATE, @EBIClosureDate_UPDATE BIT, @EBIResolvedYesNo BIT, @EBIResolvedYesNo_UPDATE BIT, @RemedyAction NVARCHAR (MAX), @RemedyAction_UPDATE BIT, @MitigationSteps NVARCHAR (MAX), @MitigationSteps_UPDATE BIT, @IncidentReportFinalizationDate DATE, @IncidentReportFinalizationDate_UPDATE BIT, @ExternalNotificationRequiredYesNo BIT, @ExternalNotificationRequiredYesNo_UPDATE BIT, @ExternalBodyId SMALLINT, @ExternalBodyId_UPDATE BIT, @ExternalNotificationDetails NVARCHAR (MAX), @ExternalNotificationDetails_UPDATE BIT, @ReimbursementRequiredYesNo BIT, @ReimbursementRequiredYesNo_UPDATE BIT, @ReimbursementAmount DECIMAL (19, 2), @ReimbursementAmount_UPDATE BIT, @ReimbursementComments NVARCHAR (MAX), @ReimbursementComments_UPDATE BIT, @ReimbursementDate DATE, @ReimbursementDate_UPDATE BIT, @WorkflowVersionGUID UNIQUEIDENTIFIER, @WorkflowVersionGUID_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @EBIRegisterCreationDatetime DATETIME, @EBIRegisterCreationDatetime_UPDATE BIT, @EBIRegisterLastModifiedDatetime DATETIME, @EBIRegisterLastModifiedDatetime_UPDATE BIT, @NotifiedDepartmentHeadId SMALLINT, @NotifiedDepartmentHeadId_UPDATE BIT, @SentBackYesNo BIT, @SentBackYesNo_UPDATE BIT, @DisputedPendingLitigationYesNo BIT, @DisputedPendingLitigationYesNo_UPDATE BIT, @InvestmentRelatedYesNo BIT, @InvestmentRelatedYesNo_UPDATE BIT, @DataProtectionRelatedYesNo BIT, @DataProtectionRelatedYesNo_UPDATE BIT, @ServiceIssueID VARCHAR (18), @ServiceIssueID_UPDATE BIT, @ServiceProviderName VARCHAR (128), @ServiceProviderName_UPDATE BIT, @ClientsNotifiedYesNo BIT, @ClientsNotifiedYesNo_UPDATE BIT, @Status VARCHAR (50), @Status_UPDATE BIT, @RegulatoryRelatedYesNo BIT, @RegulatoryRelatedYesNo_UPDATE BIT, @ReportableYesNo BIT, @ReportableYesNo_UPDATE BIT, @JIRAIssueKey VARCHAR (255), @JIRAIssueKey_UPDATE BIT, @HuddleEventId SMALLINT, @HuddleEventId_UPDATE BIT, @ActiveInvestmentBreachYesNo BIT, @ActiveInvestmentBreachYesNo_UPDATE BIT, @RiskSubcategoryID SMALLINT, @RiskSubcategoryID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


