CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION681_INBOXUPD]
@OVERRIDE_ID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @DESCRIPTION VARCHAR (100), @DESCRIPTION_UPDATE BIT, @AS_OF_DATE DATETIME, @AS_OF_DATE_UPDATE BIT, @CCY VARCHAR (3), @CCY_UPDATE BIT, @ACTIVE BIT, @ACTIVE_UPDATE BIT, @COMMENTS VARCHAR (200), @COMMENTS_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


