CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION711_INBOXUPD]
@sf_SfContactId VARCHAR (18), @DataField VARCHAR (50), @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @OverrideValue VARCHAR (2000), @OverrideValue_UPDATE BIT, @OverrideChoice VARCHAR (10), @OverrideChoice_UPDATE BIT, @OverrideStatus VARCHAR (10), @OverrideStatus_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


