CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION704_INBOXSELSINGLEROW]
@CircleId SMALLINT, @RoleId SMALLINT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


