CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION725_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Name NVARCHAR (100), @Name_UPDATE BIT, @Purpose NVARCHAR (MAX), @Purpose_UPDATE BIT, @ParentCircleId SMALLINT, @ParentCircleId_UPDATE BIT, @Label NVARCHAR (100), @Label_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @CircleLead SMALLINT, @CircleLead_UPDATE BIT, @Facilitator SMALLINT, @Facilitator_UPDATE BIT, @HasCircleLead BIT, @HasCircleLead_UPDATE BIT, @HasFacilitator BIT, @HasFacilitator_UPDATE BIT, @ProjectKey NVARCHAR (20), @ProjectKey_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


