CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION708_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @EventId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @HuddleEventId INT, @HuddleEventId_UPDATE BIT, @EventTypeId SMALLINT, @EventTypeId_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @EventDetails NVARCHAR (MAX), @EventDetails_UPDATE BIT, @JiraIssueKey NVARCHAR (50), @JiraIssueKey_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


