CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION732_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ConflictId INT, @ConflictId_UPDATE BIT, @ActionTypeId SMALLINT, @ActionTypeId_UPDATE BIT, @ActionDate DATETIME, @ActionDate_UPDATE BIT, @ActionComment NVARCHAR (MAX), @ActionComment_UPDATE BIT, @CreatedByPersonId SMALLINT, @CreatedByPersonId_UPDATE BIT, @JIRAIssueKey VARCHAR (255), @JIRAIssueKey_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


