CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION685_INBOXUPD]
@PermanentInsiderID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @PersonID SMALLINT, @PersonID_UPDATE BIT, @AdditionDateTime DATETIME, @AdditionDateTime_UPDATE BIT, @CeasedDateTime DATETIME, @CeasedDateTime_UPDATE BIT, @ActiveFlag BIT, @ActiveFlag_UPDATE BIT, @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


