CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION687_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY VARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Broker_ID VARCHAR (50), @Broker_ID_UPDATE BIT, @NT_Broker_Name VARCHAR (200), @NT_Broker_Name_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


