CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION703_INBOXSELSINGLEROW]
@POSITION_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


