CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION727_INBOXINS]
@TEXT VARCHAR (200), @TEXT_UPDATE BIT, @NUMBER INT, @NUMBER_UPDATE BIT, @DATETIME DATETIME, @DATETIME_UPDATE BIT, @BIT BIT, @BIT_UPDATE BIT, @DECIMAL DECIMAL (20, 10), @DECIMAL_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


