CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION764_INBOXGROUPSEL]
@FundName VARCHAR (8), @DATE DATETIME, @WhereSQL NVARCHAR (MAX), @GroupColumns NVARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


