CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION682_INBOXSELSINGLEROW]
@OVERRIDE_ID INT, @FUND_SHORT_NAME VARCHAR (15), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


