CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION713_INBOXUPD]
@RequestID INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @StatusID INT, @StatusID_UPDATE BIT, @EntityID INT, @EntityID_UPDATE BIT, @EntityName NVARCHAR (MAX), @EntityName_UPDATE BIT, @JiraIssueKey VARCHAR (50), @JiraIssueKey_UPDATE BIT, @Reason VARCHAR (MAX), @Reason_UPDATE BIT, @ChangeTypeID INT, @ChangeTypeID_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


