CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION750_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @FundShortName VARCHAR (20), @EDM_SEC_ID INT, @CalendarYear INT, @CADIS_SYSTEM_TIMESTAMP ROWVERSION, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Q1ExDate DATETIME, @Q1ExDate_UPDATE BIT, @Q1Rate DECIMAL (20, 6), @Q1Rate_UPDATE BIT, @Q2ExDate DATETIME, @Q2ExDate_UPDATE BIT, @Q2Rate DECIMAL (20, 6), @Q2Rate_UPDATE BIT, @Q3ExDate DATETIME, @Q3ExDate_UPDATE BIT, @Q3Rate DECIMAL (20, 6), @Q3Rate_UPDATE BIT, @Q4ExDate DATETIME, @Q4ExDate_UPDATE BIT, @Q4Rate DECIMAL (20, 6), @Q4Rate_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


