CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION763_INBOXGROUPSEL]
@SEDOL VARCHAR (10), @WhereSQL NVARCHAR (MAX), @GroupColumns NVARCHAR (MAX)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


