CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION720_INBOXINS]
@CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @RequestID INT, @RequestID_UPDATE BIT, @SubmittedByPersonID SMALLINT, @SubmittedByPersonID_UPDATE BIT, @AccountabilityID INT, @AccountabilityID_UPDATE BIT, @CurrentValue VARCHAR (MAX), @CurrentValue_UPDATE BIT, @ProposedValue VARCHAR (MAX), @ProposedValue_UPDATE BIT, @ChangeTypeID INT, @ChangeTypeID_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


