CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION762_INBOXSELSINGLEROW]
@SEDOL VARCHAR (10), @Sector VARCHAR (250), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


