CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION79_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ClientTakeOnId INT, @ClientTakeOnId_UPDATE BIT, @EventTypeId SMALLINT, @EventTypeId_UPDATE BIT, @RFPId INT, @RFPId_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @SubmittedDate DATETIME, @SubmittedDate_UPDATE BIT, @EventDetails VARCHAR (MAX), @EventDetails_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @ReviewComments VARCHAR (MAX), @ReviewComments_UPDATE BIT, @EventTrueFalse BIT, @EventTrueFalse_UPDATE BIT, @DepartmentId SMALLINT, @DepartmentId_UPDATE BIT, @JiraSubTaskKey VARCHAR (128), @JiraSubTaskKey_UPDATE BIT, @JiraEpicKey VARCHAR (128), @JiraEpicKey_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @ClientTakeOnEventLastModifiedDatetime DATETIME, @ClientTakeOnEventLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


