CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION753_INBOXDEL]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @FUND_SHORT_NAME VARCHAR (20), @EDM_SEC_ID INT, @FUND_FISCAL_YEAR INT, @CADIS_SYSTEM_TIMESTAMP ROWVERSION
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


