CREATE PROCEDURE [CADIS_PROC].[SPDM_MP1_SOURCE5_REALIGN_REALIGNEXISTINGNEW]
@OldCADISId INT, @CADISRowId INT, @NewCADISId INT, @ChangedBy NVARCHAR (100), @ChangedDate DATETIME, @Comment NVARCHAR (250), @Type TINYINT, @AssignedCADISId INT OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


