CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION201_INBOXSELSINGLEROW]
@ASSET VARCHAR (10), @ORDER_REF INT, @VALUATION_POINT DATETIME, @ESTIMATED_ BIT, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


