CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION185_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @ACCOUNT_NUMBER VARCHAR (50), @TNARRLONG VARCHAR (255), @NET_AMOUNT__BASE DECIMAL (20, 6), @RECOGNITION_DATE DATETIME, @NTRANCATG VARCHAR (100), @IEXTLREF VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


