CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION179_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @SubCategoryId SMALLINT, @RiskOwnerId SMALLINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


