CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION183_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @SOURCE VARCHAR (50), @POSITION_TYPE VARCHAR (50), @FUND_SHORT_NAME VARCHAR (8000), @POSITION_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


