CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION191_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @EDM_SEC_ID INT, @PRICE_TYPE VARCHAR (50), @PRICE_DATE DATETIME, @CADIS_SYSTEM_TIMESTAMP ROWVERSION, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @PRICE_SOURCE VARCHAR (50), @PRICE_SOURCE_UPDATE BIT, @PRICE_TIME VARCHAR (50), @PRICE_TIME_UPDATE BIT, @AVERAGE_COST VARCHAR (20), @AVERAGE_COST_UPDATE BIT, @PRICE_SOURCE_RANKING INT, @PRICE_SOURCE_RANKING_UPDATE BIT, @PRICE_ISO_CCY VARCHAR (3), @PRICE_ISO_CCY_UPDATE BIT, @MASTER_PRICE DECIMAL (24, 10), @MASTER_PRICE_UPDATE BIT, @ASK_PRICE DECIMAL (24, 10), @ASK_PRICE_UPDATE BIT, @MID_PRICE DECIMAL (24, 10), @MID_PRICE_UPDATE BIT, @BID_PRICE DECIMAL (24, 10), @BID_PRICE_UPDATE BIT, @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_PRIORITY INT, @CADIS_SYSTEM_PRIORITY_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT, @LAST_UPDATE_DATE DATETIME, @LAST_UPDATE_DATE_UPDATE BIT, @FX_RATE DECIMAL (18, 4), @FX_RATE_UPDATE BIT, @MARKET_VALUE DECIMAL (18, 2), @MARKET_VALUE_UPDATE BIT, @TICKER VARCHAR (26), @TICKER_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


