CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION241_INBOXUPD]
@Id INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @IsConfirmRequired CHAR (1), @IsConfirmRequired_UPDATE BIT, @IsReviewed CHAR (1), @IsReviewed_UPDATE BIT, @ModifiedByPersonId SMALLINT, @ModifiedByPersonId_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


