CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION182_AUDITLATESTCHANGE]
@SOURCE VARCHAR (50), @POSITION_TYPE VARCHAR (50), @FUND_SHORT_NAME VARCHAR (8000), @POSITION_DATE DATETIME, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


