CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION144_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @FUND_SHORT_NAME VARCHAR (15), @POSITION_DATE DATETIME, @ASSET_SUB_CATEGORY VARCHAR (100), @CCY VARCHAR (3), @CADIS_SYSTEM_TIMESTAMP ROWVERSION, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @LOCAL_VALUE DECIMAL (18, 3), @LOCAL_VALUE_UPDATE BIT, @BASE_VALUE DECIMAL (18, 3), @BASE_VALUE_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


