CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION143_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (15), @POSITION_DATE DATETIME, @ASSET_SUB_CATEGORY VARCHAR (100), @CCY VARCHAR (3), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


