CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION202_INBOXSELSINGLEROW]
@VALUATION_POINT_DATE DATETIME, @EXTERNAL_FUND_CODE VARCHAR (50), @FUND_REFERENCE VARCHAR (20), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


