CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION192_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @EDM_SEC_ID INT, @PRICE_TYPE VARCHAR (50), @PRICE_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


