CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION244_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CommsNameBK VARCHAR (128), @CommsNameBK_UPDATE BIT, @FinPromType VARCHAR (128), @FinPromType_UPDATE BIT, @PromotionChannel VARCHAR (128), @PromotionChannel_UPDATE BIT, @ThirdPartyYesNo BIT, @ThirdPartyYesNo_UPDATE BIT, @IssueDueDate DATETIME, @IssueDueDate_UPDATE BIT, @JIRAProjectInitiationDate DATETIME, @JIRAProjectInitiationDate_UPDATE BIT, @RecurrenceFrequency VARCHAR (25), @RecurrenceFrequency_UPDATE BIT, @ApprovalDate DATETIME, @ApprovalDate_UPDATE BIT, @ComplianceComments VARCHAR (2048), @ComplianceComments_UPDATE BIT, @CompliancePersonId SMALLINT, @CompliancePersonId_UPDATE BIT, @ComplianceRoleId SMALLINT, @ComplianceRoleId_UPDATE BIT, @FinPromStatus VARCHAR (128), @FinPromStatus_UPDATE BIT, @JIRAEpicKey VARCHAR (2000), @JIRAEpicKey_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @Notes VARCHAR (2000), @Notes_UPDATE BIT, @IsFinProm BIT, @IsFinProm_UPDATE BIT, @IntendedAudienceDetails VARCHAR (128), @IntendedAudienceDetails_UPDATE BIT, @ExpiryDate DATETIME, @ExpiryDate_UPDATE BIT, @ReviewFrequency VARCHAR (25), @ReviewFrequency_UPDATE BIT, @IssuedBy VARCHAR (50), @IssuedBy_UPDATE BIT, @IssuedDate DATETIME, @IssuedDate_UPDATE BIT, @Author VARCHAR (50), @Author_UPDATE BIT, @MandateId INT, @MandateId_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @JiraIssueKey VARCHAR (128), @JiraIssueKey_UPDATE BIT, @ComplianceJiraKey VARCHAR (128), @ComplianceJiraKey_UPDATE BIT, @Topic NVARCHAR (255), @Topic_UPDATE BIT, @Purpose NVARCHAR (MAX), @Purpose_UPDATE BIT, @WorkflowVersionGUID UNIQUEIDENTIFIER, @WorkflowVersionGUID_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @FinPromLastModifiedDatetime DATETIME, @FinPromLastModifiedDatetime_UPDATE BIT, @Outcome NVARCHAR (MAX), @Outcome_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


