CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION192_AUDITLATESTCHANGE]
@EDM_SEC_ID INT, @PRICE_TYPE VARCHAR (50), @PRICE_DATE DATETIME, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


