CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION182_INBOXSELSINGLEROW]
@SOURCE VARCHAR (50), @POSITION_TYPE VARCHAR (50), @FUND_SHORT_NAME VARCHAR (8000), @POSITION_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


