CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION2_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @LOG_DATE DATETIME, @COMPONENT_NAME VARCHAR (50), @COMPONENT_TYPE VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


