CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION2_INBOXDEL]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @LOG_DATE DATETIME, @COMPONENT_NAME VARCHAR (50), @COMPONENT_TYPE VARCHAR (50), @CADIS_SYSTEM_TIMESTAMP ROWVERSION
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


