CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION205_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATETIME, @CURRENCY VARCHAR (20), @FUND_FLOW_TYPE VARCHAR (20), @FLOW_TYPE VARCHAR (100), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @MARKET_VALUE DECIMAL (18, 2), @MARKET_VALUE_UPDATE BIT, @SETTLEMENT_DATE DATETIME, @SETTLEMENT_DATE_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


