CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION2_INBOXSELSINGLEROW]
@LOG_DATE DATETIME, @COMPONENT_NAME VARCHAR (50), @COMPONENT_TYPE VARCHAR (50), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


