CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION200_AUDITLATESTCHANGE]
@ASSET VARCHAR (10), @ORDER_REF INT, @VALUATION_POINT DATETIME, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


