CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION190_INBOXSELSINGLEROW]
@EDM_SEC_ID INT, @PRICE_TYPE VARCHAR (50), @PRICE_DATE DATETIME, @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


