CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION247_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @PolicyId INT, @PolicyId_UPDATE BIT, @ProcDocumentId INT, @ProcDocumentId_UPDATE BIT, @EventTypeId SMALLINT, @EventTypeId_UPDATE BIT, @SubmittedByPersonId SMALLINT, @SubmittedByPersonId_UPDATE BIT, @EventDetails VARCHAR (MAX), @EventDetails_UPDATE BIT, @EventDate DATETIME, @EventDate_UPDATE BIT, @EventStatus VARCHAR (25), @EventStatus_UPDATE BIT, @EventTrueFalse BIT, @EventTrueFalse_UPDATE BIT, @JiraTaskKey VARCHAR (128), @JiraTaskKey_UPDATE BIT, @IsLegalStatusChange BIT, @IsLegalStatusChange_UPDATE BIT, @IsRebrand BIT, @IsRebrand_UPDATE BIT, @IsContentChange BIT, @IsContentChange_UPDATE BIT, @BoxFileId VARCHAR (255), @BoxFileId_UPDATE BIT, @BoxFilename VARCHAR (255), @BoxFilename_UPDATE BIT, @DocumentationFolderLink VARCHAR (2000), @DocumentationFolderLink_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @EventLastModifiedDatetime DATETIME, @EventLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


