CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION196_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATETIME, @CURRENCY VARCHAR (20), @FUND_FLOW_TYPE VARCHAR (5), @FLOW_TYPE VARCHAR (100), @SOURCE_TYPE VARCHAR (20), @SOURCE VARCHAR (20), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


