CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION187_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @VALUATION_POINT_DATE DATETIME, @EXTERNAL_FUND_CODE VARCHAR (50), @FUND_REFERENCE VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


