CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION192_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @EDM_SEC_ID INT, @PRICE_TYPE VARCHAR (50), @PRICE_DATE DATETIME, @CADIS_SYSTEM_TIMESTAMP ROWVERSION, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @PRICE_SOURCE DATETIME, @PRICE_SOURCE_UPDATE BIT, @PRICE_TIME DATETIME, @PRICE_TIME_UPDATE BIT, @AVERAGE_COST DATETIME, @AVERAGE_COST_UPDATE BIT, @PRICE_SOURCE_RANKING DATETIME, @PRICE_SOURCE_RANKING_UPDATE BIT, @PRICE_ISO_CCY DATETIME, @PRICE_ISO_CCY_UPDATE BIT, @MASTER_PRICE DATETIME, @MASTER_PRICE_UPDATE BIT, @ASK_PRICE DATETIME, @ASK_PRICE_UPDATE BIT, @MID_PRICE DATETIME, @MID_PRICE_UPDATE BIT, @BID_PRICE DATETIME, @BID_PRICE_UPDATE BIT, @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_PRIORITY INT, @CADIS_SYSTEM_PRIORITY_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT, @LAST_UPDATE_DATE DATETIME, @LAST_UPDATE_DATE_UPDATE BIT, @FX_RATE DATETIME, @FX_RATE_UPDATE BIT, @MARKET_VALUE DATETIME, @MARKET_VALUE_UPDATE BIT, @TICKER DATETIME, @TICKER_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


