CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION188_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @VALUATION_POINT_DATE DATETIME, @EXTERNAL_FUND_CODE VARCHAR (50), @FUND_REFERENCE VARCHAR (20), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FUND_SHORT_NAME DATETIME, @FUND_SHORT_NAME_UPDATE BIT, @FLOW_TYPE DATETIME, @FLOW_TYPE_UPDATE BIT, @MCID DATETIME, @MCID_UPDATE BIT, @TRUSTEE DATETIME, @TRUSTEE_UPDATE BIT, @VALUATION_POINT_TIME DATETIME, @VALUATION_POINT_TIME_UPDATE BIT, @FUND_LONG_NAME DATETIME, @FUND_LONG_NAME_UPDATE BIT, @BROUGHT_FORWARD_POSITION DATETIME, @BROUGHT_FORWARD_POSITION_UPDATE BIT, @NET_UNIT_MOVEMENT DATETIME, @NET_UNIT_MOVEMENT_UPDATE BIT, @BOOK_CONVERSION_IN DATETIME, @BOOK_CONVERSION_IN_UPDATE BIT, @BOOK_CONVERSION_OUT DATETIME, @BOOK_CONVERSION_OUT_UPDATE BIT, @CONVERSION_FACTOR DATETIME, @CONVERSION_FACTOR_UPDATE BIT, @ESTIMATED_CLOSING_BALANCE DATETIME, @ESTIMATED_CLOSING_BALANCE_UPDATE BIT, @UNIT_DECISION DATETIME, @UNIT_DECISION_UPDATE BIT, @CASH_DECISION DATETIME, @CASH_DECISION_UPDATE BIT, @CARRIED_FORWARD_BALANCE DATETIME, @CARRIED_FORWARD_BALANCE_UPDATE BIT, @BOOK_BASIS DATETIME, @BOOK_BASIS_UPDATE BIT, @DECISION_VALUE DATETIME, @DECISION_VALUE_UPDATE BIT, @INSPECIE_FLAG DATETIME, @INSPECIE_FLAG_UPDATE BIT, @NARRATIVE DATETIME, @NARRATIVE_UPDATE BIT, @SIGNATORY DATETIME, @SIGNATORY_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


