CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION243_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @FinPromRegisterId INT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CapitalAtRiskStatedClearly BIT, @CapitalAtRiskStatedClearly_UPDATE BIT, @YieldFigureQuoted BIT, @YieldFigureQuoted_UPDATE BIT, @BalanceLongShortTermProjects BIT, @BalanceLongShortTermProjects_UPDATE BIT, @SufficientInfoOnCharges BIT, @SufficientInfoOnCharges_UPDATE BIT, @MustStateFCA BIT, @MustStateFCA_UPDATE BIT, @NoReferenceToGuaranteed BIT, @NoReferenceToGuaranteed_UPDATE BIT, @FinPromIdentifiableAsPromotion BIT, @FinPromIdentifiableAsPromotion_UPDATE BIT, @CanOnlyBeFactualReferences BIT, @CanOnlyBeFactualReferences_UPDATE BIT, @ContainsNameOfFirm BIT, @ContainsNameOfFirm_UPDATE BIT, @AccurateAndBalanced BIT, @AccurateAndBalanced_UPDATE BIT, @FontSizeUsed BIT, @FontSizeUsed_UPDATE BIT, @RelevantRisks BIT, @RelevantRisks_UPDATE BIT, @SufficientForAverageMember BIT, @SufficientForAverageMember_UPDATE BIT, @DoesNotDisguise BIT, @DoesNotDisguise_UPDATE BIT, @InfoNotIndicateFCA BIT, @InfoNotIndicateFCA_UPDATE BIT, @ComparisonsMeaningful BIT, @ComparisonsMeaningful_UPDATE BIT, @TaxRefStateDependsOn BIT, @TaxRefStateDependsOn_UPDATE BIT, @BenchQuotedSourcedESMA BIT, @BenchQuotedSourcedESMA_UPDATE BIT, @InfoMustBeConsistent BIT, @InfoMustBeConsistent_UPDATE BIT, @PPNotProminentFeature BIT, @PPNotProminentFeature_UPDATE BIT, @PPMustCover BIT, @PPMustCover_UPDATE BIT, @IncludeRefPeriod BIT, @IncludeRefPeriod_UPDATE BIT, @MustProminentlyStatePP BIT, @MustProminentlyStatePP_UPDATE BIT, @StateCurrencyAndWarning BIT, @StateCurrencyAndWarning_UPDATE BIT, @StateEffectOfFees BIT, @StateEffectOfFees_UPDATE BIT, @MustIncludeStandardPerfTable BIT, @MustIncludeStandardPerfTable_UPDATE BIT, @StandardPerfTableNoLessProminent BIT, @StandardPerfTableNoLessProminent_UPDATE BIT, @CarveOutsForProspectusKID BIT, @CarveOutsForProspectusKID_UPDATE BIT, @SimulatedPPAndFuturePerf BIT, @SimulatedPPAndFuturePerf_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @FinPromsChecklistLastModifiedDatetime DATETIME, @FinPromsChecklistLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


