CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION201_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @ASSET VARCHAR (10), @ORDER_REF INT, @VALUATION_POINT DATETIME, @ESTIMATED_ BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


