CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION199_AUDITLATESTCHANGE]
@ASSET VARCHAR (10), @ORDER_REF INT, @VALUATION_POINT DATETIME, @ESTIMATED_ BIT, @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


