CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION2_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @LOG_DATE DATETIME, @COMPONENT_NAME VARCHAR (50), @COMPONENT_TYPE VARCHAR (50), @CADIS_SYSTEM_TIMESTAMP ROWVERSION, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @COMMENTS VARCHAR (500), @COMMENTS_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


