CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION183_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @SOURCE VARCHAR (50), @POSITION_TYPE VARCHAR (50), @FUND_SHORT_NAME VARCHAR (8000), @POSITION_DATE DATETIME, @CADIS_SYSTEM_TIMESTAMP ROWVERSION, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @TOTAL_MARKET_VALUE_LOCAL BIT, @TOTAL_MARKET_VALUE_LOCAL_UPDATE BIT, @TOTAL_MARKET_VALUE_BASE BIT, @TOTAL_MARKET_VALUE_BASE_UPDATE BIT, @STATUS BIT, @STATUS_UPDATE BIT, @TOTAL_ACCRUED_MARKET_VALUE_BASE BIT, @TOTAL_ACCRUED_MARKET_VALUE_BASE_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


