CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION186_INBOXUPD]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @ACCOUNT_NUMBER VARCHAR (50), @TNARRLONG VARCHAR (255), @NET_AMOUNT__BASE DECIMAL (20, 6), @RECOGNITION_DATE DATETIME, @NTRANCATG VARCHAR (100), @IEXTLREF VARCHAR (50), @CADIS_SYSTEM_TIMESTAMP ROWVERSION, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @CONSOLIDATION BIT, @CONSOLIDATION_UPDATE BIT, @FUND_SHORT_NAME BIT, @FUND_SHORT_NAME_UPDATE BIT, @FROM_DATE BIT, @FROM_DATE_UPDATE BIT, @THROUGH_DATE BIT, @THROUGH_DATE_UPDATE BIT, @TASTDESCMED BIT, @TASTDESCMED_UPDATE BIT, @ABASBSE BIT, @ABASBSE_UPDATE BIT, @AMKTVAL BIT, @AMKTVAL_UPDATE BIT, @ARLSDGAIN BIT, @ARLSDGAIN_UPDATE BIT, @AEXCHGNLS BIT, @AEXCHGNLS_UPDATE BIT, @ASSET_IDENTIFIER BIT, @ASSET_IDENTIFIER_UPDATE BIT, @CTEMPLTYPE BIT, @CTEMPLTYPE_UPDATE BIT, @CVALNTYPEO BIT, @CVALNTYPEO_UPDATE BIT, @TSHAREPAR BIT, @TSHAREPAR_UPDATE BIT, @REVERSAL_INDICATOR BIT, @REVERSAL_INDICATOR_UPDATE BIT, @ALOTCOSTGNLS BIT, @ALOTCOSTGNLS_UPDATE BIT, @DTRANPROC BIT, @DTRANPROC_UPDATE BIT, @CSORTCDE3 BIT, @CSORTCDE3_UPDATE BIT, @ERROR_CODE BIT, @ERROR_CODE_UPDATE BIT, @CONSOLIDATION_AUDIT_INDICATOR_FLAG BIT, @CONSOLIDATION_AUDIT_INDICATOR_FLAG_UPDATE BIT, @CASSETLIAB BIT, @CASSETLIAB_UPDATE BIT, @ACCRUED_INTEREST BIT, @ACCRUED_INTEREST_UPDATE BIT, @DSET BIT, @DSET_UPDATE BIT, @ACCRUAL_CHANGE_FROM_SECURITY_MOVEMENTS_OFFSET BIT, @ACCRUAL_CHANGE_FROM_SECURITY_MOVEMENTS_OFFSET_UPDATE BIT, @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_PRIORITY INT, @CADIS_SYSTEM_PRIORITY_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


