CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION206_INBOXSELSINGLEROW]
@FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATETIME, @CURRENCY VARCHAR (20), @FUND_FLOW_TYPE VARCHAR (20), @FLOW_TYPE VARCHAR (100), @Username NVARCHAR (250)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


