CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION187_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @VALUATION_POINT_DATE DATETIME, @EXTERNAL_FUND_CODE VARCHAR (50), @FUND_REFERENCE VARCHAR (20), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FUND_SHORT_NAME VARCHAR (15), @FUND_SHORT_NAME_UPDATE BIT, @FLOW_TYPE VARCHAR (40), @FLOW_TYPE_UPDATE BIT, @MCID INT, @MCID_UPDATE BIT, @TRUSTEE VARCHAR (50), @TRUSTEE_UPDATE BIT, @VALUATION_POINT_TIME VARCHAR (8000), @VALUATION_POINT_TIME_UPDATE BIT, @FUND_LONG_NAME VARCHAR (100), @FUND_LONG_NAME_UPDATE BIT, @BROUGHT_FORWARD_POSITION DECIMAL (20, 4), @BROUGHT_FORWARD_POSITION_UPDATE BIT, @NET_UNIT_MOVEMENT DECIMAL (20, 4), @NET_UNIT_MOVEMENT_UPDATE BIT, @BOOK_CONVERSION_IN DECIMAL (20, 4), @BOOK_CONVERSION_IN_UPDATE BIT, @BOOK_CONVERSION_OUT DECIMAL (20, 4), @BOOK_CONVERSION_OUT_UPDATE BIT, @CONVERSION_FACTOR DECIMAL (20, 4), @CONVERSION_FACTOR_UPDATE BIT, @ESTIMATED_CLOSING_BALANCE DECIMAL (20, 4), @ESTIMATED_CLOSING_BALANCE_UPDATE BIT, @UNIT_DECISION DECIMAL (20, 4), @UNIT_DECISION_UPDATE BIT, @CASH_DECISION DECIMAL (20, 4), @CASH_DECISION_UPDATE BIT, @CARRIED_FORWARD_BALANCE DECIMAL (20, 4), @CARRIED_FORWARD_BALANCE_UPDATE BIT, @BOOK_BASIS VARCHAR (5), @BOOK_BASIS_UPDATE BIT, @DECISION_VALUE DECIMAL (20, 2), @DECISION_VALUE_UPDATE BIT, @INSPECIE_FLAG VARCHAR (20), @INSPECIE_FLAG_UPDATE BIT, @NARRATIVE VARCHAR (20), @NARRATIVE_UPDATE BIT, @SIGNATORY VARCHAR (20), @SIGNATORY_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


