CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION189_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @VALUATION_POINT_DATE DATETIME, @EXTERNAL_FUND_CODE VARCHAR (50), @FUND_REFERENCE VARCHAR (20), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @FUND_SHORT_NAME BIT, @FUND_SHORT_NAME_UPDATE BIT, @FLOW_TYPE BIT, @FLOW_TYPE_UPDATE BIT, @MCID BIT, @MCID_UPDATE BIT, @TRUSTEE BIT, @TRUSTEE_UPDATE BIT, @VALUATION_POINT_TIME BIT, @VALUATION_POINT_TIME_UPDATE BIT, @FUND_LONG_NAME BIT, @FUND_LONG_NAME_UPDATE BIT, @BROUGHT_FORWARD_POSITION BIT, @BROUGHT_FORWARD_POSITION_UPDATE BIT, @NET_UNIT_MOVEMENT BIT, @NET_UNIT_MOVEMENT_UPDATE BIT, @BOOK_CONVERSION_IN BIT, @BOOK_CONVERSION_IN_UPDATE BIT, @BOOK_CONVERSION_OUT BIT, @BOOK_CONVERSION_OUT_UPDATE BIT, @CONVERSION_FACTOR BIT, @CONVERSION_FACTOR_UPDATE BIT, @ESTIMATED_CLOSING_BALANCE BIT, @ESTIMATED_CLOSING_BALANCE_UPDATE BIT, @UNIT_DECISION BIT, @UNIT_DECISION_UPDATE BIT, @CASH_DECISION BIT, @CASH_DECISION_UPDATE BIT, @CARRIED_FORWARD_BALANCE BIT, @CARRIED_FORWARD_BALANCE_UPDATE BIT, @BOOK_BASIS BIT, @BOOK_BASIS_UPDATE BIT, @DECISION_VALUE BIT, @DECISION_VALUE_UPDATE BIT, @INSPECIE_FLAG BIT, @INSPECIE_FLAG_UPDATE BIT, @NARRATIVE BIT, @NARRATIVE_UPDATE BIT, @SIGNATORY BIT, @SIGNATORY_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


