CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION186_AUDITLATESTCHANGE]
@ACCOUNT_NUMBER VARCHAR (50), @TNARRLONG VARCHAR (255), @NET_AMOUNT__BASE DECIMAL (20, 6), @RECOGNITION_DATE DATETIME, @NTRANCATG VARCHAR (100), @IEXTLREF VARCHAR (50), @FieldName NVARCHAR (100), @LastConstructedDate DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


