CREATE TABLE [CADIS_PROC].[DC_ENRICH_INFO_RUNID] (
    [FILE_NAME__RUNID]                INT          NOT NULL,
    [FILE_TYPE__RUNID]                INT          NOT NULL,
    [FILE_DATE__RUNID]                INT          NOT NULL,
    [PRICE_FILE_TYPE__RUNID]          INT          NOT NULL,
    [NUMBER_OF_RECORDS__RUNID]        INT          NOT NULL,
    [EDM_SEC_ID__RUNID]               INT          NOT NULL,
    [SECURITY_IDENTIFIER_FLAG__RUNID] INT          NOT NULL,
    [FIRM_IDENTIFIER__RUNID]          INT          NOT NULL,
    [TICKER__RUNID]                   INT          NOT NULL,
    [ISIN_NUMBER__RUNID]              INT          NOT NULL,
    [UNIQUE_IDENTIFIER]               VARCHAR (30) NOT NULL,
    [PARSEYEABLE_DESCRIPTION__RUNID]  INT          NOT NULL,
    [BID_PRICE__RUNID]                INT          NOT NULL,
    [ASK_PRICE__RUNID]                INT          NOT NULL,
    [MID_PRICE__RUNID]                INT          NOT NULL,
    [DATE_OF_LAST_UPDATE__RUNID]      INT          NOT NULL,
    [YESTERDAY_CLOSE_PRICE__RUNID]    INT          NOT NULL,
    [TIME_OF_LAST_UPDATE__RUNID]      INT          NOT NULL,
    [NET_CURRENT_POSITION__RUNID]     INT          NOT NULL,
    [SHORT_NAME__RUNID]               INT          NOT NULL,
    [SECURITY_TYPE__RUNID]            INT          NOT NULL,
    [CLOSING_MID/TRADE_PRICE__RUNID]  INT          NOT NULL,
    [AVERAGE_COST__RUNID]             INT          NOT NULL,
    [PRICE_IS_PENCE_QUOTED__RUNID]    INT          NOT NULL,
    [CURRENCY__RUNID]                 INT          NOT NULL,
    [FX_RATE__RUNID]                  INT          NOT NULL,
    [MARKET_VALUE__RUNID]             INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([UNIQUE_IDENTIFIER] ASC)
);

