CREATE TABLE [CADIS_PROC].[DC_ENNTPOS_INFO_RULE] (
    [EDM_SEC_ID__RULEID]                 INT             NULL,
    [FILE_NAME__RULEID]                  INT             NULL,
    [FILE_TYPE__RULEID]                  INT             NULL,
    [FILE_DATE__RULEID]                  INT             NULL,
    [NUMBER_OF_RECORDS__RULEID]          INT             NULL,
    [TICKET_NUMBER__RULEID]              INT             NULL,
    [TRADE_DATE]                         DATETIME        NOT NULL,
    [SECURITY_IDENTIFIER_FLAG__RULEID]   INT             NULL,
    [SECURITY_IDENTIFIER__RULEID]        INT             NULL,
    [SETTLEMENT_DATE__RULEID]            INT             NULL,
    [LONGSHORT_INDICATOR__RULEID]        INT             NULL,
    [POSITION]                           DECIMAL (15, 2) NOT NULL,
    [ACCOUNT]                            VARCHAR (15)    NOT NULL,
    [PRICE_FRACTIONAL_INDICATOR__RULEID] INT             NULL,
    [PRICE]                              DECIMAL (18, 2) NOT NULL,
    [EXCHANGE_CODE__RULEID]              INT             NULL,
    [PRODUCT_CODE__RULEID]               INT             NULL,
    [BRADY-STYLE_FACTOR__RULEID]         INT             NULL,
    [UNIQUE_BLOOMBERG_ID]                VARCHAR (20)    NOT NULL,
    [FX_FORWARD_POINTS__RULEID]          INT             NULL,
    [SWAP_PAYRECEIVE_FLAG__RULEID]       INT             NULL,
    [SWAP_FEE__RULEID]                   INT             NULL,
    [PAY_NOTIONAL_AMOUNT__RULEID]        INT             NULL,
    [RECEIVE_NOTIONAL_AMOUNT__RULEID]    INT             NULL,
    [FX_AVERAGE_COST__RULEID]            INT             NULL,
    [IS_SHORT__RULEID]                   INT             NULL,
    [IS_CFD__RULEID]                     INT             NULL,
    [PRIME_BROKER__RULEID]               INT             NULL,
    [STRATEGY_NAME__RULEID]              INT             NULL,
    PRIMARY KEY CLUSTERED ([TRADE_DATE] ASC, [POSITION] ASC, [ACCOUNT] ASC, [PRICE] ASC, [UNIQUE_BLOOMBERG_ID] ASC)
);

