CREATE TABLE [CADIS_PROC].[DC_ENRICH_INFO_RULE] (
    [FILE_NAME__RULEID]                INT          NULL,
    [FILE_TYPE__RULEID]                INT          NULL,
    [FILE_DATE__RULEID]                INT          NULL,
    [PRICE_FILE_TYPE__RULEID]          INT          NULL,
    [NUMBER_OF_RECORDS__RULEID]        INT          NULL,
    [EDM_SEC_ID__RULEID]               INT          NULL,
    [SECURITY_IDENTIFIER_FLAG__RULEID] INT          NULL,
    [FIRM_IDENTIFIER__RULEID]          INT          NULL,
    [TICKER__RULEID]                   INT          NULL,
    [ISIN_NUMBER__RULEID]              INT          NULL,
    [UNIQUE_IDENTIFIER]                VARCHAR (30) NOT NULL,
    [PARSEYEABLE_DESCRIPTION__RULEID]  INT          NULL,
    [BID_PRICE__RULEID]                INT          NULL,
    [ASK_PRICE__RULEID]                INT          NULL,
    [MID_PRICE__RULEID]                INT          NULL,
    [DATE_OF_LAST_UPDATE__RULEID]      INT          NULL,
    [YESTERDAY_CLOSE_PRICE__RULEID]    INT          NULL,
    [TIME_OF_LAST_UPDATE__RULEID]      INT          NULL,
    [NET_CURRENT_POSITION__RULEID]     INT          NULL,
    [SHORT_NAME__RULEID]               INT          NULL,
    [SECURITY_TYPE__RULEID]            INT          NULL,
    [CLOSING_MID/TRADE_PRICE__RULEID]  INT          NULL,
    [AVERAGE_COST__RULEID]             INT          NULL,
    [PRICE_IS_PENCE_QUOTED__RULEID]    INT          NULL,
    [CURRENCY__RULEID]                 INT          NULL,
    [FX_RATE__RULEID]                  INT          NULL,
    [MARKET_VALUE__RULEID]             INT          NULL,
    PRIMARY KEY CLUSTERED ([UNIQUE_IDENTIFIER] ASC)
);

