CREATE TABLE [CADIS_PROC].[DC_ENPKGDFILE_INFO_RUNID] (
    [TOPLEVELRUNID]        INT NOT NULL,
    [FILE_NAME__RUNID]     INT NOT NULL,
    [CLIENT__RUNID]        INT NOT NULL,
    [ENV__RUNID]           INT NOT NULL,
    [TIME_STAMP__RUNID]    INT NOT NULL,
    [STATUS__RUNID]        INT NOT NULL,
    [STATUS_DECODE__RUNID] INT NOT NULL,
    [PATH__RUNID]          INT NOT NULL,
    PRIMARY KEY CLUSTERED ([TOPLEVELRUNID] ASC) WITH (FILLFACTOR = 80)
);

