CREATE TABLE [CADIS_PROC].[DC_ENPKGDFILE_ENPKGSTA_PREP] (
    [NO]                     INT           NOT NULL,
    [VALUE]                  VARCHAR (6)   NULL,
    [STATUS]                 VARCHAR (10)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL
);

