CREATE TABLE [CADIS_PROC].[DC_ENNTPOS_INFO_RUNID] (
    [EDM_SEC_ID__RUNID]                 INT             NOT NULL,
    [FILE_NAME__RUNID]                  INT             NOT NULL,
    [FILE_TYPE__RUNID]                  INT             NOT NULL,
    [FILE_DATE__RUNID]                  INT             NOT NULL,
    [NUMBER_OF_RECORDS__RUNID]          INT             NOT NULL,
    [TICKET_NUMBER__RUNID]              INT             NOT NULL,
    [TRADE_DATE]                        DATETIME        NOT NULL,
    [SECURITY_IDENTIFIER_FLAG__RUNID]   INT             NOT NULL,
    [SECURITY_IDENTIFIER__RUNID]        INT             NOT NULL,
    [SETTLEMENT_DATE__RUNID]            INT             NOT NULL,
    [LONGSHORT_INDICATOR__RUNID]        INT             NOT NULL,
    [POSITION]                          DECIMAL (15, 2) NOT NULL,
    [ACCOUNT]                           VARCHAR (15)    NOT NULL,
    [PRICE_FRACTIONAL_INDICATOR__RUNID] INT             NOT NULL,
    [PRICE]                             DECIMAL (18, 2) NOT NULL,
    [EXCHANGE_CODE__RUNID]              INT             NOT NULL,
    [PRODUCT_CODE__RUNID]               INT             NOT NULL,
    [BRADY-STYLE_FACTOR__RUNID]         INT             NOT NULL,
    [UNIQUE_BLOOMBERG_ID]               VARCHAR (20)    NOT NULL,
    [FX_FORWARD_POINTS__RUNID]          INT             NOT NULL,
    [SWAP_PAYRECEIVE_FLAG__RUNID]       INT             NOT NULL,
    [SWAP_FEE__RUNID]                   INT             NOT NULL,
    [PAY_NOTIONAL_AMOUNT__RUNID]        INT             NOT NULL,
    [RECEIVE_NOTIONAL_AMOUNT__RUNID]    INT             NOT NULL,
    [FX_AVERAGE_COST__RUNID]            INT             NOT NULL,
    [IS_SHORT__RUNID]                   INT             NOT NULL,
    [IS_CFD__RUNID]                     INT             NOT NULL,
    [PRIME_BROKER__RUNID]               INT             NOT NULL,
    [STRATEGY_NAME__RUNID]              INT             NOT NULL,
    PRIMARY KEY CLUSTERED ([TRADE_DATE] ASC, [POSITION] ASC, [ACCOUNT] ASC, [PRICE] ASC, [UNIQUE_BLOOMBERG_ID] ASC)
);

