CREATE TABLE [CADIS_PROC].[DC_ENNTPOS_MATCHER_PREP] (
    [CADIS Id]                     INT             NOT NULL,
    [CADIS Priority]               TINYINT         NOT NULL,
    [FILE_NAME]                    VARCHAR (50)    NULL,
    [FILE_DATE]                    DATETIME        NULL,
    [FILE_TYPE]                    VARCHAR (20)    NULL,
    [NUMBER_OF_RECORDS]            INT             NULL,
    [SECURITY_IDENTIFIER_FLAG]     INT             NULL,
    [FIRM_IDENTIFIER]              VARCHAR (12)    NULL,
    [TICKER]                       VARCHAR (8)     NULL,
    [COUNTRY]                      VARCHAR (50)    NULL,
    [CURRENCY]                     VARCHAR (3)     NULL,
    [PRPL_INDICATOR]               VARCHAR (1)     NULL,
    [MATURITY]                     DATETIME        NULL,
    [ISSUER]                       VARCHAR (80)    NULL,
    [AMOUNT_OUTSTANDING]           DECIMAL (20, 2) NULL,
    [AMOUNT_ISSUED]                DECIMAL (20, 2) NULL,
    [NAME]                         VARCHAR (80)    NULL,
    [UNDERLYING_CUSIP]             VARCHAR (9)     NULL,
    [FITCH_RATING]                 VARCHAR (10)    NULL,
    [MOODYS_RATING]                VARCHAR (13)    NULL,
    [ISIN_NUMBER]                  VARCHAR (12)    NULL,
    [UNIQUE_IDENTIFIER]            VARCHAR (30)    NOT NULL,
    [IPO]                          VARCHAR (4)     NULL,
    [SEDOL1_NUMBER]                VARCHAR (7)     NULL,
    [SEDOL2_NUMBER]                VARCHAR (7)     NULL,
    [DIVIDEND_EX_DATE]             DATETIME        NULL,
    [DIVIDEND_FREQUENCY]           VARCHAR (8)     NULL,
    [DIVIDEND_PAY_DATE]            DATETIME        NULL,
    [DIVIDEND_CURRENCY]            VARCHAR (5)     NULL,
    [ISO_COUNTRY_OF_ISSUE]         VARCHAR (4)     NULL,
    [EXCHANGE_CODE]                VARCHAR (18)    NULL,
    [TICKER_AND_EXCHANGE_CODE]     VARCHAR (12)    NULL,
    [LONG_EXCHANGE_NAME]           VARCHAR (30)    NULL,
    [COUNTRY_FULL_NAME]            VARCHAR (30)    NULL,
    [COUNTRY_ISO_CODE]             VARCHAR (4)     NULL,
    [COUNTRY_OF_DOMICILE]          VARCHAR (4)     NULL,
    [NUMERIC_COUNTRY_CODE]         INT             NULL,
    [SECURITY_NAME]                VARCHAR (30)    NULL,
    [SHORT_NAME]                   VARCHAR (30)    NULL,
    [SECURITY_DESCRIPTION]         VARCHAR (30)    NULL,
    [PARSKEYEABLE_DESCRIPTION]     VARCHAR (30)    NULL,
    [CUSIP_NUMBER]                 VARCHAR (9)     NULL,
    [VALOREN_NUMBER]               VARCHAR (12)    NULL,
    [WERTPAPIER_NUMBER]            VARCHAR (8)     NULL,
    [SECTOR]                       VARCHAR (20)    NULL,
    [MARKET_SECTOR_DESCRIPTION]    VARCHAR (8)     NULL,
    [MARKET_SECTOR_NUMBER]         INT             NULL,
    [CUSTOM_SECTOR_NAME]           VARCHAR (30)    NULL,
    [CUSTOM_SECTOR_GROUP_NAME]     VARCHAR (30)    NULL,
    [TRADING_SYSTEM_INDUSTRY_CODE] DECIMAL (9, 2)  NULL,
    [SECURITY_TYPE]                VARCHAR (30)    NULL,
    [ASSET_TYPE]                   VARCHAR (50)    NULL,
    [MARKET_SECTOR_TWO]            VARCHAR (20)    NULL,
    [SUBSECTOR]                    VARCHAR (20)    NULL,
    [CUSTOM_SECTOR_LEVEL_1_NAME]   VARCHAR (30)    NULL,
    [CUSTOM_SECTOR_LEVEL_2_NAME]   VARCHAR (30)    NULL,
    [CUSTOM_SECTOR_LEVEL_3_NAME]   VARCHAR (30)    NULL,
    [COUNTRY_OF_INCORPORATION]     VARCHAR (4)     NULL,
    [CUSIPIDENTIFIER_NUMBER]       VARCHAR (9)     NULL,
    [SECURITY_IDENTIFIER]          INT             NULL,
    [IRISH_SEDOL_NUMBER]           VARCHAR (8)     NULL,
    [CADIS_SYSTEM_INSERTED]        DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]         DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY]       NVARCHAR (50)   NULL,
    [CADIS_SYSTEM_PRIORITY]        INT             NULL,
    [CADIS Inserted]               DATETIME        NOT NULL,
    [CADIS Updated]                DATETIME        NOT NULL,
    [CADIS Changed By]             NVARCHAR (100)  NOT NULL,
    [CADIS Row Id]                 INT             NOT NULL,
    [CADIS Revision]               INT             NOT NULL
);

