CREATE TABLE [CADIS_PROC].[DC_ENPKGDFILE_PIVPKGD_PREP] (
    [TOPLEVELRUNID]         INT           NOT NULL,
    [FILE_NAME]             VARCHAR (200) NULL,
    [CLIENT]                VARCHAR (200) NULL,
    [ENV]                   VARCHAR (200) NULL,
    [TIME_STAMP]            VARCHAR (200) NULL,
    [STATUS]                VARCHAR (200) NULL,
    [CADIS_SYSTEM_INSERTED] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TOPLEVELRUNID] ASC) WITH (FILLFACTOR = 80)
);

