CREATE TABLE [CADIS_PROC].[DC_ISS_CTR_ISS_PREP] (
    [EDM_SEC_ID]          INT           NOT NULL,
    [UNIQUE_BLOOMBERG_ID] VARCHAR (30)  NOT NULL,
    [Issuer_Name]         VARCHAR (250) NULL,
    [SECURITY_NAME]       VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([UNIQUE_BLOOMBERG_ID] ASC) WITH (FILLFACTOR = 80)
);

