CREATE TABLE [CADIS_PROC].[DC_INPUT131_PROCESSKEYS] (
    [ID_BB_UNIQUE] VARCHAR (50) NOT NULL,
    [PX_DATE]      DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_BB_UNIQUE] ASC, [PX_DATE] ASC)
);

