CREATE TABLE [CADIS_PROC].[DC_INPUT211_PROCESSKEYS] (
    [EDM_SEC_ID] INT          NOT NULL,
    [IDENTIFIER] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [IDENTIFIER] ASC) WITH (FILLFACTOR = 80)
);

