CREATE TABLE [CADIS_PROC].[DC_INPUT118_PROCESSKEYS] (
    [SOURCE]          VARCHAR (50)   NOT NULL,
    [POSITION_TYPE]   VARCHAR (50)   NOT NULL,
    [FUND_SHORT_NAME] VARCHAR (8000) NOT NULL,
    [POSITION_DATE]   DATETIME       NOT NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC)
);

