CREATE TABLE [CADIS_PROC].[DC_INPUT257_PROCESSKEYS] (
    [VALUATION_DATE]  DATETIME     NOT NULL,
    [FUND_SHORT_NAME] VARCHAR (20) NOT NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC) WITH (FILLFACTOR = 80)
);

