CREATE TABLE [CADIS_PROC].[DC_INPUT30_PROCESSKEYS] (
    [SOURCE]          VARCHAR (2)  NOT NULL,
    [POSITION_TYPE]   VARCHAR (8)  NOT NULL,
    [D_VALN_OUT_DATE] DATETIME     NOT NULL,
    [FUND_SHORT_NAME] VARCHAR (15) NOT NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [D_VALN_OUT_DATE] ASC, [FUND_SHORT_NAME] ASC)
);

