CREATE TABLE [CADIS_PROC].[DC_INPUT141_PROCESSKEYS] (
    [ACCOUNT_NUMBER] VARCHAR (50) NOT NULL,
    [CUR_DATE]       DATE         NOT NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [CUR_DATE] ASC)
);

