CREATE TABLE [CADIS_PROC].[DC_INPUT69_PROCESSKEYS] (
    [FUND_SHORT_NAME]  VARCHAR (15)    NOT NULL,
    [THROUGH_DATE]     DATETIME        NOT NULL,
    [NTRANCATG]        VARCHAR (100)   NOT NULL,
    [NET_AMOUNT_BASE]  DECIMAL (38, 6) NOT NULL,
    [RECOGNITION_DATE] DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [THROUGH_DATE] ASC, [NTRANCATG] ASC, [NET_AMOUNT_BASE] ASC, [RECOGNITION_DATE] ASC)
);

