CREATE TABLE [CADIS_PROC].[DC_INPUT119_PROCESSKEYS] (
    [ASSET]           VARCHAR (10) NOT NULL,
    [ORDER_REF]       INT          NOT NULL,
    [VALUATION_POINT] DATETIME     NOT NULL,
    [ESTIMATED?]      BIT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ASSET] ASC, [ORDER_REF] ASC, [VALUATION_POINT] ASC, [ESTIMATED?] ASC)
);

