CREATE TABLE [CADIS_PROC].[DC_ISS_INFO_RUNID] (
    [EDM_ISSUER_ID]                          INT NOT NULL,
    [ID_BB_ULTIMATE_PARENT_CO_NAME__RUNID]   INT NOT NULL,
    [ULT_PARENT_TICKER_EXCHANGE__RUNID]      INT NOT NULL,
    [ULT_PARENT_CNTRY_OF_RISK__RUNID]        INT NOT NULL,
    [ULT_PARENT_CNTRY_DOMICILE__RUNID]       INT NOT NULL,
    [LEI_ULTIMATE_PARENT_COMPANY__RUNID]     INT NOT NULL,
    [ID_BB_GLOBAL_ULTIMATE_PARENT_CO__RUNID] INT NOT NULL,
    [ULT_PARENT_CNTRY_INCORPORATION__RUNID]  INT NOT NULL,
    [COMPANYTYPE__RUNID]                     INT NOT NULL,
    [SALESFORCE_ACCOUNT_ID__RUNID]           INT NOT NULL,
    [BOXFOLDERID__RUNID]                     INT NOT NULL,
    [FUNDMANAGERPERSONID__RUNID]             INT NOT NULL,
    [INVESTMENTANALYSTPERSONID__RUNID]       INT NOT NULL,
    [JIRAEPICKEY__RUNID]                     INT NOT NULL,
    [FILE_NAME__RUNID]                       INT NOT NULL,
    [FILE_DATE__RUNID]                       INT NOT NULL,
    [COMPANY_NUMBER__RUNID]                  INT NOT NULL,
    [IsActive__RUNID]                        INT NOT NULL,
    PRIMARY KEY CLUSTERED ([EDM_ISSUER_ID] ASC) WITH (FILLFACTOR = 80)
);

