CREATE TABLE [CADIS_PROC].[DC_INPUT12_PROCESSKEYS] (
    [DATE]           DATETIME     NOT NULL,
    [EXCEPTION_CODE] INT          NOT NULL,
    [SOURCE_COLUMN]  VARCHAR (50) NOT NULL,
    [SOURCE_KEY]     VARCHAR (50) NOT NULL,
    [SOURCE_TABLE]   VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([DATE] ASC, [EXCEPTION_CODE] ASC, [SOURCE_COLUMN] ASC, [SOURCE_KEY] ASC, [SOURCE_TABLE] ASC)
);

