CREATE TABLE [CADIS_PROC].[DC_INPUT178_PROCESSKEYS] (
    [STOCK]  VARCHAR (20) NOT NULL,
    [ROW_ID] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([STOCK] ASC, [ROW_ID] ASC) WITH (FILLFACTOR = 80)
);

