CREATE TABLE [CADIS_PROC].[DC_INPUT22_PROCESSKEYS] (
    [TRADE_DATE]          DATETIME        NOT NULL,
    [POSITION]            DECIMAL (15, 2) NOT NULL,
    [ACCOUNT]             VARCHAR (15)    NOT NULL,
    [PRICE]               DECIMAL (18, 2) NOT NULL,
    [UNIQUE_BLOOMBERG_ID] VARCHAR (20)    NOT NULL,
    PRIMARY KEY CLUSTERED ([TRADE_DATE] ASC, [POSITION] ASC, [ACCOUNT] ASC, [PRICE] ASC, [UNIQUE_BLOOMBERG_ID] ASC)
);

