CREATE TABLE [CADIS_PROC].[DC_INPUT42_PROCESSKEYS] (
    [SOURCE]         VARCHAR (50)    NOT NULL,
    [POSITION_TYPE]  VARCHAR (50)    NOT NULL,
    [EDM_SEC_ID]     INT             NOT NULL,
    [LONG_SHORT_IND] VARCHAR (8)     NOT NULL,
    [POSITION_DATE]  DATETIME        NOT NULL,
    [QUANTITY]       DECIMAL (20, 6) NOT NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [EDM_SEC_ID] ASC, [LONG_SHORT_IND] ASC, [POSITION_DATE] ASC, [QUANTITY] ASC)
);

