CREATE TABLE [CADIS_PROC].[DC_INPUT81_PROCESSKEYS] (
    [FUND_SHORT_NAME]  VARCHAR (15)  NOT NULL,
    [TRANSACTION_DATE] DATETIME      NOT NULL,
    [FLOW_TYPE]        VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [FLOW_TYPE] ASC)
);

