CREATE TABLE [CADIS_PROC].[DC_INPUT256_PROCESSKEYS] (
    [VALUATION_DATE]  DATETIME     NOT NULL,
    [FUND_SHORT_NAME] VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]      INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);

