CREATE TABLE [CADIS_PROC].[DC_INPUT142_PROCESSKEYS] (
    [CUR_DATE]       DATE         NOT NULL,
    [ACCOUNT_NUMBER] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([CUR_DATE] ASC, [ACCOUNT_NUMBER] ASC)
);

