CREATE TABLE [CADIS_PROC].[DC_INPUT80_PROCESSKEYS] (
    [TRANSACTION_DATE] DATETIME      NOT NULL,
    [FLOW_TYPE]        VARCHAR (100) NOT NULL,
    [FUND_SHORT_NAME]  VARCHAR (50)  NOT NULL,
    [SOURCE_TYPE]      VARCHAR (11)  NOT NULL,
    PRIMARY KEY CLUSTERED ([TRANSACTION_DATE] ASC, [FLOW_TYPE] ASC, [FUND_SHORT_NAME] ASC, [SOURCE_TYPE] ASC)
);

