CREATE TABLE [CADIS_PROC].[DC_INPUT78_PROCESSKEYS] (
    [FUND_SHORT_NAME]  VARCHAR (15)    NOT NULL,
    [RECOGNITION_DATE] DATETIME        NOT NULL,
    [FLOW_TYPE]        VARCHAR (100)   NOT NULL,
    [NET_AMOUNT_BASE]  DECIMAL (38, 6) NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [RECOGNITION_DATE] ASC, [FLOW_TYPE] ASC, [NET_AMOUNT_BASE] ASC)
);

