CREATE TABLE [CADIS_PROC].[DC_INPUT113_PROCESSKEYS] (
    [EDM_SEC_ID] INT          NOT NULL,
    [PRICE_TYPE] VARCHAR (50) NOT NULL,
    [PRICE_DATE] DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [PRICE_TYPE] ASC, [PRICE_DATE] ASC)
);

