CREATE TABLE [CADIS_PROC].[DC_INPUT151_PROCESSKEYS] (
    [SOURCE_TABLE]   VARCHAR (50) NOT NULL,
    [SOURCE_KEY]     VARCHAR (50) NOT NULL,
    [SOURCE_COLUMN]  VARCHAR (50) NOT NULL,
    [EXCEPTION_CODE] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC)
);

