CREATE TABLE [CADIS_PROC].[DC_OWNTEISS_INFO_RULE] (
    [VALUATION_DATE]                     DATETIME     NOT NULL,
    [FUND_SHORT_NAME]                    VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]                         INT          NOT NULL,
    [FUND_FISCAL_YEAR]                   INT          NOT NULL,
    [FUND_FISCAL_QUARTER]                INT          NOT NULL,
    [ACCOUNT_NUMBER__RULEID]             INT          NULL,
    [SECURITY_NUMBER__RULEID]            INT          NULL,
    [SECURITY_DESCRIPTION__RULEID]       INT          NULL,
    [SEDOL__RULEID]                      INT          NULL,
    [CUSIP__RULEID]                      INT          NULL,
    [COUNTRY_OF_TAXATION__RULEID]        INT          NULL,
    [STATE_CODE__RULEID]                 INT          NULL,
    [ASSET_GROUP__RULEID]                INT          NULL,
    [EX_DATE_SHARES__RULEID]             INT          NULL,
    [EX_DATE__RULEID]                    INT          NULL,
    [ACCRUED_INCOME__RULEID]             INT          NULL,
    [INCOME_RECEIVED__RULEID]            INT          NULL,
    [PRIOR_INC_ACCRUED__RULEID]          INT          NULL,
    [INCOME_EARNED__RULEID]              INT          NULL,
    [AMORT_ACCRUED__RULEID]              INT          NULL,
    [AMORT_SOLD__RULEID]                 INT          NULL,
    [PRIOR_AMORT_ACCRUED__RULEID]        INT          NULL,
    [AMORT_EARNED__RULEID]               INT          NULL,
    [TOTAL_INC_AND_AMORT_EARNED__RULEID] INT          NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC, [FUND_FISCAL_QUARTER] ASC) WITH (FILLFACTOR = 80)
);

