CREATE TABLE [CADIS_PROC].[DC_OWNTEISS_CBUF] (
    [VALUATION_DATE]      DATETIME     NOT NULL,
    [FUND_SHORT_NAME]     VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]          INT          NOT NULL,
    [FUND_FISCAL_YEAR]    INT          NOT NULL,
    [FUND_FISCAL_QUARTER] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC, [FUND_FISCAL_QUARTER] ASC) WITH (FILLFACTOR = 80)
);

