CREATE TABLE [CADIS_PROC].[DC_OWNTSCPS_INFO_RUNID] (
    [ID]                                INT NOT NULL,
    [EDM_SHARECLASS_ID__RUNID]          INT NOT NULL,
    [VALUATION_DATE__RUNID]             INT NOT NULL,
    [SHARE_CLASS_NAME__RUNID]           INT NOT NULL,
    [ISIN__RUNID]                       INT NOT NULL,
    [XD__RUNID]                         INT NOT NULL,
    [EXIT_CHARGE_PERCENT__RUNID]        INT NOT NULL,
    [INITIAL_CHARGE_PERCENT__RUNID]     INT NOT NULL,
    [MID_PRICE__RUNID]                  INT NOT NULL,
    [PRICE_CHANGE__RUNID]               INT NOT NULL,
    [PRICE_MOVE_PERCENT__RUNID]         INT NOT NULL,
    [INITIAL_CHARGE__RUNID]             INT NOT NULL,
    [HISTORIC_YIELD_PERCENT__RUNID]     INT NOT NULL,
    [DISTRIBUTION_YIELD_PERCENT__RUNID] INT NOT NULL,
    [UNDERLYING_YIELD_PERCENT__RUNID]   INT NOT NULL,
    [EQUALISATION_RATE__RUNID]          INT NOT NULL,
    [UNITS_IN_ISSUE__RUNID]             INT NOT NULL,
    [FUND_VALUE__RUNID]                 INT NOT NULL,
    [CURRENCY__RUNID]                   INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

