CREATE TABLE [CADIS_PROC].[DC_OWNTEISTG_MST_FND_PREP] (
    [ACCOUNT_NUMBER]               VARCHAR (50) NOT NULL,
    [FUND_SHORT_NAME]              VARCHAR (20) NOT NULL,
    [INCOME_PERIOD_QUARTER_OFFSET] INT          NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 80)
);

