CREATE TABLE [CADIS_PROC].[DC_OWNTEIFS_INFO_RUNID] (
    [VALUATION_DATE]         DATETIME     NOT NULL,
    [FUND_SHORT_NAME]        VARCHAR (20) NOT NULL,
    [UNITS__RUNID]           INT          NOT NULL,
    [FUND_NET_INCOME__RUNID] INT          NOT NULL,
    [RATE__RUNID]            INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC) WITH (FILLFACTOR = 80)
);

