CREATE TABLE [CADIS_PROC].[DC_OVSTAMO_AUDIT] (
    [SfAccountId]            VARCHAR (18)   NOT NULL,
    [Sector]                 VARCHAR (10)   NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([SfAccountId] ASC, [Sector] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC) WITH (FILLFACTOR = 80)
);

