CREATE TABLE [CADIS_PROC].[DC_OWNTSCPS_M_SHR_CLS_PREP] (
    [EDM_SHARE_CLASS_ID]     INT           NOT NULL,
    [ISIN]                   VARCHAR (12)  NULL,
    [SEDOL]                  VARCHAR (7)   NULL,
    [FUND_SHORT_NAME]        VARCHAR (20)  NOT NULL,
    [SHARE_CLASS_SHORT_NAME] VARCHAR (20)  NULL,
    [SHARE_CLASS_LONG_NAME]  VARCHAR (100) NULL,
    [SHARE_CLASS_CURRENCY]   VARCHAR (3)   NOT NULL,
    [VALUATION_PERIOD]       VARCHAR (20)  NULL,
    [INCEPTION_DATE]         DATE          NULL,
    [IS_ACCUMULATION]        BIT           NULL,
    [IS_INCOME]              BIT           NULL,
    [IS_ACTIVE]              BIT           NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL
);

