CREATE TABLE [CADIS_PROC].[DC_OWNTEIFS_INFO_RULE] (
    [VALUATION_DATE]          DATETIME     NOT NULL,
    [FUND_SHORT_NAME]         VARCHAR (20) NOT NULL,
    [UNITS__RULEID]           INT          NULL,
    [FUND_NET_INCOME__RULEID] INT          NULL,
    [RATE__RULEID]            INT          NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC) WITH (FILLFACTOR = 80)
);

