CREATE TABLE [CADIS_PROC].[DC_PMFFLOW_MLFF_PREP] (
    [FILE_NAME]              VARCHAR (20)    NULL,
    [FILE_TYPE]              VARCHAR (20)    NULL,
    [FILE_DATE]              DATETIME        NULL,
    [FUND_SHORT_NAME]        VARCHAR (15)    NOT NULL,
    [PORTFOLIO_NAME]         VARCHAR (100)   NULL,
    [CURRENCY]               VARCHAR (3)     NOT NULL,
    [FUND_FLOW_TYPE]         VARCHAR (20)    NOT NULL,
    [FLOW_TYPE]              VARCHAR (100)   NOT NULL,
    [AMOUNT]                 DECIMAL (18, 2) NULL,
    [TRADE_DATE]             DATETIME        NOT NULL,
    [VALUE_DATE]             DATETIME        NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [CURRENCY] ASC, [FUND_FLOW_TYPE] ASC, [FLOW_TYPE] ASC, [TRADE_DATE] ASC) WITH (FILLFACTOR = 80)
);

