CREATE TABLE [CADIS_PROC].[DC_PREMASSEC_PRICECCY_PREP] (
    [EDM_SEC_ID]    INT         NOT NULL,
    [PRICE_ISO_CCY] VARCHAR (3) NULL,
    [PRICE_DATE]    DATETIME    NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);

