CREATE TABLE [CADIS_PROC].[DC_PMFFLOW_INFO_RUNID] (
    [FUND_SHORT_NAME]        VARCHAR (15)  NOT NULL,
    [TRANSACTION_DATE]       DATETIME      NOT NULL,
    [CURRENCY]               VARCHAR (20)  NOT NULL,
    [FUND_FLOW_TYPE]         VARCHAR (20)  NOT NULL,
    [FLOW_TYPE]              VARCHAR (100) NOT NULL,
    [SOURCE_TYPE]            VARCHAR (20)  DEFAULT ('CONFIRMED') NOT NULL,
    [MARKET_VALUE__RUNID]    INT           NOT NULL,
    [SETTLEMENT_DATE__RUNID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [CURRENCY] ASC, [FUND_FLOW_TYPE] ASC, [FLOW_TYPE] ASC, [SOURCE_TYPE] ASC)
);

