CREATE TABLE [CADIS_PROC].[DC_PREMASSEC_INFO_RULE] (
    [EDM_SEC_ID]                             INT NOT NULL,
    [SECURITY_NAME__RULEID]                  INT NULL,
    [SECURITY_DESCRIPTION__RULEID]           INT NULL,
    [SECURITY_SHORTNAME__RULEID]             INT NULL,
    [ASSET_TYPE__RULEID]                     INT NULL,
    [SECURITY_TYPE__RULEID]                  INT NULL,
    [CUSIP__RULEID]                          INT NULL,
    [ISIN__RULEID]                           INT NULL,
    [SEDOL__RULEID]                          INT NULL,
    [TICKER__RULEID]                         INT NULL,
    [VALOREN__RULEID]                        INT NULL,
    [WERTPAPIER__RULEID]                     INT NULL,
    [SECURITY_ISO_CCY__RULEID]               INT NULL,
    [RISK_ISO_CCY__RULEID]                   INT NULL,
    [FIXED_ISO_CCY__RULEID]                  INT NULL,
    [INCORPORATION_ISO_CTY__RULEID]          INT NULL,
    [DOMICILE_ISO_CTY__RULEID]               INT NULL,
    [ISSUE_COUNTRY_ISO__RULEID]              INT NULL,
    [RISK_ISO_CTY__RULEID]                   INT NULL,
    [MIC_EXCHANGE_CODE__RULEID]              INT NULL,
    [STATE_CODE__RULEID]                     INT NULL,
    [ACTIVE_TRADE_INDICATOR__RULEID]         INT NULL,
    [144A_INDICATOR__RULEID]                 INT NULL,
    [PRIVATE_PLACEMENT_INDICATOR__RULEID]    INT NULL,
    [ILLIQUID__RULEID]                       INT NULL,
    [QUOTE_TYPE__RULEID]                     INT NULL,
    [DAYS_TO_SETTLE__RULEID]                 INT NULL,
    [TRADE_SETTLEMENT_CALENDAR_CODE__RULEID] INT NULL,
    [UNIQUE_BLOOMBERG_ID__RULEID]            INT NULL,
    [BBG_EXCHANGE_CODE__RULEID]              INT NULL,
    [BBG_SECTOR__RULEID]                     INT NULL,
    [BBG_SUBSECTOR__RULEID]                  INT NULL,
    [BBG_GROUP__RULEID]                      INT NULL,
    [IS_IPO__RULEID]                         INT NULL,
    [PARSEKEYABLE_DESCRIPTION__RULEID]       INT NULL,
    [SECURITY_IDENTIFIER__RULEID]            INT NULL,
    [IRISH_SEDOL_NUMBER__RULEID]             INT NULL,
    [ISSUER__RULEID]                         INT NULL,
    [CUR_MAR_CAP__RULEID]                    INT NULL,
    [PRIMARY_EXCHANGE_NAME__RULEID]          INT NULL,
    [SECURITY_HAS_ADRS__RULEID]              INT NULL,
    [WITHHOLDING_TAX__RULEID]                INT NULL,
    [VOL_AVG_5D__RULEID]                     INT NULL,
    [VOL_AVG_20D__RULEID]                    INT NULL,
    [EDM_ISSUER_ID__RULEID]                  INT NULL,
    [ADV_TOTAL_VOLUME__RULEID]               INT NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC)
);

