CREATE TABLE [CADIS_PROC].[DC_UPPREMSTIN_MST_PRC_PREP] (
    [EDM_SEC_ID] INT              NOT NULL,
    [PRICE_DATE] DATE             NULL,
    [BID_PRICE]  DECIMAL (24, 10) NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);

