CREATE TABLE [CADIS_PROC].[DC_UPDTEXCEPT_STAGE_PREP] (
    [DATE]                      DATETIME       NOT NULL,
    [SOURCE_TABLE]              VARCHAR (50)   NOT NULL,
    [SOURCE_KEY]                VARCHAR (50)   NOT NULL,
    [SOURCE_COLUMN]             VARCHAR (50)   NOT NULL,
    [EXCEPTION_CODE]            INT            NOT NULL,
    [PROCESS_STATUS]            VARCHAR (2)    NULL,
    [ENTITY]                    VARCHAR (40)   NULL,
    [SOURCE]                    VARCHAR (50)   NULL,
    [SOURCE_COMPONENT]          VARCHAR (500)  NULL,
    [EDM_ENTITY_ID]             INT            NULL,
    [SOURCE_VALUE]              VARCHAR (1000) NULL,
    [DATA_A_TYPE]               VARCHAR (100)  NOT NULL,
    [DATA_A_VALUE]              VARCHAR (1000) NULL,
    [DATA_B_TYPE]               VARCHAR (100)  NULL,
    [DATA_B_VALUE]              VARCHAR (1000) NULL,
    [DATA_C_TYPE]               VARCHAR (100)  NULL,
    [DATA_C_VALUE]              VARCHAR (1000) NULL,
    [ISIN]                      VARCHAR (20)   NULL,
    [SEDOL]                     VARCHAR (20)   NULL,
    [CUSIP]                     VARCHAR (20)   NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME       NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME       NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)  NULL,
    [CADIS_SYSTEM_PRIORITY]     INT            NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC) WITH (FILLFACTOR = 80)
);

