CREATE TABLE [CADIS_PROC].[DC_UPDTHWPOS_AUDIT] (
    [MODEL_CODE]             VARCHAR (20)   NOT NULL,
    [INSTRUMENT_UII]         VARCHAR (12)   NOT NULL,
    [CURRENT_DATE]           DATETIME       NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([MODEL_CODE] ASC, [INSTRUMENT_UII] ASC, [CURRENT_DATE] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC) WITH (FILLFACTOR = 80)
);

