CREATE TABLE [CADIS_PROC].[DC_UPPMFI_CBUF] (
    [FUND_SHORT_NAME] VARCHAR (20) NOT NULL,
    [VALUATION_DATE]  DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [VALUATION_DATE] ASC) WITH (FILLFACTOR = 80)
);

