CREATE TABLE [CADIS_PROC].[DC_UPNTDVDIRR_EIARPT_PREP] (
    [CUR_DATE]               DATE          NULL,
    [DATE]                   DATETIME      NOT NULL,
    [ACCOUNT_NUMBER]         VARCHAR (50)  NOT NULL,
    [SEC_DESCRIPTION]        VARCHAR (50)  NULL,
    [CUSIP]                  VARCHAR (20)  NULL,
    [SEDOL]                  VARCHAR (20)  NULL,
    [CTRY_OF_TAXATION]       VARCHAR (5)   NULL,
    [TOTAL_INC_AMORT_EARNED] VARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([DATE] ASC, [ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 80)
);

