CREATE TABLE [CADIS_PROC].[DC_UPMSTFNDMK_RESET_PREP] (
    [SOURCE]                          VARCHAR (50)   NOT NULL,
    [POSITION_TYPE]                   VARCHAR (50)   NOT NULL,
    [FUND_SHORT_NAME]                 VARCHAR (8000) NOT NULL,
    [POSITION_DATE]                   DATETIME       NOT NULL,
    [TOTAL_MARKET_VALUE_LOCAL]        BIT            NULL,
    [TOTAL_MARKET_VALUE_BASE]         BIT            NULL,
    [STATUS]                          BIT            NULL,
    [TOTAL_ACCRUED_MARKET_VALUE_BASE] BIT            NULL,
    [CADIS_SYSTEM_INSERTED]           DATETIME       NULL,
    [CADIS_SYSTEM_UPDATED]            DATETIME       NULL,
    [CADIS_SYSTEM_CHANGEDBY]          NVARCHAR (50)  NULL,
    [CADIS_SYSTEM_PRIORITY]           INT            NULL,
    [CADIS_SYSTEM_LASTMODIFIED]       DATETIME       NULL,
    [CADIS_SYSTEM_TIMESTAMP]          ROWVERSION     NOT NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC) WITH (FILLFACTOR = 80)
);

