CREATE TABLE [CADIS_PROC].[DC_UPMSI_INFO_RUNID] (
    [FUND_SHORT_NAME]         VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]              INT          NOT NULL,
    [FUND_FISCAL_YEAR]        INT          NOT NULL,
    [POSITION_DATE__RUNID]    INT          NOT NULL,
    [DVD_CCY__RUNID]          INT          NOT NULL,
    [WITHHOLDING_TAX__RUNID]  INT          NOT NULL,
    [DECLARED_DATE__RUNID]    INT          NOT NULL,
    [POSITION__RUNID]         INT          NOT NULL,
    [MID_PRICE__RUNID]        INT          NOT NULL,
    [SPOT_RATE__RUNID]        INT          NOT NULL,
    [MARKET_VALUE__RUNID]     INT          NOT NULL,
    [Q1_EX_DATE__RUNID]       INT          NOT NULL,
    [Q1_RATE__RUNID]          INT          NOT NULL,
    [Q1_EARNED_INCOME__RUNID] INT          NOT NULL,
    [Q1_TO_PAY__RUNID]        INT          NOT NULL,
    [Q1_NET_INCOME__RUNID]    INT          NOT NULL,
    [Q1_NOTE__RUNID]          INT          NOT NULL,
    [Q2_EX_DATE__RUNID]       INT          NOT NULL,
    [Q2_RATE__RUNID]          INT          NOT NULL,
    [Q2_EARNED_INCOME__RUNID] INT          NOT NULL,
    [Q2_TO_PAY__RUNID]        INT          NOT NULL,
    [Q2_NET_INCOME__RUNID]    INT          NOT NULL,
    [Q2_NOTE__RUNID]          INT          NOT NULL,
    [Q3_EX_DATE__RUNID]       INT          NOT NULL,
    [Q3_RATE__RUNID]          INT          NOT NULL,
    [Q3_EARNED_INCOME__RUNID] INT          NOT NULL,
    [Q3_TO_PAY__RUNID]        INT          NOT NULL,
    [Q3_NET_INCOME__RUNID]    INT          NOT NULL,
    [Q3_NOTE__RUNID]          INT          NOT NULL,
    [Q4_EX_DATE__RUNID]       INT          NOT NULL,
    [Q4_RATE__RUNID]          INT          NOT NULL,
    [Q4_EARNED_INCOME__RUNID] INT          NOT NULL,
    [Q4_TO_PAY__RUNID]        INT          NOT NULL,
    [Q4_NET_INCOME__RUNID]    INT          NOT NULL,
    [Q4_NOTE__RUNID]          INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC) WITH (FILLFACTOR = 80)
);

