CREATE TABLE [CADIS_PROC].[DC_UPPKGDARP_INFO_RULE] (
    [TOPLEVELRUNID]         INT NOT NULL,
    [FILE_NAME__RULEID]     INT NULL,
    [CLIENT__RULEID]        INT NULL,
    [ENV__RULEID]           INT NULL,
    [TIME_STAMP__RULEID]    INT NULL,
    [STATUS__RULEID]        INT NULL,
    [STATUS_DECODE__RULEID] INT NULL,
    [PATH__RULEID]          INT NULL,
    PRIMARY KEY CLUSTERED ([TOPLEVELRUNID] ASC) WITH (FILLFACTOR = 80)
);

