CREATE TABLE [CADIS_PROC].[DC_UPNTDVDIRR_AUDIT] (
    [ACCOUNT_NUMBER]         VARCHAR (50)   NOT NULL,
    [DATE]                   DATETIME       NOT NULL,
    [SEC_DESCRIPTION]        VARCHAR (50)   NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [DATE] ASC, [SEC_DESCRIPTION] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC)
);

