CREATE TABLE [CADIS_PROC].[DC_UPPMSI_CBUF] (
    [FUND_SHORT_NAME]  VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]       INT          NOT NULL,
    [FUND_FISCAL_YEAR] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC) WITH (FILLFACTOR = 80)
);

