CREATE TABLE [CADIS_PROC].[DC_UPMASSECDR_RESET_PREP] (
    [EDM_SEC_ID]               INT           NOT NULL,
    [OPTION_ROOT_TICKER]       BIT           NULL,
    [PUT_CALL_INDICATOR]       BIT           NULL,
    [EXPIRY_DATE]              BIT           NULL,
    [FUTURE_EXPIRY_MONTH_YEAR] BIT           NULL,
    [EXERCISE_TYPE]            BIT           NULL,
    [CONTRACT_SIZE]            BIT           NULL,
    [CONTRACT_VALUE]           BIT           NULL,
    [FUTURE_TYPE]              BIT           NULL,
    [LAST_TRADE_DATE]          BIT           NULL,
    [LONG_EXCHANGE_NAME]       BIT           NULL,
    [DELTA]                    BIT           NULL,
    [GAMMA]                    BIT           NULL,
    [THETA]                    BIT           NULL,
    [VEGA]                     BIT           NULL,
    [EURO_FUTURE_INDICATOR]    BIT           NULL,
    [CONVERSION_FACTOR]        BIT           NULL,
    [CTD_CONVERSION_DURATION]  BIT           NULL,
    [CTD_ISIN]                 BIT           NULL,
    [CTD_SEDOL]                BIT           NULL,
    [CTD_RISK_TYPE]            BIT           NULL,
    [FUTURE_DAYS_TO_EXPIRY]    BIT           NULL,
    [FUTURE_LONGNAME]          BIT           NULL,
    [STRIKE_PRICE]             BIT           NULL,
    [TICK_SIZE]                BIT           NULL,
    [CADIS_SYSTEM_INSERTED]    DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]     DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY]   NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]    INT           NULL,
    [CADIS_SYSTEM_TIMESTAMP]   ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);

