CREATE TABLE [CADIS_PROC].[DC_UPMSTPOS_INFO_RULE] (
    [SOURCE]           VARCHAR (50) NOT NULL,
    [POSITION_TYPE]    VARCHAR (50) NOT NULL,
    [EDM_SEC_ID]       INT          NOT NULL,
    [FUND_SHORT_NAME]  VARCHAR (15) NOT NULL,
    [LONG_SHORT_IND]   VARCHAR (8)  NOT NULL,
    [POSITION_DATE]    DATETIME     NOT NULL,
    [QUANTITY__RULEID] INT          NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [EDM_SEC_ID] ASC, [FUND_SHORT_NAME] ASC, [LONG_SHORT_IND] ASC, [POSITION_DATE] ASC)
);

