CREATE TABLE [CADIS_PROC].[DC_UPMSFFLOW_PREMASTER_PREP] (
    [FUND_SHORT_NAME]           VARCHAR (15)    NOT NULL,
    [TRANSACTION_DATE]          DATETIME        NOT NULL,
    [FLOW_TYPE]                 VARCHAR (100)   NOT NULL,
    [MARKET_VALUE]              DECIMAL (20, 6) NULL,
    [RECOGNITION_DATE]          DATETIME        NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [FLOW_TYPE] ASC, [RECOGNITION_DATE] ASC)
);

