CREATE TABLE [CADIS_PROC].[DC_UPPRENFF_INFO_RULE] (
    [FILE_NAME__RULEID]                                     INT             NULL,
    [FILE_TYPE__RULEID]                                     INT             NULL,
    [FILE_DATE__RULEID]                                     INT             NULL,
    [NUMBER_OF_RECORDS__RULEID]                             INT             NULL,
    [CONSOLIDATION__RULEID]                                 INT             NULL,
    [ACCOUNT_NUMBER]                                        VARCHAR (50)    NOT NULL,
    [FUND_SHORT_NAME__RULEID]                               INT             NULL,
    [FROM_DATE__RULEID]                                     INT             NULL,
    [THROUGH_DATE__RULEID]                                  INT             NULL,
    [TASTDESCMED__RULEID]                                   INT             NULL,
    [TNARRLONG]                                             VARCHAR (255)   NOT NULL,
    [ABASBSE__RULEID]                                       INT             NULL,
    [NET_AMOUNT__BASE]                                      DECIMAL (20, 6) NOT NULL,
    [AMKTVAL__RULEID]                                       INT             NULL,
    [ARLSDGAIN__RULEID]                                     INT             NULL,
    [AEXCHGNLS__RULEID]                                     INT             NULL,
    [RECOGNITION_DATE]                                      DATETIME        NOT NULL,
    [NTRANCATG]                                             VARCHAR (100)   NOT NULL,
    [ASSET_IDENTIFIER__RULEID]                              INT             NULL,
    [CTEMPLTYPE__RULEID]                                    INT             NULL,
    [CVALNTYPEO__RULEID]                                    INT             NULL,
    [TSHAREPAR__RULEID]                                     INT             NULL,
    [REVERSAL_INDICATOR__RULEID]                            INT             NULL,
    [ALOTCOSTGNLS__RULEID]                                  INT             NULL,
    [DTRANPROC__RULEID]                                     INT             NULL,
    [CSORTCDE3__RULEID]                                     INT             NULL,
    [ERROR_CODE__RULEID]                                    INT             NULL,
    [CONSOLIDATION_AUDIT_INDICATOR_FLAG__RULEID]            INT             NULL,
    [IEXTLREF]                                              VARCHAR (50)    NOT NULL,
    [CASSETLIAB__RULEID]                                    INT             NULL,
    [ACCRUED_INTEREST__RULEID]                              INT             NULL,
    [DSET__RULEID]                                          INT             NULL,
    [ACCRUAL_CHANGE_FROM_SECURITY_MOVEMENTS_OFFSET__RULEID] INT             NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [TNARRLONG] ASC, [NET_AMOUNT__BASE] ASC, [RECOGNITION_DATE] ASC, [NTRANCATG] ASC, [IEXTLREF] ASC)
);

