CREATE TABLE [CADIS_PROC].[DC_UPPMSI_NT_PREP] (
    [FUND_SHORT_NAME]  VARCHAR (20)    NOT NULL,
    [EDM_SEC_ID]       INT             NOT NULL,
    [FUND_FISCAL_YEAR] INT             NOT NULL,
    [VALUATION_DATE]   DATETIME        NULL,
    [Q1_INCOME_EARNED] DECIMAL (18, 4) NULL,
    [Q2_INCOME_EARNED] DECIMAL (18, 4) NULL,
    [Q3_INCOME_EARNED] DECIMAL (18, 4) NULL,
    [Q4_INCOME_EARNED] DECIMAL (18, 4) NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC) WITH (FILLFACTOR = 80)
);

