CREATE TABLE [CADIS_PROC].[DC_UPPMSCV_INFO_RULE] (
    [EDM_SHARECLASS_ID]                  INT      NOT NULL,
    [VALUATION_DATE]                     DATETIME NOT NULL,
    [EXIT_CHARGE_PERCENT__RULEID]        INT      NULL,
    [INITIAL_CHARGE_PERCENT__RULEID]     INT      NULL,
    [MID_PRICE__RULEID]                  INT      NULL,
    [PRICE_CHANGE__RULEID]               INT      NULL,
    [PRICE_MOVE_PERCENT__RULEID]         INT      NULL,
    [INITIAL_CHARGE__RULEID]             INT      NULL,
    [HISTORIC_YIELD_PERCENT__RULEID]     INT      NULL,
    [DISTRIBUTION_YIELD_PERCENT__RULEID] INT      NULL,
    [UNDERLYING_YIELD_PERCENT__RULEID]   INT      NULL,
    [EQUALISATION_RATE__RULEID]          INT      NULL,
    [UNITS_IN_ISSUE__RULEID]             INT      NULL,
    [FUND_VALUE__RULEID]                 INT      NULL,
    PRIMARY KEY CLUSTERED ([EDM_SHARECLASS_ID] ASC, [VALUATION_DATE] ASC) WITH (FILLFACTOR = 80)
);

