CREATE TABLE [CADIS_PROC].[DC_UPMASDIPS_EXPIRY_PREP] (
    [ASSET]                       VARCHAR (10)  NOT NULL,
    [ASSET_NAME]                  DATETIME      NULL,
    [I/A]                         DATETIME      NULL,
    [SUB_FUND]                    DATETIME      NULL,
    [SUB_FUND_NAME]               DATETIME      NULL,
    [DEALING_PERIOD_ID]           DATETIME      NULL,
    [ORDER_DATE]                  DATETIME      NULL,
    [ORDER_REF]                   INT           NOT NULL,
    [MAIN_OWNER]                  DATETIME      NULL,
    [MAIN_OWNER_NAME]             DATETIME      NULL,
    [TYPE]                        DATETIME      NULL,
    [STATUS]                      VARCHAR (40)  NULL,
    [DEAL_CLASS]                  DATETIME      NULL,
    [UNITS/SHARES]                DATETIME      NULL,
    [CCY]                         DATETIME      NULL,
    [VALUE]                       DATETIME      NULL,
    [PLAN_ID]                     DATETIME      NULL,
    [DESIGNATION]                 DATETIME      NULL,
    [PRODUCT_NAME]                DATETIME      NULL,
    [DESCRIPTION]                 DATETIME      NULL,
    [AGENT]                       DATETIME      NULL,
    [AGENT_NAME]                  DATETIME      NULL,
    [ADMIN_FEE_%]                 DATETIME      NULL,
    [CREATION_PLUS_%]             DATETIME      NULL,
    [INITIAL_CHARGE_%]            DATETIME      NULL,
    [FEE_DISCOUNT_%]              DATETIME      NULL,
    [PRICE_DISCOUNT_%]            DATETIME      NULL,
    [COMMISSION_%]                DATETIME      NULL,
    [COMMISSION_VALUE]            DATETIME      NULL,
    [COMMISSION_WAIVER_%]         DATETIME      NULL,
    [RENEWAL_COMMISSION_%]        DATETIME      NULL,
    [PRICE_TYPE]                  DATETIME      NULL,
    [VALUATION_POINT]             DATETIME      NOT NULL,
    [PRICING_DEALING_PERIOD_ID]   DATETIME      NULL,
    [DEAL_TYPE]                   DATETIME      NULL,
    [CONTRACT_NOTE_COMMENTS]      DATETIME      NULL,
    [FX_REQD?]                    DATETIME      NULL,
    [FX_CONFIRMED?]               DATETIME      NULL,
    [FX_INSTRUCTION]              DATETIME      NULL,
    [INDICATIVE_FX_RATE]          DATETIME      NULL,
    [CONFIRMED/SPOT_RATE]         DATETIME      NULL,
    [SETTLEMENT_CCY]              DATETIME      NULL,
    [SETTLEMENT_AMT]              DATETIME      NULL,
    [DL_%]                        DATETIME      NULL,
    [DL_AMOUNT]                   DATETIME      NULL,
    [EXEMPT?]                     DATETIME      NULL,
    [ESTIMATED?]                  BIT           NOT NULL,
    [EXTERNAL?]                   DATETIME      NULL,
    [IN_SPECIE]                   DATETIME      NULL,
    [US_WITHHOLDING_TAX]          DATETIME      NULL,
    [QUOTED_PRICE]                DATETIME      NULL,
    [DEAL_PRICE]                  DATETIME      NULL,
    [PRICE_ADJUSTMENT]            DATETIME      NULL,
    [%_OF_FUND_VALUE]             DATETIME      NULL,
    [COUNT]                       DATETIME      NULL,
    [DEALING_PERIOD_CLOSE_DATE]   DATETIME      NULL,
    [DEALING_PERIOD_CUT_OFF_DATE] DATETIME      NULL,
    [CUT_OFF_OVERRIDDEN]          DATETIME      NULL,
    [EXTERNAL_SOURCE]             DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]       DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]        DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY]      NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]       INT           NULL,
    [CADIS_SYSTEM_LASTMODIFIED]   DATETIME      NULL,
    [CADIS_SYSTEM_TIMESTAMP]      ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([ASSET] ASC, [ORDER_REF] ASC, [VALUATION_POINT] ASC, [ESTIMATED?] ASC) WITH (FILLFACTOR = 80)
);

