CREATE TABLE [CADIS_PROC].[DC_UPPREACCBA_NTACCBAL_PREP] (
    [ACCOUNT_NUMBER]         VARCHAR (20)    NOT NULL,
    [ACCOUNT_NAME]           VARCHAR (100)   NULL,
    [VALUATION_DATE]         DATETIME        NOT NULL,
    [ASSET_SUB_CATEGORY]     VARCHAR (100)   NOT NULL,
    [CURRENCY_NAME_ASSET]    VARCHAR (100)   NULL,
    [LOCAL_CURRENCY_CODE]    VARCHAR (3)     NOT NULL,
    [FUND_SHORT_NAME]        VARCHAR (15)    NOT NULL,
    [MARKET_VALUE_BASE]      DECIMAL (18, 3) NULL,
    [MARKET_VALUE_LOCAL]     DECIMAL (18, 3) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   NULL,
    [CADIS_SYSTEM_PRIORITY]  INT             NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [ASSET_SUB_CATEGORY] ASC, [LOCAL_CURRENCY_CODE] ASC, [FUND_SHORT_NAME] ASC) WITH (FILLFACTOR = 80)
);

