CREATE TABLE [CADIS_PROC].[DC_UPDTHWPOS_INFO_VALUE] (
    [EDM_SEC_ID]                INT              NULL,
    [FILE_NAME]                 VARCHAR (50)     NOT NULL,
    [FILE_TYPE]                 VARCHAR (12)     NOT NULL,
    [FILE_DATE]                 DATETIME         NOT NULL,
    [CUSTOMER_CODE]             VARCHAR (20)     NOT NULL,
    [MODEL_CODE]                VARCHAR (20)     NOT NULL,
    [MODEL_DATE]                DATETIME         NOT NULL,
    [MODEL_DESCRIPTION]         VARCHAR (80)     NOT NULL,
    [INSTRUMENT_UII]            VARCHAR (12)     NOT NULL,
    [SEDOL]                     VARCHAR (12)     NULL,
    [CURRENCY]                  VARCHAR (12)     NULL,
    [STOCK_SHORT_NAME]          VARCHAR (80)     NOT NULL,
    [SECTOR_CODE]               VARCHAR (50)     NULL,
    [UII_ALLOCATION_PCT]        INT              NOT NULL,
    [CURRENT_PERCENTAGE]        DECIMAL (10, 4)  NOT NULL,
    [CHANGE_PERCENTAGE]         DECIMAL (10, 4)  NOT NULL,
    [START_PRICE]               DECIMAL (24, 10) NOT NULL,
    [START_PRICE_DATE]          DATETIME         NOT NULL,
    [CURRENT_PRICE]             DECIMAL (24, 10) NOT NULL,
    [CURRENT_DATE]              DATETIME         NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT              DEFAULT ((1)) NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME         DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([MODEL_CODE] ASC, [INSTRUMENT_UII] ASC, [CURRENT_DATE] ASC) WITH (FILLFACTOR = 80)
);

