CREATE TABLE [CADIS_PROC].[DC_UPFNDEXCEP_INFO_RULE] (
    [SOURCE_TABLE]             VARCHAR (50) NOT NULL,
    [SOURCE_KEY_1]             VARCHAR (50) NOT NULL,
    [SOURCE_KEY_2]             VARCHAR (50) NOT NULL,
    [SOURCE_COLUMN]            VARCHAR (50) NOT NULL,
    [EXCEPTION_CODE]           INT          NOT NULL,
    [EXCEPTION_DATE__RULEID]   INT          NULL,
    [FUND_SHORT_NAME__RULEID]  INT          NULL,
    [ENTITY__RULEID]           INT          NULL,
    [EXCEPTION_NAME__RULEID]   INT          NULL,
    [EXCEPTION_TYPE__RULEID]   INT          NULL,
    [STATUS__RULEID]           INT          NULL,
    [PRIORITY__RULEID]         INT          NULL,
    [COMMENT__RULEID]          INT          NULL,
    [OWNER__RULEID]            INT          NULL,
    [TEAM__RULEID]             INT          NULL,
    [SOURCE_VALUE__RULEID]     INT          NULL,
    [DATA_A_TYPE__RULEID]      INT          NULL,
    [DATA_A_VALUE__RULEID]     INT          NULL,
    [DATA_B_TYPE__RULEID]      INT          NULL,
    [DATA_B_VALUE__RULEID]     INT          NULL,
    [DATA_C_TYPE__RULEID]      INT          NULL,
    [DATA_C_VALUE__RULEID]     INT          NULL,
    [SOURCE__RULEID]           INT          NULL,
    [SOURCE_COMPONENT__RULEID] INT          NULL,
    [RETENTION__RULEID]        INT          NULL,
    [HASVALUECHANGED__RULEID]  INT          NULL,
    [DAYS_VALID__RULEID]       INT          NULL,
    [OCCURRENCE__RULEID]       INT          NULL,
    [EXCEPTION_AGE__RULEID]    INT          NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY_1] ASC, [SOURCE_KEY_2] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC)
);

