CREATE TABLE [CADIS_PROC].[DC_UPNTEISS_VALID_PREP] (
    [Primary Key Unique?]             BIT              NULL,
    [Fund Short Name Mapping Exists?] BIT              NULL,
    [EDM_SEC_ID Mapping Exists?]      BIT              NULL,
    [FUND_FISCAL_YEAR Populated?]     BIT              NULL,
    [FUND_FISCAL_QUARTER Populated?]  BIT              NULL,
    [All Tests Passed?]               BIT              NULL,
    [CADIS_SYSTEM_CHANGEDBY]          NVARCHAR (50)    NULL,
    [CADIS_SYSTEM_INSERTED]           DATETIME         NULL,
    [CADIS_SYSTEM_UPDATED]            DATETIME         NULL,
    [PK_RANK]                         BIGINT           NULL,
    [PK_COLUMNS]                      VARCHAR (41)     NOT NULL,
    [PK_VALUE]                        VARCHAR (82)     NULL,
    [SOURCE_COMPONENT]                VARCHAR (34)     NOT NULL,
    [ID]                              INT              NOT NULL,
    [ACCOUNT_NUMBER]                  VARCHAR (255)    NOT NULL,
    [SECURITY_NUMBER]                 VARCHAR (255)    NULL,
    [VALUATION_DATE]                  DATETIME         NOT NULL,
    [SECURITY_DESCRIPTION]            VARCHAR (255)    NULL,
    [SEDOL]                           VARCHAR (7)      NULL,
    [CUSIP]                           VARCHAR (9)      NULL,
    [COUNTRY_OF_TAXATION]             VARCHAR (2)      NULL,
    [STATE_CODE]                      VARCHAR (255)    NULL,
    [ASSET_GROUP]                     VARCHAR (255)    NULL,
    [EX_DATE_SHARES]                  DECIMAL (18, 4)  NULL,
    [EX_DATE]                         DATETIME         NOT NULL,
    [ACCRUED_INCOME]                  DECIMAL (18, 4)  NULL,
    [INCOME_RECEIVED]                 DECIMAL (18, 4)  NULL,
    [PRIOR_INC_ACCRUED]               DECIMAL (18, 4)  NULL,
    [INCOME_EARNED]                   DECIMAL (18, 4)  NULL,
    [AMORT_ACCRUED]                   DECIMAL (18, 4)  NULL,
    [AMORT_SOLD]                      DECIMAL (18, 4)  NULL,
    [PRIOR_AMORT_ACCRUED]             DECIMAL (18, 4)  NULL,
    [AMORT_EARNED]                    DECIMAL (18, 4)  NULL,
    [TOTAL_INC_AND_AMORT_EARNED]      DECIMAL (18, 4)  NULL,
    [UNITS]                           DECIMAL (18, 4)  NULL,
    [FUND_NET_INCOME]                 DECIMAL (18, 4)  NULL,
    [RATE]                            DECIMAL (23, 15) NULL,
    [FUND_SHORT_NAME]                 VARCHAR (20)     NOT NULL,
    [EDM_SEC_ID]                      INT              NOT NULL,
    [FUND_FISCAL_YEAR]                INT              NULL,
    [FUND_FISCAL_QUARTER]             INT              NULL,
    [CADIS_SYSTEM_INSERTED0]          DATETIME         NULL,
    [CADIS_SYSTEM_UPDATED0]           DATETIME         NULL,
    [CADIS_SYSTEM_CHANGEDBY0]         NVARCHAR (50)    NULL,
    [CADIS_SYSTEM_RUNID]              INT              NOT NULL,
    [CADIS_SYSTEM_TOPRUNID]           INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);

