CREATE TABLE [CADIS_PROC].[DC_UPFNDEXCEP_CBUF] (
    [SOURCE_TABLE]   VARCHAR (50) NOT NULL,
    [SOURCE_KEY_1]   VARCHAR (50) NOT NULL,
    [SOURCE_KEY_2]   VARCHAR (50) NOT NULL,
    [SOURCE_COLUMN]  VARCHAR (50) NOT NULL,
    [EXCEPTION_CODE] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY_1] ASC, [SOURCE_KEY_2] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC)
);

