CREATE TABLE [CADIS_PROC].[DC_UPNTDVDIRR_CBUF] (
    [ACCOUNT_NUMBER]  VARCHAR (50) NOT NULL,
    [DATE]            DATETIME     NOT NULL,
    [SEC_DESCRIPTION] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [DATE] ASC, [SEC_DESCRIPTION] ASC)
);

