CREATE TABLE [CADIS_PROC].[DC_UPNTDVDIRR_R092_PREP] (
    [CUR_DATE]               DATE          NULL,
    [DATE]                   DATETIME      NOT NULL,
    [ACCOUNT_NUMBER]         VARCHAR (50)  NOT NULL,
    [TYPE]                   VARCHAR (20)  NULL,
    [GEN_LEDGER_ACCOUNT]     VARCHAR (400) NULL,
    [TOTAL_DEBITS]           VARCHAR (400) NULL,
    [TOTAL_CREDITS]          VARCHAR (400) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([DATE] ASC, [ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 80)
);

