CREATE TABLE [CADIS_PROC].[DC_UPMSI_PRE_MST_PREP] (
    [FUND_SHORT_NAME]        VARCHAR (20)     NOT NULL,
    [EDM_SEC_ID]             INT              NOT NULL,
    [FUND_FISCAL_YEAR]       INT              NOT NULL,
    [POSITION_DATE]          DATETIME         NOT NULL,
    [DVD_CCY]                VARCHAR (3)      NULL,
    [WITHHOLDING_TAX]        DECIMAL (26, 6)  NULL,
    [DECLARED_DATE]          DATETIME         NULL,
    [POSITION]               DECIMAL (20, 6)  NULL,
    [MID_PRICE]              DECIMAL (24, 10) NULL,
    [SPOT_RATE]              DECIMAL (24, 10) NULL,
    [MARKET_VALUE]           DECIMAL (24, 10) NULL,
    [Q1_EX_DATE]             DATE             NULL,
    [Q1_RATE]                DECIMAL (20, 6)  NULL,
    [Q1_EARNED_INCOME]       DECIMAL (24, 10) NULL,
    [Q1_TO_PAY]              DECIMAL (24, 10) NULL,
    [Q1_NET_INCOME]          DECIMAL (24, 10) NULL,
    [Q2_EX_DATE]             DATE             NULL,
    [Q2_RATE]                DECIMAL (20, 6)  NULL,
    [Q2_EARNED_INCOME]       DECIMAL (24, 10) NULL,
    [Q2_TO_PAY]              DECIMAL (24, 10) NULL,
    [Q2_NET_INCOME]          DECIMAL (24, 10) NULL,
    [Q3_EX_DATE]             DATE             NULL,
    [Q3_RATE]                DECIMAL (20, 6)  NULL,
    [Q3_EARNED_INCOME]       DECIMAL (24, 10) NULL,
    [Q3_TO_PAY]              DECIMAL (24, 10) NULL,
    [Q3_NET_INCOME]          DECIMAL (24, 10) NULL,
    [Q4_EX_DATE]             DATE             NULL,
    [Q4_RATE]                DECIMAL (20, 6)  NULL,
    [Q4_EARNED_INCOME]       DECIMAL (24, 10) NULL,
    [Q4_TO_PAY]              DECIMAL (24, 10) NULL,
    [Q4_NET_INCOME]          DECIMAL (24, 10) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME         NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME         NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)    NULL,
    [CADIS_SYSTEM_RUNID]     INT              NOT NULL,
    [CADIS_SYSTEM_TOPRUNID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC) WITH (FILLFACTOR = 80)
);

