CREATE TABLE [CADIS_PROC].[DC_UPPMFFLOW_NT_PREP] (
    [FUND_SHORT_NAME]  VARCHAR (15)    NOT NULL,
    [THROUGH_DATE]     DATETIME        NOT NULL,
    [NTRANCATG]        VARCHAR (29)    NOT NULL,
    [NET_AMOUNT_BASE]  DECIMAL (38, 5) NULL,
    [RECOGNITION_DATE] DATETIME        NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [THROUGH_DATE] ASC, [NTRANCATG] ASC, [RECOGNITION_DATE] ASC)
);

