CREATE TABLE [CADIS_PROC].[DC_UPNTDVDIRR_EXP_SUM_PREP] (
    [CUR_DATE]               DATE          NOT NULL,
    [DATE]                   DATETIME      NULL,
    [ACCOUNT_NUMBER]         VARCHAR (50)  NOT NULL,
    [SECURITY]               VARCHAR (100) NULL,
    [DESCRIPTION]            VARCHAR (50)  NULL,
    [EXPENSES_CHARGED]       VARCHAR (20)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([CUR_DATE] ASC, [ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 80)
);

