CREATE TABLE [CADIS_PROC].[DC_UPMASCFLOW_RESET_PREP] (
    [FUND_SHORT_NAME]           BIT           NULL,
    [FLOW_TYPE]                 BIT           NULL,
    [MCID]                      BIT           NULL,
    [TRUSTEE]                   BIT           NULL,
    [VALUATION_POINT_DATE]      DATETIME      NOT NULL,
    [VALUATION_POINT_TIME]      BIT           NULL,
    [FUND_LONG_NAME]            BIT           NULL,
    [EXTERNAL_FUND_CODE]        VARCHAR (50)  NOT NULL,
    [FUND_REFERENCE]            VARCHAR (20)  NOT NULL,
    [BROUGHT_FORWARD_POSITION]  BIT           NULL,
    [NET_UNIT_MOVEMENT]         BIT           NULL,
    [BOOK_CONVERSION_IN]        BIT           NULL,
    [BOOK_CONVERSION_OUT]       BIT           NULL,
    [CONVERSION_FACTOR]         BIT           NULL,
    [ESTIMATED_CLOSING_BALANCE] BIT           NULL,
    [UNIT_DECISION]             BIT           NULL,
    [CASH_DECISION]             BIT           NULL,
    [CARRIED_FORWARD_BALANCE]   BIT           NULL,
    [BOOK_BASIS]                BIT           NULL,
    [DECISION_VALUE]            BIT           NULL,
    [INSPECIE_FLAG]             BIT           NULL,
    [NARRATIVE]                 BIT           NULL,
    [SIGNATORY]                 BIT           NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_POINT_DATE] ASC, [EXTERNAL_FUND_CODE] ASC, [FUND_REFERENCE] ASC) WITH (FILLFACTOR = 80)
);

