CREATE TABLE [CADIS_PROC].[DC_UPPREPRC_BPS_HIST_PREP] (
    [ID_BB_UNIQUE]         VARCHAR (50)    NOT NULL,
    [PX_DATE]              DATETIME        NOT NULL,
    [PX_LAST]              DECIMAL (20, 6) NOT NULL,
    [EDM_SEC_ID]           INT             NOT NULL,
    [CADIS_SYSTEM_UPDATED] DATETIME        NULL,
    [PRICE_SOURCE]         VARCHAR (11)    NOT NULL,
    PRIMARY KEY CLUSTERED ([PX_DATE] ASC, [EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);

