CREATE TABLE [CADIS_PROC].[DC_UPDTHWPOS_HWPOS_PREP] (
    [MODEL_CODE]             VARCHAR (20)  NOT NULL,
    [MODEL_DATE]             DATETIME      NOT NULL,
    [INSTRUMENT_UII]         VARCHAR (12)  NOT NULL,
    [SEDOL]                  VARCHAR (12)  NULL,
    [CURRENT_DATE]           DATETIME      NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([MODEL_CODE] ASC, [INSTRUMENT_UII] ASC, [CURRENT_DATE] ASC) WITH (FILLFACTOR = 80)
);

