CREATE TABLE [CADIS_PROC].[DC_UPPRNOTIF_INFO_RUNID] (
    [DATA_CHANNEL_ID]                     INT NOT NULL,
    [SOURCE__RUNID]                       INT NOT NULL,
    [ENTITY__RUNID]                       INT NOT NULL,
    [DESCRIPTION__RUNID]                  INT NOT NULL,
    [DIRECTION__RUNID]                    INT NOT NULL,
    [EXPECTED_DELIVERY_TIME__RUNID]       INT NOT NULL,
    [ACTUAL_DELIVERY__RUNID]              INT NOT NULL,
    [DELIVERY_SLA_MET__RUNID]             INT NOT NULL,
    [EXPECTED_SLA_COMPLETION__RUNID]      INT NOT NULL,
    [ACTUAL_SLA_COMPLETION__RUNID]        INT NOT NULL,
    [PROCESSING_SLA_MET__RUNID]           INT NOT NULL,
    [DELIVERY_NOTIFICATION_SENT__RUNID]   INT NOT NULL,
    [PROCESSING_NOTIFICATION_SENT__RUNID] INT NOT NULL,
    [MARKIT_SOLUTION__RUNID]              INT NOT NULL,
    [MORNING_CHECK__RUNID]                INT NOT NULL,
    PRIMARY KEY CLUSTERED ([DATA_CHANNEL_ID] ASC) WITH (FILLFACTOR = 80)
);

