CREATE TABLE [CADIS_PROC].[DC_UPMSFFLOW_SHARECLASS_PREP] (
    [FUND_SHORT_NAME]      VARCHAR (15)    NOT NULL,
    [TRANSACTION_DATE]     DATETIME        NOT NULL,
    [FLOW_TYPE]            VARCHAR (100)   NOT NULL,
    [MARKET_VALUE]         DECIMAL (38, 2) NULL,
    [CADIS_SYSTEM_UPDATED] DATETIME        NULL,
    [SOURCE]               VARCHAR (10)    NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [FLOW_TYPE] ASC)
);

