CREATE TABLE [CADIS_PROC].[DC_UPPMFFLOW_AUDIT] (
    [FUND_SHORT_NAME]        VARCHAR (15)   NOT NULL,
    [TRANSACTION_DATE]       DATETIME       NOT NULL,
    [FLOW_TYPE]              VARCHAR (100)  NOT NULL,
    [RECOGNITION_DATE]       DATETIME       NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [FLOW_TYPE] ASC, [RECOGNITION_DATE] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC)
);

