CREATE TABLE [CADIS_PROC].[DC_UPFNDEXCEP_EXC_RULE_PREP] (
    [EXCEPTION_CODE]         INT           NOT NULL,
    [EXCEPTION_TYPE]         VARCHAR (50)  NOT NULL,
    [EXCEPTION_NAME]         VARCHAR (150) NULL,
    [EXCEPTION_DESC]         VARCHAR (250) NOT NULL,
    [EXCEPTION_DAYS_VALID]   INT           NULL,
    [DEFAULT_STATUS]         VARCHAR (50)  NULL,
    [DEFAULT_PRIORITY]       VARCHAR (20)  NULL,
    [DEFAULT_OWNER]          VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([EXCEPTION_CODE] ASC) WITH (FILLFACTOR = 80)
);

