CREATE TABLE [CADIS_PROC].[DC_UPSECEXP_INFO_RULE] (
    [ENTITY__RULEID]                 INT          NULL,
    [SOURCE__RULEID]                 INT          NULL,
    [SOURCE_TABLE]                   VARCHAR (50) NOT NULL,
    [SOURCE_COMPONENT__RULEID]       INT          NULL,
    [SOURCE_KEY]                     VARCHAR (50) NOT NULL,
    [SOURCE_COLUMN]                  VARCHAR (50) NOT NULL,
    [EXCEPTION_CODE]                 INT          NOT NULL,
    [ACCOUNT_CODE__RULEID]           INT          NULL,
    [SECURITY_ID__RULEID]            INT          NULL,
    [CADIS_ID__RULEID]               INT          NULL,
    [POSITION_TYPE__RULEID]          INT          NULL,
    [SECURITY_NAME__RULEID]          INT          NULL,
    [ISSUER_NAME__RULEID]            INT          NULL,
    [ACCOUNT_NAME__RULEID]           INT          NULL,
    [EXCEPTION_DATE__RULEID]         INT          NULL,
    [SOURCE_VALUE__RULEID]           INT          NULL,
    [DATA_A_TYPE__RULEID]            INT          NULL,
    [DATA_A_VALUE__RULEID]           INT          NULL,
    [DATA_B_TYPE__RULEID]            INT          NULL,
    [DATA_B_VALUE__RULEID]           INT          NULL,
    [DATA_C_TYPE__RULEID]            INT          NULL,
    [DATA_C_VALUE__RULEID]           INT          NULL,
    [HELD_SECURITY__RULEID]          INT          NULL,
    [INDEX_SECURITY__RULEID]         INT          NULL,
    [ISIN__RULEID]                   INT          NULL,
    [SEDOL__RULEID]                  INT          NULL,
    [CUSIP__RULEID]                  INT          NULL,
    [SECURITY_TYPE__RULEID]          INT          NULL,
    [CURRENCY__RULEID]               INT          NULL,
    [BLOOMBERG_LAST_UPDATED__RULEID] INT          NULL,
    [STATUS__RULEID]                 INT          NULL,
    [PRIORITY__RULEID]               INT          NULL,
    [OWNER__RULEID]                  INT          NULL,
    [TEAM__RULEID]                   INT          NULL,
    [RETENTION__RULEID]              INT          NULL,
    [COMMENT__RULEID]                INT          NULL,
    [EXCEPTION_NAME__RULEID]         INT          NULL,
    [EXCEPTION_TYPE__RULEID]         INT          NULL,
    [BUSINESS_PROCESS_LEVEL__RULEID] INT          NULL,
    [HASVALUECHANGED__RULEID]        INT          NULL,
    [DAYS_VALID__RULEID]             INT          NULL,
    [OCCURRENCE__RULEID]             INT          NULL,
    [EXCEPTION_AGE__RULEID]          INT          NULL,
    [TOLERANCE__RULEID]              INT          NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC)
);

