CREATE TABLE [CADIS_PROC].[DC_UPPRNOTIF_INFO_RULE] (
    [DATA_CHANNEL_ID]                      INT NOT NULL,
    [SOURCE__RULEID]                       INT NULL,
    [ENTITY__RULEID]                       INT NULL,
    [DESCRIPTION__RULEID]                  INT NULL,
    [DIRECTION__RULEID]                    INT NULL,
    [EXPECTED_DELIVERY_TIME__RULEID]       INT NULL,
    [ACTUAL_DELIVERY__RULEID]              INT NULL,
    [DELIVERY_SLA_MET__RULEID]             INT NULL,
    [EXPECTED_SLA_COMPLETION__RULEID]      INT NULL,
    [ACTUAL_SLA_COMPLETION__RULEID]        INT NULL,
    [PROCESSING_SLA_MET__RULEID]           INT NULL,
    [DELIVERY_NOTIFICATION_SENT__RULEID]   INT NULL,
    [PROCESSING_NOTIFICATION_SENT__RULEID] INT NULL,
    [MARKIT_SOLUTION__RULEID]              INT NULL,
    [MORNING_CHECK__RULEID]                INT NULL,
    PRIMARY KEY CLUSTERED ([DATA_CHANNEL_ID] ASC) WITH (FILLFACTOR = 80)
);

