CREATE TABLE [CADIS_PROC].[DC_UPFNDEXCEP_AUDIT] (
    [SOURCE_TABLE]           VARCHAR (50)   NOT NULL,
    [SOURCE_KEY_1]           VARCHAR (50)   NOT NULL,
    [SOURCE_KEY_2]           VARCHAR (50)   NOT NULL,
    [SOURCE_COLUMN]          VARCHAR (50)   NOT NULL,
    [EXCEPTION_CODE]         INT            NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY_1] ASC, [SOURCE_KEY_2] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC)
);

