CREATE TABLE [CADIS_PROC].[DC_UPPRNOTIF_PROCESSSLA_PREP] (
    [SOURCE]                  VARCHAR (30)  NOT NULL,
    [ENTITY]                  VARCHAR (50)  NOT NULL,
    [DESCRIPTION]             VARCHAR (150) NOT NULL,
    [DIRECTION]               VARCHAR (3)   NOT NULL,
    [DATE]                    DATE          NULL,
    [EXPECTED_DELIVERY_TIME]  DATETIME      NULL,
    [ACTUAL_DELIVERY]         DATETIME      NULL,
    [DELIVERY_SLA_MET]        INT           NOT NULL,
    [EXPECTED_SLA_COMPLETION] DATETIME      NULL,
    [ACTUAL_SLA_COMPLETION]   DATETIME      NULL,
    [PROCESSING_SLA_MET]      INT           NOT NULL,
    [PROCESSING_TIME]         TIME (7)      NULL,
    [DATA_CHANNEL_ID]         INT           NOT NULL,
    [CURRENT_SLA_DATE]        DATETIME      NULL,
    [MARKIT_SOLUTION]         VARCHAR (150) NULL,
    [MORNING_CHECK]           VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([DATA_CHANNEL_ID] ASC) WITH (FILLFACTOR = 80)
);

