CREATE TABLE [CADIS_PROC].[DC_UPPMFFLOW_INFO_RULE] (
    [FUND_SHORT_NAME]      VARCHAR (15)  NOT NULL,
    [TRANSACTION_DATE]     DATETIME      NOT NULL,
    [FLOW_TYPE]            VARCHAR (100) NOT NULL,
    [MARKET_VALUE__RULEID] INT           NULL,
    [RECOGNITION_DATE]     DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [FLOW_TYPE] ASC, [RECOGNITION_DATE] ASC)
);

