CREATE TABLE [CADIS_PROC].[DC_UPNTDVDIRR_SUMMARY_PREP] (
    [ACCOUNT_NUMBER] VARCHAR (50) NOT NULL,
    [CUR_DATE]       DATE         NOT NULL,
    [DATE]           DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [CUR_DATE] ASC) WITH (FILLFACTOR = 80)
);

