CREATE TABLE [CADIS_PROC].[DC_UMLGFF_RED_PREP] (
    [FILE_NAME]       VARCHAR (20)    NOT NULL,
    [FILE_TYPE]       VARCHAR (20)    NULL,
    [FILE_DATE]       DATETIME        NULL,
    [FUND_SHORT_NAME] VARCHAR (15)    NOT NULL,
    [NT_ACCOUNT_CODE] VARCHAR (10)    NOT NULL,
    [PORTFOLIO_NAME]  VARCHAR (100)   NULL,
    [CURRENCY]        VARCHAR (3)     NULL,
    [TRADE_DATE]      DATETIME        NOT NULL,
    [AMOUNT]          DECIMAL (18, 2) NULL,
    [VALUE_DATE]      DATETIME        NULL,
    [FLOW_TYPE]       VARCHAR (10)    NOT NULL,
    [FUND_FLOW_TYPE]  VARCHAR (5)     NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRADE_DATE] ASC) WITH (FILLFACTOR = 80)
);

