CREATE TABLE [CADIS_PROC].[DC_UPMASACCBA_EXPIRY_PREP] (
    [FUND_SHORT_NAME]           VARCHAR (15)  NOT NULL,
    [POSITION_DATE]             DATETIME      NOT NULL,
    [ASSET_SUB_CATEGORY]        VARCHAR (100) NOT NULL,
    [CCY]                       VARCHAR (3)   NOT NULL,
    [LOCAL_VALUE]               DATETIME      NULL,
    [BASE_VALUE]                DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC, [ASSET_SUB_CATEGORY] ASC, [CCY] ASC) WITH (FILLFACTOR = 80)
);

