CREATE TABLE [CADIS_PROC].[DC_UPPLNOTIF_AUDIT] (
    [RUNID]                  INT            NOT NULL,
    [PROCESS_NAME]           VARCHAR (250)  NOT NULL,
    [PROCESS_TYPE]           VARCHAR (50)   NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([RUNID] ASC, [PROCESS_NAME] ASC, [PROCESS_TYPE] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC)
);

