CREATE TABLE [CADIS_PROC].[DC_UPDTEXCEPT_INFO_VALUE] (
    [SOURCE_TABLE]              VARCHAR (50)   NOT NULL,
    [SOURCE_KEY]                VARCHAR (50)   NOT NULL,
    [SOURCE_COLUMN]             VARCHAR (50)   NOT NULL,
    [EXCEPTION_CODE]            INT            NOT NULL,
    [EXCEPTION_DATE]            DATETIME       NOT NULL,
    [EDM_ENTITY_ID]             INT            NULL,
    [ENTITY]                    VARCHAR (40)   NULL,
    [EXCEPTION_NAME]            VARCHAR (40)   NULL,
    [EXCEPTION_TYPE]            VARCHAR (50)   NULL,
    [STATUS]                    VARCHAR (20)   DEFAULT ('New') NULL,
    [PRIORITY]                  VARCHAR (20)   NULL,
    [COMMENT]                   VARCHAR (100)  NULL,
    [OWNER]                     VARCHAR (50)   NULL,
    [TEAM]                      VARCHAR (50)   NULL,
    [SOURCE_VALUE]              VARCHAR (1000) NULL,
    [DATA_A_TYPE]               VARCHAR (100)  NULL,
    [DATA_A_VALUE]              VARCHAR (1000) NULL,
    [DATA_B_TYPE]               VARCHAR (100)  NULL,
    [DATA_B_VALUE]              VARCHAR (1000) NULL,
    [DATA_C_TYPE]               VARCHAR (100)  NULL,
    [DATA_C_VALUE]              VARCHAR (1000) NULL,
    [SOURCE]                    VARCHAR (50)   NULL,
    [SOURCE_COMPONENT]          VARCHAR (50)   NULL,
    [RETENTION]                 INT            NULL,
    [HASVALUECHANGED]           INT            NULL,
    [DAYS_VALID]                INT            NULL,
    [OCCURRENCE]                INT            NULL,
    [EXCEPTION_AGE]             INT            NULL,
    [CUSIP]                     VARCHAR (20)   NULL,
    [ISIN]                      VARCHAR (20)   NULL,
    [SECURITY_ID]               VARCHAR (50)   NULL,
    [SEDOL]                     VARCHAR (20)   NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)  DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT            DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME       DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC)
);

