CREATE TABLE [CADIS_PROC].[DC_UPPRENFF_INFO_RUNID] (
    [FILE_NAME__RUNID]                                     INT             NOT NULL,
    [FILE_TYPE__RUNID]                                     INT             NOT NULL,
    [FILE_DATE__RUNID]                                     INT             NOT NULL,
    [NUMBER_OF_RECORDS__RUNID]                             INT             NOT NULL,
    [CONSOLIDATION__RUNID]                                 INT             NOT NULL,
    [ACCOUNT_NUMBER]                                       VARCHAR (50)    NOT NULL,
    [FUND_SHORT_NAME__RUNID]                               INT             NOT NULL,
    [FROM_DATE__RUNID]                                     INT             NOT NULL,
    [THROUGH_DATE__RUNID]                                  INT             NOT NULL,
    [TASTDESCMED__RUNID]                                   INT             NOT NULL,
    [TNARRLONG]                                            VARCHAR (255)   NOT NULL,
    [ABASBSE__RUNID]                                       INT             NOT NULL,
    [NET_AMOUNT__BASE]                                     DECIMAL (20, 6) NOT NULL,
    [AMKTVAL__RUNID]                                       INT             NOT NULL,
    [ARLSDGAIN__RUNID]                                     INT             NOT NULL,
    [AEXCHGNLS__RUNID]                                     INT             NOT NULL,
    [RECOGNITION_DATE]                                     DATETIME        NOT NULL,
    [NTRANCATG]                                            VARCHAR (100)   NOT NULL,
    [ASSET_IDENTIFIER__RUNID]                              INT             NOT NULL,
    [CTEMPLTYPE__RUNID]                                    INT             NOT NULL,
    [CVALNTYPEO__RUNID]                                    INT             NOT NULL,
    [TSHAREPAR__RUNID]                                     INT             NOT NULL,
    [REVERSAL_INDICATOR__RUNID]                            INT             NOT NULL,
    [ALOTCOSTGNLS__RUNID]                                  INT             NOT NULL,
    [DTRANPROC__RUNID]                                     INT             NOT NULL,
    [CSORTCDE3__RUNID]                                     INT             NOT NULL,
    [ERROR_CODE__RUNID]                                    INT             NOT NULL,
    [CONSOLIDATION_AUDIT_INDICATOR_FLAG__RUNID]            INT             NOT NULL,
    [IEXTLREF]                                             VARCHAR (50)    NOT NULL,
    [CASSETLIAB__RUNID]                                    INT             NOT NULL,
    [ACCRUED_INTEREST__RUNID]                              INT             NOT NULL,
    [DSET__RUNID]                                          INT             NOT NULL,
    [ACCRUAL_CHANGE_FROM_SECURITY_MOVEMENTS_OFFSET__RUNID] INT             NOT NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [TNARRLONG] ASC, [NET_AMOUNT__BASE] ASC, [RECOGNITION_DATE] ASC, [NTRANCATG] ASC, [IEXTLREF] ASC)
);

