CREATE TABLE [CADIS_PROC].[DC_UPMSCV_PRE_PREP] (
    [EDM_SHARECLASS_ID]          INT              NOT NULL,
    [VALUATION_DATE]             DATETIME         NOT NULL,
    [EXIT_CHARGE_PERCENT]        DECIMAL (28, 10) NULL,
    [INITIAL_CHARGE_PERCENT]     DECIMAL (28, 10) NULL,
    [MID_PRICE]                  DECIMAL (28, 10) NOT NULL,
    [PRICE_CHANGE]               DECIMAL (28, 10) NULL,
    [PRICE_MOVE_PERCENT]         DECIMAL (28, 10) NULL,
    [INITIAL_CHARGE]             DECIMAL (28, 10) NULL,
    [HISTORIC_YIELD_PERCENT]     DECIMAL (28, 10) NULL,
    [DISTRIBUTION_YIELD_PERCENT] DECIMAL (28, 10) NULL,
    [UNDERLYING_YIELD_PERCENT]   DECIMAL (28, 10) NULL,
    [EQUALISATION_RATE]          DECIMAL (28, 10) NULL,
    [UNITS_IN_ISSUE]             DECIMAL (28, 10) NOT NULL,
    [FUND_VALUE]                 DECIMAL (28, 10) NOT NULL,
    [CADIS_SYSTEM_INSERTED]      DATETIME         NULL,
    [CADIS_SYSTEM_UPDATED]       DATETIME         NULL,
    [CADIS_SYSTEM_CHANGEDBY]     NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([EDM_SHARECLASS_ID] ASC, [VALUATION_DATE] ASC) WITH (FILLFACTOR = 80)
);

