CREATE TABLE [CADIS_PROC].[DC_UMLGFF_CBUF] (
    [FUND_SHORT_NAME] VARCHAR (15) NOT NULL,
    [TRADE_DATE]      DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRADE_DATE] ASC) WITH (FILLFACTOR = 80)
);

