CREATE TABLE [CADIS_PROC].[DC_UPMSFFLOW_NET_PREP] (
    [FUND_SHORT_NAME]      VARCHAR (15)    NOT NULL,
    [RECOGNITION_DATE]     DATETIME        NOT NULL,
    [FLOW_TYPE]            VARCHAR (100)   NOT NULL,
    [NET_AMOUNT_BASE]      DECIMAL (38, 6) NULL,
    [CADIS_SYSTEM_UPDATED] DATETIME        NULL,
    [SOURCE]               VARCHAR (3)     NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [RECOGNITION_DATE] ASC, [FLOW_TYPE] ASC)
);

