CREATE TABLE [CADIS_PROC].[DC_UPMASCFLOW_AUDIT] (
    [VALUATION_POINT_DATE]   DATETIME       NOT NULL,
    [EXTERNAL_FUND_CODE]     VARCHAR (50)   NOT NULL,
    [FUND_REFERENCE]         VARCHAR (20)   NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_POINT_DATE] ASC, [EXTERNAL_FUND_CODE] ASC, [FUND_REFERENCE] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC)
);

