CREATE TABLE [CADIS_PROC].[DC_UPMASSEC_EXPIRY_PREP] (
    [EDM_SEC_ID]                     INT           NOT NULL,
    [SECURITY_NAME]                  DATETIME      NULL,
    [SECURITY_DESCRIPTION]           DATETIME      NULL,
    [SECURITY_SHORTNAME]             DATETIME      NULL,
    [ASSET_TYPE]                     DATETIME      NULL,
    [SECURITY_TYPE]                  DATETIME      NULL,
    [CUSIP]                          DATETIME      NULL,
    [ISIN]                           DATETIME      NULL,
    [SEDOL]                          DATETIME      NULL,
    [TICKER]                         DATETIME      NULL,
    [VALOREN]                        DATETIME      NULL,
    [WERTPAPIER]                     DATETIME      NULL,
    [SECURITY_ISO_CCY]               DATETIME      NULL,
    [RISK_ISO_CCY]                   DATETIME      NULL,
    [FIXED_ISO_CCY]                  DATETIME      NULL,
    [INCORPORATION_ISO_CTY]          DATETIME      NULL,
    [DOMICILE_ISO_CTY]               DATETIME      NULL,
    [ISSUE_COUNTRY_ISO]              DATETIME      NULL,
    [RISK_ISO_CTY]                   DATETIME      NULL,
    [MIC_EXCHANGE_CODE]              DATETIME      NULL,
    [BBG_EXCHANGE_CODE]              DATETIME      NULL,
    [STATE_CODE]                     DATETIME      NULL,
    [ACTIVE_TRADE_INDICATOR]         DATETIME      NULL,
    [144A_INDICATOR]                 DATETIME      NULL,
    [PRIVATE_PLACEMENT_INDICATOR]    DATETIME      NULL,
    [ILLIQUID]                       DATETIME      NULL,
    [QUOTE_TYPE]                     DATETIME      NULL,
    [DAYS_TO_SETTLE]                 DATETIME      NULL,
    [TRADE_SETTLEMENT_CALENDAR_CODE] DATETIME      NULL,
    [UNIQUE_BLOOMBERG_ID]            DATETIME      NULL,
    [BBG_SECTOR]                     DATETIME      NULL,
    [BBG_SUBSECTOR]                  DATETIME      NULL,
    [BBG_GROUP]                      DATETIME      NULL,
    [IS_IPO]                         DATETIME      NULL,
    [PARSEKEYABLE_DESCRIPTION]       DATETIME      NULL,
    [SECURITY_IDENTIFIER]            DATETIME      NULL,
    [IRISH_SEDOL_NUMBER]             DATETIME      NULL,
    [ISSUER]                         DATETIME      NULL,
    [CUR_MAR_CAP]                    DATETIME      NULL,
    [PRIMARY_EXCHANGE_NAME]          DATETIME      NULL,
    [SECURITY_HAS_ADRS]              DATETIME      NULL,
    [WITHHOLDING_TAX]                DATETIME      NULL,
    [VOL_AVG_5D]                     DATETIME      NULL,
    [VOL_AVG_20D]                    DATETIME      NULL,
    [ADV_TOTAL_VOLUME]               DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]          DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]           DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY]         NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]          INT           NULL,
    [CADIS_SYSTEM_LASTMODIFIED]      DATETIME      NULL,
    [CADIS_SYSTEM_TIMESTAMP]         ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);

