CREATE TABLE [CADIS_PROC].[DC_UPDSCOPE_UPDREGLMT_PREP] (
    [ROW_ID]    BIGINT         NOT NULL,
    [FUND_CODE] VARCHAR (255)  NULL,
    [RULE_ID]   VARCHAR (8000) NULL,
    [TICKER]    VARCHAR (255)  NULL,
    PRIMARY KEY CLUSTERED ([ROW_ID] ASC) WITH (FILLFACTOR = 80)
);

