CREATE TABLE [CADIS_PROC].[DC_UPPMSI_INFO_RULE] (
    [FUND_SHORT_NAME]          VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]               INT          NOT NULL,
    [FUND_FISCAL_YEAR]         INT          NOT NULL,
    [POSITION_DATE__RULEID]    INT          NULL,
    [DVD_CCY__RULEID]          INT          NULL,
    [WITHHOLDING_TAX__RULEID]  INT          NULL,
    [DECLARED_DATE__RULEID]    INT          NULL,
    [POSITION__RULEID]         INT          NULL,
    [MID_PRICE__RULEID]        INT          NULL,
    [SPOT_RATE__RULEID]        INT          NULL,
    [MARKET_VALUE__RULEID]     INT          NULL,
    [Q1_EX_DATE__RULEID]       INT          NULL,
    [Q1_RATE__RULEID]          INT          NULL,
    [Q1_EARNED_INCOME__RULEID] INT          NULL,
    [Q1_TO_PAY__RULEID]        INT          NULL,
    [Q1_NET_INCOME__RULEID]    INT          NULL,
    [Q2_EX_DATE__RULEID]       INT          NULL,
    [Q2_RATE__RULEID]          INT          NULL,
    [Q2_EARNED_INCOME__RULEID] INT          NULL,
    [Q2_TO_PAY__RULEID]        INT          NULL,
    [Q2_NET_INCOME__RULEID]    INT          NULL,
    [Q3_EX_DATE__RULEID]       INT          NULL,
    [Q3_RATE__RULEID]          INT          NULL,
    [Q3_EARNED_INCOME__RULEID] INT          NULL,
    [Q3_TO_PAY__RULEID]        INT          NULL,
    [Q3_NET_INCOME__RULEID]    INT          NULL,
    [Q4_EX_DATE__RULEID]       INT          NULL,
    [Q4_RATE__RULEID]          INT          NULL,
    [Q4_EARNED_INCOME__RULEID] INT          NULL,
    [Q4_TO_PAY__RULEID]        INT          NULL,
    [Q4_NET_INCOME__RULEID]    INT          NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC) WITH (FILLFACTOR = 80)
);

