CREATE TABLE [CADIS_PROC].[DC_UPPMFX_AUDIT] (
    [FXRATE_ID]              VARCHAR (16)   NOT NULL,
    [DATE]                   DATETIME       NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([FXRATE_ID] ASC, [DATE] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC)
);

