CREATE TABLE [CADIS_PROC].[DC_UPNTEIFS_INFO_VALUE] (
    [FUND_SHORT_NAME]        VARCHAR (20)     NOT NULL,
    [VALUATION_DATE]         DATETIME         NOT NULL,
    [UNITS]                  DECIMAL (28, 10) NOT NULL,
    [FUND_NET_INCOME]        DECIMAL (28, 10) NOT NULL,
    [RATE]                   DECIMAL (28, 10) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_RUNID]     INT              DEFAULT ((0)) NOT NULL,
    [CADIS_SYSTEM_TOPRUNID]  INT              DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [VALUATION_DATE] ASC) WITH (FILLFACTOR = 80)
);

