CREATE TABLE [CADIS_PROC].[DC_UPPLNOTIF_INFO_VALUE] (
    [RUNID]                     INT           NOT NULL,
    [PROCESS_NAME]              VARCHAR (250) NOT NULL,
    [PROCESS_TYPE]              VARCHAR (50)  NOT NULL,
    [NOTIFICATION_SENT]         DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      DEFAULT (getdate()) NULL,
    [RUNSTART]                  DATETIME      NULL,
    [RUNEND]                    DATETIME      NULL,
    [RUNSUCCESSFUL]             BIT           NULL,
    PRIMARY KEY CLUSTERED ([RUNID] ASC, [PROCESS_NAME] ASC, [PROCESS_TYPE] ASC)
);

