CREATE TABLE [CADIS_PROC].[DC_UPNTEIFS_INFO_RULE] (
    [FUND_SHORT_NAME]         VARCHAR (20) NOT NULL,
    [VALUATION_DATE]          DATETIME     NOT NULL,
    [UNITS__RULEID]           INT          NULL,
    [FUND_NET_INCOME__RULEID] INT          NULL,
    [RATE__RULEID]            INT          NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [VALUATION_DATE] ASC) WITH (FILLFACTOR = 80)
);

