CREATE TABLE [CADIS_PROC].[DC_UPBBMSTBRK_INFO_RULE] (
    [MASTER_BROKER_NUMBER]             VARCHAR (40) NOT NULL,
    [MASTER_BROKER_SHORT_NAME__RULEID] INT          NULL,
    [MASTER_BROKER_LONG_NAME__RULEID]  INT          NULL,
    PRIMARY KEY CLUSTERED ([MASTER_BROKER_NUMBER] ASC)
);

