CREATE TABLE [CADIS_PROC].[DC_UPMSTINC_AUDIT] (
    [FUND_SHORT_NAME]        VARCHAR (50)   NOT NULL,
    [EDM_SEC_ID]             INT            NOT NULL,
    [FUND_FISCAL_YEAR]       INT            NOT NULL,
    [FUND_FISCAL_QUARTER]    INT            NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC, [FUND_FISCAL_QUARTER] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC) WITH (FILLFACTOR = 80)
);

