CREATE TABLE [CADIS_PROC].[DC_UPDRGLMSUM_UPDREGLMT_PREP] (
    [ROW_ID]    BIGINT        NOT NULL,
    [FUND_CODE] VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ROW_ID] ASC) WITH (FILLFACTOR = 80)
);

