CREATE TABLE [CADIS_PROC].[DC_UPPREDIPS_AUDIT] (
    [ASSET]                  VARCHAR (10)   NOT NULL,
    [ORDER_REF]              INT            NOT NULL,
    [VALUATION_POINT]        DATETIME       NOT NULL,
    [ESTIMATED?]             BIT            NOT NULL,
    [CADIS_SYSTEM_RUNID]     INT            NOT NULL,
    [CADIS_SYSTEM_FIELDNAME] NVARCHAR (128) NOT NULL,
    [CADIS_SYSTEM_RULEID]    INT            NULL,
    [CADIS_SYSTEM_NEWVAL]    SQL_VARIANT    NULL,
    PRIMARY KEY CLUSTERED ([ASSET] ASC, [ORDER_REF] ASC, [VALUATION_POINT] ASC, [ESTIMATED?] ASC, [CADIS_SYSTEM_RUNID] ASC, [CADIS_SYSTEM_FIELDNAME] ASC)
);

