CREATE TABLE [CADIS_SYS].[CO_BESTPRACTICEINFO] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [PROCESSGUID] NCHAR (32)     NOT NULL,
    [PLUGINGUID]  NCHAR (32)     NOT NULL,
    [CHANGEDBY]   NVARCHAR (200) NOT NULL,
    [CHANGEDDATE] DATETIME       NOT NULL,
    CONSTRAINT [PK_CO_BESTPRACTICEINFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

