CREATE TABLE [CADIS_SYS].[CO_DBPARM] (
    [NAME]        NVARCHAR (50)   NOT NULL,
    [VALUE]       NVARCHAR (4000) NULL,
    [DESCRIPTION] NVARCHAR (100)  NOT NULL,
    [INSERTED]    DATETIME        DEFAULT (getdate()) NOT NULL,
    [UPDATED]     DATETIME        DEFAULT (getdate()) NOT NULL,
    [CHANGEDBY]   NVARCHAR (20)   DEFAULT ('UNKNOWN') NOT NULL,
    CONSTRAINT [PK_DBPARM] PRIMARY KEY CLUSTERED ([NAME] ASC)
);


GO
CREATE NONCLUSTERED INDEX [idxCADIS_System_Inserted]
    ON [CADIS_SYS].[CO_DBPARM]([INSERTED] ASC);


GO
CREATE NONCLUSTERED INDEX [idxCADIS_System_Updated]
    ON [CADIS_SYS].[CO_DBPARM]([UPDATED] ASC);


GO
CREATE NONCLUSTERED INDEX [idxCADIS_System_ChangedBy]
    ON [CADIS_SYS].[CO_DBPARM]([CHANGEDBY] ASC);

