CREATE TABLE [CADIS_SYS].[CO_EDMGROUP] (
    [ID]     UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
    [NAME]   NVARCHAR (250)   NOT NULL,
    [ACTIVE] BIT              NOT NULL,
    [TYPE]   TINYINT          NOT NULL,
    CONSTRAINT [PK_CO_EDMGROUP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

