CREATE TABLE [CADIS_SYS].[CO_EDMGROUPUSER] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GROUPID] UNIQUEIDENTIFIER NOT NULL,
    [USERID]  UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_CO_EDMGROUPUSER] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_EDMGROUPUSER_EDMGROUP] FOREIGN KEY ([GROUPID]) REFERENCES [CADIS_SYS].[CO_EDMGROUP] ([ID]),
    CONSTRAINT [FK_EDMGROUPUSER_WEBUSER] FOREIGN KEY ([USERID]) REFERENCES [CADIS_SYS].[CO_WEBUSER] ([ID])
);

