CREATE TABLE [CADIS_SYS].[CO_EDMGROUP_MEMBER_AUDIT] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GROUPID]      UNIQUEIDENTIFIER NOT NULL,
    [CHILDGROUPID] UNIQUEIDENTIFIER NULL,
    [DESCRIPTION]  NVARCHAR (600)   NOT NULL,
    [TYPE]         TINYINT          NOT NULL,
    [CHANGEDBY]    NVARCHAR (256)   NOT NULL,
    [CHANGEDDATE]  DATETIME         DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_CO_EDMGROUP_MEMBER_AUDIT] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

