CREATE TABLE [CADIS_SYS].[CO_GROUPPROCESS] (
    [GROUPID]     INT        NOT NULL,
    [GUID]        NCHAR (32) NOT NULL,
    [COMPONENTID] INT        NOT NULL,
    CONSTRAINT [PK_CO_GROUPPROCESS] PRIMARY KEY CLUSTERED ([GROUPID] ASC, [GUID] ASC, [COMPONENTID] ASC),
    CONSTRAINT [FK_CO_GROUPPROCESS_CO_GROUP] FOREIGN KEY ([GROUPID]) REFERENCES [CADIS_SYS].[CO_GROUP] ([GROUPID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_CO_GROUPPROCESS_GUID_COMPONENTID]
    ON [CADIS_SYS].[CO_GROUPPROCESS]([GUID] ASC, [COMPONENTID] ASC)
    INCLUDE([GROUPID]) WITH (FILLFACTOR = 80);

