CREATE TABLE [CADIS_SYS].[CO_GROUPLOCK] (
    [LOCKEDBY]     NVARCHAR (200) NOT NULL,
    [LOCKACQUIRED] DATETIME       NOT NULL,
    CONSTRAINT [PK_CO_GROUPLOCK] PRIMARY KEY CLUSTERED ([LOCKEDBY] ASC)
);

