CREATE TABLE [CADIS_SYS].[CO_GROUPUSER_AUDIT] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [CHANGEDBY]      NVARCHAR (256) NOT NULL,
    [CHANGEDDATE]    DATETIME       CONSTRAINT [DF_CO_GROUPUSER_AUDIT_CHANGEDDATE] DEFAULT (getdate()) NOT NULL,
    [ACTIONTYPE]     NVARCHAR (6)   NOT NULL,
    [GROUPID]        INT            NOT NULL,
    [NAME]           NVARCHAR (200) NULL,
    [USERTYPE]       TINYINT        NOT NULL,
    [PERMISSION]     SMALLINT       NULL,
    [NEW_PERMISSION] SMALLINT       NULL,
    CONSTRAINT [PK_CO_GROUPUSER_AUDIT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

