CREATE TABLE [CADIS_SYS].[CO_GROUP_AUDIT] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [CHANGEDBY]   NVARCHAR (256) NOT NULL,
    [CHANGEDDATE] DATETIME       CONSTRAINT [DF_CO_GROUP_AUDIT_CHANGEDDATE] DEFAULT (getdate()) NOT NULL,
    [ACTIONTYPE]  NVARCHAR (6)   NOT NULL,
    [NAME]        NVARCHAR (100) NOT NULL,
    [ORDER]       INT            NULL,
    [PARENTGROUP] INT            NULL,
    [SYSTEM]      BIT            NOT NULL,
    [TIMESTAMP]   BINARY (8)     NOT NULL,
    CONSTRAINT [PK_CO_GROUP_AUDIT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

