CREATE TABLE [CADIS_SYS].[CO_GLOBAL] (
    [NAME]       NVARCHAR (50) NOT NULL,
    [DETAILS]    IMAGE         NULL,
    [DEFINITION] XML           NULL,
    [CRC]        NCHAR (64)    NULL,
    CONSTRAINT [PK_CO_GLOBAL] PRIMARY KEY CLUSTERED ([NAME] ASC)
);

