CREATE TABLE [CADIS_SYS].[CO_PROCESS] (
    [GUID]        NCHAR (32)     NOT NULL,
    [NAME]        NVARCHAR (260) NOT NULL,
    [PROCESSTYPE] INT            NOT NULL,
    [IDENTIFIER]  INT            IDENTITY (1, 1) NOT NULL,
    [OBSOLETE]    TINYINT        CONSTRAINT [DF_CO_PROCESS_OBSOLETE] DEFAULT ((0)) NOT NULL,
    [INSERTED]    DATETIME       NOT NULL,
    [UPDATED]     DATETIME       NOT NULL,
    [CHANGEDBY]   NVARCHAR (100) NOT NULL,
    [CODE]        NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEFINITION]  XML            NULL,
    [CRC]         NCHAR (64)     NULL,
    [ENABLED]     BIT            DEFAULT ((1)) NOT NULL,
    [INFO1]       NVARCHAR (100) NULL,
    [LOCKKEY]     NVARCHAR (256) NULL,
    [TIMECODE]    VARCHAR (17)   NOT NULL,
    CONSTRAINT [PK_CO_PROCESS] PRIMARY KEY NONCLUSTERED ([GUID] ASC),
    CONSTRAINT [IX_CO_PROCESS] UNIQUE NONCLUSTERED ([NAME] ASC, [PROCESSTYPE] ASC, [OBSOLETE] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXPROCESSID]
    ON [CADIS_SYS].[CO_PROCESS]([IDENTIFIER] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_CO_PROCESS_OBSOLETE]
    ON [CADIS_SYS].[CO_PROCESS]([OBSOLETE] ASC)
    INCLUDE([GUID], [NAME], [PROCESSTYPE], [IDENTIFIER], [ENABLED], [INFO1]) WITH (FILLFACTOR = 80);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CO_PROCESS_CodeProccessTypeObsolete_UNIQUE]
    ON [CADIS_SYS].[CO_PROCESS]([CODE] ASC, [PROCESSTYPE] ASC, [OBSOLETE] ASC) WHERE ([CODE]<>'' AND [CODE] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IDX_CO_PROCESS_PROCESSTYPE_PROCTYPE_OBSOLETE]
    ON [CADIS_SYS].[CO_PROCESS]([PROCESSTYPE] ASC, [OBSOLETE] ASC)
    INCLUDE([NAME], [INFO1]) WITH (FILLFACTOR = 80);

