CREATE TABLE [CADIS_SYS].[CO_PROCESSLINK] (
    [ID]                 INT        IDENTITY (1, 1) NOT NULL,
    [FROMCOMPONENTTYPE]  INT        NOT NULL,
    [FROMGUID]           NCHAR (32) NOT NULL,
    [TOCOMPONENTTYPE]    INT        NOT NULL,
    [TOGUID]             NCHAR (32) NOT NULL,
    [OWNERCOMPONENTTYPE] INT        NOT NULL,
    [OWNERGUID]          NCHAR (32) NOT NULL,
    [LINKTYPE]           TINYINT    NOT NULL,
    CONSTRAINT [PK_CO_PROCESSLINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CO_PROCESSLINK_FROM]
    ON [CADIS_SYS].[CO_PROCESSLINK]([FROMCOMPONENTTYPE] ASC, [FROMGUID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_CO_PROCESSLINK_TO]
    ON [CADIS_SYS].[CO_PROCESSLINK]([TOCOMPONENTTYPE] ASC, [TOGUID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_CO_PROCESSLINK_OWNER]
    ON [CADIS_SYS].[CO_PROCESSLINK]([OWNERCOMPONENTTYPE] ASC, [OWNERGUID] ASC);

