CREATE TABLE [CADIS_SYS].[CO_PROCESSAUDIT] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [COMPONENTID] INT            NOT NULL,
    [IDENTIFIER]  INT            NOT NULL,
    [GUID]        NVARCHAR (32)  NOT NULL,
    [ACTION]      TINYINT        NOT NULL,
    [CHANGEDBY]   NVARCHAR (256) NOT NULL,
    [CHANGEDATE]  DATETIME       NOT NULL,
    CONSTRAINT [PK_CO_PROCESSAUDIT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

