CREATE TABLE [CADIS_SYS].[CO_PROCESSLOCK] (
    [LOCKID]       INT            IDENTITY (1, 1) NOT NULL,
    [COMPONENTID]  INT            NULL,
    [GUID]         NCHAR (32)     NOT NULL,
    [LOCKEDBY]     NVARCHAR (100) NOT NULL,
    [LOCKACQUIRED] DATETIME       NULL,
    [RUNNING]      BIT            NOT NULL,
    [UNIQUEID]     NVARCHAR (260) NULL,
    [SESSIONTOKEN] NVARCHAR (88)  NULL,
    CONSTRAINT [PK_CO_PROCESSLOCK] PRIMARY KEY CLUSTERED ([LOCKID] ASC),
    CONSTRAINT [UK_CO_PROCESSLOCK] UNIQUE NONCLUSTERED ([GUID] ASC, [UNIQUEID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_LOCK_COMPID_GUID]
    ON [CADIS_SYS].[CO_PROCESSLOCK]([COMPONENTID] ASC, [GUID] ASC);

