CREATE TABLE [CADIS_SYS].[CO_PROCESS_INFO] (
    [GUID]      NCHAR (32)     NOT NULL,
    [PARAMS]    XML            NULL,
    [INSERTED]  DATETIME       NOT NULL,
    [UPDATED]   DATETIME       NOT NULL,
    [CHANGEDBY] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_CO_PROCESS_PARAMETERS] PRIMARY KEY NONCLUSTERED ([GUID] ASC)
);

