CREATE TABLE [CADIS_SYS].[CO_PROCESSMESSAGE] (
    [ID]       INT            IDENTITY (1, 1) NOT NULL,
    [RUNTOKEN] INT            NOT NULL,
    [MSGID]    NVARCHAR (150) NOT NULL,
    [INSERTED] DATETIME       NOT NULL,
    [PLGUID]   NVARCHAR (32)  NOT NULL,
    CONSTRAINT [PK_CO_PROCESSMESSAGE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CO_PROCESSMONITOR_CO_PROCESSMESSAGE] FOREIGN KEY ([RUNTOKEN]) REFERENCES [CADIS_SYS].[CO_PROCESSMONITOR] ([RUNTOKEN])
);

