CREATE TABLE [CADIS_SYS].[CO_PROCESSLOG] (
    [LOGID]       INT             IDENTITY (1, 1) NOT NULL,
    [RUNID]       INT             NOT NULL,
    [LOGTIME]     DATETIME        NOT NULL,
    [LOGMESSAGE]  NVARCHAR (1024) NULL,
    [MESSAGETYPE] TINYINT         NOT NULL,
    CONSTRAINT [PK_CO_PROCESSLOG] PRIMARY KEY CLUSTERED ([LOGID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CADIS_SYSTEM_FK_PROCESSLOG_PROCESSHISTORY] FOREIGN KEY ([RUNID]) REFERENCES [CADIS_SYS].[CO_PROCESSHISTORY] ([RUNID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PLOG_RUNID]
    ON [CADIS_SYS].[CO_PROCESSLOG]([RUNID] ASC);

