CREATE TABLE [CADIS_SYS].[CO_SERVICE] (
    [NAME]        NVARCHAR (200) NOT NULL,
    [ADDRESS]     NVARCHAR (250) NOT NULL,
    [DESCRIPTION] NVARCHAR (100) NULL,
    CONSTRAINT [PK_CO_SERVICE] PRIMARY KEY CLUSTERED ([NAME] ASC, [ADDRESS] ASC)
);

