CREATE TABLE [CADIS_SYS].[CO_SITEMAP] (
    [ID]        INT            IDENTITY (1, 1) NOT NULL,
    [GROUP]     NVARCHAR (250) NOT NULL,
    [HEADER]    NVARCHAR (250) NOT NULL,
    [PAGE]      NVARCHAR (100) NOT NULL,
    [ALIAS]     NVARCHAR (100) NULL,
    [SORT]      INT            NOT NULL,
    [INSERTED]  DATETIME       NOT NULL,
    [UPDATED]   DATETIME       NOT NULL,
    [CHANGEDBY] NVARCHAR (100) NOT NULL,
    [PAGETYPE]  NVARCHAR (100) DEFAULT ('Workflow') NOT NULL,
    CONSTRAINT [PK_CO_SITEMAP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

