CREATE TABLE [CADIS_SYS].[CO_SOLUTION] (
    [GUID]       NCHAR (32)     NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL,
    [IDENTIFIER] INT            IDENTITY (1, 1) NOT NULL,
    [oldDetails] IMAGE          NULL,
    [OBSOLETE]   TINYINT        CONSTRAINT [DF_CO_SOLUTION_OBSOLETE] DEFAULT ((0)) NOT NULL,
    [INSERTED]   DATETIME       NOT NULL,
    [UPDATED]    DATETIME       NOT NULL,
    [CHANGEDBY]  NVARCHAR (100) NOT NULL,
    [DETAILS]    IMAGE          NULL,
    [CODE]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEFINITION] XML            NULL,
    [CRC]        NCHAR (64)     NULL,
    [ENABLED]    BIT            DEFAULT ((1)) NOT NULL,
    [INFO1]      NVARCHAR (100) NULL,
    [TIMECODE]   VARCHAR (17)   NOT NULL,
    CONSTRAINT [PK_CO_SOLUTION] PRIMARY KEY NONCLUSTERED ([GUID] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_SOLUTION1] UNIQUE NONCLUSTERED ([NAME] ASC, [OBSOLETE] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXSOLUTIONID]
    ON [CADIS_SYS].[CO_SOLUTION]([IDENTIFIER] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDXSOLUTIONOBSOLETE]
    ON [CADIS_SYS].[CO_SOLUTION]([NAME] ASC, [OBSOLETE] ASC);

