CREATE TABLE [CADIS_SYS].[CO_UNVERIFIED] (
    [COMPONENTID] INT        NOT NULL,
    [GUID]        NCHAR (32) NOT NULL,
    CONSTRAINT [PK_CO_UNVERIFIED] PRIMARY KEY CLUSTERED ([COMPONENTID] ASC, [GUID] ASC)
);

