CREATE TABLE [CADIS_SYS].[CO_USERSETTINGS] (
    [WORKFLOWID]  INT             NOT NULL,
    [STEPID]      INT             NOT NULL,
    [GROUPID]     INT             NOT NULL,
    [USERID]      NVARCHAR (100)  NOT NULL,
    [SETTINGS]    VARBINARY (MAX) NULL,
    [TIMESTAMP]   ROWVERSION      NOT NULL,
    [PROCESSTYPE] INT             CONSTRAINT [DF_CO_USERSETTINGS_PROCESSTYPE] DEFAULT ((0)) NOT NULL,
    [PROCESSGUID] NCHAR (32)      CONSTRAINT [DF_CO_USERSETTINGS_PROCESSID] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_CO_USERSETTINGS] PRIMARY KEY CLUSTERED ([WORKFLOWID] ASC, [STEPID] ASC, [GROUPID] ASC, [USERID] ASC, [PROCESSTYPE] ASC, [PROCESSGUID] ASC)
);

