CREATE TABLE [CADIS_SYS].[CO_WEBUSER_AUDIT] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [CHANGEDBY]   NVARCHAR (256)   NOT NULL,
    [CHANGEDDATE] DATETIME         CONSTRAINT [DF_CO_WEBUSER_AUDIT_CHANGEDDATE] DEFAULT (getdate()) NOT NULL,
    [ACTIONTYPE]  NVARCHAR (6)     NOT NULL,
    [USERNAME]    NVARCHAR (100)   NOT NULL,
    [EMAIL]       NVARCHAR (512)   NULL,
    [WebUserID]   UNIQUEIDENTIFIER NULL,
    [DISPLAYNAME] NVARCHAR (512)   NULL,
    [ACTIVE]      BIT              DEFAULT ((1)) NOT NULL,
    [WEBUSER]     BIT              DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_CO_WEBUSER_AUDIT] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CO_WEBUSER_AUDIT_WebUserid]
    ON [CADIS_SYS].[CO_WEBUSER_AUDIT]([WebUserID] ASC) WITH (FILLFACTOR = 80);

