CREATE TABLE [CADIS_SYS].[CO_WEBUSER_PROPOSALS] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [USERNAME]      NVARCHAR (100) NOT NULL,
    [ACTION]        SMALLINT       NOT NULL,
    [PROPOSER]      NVARCHAR (100) NOT NULL,
    [PROPOSAL_DATE] DATETIME       CONSTRAINT [DF_PROPOSAL_DATE] DEFAULT (getdate()) NOT NULL,
    [APPROVED]      BIT            NULL,
    [APPROVER]      NVARCHAR (100) NULL,
    [APPROVAL_DATE] DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

