CREATE TABLE [CADIS_SYS].[CO_WEBUSER_GROUP_PERMISSIONS_PROPOSALS] (
    [ID]                    INT      IDENTITY (1, 1) NOT NULL,
    [PROPOSAL_ID]           INT      NOT NULL,
    [ACTION]                SMALLINT NOT NULL,
    [GROUP_ID]              INT      NOT NULL,
    [PERMISSIONS]           SMALLINT NOT NULL,
    [CADIS_SYSTEM_INSERTED] DATETIME CONSTRAINT [DF_CADIS_SYSTEM_INSERTED] DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

