CREATE TABLE [CADIS_SYS].[CO_WEBUSER] (
    [ID]                     UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
    [USERNAME]               NVARCHAR (100)   NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    [EMAIL]                  NVARCHAR (512)   NULL,
    [DISPLAYNAME]            NVARCHAR (250)   NULL,
    [ACTIVE]                 BIT              DEFAULT ((1)) NOT NULL,
    [WEBUSER]                BIT              DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_CO_WEBUSER] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_CO_WEBUSER_USERNAME]
    ON [CADIS_SYS].[CO_WEBUSER]([USERNAME] ASC) WITH (FILLFACTOR = 80);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_CO_WEBUSER_DISPLAYNAME]
    ON [CADIS_SYS].[CO_WEBUSER]([DISPLAYNAME] ASC) WHERE ([DISPLAYNAME] IS NOT NULL) WITH (FILLFACTOR = 80);

