CREATE TABLE [CADIS_SYS].[CO_WEBUSERACTIVITY] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [USERNAME]     NVARCHAR (100) NOT NULL,
    [ACTIVITY]     NVARCHAR (25)  NULL,
    [TOKEN]        NVARCHAR (120) NOT NULL,
    [INSERTEDDATE] DATETIME2 (7)  CONSTRAINT [DF_INSERTEDDATE] DEFAULT (sysdatetime()) NULL,
    [DETAIL]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CO_WEBUSERACTIVITY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

