CREATE TABLE [CADIS_SYS].[DC_CONSTRUCTION] (
    [IDENTIFIER] INT            IDENTITY (1, 1) NOT NULL,
    [CODE]       NVARCHAR (10)  NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL,
    [DETAILS]    IMAGE          NULL,
    [INSERTED]   DATETIME       NOT NULL,
    [UPDATED]    DATETIME       NOT NULL,
    [CHANGEDBY]  NVARCHAR (256) NULL,
    [OBSOLETE]   INT            DEFAULT ((0)) NOT NULL,
    [GUID]       NCHAR (32)     NOT NULL,
    [DEFINITION] XML            NULL,
    [CRC]        NCHAR (64)     NULL,
    [ENABLED]    BIT            DEFAULT ((1)) NOT NULL,
    [LOCKKEY]    NVARCHAR (256) NULL,
    [TIMECODE]   VARCHAR (17)   NOT NULL,
    CONSTRAINT [PKCADIS_SYSTEM_DC_CONSTRUCTION] PRIMARY KEY NONCLUSTERED ([GUID] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DC_CONSTRUCTION1] UNIQUE NONCLUSTERED ([CODE] ASC, [OBSOLETE] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DC_CONSTRUCTION2] UNIQUE NONCLUSTERED ([NAME] ASC, [OBSOLETE] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DC_CONSTRUCTIONID] UNIQUE NONCLUSTERED ([IDENTIFIER] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXCONSTRUCTIONID]
    ON [CADIS_SYS].[DC_CONSTRUCTION]([IDENTIFIER] ASC);

