CREATE TABLE [CADIS_SYS].[DC_CUSTOMFNPARM] (
    [FNID]            INT            NOT NULL,
    [PARMORDER]       TINYINT        NOT NULL,
    [ISINPUT]         TINYINT        NOT NULL,
    [ISOUTPUT]        TINYINT        NOT NULL,
    [NAME]            NVARCHAR (20)  NOT NULL,
    [DESCRIPTION]     NVARCHAR (256) NOT NULL,
    [MAXSTRINGLENGTH] INT            NULL,
    CONSTRAINT [PKCADIS_SYSTEM_DC_CUSTOMFNPARM] PRIMARY KEY CLUSTERED ([FNID] ASC, [PARMORDER] ASC),
    CONSTRAINT [FKCADIS_SYSTEM_DC_CUSTOMFN_PARM] FOREIGN KEY ([FNID]) REFERENCES [CADIS_SYS].[DC_CUSTOMFN] ([FNID]),
    CONSTRAINT [UKCADIS_SYSTEM_DC_CUSTOMFNPARM] UNIQUE NONCLUSTERED ([FNID] ASC, [NAME] ASC)
);

