CREATE TABLE [CADIS_SYS].[DC_RULE] (
    [ID]             VARCHAR (36)   NOT NULL,
    [ORIGINALID]     VARCHAR (36)   NOT NULL,
    [RULEID]         INT            IDENTITY (1, 1) NOT NULL,
    [CONSTRUCTIONID] INT            NOT NULL,
    [TARGETFIELD]    [sysname]      NOT NULL,
    [PRIORITY]       SMALLINT       NOT NULL,
    [DESCRIPTION]    NVARCHAR (200) NOT NULL,
    [DETAILS]        IMAGE          NULL,
    [INSERTED]       DATETIME       NOT NULL,
    [INSERTEDBY]     NVARCHAR (256) NOT NULL,
    [DELETED]        DATETIME       NULL,
    [DELETEDBY]      NVARCHAR (256) NULL,
    CONSTRAINT [PKCADIS_SYSTEM_DC_RULE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FKCADIS_SYSTEM_DC_RULE_DC_CONSTRUCTION] FOREIGN KEY ([CONSTRUCTIONID]) REFERENCES [CADIS_SYS].[DC_CONSTRUCTION] ([IDENTIFIER]),
    CONSTRAINT [FKCADIS_SYSTEM_DC_RULE_DC_RULE] FOREIGN KEY ([ORIGINALID]) REFERENCES [CADIS_SYS].[DC_RULE] ([ID]),
    CONSTRAINT [UKCADIS_SYSTEM_DC_RULE1] UNIQUE NONCLUSTERED ([RULEID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX1CONSTRUCTIONRULE]
    ON [CADIS_SYS].[DC_RULE]([CONSTRUCTIONID] ASC, [DELETED] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULEORIGINAL]
    ON [CADIS_SYS].[DC_RULE]([ORIGINALID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULEDELETEDBY]
    ON [CADIS_SYS].[DC_RULE]([DELETEDBY] ASC);

