CREATE TABLE [CADIS_SYS].[DC_RUNINFO] (
    [RUNID]         INT            NOT NULL,
    [RUNSTART]      DATETIME       NOT NULL,
    [LAUNCHEDBY]    NVARCHAR (256) NULL,
    [TOPLEVELRUNID] INT            NULL,
    CONSTRAINT [PK_DC_RUNINFO] PRIMARY KEY CLUSTERED ([RUNID] ASC)
);

