CREATE TABLE [CADIS_SYS].[DGM_DIAGRAM] (
    [GUID]       NCHAR (32)     NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL,
    [IDENTIFIER] INT            IDENTITY (1, 1) NOT NULL,
    [OBSOLETE]   TINYINT        CONSTRAINT [DF_DGM_DIAGRAM_OBSOLETE] DEFAULT ((0)) NOT NULL,
    [INSERTED]   DATETIME       NOT NULL,
    [UPDATED]    DATETIME       NOT NULL,
    [CHANGEDBY]  NVARCHAR (100) NOT NULL,
    [DETAILS]    IMAGE          NULL,
    [CODE]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEFINITION] XML            NULL,
    [CRC]        NCHAR (64)     NULL,
    [ENABLED]    BIT            DEFAULT ((1)) NOT NULL,
    [TIMECODE]   VARCHAR (17)   NOT NULL,
    CONSTRAINT [PK_DGM_DIAGRAM] PRIMARY KEY NONCLUSTERED ([GUID] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DIAGRAM1] UNIQUE NONCLUSTERED ([NAME] ASC, [OBSOLETE] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXDIAGRAMID]
    ON [CADIS_SYS].[DGM_DIAGRAM]([IDENTIFIER] ASC);

