CREATE TABLE [CADIS_SYS].[DI_CUSTOMFN] (
    [FNID]        INT            IDENTITY (1, 1) NOT NULL,
    [FNGROUPID]   INT            NOT NULL,
    [NAME]        NVARCHAR (20)  NOT NULL,
    [DESCRIPTION] NVARCHAR (256) NOT NULL,
    [PROCNAME]    [sysname]      NOT NULL,
    [IO_BUFFER]   [sysname]      NOT NULL,
    CONSTRAINT [PKCADIS_SYSTEM_DI_CUSTOMFN] PRIMARY KEY CLUSTERED ([FNID] ASC),
    CONSTRAINT [FKCADIS_SYSTEM_DI_CUSTOMFN_GROUP] FOREIGN KEY ([FNGROUPID]) REFERENCES [CADIS_SYS].[DI_CUSTOMFNGROUP] ([FNGROUPID]),
    CONSTRAINT [UKCADIS_SYSTEM_DI_CUSTOMFN] UNIQUE NONCLUSTERED ([NAME] ASC)
);

