CREATE TABLE [CADIS_SYS].[DI_CUSTOMFNGROUP] (
    [FNGROUPID]   INT            IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (20)  NOT NULL,
    [DESCRIPTION] NVARCHAR (256) NOT NULL,
    CONSTRAINT [PKCADIS_SYSTEM_DI_CUSTOMFNGROUP] PRIMARY KEY CLUSTERED ([FNGROUPID] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DI_CUSTOMFNGROUP] UNIQUE NONCLUSTERED ([NAME] ASC)
);

