CREATE TABLE [CADIS_SYS].[DI_CUSTOMFNPARM] (
    [FNID]            INT            NOT NULL,
    [PARMORDER]       TINYINT        NOT NULL,
    [NAME]            NVARCHAR (20)  NOT NULL,
    [DESCRIPTION]     NVARCHAR (256) NOT NULL,
    [MAXSTRINGLENGTH] INT            NULL,
    CONSTRAINT [PKCADIS_SYSTEM_DI_CUSTOMFNPARM] PRIMARY KEY CLUSTERED ([FNID] ASC, [PARMORDER] ASC),
    CONSTRAINT [FKCADIS_SYSTEM_DI_CUSTOMFN_PARM] FOREIGN KEY ([FNID]) REFERENCES [CADIS_SYS].[DI_CUSTOMFN] ([FNID]),
    CONSTRAINT [UKCADIS_SYSTEM_DI_CUSTOMFNPARM] UNIQUE NONCLUSTERED ([FNID] ASC, [NAME] ASC)
);

