CREATE TABLE [CADIS_SYS].[DM_MATCHPOINT] (
    [GUID]       NCHAR (32)     NOT NULL,
    [CODE]       NVARCHAR (10)  NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL,
    [IDENTIFIER] INT            IDENTITY (1, 1) NOT NULL,
    [TABLENAME]  [sysname]      NULL,
    [DETAILS]    IMAGE          NULL,
    [OBSOLETE]   TINYINT        CONSTRAINT [DF_DM_MATCHPOINT_OBSOLETE] DEFAULT ((0)) NOT NULL,
    [INSERTED]   DATETIME       NOT NULL,
    [UPDATED]    DATETIME       NOT NULL,
    [CHANGEDBY]  NVARCHAR (100) NOT NULL,
    [LASTRUN]    DATETIME       NULL,
    [DEFINITION] XML            NULL,
    [CRC]        NCHAR (64)     NULL,
    [ENABLED]    BIT            DEFAULT ((1)) NOT NULL,
    [TIMECODE]   VARCHAR (17)   NOT NULL,
    CONSTRAINT [PK_DM_MATCHPOINT] PRIMARY KEY NONCLUSTERED ([GUID] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DM1] UNIQUE NONCLUSTERED ([CODE] ASC, [OBSOLETE] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DM2] UNIQUE NONCLUSTERED ([NAME] ASC, [OBSOLETE] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXMATCHPOINTID]
    ON [CADIS_SYS].[DM_MATCHPOINT]([IDENTIFIER] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXMATCHPOINTOBSOLETE]
    ON [CADIS_SYS].[DM_MATCHPOINT]([OBSOLETE] ASC);

