CREATE TABLE [CADIS_SYS].[DM_REALIGN_AUDIT] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [INSERTED]     DATETIME       NOT NULL,
    [INSERTEDBY]   NVARCHAR (100) NOT NULL,
    [COMMENT]      NVARCHAR (250) NULL,
    [TYPE]         TINYINT        NOT NULL,
    [MATCHPOINTID] INT            NOT NULL,
    [SOURCEID]     INT            NOT NULL,
    [OLDCADISID]   INT            NOT NULL,
    [CADISROWID]   INT            NOT NULL,
    [NEWCADISID]   INT            NULL,
    [SOURCEKEYS]   NVARCHAR (250) NOT NULL,
    CONSTRAINT [PK_DM_REALIGN_AUDIT] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDXREALIGNAUDITINSERTED]
    ON [CADIS_SYS].[DM_REALIGN_AUDIT]([INSERTED] ASC, [INSERTEDBY] ASC);

