CREATE TABLE [CADIS_SYS].[DM_RULE] (
    [ID]              NCHAR (32)     NOT NULL,
    [ORIGINALID]      NCHAR (32)     NOT NULL,
    [RULEID]          INT            IDENTITY (1, 1) NOT NULL,
    [SOURCEID]        INT            NOT NULL,
    [CONFIDENCELEVEL] INT            CONSTRAINT [DF_DM_RULE_CONFIDENCELEVEL] DEFAULT ((0)) NOT NULL,
    [PRIORITY]        SMALLINT       NOT NULL,
    [RULETYPE]        NVARCHAR (20)  CONSTRAINT [DF_DM_RULE_RULETYPE] DEFAULT ('User') NOT NULL,
    [DESCRIPTION]     NVARCHAR (200) NOT NULL,
    [DETAILS]         IMAGE          NULL,
    [MATCHTYPE]       TINYINT        NOT NULL,
    [INSERTED]        DATETIME       NOT NULL,
    [INSERTEDBY]      NVARCHAR (256) NOT NULL,
    [DELETED]         DATETIME       NULL,
    [DELETEDBY]       NVARCHAR (256) NULL,
    [TARGETID]        INT            CONSTRAINT [DF_DM_TARGET_ID] DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_DM_RULE] PRIMARY KEY NONCLUSTERED ([ID] ASC),
    CONSTRAINT [CK_DM_RULE_MATCHTYPE] CHECK ([MATCHTYPE]=(0) OR [MATCHTYPE]=(1) OR [MATCHTYPE]=(2)),
    CONSTRAINT [CK_DM_RULE_RULETYPE] CHECK ([RULETYPE]='User' OR [RULETYPE]='DefaultInsert' OR [RULETYPE]='ManualMatch' OR [RULETYPE]='ManualInsert'),
    CONSTRAINT [FK_DM_RULE_DM_RULE] FOREIGN KEY ([ORIGINALID]) REFERENCES [CADIS_SYS].[DM_RULE] ([ID]),
    CONSTRAINT [FK_DM_SOURCE_DM_RULE] FOREIGN KEY ([SOURCEID]) REFERENCES [CADIS_SYS].[DM_SOURCE] ([SOURCEID])
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXRULEID]
    ON [CADIS_SYS].[DM_RULE]([RULEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULEPRIORITY]
    ON [CADIS_SYS].[DM_RULE]([SOURCEID] ASC, [MATCHTYPE] ASC, [CONFIDENCELEVEL] ASC, [PRIORITY] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULETYPE]
    ON [CADIS_SYS].[DM_RULE]([SOURCEID] ASC, [RULETYPE] ASC, [DELETED] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULEORIGINAL]
    ON [CADIS_SYS].[DM_RULE]([ORIGINALID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULEINSERTEDBY]
    ON [CADIS_SYS].[DM_RULE]([INSERTEDBY] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULEDELETEDBY]
    ON [CADIS_SYS].[DM_RULE]([DELETEDBY] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXRULEACTIVE]
    ON [CADIS_SYS].[DM_RULE]([ID] ASC, [INSERTED] ASC, [DELETED] ASC);

