CREATE TABLE [CADIS_SYS].[DM_SOURCE] (
    [ID]                  NCHAR (32)     NOT NULL,
    [ORIGINALID]          NCHAR (32)     NOT NULL,
    [MATCHPOINTID]        INT            NOT NULL,
    [SOURCEID]            INT            NOT NULL,
    [SHORTNAME]           NVARCHAR (10)  NOT NULL,
    [LONGNAME]            NVARCHAR (50)  NOT NULL,
    [SOURCEOBJECTNAME]    NVARCHAR (128) NOT NULL,
    [SOURCEKEYS]          NVARCHAR (250) NOT NULL,
    [TABLENAME]           NVARCHAR (128) NOT NULL,
    [VIEWNAME]            NVARCHAR (128) NOT NULL,
    [PRIORITY]            SMALLINT       CONSTRAINT [DF_DM_SOURCE_PRIORITY] DEFAULT ((0)) NOT NULL,
    [AUTOCONFIDENCELEVEL] TINYINT        CONSTRAINT [DF_DM_SOURCE_CONFIDENCE] DEFAULT ((100)) NOT NULL,
    [REFERENCESOURCE]     BIT            CONSTRAINT [DF_DM_SOURCE_REFERENCE] DEFAULT ((0)) NOT NULL,
    [OBSOLETE]            TINYINT        CONSTRAINT [DF_DM_SOURCE_OBSOLETE] DEFAULT ((0)) NOT NULL,
    [INSERTED]            DATETIME       NOT NULL,
    [UPDATED]             DATETIME       NOT NULL,
    [CHANGEDBY]           NVARCHAR (100) NOT NULL,
    [RULETERMS]           NVARCHAR (500) DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_DM_SOURCE] PRIMARY KEY NONCLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DM_MATCHPOINT_DM_SOURCE] FOREIGN KEY ([MATCHPOINTID]) REFERENCES [CADIS_SYS].[DM_MATCHPOINT] ([IDENTIFIER]),
    CONSTRAINT [UKCADIS_SYSTEM_DM_SRC1] UNIQUE NONCLUSTERED ([MATCHPOINTID] ASC, [SHORTNAME] ASC, [OBSOLETE] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DM_SRC2] UNIQUE NONCLUSTERED ([MATCHPOINTID] ASC, [LONGNAME] ASC, [OBSOLETE] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXSOURCEID]
    ON [CADIS_SYS].[DM_SOURCE]([SOURCEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXSOURCEOBSOLETE]
    ON [CADIS_SYS].[DM_SOURCE]([MATCHPOINTID] ASC, [OBSOLETE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXSOURCEPRIORITY]
    ON [CADIS_SYS].[DM_SOURCE]([MATCHPOINTID] ASC, [PRIORITY] ASC, [OBSOLETE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXSOURCENAME]
    ON [CADIS_SYS].[DM_SOURCE]([MATCHPOINTID] ASC, [SHORTNAME] ASC, [OBSOLETE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXSOURCEORIGINAL]
    ON [CADIS_SYS].[DM_SOURCE]([ORIGINALID] ASC);

