CREATE TABLE [CADIS_SYS].[DP_DATAPORT] (
    [GUID]       NCHAR (32)     NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL,
    [IDENTIFIER] INT            IDENTITY (1, 1) NOT NULL,
    [DETAILS]    IMAGE          NULL,
    [OBSOLETE]   TINYINT        CONSTRAINT [DF_DP_DATAPORT_OBSOLETE] DEFAULT ((0)) NOT NULL,
    [INSERTED]   DATETIME       NOT NULL,
    [UPDATED]    DATETIME       NOT NULL,
    [CHANGEDBY]  NVARCHAR (100) NOT NULL,
    [CODE]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEFINITION] XML            NULL,
    [CRC]        NCHAR (64)     NULL,
    [ENABLED]    BIT            DEFAULT ((1)) NOT NULL,
    [LOCKKEY]    NVARCHAR (256) NULL,
    [TIMECODE]   VARCHAR (17)   NOT NULL,
    CONSTRAINT [PK_DP_DATAPORT] PRIMARY KEY NONCLUSTERED ([GUID] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_DP1] UNIQUE NONCLUSTERED ([NAME] ASC, [OBSOLETE] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXDATAPORTID]
    ON [CADIS_SYS].[DP_DATAPORT]([IDENTIFIER] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXDATAPORTOBSOLETE]
    ON [CADIS_SYS].[DP_DATAPORT]([OBSOLETE] ASC);

