CREATE TABLE [CADIS_SYS].[IL_ILLUSTRATORFIELDS] (
    [TEMPLATEID]        INT            NOT NULL,
    [ILLUSTRATORID]     INT            NOT NULL,
    [TEMPLATEFIELDNAME] NVARCHAR (256) NULL,
    [ILLFIELDNAME]      NVARCHAR (256) NOT NULL,
    CONSTRAINT [PK_IL_ILLUSTRATORFIELDS] PRIMARY KEY CLUSTERED ([ILLUSTRATORID] ASC, [ILLFIELDNAME] ASC)
);

