CREATE TABLE [CADIS_SYS].[PL_PROCESSLAUNCH] (
    [IDENTIFIER] INT            IDENTITY (1, 1) NOT NULL,
    [GUID]       NCHAR (32)     NOT NULL,
    [CODE]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL,
    [DETAILS]    IMAGE          NULL,
    [OBSOLETE]   TINYINT        DEFAULT ((0)) NOT NULL,
    [INSERTED]   DATETIME       NOT NULL,
    [UPDATED]    DATETIME       NOT NULL,
    [CHANGEDBY]  NVARCHAR (100) NOT NULL,
    [DEFINITION] XML            NULL,
    [CRC]        NCHAR (64)     NULL,
    [ENABLED]    BIT            DEFAULT ((1)) NOT NULL,
    [TIMECODE]   VARCHAR (17)   NOT NULL,
    CONSTRAINT [PK_PL_PROCESSLAUNCH] PRIMARY KEY CLUSTERED ([GUID] ASC)
);

