CREATE TABLE [CADIS_SYS].[PR_AUDIT_OLD] (
    [ID]           INT             IDENTITY (1, 1) NOT NULL,
    [SOURCE]       NVARCHAR (50)   NOT NULL,
    [AUDITTYPE]    SMALLINT        NOT NULL,
    [EVENTTYPE]    SMALLINT        NOT NULL,
    [AUDITSUMMARY] NVARCHAR (500)  NULL,
    [AUDITDETAILS] NVARCHAR (1500) NULL,
    [BODY]         NVARCHAR (500)  NULL,
    [COMPUTER]     NVARCHAR (50)   NULL,
    [USER]         NVARCHAR (100)  NULL,
    [CATEGORY]     NVARCHAR (100)  NULL,
    [TIME]         DATETIME        CONSTRAINT [DF_PR_AUDIT_TIME] DEFAULT (getdate()) NULL,
    [ENDTIME]      DATETIME        NULL,
    [PURGED]       BIT             CONSTRAINT [DF_PR_AUDIT_USER] DEFAULT ((0)) NULL,
    [TOKEN]        NVARCHAR (50)   NULL,
    CONSTRAINT [PK_PR_AUDIT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

