CREATE TABLE [CADIS_SYS].[PR_MESSAGE] (
    [COMPONENTID] INT            NOT NULL,
    [MESSAGEID]   NVARCHAR (200) NOT NULL,
    [INSERTED]    DATETIME       NULL,
    [UPDATED]     DATETIME       NULL,
    CONSTRAINT [PK_PR_MESSAGE] PRIMARY KEY CLUSTERED ([COMPONENTID] ASC)
);

