CREATE TABLE [CADIS_SYS].[PR_MESSAGEAUDIT] (
    [QUEUE_NAME]    NVARCHAR (100) NOT NULL,
    [MESSAGE_ID]    NVARCHAR (200) NOT NULL,
    [OWNER_RUNID]   INT            NOT NULL,
    [OWNER_UPDATED] DATETIME       NOT NULL,
    [MESSAGE_COUNT] INT            NOT NULL,
    CONSTRAINT [PK_PR_MESSAGEAUDIT] PRIMARY KEY CLUSTERED ([QUEUE_NAME] ASC)
);

