CREATE TABLE [CADIS_SYS].[RB_FUNCTION] (
    [GUID]       NCHAR (32)     NOT NULL,
    [IDENTIFIER] INT            IDENTITY (1, 1) NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL,
    [DETAILS]    IMAGE          NULL,
    [INSERTED]   DATETIME       NOT NULL,
    [UPDATED]    DATETIME       NOT NULL,
    [CHANGEDBY]  NVARCHAR (256) NULL,
    [OBSOLETE]   INT            DEFAULT ((0)) NOT NULL,
    [CODE]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEFINITION] XML            NULL,
    [CRC]        NCHAR (64)     NULL,
    [INFO1]      NVARCHAR (100) NULL,
    [ENABLED]    BIT            DEFAULT ((1)) NOT NULL,
    [INFO2]      NVARCHAR (100) NULL,
    [TIMECODE]   VARCHAR (17)   NOT NULL,
    CONSTRAINT [PKCADIS_SYSTEM_RB_FUNCTION] PRIMARY KEY NONCLUSTERED ([GUID] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_RB_FUNCTION1] UNIQUE NONCLUSTERED ([NAME] ASC, [OBSOLETE] ASC),
    CONSTRAINT [UKCADIS_SYSTEM_RB_FUNCTIONID] UNIQUE NONCLUSTERED ([IDENTIFIER] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDXRBFUNCTIONID]
    ON [CADIS_SYS].[RB_FUNCTION]([IDENTIFIER] ASC);

