CREATE TABLE [CADIS_SYS].[TMPDC_LTEXT_IDATA] (
    [CALLID]    INT             NOT NULL,
    [ROWKEY]    NVARCHAR (200)  NOT NULL,
    [SETNUMBER] TINYINT         NOT NULL,
    [ITEM]      NVARCHAR (3800) NULL,
    CONSTRAINT [PK_TMPDI_LTEXT_IDATA] PRIMARY KEY CLUSTERED ([CALLID] ASC, [ROWKEY] ASC, [SETNUMBER] ASC) WITH (FILLFACTOR = 80)
);

