CREATE TABLE [CADIS_SYS].[TMPDI_SEDOLVALIDATOR_IDATA] (
    [CALLID] INT            NOT NULL,
    [ROWKEY] NVARCHAR (200) NOT NULL,
    [SEDOL]  NVARCHAR (20)  NULL,
    [RESULT] INT            DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_TMPDI_SEDOLVALIDATOR_IDATA] PRIMARY KEY CLUSTERED ([CALLID] ASC, [ROWKEY] ASC) WITH (FILLFACTOR = 80)
);

