CREATE TABLE [CADIS_SYS].[TMPDI_FAILDUPLICATES_IDATA] (
    [CALLID] INT            NOT NULL,
    [ROWKEY] NVARCHAR (200) NOT NULL,
    [ITEM]   NVARCHAR (500) NULL,
    [RESULT] INT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TMPDI_FAILDUPLICATES_IDATA] PRIMARY KEY CLUSTERED ([CALLID] ASC, [ROWKEY] ASC) WITH (FILLFACTOR = 80)
);

