CREATE TABLE [CADIS_SYS].[TMPDC_MINVAL_IDATA] (
    [CALLID]    INT            NOT NULL,
    [ROWKEY]    NVARCHAR (200) NOT NULL,
    [SETNUMBER] TINYINT        NOT NULL,
    [VALUE]     FLOAT (53)     NULL,
    CONSTRAINT [PK_TMPDC_MINVAL_IDATA] PRIMARY KEY CLUSTERED ([CALLID] ASC, [ROWKEY] ASC, [SETNUMBER] ASC) WITH (FILLFACTOR = 80)
);

