CREATE TABLE [KPI].[KPIGroupRelationship] (
    [KPIId]                     SMALLINT      NOT NULL,
    [KPIGroupId]                SMALLINT      NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF_KGR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF_KGR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF_KGR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF_KGR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF_KGR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKKPIGroupRelationship] PRIMARY KEY CLUSTERED ([KPIId] ASC, [KPIGroupId] ASC),
    CONSTRAINT [KPIGroupRelationshipKPIGroupId] FOREIGN KEY ([KPIGroupId]) REFERENCES [KPI].[KPIGroups] ([KPIGroupId]),
    CONSTRAINT [KPIGroupRelationshipKPIId] FOREIGN KEY ([KPIId]) REFERENCES [KPI].[MeasuredKPIs-old] ([KPIId])
);


GO
ALTER TABLE [KPI].[KPIGroupRelationship] NOCHECK CONSTRAINT [KPIGroupRelationshipKPIId];

