CREATE TABLE [KPI].[RefreshFrequency] (
    [RefreshFrequencyId]        SMALLINT       IDENTITY (1, 1) NOT NULL,
    [FrequencyName]             NVARCHAR (128) NOT NULL,
    [DaysRange]                 SMALLINT       DEFAULT ((90)) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME       CONSTRAINT [DF_KRF_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME       CONSTRAINT [DF_KRF_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)  CONSTRAINT [DF_KRF_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT            CONSTRAINT [DF_KRF_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION     NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME       CONSTRAINT [DF_KRF_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKRefreshFrequency] PRIMARY KEY CLUSTERED ([FrequencyName] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UXIRefreshFrequency]
    ON [KPI].[RefreshFrequency]([RefreshFrequencyId] ASC);

