CREATE TABLE [dbo].[Compliance_KYCRiskRating] (
    [RiskRatingID]           TINYINT       IDENTITY (1, 1) NOT NULL,
    [RiskRatingName]         VARCHAR (50)  NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PKCompliance_KYCRiskRating] PRIMARY KEY CLUSTERED ([RiskRatingID] ASC) WITH (FILLFACTOR = 80)
);

