CREATE TABLE [dbo].[Compliance_KYCChecklist] (
    [ChecklistID]             INT              IDENTITY (1, 1) NOT NULL,
    [LegalEntityTypeID]       SMALLINT         NOT NULL,
    [IncorporationCountryID]  INT              NOT NULL,
    [JurisdictionCountryID]   INT              NOT NULL,
    [StatusID]                INT              NOT NULL,
    [Name]                    VARCHAR (50)     NULL,
    [ReviewDate]              DATETIME         NOT NULL,
    [NextReviewDate]          DATETIME         NOT NULL,
    [OutputFromScreening]     VARCHAR (2000)   NULL,
    [FalsePositives]          VARCHAR (2000)   NULL,
    [AdditionalFactors]       VARCHAR (2000)   NULL,
    [DocumentsReviewed]       VARCHAR (2000)   NULL,
    [Documentationfolderlink] VARCHAR (50)     NOT NULL,
    [Rationale]               VARCHAR (2000)   NULL,
    [ReviewedByPersonID]      SMALLINT         NULL,
    [SDDApproved]             BIT              NULL,
    [SubmittedByPersonID]     SMALLINT         NULL,
    [JoinGUID]                UNIQUEIDENTIFIER NOT NULL,
    [CADIS_SYSTEM_INSERTED]   DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]    DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]  NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    [IsActive]                BIT              DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PKCompliance_KYCChecklist] PRIMARY KEY CLUSTERED ([ChecklistID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [KYCIncorporationCountryID] FOREIGN KEY ([IncorporationCountryID]) REFERENCES [dbo].[Compliance_KYCCountries] ([CountryID]),
    CONSTRAINT [KYCJurisdictionCountryID] FOREIGN KEY ([JurisdictionCountryID]) REFERENCES [dbo].[Compliance_KYCCountries] ([CountryID]),
    CONSTRAINT [KYCLegalEntityTypeID] FOREIGN KEY ([LegalEntityTypeID]) REFERENCES [dbo].[Compliance_KYCLegalEntityTypes] ([LegalEntityTypeID]),
    CONSTRAINT [KYCReviewedByPersonID] FOREIGN KEY ([ReviewedByPersonID]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [KYCStatusId] FOREIGN KEY ([StatusID]) REFERENCES [Core].[FlowStatus] ([FlowStatusId]),
    CONSTRAINT [KYCSubmittedByPersonID] FOREIGN KEY ([SubmittedByPersonID]) REFERENCES [Core].[Persons] ([PersonId])
);

