CREATE TABLE [dbo].[FundContents] (
    [EDM_FND_ID]             VARCHAR (50) NULL,
    [SHORT_NAME]             VARCHAR (50) NULL,
    [LONG_NAME]              VARCHAR (50) NULL,
    [EDM_FUND_GROUP_ID]      VARCHAR (50) NULL,
    [START_DATE]             VARCHAR (50) NULL,
    [FUND_TYPE]              VARCHAR (50) NULL,
    [STATUS]                 VARCHAR (50) NULL,
    [BASE_CURRENCY]          VARCHAR (50) NULL,
    [LOCATION]               VARCHAR (50) NULL,
    [CADIS_SYSTEM_INSERTED]  VARCHAR (50) NULL,
    [CADIS_SYSTEM_UPDATED]   VARCHAR (50) NULL,
    [CADIS_SYSTEM_CHANGEDBY] VARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]  VARCHAR (50) NULL,
    [VALUATION_PERIOD]       VARCHAR (50) NULL
);

