CREATE TABLE [dbo].[T_BBG_MASTER_BROKER] (
    [MASTER_BROKER_NUMBER]      VARCHAR (40)  NOT NULL,
    [MASTER_BROKER_SHORT_NAME]  VARCHAR (40)  NULL,
    [MASTER_BROKER_LONG_NAME]   VARCHAR (40)  NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([MASTER_BROKER_NUMBER] ASC) WITH (FILLFACTOR = 80)
);

