CREATE TABLE [dbo].[T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_RepoFields_IN] (
    [CADIS_BATCH_ID]                          INT            NOT NULL,
    [CADIS_MSG_ID]                            INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__16FBAD24] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                         INT            NOT NULL,
    [CADIS_ROW_ID]                            INT            NOT NULL,
    [esxsd:Haircut]                           NVARCHAR (MAX) NULL,
    [esxsd:ForwardDate]                       NVARCHAR (MAX) NULL,
    [esxsd:TerminationDays]                   NVARCHAR (MAX) NULL,
    [esxsd:TransactionType]                   NVARCHAR (MAX) NULL,
    [esxsd:DeliveryType]                      NVARCHAR (MAX) NULL,
    [esxsd:DayCount]                          NVARCHAR (MAX) NULL,
    [esxsd:RepoTraderAccountAssignment]       NVARCHAR (MAX) NULL,
    [esxsd:Substitute]                        NVARCHAR (MAX) NULL,
    [esxsd:OpenRepoFlag]                      NVARCHAR (MAX) NULL,
    [esxsd:EarlyDeliveryFlag]                 NVARCHAR (MAX) NULL,
    [esxsd:PriceRoundingFlag]                 NVARCHAR (MAX) NULL,
    [esxsd:RoundToNearest]                    NVARCHAR (MAX) NULL,
    [esxsd:AllInPrice]                        NVARCHAR (MAX) NULL,
    [esxsd:ForwardPrice]                      NVARCHAR (MAX) NULL,
    [esxsd:Margin]                            NVARCHAR (MAX) NULL,
    [esxsd:CumulativeAccruedInterest]         NVARCHAR (MAX) NULL,
    [esxsd:OpenRepoCloseOutFlag]              NVARCHAR (MAX) NULL,
    [esxsd:TerminationDate]                   NVARCHAR (MAX) NULL,
    [esxsd:TerminationMoney]                  NVARCHAR (MAX) NULL,
    [esxsd:RepoStatusIndicator]               NVARCHAR (MAX) NULL,
    [esxsd:CouponReinvestmentFlag]            NVARCHAR (MAX) NULL,
    [esxsd:BondBorrowRate]                    NVARCHAR (MAX) NULL,
    [esxsd:BondBorrowFeeAmount]               NVARCHAR (MAX) NULL,
    [esxsd:NumberOfSubstitutions]             NVARCHAR (MAX) NULL,
    [esxsd:NumberSubstituted]                 NVARCHAR (MAX) NULL,
    [esxsd:EuroDiscrepancy]                   NVARCHAR (MAX) NULL,
    [esxsd:MasterOrSwingTicket]               NVARCHAR (MAX) NULL,
    [esxsd:FirmbookOrMatchbookForTrader]      NVARCHAR (MAX) NULL,
    [esxsd:FirmbookOrMatchbookForSwingTrader] NVARCHAR (MAX) NULL,
    [esxsd:HistoricalRerateDate]              NVARCHAR (MAX) NULL,
    [esxsd:RepoProductType]                   NVARCHAR (MAX) NULL,
    [esxsd:RelativeSwingTicketNumber]         NVARCHAR (MAX) NULL,
    [esxsd:TermPrice]                         NVARCHAR (MAX) NULL,
    [esxsd:StartPrice]                        NVARCHAR (MAX) NULL,
    [esxsd:TermDayAccrued]                    NVARCHAR (MAX) NULL,
    [esxsd:PriceMethod]                       NVARCHAR (MAX) NULL,
    [esxsd:BESAConvention]                    NVARCHAR (MAX) NULL,
    [esxsd:RepoRollover]                      NVARCHAR (MAX) NULL,
    [esxsd:JointRepo]                         NVARCHAR (MAX) NULL,
    [esxsd:HaircutOption]                     NVARCHAR (MAX) NULL,
    [esxsd:JapaneseBondType]                  NVARCHAR (MAX) NULL,
    [esxsd:AdjTerminationMoney]               NVARCHAR (MAX) NULL,
    [esxsd:OverPeriodCoupon]                  NVARCHAR (MAX) NULL,
    [esxsd:OriginalReference]                 NVARCHAR (MAX) NULL,
    [esxsd:ProfitSharingRatio]                NVARCHAR (MAX) NULL,
    [esxsd:EarlyCloseoutFlag]                 NVARCHAR (MAX) NULL,
    [esxsd:RepoRerateFlag]                    NVARCHAR (MAX) NULL,
    [esxsd:RerateDate]                        NVARCHAR (MAX) NULL,
    [esxsd:RerateRate]                        NVARCHAR (MAX) NULL,
    [esxsd:RolledOverTicket]                  NVARCHAR (MAX) NULL,
    [esxsd:RepoDealerRate]                    NVARCHAR (MAX) NULL,
    [esxsd:VariablePensionLivreeIndex]        NVARCHAR (MAX) NULL,
    [esxsd:BusinessDayCcy]                    NVARCHAR (MAX) NULL,
    [esxsd:Benchmark]                         NVARCHAR (MAX) NULL,
    [esxsd:FullTermProfitSharing]             NVARCHAR (MAX) NULL,
    [esxsd:WithholdingTax]                    NVARCHAR (MAX) NULL,
    [esxsd:ContactNote]                       NVARCHAR (MAX) NULL,
    [esxsd:RepoSecAccrued]                    NVARCHAR (MAX) NULL,
    [esxsd:RepricedFlag]                      NVARCHAR (MAX) NULL,
    [esxsd:CrossCurrencyFlag]                 NVARCHAR (MAX) NULL,
    [esxsd:StructureType]                     NVARCHAR (MAX) NULL,
    [esxsd:ExtensionDate]                     NVARCHAR (MAX) NULL,
    [esxsd:MinimumNoticePeriod]               NVARCHAR (MAX) NULL,
    [esxsd:Variance]                          NVARCHAR (MAX) NULL,
    [esxsd:GenericLabel]                      NVARCHAR (MAX) NULL,
    [esxsd:RepoRepriceOriginalTicket]         NVARCHAR (MAX) NULL,
    [esxsd:SellerLegalEntity]                 NVARCHAR (MAX) NULL,
    [esxsd:CarryoverRepoTradeFlag]            NVARCHAR (MAX) NULL,
    [esxsd:ExtendedPrecisionRepoPrice]        NVARCHAR (MAX) NULL,
    [esxsd:ExtendedPrecisionForwardPrice]     NVARCHAR (MAX) NULL,
    [esxsd:ExtendedPrecisionAccruedPrice]     NVARCHAR (MAX) NULL,
    [esxsd:OriginalCost]                      NVARCHAR (MAX) NULL,
    [esxsd:IndicativeCost]                    NVARCHAR (MAX) NULL,
    [esxsd:CalcType]                          NVARCHAR (MAX) NULL,
    [esxsd:Reversibility]                     NVARCHAR (MAX) NULL,
    [esxsd:InterestFlag]                      NVARCHAR (MAX) NULL,
    [CADIS_SYSTEM_INSERTED]                   DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__17EFD15D] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                    DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__18E3F596] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                  NVARCHAR (50)  CONSTRAINT [DF__T_BBAIM_X__CADIS__19D819CF] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                   INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__1ACC3E08] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_RepoFields_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

