CREATE TABLE [dbo].[T_BBG_COMPLIANCE_TRADE_VIOL_BUCKET_SECURITY] (
    [CADIS_PARENT_ID]      VARCHAR (50) NULL,
    [SECURITY_SECBOOKVAL]  VARCHAR (50) NULL,
    [SECURITY_SECBUYSELL]  VARCHAR (50) NULL,
    [SECURITY_SECDESC]     VARCHAR (50) NULL,
    [SECURITY_SECIDENT]    VARCHAR (50) NULL,
    [SECURITY_SECMKTVAL]   VARCHAR (50) NULL,
    [SECURITY_SECPARVAL]   VARCHAR (50) NULL,
    [SECURITY_SECPOSITION] VARCHAR (50) NULL,
    [SECURITY_SECPRICE]    VARCHAR (50) NULL,
    [SECURITY_SECCURNCY]   VARCHAR (50) NULL
);

