CREATE TABLE [dbo].[T_BBG_COMPLIANCE_RULE_REVISION_RULEGROUP] (
    [CADIS_PARENT_ID]               VARCHAR (50)  NULL,
    [RULEGROUP_RULEGROUPNAMEAFTER]  VARCHAR (50)  NULL,
    [RULEGROUP_RULEGROUPNAMEBEFORE] VARCHAR (50)  NULL,
    [RULEGROUP_FOLDERNAMEAFTER]     VARCHAR (50)  NULL,
    [RULEGROUP_FOLDERNAMEBEFORE]    VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]         DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__42FC8CF8] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]          DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__43F0B131] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]        NVARCHAR (50) CONSTRAINT [DF__T_BBG_COM__CADIS__44E4D56A] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]         INT           CONSTRAINT [DF__T_BBG_COM__CADIS__45D8F9A3] DEFAULT ((1)) NULL
);

