CREATE TABLE [dbo].[T_BBG_COMPLIANCE_RULE_BROKERS] (
    [CADIS_PARENT_ID]        VARCHAR (50)  NULL,
    [EVALUATION_EVALTYPE]    VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTNAME]      VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTTYPE]      VARCHAR (50)  NULL,
    [SCOPE_BROKERNAME]       VARCHAR (50)  NULL,
    [SCOPE_BROKERTYPE]       VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL
);

