CREATE TABLE [dbo].[T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_Common_esxsd_Loan_IN] (
    [CADIS_BATCH_ID]              INT            NOT NULL,
    [CADIS_MSG_ID]                INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__3985CF52] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]             INT            NOT NULL,
    [CADIS_ROW_ID]                INT            NOT NULL,
    [esxsd:Description]           NVARCHAR (MAX) NULL,
    [esxsd:TradeType]             NVARCHAR (MAX) NULL,
    [esxsd:TradeTerm]             NVARCHAR (MAX) NULL,
    [esxsd:InterestMethod]        NVARCHAR (MAX) NULL,
    [esxsd:AssignType]            NVARCHAR (MAX) NULL,
    [esxsd:AssignFee]             NVARCHAR (MAX) NULL,
    [esxsd:FundedNotional]        NVARCHAR (MAX) NULL,
    [esxsd:UnfundedNotional]      NVARCHAR (MAX) NULL,
    [esxsd:UnfundedLOC]           NVARCHAR (MAX) NULL,
    [esxsd:DelayedComp]           NVARCHAR (MAX) NULL,
    [esxsd:Paydown]               NVARCHAR (MAX) NULL,
    [esxsd:NonRecurFee]           NVARCHAR (MAX) NULL,
    [esxsd:OtherFee]              NVARCHAR (MAX) NULL,
    [esxsd:ActualSettleDate]      NVARCHAR (MAX) NULL,
    [esxsd:ContractualSettleDate] NVARCHAR (MAX) NULL,
    [CADIS_SYSTEM_INSERTED]       DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__3A79F38B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]        DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__3B6E17C4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]      NVARCHAR (50)  CONSTRAINT [DF__T_BBAIM_X__CADIS__3C623BFD] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]       INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__3D566036] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_Common_esxsd_Loan_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

