CREATE TABLE [dbo].[T_BBG_CASH_LADDER_PRE] (
    [FILE_NAME]              VARCHAR (100)  NULL,
    [FILE_DATE]              VARCHAR (20)   NULL,
    [FILE_TYPE]              VARCHAR (4)    NULL,
    [CASH_LADDER_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [ROW_DATA]               VARCHAR (8000) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)  DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([CASH_LADDER_ID] ASC) WITH (FILLFACTOR = 80)
);

