CREATE TABLE [dbo].[T_BBG_COMPLIANCE_EOD_VIOLATION_BUCKET] (
    [CADIS_PARENT_ID]        VARCHAR (50)  NULL,
    [BUCKET_BUCKETBOOKVAL]   VARCHAR (50)  NULL,
    [BUCKET_BUCKETMKTVAL]    VARCHAR (50)  NULL,
    [BUCKET_BUCKETNAME]      VARCHAR (50)  NULL,
    [BUCKET_BUCKETPARVAL]    VARCHAR (50)  NULL,
    [BUCKET_BUCKETTESTVAL]   VARCHAR (50)  NULL,
    [SECURITY_SECBOOKVAL]    VARCHAR (50)  NULL,
    [SECURITY_SECBUYSELL]    VARCHAR (50)  NULL,
    [SECURITY_SECCURNCY]     VARCHAR (50)  NULL,
    [SECURITY_SECDESC]       VARCHAR (50)  NULL,
    [SECURITY_SECIDENT]      VARCHAR (50)  NULL,
    [SECURITY_SECMKTVAL]     VARCHAR (50)  NULL,
    [SECURITY_SECPARVAL]     VARCHAR (50)  NULL,
    [SECURITY_SECPOSITION]   VARCHAR (50)  NULL,
    [SECURITY_SECPRICE]      VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__27DE8268] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__28D2A6A1] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_BBG_COM__CADIS__29C6CADA] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_BBG_COM__CADIS__2ABAEF13] DEFAULT ((1)) NULL
);

