CREATE TABLE [dbo].[T_BBG_DAILY_FUND_PERFORMANCE_IN] (
    [PortfolioGroup]            VARCHAR (256)   NULL,
    [Fund]                      VARCHAR (20)    NULL,
    [Filler]                    VARCHAR (20)    NULL,
    [ReportDate]                DATE            NULL,
    [FileName]                  VARCHAR (256)   NULL,
    [FileType]                  VARCHAR (256)   NULL,
    [EndWeightPort]             VARCHAR (256)   NULL,
    [EndWeightBench]            DECIMAL (19, 5) NULL,
    [EndWeight]                 DECIMAL (19, 5) NULL,
    [RtnDayPort]                DECIMAL (19, 5) NULL,
    [RtnDayBench]               DECIMAL (19, 5) NULL,
    [RtnDay]                    DECIMAL (19, 5) NULL,
    [RtnWtdPort]                DECIMAL (19, 5) NULL,
    [RtnWtdBench]               DECIMAL (19, 5) NULL,
    [RtnWtd]                    DECIMAL (19, 5) NULL,
    [RtnMtdPort]                DECIMAL (19, 5) NULL,
    [RtnMtdBench]               DECIMAL (19, 5) NULL,
    [RtnMtd]                    DECIMAL (19, 5) NULL,
    [RtnQtdPort]                DECIMAL (19, 5) NULL,
    [RtnQtdBench]               DECIMAL (19, 5) NULL,
    [RtnQtd]                    DECIMAL (19, 5) NULL,
    [RtnYtdPort]                DECIMAL (19, 5) NULL,
    [RtnYtdBench]               DECIMAL (19, 5) NULL,
    [RtnYtd]                    DECIMAL (19, 5) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION      NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        NULL
);

