CREATE TABLE [dbo].[T_BBG_COMPLIANCE_TRADE_VIOL_TRADER_NOTE_DETAIL] (
    [CADIS_PARENT_ID]      VARCHAR (50)    NULL,
    [NOTEDETAILS_DATETIME] VARCHAR (50)    NULL,
    [NOTEDETAILS_NOTE]     NVARCHAR (1000) NULL,
    [NOTEDETAILS_USER]     VARCHAR (50)    NULL
);

