CREATE TABLE [dbo].[T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_FXFields_esxsd_FXOption_IN] (
    [CADIS_BATCH_ID]          INT            NOT NULL,
    [CADIS_MSG_ID]            INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__6840BE3B] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]         INT            NOT NULL,
    [CADIS_ROW_ID]            INT            NOT NULL,
    [esxsd:AlternativeID]     NVARCHAR (MAX) NULL,
    [esxsd:ExpirationTime]    NVARCHAR (MAX) NULL,
    [esxsd:ExpirationCityTZ]  NVARCHAR (MAX) NULL,
    [esxsd:LocalCutTime]      NVARCHAR (MAX) NULL,
    [esxsd:GMTCutTime]        NVARCHAR (MAX) NULL,
    [esxsd:SpotPrice]         NVARCHAR (MAX) NULL,
    [esxsd:PriceCurrency]     NVARCHAR (MAX) NULL,
    [esxsd:Premium]           NVARCHAR (MAX) NULL,
    [esxsd:Delta]             NVARCHAR (MAX) NULL,
    [esxsd:SpotHedge]         NVARCHAR (MAX) NULL,
    [esxsd:Gamma]             NVARCHAR (MAX) NULL,
    [esxsd:Vega]              NVARCHAR (MAX) NULL,
    [esxsd:Theta]             NVARCHAR (MAX) NULL,
    [esxsd:Rho]               NVARCHAR (MAX) NULL,
    [esxsd:Vomma]             NVARCHAR (MAX) NULL,
    [esxsd:Vanna]             NVARCHAR (MAX) NULL,
    [esxsd:CallPutCurrency]   NVARCHAR (MAX) NULL,
    [esxsd:CallPutIndicator]  NVARCHAR (MAX) NULL,
    [esxsd:Strike]            NVARCHAR (MAX) NULL,
    [esxsd:NotionalCurrency]  NVARCHAR (MAX) NULL,
    [esxsd:NotionalAmount]    NVARCHAR (MAX) NULL,
    [esxsd:OptionStatus]      NVARCHAR (MAX) NULL,
    [esxsd:BarrierStartDate]  NVARCHAR (MAX) NULL,
    [esxsd:BarrierEndDate]    NVARCHAR (MAX) NULL,
    [esxsd:BarrierDirection]  NVARCHAR (MAX) NULL,
    [esxsd:UpperBarrierLevel] NVARCHAR (MAX) NULL,
    [esxsd:LowerBarrierLevel] NVARCHAR (MAX) NULL,
    [esxsd:UpperRebate]       NVARCHAR (MAX) NULL,
    [esxsd:LowerRebate]       NVARCHAR (MAX) NULL,
    [esxsd:PayoffStyle]       NVARCHAR (MAX) NULL,
    [esxsd:PayoffCurrency]    NVARCHAR (MAX) NULL,
    [esxsd:DeliveryDate]      NVARCHAR (MAX) NULL,
    [esxsd:BaseCurrency]      NVARCHAR (MAX) NULL,
    [esxsd:CommodityCurrency] NVARCHAR (MAX) NULL,
    [esxsd:PremiumDate]       NVARCHAR (MAX) NULL,
    [esxsd:ExerciseType]      NVARCHAR (MAX) NULL,
    [esxsd:OptionType]        NVARCHAR (MAX) NULL,
    [esxsd:FXTimeZone]        NVARCHAR (MAX) NULL,
    [esxsd:PayoffAmount]      NVARCHAR (MAX) NULL,
    [CADIS_SYSTEM_INSERTED]   DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__6934E274] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]    DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__6A2906AD] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]  NVARCHAR (50)  CONSTRAINT [DF__T_BBAIM_X__CADIS__6B1D2AE6] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]   INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__6C114F1F] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_FXFields_esxsd_FXOption_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

