CREATE TABLE [dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT] (
    [FILE_DATE]                DATETIME        NOT NULL,
    [FILE_NAME]                VARCHAR (50)    NULL,
    [I_AUDITID]                BIGINT          NOT NULL,
    [D_DATE]                   DATETIME        NOT NULL,
    [T_TIME]                   TIME (7)        NULL,
    [F_ALLOCATED_QUANTITY]     DECIMAL (18, 6) NULL,
    [I_TERMDAYS]               INT             NULL,
    [I_TSORDNUM]               INT             NULL,
    [C_RECORDTYPE]             VARCHAR (4)     NULL,
    [C_SECURITY]               VARCHAR (30)    NULL,
    [I_FLAG]                   INT             NULL,
    [I_SUBFLAG]                INT             NULL,
    [C_IDENTIFIER]             VARCHAR (12)    NULL,
    [I_MTKTNUM]                INT             NULL,
    [I_TKTNUM]                 INT             NULL,
    [C_ACCOUNT]                VARCHAR (8)     NULL,
    [C_USER]                   VARCHAR (12)    NULL,
    [C_FUNCTION]               VARCHAR (4)     NULL,
    [C_EVENT]                  VARCHAR (30)    NULL,
    [F_QUANTITY]               DECIMAL (18, 6) NULL,
    [F_PRICE]                  DECIMAL (18, 6) NULL,
    [C_CURRENCY]               VARCHAR (3)     NULL,
    [C_BROKER]                 VARCHAR (10)    NULL,
    [C_ORDSTATUS]              VARCHAR (12)    NULL,
    [C_ORDTYPE]                VARCHAR (4)     NULL,
    [C_TIF]                    VARCHAR (3)     NULL,
    [C_BASKETNAME]             VARCHAR (36)    NULL,
    [C_SIDE]                   VARCHAR (5)     NULL,
    [D_ASOFDATE]               DATETIME        NULL,
    [T_ASOFTIME]               TIME (7)        NULL,
    [D_CREATEDATE]             DATETIME        NULL,
    [T_CREATETIME]             TIME (7)        NULL,
    [F_LIMITPRC]               DECIMAL (18, 6) NULL,
    [C_PM]                     VARCHAR (12)    NULL,
    [C_TRADER]                 VARCHAR (12)    NULL,
    [F_STOPPRC]                DECIMAL (18, 6) NULL,
    [C_INSTR]                  VARCHAR (44)    NULL,
    [C_EXECINSTR]              VARCHAR (80)    NULL,
    [C_AUTOALLOC]              VARCHAR (3)     NULL,
    [C_JAPALLOC]               VARCHAR (3)     NULL,
    [D_SETTLEDT]               DATETIME        NULL,
    [D_GTD]                    DATETIME        NULL,
    [C_PA]                     VARCHAR (9)     NULL,
    [I_BASKETNO]               INT             NULL,
    [C_IPO]                    VARCHAR (3)     NULL,
    [C_TRADEFLAT]              VARCHAR (3)     NULL,
    [F_CHANGE]                 DECIMAL (18, 6) NULL,
    [C_TRADDESK]               VARCHAR (8)     NULL,
    [F_FILL]                   DECIMAL (18, 6) NULL,
    [F_YIELD]                  DECIMAL (18, 6) NULL,
    [C_ALLOCMETHOD]            VARCHAR (20)    NULL,
    [C_SETTLELOCN]             VARCHAR (3)     NULL,
    [C_TRANSCODE]              VARCHAR (2)     NULL,
    [C_CLEARBROKER]            VARCHAR (10)    NULL,
    [C_SHORT1]                 VARCHAR (12)    NULL,
    [C_SHORT2]                 VARCHAR (12)    NULL,
    [C_SHORT3]                 VARCHAR (12)    NULL,
    [C_SHORT4]                 VARCHAR (12)    NULL,
    [C_LONG1]                  VARCHAR (45)    NULL,
    [C_LONG2]                  VARCHAR (45)    NULL,
    [C_LONG3]                  VARCHAR (45)    NULL,
    [C_LONG4]                  VARCHAR (45)    NULL,
    [C_NOTES]                  VARCHAR (45)    NULL,
    [I_AGGRTO]                 INT             NULL,
    [I_AGGRFROM]               INT             NULL,
    [I_DEAGGRTO]               INT             NULL,
    [I_DEAGGRFROM]             INT             NULL,
    [C_IMPUTE]                 VARCHAR (3)     NULL,
    [C_CURRCODE]               VARCHAR (2)     NULL,
    [F_CURRRATE]               DECIMAL (18, 6) NULL,
    [F_VWAP]                   DECIMAL (18, 6) NULL,
    [C_SCOM]                   VARCHAR (50)    NULL,
    [C_BCOM]                   VARCHAR (50)    NULL,
    [C_EFEE]                   VARCHAR (50)    NULL,
    [C_WTAX]                   VARCHAR (50)    NULL,
    [C_TTAX]                   VARCHAR (50)    NULL,
    [C_SDTY]                   VARCHAR (50)    NULL,
    [C_TLVY]                   VARCHAR (50)    NULL,
    [C_CFEE]                   VARCHAR (50)    NULL,
    [C_NFEE]                   VARCHAR (50)    NULL,
    [C_SFEE]                   VARCHAR (50)    NULL,
    [C_OFEE]                   VARCHAR (50)    NULL,
    [C_BFEE]                   VARCHAR (50)    NULL,
    [C_AFEE]                   VARCHAR (50)    NULL,
    [C_VTAX]                   VARCHAR (50)    NULL,
    [C_STAX]                   VARCHAR (50)    NULL,
    [C_MFEE]                   VARCHAR (50)    NULL,
    [C_PFEE]                   VARCHAR (50)    NULL,
    [C_GSTAX]                  VARCHAR (50)    NULL,
    [C_CTAX]                   VARCHAR (50)    NULL,
    [C_UPFEE]                  VARCHAR (50)    NULL,
    [C_ASFEE]                  VARCHAR (50)    NULL,
    [C_BONIF]                  VARCHAR (50)    NULL,
    [C_TAX]                    VARCHAR (50)    NULL,
    [C_TRCCM]                  VARCHAR (50)    NULL,
    [C_RETCM]                  VARCHAR (50)    NULL,
    [C_REASONCODE]             VARCHAR (2)     NULL,
    [C_BESTEXEC1]              VARCHAR (80)    NULL,
    [C_BESTEXEC2]              VARCHAR (80)    NULL,
    [C_BESTEXEC3]              VARCHAR (80)    NULL,
    [C_BESTEXEC4]              VARCHAR (80)    NULL,
    [C_BESTEXEC5]              VARCHAR (80)    NULL,
    [C_BESTEXEC6]              VARCHAR (80)    NULL,
    [C_OPTIONDELTA]            VARCHAR (12)    NULL,
    [F_WORKPRC]                DECIMAL (18, 6) NULL,
    [C_OVERRIDE1]              VARCHAR (60)    NULL,
    [C_OVERRIDE2]              VARCHAR (60)    NULL,
    [F_ROUTAMT]                DECIMAL (18, 6) NULL,
    [F_ROUTACKAMT]             DECIMAL (18, 6) NULL,
    [F_EXECFILLAMT]            DECIMAL (18, 6) NULL,
    [F_EXECLFILLAMT]           DECIMAL (18, 6) NULL,
    [F_EXECLFILLPRC]           DECIMAL (18, 6) NULL,
    [F_CANCELAMT]              DECIMAL (18, 6) NULL,
    [C_ROUTORDTYP]             VARCHAR (4)     NULL,
    [F_ROUTLMTPRC]             DECIMAL (18, 6) NULL,
    [C_ROUTTIF]                VARCHAR (4)     NULL,
    [C_EXECASOFDATE]           VARCHAR (10)    NULL,
    [C_EXECASOFTIME]           VARCHAR (8)     NULL,
    [C_EXECBROKER]             VARCHAR (10)    NULL,
    [C_CRITERIA]               VARCHAR (80)    NULL,
    [I_IDENTTYPE]              INT             NULL,
    [C_LINKTO]                 VARCHAR (10)    NULL,
    [C_LINKFROM]               VARCHAR (10)    NULL,
    [I_SLICEPERCENT]           INT             NULL,
    [C_SLICESTTIME]            VARCHAR (5)     NULL,
    [I_SLICERPTFREQ]           INT             NULL,
    [I_SLICECUMULATIVE]        INT             NULL,
    [C_BENCHMARK1]             VARCHAR (80)    NULL,
    [C_BENCHMARK2]             VARCHAR (80)    NULL,
    [C_BENCHMARK3]             VARCHAR (80)    NULL,
    [C_BENCHMARK4]             VARCHAR (80)    NULL,
    [C_BENCHMARK5]             VARCHAR (80)    NULL,
    [C_BENCHMARK6]             VARCHAR (80)    NULL,
    [C_BESTEXECMEMO]           VARCHAR (80)    NULL,
    [C_BESTEXECMEMO2]          VARCHAR (80)    NULL,
    [C_BENCHMARK_CUSIP]        VARCHAR (11)    NULL,
    [F_BENCHMARK_YIELD]        DECIMAL (18, 6) NULL,
    [F_BENCHMARK_SPREAD]       DECIMAL (18, 6) NULL,
    [C_TRANS_SEQ]              VARCHAR (80)    NULL,
    [C_STRATEGY_CODE]          VARCHAR (2)     NULL,
    [C_UPDATE_CASH]            VARCHAR (2)     NULL,
    [C_ORDERNAME]              VARCHAR (36)    NULL,
    [C_CONTINGENTFLAG]         VARCHAR (1)     NULL,
    [D_JPTRADEDATE]            DATETIME        NULL,
    [F_JPTRADEAMT]             DECIMAL (18, 6) NULL,
    [F_JPCOMMAMT]              DECIMAL (18, 6) NULL,
    [F_JPTAXAMT]               DECIMAL (18, 6) NULL,
    [F_JPOTHERMKTFEES]         DECIMAL (18, 6) NULL,
    [F_JPNETMONEY]             DECIMAL (18, 6) NULL,
    [F_BENCHMARKPRICE]         DECIMAL (18, 6) NULL,
    [C_YIELDCONVENTION]        VARCHAR (1)     NULL,
    [C_CBCOM]                  VARCHAR (50)    NULL,
    [C_PX_RE]                  VARCHAR (50)    NULL,
    [C_CRTGE]                  VARCHAR (50)    NULL,
    [C_PCOM]                   VARCHAR (50)    NULL,
    [C_COTAX]                  VARCHAR (50)    NULL,
    [C_FRAN]                   VARCHAR (50)    NULL,
    [C_TAFFEE]                 VARCHAR (50)    NULL,
    [C_ACCPT]                  VARCHAR (50)    NULL,
    [C_SECONDARYBROKER]        VARCHAR (10)    NULL,
    [F_ACCRUED]                DECIMAL (18, 6) NULL,
    [F_PRINCIPAL]              DECIMAL (18, 6) NULL,
    [C_AUDITIDTKT]             VARCHAR (10)    NULL,
    [I_ALLOC_FROM]             INT             NULL,
    [I_TRDAGGRTO]              INT             NULL,
    [I_TRDDEAGGRFROM]          INT             NULL,
    [C_EXCHDEST]               VARCHAR (4)     NULL,
    [C_LASTMARKET]             VARCHAR (4)     NULL,
    [I_CXLNUM]                 INT             NULL,
    [I_LISTNUM]                INT             NULL,
    [C_STRATNAME]              VARCHAR (12)    NULL,
    [C_STYLE]                  VARCHAR (12)    NULL,
    [I_STARTTIME]              VARCHAR (20)    NULL,
    [I_ENDTIME]                VARCHAR (20)    NULL,
    [F_MINPERCENTVOL]          DECIMAL (18, 6) NULL,
    [F_MAXPERCENTVOL]          DECIMAL (18, 6) NULL,
    [C_TRADEDCUR]              VARCHAR (4)     NULL,
    [C_BASECURRENCY]           VARCHAR (4)     NULL,
    [I_TERMINALID]             INT             NULL,
    [C_TICKER]                 VARCHAR (10)    NULL,
    [C_SECDESC]                VARCHAR (32)    NULL,
    [C_EXCHCODE]               VARCHAR (32)    NULL,
    [C_BBID]                   VARCHAR (32)    NULL,
    [C_PRIME_BROKER]           VARCHAR (6)     NULL,
    [C_TSAM_FACILITY_ID]       VARCHAR (25)    NULL,
    [C_TSAM_ALLOCATION_ID]     VARCHAR (22)    NULL,
    [C_TSAM_ALLOCATION_STATUS] VARCHAR (20)    NULL,
    [C_TSAM_BROKER_NOTES]      VARCHAR (60)    NULL,
    [C_EXTERNAL_ORDER_ID]      VARCHAR (40)    NULL,
    [C_EXTERNAL_ALLOC_ID]      VARCHAR (40)    NULL,
    [C_FIRMIDENT]              VARCHAR (32)    NULL,
    [C_ROUTE_INSTRUCTION]      VARCHAR (44)    NULL,
    [C_SSI_NEW_VALUE]          VARCHAR (50)    NULL,
    [C_PARTICIPANT]            VARCHAR (25)    NULL,
    [C_TI_HEADLINE]            VARCHAR (36)    NULL,
    [C_TI_DESCRIPTION]         VARCHAR (80)    NULL,
    [C_TI_LOG_ENTRY]           VARCHAR (80)    NULL,
    [C_TI_LEAD_MGRS]           VARCHAR (80)    NULL,
    [F_TI_DEAL_SIZE]           DECIMAL (18, 6) NULL,
    [F_TI_AMOUNT_REQ]          DECIMAL (18, 6) NULL,
    [C_TI_PRICE_TYPE]          VARCHAR (30)    NULL,
    [C_TI_PRICE_DETAIL]        VARCHAR (30)    NULL,
    [C_TRANSTYPE]              VARCHAR (3)     NULL,
    [C_DELIVTYPE]              VARCHAR (2)     NULL,
    [F_REPORATE]               DECIMAL (18, 6) NULL,
    [F_MARGIN]                 DECIMAL (18, 6) NULL,
    [F_HAIRCUT]                DECIMAL (18, 6) NULL,
    [F_UNDEREQUIV]             DECIMAL (18, 6) NULL,
    [F_FULLQUANTITY]           DECIMAL (18, 6) NULL,
    [C_AIMSTRATEGY]            VARCHAR (56)    NULL,
    [C_SHORT5]                 VARCHAR (12)    NULL,
    [C_SHORT6]                 VARCHAR (12)    NULL,
    [C_SHORT7]                 VARCHAR (12)    NULL,
    [C_SHORT8]                 VARCHAR (12)    NULL,
    [C_LONG5]                  VARCHAR (45)    NULL,
    [C_LONG6]                  VARCHAR (45)    NULL,
    [C_LONG7]                  VARCHAR (45)    NULL,
    [C_LONG8]                  VARCHAR (45)    NULL,
    [C_TAGS]                   VARCHAR (80)    NULL,
    [F_FX_BOOK]                DECIMAL (18, 6) NULL,
    [F_EX_RATE]                DECIMAL (18, 6) NULL,
    [C_DISTDESK]               VARCHAR (8)     NULL,
    [C_DELIVERY_METHOD]        VARCHAR (80)    NULL,
    [C_ORDEREXCH]              VARCHAR (10)    NULL,
    [C_SCOM_CURR]              VARCHAR (3)     NULL,
    [C_BCOM_CURR]              VARCHAR (3)     NULL,
    [C_EFEE_CURR]              VARCHAR (3)     NULL,
    [C_WTAX_CURR]              VARCHAR (3)     NULL,
    [C_TTAX_CURR]              VARCHAR (3)     NULL,
    [C_SDTY_CURR]              VARCHAR (3)     NULL,
    [C_TLVY_CURR]              VARCHAR (3)     NULL,
    [C_CFEE_CURR]              VARCHAR (3)     NULL,
    [C_NFEE_CURR]              VARCHAR (3)     NULL,
    [C_SFEE_CURR]              VARCHAR (3)     NULL,
    [C_OFEE_CURR]              VARCHAR (3)     NULL,
    [C_BFEE_CURR]              VARCHAR (3)     NULL,
    [C_AFEE_CURR]              VARCHAR (3)     NULL,
    [C_VTAX_CURR]              VARCHAR (3)     NULL,
    [C_STAX_CURR]              VARCHAR (3)     NULL,
    [C_MFEE_CURR]              VARCHAR (3)     NULL,
    [C_PFEE_CURR]              VARCHAR (3)     NULL,
    [C_GSTAX_CURR]             VARCHAR (3)     NULL,
    [C_CTAX_CURR]              VARCHAR (3)     NULL,
    [C_UPFEE_CURR]             VARCHAR (3)     NULL,
    [C_ASFEE_CURR]             VARCHAR (3)     NULL,
    [C_BONIF_CURR]             VARCHAR (3)     NULL,
    [C_TAX_CURR]               VARCHAR (3)     NULL,
    [C_TRCCM_CURR]             VARCHAR (3)     NULL,
    [C_RETCM_CURR]             VARCHAR (3)     NULL,
    [C_EXECPLATFORM]           VARCHAR (20)    NULL,
    [F_CDSPRICE]               DECIMAL (18, 6) NULL,
    [F_CDSSPREAD]              DECIMAL (18, 6) NULL,
    [C_QUOTETYPE]              VARCHAR (10)    NULL,
    [C_DISCOUNT]               VARCHAR (20)    NULL,
    [D_TERMDATE]               DATETIME        NULL,
    [F_CONTRACT_SIZE]          DECIMAL (18, 6) NULL,
    [C_SCOM_RATE]              DECIMAL (18, 6) NULL,
    [C_BCOM_RATE]              DECIMAL (18, 6) NULL,
    [C_EFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_WTAX_RATE]              DECIMAL (18, 6) NULL,
    [C_TTAX_RATE]              DECIMAL (18, 6) NULL,
    [C_SDTY_RATE]              DECIMAL (18, 6) NULL,
    [C_TLVY_RATE]              DECIMAL (18, 6) NULL,
    [C_CFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_NFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_SFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_OFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_BFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_AFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_VTAX_RATE]              DECIMAL (18, 6) NULL,
    [C_STAX_RATE]              DECIMAL (18, 6) NULL,
    [C_MFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_PFEE_RATE]              DECIMAL (18, 6) NULL,
    [C_GSTAX_RATE]             DECIMAL (18, 6) NULL,
    [C_CTAX_RATE]              DECIMAL (18, 6) NULL,
    [C_UPFEE_RATE]             DECIMAL (18, 6) NULL,
    [C_ASFEE_RATE]             DECIMAL (18, 6) NULL,
    [C_BONIF_RATE]             DECIMAL (18, 6) NULL,
    [C_TAX_RATE]               DECIMAL (18, 6) NULL,
    [C_TRCCM_RATE]             DECIMAL (18, 6) NULL,
    [C_RETCM_RATE]             DECIMAL (18, 6) NULL,
    [C_SCOM_VALUE]             DECIMAL (18, 6) NULL,
    [C_BCOM_VALUE]             DECIMAL (18, 6) NULL,
    [C_EFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_WTAX_VALUE]             DECIMAL (18, 6) NULL,
    [C_TTAX_VALUE]             DECIMAL (18, 6) NULL,
    [C_SDTY_VALUE]             DECIMAL (18, 6) NULL,
    [C_TLVY_VALUE]             DECIMAL (18, 6) NULL,
    [C_CFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_NFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_SFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_OFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_BFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_AFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_VTAX_VALUE]             DECIMAL (18, 6) NULL,
    [C_STAX_VALUE]             DECIMAL (18, 6) NULL,
    [C_MFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_PFEE_VALUE]             DECIMAL (18, 6) NULL,
    [C_GSTAX_VALUE]            DECIMAL (18, 6) NULL,
    [C_CTAX_VALUE]             DECIMAL (18, 6) NULL,
    [C_UPFEE_VALUE]            DECIMAL (18, 6) NULL,
    [C_ASFEE_VALUE]            DECIMAL (18, 6) NULL,
    [C_BONIF_VALUE]            DECIMAL (18, 6) NULL,
    [C_TAX_VALUE]              DECIMAL (18, 6) NULL,
    [C_TRCCM_VALUE]            DECIMAL (18, 6) NULL,
    [C_RETCM_VALUE]            DECIMAL (18, 6) NULL,
    [CADIS_SYSTEM_INSERTED]    DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]     DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]   NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([I_AUDITID] ASC, [D_DATE] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [idx_audit_date_tsordernum]
    ON [dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT]([D_DATE] ASC)
    INCLUDE([I_TSORDNUM]);


GO
CREATE NONCLUSTERED INDEX [idx_audit_c_event]
    ON [dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT]([C_EVENT] ASC)
    INCLUDE([D_DATE], [T_TIME], [I_TSORDNUM], [I_MTKTNUM], [C_USER], [F_QUANTITY], [I_AGGRTO], [I_AGGRFROM], [F_ROUTAMT]);


GO
CREATE NONCLUSTERED INDEX [idx_audit_tsordnum]
    ON [dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT]([I_TSORDNUM] ASC, [C_EVENT] ASC)
    INCLUDE([I_TKTNUM], [F_QUANTITY]);


GO
CREATE NONCLUSTERED INDEX [CoverIndex_1]
    ON [dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT]([C_EVENT] ASC, [C_SIDE] ASC, [C_ACCOUNT] ASC)
    INCLUDE([C_SECURITY], [C_IDENTIFIER], [F_QUANTITY], [F_PRICE], [C_CURRENCY], [D_ASOFDATE], [C_IPO], [F_PRINCIPAL]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [idx_act_alloc_c_event]
    ON [dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT]([I_TSORDNUM] ASC, [C_ACCOUNT] ASC)
    INCLUDE([I_AUDITID], [D_DATE], [C_EVENT], [F_QUANTITY], [C_BROKER]) WHERE ([C_EVENT] IN ('ACTIVATED ORDER', 'ORDER ALLOCATED')) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [idx_audit_reasoncode]
    ON [dbo].[T_BBG_TCA_TRADE_ORDERS_AUDIT]([C_REASONCODE] ASC, [I_AUDITID] ASC, [D_DATE] ASC) WHERE ([C_REASONCODE] IS NOT NULL) WITH (FILLFACTOR = 80);

