CREATE TABLE [dbo].[T_BBG_COMPLIANCE_RULE_REVISION_BROKER] (
    [CADIS_PARENT_ID]           VARCHAR (50)  NULL,
    [EVALUATION_EVALTYPEAFTER]  VARCHAR (50)  NULL,
    [EVALUATION_EVALTYPEBEFORE] VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTNAMEAFTER]    VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTNAMEBEFORE]   VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTTYPEAFTER]    VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTTYPEBEFORE]   VARCHAR (50)  NULL,
    [SCOPE_BROKERNAMEAFTER]     VARCHAR (50)  NULL,
    [SCOPE_BROKERNAMEBEFORE]    VARCHAR (50)  NULL,
    [SCOPE_BROKERTYPEAFTER]     VARCHAR (50)  NULL,
    [SCOPE_BROKERTYPEBEFORE]    VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__4D7A1B6B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__4E6E3FA4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_BBG_COM__CADIS__4F6263DD] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_BBG_COM__CADIS__50568816] DEFAULT ((1)) NULL
);

