CREATE TABLE [dbo].[T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_FXFields_IN] (
    [CADIS_BATCH_ID]                     INT            NOT NULL,
    [CADIS_MSG_ID]                       INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__4D8CC7FF] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                    INT            NOT NULL,
    [CADIS_ROW_ID]                       INT            NOT NULL,
    [esxsd:SwapLeg]                      NVARCHAR (MAX) NULL,
    [esxsd:InvertedFlag]                 NVARCHAR (MAX) NULL,
    [esxsd:UseStandardInstructionsFlag]  NVARCHAR (MAX) NULL,
    [esxsd:DealType]                     NVARCHAR (MAX) NULL,
    [esxsd:MarketSpotDate]               NVARCHAR (MAX) NULL,
    [esxsd:MarketSpotSource]             NVARCHAR (MAX) NULL,
    [esxsd:MarketRateSource]             NVARCHAR (MAX) NULL,
    [esxsd:ISOCodeOf1stCurrency]         NVARCHAR (MAX) NULL,
    [esxsd:ISOCodeOf2ndCurrency]         NVARCHAR (MAX) NULL,
    [esxsd:SwapTicketNumber]             NVARCHAR (MAX) NULL,
    [esxsd:OutrightSpotRate]             NVARCHAR (MAX) NULL,
    [esxsd:Points]                       NVARCHAR (MAX) NULL,
    [esxsd:MarketRate]                   NVARCHAR (MAX) NULL,
    [esxsd:EnteredByCurrency]            NVARCHAR (MAX) NULL,
    [esxsd:ExerciseType]                 NVARCHAR (MAX) NULL,
    [esxsd:AdjustedRateFlag]             NVARCHAR (MAX) NULL,
    [esxsd:AdjustedRate]                 NVARCHAR (MAX) NULL,
    [esxsd:SecondCashSettlementDate]     NVARCHAR (MAX) NULL,
    [esxsd:OptionStyle]                  NVARCHAR (MAX) NULL,
    [esxsd:InvertRate]                   NVARCHAR (MAX) NULL,
    [esxsd:InvertSpot]                   NVARCHAR (MAX) NULL,
    [esxsd:InvertPoints]                 NVARCHAR (MAX) NULL,
    [esxsd:InitialDealAmount]            NVARCHAR (MAX) NULL,
    [esxsd:TakeUpCurrency]               NVARCHAR (MAX) NULL,
    [esxsd:FirstCashSettlementDate]      NVARCHAR (MAX) NULL,
    [esxsd:StrategyTicketNumber]         NVARCHAR (MAX) NULL,
    [esxsd:StrategyLegNumber]            NVARCHAR (MAX) NULL,
    [esxsd:StrategyName]                 NVARCHAR (MAX) NULL,
    [esxsd:NumberOfLegs]                 NVARCHAR (MAX) NULL,
    [esxsd:StrategyModel]                NVARCHAR (MAX) NULL,
    [esxsd:StrategyIdentifier]           NVARCHAR (MAX) NULL,
    [esxsd:UpdateCashAtSettlement]       NVARCHAR (MAX) NULL,
    [esxsd:DealType2]                    NVARCHAR (MAX) NULL,
    [esxsd:OrigTkt]                      NVARCHAR (MAX) NULL,
    [esxsd:OrigOrder]                    NVARCHAR (MAX) NULL,
    [esxsd:CCPVenue]                     NVARCHAR (MAX) NULL,
    [esxsd:UniqueSwapIdentifierforTrade] NVARCHAR (MAX) NULL,
    [esxsd:SEFFlag]                      NVARCHAR (MAX) NULL,
    [esxsd:IsSecurityMAT]                NVARCHAR (MAX) NULL,
    [esxsd:SecBlockLimit]                NVARCHAR (MAX) NULL,
    [esxsd:AccountLEI]                   NVARCHAR (MAX) NULL,
    [esxsd:FCMLEI]                       NVARCHAR (MAX) NULL,
    [esxsd:ExecutionCounterParty]        NVARCHAR (MAX) NULL,
    [esxsd:EmirTradeID]                  NVARCHAR (MAX) NULL,
    [CADIS_SYSTEM_INSERTED]              DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__4E80EC38] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]               DATETIME       CONSTRAINT [DF__T_BBAIM_X__CADIS__4F751071] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]             NVARCHAR (50)  CONSTRAINT [DF__T_BBAIM_X__CADIS__506934AA] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]              INT            CONSTRAINT [DF__T_BBAIM_X__CADIS__515D58E3] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_BBAIM_XML_esxsd_BatchFeed_esxsd_TradeFeed_esxsd_FXFields_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

