CREATE TABLE [dbo].[T_BBG_CASH_LADDER_UNTYPED] (
    [FILE_NAME]              VARCHAR (100) NULL,
    [FILE_DATE]              VARCHAR (20)  NULL,
    [FUND_SHORT_NAME]        VARCHAR (20)  NOT NULL,
    [CCY]                    VARCHAR (10)  NOT NULL,
    [AS_OF_DATE]             VARCHAR (50)  NOT NULL,
    [VALUE]                  VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [CCY] ASC, [AS_OF_DATE] ASC) WITH (FILLFACTOR = 80)
);

