CREATE TABLE [dbo].[T_BBG_COMPLIANCE_RULE_REVISION_ATTRIBUTE_BEFORE] (
    [CADIS_PARENT_ID]        VARCHAR (50)  NULL,
    [VALUE_VALUE_INNERTEXT]  VARCHAR (50)  NULL,
    [VALUE_VALUE_INNERTEXT2] VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__5BC83AC2] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_BBG_COM__CADIS__5CBC5EFB] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_BBG_COM__CADIS__5DB08334] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_BBG_COM__CADIS__5EA4A76D] DEFAULT ((1)) NULL
);

