CREATE TABLE [dbo].[T_BPS_REQUEST_UNIQUE_OUT] (
    [REQUEST_ID]             VARCHAR (50)  NOT NULL,
    [REQUEST_ID_TYPE]        VARCHAR (50)  NULL,
    [PRICING_SOURCE]         VARCHAR (30)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_BPS_REQ__CADIS__1D386D71] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_BPS_REQ__CADIS__1E2C91AA] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_BPS_REQ__CADIS__1F20B5E3] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_BPS_REQ__CADIS__2014DA1C] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_BPS_RE__71D2766C280E5700] PRIMARY KEY CLUSTERED ([REQUEST_ID] ASC) WITH (FILLFACTOR = 90)
);

