CREATE TABLE [dbo].[T_BPS_REQUEST_CONTROL] (
    [FIELD_GROUP]            VARCHAR (20)  NULL,
    [PROCESSED]              BIT           NULL,
    [LAST_PROCESSED_DATE]    DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_BPS_REQ__CADIS__2F620AA4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_BPS_REQ__CADIS__30562EDD] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_BPS_REQ__CADIS__314A5316] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_BPS_REQ__CADIS__323E774F] DEFAULT ((1)) NULL
);

