CREATE TABLE [dbo].[T_BPS_SECURITY] (
    [FILE_NAME]              VARCHAR (50)  NULL,
    [DATE]                   DATETIME      NULL,
    [IDENTIFIER]             VARCHAR (50)  NULL,
    [FIELD]                  VARCHAR (50)  NULL,
    [VALUE]                  VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_BPS_SEC__CADIS__264F3864] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_BPS_SEC__CADIS__27435C9D] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_BPS_SEC__CADIS__283780D6] DEFAULT ('UNKNOWN') NULL
);

