CREATE TABLE [dbo].[T_BPS_PRICE_EXCL_MANUAL] (
    [ID_BB_UNIQUE]           VARCHAR (30)  NOT NULL,
    [NOTES]                  VARCHAR (100) NULL,
    [EDM_SEC_ID]             VARCHAR (30)  NULL,
    [ID_BB_GLOBAL]           VARCHAR (30)  NULL,
    [SEDOL]                  VARCHAR (7)   NULL,
    [ISIN]                   VARCHAR (12)  NULL,
    [CUSIP]                  VARCHAR (9)   NULL,
    [TICKER]                 VARCHAR (26)  NULL,
    [BPS_YELLOWKEY]          VARCHAR (30)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_BPS_PRI__CADIS__294BA0A0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_BPS_PRI__CADIS__2A3FC4D9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_BPS_PRI__CADIS__2B33E912] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_BPS_PRI__CADIS__2C280D4B] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_BPS_PR__9FF60D80EEF167C1] PRIMARY KEY CLUSTERED ([ID_BB_UNIQUE] ASC) WITH (FILLFACTOR = 90)
);

