CREATE TABLE [dbo].[T_BPS_PH_EXCL_MANUAL] (
    [ID_BB_UNIQUE]           VARCHAR (30)  NOT NULL,
    [NOTES]                  VARCHAR (100) NULL,
    [EDM_SEC_ID]             VARCHAR (30)  NULL,
    [ID_BB_GLOBAL]           VARCHAR (30)  NULL,
    [SEDOL]                  VARCHAR (7)   NULL,
    [ISIN]                   VARCHAR (12)  NULL,
    [CUSIP]                  VARCHAR (9)   NULL,
    [TICKER]                 VARCHAR (26)  NULL,
    [BPS_YELLOWKEY]          VARCHAR (30)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_BPS_PH___CADIS__7CAE0453] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_BPS_PH___CADIS__7DA2288C] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_BPS_PH___CADIS__7E964CC5] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_BPS_PH___CADIS__7F8A70FE] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_BPS_PH__9FF60D80F4212EF1] PRIMARY KEY CLUSTERED ([ID_BB_UNIQUE] ASC) WITH (FILLFACTOR = 90)
);

