CREATE TABLE [dbo].[T_BPS_PRICE_HISTORY] (
    [FILE_NAME]              VARCHAR (50)    NULL,
    [RUN_DATE]               DATETIME        NULL,
    [ID_BB_UNIQUE]           VARCHAR (50)    NOT NULL,
    [PX_DATE]                DATETIME        NOT NULL,
    [PX_LAST]                DECIMAL (20, 6) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        CONSTRAINT [DF__T_BPS_PRI__CADIS__799C8D7E] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        CONSTRAINT [DF__T_BPS_PRI__CADIS__7A90B1B7] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   CONSTRAINT [DF__T_BPS_PRI__CADIS__7B84D5F0] DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PK__T_BPS_PR__B862D7FE1DC9F29D] PRIMARY KEY CLUSTERED ([ID_BB_UNIQUE] ASC, [PX_DATE] ASC) WITH (FILLFACTOR = 90)
);

