CREATE TABLE [dbo].[T_CONTROL_SALES_FORCE_ACCOUNT_OWNER] (
    [MATRIXOUTLETID]         VARCHAR (50)   NOT NULL,
    [ACCOUNT_NAME]           VARCHAR (2000) NULL,
    [OLD_ACCOUNT_OWNER_ID]   VARCHAR (18)   NULL,
    [OLD_ACCOUNT_OWNER]      VARCHAR (200)  NULL,
    [NEW_ACCOUNT_OWNER_ID]   VARCHAR (18)   NULL,
    [NEW_ACCOUNT_OWNER]      VARCHAR (200)  NULL,
    [PROCESS_STATUS]         VARCHAR (20)   NULL,
    [RECIPIENT]              VARCHAR (512)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)  DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([MATRIXOUTLETID] ASC) WITH (FILLFACTOR = 80)
);

