CREATE TABLE [dbo].[T_CO_BAK_PROCESSLOG_ARCHIVE] (
    [LOGID]       INT             NOT NULL,
    [RUNID]       INT             NOT NULL,
    [LOGTIME]     DATETIME        NOT NULL,
    [LOGMESSAGE]  NVARCHAR (1024) NOT NULL,
    [MESSAGETYPE] TINYINT         DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([LOGID] ASC),
    CONSTRAINT [FK_PROCESSLOG_PROCESSHISTORY_ARCHIVE] FOREIGN KEY ([RUNID]) REFERENCES [dbo].[T_CO_BAK_PROCESSHISTORY_ARCHIVE] ([RUNID])
);

