CREATE TABLE [dbo].[T_CO_BAK_PROCESSLOG_ARCHIVE_0217] (
    [LOGID]       INT             NOT NULL,
    [RUNID]       INT             NOT NULL,
    [LOGTIME]     DATETIME        NOT NULL,
    [LOGMESSAGE]  NVARCHAR (1024) NOT NULL,
    [MESSAGETYPE] TINYINT         DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([LOGID] ASC)
);

