CREATE TABLE [dbo].[T_DELL_BOOMI_CUSTOM_DP] (
    [T_DELL_BOOMI_CUSTOM_DP_ID] INT           IDENTITY (1, 1) NOT NULL,
    [JOB_MANE]                  VARCHAR (150) NULL,
    [ENVIRONMENT]               VARCHAR (5)   NULL,
    [JOB_PROCESS_STRING]        VARCHAR (MAX) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([T_DELL_BOOMI_CUSTOM_DP_ID] ASC) WITH (FILLFACTOR = 90)
);

