CREATE TABLE [dbo].[T_DUMMY_MG_FND_MARKET_VALUE] (
    [SOURCE]                          VARCHAR (50)    NOT NULL,
    [POSITION_TYPE]                   VARCHAR (50)    NOT NULL,
    [FUND_SHORT_NAME]                 VARCHAR (8000)  NOT NULL,
    [POSITION_DATE]                   DATETIME        NOT NULL,
    [TOTAL_MARKET_VALUE_LOCAL]        DECIMAL (20, 2) NULL,
    [TOTAL_MARKET_VALUE_BASE]         DECIMAL (20, 2) NULL,
    [STATUS]                          VARCHAR (20)    NULL,
    [TOTAL_ACCRUED_MARKET_VALUE_BASE] DECIMAL (20, 2) NULL,
    [CADIS_SYSTEM_INSERTED]           DATETIME        CONSTRAINT [DF__T_DUMMY_M__CADIS__61100B7F] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]            DATETIME        CONSTRAINT [DF__T_DUMMY_M__CADIS__62042FB8] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]          NVARCHAR (50)   CONSTRAINT [DF__T_DUMMY_M__CADIS__62F853F1] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]           INT             CONSTRAINT [DF__T_DUMMY_M__CADIS__63EC782A] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED]       DATETIME        CONSTRAINT [DF__T_DUMMY_M__CADIS__64E09C63] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_DUMMY___D5F86804F7567C21] PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC) WITH (FILLFACTOR = 90)
);

