CREATE TABLE [dbo].[T_DUMMY_MG_SEC_FIXED] (
    [EDM_SEC_ID]                             INT              NOT NULL,
    [ISSUE_DATE]                             DATETIME         NULL,
    [MATURITY_DATE]                          DATETIME         NULL,
    [COUPON_RATE]                            DECIMAL (26, 6)  NULL,
    [COUPON_FREQUENCY]                       INT              NULL,
    [COUPON_TYPE]                            VARCHAR (30)     NULL,
    [CONVERTIBLE_INDICATOR]                  VARCHAR (1)      NULL,
    [AMOUNT_ISSUED]                          DECIMAL (26, 2)  NULL,
    [AMOUNT_OUTSTANDING]                     DECIMAL (26, 2)  NULL,
    [COUPON_CAP]                             DECIMAL (26, 6)  NULL,
    [COUPON_ISO_CCY]                         VARCHAR (3)      NULL,
    [COUPON_FLOOR]                           DECIMAL (26, 6)  NULL,
    [ISSUE_PRICE]                            DECIMAL (26, 6)  NULL,
    [DAY_COUNT]                              INT              NULL,
    [FIRST_COUPON_DATE]                      DATETIME         NULL,
    [FIRST_SETTLE_DATE]                      DATETIME         NULL,
    [PREVIOUS_COUPON_DATE]                   DATETIME         NULL,
    [NEXT_COUPON_DATE]                       DATETIME         NULL,
    [NEXT_CALL_DATE]                         DATETIME         NULL,
    [NEXT_CALL_PRICE]                        DECIMAL (26, 6)  NULL,
    [LAST_RESET_DATE]                        DATETIME         NULL,
    [NEXT_RESET_DATE]                        DATETIME         NULL,
    [SECOND_COUPON_DATE]                     DATETIME         NULL,
    [FIXED_INDICATOR]                        VARCHAR (1)      NULL,
    [FIX_TO_FLOAT_INDICATOR]                 VARCHAR (1)      NULL,
    [FLOATER_INDICATOR]                      VARCHAR (1)      NULL,
    [FLOAT_TO_FIX_INDICATOR]                 VARCHAR (1)      NULL,
    [INDEX_LINKED_INDICATOR]                 VARCHAR (1)      NULL,
    [INFLATION_LINKED_INDICATOR]             VARCHAR (1)      NULL,
    [PERPETUAL_INDICATOR]                    VARCHAR (1)      NULL,
    [ZERO_COUPON_INDICATOR]                  VARCHAR (1)      NULL,
    [ACCRUED_INTEREST_PER_100]               DECIMAL (26, 6)  NULL,
    [ACCRUED_INTEREST_DATE]                  DATETIME         NULL,
    [COLLATERAL_TYPE]                        VARCHAR (30)     NULL,
    [AGGREGATE_AMOUNT_ISSUED_INDICATOR]      VARCHAR (1)      NULL,
    [ASSUMED_INDEX_VALUE]                    DECIMAL (26, 6)  NULL,
    [BRADY_INDICATOR]                        VARCHAR (1)      NULL,
    [CALCULATION_TYPE]                       INT              NULL,
    [CALLABLE_INDICATOR]                     VARCHAR (1)      NULL,
    [CALLED_INDICATOR]                       VARCHAR (1)      NULL,
    [CALL_DAYS_NOTICE]                       INT              NULL,
    [PUTABLE_INDICATOR]                      VARCHAR (1)      NULL,
    [PUT_DAYS_NOTICE]                        INT              NULL,
    [CASH_SETTLED_INDICATOR]                 VARCHAR (1)      NULL,
    [CDS_RECOVERY_RATE]                      DECIMAL (26, 6)  NULL,
    [CORPORATE_TO_EQUITY_TICKER]             VARCHAR (11)     NULL,
    [FIX_TO_FLOAT_COUPON_TYPE_RESET_DATE]    DATETIME         NULL,
    [DEFAULTED_INDICATOR]                    VARCHAR (1)      NULL,
    [EXCHANGEABLE_INDICATOR]                 VARCHAR (1)      NULL,
    [FLOATER_COUPON_CONVENTION]              VARCHAR (30)     NULL,
    [FLOATER_LOCKOUT_PERIOD]                 INT              NULL,
    [FLOATER_PAY_DAY]                        VARCHAR (30)     NULL,
    [JUNIOR_INDICATOR]                       VARCHAR (1)      NULL,
    [SENIOR_INDICATOR]                       VARCHAR (1)      NULL,
    [REGULATION_S_INDICATOR]                 VARCHAR (1)      NULL,
    [SUBORDINATED_INDICATOR]                 VARCHAR (1)      NULL,
    [UNIT_TRADED_INDICATOR]                  VARCHAR (1)      NULL,
    [LOAN_PARTICIPATION_NOTE_INDICATOR]      VARCHAR (1)      NULL,
    [ORIGINAL_ISSUE_DISCOUNT_INDICATOR]      VARCHAR (4)      NULL,
    [GILT_DIGITS]                            INT              NULL,
    [GILTS_EX_DIVIDEND_DATE]                 DATETIME         NULL,
    [INDEX_RATIO_CPI]                        DECIMAL (26, 6)  NULL,
    [MINIMUM_INCREMENT]                      DECIMAL (26, 6)  NULL,
    [MINIMUM_PIECE]                          DECIMAL (26, 6)  NULL,
    [MOST_RECENT_REPORTED_FACTOR]            DECIMAL (26, 10) NULL,
    [MOST_RECENT_ACCRUAL_RATE]               DECIMAL (26, 6)  NULL,
    [MOST_RECENT_ACCRUAL_RATE_START_DATE]    DATETIME         NULL,
    [MORTGAGE_DEAL_CALL_DATE]                DATETIME         NULL,
    [MORTGAGE_END_PRINCIPAL_WINDOW_MATURITY] DATETIME         NULL,
    [MORTGAGE_FACTOR_DATE]                   DATETIME         NULL,
    [MORTGAGE_CURRENT_PAYMENT_RATE]          DECIMAL (26, 6)  NULL,
    [MORTGAGE_FINAL_PAY_DATE]                DATETIME         NULL,
    [MORTGAGE_FIRST_PAY_DATE]                DATETIME         NULL,
    [MORTGAGE_LIFE_FLOOR]                    DECIMAL (26, 2)  NULL,
    [MORTGAGE_PAYMENT_DELAY]                 VARCHAR (8)      NULL,
    [MORTGAGE_RATE_CHANGE_FREQUENCY]         INT              NULL,
    [MORTGAGE_TRANCHE_TYPE]                  VARCHAR (8)      NULL,
    [MATURITY_REFUND_TYPE]                   VARCHAR (18)     NULL,
    [NOMINAL_PAYMENT_DAY]                    INT              NULL,
    [PENULTIMATE_COUPON_DATE]                DATETIME         NULL,
    [REDEMPTION_VALUE]                       DECIMAL (26, 6)  NULL,
    [UNDERLYING_REFERENCE_INDEX]             VARCHAR (30)     NULL,
    [RESET_FREQUENCY]                        INT              NULL,
    [RESET_INDEX]                            VARCHAR (15)     NULL,
    [SINK_TYPE]                              VARCHAR (10)     NULL,
    [SINKABLE_INDICATOR]                     VARCHAR (1)      NULL,
    [STEPUP_STEPDOWN_COUPON]                 DECIMAL (26, 6)  NULL,
    [STEPUP_STEPDOWN_COUPON_DATE]            DATETIME         NULL,
    [STRUCTURED_NOTE_INDICATOR]              VARCHAR (1)      NULL,
    [LOWER_TIER2_CAPITAL_INDICATOR]          VARCHAR (1)      NULL,
    [TIER1_CAPITAL_INDICATOR]                VARCHAR (1)      NULL,
    [TIER2_CAPITAL_NON_SPECIFIC_INDICATOR]   VARCHAR (1)      NULL,
    [UPPER_TIER2_CAPITAL_INDICATOR]          VARCHAR (1)      NULL,
    [EX_DIVIDEND_DAYS]                       INT              NULL,
    [EX_DIVIDEND_DAYS_CALENDAR_CODE]         VARCHAR (8)      NULL,
    [SUBORDINATE_TYPE]                       VARCHAR (6)      NULL,
    [SENIORITY_LEVEL_2]                      VARCHAR (5)      NULL,
    [CADIS_SYSTEM_INSERTED]                  DATETIME         CONSTRAINT [DF__T_DUMMY_M__CADIS__1B91B2CF] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                   DATETIME         CONSTRAINT [DF__T_DUMMY_M__CADIS__1C85D708] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                 NVARCHAR (50)    CONSTRAINT [DF__T_DUMMY_M__CADIS__1D79FB41] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                  INT              CONSTRAINT [DF__T_DUMMY_M__CADIS__1E6E1F7A] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                 ROWVERSION       NOT NULL,
    CONSTRAINT [PK__T_DUMMY___B157E8F207230FB4] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 90)
);

