CREATE TABLE [dbo].[T_EDM_NEW_COMPONENT] (
    [COMPTYPE]               VARCHAR (8000) NULL,
    [COMPNAME]               VARCHAR (8000) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)  DEFAULT ('UNKNOWN') NULL
);

