CREATE TABLE [dbo].[T_EXCEPTION_LOAD_STAGE] (
    [DATE]                      DATETIME       NOT NULL,
    [SOURCE_TABLE]              VARCHAR (50)   NOT NULL,
    [SOURCE_KEY]                VARCHAR (50)   NOT NULL,
    [SOURCE_COLUMN]             VARCHAR (50)   NULL,
    [EXCEPTION_CODE]            INT            NOT NULL,
    [PROCESS_STATUS]            VARCHAR (2)    DEFAULT ('N') NULL,
    [ENTITY]                    VARCHAR (40)   NULL,
    [SOURCE]                    VARCHAR (50)   NULL,
    [SOURCE_COMPONENT]          VARCHAR (500)  NULL,
    [EDM_ENTITY_ID]             INT            NULL,
    [SOURCE_VALUE]              VARCHAR (1000) NULL,
    [DATA_A_TYPE]               VARCHAR (100)  NOT NULL,
    [DATA_A_VALUE]              VARCHAR (1000) NULL,
    [DATA_B_TYPE]               VARCHAR (100)  NULL,
    [DATA_B_VALUE]              VARCHAR (1000) NULL,
    [DATA_C_TYPE]               VARCHAR (100)  NULL,
    [DATA_C_VALUE]              VARCHAR (1000) NULL,
    [ISIN]                      VARCHAR (20)   NULL,
    [SEDOL]                     VARCHAR (20)   NULL,
    [CUSIP]                     VARCHAR (20)   NULL,
    [BUSINESS_PROCESS_LEVEL]    INT            NULL,
    [CURRENCY]                  VARCHAR (3)    NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)  DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT            DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME       DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([DATE] ASC, [SOURCE_TABLE] ASC, [SOURCE_KEY] ASC, [EXCEPTION_CODE] ASC) WITH (FILLFACTOR = 80)
);

