CREATE TABLE [dbo].[T_EXCEPTION_SEC] (
    [ENTITY]                    VARCHAR (40)   NULL,
    [SOURCE]                    VARCHAR (50)   NULL,
    [SOURCE_TABLE]              VARCHAR (50)   NOT NULL,
    [SOURCE_COMPONENT]          VARCHAR (50)   NULL,
    [SOURCE_KEY]                VARCHAR (50)   NOT NULL,
    [SOURCE_COLUMN]             VARCHAR (50)   NOT NULL,
    [EXCEPTION_CODE]            INT            NOT NULL,
    [ACCOUNT_CODE]              VARCHAR (100)  NULL,
    [SECURITY_ID]               VARCHAR (50)   NULL,
    [CADIS_ID]                  INT            NULL,
    [POSITION_TYPE]             VARCHAR (50)   NULL,
    [SECURITY_NAME]             VARCHAR (150)  NULL,
    [ISSUER_NAME]               VARCHAR (150)  NULL,
    [ACCOUNT_NAME]              VARCHAR (150)  NULL,
    [EXCEPTION_DATE]            DATETIME       NOT NULL,
    [SOURCE_VALUE]              VARCHAR (1000) NULL,
    [DATA_A_TYPE]               VARCHAR (100)  NULL,
    [DATA_A_VALUE]              VARCHAR (1000) NULL,
    [DATA_B_TYPE]               VARCHAR (100)  NULL,
    [DATA_B_VALUE]              VARCHAR (1000) NULL,
    [DATA_C_TYPE]               VARCHAR (100)  NULL,
    [DATA_C_VALUE]              VARCHAR (1000) NULL,
    [HELD_SECURITY]             BIT            NULL,
    [INDEX_SECURITY]            BIT            NULL,
    [ISIN]                      VARCHAR (20)   NULL,
    [SEDOL]                     VARCHAR (20)   NULL,
    [CUSIP]                     VARCHAR (20)   NULL,
    [SECURITY_TYPE]             VARCHAR (20)   NULL,
    [CURRENCY]                  VARCHAR (3)    NULL,
    [BLOOMBERG_LAST_UPDATED]    DATETIME       NULL,
    [STATUS]                    VARCHAR (20)   DEFAULT ('New') NULL,
    [PRIORITY]                  VARCHAR (20)   NULL,
    [OWNER]                     VARCHAR (50)   NULL,
    [TEAM]                      VARCHAR (50)   NULL,
    [RETENTION]                 INT            NULL,
    [COMMENT]                   VARCHAR (100)  NULL,
    [EXCEPTION_NAME]            VARCHAR (40)   NULL,
    [EXCEPTION_TYPE]            VARCHAR (50)   NULL,
    [BUSINESS_PROCESS_LEVEL]    INT            NULL,
    [HASVALUECHANGED]           INT            NULL,
    [DAYS_VALID]                INT            NULL,
    [OCCURRENCE]                INT            NULL,
    [EXCEPTION_AGE]             INT            NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)  DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT            DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION     NOT NULL,
    [TOLERANCE]                 VARCHAR (20)   NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC)
);

