CREATE TABLE [dbo].[T_ExpostViolation_Violation_IN] (
    [CADIS_BATCH_ID]               INT            NOT NULL,
    [CADIS_MSG_ID]                 INT            CONSTRAINT [DF__T_ExpostV__CADIS__00C4B547] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]              INT            NOT NULL,
    [CADIS_ROW_ID]                 INT            NOT NULL,
    [Violation_CADIS_ROW_ID]       INT            NULL,
    [Violation_ViolDateTime]       NVARCHAR (100) NULL,
    [Violation_ViolGrpID]          NVARCHAR (100) NULL,
    [Violation_ViolID]             NVARCHAR (100) NULL,
    [Violation_ViolSeverity]       NVARCHAR (100) NULL,
    [Violation_ViolStatus]         NVARCHAR (100) NULL,
    [Violation_ViolType]           NVARCHAR (100) NULL,
    [Violation_ViolPriority]       NVARCHAR (100) NULL,
    [Violation_ViolationTriggered] NVARCHAR (100) NULL,
    [Violation_ViolAsofDate]       NVARCHAR (100) NULL,
    [Rule_CADIS_ROW_ID]            INT            NULL,
    [Rule_RuleCurncy]              NVARCHAR (100) NULL,
    [Rule_RuleDesc]                NVARCHAR (100) NULL,
    [Rule_RuleLimit]               NVARCHAR (100) NULL,
    [Rule_RuleType]                NVARCHAR (100) NULL,
    [Rule_RuleWgtType]             NVARCHAR (100) NULL,
    [Rule_RuleCode]                NVARCHAR (100) NULL,
    [Rule_RuleName]                NVARCHAR (100) NULL,
    [Flags_CADIS_ROW_ID]           INT            NULL,
    [Flags_CopyNoteFlag]           NVARCHAR (100) NULL,
    [Flags_DayCounter]             NVARCHAR (100) NULL,
    [Flags_PrevViolNum]            NVARCHAR (100) NULL,
    [Flags_SuppressFlag]           NVARCHAR (100) NULL,
    [Flags_SuppressTolerance]      NVARCHAR (100) NULL,
    [Test_CADIS_ROW_ID]            INT            NULL,
    [Test_CurrTestVal]             NVARCHAR (100) NULL,
    [Test_PrevTestVal]             NVARCHAR (100) NULL,
    [Test_TestUnits]               NVARCHAR (100) NULL,
    [Scope_CADIS_ROW_ID]           INT            NULL,
    [Scope_ScopeCode]              NVARCHAR (100) NULL,
    [Scope_ScopeName]              NVARCHAR (100) NULL,
    [Scope_ScopeNum]               NVARCHAR (100) NULL,
    [Scope_ScopeType]              NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]        DATETIME       CONSTRAINT [DF__T_ExpostV__CADIS__01B8D980] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]         DATETIME       CONSTRAINT [DF__T_ExpostV__CADIS__02ACFDB9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]       NVARCHAR (50)  CONSTRAINT [DF__T_ExpostV__CADIS__03A121F2] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]        INT            CONSTRAINT [DF__T_ExpostV__CADIS__0495462B] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_ExpostViolation_Violation_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

