CREATE TABLE [dbo].[T_FE_FUND_PERFORMANCE] (
    [FILE_DATE]              DATETIME        NULL,
    [CITI_CODE]              VARCHAR (4)     NOT NULL,
    [SECTOR]                 VARCHAR (20)    NOT NULL,
    [PRICE_DATE]             DATETIME        NOT NULL,
    [UNIT_NAME]              VARCHAR (100)   NULL,
    [M1_PERFORMANCE]         DECIMAL (20, 2) NULL,
    [M1_RANK]                INT             NULL,
    [M1_QUARTILE]            INT             NULL,
    [Y1_PERFORMANCE]         DECIMAL (20, 2) NULL,
    [Y1_RANK]                INT             NULL,
    [Y1_QUARTILE]            INT             NULL,
    [YTD_PERFORMANCE]        DECIMAL (20, 2) NULL,
    [YTD_RANK]               INT             NULL,
    [YTD_QUARTILE]           INT             NULL,
    [Y3_PERFORMANCE]         DECIMAL (20, 2) NULL,
    [Y3_RANK]                INT             NULL,
    [Y3_QUARTILE]            INT             NULL,
    [D20140616_PERFORMANCE]  DECIMAL (20, 2) NULL,
    [D20140616_RANK]         INT             NULL,
    [D20140616_QUARTILE]     INT             NULL,
    [D20170412_PERFORMANCE]  DECIMAL (20, 2) NULL,
    [D20170412_RANK]         INT             NULL,
    [D20170412_QUARTILE]     INT             NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([CITI_CODE] ASC, [SECTOR] ASC, [PRICE_DATE] ASC) WITH (FILLFACTOR = 80)
);

