CREATE TABLE [dbo].[T_FILE_MONITOR] (
    [ID]                     INT           IDENTITY (1, 1) NOT NULL,
    [PORTER_NAME]            VARCHAR (100) NULL,
    [CURRENT_FILE]           VARCHAR (100) NULL,
    [STATUS]                 VARCHAR (20)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_FILE_MO__CADIS__5DB219E2] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_FILE_MO__CADIS__5EA63E1B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_FILE_MO__CADIS__5F9A6254] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_FILE_MO__CADIS__608E868D] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_FILE_M__3214EC278E13F6E0] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

