CREATE TABLE [dbo].[T_FUNDING_PORTFOLIO_ALLOCATION] (
    [AllocationID]            INT             NOT NULL,
    [FundingID]               INT             NULL,
    [FUND_SHORT_NAME]         VARCHAR (20)    NULL,
    [InitialAllocationAmount] DECIMAL (38, 2) NULL,
    [Currency]                VARCHAR (3)     NULL,
    [CADIS_SYSTEM_INSERTED]   DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]    DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]  NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PK_T_FUNDING_PORTFOLIO_ALLOCATION] PRIMARY KEY CLUSTERED ([AllocationID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_UQFUNDCurrency] FOREIGN KEY ([Currency]) REFERENCES [dbo].[T_REF_CURRENCY] ([ISO_CCY_CD]),
    CONSTRAINT [FK_UQFUNDPORTALLOCATIONID] FOREIGN KEY ([FundingID]) REFERENCES [dbo].[T_MASTER_FUNDING] ([FundingID]),
    CONSTRAINT [FK_UQFUNDSHID] FOREIGN KEY ([FUND_SHORT_NAME]) REFERENCES [dbo].[T_MASTER_FND] ([SHORT_NAME])
);

