CREATE TABLE [dbo].[T_ITG_FILE_MONITOR] (
    [TOPLEVELRUNID]          INT           NOT NULL,
    [EVENT_DATETIME]         DATETIME      NULL,
    [FILENAME]               VARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL,
    PRIMARY KEY CLUSTERED ([TOPLEVELRUNID] ASC) WITH (FILLFACTOR = 90)
);

