CREATE TABLE [dbo].[T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_EXCEPTION_AUDIT] (
    [AccountAuditId]                     INT            IDENTITY (1, 1) NOT NULL,
    [AuditDate]                          DATETIME       NULL,
    [AuditUser]                          VARCHAR (50)   NULL,
    [AccSalesForceID]                    VARCHAR (18)   NOT NULL,
    [AccFcaID]                           INT            NULL,
    [Old_AccFcaID]                       INT            NULL,
    [AccMatrixOutletId]                  VARCHAR (50)   NULL,
    [Old_AccMatrixOutletId]              VARCHAR (50)   NULL,
    [AccOwnerId]                         VARCHAR (18)   NULL,
    [Old_AccOwnerId]                     VARCHAR (50)   NULL,
    [AccOwnerName]                       VARCHAR (2000) NULL,
    [Old_AccOwnerName]                   VARCHAR (2000) NULL,
    [AccName]                            VARCHAR (1000) NULL,
    [Old_AccName]                        VARCHAR (1000) NULL,
    [AccOutletType]                      VARCHAR (100)  NULL,
    [Old_AccOutletType]                  VARCHAR (100)  NULL,
    [AccBillingStreet]                   VARCHAR (8000) NULL,
    [Old_AccBillingStreet]               VARCHAR (8000) NULL,
    [AccBillingCity]                     VARCHAR (100)  NULL,
    [Old_AccBillingCity]                 VARCHAR (100)  NULL,
    [AccBillingState]                    VARCHAR (100)  NULL,
    [Old_AccBillingState]                VARCHAR (100)  NULL,
    [AccBillingPostcode]                 VARCHAR (100)  NULL,
    [Old_AccBillingPostcode]             VARCHAR (100)  NULL,
    [AccBillingCountry]                  VARCHAR (100)  NULL,
    [Old_AccBillingCountry]              VARCHAR (100)  NULL,
    [AccLandline]                        VARCHAR (50)   NULL,
    [Old_AccLandline]                    VARCHAR (50)   NULL,
    [AccFax]                             VARCHAR (50)   NULL,
    [Old_AccFax]                         VARCHAR (50)   NULL,
    [AccWebsite]                         VARCHAR (128)  NULL,
    [Old_AccWebsite]                     VARCHAR (128)  NULL,
    [AccEmail]                           VARCHAR (128)  NULL,
    [Old_AccEmail]                       VARCHAR (128)  NULL,
    [AccFirmSegment]                     VARCHAR (100)  NULL,
    [Old_AccFirmSegment]                 VARCHAR (100)  NULL,
    [AccAuthStatus]                      VARCHAR (100)  NULL,
    [Old_AccAuthStatus]                  VARCHAR (100)  NULL,
    [AccPlatformsUsed]                   VARCHAR (1000) NULL,
    [Old_AccPlatformsUsed]               VARCHAR (1000) NULL,
    [AccVerifiedBy]                      VARCHAR (1000) NULL,
    [Old_AccVerifiedBy]                  VARCHAR (1000) NULL,
    [AccExistingCompanyRelationship]     VARCHAR (1000) NULL,
    [Old_AccExistingCompanyRelationship] VARCHAR (1000) NULL,
    [AccPriorityClient]                  VARCHAR (100)  NULL,
    [Old_AccPriorityClient]              VARCHAR (100)  NULL,
    [AccCalculatedPriority]              VARCHAR (50)   NULL,
    [Old_AccCalculatedPriority]          VARCHAR (50)   NULL,
    [AccKeyAccount]                      VARCHAR (100)  NULL,
    [Old_AccKeyAccount]                  VARCHAR (100)  NULL,
    [AccRegionCode]                      VARCHAR (100)  NULL,
    [Old_AccRegionCode]                  VARCHAR (100)  NULL,
    [WFPrimaryBusiness]                  VARCHAR (1000) NULL,
    [Old_WFPrimaryBusiness]              VARCHAR (1000) NULL,
    [MXPrimaryBusiness]                  VARCHAR (1000) NULL,
    [Old_MXPrimaryBusiness]              VARCHAR (1000) NULL,
    [RecordTypeName]                     VARCHAR (50)   NULL,
    [Old_RecordTypeName]                 VARCHAR (50)   NULL,
    [FCAStatus]                          VARCHAR (50)   NULL,
    [Old_FCAStatus]                      VARCHAR (50)   NULL,
    [MfidStatus]                         VARCHAR (100)  NULL,
    [Old_MfidStatus]                     VARCHAR (100)  NULL,
    [ActiveStatus]                       VARCHAR (100)  NULL,
    [Old_ActiveStatus]                   VARCHAR (100)  NULL,
    [ExportStatus]                       VARCHAR (20)   NOT NULL,
    [CADIS_SYSTEM_INSERTED]              DATETIME       CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_EXCEPTION_AUDIT_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]               DATETIME       CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_EXCEPTION_AUDIT_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]             VARCHAR (50)   CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_EXCEPTION_AUDIT_CSCB] DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([AccountAuditId] ASC) WITH (FILLFACTOR = 80)
);

