CREATE TABLE [dbo].[T_MASTER_FND_MARKET_VALUE] (
    [SOURCE]                          VARCHAR (50)    NOT NULL,
    [POSITION_TYPE]                   VARCHAR (50)    NOT NULL,
    [FUND_SHORT_NAME]                 VARCHAR (8000)  NOT NULL,
    [POSITION_DATE]                   DATETIME        NOT NULL,
    [TOTAL_MARKET_VALUE_LOCAL]        DECIMAL (20, 2) NULL,
    [TOTAL_MARKET_VALUE_BASE]         DECIMAL (20, 2) NULL,
    [STATUS]                          VARCHAR (20)    NULL,
    [TOTAL_ACCRUED_MARKET_VALUE_BASE] DECIMAL (20, 2) NULL,
    [CADIS_SYSTEM_INSERTED]           DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__7EF93B0A] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]            DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__7FED5F43] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]          NVARCHAR (50)   CONSTRAINT [DF__T_MASTER___CADIS__00E1837C] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]           INT             CONSTRAINT [DF__T_MASTER___CADIS__01D5A7B5] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED]       DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__02C9CBEE] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER__D5F8680478CE4D0F] PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC) WITH (FILLFACTOR = 90)
);

