CREATE TABLE [dbo].[T_MASTER_COMPLIANCE_VIOL_NOTE_DETAIL] (
    [CADIS_RUN_ID]         INT             NULL,
    [CADIS_PARENT_ID]      INT             NULL,
    [NOTEDETAILS_DATETIME] VARCHAR (50)    NULL,
    [NOTEDETAILS_NOTE]     NVARCHAR (1000) NULL,
    [NOTEDETAILS_USER]     VARCHAR (50)    NULL,
    [NOTE_TYPE]            VARCHAR (50)    NULL
);

