CREATE TABLE [dbo].[T_MASTER_COMPLIANCE_RULE_REVISION_ACCOUNT] (
    [CADIS_RUN_ID]              INT           NULL,
    [CADIS_PARENT_ID]           INT           NULL,
    [EVALUATION_EVALTYPEAFTER]  VARCHAR (50)  NULL,
    [EVALUATION_EVALTYPEBEFORE] VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTNAMEAFTER]    VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTNAMEBEFORE]   VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTTYPEAFTER]    VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTTYPEBEFORE]   VARCHAR (50)  NULL,
    [SCOPE_BROKERNAMEAFTER]     VARCHAR (50)  NULL,
    [SCOPE_BROKERNAMEBEFORE]    VARCHAR (50)  NULL,
    [SCOPE_BROKERTYPEAFTER]     VARCHAR (50)  NULL,
    [SCOPE_BROKERTYPEBEFORE]    VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           DEFAULT ((1)) NULL
);

