CREATE TABLE [dbo].[T_MASTER_SEC_FORWARD] (
    [EDM_SEC_ID]             INT              NOT NULL,
    [FIXED_CCY]              VARCHAR (3)      NULL,
    [CCY_PAIR_RATE]          DECIMAL (21, 11) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME         CONSTRAINT [DF__T_MASTER___CADIS__69B1A35C] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME         CONSTRAINT [DF__T_MASTER___CADIS__6AA5C795] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)    CONSTRAINT [DF__T_MASTER___CADIS__6B99EBCE] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT              CONSTRAINT [DF__T_MASTER___CADIS__6C8E1007] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_MASTER__B157E8F267C95AEA] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 90)
);

