CREATE TABLE [dbo].[T_MASTER_SEC_LIST] (
    [EDM_SEC_ID]             INT           NOT NULL,
    [LIST_NAME]              VARCHAR (50)  NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__3F6663D5] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__405A880E] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__414EAC47] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_MASTER___CADIS__4242D080] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_MASTER__3D822B5D3D7E1B63] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [LIST_NAME] ASC) WITH (FILLFACTOR = 90)
);

