CREATE TABLE [dbo].[T_MASTER_SEC_UNIVERSE] (
    [EDM_SEC_ID]                INT           NOT NULL,
    [STATUS]                    VARCHAR (20)  NULL,
    [DATA_QUALITY]              VARCHAR (20)  NULL,
    [HELD_SECURITY]             VARCHAR (1)   NULL,
    [INDEX_SECURITY]            VARCHAR (1)   NULL,
    [INTERESTED_SECURITY]       VARCHAR (1)   NULL,
    [UNDERLYING_SECURITY]       INT           NULL,
    [BLOOMBERG_LAST_UPDATED]    DATETIME      NULL,
    [LAST_HELD]                 DATETIME      NULL,
    [FIRST_HELD]                DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__2DA871A4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__2E9C95DD] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__2F90BA16] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_MASTER___CADIS__3084DE4F] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__31790288] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER__B157E8F247079637] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 90)
);

