CREATE TABLE [dbo].[T_MASTER_COMPLIANCE_RULE_REVISION_RULEGROUP] (
    [CADIS_RUN_ID]                  INT           NULL,
    [CADIS_PARENT_ID]               INT           NULL,
    [RULEGROUP_RULEGROUPNAMEAFTER]  VARCHAR (50)  NULL,
    [RULEGROUP_RULEGROUPNAMEBEFORE] VARCHAR (50)  NULL,
    [RULEGROUP_FOLDERNAMEAFTER]     VARCHAR (50)  NULL,
    [RULEGROUP_FOLDERNAMEBEFORE]    VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]         DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]          DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]        NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]         INT           DEFAULT ((1)) NULL
);

