CREATE TABLE [dbo].[T_MASTER_SEC_RATING] (
    [EDM_SEC_ID]                INT           NOT NULL,
    [RATER]                     VARCHAR (50)  NOT NULL,
    [RATING_TYPE]               VARCHAR (50)  NOT NULL,
    [RATING]                    VARCHAR (50)  NULL,
    [RATING_DATE]               DATETIME      NULL,
    [OUTLOOK_RATING]            VARCHAR (20)  NULL,
    [WATCH_FLAG]                VARCHAR (1)   CONSTRAINT [DF__T_MASTER___WATCH__241F076A] DEFAULT ('N') NULL,
    [WATCH_DATE]                DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__25132BA3] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__26074FDC] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__26FB7415] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_MASTER___CADIS__27EF984E] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__28E3BC87] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER__91A17E0BC0182D4D] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [RATER] ASC, [RATING_TYPE] ASC) WITH (FILLFACTOR = 90)
);

