CREATE TABLE [dbo].[T_MASTER_SEC_CLASSIFICATION] (
    [EDM_SEC_ID]                INT           NOT NULL,
    [CLASS_SCHEME]              VARCHAR (20)  NOT NULL,
    [CLASS_LEVEL]               INT           NULL,
    [CLASS_LEVEL_NAME]          VARCHAR (150) NULL,
    [CLASS_CODE]                VARCHAR (20)  NULL,
    [EFFECTIVE_DATE]            DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__14DCC3DA] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__15D0E813] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__16C50C4C] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_MASTER___CADIS__17B93085] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__18AD54BE] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER__141A589C245B2873] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [CLASS_SCHEME] ASC) WITH (FILLFACTOR = 90)
);

