CREATE TABLE [dbo].[T_MASTER_SEC_ALTERNATIVE_ID] (
    [EDM_SEC_ID]                INT           NOT NULL,
    [ID_TYPE]                   VARCHAR (20)  NOT NULL,
    [ID_VALUE]                  VARCHAR (100) NULL,
    [ACTIVE]                    VARCHAR (1)   CONSTRAINT [DF__T_MASTER___ACTIV__0A5F3567] DEFAULT ('Y') NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__0B5359A0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__0C477DD9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__0D3BA212] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_MASTER___CADIS__0E2FC64B] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__0F23EA84] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER__8323263AFD5EFE6C] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [ID_TYPE] ASC) WITH (FILLFACTOR = 90)
);

