CREATE TABLE [dbo].[T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_AUDIT] (
    [AccountAuditId]                 INT            IDENTITY (1, 1) NOT NULL,
    [AuditDate]                      DATETIME       NULL,
    [AuditUser]                      VARCHAR (50)   NULL,
    [AccSivId]                       VARCHAR (100)  NOT NULL,
    [AsAtDate]                       DATETIME       NOT NULL,
    [CaseID]                         INT            NOT NULL,
    [Type]                           VARCHAR (20)   NOT NULL,
    [AccFcaID]                       INT            NULL,
    [AccSalesForceID]                VARCHAR (18)   NULL,
    [AccMatrixOutletId]              VARCHAR (50)   NULL,
    [AccParentSivId]                 VARCHAR (100)  NULL,
    [AccOwnerId]                     VARCHAR (18)   NULL,
    [AccOwnerName]                   VARCHAR (2000) NULL,
    [AccName]                        VARCHAR (1000) NULL,
    [AccOutletType]                  VARCHAR (100)  NULL,
    [AccBillingStreet]               VARCHAR (8000) NULL,
    [AccBillingCity]                 VARCHAR (100)  NULL,
    [AccBillingState]                VARCHAR (100)  NULL,
    [AccBillingPostcode]             VARCHAR (100)  NULL,
    [AccBillingCountry]              VARCHAR (100)  NULL,
    [AccLandline]                    VARCHAR (50)   NULL,
    [AccFax]                         VARCHAR (50)   NULL,
    [AccWebsite]                     VARCHAR (128)  NULL,
    [AccEmail]                       VARCHAR (128)  NULL,
    [AccFirmSegment]                 VARCHAR (100)  NULL,
    [AccAuthStatus]                  VARCHAR (100)  NULL,
    [AccPlatformsUsed]               VARCHAR (1000) NULL,
    [AccVerifiedBy]                  VARCHAR (1000) NULL,
    [AccExistingCompanyRelationship] VARCHAR (1000) NULL,
    [AccPriorityClient]              VARCHAR (100)  NULL,
    [AccCalculatedPriority]          VARCHAR (50)   NULL,
    [AccKeyAccount]                  VARCHAR (100)  NULL,
    [AccRegionCode]                  VARCHAR (100)  NULL,
    [AccIsLocked]                    VARCHAR (20)   NULL,
    [WFPrimaryBusiness]              VARCHAR (1000) NULL,
    [MXPrimaryBusiness]              VARCHAR (1000) NULL,
    [RecordTypeName]                 VARCHAR (50)   NULL,
    [AccParentSalesforceId]          VARCHAR (20)   NULL,
    [FCAStatus]                      VARCHAR (50)   NULL,
    [MfidStatus]                     VARCHAR (100)  NULL,
    [IsActive]                       VARCHAR (100)  NULL,
    [ExportStatus]                   VARCHAR (20)   NOT NULL,
    [CADIS_SYSTEM_INSERTED]          DATETIME       CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_AUDIT_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]           DATETIME       CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_AUDIT_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]         VARCHAR (50)   CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_ACCOUNT_AUDIT_CSCB] DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([AccountAuditId] ASC) WITH (FILLFACTOR = 80)
);

