CREATE TABLE [dbo].[T_MASTER_SEC_RELATIONSHIP] (
    [EDM_SEC_ID]             INT           NOT NULL,
    [RELATED_EDM_SEC_ID]     INT           NOT NULL,
    [RELATIONSHIP_TYPE]      VARCHAR (100) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__6D8D2138] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__6E814571] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__6F7569AA] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_MASTER___CADIS__70698DE3] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_MASTER__C9F50DB97251D655] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [RELATED_EDM_SEC_ID] ASC, [RELATIONSHIP_TYPE] ASC) WITH (FILLFACTOR = 90)
);

