CREATE TABLE [dbo].[T_MASTER_SEC_PTY_ROLE] (
    [EDM_PTY_ID]                INT           NOT NULL,
    [ROLE_TYPE]                 VARCHAR (50)  NOT NULL,
    [EDM_SEC_ID]                INT           NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__06ED0088] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__07E124C1] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_MASTER___CADIS__08D548FA] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_MASTER___CADIS__09C96D33] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_MASTER___CADIS__0ABD916C] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_MASTER_SEC_PTY_ROLE] PRIMARY KEY CLUSTERED ([EDM_PTY_ID] ASC, [ROLE_TYPE] ASC, [EDM_SEC_ID] ASC) WITH (FILLFACTOR = 90)
);

