CREATE TABLE [dbo].[T_MASTER_SEC_SCHEDULE] (
    [EDM_SEC_ID]             INT             NOT NULL,
    [SCHEDULE_TYPE]          VARCHAR (50)    NOT NULL,
    [SCHEDULE_DATE]          DATETIME        NOT NULL,
    [PRICE]                  DECIMAL (26, 6) NULL,
    [AMOUNT]                 DECIMAL (26, 2) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__29D7E0C0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__2ACC04F9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   CONSTRAINT [DF__T_MASTER___CADIS__2BC02932] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT             CONSTRAINT [DF__T_MASTER___CADIS__2CB44D6B] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_MASTER__E51CBB7FB7A6EB00] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [SCHEDULE_TYPE] ASC, [SCHEDULE_DATE] ASC) WITH (FILLFACTOR = 90)
);

