CREATE TABLE [dbo].[T_MASTER_COMPLIANCE_RULE_ACCOUNTS] (
    [CADIS_RUN_ID]           INT           NULL,
    [CADIS_PARENT_ID]        INT           NULL,
    [EVALUATION_EVALTYPE]    VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTNAME]      VARCHAR (50)  NULL,
    [SCOPE_ACCOUNTTYPE]      VARCHAR (50)  NULL,
    [SCOPE_BROKERNAME]       VARCHAR (50)  NULL,
    [SCOPE_BROKERTYPE]       VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL
);

