CREATE TABLE [dbo].[T_MASTER_COMPLIANCE_RULE_REVISION_ATTRIBUTE_AFTER] (
    [CADIS_RUN_ID]           INT           NULL,
    [CADIS_PARENT_ID]        INT           NULL,
    [VALUE_VALUE_INNERTEXT]  VARCHAR (50)  NULL,
    [VALUE_VALUE_INNERTEXT2] VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL
);

