CREATE TABLE [dbo].[T_MATRIX_PROCESS_SALESFORCE_CONTACT_EXCEPTION_AUDIT] (
    [ContactAuditId]         INT            IDENTITY (1, 1) NOT NULL,
    [AuditDate]              DATETIME       NULL,
    [AuditUser]              VARCHAR (50)   NULL,
    [CntSalesforceId]        VARCHAR (18)   NOT NULL,
    [CntAccountSalesforceId] VARCHAR (18)   NOT NULL,
    [CntFcaId]               VARCHAR (20)   NULL,
    [Old_CntFcaId]           VARCHAR (20)   NULL,
    [CntAccountFcaId]        VARCHAR (20)   NULL,
    [Old_CntAccountFcaId]    VARCHAR (20)   NULL,
    [CntOwnerId]             VARCHAR (18)   NULL,
    [Old_CntOwnerId]         VARCHAR (18)   NULL,
    [CntOwnerName]           VARCHAR (200)  NULL,
    [Old_CntOwnerName]       VARCHAR (200)  NULL,
    [CntAccountSivId]        VARCHAR (100)  NULL,
    [Old_CntAccountSivId]    VARCHAR (100)  NULL,
    [CntMatrixId]            VARCHAR (20)   NULL,
    [Old_CntMatrixId]        VARCHAR (20)   NULL,
    [CntSalutation]          VARCHAR (20)   NULL,
    [Old_CntSalutation]      VARCHAR (20)   NULL,
    [CntFirstName]           VARCHAR (100)  NULL,
    [Old_CntFirstName]       VARCHAR (100)  NULL,
    [CntLastName]            VARCHAR (100)  NULL,
    [Old_CntLastName]        VARCHAR (100)  NULL,
    [CntJobTitle]            VARCHAR (100)  NULL,
    [Old_CntJobTitle]        VARCHAR (100)  NULL,
    [CntMailingStreet]       VARCHAR (1000) NULL,
    [Old_CntMailingStreet]   VARCHAR (1000) NULL,
    [CntMailingCity]         VARCHAR (100)  NULL,
    [Old_CntMailingCity]     VARCHAR (100)  NULL,
    [CntMailingState]        VARCHAR (100)  NULL,
    [Old_CntMailingState]    VARCHAR (100)  NULL,
    [CntMailingPostcode]     VARCHAR (100)  NULL,
    [Old_CntMailingPostcode] VARCHAR (100)  NULL,
    [CntMailingCountry]      VARCHAR (100)  NULL,
    [Old_CntMailingCountry]  VARCHAR (100)  NULL,
    [CntLandline]            VARCHAR (50)   NULL,
    [Old_CntLandline]        VARCHAR (50)   NULL,
    [CntMobile]              VARCHAR (50)   NULL,
    [Old_CntMobile]          VARCHAR (50)   NULL,
    [CntFax]                 VARCHAR (50)   NULL,
    [Old_CntFax]             VARCHAR (50)   NULL,
    [CntEmail]               VARCHAR (128)  NULL,
    [Old_CntEmail]           VARCHAR (128)  NULL,
    [CntIsCf1]               VARCHAR (5)    NULL,
    [Old_CntIsCf1]           VARCHAR (5)    NULL,
    [CntIsCf2]               VARCHAR (5)    NULL,
    [Old_CntIsCf2]           VARCHAR (5)    NULL,
    [CntIsCf3]               VARCHAR (5)    NULL,
    [Old_CntIsCf3]           VARCHAR (5)    NULL,
    [CntIsCf4]               VARCHAR (5)    NULL,
    [Old_CntIsCf4]           VARCHAR (5)    NULL,
    [CntIsCf10]              VARCHAR (5)    NULL,
    [Old_CntIsCf10]          VARCHAR (5)    NULL,
    [CntIsCf11]              VARCHAR (5)    NULL,
    [Old_CntIsCf11]          VARCHAR (5)    NULL,
    [CntIsCf30]              VARCHAR (5)    NULL,
    [Old_CntIsCf30]          VARCHAR (5)    NULL,
    [CntVerifiedBy]          VARCHAR (100)  NULL,
    [Old_CntVerifiedBy]      VARCHAR (100)  NULL,
    [FCAStatus]              VARCHAR (50)   NULL,
    [Old_FCAStatus]          VARCHAR (50)   NULL,
    [MfidStatus]             VARCHAR (100)  NULL,
    [Old_MfidStatus]         VARCHAR (100)  NULL,
    [ActiveStatus]           VARCHAR (100)  NULL,
    [Old_ActiveStatus]       VARCHAR (100)  NULL,
    [ExportStatus]           VARCHAR (20)   NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME       CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_CONTACT_EXCEPTION_AUDIT_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME       CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_CONTACT_EXCEPTION_AUDIT_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] VARCHAR (50)   CONSTRAINT [DF_T_MATRIX_PROCESS_SALESFORCE_CONTACT_EXCEPTION_AUDIT_CSCB] DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([ContactAuditId] ASC) WITH (FILLFACTOR = 80)
);

