CREATE TABLE [dbo].[T_MASTER_SEC_INCOME_KEYS] (
    [FUND_SHORT_NAME]        VARCHAR (20)  NOT NULL,
    [EDM_SEC_ID]             INT           NOT NULL,
    [FUND_FISCAL_YEAR]       INT           NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_RUNID]     INT           DEFAULT ((0)) NOT NULL,
    [CADIS_SYSTEM_TOPRUNID]  INT           DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC) WITH (FILLFACTOR = 80)
);

