CREATE TABLE [dbo].[T_MASTER_FUND_FLOW] (
    [FUND_SHORT_NAME]           VARCHAR (15)    NOT NULL,
    [TRANSACTION_DATE]          DATETIME        NOT NULL,
    [CURRENCY]                  VARCHAR (20)    NOT NULL,
    [FUND_FLOW_TYPE]            VARCHAR (20)    NOT NULL,
    [FLOW_TYPE]                 VARCHAR (100)   NOT NULL,
    [SOURCE_TYPE]               VARCHAR (20)    NOT NULL,
    [MARKET_VALUE]              DECIMAL (18, 2) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__2AE839A1] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__2BDC5DDA] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   CONSTRAINT [DF__T_MASTER___CADIS__2CD08213] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             CONSTRAINT [DF__T_MASTER___CADIS__2DC4A64C] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        CONSTRAINT [DF__T_MASTER___CADIS__2EB8CA85] DEFAULT (getdate()) NULL,
    [SOURCE]                    VARCHAR (20)    NULL,
    [DATA_SOURCE]               VARCHAR (50)    NULL,
    CONSTRAINT [PK__T_MASTER__2D68B037807F007C] PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [CURRENCY] ASC, [FUND_FLOW_TYPE] ASC, [FLOW_TYPE] ASC, [SOURCE_TYPE] ASC) WITH (FILLFACTOR = 90)
);

