CREATE TABLE [dbo].[T_NOTIFICATION_SLACK] (
    [SOURCE_SLA_SUBSCRIBER_ID] INT           NOT NULL,
    [SUBSCRIBER_ID]            INT           NULL,
    [DATA_CHANNEL_ID]          INT           NULL,
    [SLACK_NOTIFICATION_SENT]  DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]    DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]   NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_SLA_SUBSCRIBER_ID] ASC) WITH (FILLFACTOR = 80)
);

