CREATE TABLE [dbo].[T_NOTIFICATION] (
    [DATA_CHANNEL_ID]              INT           NOT NULL,
    [SOURCE]                       VARCHAR (30)  NOT NULL,
    [ENTITY]                       VARCHAR (50)  NOT NULL,
    [DESCRIPTION]                  VARCHAR (150) NOT NULL,
    [DIRECTION]                    VARCHAR (3)   NOT NULL,
    [EXPECTED_DELIVERY_TIME]       DATETIME      NULL,
    [ACTUAL_DELIVERY]              DATETIME      NULL,
    [DELIVERY_SLA_MET]             BIT           NULL,
    [EXPECTED_SLA_COMPLETION]      DATETIME      NULL,
    [ACTUAL_SLA_COMPLETION]        DATETIME      NULL,
    [PROCESSING_SLA_MET]           BIT           NULL,
    [DELIVERY_NOTIFICATION_SENT]   DATETIME      NULL,
    [PROCESSING_NOTIFICATION_SENT] DATETIME      NULL,
    [MARKIT_SOLUTION]              VARCHAR (150) NULL,
    [MORNING_CHECK]                VARCHAR (50)  NULL,
    [CADIS_SYSTEM_INSERTED]        DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]         DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]       NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]        INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED]    DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([DATA_CHANNEL_ID] ASC) WITH (FILLFACTOR = 80)
);

