CREATE TABLE [dbo].[T_NT_TCA_TRADE_EXECUTIONS_OUT] (
    [ROW_ID]                 INT             NOT NULL,
    [BUSINESS_DATE]          DATETIME        NULL,
    [ACCT_NO]                VARCHAR (8)     NULL,
    [REFERENCE_NUM]          VARCHAR (16)    NULL,
    [VNU]                    VARCHAR (4)     NULL,
    [ORDER]                  VARCHAR (6)     NULL,
    [EXECUTION_TIME]         DATETIME        NULL,
    [TRADE_REF_WTS]          VARCHAR (40)    NULL,
    [COMMISSION]             DECIMAL (18, 3) NULL,
    [CLEARING_FEE]           DECIMAL (18, 3) NULL,
    [EXCHANGE_FEE]           DECIMAL (18, 3) NULL,
    [MARKET_LEVY]            DECIMAL (18, 3) NULL,
    [EXCHANGE_LEVY]          DECIMAL (18, 3) NULL,
    [STAMP_DUTY]             DECIMAL (18, 3) NULL,
    [TAX]                    DECIMAL (18, 3) NULL,
    [OTHER_CHARGE]           DECIMAL (18, 3) NULL,
    [LOCAL_CHARGE]           DECIMAL (18, 3) NULL,
    [ORDER_DATE_TIME]        DATETIME        NULL,
    [MARKET_BID_PRICE]       DECIMAL (18, 3) NULL,
    [MARKET_ASK_PRICE]       DECIMAL (18, 3) NULL,
    [BROKER_EXEC_COMM]       DECIMAL (18, 3) NULL,
    [RESEARCH_PAYMENT]       DECIMAL (18, 3) NULL,
    [MARK_UP]                DECIMAL (18, 3) NULL,
    [FX_ISIN]                VARCHAR (12)    NULL,
    [CONFIRMATION_DATE_TIME] DATETIME        NULL,
    [VENUE_BIC]              VARCHAR (12)    NULL,
    [LEI_CODE_FOR_VENUE]     VARCHAR (20)    NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

