CREATE TABLE [dbo].[T_NT_EARNED_INCOME_IN_STORE] (
    [ID]                         INT           IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_NUMBER]             VARCHAR (255) NULL,
    [SECURITY_NUMBER]            VARCHAR (255) NULL,
    [VALUATION_DATE]             VARCHAR (255) NULL,
    [SECURITY_DESCRIPTION]       VARCHAR (255) NULL,
    [SEDOL]                      VARCHAR (255) NULL,
    [CUSIP]                      VARCHAR (255) NULL,
    [COUNTRY_OF_TAXATION]        VARCHAR (255) NULL,
    [STATE_CODE]                 VARCHAR (255) NULL,
    [ASSET_GROUP]                VARCHAR (255) NULL,
    [EX_DATE_SHARES]             VARCHAR (255) NULL,
    [EX_DATE]                    VARCHAR (255) NULL,
    [ACCRUED_INCOME]             VARCHAR (255) NULL,
    [INCOME_RECEIVED]            VARCHAR (255) NULL,
    [PRIOR_INC_ACCRUED]          VARCHAR (255) NULL,
    [INCOME_EARNED]              VARCHAR (255) NULL,
    [AMORT_ACCRUED]              VARCHAR (255) NULL,
    [AMORT_SOLD]                 VARCHAR (255) NULL,
    [PRIOR_AMORT_ACCRUED]        VARCHAR (255) NULL,
    [AMORT_EARNED]               VARCHAR (255) NULL,
    [TOTAL_INC_AND_AMORT_EARNED] VARCHAR (255) NULL,
    [UNITS]                      VARCHAR (255) NULL,
    [FUND_NET_INCOME]            VARCHAR (255) NULL,
    [RATE]                       VARCHAR (255) NULL,
    [CADIS_SYSTEM_INSERTED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]       DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]     NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_RUNID]         INT           DEFAULT ((0)) NOT NULL,
    [CADIS_SYSTEM_TOPRUNID]      INT           DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

