CREATE TABLE [dbo].[T_NT_FUND_PERFORMANCE_ATTRIBUTION_IN] (
    [FILE_NAME]              VARCHAR (100)    NULL,
    [FILE_DATE]              DATETIME         NULL,
    [FILE_TYPE]              VARCHAR (20)     NULL,
    [AS_AT_DATE]             DATETIME         NULL,
    [SEDOL]                  VARCHAR (7)      NOT NULL,
    [SECURITY_NAME]          VARCHAR (100)    NULL,
    [PREFERRED_NAME]         VARCHAR (50)     NULL,
    [ISIN]                   VARCHAR (12)     NULL,
    [SECTOR]                 VARCHAR (50)     NULL,
    [COUNTRY]                VARCHAR (50)     NULL,
    [MATURITY_STAGE]         VARCHAR (20)     NULL,
    [MKT_CAP]                VARCHAR (20)     NULL,
    [LISTING_STATUS]         VARCHAR (20)     NULL,
    [CTR_TO_WI0001]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0002]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0003]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0004]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0005]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0006]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0007]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0013]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0014]          DECIMAL (20, 10) NULL,
    [CTR_TO_WI0018]          DECIMAL (20, 10) NULL,
    [Filler]                 VARCHAR (20)     NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    [Filler1]                VARCHAR (20)     NULL,
    [Filler2]                VARCHAR (20)     NULL,
    [Fund]                   VARCHAR (20)     NULL,
    [SectorBM]               VARCHAR (20)     NULL,
    [Filler4]                VARCHAR (20)     NULL,
    [BenchMarkWeight]        DECIMAL (18, 2)  NULL,
    PRIMARY KEY CLUSTERED ([SEDOL] ASC) WITH (FILLFACTOR = 80)
);

