CREATE TABLE [dbo].[T_NT_FX] (
    [FILE_NAME]              VARCHAR (70)     NOT NULL,
    [FILE_TYPE]              VARCHAR (20)     NULL,
    [FILE_DATE]              DATE             NULL,
    [NUMBER_OF_RECORDS]      INT              NULL,
    [CONSOLIDATION]          VARCHAR (20)     NULL,
    [ACCOUNT NUMBER]         VARCHAR (20)     NULL,
    [FROM DATE]              DATE             NULL,
    [THROUGH DATE]           DATE             NOT NULL,
    [COUNTRY NAME]           VARCHAR (50)     NOT NULL,
    [CURRENCY NAME - ASSET]  VARCHAR (100)    NOT NULL,
    [C-BSE-CURR]             VARCHAR (20)     NULL,
    [CURRENCY CODE]          VARCHAR (20)     NOT NULL,
    [R-EXCH]                 DECIMAL (20, 10) NULL,
    [P-EXCH-RT-CHG]          DECIMAL (20, 10) NULL,
    [ERROR CODE]             VARCHAR (20)     NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME         CONSTRAINT [DF__T_NT_FX_N__CADIS__20101612] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME         CONSTRAINT [DF__T_NT_FX_N__CADIS__21043A4B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)    CONSTRAINT [DF__T_NT_FX_N__CADIS__21F85E84] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT              CONSTRAINT [DF__T_NT_FX_N__CADIS__22EC82BD] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_NT_FX___6DDC3CF9BBEA9437] PRIMARY KEY CLUSTERED ([COUNTRY NAME] ASC, [CURRENCY CODE] ASC) WITH (FILLFACTOR = 80)
);

