CREATE TABLE [dbo].[T_NT_TCA_CTM_TRADE_BLOTTER] (
    [TRADE_REFERENCE_NT]           VARCHAR (22)    NOT NULL,
    [TRADE_REFERENCE]              VARCHAR (22)    NULL,
    [FILE_NAME]                    VARCHAR (400)   NULL,
    [FILE_DATE]                    DATETIME        NULL,
    [NUM_OF_ROWS]                  INT             NULL,
    [COMPANY]                      VARCHAR (7)     NULL,
    [FUND]                         VARCHAR (15)    NULL,
    [CUSTODIAN_ACCOUNT]            VARCHAR (15)    NULL,
    [TRANSACTION_TYPE]             VARCHAR (7)     NULL,
    [INSTRUMENT_TYPE]              VARCHAR (7)     NULL,
    [ASSET_CLASS]                  VARCHAR (7)     NULL,
    [DATE_RECEIVED]                DATETIME        NULL,
    [TIME_RECEIVED]                TIME (7)        NULL,
    [TRADE_DATE]                   DATETIME        NULL,
    [SETTLEMENT_DATE]              DATETIME        NULL,
    [MATURITY_DATE]                DATETIME        NULL,
    [BLOCK_REFERENCE_NT]           VARCHAR (22)    NULL,
    [BLOCK_REFERENCE]              VARCHAR (22)    NULL,
    [BUY/SELL]                     VARCHAR (7)     NULL,
    [NOMINAL/QUANTITY]             INT             NULL,
    [ORIGINAL_FACE]                VARCHAR (255)   NULL,
    [PRICE]                        DECIMAL (18, 6) NULL,
    [PRICE_CCY]                    VARCHAR (3)     NULL,
    [SETTLEMENT_AMOUNT]            DECIMAL (18, 6) NULL,
    [SETTLEMENT_CCY]               VARCHAR (3)     NULL,
    [NET_CONSIDERATION]            DECIMAL (18, 6) NULL,
    [GROSS_CONSIDERATION]          DECIMAL (18, 6) NULL,
    [ACCRUED_INTEREST]             DECIMAL (18, 6) NULL,
    [CLEARING_FEE]                 DECIMAL (18, 6) NULL,
    [COMMISSION]                   DECIMAL (18, 6) NULL,
    [EXCHANGE_FEE]                 DECIMAL (18, 6) NULL,
    [JSE_LEVY]                     DECIMAL (18, 6) NULL,
    [PTM_LEVY]                     DECIMAL (18, 6) NULL,
    [STAMP_DUTY]                   DECIMAL (18, 6) NULL,
    [TAX]                          DECIMAL (18, 6) NULL,
    [OTHER_CHARGE]                 DECIMAL (18, 6) NULL,
    [LOCAL_CHARGE]                 DECIMAL (18, 6) NULL,
    [ASSET_ID_ISIN]                VARCHAR (15)    NULL,
    [ASSET_ID_SEDOL]               VARCHAR (15)    NULL,
    [ASSET_ID_CUSIP]               VARCHAR (15)    NULL,
    [ASSET_ID_FUNDMASTER]          VARCHAR (15)    NULL,
    [ASSET_ID_IM]                  VARCHAR (31)    NULL,
    [ASSET_ID_TICKER]              VARCHAR (15)    NULL,
    [ASSET_ID_BLOOMBERG]           VARCHAR (15)    NULL,
    [ASSET_DESCRIPTION]            VARCHAR (255)   NULL,
    [FACE_FACTOR]                  VARCHAR (255)   NULL,
    [INDEX/PRICE_FACTOR]           VARCHAR (255)   NULL,
    [ETD_CONTRACT_MONTH]           VARCHAR (255)   NULL,
    [ETD_CONTRACT_YEAR]            VARCHAR (255)   NULL,
    [ETD_STRIKE_PRICE]             DECIMAL (18, 6) NULL,
    [ETD_TYPE]                     VARCHAR (255)   NULL,
    [ETD_EXCHANGE]                 VARCHAR (255)   NULL,
    [ETD_PROMPT_DATE]              DATETIME        NULL,
    [ETD_FLEX_DATE]                DATETIME        NULL,
    [ETD_PRODUCT_TYPE]             VARCHAR (255)   NULL,
    [ETD_CALL/PUT_INDICATOR]       VARCHAR (255)   NULL,
    [EXECUTING_BROKER_NAME]        VARCHAR (255)   NULL,
    [EXECUTING_BROKER_BIC]         VARCHAR (255)   NULL,
    [EXECUTING_BROKER_CLIENT_CODE] VARCHAR (255)   NULL,
    [CLEARING_BROKER_NAME]         VARCHAR (255)   NULL,
    [CLEARING_BROKER_BIC]          VARCHAR (255)   NULL,
    [ISSUER]                       VARCHAR (255)   NULL,
    [CUSTODIAN_NAME]               VARCHAR (255)   NULL,
    [CUSTODIAN_BIC]                VARCHAR (255)   NULL,
    [FX_COVER]                     VARCHAR (255)   NULL,
    [FX_COVER_CCY]                 VARCHAR (3)     NULL,
    [RATE]                         VARCHAR (255)   NULL,
    [BUY_AMOUNT]                   VARCHAR (255)   NULL,
    [BUY_CCY]                      VARCHAR (3)     NULL,
    [SELL_AMOUNT]                  VARCHAR (255)   NULL,
    [SELL_CCY]                     VARCHAR (3)     NULL,
    [CLS_ELIGIBLE]                 VARCHAR (255)   NULL,
    [NDF_FIXING_DATE]              VARCHAR (255)   NULL,
    [OPEN/CLOSE]                   VARCHAR (255)   NULL,
    [INTEREST_AMOUNT]              VARCHAR (255)   NULL,
    [MATURITY_AMOUNT]              VARCHAR (255)   NULL,
    [PRINCIPLE_AMOUNT_ROLLED]      VARCHAR (255)   NULL,
    [INTEREST_AMOUNT_ROLLED]       VARCHAR (255)   NULL,
    [ADDITIONAL_PRINCIPAL_ROLLED]  VARCHAR (255)   NULL,
    [PRINCIPAL_REPAID]             VARCHAR (255)   NULL,
    [INTEREST_REPAID]              VARCHAR (255)   NULL,
    [STRATEGY_CODE]                VARCHAR (255)   NULL,
    [INVESTMENT_STRATEGY]          VARCHAR (255)   NULL,
    [SHORT_SALES]                  VARCHAR (255)   NULL,
    [TAX_STATUS]                   VARCHAR (255)   NULL,
    [TRANSACTION_CODE]             VARCHAR (255)   NULL,
    [REBOOK_INDICATOR]             VARCHAR (255)   NULL,
    [RELATED_REF]                  VARCHAR (255)   NULL,
    [REPO_REFERENCE]               VARCHAR (255)   NULL,
    [TRADE_STATUS]                 VARCHAR (255)   NULL,
    [CANCELLATION_DATE]            DATETIME        NULL,
    [CTM_SENT_TIME]                DATETIME        NULL,
    [CTM_RECEIVED_TIME]            DATETIME        NULL,
    [CADIS_SYSTEM_INSERTED]        DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]         DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]       NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([TRADE_REFERENCE_NT] ASC)
);

