CREATE TABLE [dbo].[T_NT_EARNED_INCOME_TOTAL_IN_STORE] (
    [ID]                         INT             IDENTITY (1, 1) NOT NULL,
    [ACCRUED_INCOME]             DECIMAL (18, 4) NULL,
    [INCOME_RECEIVED]            DECIMAL (18, 4) NULL,
    [PRIOR_INC_ACCRUED]          DECIMAL (18, 4) NULL,
    [INCOME_EARNED]              DECIMAL (18, 4) NULL,
    [AMORT_ACCRUED]              DECIMAL (18, 4) NULL,
    [AMORT_SOLD]                 DECIMAL (18, 4) NULL,
    [PRIOR_AMORT_ACCRUED]        DECIMAL (18, 4) NULL,
    [AMORT_EARNED]               DECIMAL (18, 4) NULL,
    [TOTAL_INC_AND_AMORT_EARNED] DECIMAL (18, 4) NULL,
    [CADIS_SYSTEM_INSERTED]      DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]       DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]     NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_RUNID]         INT             DEFAULT ((0)) NOT NULL,
    [CADIS_SYSTEM_TOPRUNID]      INT             DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

