CREATE TABLE [dbo].[T_NT_DIVIDENDS_INCOME_REC_RPT] (
    [ACCOUNT_NUMBER]          VARCHAR (50)    NOT NULL,
    [DATE]                    DATETIME        NOT NULL,
    [CUSIP]                   VARCHAR (20)    NULL,
    [SEDOL]                   VARCHAR (20)    NULL,
    [SEC_DESCRIPTION]         VARCHAR (50)    NOT NULL,
    [TOTAL_EQUITY]            DECIMAL (18, 2) NULL,
    [TOTAL_DEBT]              DECIMAL (18, 2) NULL,
    [INCOME_EXPENSE_TRANSFER] DECIMAL (18, 2) NULL,
    [REALIZED_EXCH_GL]        DECIMAL (18, 2) NULL,
    [UNREALIZED_EXCH_GL]      DECIMAL (18, 2) NULL,
    [EXCH_GAIN_LOSS]          DECIMAL (18, 2) NULL,
    [INCOME_DISTRIBUTIONS]    DECIMAL (18, 2) NULL,
    [EQL_CREATIONS]           DECIMAL (18, 2) NULL,
    [EQL_LIQUIDATIONS]        DECIMAL (18, 2) NULL,
    [CURRENT_NET_INCOME]      DECIMAL (18, 2) NULL,
    [UNITS_IN_ISSUE]          DECIMAL (18, 4) NULL,
    [REVISED_INCOME_RATE]     DECIMAL (18, 4) NULL,
    [CADIS_SYSTEM_INSERTED]   DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]    DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]  NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [DATE] ASC, [SEC_DESCRIPTION] ASC) WITH (FILLFACTOR = 90)
);

