CREATE TABLE [dbo].[T_NT_DIVIDENDS_INCOME_REC_RPT_PRE] (
    [ACCOUNT_NUMBER]          VARCHAR (50)  NOT NULL,
    [DATE]                    DATETIME      NOT NULL,
    [CUSIP]                   VARCHAR (20)  NULL,
    [SEDOL]                   VARCHAR (20)  NULL,
    [SEC_DESCRIPTION]         VARCHAR (50)  NOT NULL,
    [TOTAL_EQUITY]            VARCHAR (200) NULL,
    [TOTAL_DEBT]              VARCHAR (200) NULL,
    [INCOME_EXPENSE_TRANSFER] VARCHAR (200) NULL,
    [REALIZED_EXCH_GL]        VARCHAR (200) NULL,
    [UNREALIZED_EXCH_GL]      VARCHAR (200) NULL,
    [EXCH_GAIN_LOSS]          VARCHAR (200) NULL,
    [INCOME_DISTRIBUTIONS]    VARCHAR (200) NULL,
    [EQL_CREATIONS]           VARCHAR (200) NULL,
    [EQL_LIQUIDATIONS]        VARCHAR (200) NULL,
    [CURRENT_NET_INCOME]      VARCHAR (200) NULL,
    [UNITS_IN_ISSUE]          VARCHAR (200) NULL,
    [CADIS_SYSTEM_INSERTED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]    DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]  NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [DATE] ASC, [SEC_DESCRIPTION] ASC) WITH (FILLFACTOR = 90)
);

