CREATE TABLE [dbo].[T_NT_CASH_REPORT_STAGE] (
    [FILE_NAME]                          VARCHAR (100)   NULL,
    [FILE_DATE]                          DATE            NULL,
    [D_GL_POST]                          DATE            NOT NULL,
    [CONSOLIDATION]                      VARCHAR (6)     NULL,
    [ACCOUNT_NUMBER]                     VARCHAR (6)     NOT NULL,
    [SEDOL]                              VARCHAR (20)    NOT NULL,
    [ISIN]                               VARCHAR (20)    NULL,
    [FROM_DATE]                          DATE            NULL,
    [THROUGH_DATE]                       DATE            NULL,
    [CURRENCY_CODE]                      VARCHAR (3)     NULL,
    [I_GL_CHR_AC]                        INT             NULL,
    [I_GL_AC_SEQ]                        INT             NULL,
    [N_GL_AC30]                          INT             NULL,
    [C_REC_TYPE]                         BIGINT          NULL,
    [I_TRAN]                             VARCHAR (20)    NOT NULL,
    [D_TRAN_EFF]                         DATE            NULL,
    [NARRATIVE_SHORT]                    VARCHAR (200)   NULL,
    [NET_AMOUNT_LOCAL]                   DECIMAL (18, 2) NULL,
    [NET_AMOUNT_BASE]                    DECIMAL (18, 2) NULL,
    [C_SORT_CDE]                         VARCHAR (5)     NULL,
    [ISIN_ASSET_IDENTIFIER]              VARCHAR (1)     NULL,
    [T_AST_DESC_MED]                     VARCHAR (10)    NULL,
    [ROW_INDEX]                          INT             NULL,
    [C_VALN_TYPE_O]                      VARCHAR (2)     NULL,
    [ERROR_CODE]                         INT             NULL,
    [SHARE/PAR_VALUE]                    INT             NULL,
    [CONSOLIDATION_AUDIT_INDICATOR_FLAG] VARCHAR (1)     NULL,
    [INCOME_RATE]                        INT             NULL,
    [EX_DATE]                            DATE            NULL,
    [I_TRAN_PROC_3]                      VARCHAR (20)    NULL,
    [C_EXTL_SYS_TRN_DSC_3]               VARCHAR (20)    NULL,
    [CADIS_SYSTEM_INSERTED]              DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]               DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]             NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([D_GL_POST] ASC, [ACCOUNT_NUMBER] ASC, [SEDOL] ASC, [I_TRAN] ASC) WITH (FILLFACTOR = 90)
);

