CREATE TABLE [dbo].[T_NT_COST_SHEET] (
    [DATE]                   DATETIME        NOT NULL,
    [ACCOUNT_NUMBER]         VARCHAR (50)    NOT NULL,
    [NET_INCOME]             DECIMAL (18, 2) NULL,
    [UNITS_IN_ISSUE]         DECIMAL (18, 4) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([DATE] ASC, [ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 90)
);

