CREATE TABLE [dbo].[T_NT_CURRENCY_CODES] (
    [CCY_CODE]               VARCHAR (20)  NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_NT_CURR__CADIS__05FC09AB] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_NT_CURR__CADIS__06F02DE4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_NT_CURR__CADIS__07E4521D] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_NT_CURR__CADIS__08D87656] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_NT_CUR__DB9FBD46613A02BD] PRIMARY KEY CLUSTERED ([CCY_CODE] ASC) WITH (FILLFACTOR = 90)
);

