CREATE TABLE [dbo].[T_NT_CASH_PROJECT] (
    [FILE_DATE]              DATETIME        NULL,
    [CONSOLIDATION]          VARCHAR (8)     NULL,
    [ACCOUNT_NUM]            VARCHAR (8)     NULL,
    [FUND_SHORT_NAME]        VARCHAR (15)    NOT NULL,
    [FROM_DATE]              DATETIME        NULL,
    [THROUGH_DATE]           DATETIME        NULL,
    [CCY]                    VARCHAR (3)     NOT NULL,
    [C_REC_TYPE]             INT             NOT NULL,
    [T_NARR_LONG]            VARCHAR (230)   NULL,
    [C_VALN_TYPE_O]          VARCHAR (2)     NULL,
    [ACCOUNT_NAME]           VARCHAR (30)    NULL,
    [D_CURR_DATE]            DATETIME        NOT NULL,
    [I_ACTING_REF]           VARCHAR (20)    NULL,
    [ERROR_CODE]             VARCHAR (9)     NULL,
    [CUSIP]                  VARCHAR (16)    NULL,
    [TRANSACTION_CATEGORY]   VARCHAR (8)     NULL,
    [A_TRAN_AMT]             DECIMAL (20, 2) NULL,
    [I_POST_SEQ]             INT             NULL,
    [TRANSACTION_STATUS]     VARCHAR (3)     NULL,
    [CCY_NAME]               VARCHAR (30)    NOT NULL,
    [I_TRAN]                 INT             NOT NULL,
    [S_ROW_UPD]              VARCHAR (26)    NULL,
    [I_SEQ_NBR]              INT             NULL,
    [C_BSE_CCY]              VARCHAR (3)     NULL,
    [A_TRAN_RP_BASE]         DECIMAL (20, 2) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [CCY] ASC, [C_REC_TYPE] ASC, [D_CURR_DATE] ASC, [CCY_NAME] ASC, [I_TRAN] ASC) WITH (FILLFACTOR = 80)
);

