CREATE TABLE [dbo].[T_NT_POS_ACCOUNT_BALANCE] (
    [ACCOUNT_NUMBER]         VARCHAR (20)    NOT NULL,
    [ACCOUNT_NAME]           VARCHAR (100)   NULL,
    [VALUATION_DATE]         DATETIME        NOT NULL,
    [ASSET_SUB_CATEGORY]     VARCHAR (100)   NOT NULL,
    [CURRENCY_NAME_ASSET]    VARCHAR (100)   NULL,
    [LOCAL_CURRENCY_CODE]    VARCHAR (3)     NOT NULL,
    [FUND_SHORT_NAME]        VARCHAR (15)    NULL,
    [MARKET_VALUE_BASE]      DECIMAL (18, 3) NULL,
    [MARKET_VALUE_LOCAL]     DECIMAL (18, 3) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        CONSTRAINT [DF__T_NT_POS___CADIS__7F08EC0C] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        CONSTRAINT [DF__T_NT_POS___CADIS__7FFD1045] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   CONSTRAINT [DF__T_NT_POS___CADIS__00F1347E] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT             CONSTRAINT [DF__T_NT_POS___CADIS__01E558B7] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_NT_POS__B4087C3FCA8F7350] PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [VALUATION_DATE] ASC, [ASSET_SUB_CATEGORY] ASC, [LOCAL_CURRENCY_CODE] ASC) WITH (FILLFACTOR = 90)
);

