CREATE TABLE [dbo].[T_OMNIS_GROSS_FUND_FLOW_IN] (
    [ROW_NUMBER]                  INT              IDENTITY (1, 1) NOT NULL,
    [SHARE_CLASS__FUND_NAME]      VARCHAR (100)    NULL,
    [FUND]                        VARCHAR (3)      NULL,
    [ESTIMATED_MOVEMENT]          VARCHAR (100)    NULL,
    [PREVIOUS_DAYS_PRICE]         VARCHAR (100)    NULL,
    [ESTIMATED_COST]              DECIMAL (28, 12) NULL,
    [FUND_VALUE]                  VARCHAR (100)    NULL,
    [PERCENTAGE_OF_FUND_MOVEMENT] VARCHAR (100)    NULL,
    [NO_OF_SHARES_IN_ISSUE]       DECIMAL (28, 12) NULL,
    [VP_DATE]                     DATETIME         NULL,
    [RUN_DATE]                    DATETIME         NULL,
    [CADIS_SYSTEM_INSERTED]       DATETIME         CONSTRAINT [DF__T_OMNIS_G__CADIS__653E2D11] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]        DATETIME         CONSTRAINT [DF__T_OMNIS_G__CADIS__6632514A] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]      NVARCHAR (50)    CONSTRAINT [DF__T_OMNIS_G__CADIS__67267583] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]       INT              CONSTRAINT [DF__T_OMNIS_G__CADIS__681A99BC] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_OMNIS___F6D12DF3EA0D315B] PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC) WITH (FILLFACTOR = 90)
);

