CREATE TABLE [dbo].[T_OMT_GROSS_FUND_FLOW_IN] (
    [ROW_NUMBER]             INT              IDENTITY (1, 1) NOT NULL,
    [TRADE_DATE]             DATETIME         NULL,
    [FUND_NAME]              VARCHAR (100)    NULL,
    [CCY]                    VARCHAR (100)    NULL,
    [TYPE]                   VARCHAR (100)    NULL,
    [NET_CASH_MVT]           DECIMAL (28, 10) NULL,
    [SETTLE_DATE]            DATETIME         NULL,
    [STATUS]                 VARCHAR (100)    NULL,
    [COLUMN1]                VARCHAR (100)    NULL,
    [COLUMN2]                VARCHAR (100)    NULL,
    [COLUMN3]                VARCHAR (100)    NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME         CONSTRAINT [DF__T_OMT_GRO__CADIS__62EBD04B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME         CONSTRAINT [DF__T_OMT_GRO__CADIS__63DFF484] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)    CONSTRAINT [DF__T_OMT_GRO__CADIS__64D418BD] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT              CONSTRAINT [DF__T_OMT_GRO__CADIS__65C83CF6] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_OMT_GR__F6D12DF34CF66733] PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC) WITH (FILLFACTOR = 90)
);

