CREATE TABLE [dbo].[T_OVERRIDE_POS_ACCOUNT_BALANCE_RESET] (
    [FUND_SHORT_NAME]           VARCHAR (15)  NOT NULL,
    [POSITION_DATE]             DATETIME      NOT NULL,
    [ASSET_SUB_CATEGORY]        VARCHAR (100) NOT NULL,
    [CCY]                       VARCHAR (3)   NOT NULL,
    [LOCAL_VALUE]               BIT           NULL,
    [BASE_VALUE]                BIT           NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_OVERRID__CADIS__170207DC] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_OVERRID__CADIS__17F62C15] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_OVERRID__CADIS__18EA504E] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_OVERRID__CADIS__19DE7487] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_OVERRID__CADIS__1AD298C0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    CONSTRAINT [PK__T_OVERRI__5B124C7FDFB39F3F] PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC, [ASSET_SUB_CATEGORY] ASC, [CCY] ASC) WITH (FILLFACTOR = 90)
);

