CREATE TABLE [dbo].[T_OVERRIDE_NET_FUND_FLOW_EXPIRY] (
    [FILE_NAME]                                     VARCHAR (50)    NULL,
    [FILE_TYPE]                                     VARCHAR (20)    NULL,
    [FILE_DATE]                                     DATETIME        NULL,
    [NUMBER_OF_RECORDS]                             VARCHAR (20)    NULL,
    [CONSOLIDATION]                                 DATETIME        NULL,
    [ACCOUNT_NUMBER]                                VARCHAR (50)    NOT NULL,
    [FUND_SHORT_NAME]                               DATETIME        NULL,
    [FROM_DATE]                                     DATETIME        NULL,
    [THROUGH_DATE]                                  DATETIME        NULL,
    [TASTDESCMED]                                   DATETIME        NULL,
    [TNARRLONG]                                     VARCHAR (255)   NOT NULL,
    [ABASBSE]                                       DATETIME        NULL,
    [NET_AMOUNT__BASE]                              DECIMAL (20, 6) NOT NULL,
    [AMKTVAL]                                       DATETIME        NULL,
    [ARLSDGAIN]                                     DATETIME        NULL,
    [AEXCHGNLS]                                     DATETIME        NULL,
    [RECOGNITION_DATE]                              DATETIME        NOT NULL,
    [NTRANCATG]                                     VARCHAR (100)   NOT NULL,
    [ASSET_IDENTIFIER]                              DATETIME        NULL,
    [CTEMPLTYPE]                                    DATETIME        NULL,
    [CVALNTYPEO]                                    DATETIME        NULL,
    [TSHAREPAR]                                     DATETIME        NULL,
    [REVERSAL_INDICATOR]                            DATETIME        NULL,
    [ALOTCOSTGNLS]                                  DATETIME        NULL,
    [DTRANPROC]                                     DATETIME        NULL,
    [CSORTCDE3]                                     DATETIME        NULL,
    [ERROR_CODE]                                    DATETIME        NULL,
    [CONSOLIDATION_AUDIT_INDICATOR_FLAG]            DATETIME        NULL,
    [IEXTLREF]                                      VARCHAR (50)    NOT NULL,
    [CASSETLIAB]                                    DATETIME        NULL,
    [ACCRUED_INTEREST]                              DATETIME        NULL,
    [DSET]                                          DATETIME        NULL,
    [ACCRUAL_CHANGE_FROM_SECURITY_MOVEMENTS_OFFSET] DATETIME        NULL,
    [CADIS_SYSTEM_INSERTED]                         DATETIME        CONSTRAINT [DF__T_OVERRID__CADIS__045947BC] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                          DATETIME        CONSTRAINT [DF__T_OVERRID__CADIS__054D6BF5] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                        NVARCHAR (50)   CONSTRAINT [DF__T_OVERRID__CADIS__0641902E] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                         INT             CONSTRAINT [DF__T_OVERRID__CADIS__0735B467] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                     DATETIME        CONSTRAINT [DF__T_OVERRID__CADIS__0829D8A0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                        ROWVERSION      NOT NULL,
    CONSTRAINT [PK__T_OVERRI__46233BEEE6733D2B] PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [TNARRLONG] ASC, [NET_AMOUNT__BASE] ASC, [RECOGNITION_DATE] ASC, [NTRANCATG] ASC, [IEXTLREF] ASC) WITH (FILLFACTOR = 90)
);

