CREATE TABLE [dbo].[T_OVERRIDE_SEC_FIXED_EXPIRY] (
    [EDM_SEC_ID]                             INT           NOT NULL,
    [ISSUE_DATE]                             DATETIME      NULL,
    [MATURITY_DATE]                          DATETIME      NULL,
    [COUPON_RATE]                            DATETIME      NULL,
    [COUPON_FREQUENCY]                       DATETIME      NULL,
    [COUPON_TYPE]                            DATETIME      NULL,
    [CONVERTIBLE_INDICATOR]                  DATETIME      NULL,
    [AMOUNT_ISSUED]                          DATETIME      NULL,
    [AMOUNT_OUTSTANDING]                     DATETIME      NULL,
    [COUPON_CAP]                             DATETIME      NULL,
    [COUPON_ISO_CCY]                         DATETIME      NULL,
    [COUPON_FLOOR]                           DATETIME      NULL,
    [ISSUE_PRICE]                            DATETIME      NULL,
    [DAY_COUNT]                              DATETIME      NULL,
    [FIRST_COUPON_DATE]                      DATETIME      NULL,
    [FIRST_SETTLE_DATE]                      DATETIME      NULL,
    [PREVIOUS_COUPON_DATE]                   DATETIME      NULL,
    [NEXT_COUPON_DATE]                       DATETIME      NULL,
    [NEXT_CALL_DATE]                         DATETIME      NULL,
    [NEXT_CALL_PRICE]                        DATETIME      NULL,
    [LAST_RESET_DATE]                        DATETIME      NULL,
    [NEXT_RESET_DATE]                        DATETIME      NULL,
    [SECOND_COUPON_DATE]                     DATETIME      NULL,
    [FIXED_INDICATOR]                        DATETIME      NULL,
    [FIX_TO_FLOAT_INDICATOR]                 DATETIME      NULL,
    [FLOATER_INDICATOR]                      DATETIME      NULL,
    [FLOAT_TO_FIX_INDICATOR]                 DATETIME      NULL,
    [INDEX_LINKED_INDICATOR]                 DATETIME      NULL,
    [INFLATION_LINKED_INDICATOR]             DATETIME      NULL,
    [PERPETUAL_INDICATOR]                    DATETIME      NULL,
    [ZERO_COUPON_INDICATOR]                  DATETIME      NULL,
    [ACCRUED_INTEREST_PER_100]               DATETIME      NULL,
    [ACCRUED_INTEREST_DATE]                  DATETIME      NULL,
    [COLLATERAL_TYPE]                        DATETIME      NULL,
    [AGGREGATE_AMOUNT_ISSUED_INDICATOR]      DATETIME      NULL,
    [ASSUMED_INDEX_VALUE]                    DATETIME      NULL,
    [BRADY_INDICATOR]                        DATETIME      NULL,
    [CALCULATION_TYPE]                       DATETIME      NULL,
    [CALLABLE_INDICATOR]                     DATETIME      NULL,
    [CALLED_INDICATOR]                       DATETIME      NULL,
    [CALL_DAYS_NOTICE]                       DATETIME      NULL,
    [PUTABLE_INDICATOR]                      DATETIME      NULL,
    [PUT_DAYS_NOTICE]                        DATETIME      NULL,
    [CASH_SETTLED_INDICATOR]                 DATETIME      NULL,
    [CDS_RECOVERY_RATE]                      DATETIME      NULL,
    [CORPORATE_TO_EQUITY_TICKER]             DATETIME      NULL,
    [FIX_TO_FLOAT_COUPON_TYPE_RESET_DATE]    DATETIME      NULL,
    [DEFAULTED_INDICATOR]                    DATETIME      NULL,
    [EXCHANGEABLE_INDICATOR]                 DATETIME      NULL,
    [FLOATER_COUPON_CONVENTION]              DATETIME      NULL,
    [FLOATER_LOCKOUT_PERIOD]                 DATETIME      NULL,
    [FLOATER_PAY_DAY]                        DATETIME      NULL,
    [JUNIOR_INDICATOR]                       DATETIME      NULL,
    [SENIOR_INDICATOR]                       DATETIME      NULL,
    [REGULATION_S_INDICATOR]                 DATETIME      NULL,
    [SUBORDINATED_INDICATOR]                 DATETIME      NULL,
    [UNIT_TRADED_INDICATOR]                  DATETIME      NULL,
    [LOAN_PARTICIPATION_NOTE_INDICATOR]      DATETIME      NULL,
    [ORIGINAL_ISSUE_DISCOUNT_INDICATOR]      DATETIME      NULL,
    [GILT_DIGITS]                            DATETIME      NULL,
    [GILTS_EX_DIVIDEND_DATE]                 DATETIME      NULL,
    [INDEX_RATIO_CPI]                        DATETIME      NULL,
    [MINIMUM_INCREMENT]                      DATETIME      NULL,
    [MINIMUM_PIECE]                          DATETIME      NULL,
    [MOST_RECENT_REPORTED_FACTOR]            DATETIME      NULL,
    [MOST_RECENT_ACCRUAL_RATE]               DATETIME      NULL,
    [MOST_RECENT_ACCRUAL_RATE_START_DATE]    DATETIME      NULL,
    [MORTGAGE_DEAL_CALL_DATE]                DATETIME      NULL,
    [MORTGAGE_END_PRINCIPAL_WINDOW_MATURITY] DATETIME      NULL,
    [MORTGAGE_FACTOR_DATE]                   DATETIME      NULL,
    [MORTGAGE_CURRENT_PAYMENT_RATE]          DATETIME      NULL,
    [MORTGAGE_FINAL_PAY_DATE]                DATETIME      NULL,
    [MORTGAGE_FIRST_PAY_DATE]                DATETIME      NULL,
    [MORTGAGE_LIFE_FLOOR]                    DATETIME      NULL,
    [MORTGAGE_PAYMENT_DELAY]                 DATETIME      NULL,
    [MORTGAGE_RATE_CHANGE_FREQUENCY]         DATETIME      NULL,
    [MORTGAGE_TRANCHE_TYPE]                  DATETIME      NULL,
    [MATURITY_REFUND_TYPE]                   DATETIME      NULL,
    [NOMINAL_PAYMENT_DAY]                    DATETIME      NULL,
    [PENULTIMATE_COUPON_DATE]                DATETIME      NULL,
    [REDEMPTION_VALUE]                       DATETIME      NULL,
    [UNDERLYING_REFERENCE_INDEX]             DATETIME      NULL,
    [RESET_FREQUENCY]                        DATETIME      NULL,
    [RESET_INDEX]                            DATETIME      NULL,
    [SINK_TYPE]                              DATETIME      NULL,
    [SINKABLE_INDICATOR]                     DATETIME      NULL,
    [STEPUP_STEPDOWN_COUPON]                 DATETIME      NULL,
    [STEPUP_STEPDOWN_COUPON_DATE]            DATETIME      NULL,
    [STRUCTURED_NOTE_INDICATOR]              DATETIME      NULL,
    [LOWER_TIER2_CAPITAL_INDICATOR]          DATETIME      NULL,
    [TIER1_CAPITAL_INDICATOR]                DATETIME      NULL,
    [TIER2_CAPITAL_NON_SPECIFIC_INDICATOR]   DATETIME      NULL,
    [UPPER_TIER2_CAPITAL_INDICATOR]          DATETIME      NULL,
    [EX_DIVIDEND_DAYS]                       DATETIME      NULL,
    [EX_DIVIDEND_DAYS_CALENDAR_CODE]         DATETIME      NULL,
    [SUBORDINATE_TYPE]                       DATETIME      NULL,
    [SENIORITY_LEVEL_2]                      DATETIME      NULL,
    [CADIS_SYSTEM_INSERTED]                  DATETIME      CONSTRAINT [DF__T_OVERRID__CADIS__16900222] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                   DATETIME      CONSTRAINT [DF__T_OVERRID__CADIS__1784265B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                 NVARCHAR (50) CONSTRAINT [DF__T_OVERRID__CADIS__18784A94] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                  INT           CONSTRAINT [DF__T_OVERRID__CADIS__196C6ECD] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                 ROWVERSION    NOT NULL,
    CONSTRAINT [PK__T_OVERRI__B157E8F2F7ADE266] PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC) WITH (FILLFACTOR = 90)
);

