CREATE TABLE [dbo].[T_OVERRIDE_APPROVAL_FXRATE] (
    [FXRATE_ID]                 VARCHAR (6)      NOT NULL,
    [DATE]                      DATETIME         NOT NULL,
    [FROM_ISO_CURRENCY_CODE]    VARCHAR (3)      NULL,
    [TO_ISO_CURRENCY_CODE]      VARCHAR (3)      NULL,
    [SPOT_RATE]                 DECIMAL (24, 16) NULL,
    [1_MONTH_FORWARD_RATE]      DECIMAL (24, 16) NULL,
    [2_MONTH_FORWARD_RATE]      DECIMAL (24, 16) NULL,
    [3_MONTH_FORWARD_RATE]      DECIMAL (24, 16) NULL,
    [6_MONTH_FORWARD_RATE]      DECIMAL (24, 16) NULL,
    [1_YEAR_FORWARD_RATE]       DECIMAL (24, 16) NULL,
    [DATA_QUALITY]              VARCHAR (20)     NULL,
    [OVERRIDE_COMMENT]          VARCHAR (255)    NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME         CONSTRAINT [DF__T_OVERRID__CADIS__4790FBF5] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME         CONSTRAINT [DF__T_OVERRID__CADIS__4885202E] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)    CONSTRAINT [DF__T_OVERRID__CADIS__49794467] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT              CONSTRAINT [DF__T_OVERRID__CADIS__4A6D68A0] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME         CONSTRAINT [DF__T_OVERRID__CADIS__4B618CD9] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_OVERRI__4A5618168AE8CA24] PRIMARY KEY CLUSTERED ([FXRATE_ID] ASC, [DATE] ASC) WITH (FILLFACTOR = 90)
);

