CREATE TABLE [dbo].[T_OVERRIDE_FND_MARKET_VALUE_EXPIRY] (
    [SOURCE]                          VARCHAR (50)   NOT NULL,
    [POSITION_TYPE]                   VARCHAR (50)   NOT NULL,
    [FUND_SHORT_NAME]                 VARCHAR (8000) NOT NULL,
    [POSITION_DATE]                   DATETIME       NOT NULL,
    [TOTAL_MARKET_VALUE_LOCAL]        DATETIME       NULL,
    [TOTAL_MARKET_VALUE_BASE]         DATETIME       NULL,
    [STATUS]                          DATETIME       NULL,
    [TOTAL_ACCRUED_MARKET_VALUE_BASE] DATETIME       NULL,
    [CADIS_SYSTEM_INSERTED]           DATETIME       CONSTRAINT [DF__T_OVERRID__CADIS__00BDC102] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]            DATETIME       CONSTRAINT [DF__T_OVERRID__CADIS__01B1E53B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]          NVARCHAR (50)  CONSTRAINT [DF__T_OVERRID__CADIS__02A60974] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]           INT            CONSTRAINT [DF__T_OVERRID__CADIS__039A2DAD] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED]       DATETIME       CONSTRAINT [DF__T_OVERRID__CADIS__048E51E6] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_TIMESTAMP]          ROWVERSION     NOT NULL,
    CONSTRAINT [PK__T_OVERRI__D5F8680437C74ABF] PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC) WITH (FILLFACTOR = 90)
);

