CREATE TABLE [dbo].[T_OVERRIDE_GROSS_FUND_FLOW_RESET] (
    [FUND_SHORT_NAME]           VARCHAR (15)  NOT NULL,
    [TRANSACTION_DATE]          DATETIME      NOT NULL,
    [CURRENCY]                  VARCHAR (20)  NOT NULL,
    [FUND_FLOW_TYPE]            VARCHAR (20)  NOT NULL,
    [FLOW_TYPE]                 VARCHAR (100) NOT NULL,
    [SOURCE_TYPE]               VARCHAR (20)  DEFAULT ('CONFIRMED') NOT NULL,
    [MARKET_VALUE]              BIT           NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      DEFAULT (getdate()) NULL,
    [SETTLEMENT_DATE]           BIT           NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [CURRENCY] ASC, [FUND_FLOW_TYPE] ASC, [FLOW_TYPE] ASC, [SOURCE_TYPE] ASC)
);

