CREATE TABLE [dbo].[T_PKGD_FILE] (
    [NO]                     INT           NOT NULL,
    [PKGFILE]                VARCHAR (200) NULL,
    [STATUS]                 VARCHAR (20)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([NO] ASC) WITH (FILLFACTOR = 80)
);

