CREATE TABLE [dbo].[T_PREMASTER_POS] (
    [SOURCE]                    VARCHAR (50)    NOT NULL,
    [POSITION_TYPE]             VARCHAR (50)    NOT NULL,
    [EDM_SEC_ID]                INT             NOT NULL,
    [FUND_SHORT_NAME]           VARCHAR (15)    NOT NULL,
    [LONG_SHORT_IND]            VARCHAR (8)     NOT NULL,
    [POSITION_DATE]             DATETIME        NOT NULL,
    [QUANTITY]                  DECIMAL (20, 6) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__475FB8B4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__4853DCED] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   CONSTRAINT [DF__T_PREMAST__CADIS__49480126] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             CONSTRAINT [DF__T_PREMAST__CADIS__4A3C255F] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__4B304998] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_PREMAS__8CEB76694F34EC53] PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [EDM_SEC_ID] ASC, [FUND_SHORT_NAME] ASC, [LONG_SHORT_IND] ASC, [POSITION_DATE] ASC) WITH (FILLFACTOR = 90)
);

