CREATE TABLE [dbo].[T_PREMASTER_FND_MARKET_VALUE] (
    [SOURCE]                          VARCHAR (50)    NOT NULL,
    [POSITION_TYPE]                   VARCHAR (50)    NOT NULL,
    [FUND_SHORT_NAME]                 VARCHAR (8000)  NOT NULL,
    [POSITION_DATE]                   DATETIME        NOT NULL,
    [TOTAL_MARKET_VALUE_LOCAL]        DECIMAL (20, 2) NULL,
    [TOTAL_MARKET_VALUE_BASE]         DECIMAL (20, 2) NULL,
    [STATUS]                          VARCHAR (20)    NULL,
    [TOTAL_ACCRUED_MARKET_VALUE_BASE] DECIMAL (20, 2) NULL,
    [CADIS_SYSTEM_INSERTED]           DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__078E810B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]            DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__0882A544] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]          NVARCHAR (50)   CONSTRAINT [DF__T_PREMAST__CADIS__0976C97D] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]           INT             CONSTRAINT [DF__T_PREMAST__CADIS__0A6AEDB6] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED]       DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__0B5F11EF] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_PREMAS__D5F868042543BFBC] PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC) WITH (FILLFACTOR = 90)
);

