CREATE TABLE [dbo].[T_PROCESS_MONITOR] (
    [SOURCE]                    VARCHAR (30)  NOT NULL,
    [ENTITY]                    VARCHAR (50)  NOT NULL,
    [DESCRIPTION]               VARCHAR (50)  NOT NULL,
    [DIRECTION]                 VARCHAR (3)   NOT NULL,
    [RUN_DATE]                  DATETIME      NOT NULL,
    [SOURCE_DATE]               DATETIME      NULL,
    [ROW_COUNT]                 INT           NULL,
    [EXPECTED_ROW_COUNT]        INT           NULL,
    [STATUS]                    VARCHAR (30)  NULL,
    [TOP_LEVEL_RUNID]           INT           NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF__T_PROCESS__CADIS__6A26A4A8] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF__T_PROCESS__CADIS__6B1AC8E1] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF__T_PROCESS__CADIS__6C0EED1A] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF__T_PROCESS__CADIS__6D031153] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF__T_PROCESS__CADIS__6DF7358C] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_RUNID]        INT           DEFAULT ((0)) NULL,
    [CADIS_SYSTEM_TOPRUNID]     INT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK__T_PROCES__2F7781342C3EB292] PRIMARY KEY CLUSTERED ([SOURCE] ASC, [ENTITY] ASC, [DESCRIPTION] ASC, [DIRECTION] ASC, [RUN_DATE] ASC) WITH (FILLFACTOR = 90)
);

