CREATE TABLE [dbo].[T_PREMASTER_POS_ACCOUNT_BALANCE] (
    [FUND_SHORT_NAME]           VARCHAR (15)    NOT NULL,
    [POSITION_DATE]             DATETIME        NOT NULL,
    [ASSET_SUB_CATEGORY]        VARCHAR (100)   NOT NULL,
    [CCY]                       VARCHAR (3)     NOT NULL,
    [LOCAL_VALUE]               DECIMAL (18, 3) NULL,
    [BASE_VALUE]                DECIMAL (18, 3) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__72C310B8] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__73B734F1] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   CONSTRAINT [DF__T_PREMAST__CADIS__74AB592A] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             CONSTRAINT [DF__T_PREMAST__CADIS__759F7D63] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        CONSTRAINT [DF__T_PREMAST__CADIS__7693A19C] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_PREMAS__5B124C7FC2B287A3] PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC, [ASSET_SUB_CATEGORY] ASC, [CCY] ASC) WITH (FILLFACTOR = 90)
);

