CREATE TABLE [dbo].[T_REQUEST_SEC] (
    [ID_BB_GLOBAL]           VARCHAR (30)  NULL,
    [PRICING_SOURCE]         VARCHAR (30)  NULL,
    [SOURCE_ID]              VARCHAR (30)  NULL,
    [SOURCE]                 VARCHAR (30)  NULL,
    [ID_BB_UNIQUE]           VARCHAR (30)  NOT NULL,
    [SEDOL]                  VARCHAR (7)   NULL,
    [ISIN]                   VARCHAR (12)  NULL,
    [CUSIP]                  VARCHAR (9)   NULL,
    [TICKER]                 VARCHAR (26)  NULL,
    [BPS_YELLOWKEY]          VARCHAR (30)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REQUEST__CADIS__4FC3ED3E] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REQUEST__CADIS__50B81177] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REQUEST__CADIS__51AC35B0] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REQUEST__CADIS__52A059E9] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_REQUES__9FF60D80CF31BDFF] PRIMARY KEY CLUSTERED ([ID_BB_UNIQUE] ASC) WITH (FILLFACTOR = 90)
);

