CREATE TABLE [dbo].[T_REF_SF_OVERRIDE_STATUS] (
    [OVERRIDE_STATUS]        VARCHAR (20)  NOT NULL,
    [ACTIVE]                 BIT           DEFAULT ((0)) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([OVERRIDE_STATUS] ASC)
);

