CREATE TABLE [dbo].[T_REF_DOMAIN_VALUE] (
    [TYPE]                   VARCHAR (150) NOT NULL,
    [NAME]                   VARCHAR (150) NOT NULL,
    [VALUE]                  VARCHAR (150) NULL,
    [ACTIVE]                 VARCHAR (1)   CONSTRAINT [DF__T_REF_DOM__ACTIV__4EA0E7C9] DEFAULT ('Y') NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_DOM__CADIS__4F950C02] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_DOM__CADIS__5089303B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_DOM__CADIS__517D5474] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_DOM__CADIS__527178AD] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_REF_DO__8DAF55004CB89F57] PRIMARY KEY CLUSTERED ([TYPE] ASC, [NAME] ASC) WITH (FILLFACTOR = 90)
);

