CREATE TABLE [dbo].[T_REF_SECURITY_TYPE] (
    [SECURITY_TYPE]          VARCHAR (8)   NOT NULL,
    [BBG_PRODUCT_SUB_TYPE]   VARCHAR (20)  NULL,
    [SECURITY_TYPE_NAME]     VARCHAR (50)  NOT NULL,
    [ASSET_TYPE]             VARCHAR (50)  NULL,
    [ACTIVE]                 VARCHAR (1)   DEFAULT ('Y') NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([SECURITY_TYPE] ASC) WITH (FILLFACTOR = 90)
);

