CREATE TABLE [dbo].[T_REF_EXCEPTION_PRIORITY] (
    [Priority]               NVARCHAR (20) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__240BC149] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__24FFE582] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_EXC__CADIS__25F409BB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_EXC__CADIS__26E82DF4] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_REF_EX__534DF97A52A6FCD8] PRIMARY KEY CLUSTERED ([Priority] ASC) WITH (FILLFACTOR = 90)
);

