CREATE TABLE [dbo].[T_REF_ASSET_TYPE] (
    [ASSET_TYPE]             VARCHAR (50)  NOT NULL,
    [ACTIVE]                 VARCHAR (1)   CONSTRAINT [DF__T_REF_ASS__ACTIV__1D939C1A] DEFAULT ('Y') NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_ASS__CADIS__1E87C053] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_ASS__CADIS__1F7BE48C] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_ASS__CADIS__207008C5] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_ASS__CADIS__21642CFE] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    CONSTRAINT [PK__T_REF_AS__EA554DD11BAB53A8] PRIMARY KEY CLUSTERED ([ASSET_TYPE] ASC) WITH (FILLFACTOR = 90)
);

