CREATE TABLE [dbo].[T_REF_FND_MODEL_SUB_TYPE] (
    [MODEL_SUB_TYPE_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [MODEL_SUB_TYPE]            VARCHAR (12)  NOT NULL,
    [STATUS]                    VARCHAR (8)   NOT NULL,
    [DESCRIPTION]               VARCHAR (255) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           DEFAULT ((1)) NOT NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([MODEL_SUB_TYPE] ASC) WITH (FILLFACTOR = 90)
);

