CREATE TABLE [dbo].[T_RESOLUTION_LOG] (
    [COMPONENT_NAME]         VARCHAR (50)  NOT NULL,
    [COMPONENT_TYPE]         VARCHAR (50)  NOT NULL,
    [LOG_DATE]               DATETIME      NOT NULL,
    [COMMENTS]               VARCHAR (500) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_RESOLUT__CADIS__679450C0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_RESOLUT__CADIS__688874F9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_RESOLUT__CADIS__697C9932] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_RESOLUT__CADIS__6A70BD6B] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    CONSTRAINT [PK__T_RESOLU__E698236E841393F1] PRIMARY KEY CLUSTERED ([COMPONENT_NAME] ASC, [COMPONENT_TYPE] ASC, [LOG_DATE] ASC, [CADIS_SYSTEM_TIMESTAMP] ASC) WITH (FILLFACTOR = 90)
);

