CREATE TABLE [dbo].[T_REF_GENERAL_MAP] (
    [FIELD_NAME]             VARCHAR (50)  NOT NULL,
    [SOURCE]                 VARCHAR (50)  NOT NULL,
    [SOURCE_CODE]            VARCHAR (50)  NOT NULL,
    [TARGET]                 VARCHAR (50)  NOT NULL,
    [TARGET_CODE]            VARCHAR (50)  NULL,
    [ACTIVE]                 VARCHAR (1)   CONSTRAINT [DF__T_REF_GEN__ACTIV__39CE5167] DEFAULT ('Y') NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_GEN__CADIS__3AC275A0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_GEN__CADIS__3BB699D9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_GEN__CADIS__3CAABE12] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_GEN__CADIS__3D9EE24B] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    CONSTRAINT [PK__T_REF_GE__859368973F872ABD] PRIMARY KEY CLUSTERED ([FIELD_NAME] ASC, [SOURCE] ASC, [SOURCE_CODE] ASC, [TARGET] ASC) WITH (FILLFACTOR = 90)
);

