CREATE TABLE [dbo].[T_REF_ILLUSTRATION_SOURCE] (
    [TEMPLATE]               VARCHAR (50)  NOT NULL,
    [SOURCE]                 VARCHAR (50)  NOT NULL,
    [SOURCE_COLUMN]          VARCHAR (100) NOT NULL,
    [ILLUSTRATED_NAME]       VARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL,
    PRIMARY KEY CLUSTERED ([TEMPLATE] ASC, [SOURCE] ASC, [SOURCE_COLUMN] ASC)
);

