CREATE TABLE [dbo].[T_REF_FND_ASSET_CLASS] (
    [ASSET_CLASS_ID]            INT           IDENTITY (1, 1) NOT NULL,
    [ASSET_TYPE]                VARCHAR (12)  NULL,
    [MORNINGSTAR_ASSET_CLASS]   VARCHAR (50)  NULL,
    [SQUARE_MILE_ASSET_CLASS]   VARCHAR (50)  NULL,
    [IMA_SECTOR]                VARCHAR (255) NULL,
    [CHARACTERISTICS]           VARCHAR (255) NULL,
    [STATUS]                    VARCHAR (8)   NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           DEFAULT ((1)) NOT NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      DEFAULT (getdate()) NULL
);

