CREATE TABLE [dbo].[T_REF_SOURCE_SLA_SUBSCRIBER] (
    [SOURCE_SLA_SUBSCRIBER_ID] INT           IDENTITY (1, 1) NOT NULL,
    [DATA_CHANNEL_ID]          INT           NULL,
    [SUBSCRIBER_ID]            INT           NULL,
    [ACTIVE]                   BIT           NULL,
    [CADIS_SYSTEM_INSERTED]    DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]   NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_SLA_SUBSCRIBER_ID] ASC) WITH (FILLFACTOR = 80)
);

