CREATE TABLE [dbo].[T_REF_SALES_FORCE_POST_CODE_OWNER] (
    [POST_CODE]              VARCHAR (20)  NOT NULL,
    [EmployeeBK]             VARCHAR (15)  NULL,
    [EmployeeIdBK]           VARCHAR (18)  NULL,
    [FullEmployeeBK]         VARCHAR (18)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([POST_CODE] ASC) WITH (FILLFACTOR = 80)
);

