CREATE TABLE [dbo].[T_REF_BBG_RISK_KPI_NAME] (
    [KPIID]   INT           NOT NULL,
    [KPINAME] VARCHAR (250) NULL,
    CONSTRAINT [PK_dbo.T_REF_BBG_RISK_KPI_NAME] PRIMARY KEY CLUSTERED ([KPIID] ASC) WITH (FILLFACTOR = 80)
);

