CREATE TABLE [dbo].[T_REF_FND_MODEL] (
    [MODEL_TYPE_ID]             INT           IDENTITY (1, 1) NOT NULL,
    [MODEL_TYPE]                VARCHAR (12)  NOT NULL,
    [STATUS]                    VARCHAR (8)   NOT NULL,
    [DESCRIPTION]               VARCHAR (255) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           NOT NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MODEL_TYPE] ASC) WITH (FILLFACTOR = 90)
);

