CREATE TABLE [dbo].[T_REF_BPS_FIELDS] (
    [FIELD_ID]                         VARCHAR (5)   NOT NULL,
    [FIELD_MNEMONIC]                   VARCHAR (32)  NULL,
    [DESCRIPTION]                      VARCHAR (50)  NULL,
    [DATA_LICENSE_CATEGORY]            VARCHAR (39)  NULL,
    [CATEGORY]                         VARCHAR (42)  NULL,
    [DEFINITION]                       VARCHAR (MAX) NULL,
    [COMDTY]                           VARCHAR (6)   NULL,
    [EQUITY]                           VARCHAR (6)   NULL,
    [MUNI]                             VARCHAR (4)   NULL,
    [PFD]                              VARCHAR (3)   NULL,
    [MMKT]                             VARCHAR (5)   NULL,
    [GOVT]                             VARCHAR (4)   NULL,
    [CORP]                             VARCHAR (4)   NULL,
    [INDEX]                            VARCHAR (5)   NULL,
    [CURNCY]                           VARCHAR (6)   NULL,
    [MTGE]                             VARCHAR (4)   NULL,
    [STANDARD_WIDTH]                   INT           NULL,
    [STANDARD_DECIMAL_PLACES]          INT           NULL,
    [FIELD_TYPE]                       VARCHAR (14)  NULL,
    [BACK_OFFICE]                      VARCHAR (11)  NULL,
    [EXTENDED_BACK_OFFICE]             VARCHAR (20)  NULL,
    [PRODUCTION_DATE]                  DATETIME      NULL,
    [CURRENT_MAXIMUM_WIDTH]            INT           NULL,
    [BVAL]                             VARCHAR (4)   NULL,
    [BVAL_BLOCKED]                     VARCHAR (12)  NULL,
    [GETFUNDAMENTALS]                  VARCHAR (15)  NULL,
    [GETHISTORY]                       VARCHAR (10)  NULL,
    [GETCOMPANY]                       VARCHAR (10)  NULL,
    [OLD_MNEMONIC]                     VARCHAR (32)  NULL,
    [DATA_LICENSE_CATEGORY_2]          VARCHAR (39)  NULL,
    [PSBOOPT]                          VARCHAR (1)   NULL,
    [DS_BVAL_METERED]                  VARCHAR (15)  NULL,
    [DLBOOPTFUNDAMENTALS]              VARCHAR (1)   NULL,
    [DLBOOPTBDVD]                      VARCHAR (1)   NULL,
    [DLBOOPTBEST]                      VARCHAR (1)   NULL,
    [DLBOOPTCREDITRISK]                VARCHAR (1)   NULL,
    [DLBOOPTCAPSTRUCT]                 VARCHAR (1)   NULL,
    [DLBOOPTCREDITRISKGETCOMPANY]      VARCHAR (1)   NULL,
    [DLBOOPTCAPSTRUCTGETCOMPANY]       VARCHAR (1)   NULL,
    [SAPIOMS]                          VARCHAR (1)   NULL,
    [DLBOOPTREGCOMPLIANCE]             VARCHAR (1)   NULL,
    [DLBOOPTISSUERRATINGS]             VARCHAR (1)   NULL,
    [XSDTYPE]                          VARCHAR (11)  NULL,
    [XSDMININCLUSIVE]                  INT           NULL,
    [XSDMAXINCLUSIVE]                  INT           NULL,
    [XSDMINEXCLUSIVE]                  VARCHAR (3)   NULL,
    [XSDMAXEXCLUSIVE]                  VARCHAR (3)   NULL,
    [XSDFRACTIONDIGITS]                INT           NULL,
    [XSDMINLENGTH]                     INT           NULL,
    [XSDMAXLENGTH]                     INT           NULL,
    [XSDLENGTH]                        VARCHAR (3)   NULL,
    [XSDPATTERN]                       VARCHAR (3)   NULL,
    [RDFLANGRANGE]                     VARCHAR (8)   NULL,
    [NAMEDPROPERTYIRI]                 VARCHAR (64)  NULL,
    [SUPERPROPERTYIRI]                 VARCHAR (3)   NULL,
    [ISABSTRACT]                       VARCHAR (3)   NULL,
    [CLEANNAME]                        VARCHAR (32)  NULL,
    [HELD_SECURITY]                    BIT           NULL,
    [HELD_SECURITY_ORDER]              VARCHAR (20)  NULL,
    [HELD_SECURITY_FIXED_INCOME]       BIT           NULL,
    [HELD_SECURITY_FIXED_INCOME_ORDER] INT           NULL,
    [HELD_SECURITY_EQUITY]             BIT           NULL,
    [HELD_SECURITY_EQUITY_ORDER]       INT           NULL,
    [HELD_SECURITY_PREFERRED]          BIT           NULL,
    [HELD_SECURITY_PREFERRED_ORDER]    INT           NULL,
    [CADIS_SYSTEM_INSERTED]            DATETIME      CONSTRAINT [DF__T_REF_BPS__CADIS__6E48745E] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]             DATETIME      CONSTRAINT [DF__T_REF_BPS__CADIS__6F3C9897] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]           NVARCHAR (50) CONSTRAINT [DF__T_REF_BPS__CADIS__7030BCD0] DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PK__T_REF_BP__E86DCC3F0AEA3133] PRIMARY KEY CLUSTERED ([FIELD_ID] ASC) WITH (FILLFACTOR = 90)
);

