CREATE TABLE [dbo].[T_REF_EXCEPTION_TEAM] (
    [Team]                   NVARCHAR (30) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__2F7D73F5] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__3071982E] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_EXC__CADIS__3165BC67] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_EXC__CADIS__3259E0A0] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_REF_EX__8F78AFA8BABAE7A9] PRIMARY KEY CLUSTERED ([Team] ASC) WITH (FILLFACTOR = 90)
);

