CREATE TABLE [dbo].[T_REF_ELEMENT_EDITABLE_FIELDS] (
    [NAME]                   VARCHAR (100) NOT NULL,
    [FILTER_TYPE]            VARCHAR (50)  NOT NULL,
    [FILTER_VALUE]           VARCHAR (100) NOT NULL,
    [FIELD_NAME]             VARCHAR (100) NOT NULL,
    [EDITABLE]               BIT           CONSTRAINT [DF__T_REF_ELE__EDITA__6A6CF682] DEFAULT ((1)) NOT NULL,
    [MANDATORY]              BIT           CONSTRAINT [DF__T_REF_ELE__MANDA__6B611ABB] DEFAULT ((0)) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_ELE__CADIS__6C553EF4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_ELE__CADIS__6D49632D] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_ELE__CADIS__6E3D8766] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_ELE__CADIS__6F31AB9F] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    CONSTRAINT [PK__T_REF_EL__8FD5E168E435F588] PRIMARY KEY CLUSTERED ([NAME] ASC, [FILTER_TYPE] ASC, [FILTER_VALUE] ASC, [FIELD_NAME] ASC) WITH (FILLFACTOR = 90)
);

