CREATE TABLE [dbo].[T_REF_EXCEPTION_OWNER] (
    [OWNER_ID]               INT           IDENTITY (1, 1) NOT NULL,
    [OWNER]                  VARCHAR (50)  NOT NULL,
    [NAME]                   VARCHAR (200) NOT NULL,
    [EMAIL]                  VARCHAR (200) NULL,
    [ACTIVE]                 VARCHAR (1)   CONSTRAINT [DF__T_REF_EXC__ACTIV__5D16C24D] DEFAULT ('Y') NOT NULL,
    [VISIBLE]                VARCHAR (1)   CONSTRAINT [DF__T_REF_EXC__VISIB__5E0AE686] DEFAULT ('Y') NOT NULL,
    [REF_TYPE]               VARCHAR (20)  CONSTRAINT [DF__T_REF_EXC__REF_T__5EFF0ABF] DEFAULT ('OWNER') NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__5FF32EF8] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__60E75331] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_EXC__CADIS__61DB776A] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_EXC__CADIS__62CF9BA3] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    CONSTRAINT [PK__T_REF_EX__7C4E08F3C1D136FB] PRIMARY KEY CLUSTERED ([OWNER_ID] ASC) WITH (FILLFACTOR = 90)
);

