CREATE TABLE [dbo].[T_REF_SOURCE_SLA] (
    [SOURCE]                    VARCHAR (30)  NOT NULL,
    [ENTITY]                    VARCHAR (50)  NOT NULL,
    [DESCRIPTION]               VARCHAR (150) NOT NULL,
    [DIRECTION]                 VARCHAR (3)   NOT NULL,
    [DATA_CHANNEL_ID]           INT           NOT NULL,
    [MARKIT_SOLUTION]           VARCHAR (150) NULL,
    [MORNING_CHECK]             VARCHAR (50)  NULL,
    [DELIVERY_SCHEDULE_ID]      INT           NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      DEFAULT (getdate()) NULL,
    PRIMARY KEY CLUSTERED ([DATA_CHANNEL_ID] ASC) WITH (FILLFACTOR = 80)
);

