CREATE TABLE [dbo].[T_REF_LOOKUP] (
    [ENTITY]                 VARCHAR (50)  NOT NULL,
    [SUB_ENTITY]             VARCHAR (50)  NOT NULL,
    [FIELD]                  VARCHAR (100) NOT NULL,
    [FIELD_VALUE]            VARCHAR (100) NOT NULL,
    [LOOKUP_VALUE]           VARCHAR (100) NULL,
    [CHAR_VALUE]             VARCHAR (50)  NULL,
    [INT_VALUE]              INT           NULL,
    [SORT]                   INT           NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([ENTITY] ASC, [SUB_ENTITY] ASC, [FIELD] ASC, [FIELD_VALUE] ASC) WITH (FILLFACTOR = 90)
);

