CREATE TABLE [dbo].[T_REF_SUBSCRIBER] (
    [SUBSCRIBER_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]            VARCHAR (50)  NULL,
    [EMAIL_ADDRESS]          VARCHAR (100) NULL,
    [NOTIFY_BY_EMAIL]        BIT           NULL,
    [SLACK_ADDRESS]          VARCHAR (50)  NULL,
    [NOTIFY_BY_SLACK]        BIT           NULL,
    [ACTIVE]                 BIT           NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    PRIMARY KEY CLUSTERED ([SUBSCRIBER_ID] ASC) WITH (FILLFACTOR = 80)
);

