CREATE TABLE [dbo].[T_REF_EXCEPTION_STATUS] (
    [Status]                 NVARCHAR (20) NOT NULL,
    [Level]                  INT           NULL,
    [Closed]                 BIT           NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__29C49A9F] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_REF_EXC__CADIS__2AB8BED8] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_REF_EXC__CADIS__2BACE311] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           CONSTRAINT [DF__T_REF_EXC__CADIS__2CA1074A] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_REF_EX__3A15923E135584DE] PRIMARY KEY CLUSTERED ([Status] ASC) WITH (FILLFACTOR = 90)
);

