CREATE TABLE [dbo].[T_REF_SEARCH_LIST] (
    [SEARCH_ID]              INT           IDENTITY (1, 1) NOT NULL,
    [LIST_TYPE]              VARCHAR (100) NULL,
    [SEARCH_VALUE]           VARCHAR (100) NULL,
    [LIST_ORDER]             INT           NULL,
    [ACTIVE]                 VARCHAR (20)  DEFAULT ((1)) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL,
    PRIMARY KEY CLUSTERED ([SEARCH_ID] ASC) WITH (FILLFACTOR = 90)
);

