CREATE TABLE [dbo].[T_REF_CURRENCY] (
    [ISO_CCY_CD]             VARCHAR (3)    NOT NULL,
    [CCY_NAME]               VARCHAR (255)  NULL,
    [MAJOR_CCY_CD]           VARCHAR (3)    NULL,
    [MAJOR_MULTIPLIER]       DECIMAL (3, 2) DEFAULT ((1.00)) NOT NULL,
    [MINOR_CCY_CD]           VARCHAR (3)    NULL,
    [MINOR_MULTIPLIER]       DECIMAL (8, 2) NULL,
    [ISO_CTY_CD]             VARCHAR (2)    NULL,
    [ACTIVE]                 VARCHAR (1)    DEFAULT ('Y') NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME       DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)  DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT            DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION     NOT NULL,
    PRIMARY KEY CLUSTERED ([ISO_CCY_CD] ASC) WITH (FILLFACTOR = 90)
);

