CREATE TABLE [dbo].[T_RuleAuditTrail_Rule_Revision_Attributes_Attribute_IN] (
    [CADIS_BATCH_ID]                                                 INT            NOT NULL,
    [CADIS_MSG_ID]                                                   INT            CONSTRAINT [DF__T_RuleAud__CADIS__1E001273] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                                                INT            NOT NULL,
    [CADIS_ROW_ID]                                                   INT            NOT NULL,
    [Attribute_CADIS_ROW_ID]                                         INT            NULL,
    [Attribute_AttrCodeAfter]                                        NVARCHAR (100) NULL,
    [Attribute_AttrCodeBefore]                                       NVARCHAR (100) NULL,
    [Attribute_AttrDescAfter]                                        NVARCHAR (100) NULL,
    [Attribute_AttrDescBefore]                                       NVARCHAR (100) NULL,
    [Attribute_AttrPercentAfter]                                     NVARCHAR (100) NULL,
    [Attribute_AttrPercentBefore]                                    NVARCHAR (100) NULL,
    [attributeValBefore_CADIS_ROW_ID]                                INT            NULL,
    [attributeValBefore_type]                                        NVARCHAR (100) NULL,
    [attributeValBefore_ViolateIfPriceIsNA]                          NVARCHAR (100) NULL,
    [attributeValBefore_CheckLimitPrc]                               NVARCHAR (100) NULL,
    [PriceSourcePrecedenceTable_CADIS_ROW_ID]                        INT            NULL,
    [PriceSourcePrecedenceTable_Value]                               NVARCHAR (100) NULL,
    [attributeValAfter_CADIS_ROW_ID]                                 INT            NULL,
    [attributeValAfter_type]                                         NVARCHAR (100) NULL,
    [attributeValAfter_ViolateIfPriceIsNA]                           NVARCHAR (100) NULL,
    [attributeValAfter_CheckLimitPrc]                                NVARCHAR (100) NULL,
    [PriceSourcePrecedenceTable_CADIS_ROW_ID_0017]                   INT            NULL,
    [PriceSourcePrecedenceTable_Value_0018]                          NVARCHAR (100) NULL,
    [AttrDetails_CADIS_ROW_ID]                                       INT            NULL,
    [ConditionsNeeded_CADIS_ROW_ID]                                  INT            NULL,
    [ConditionsNeeded_ConditionsNeededValAfter]                      NVARCHAR (100) NULL,
    [ConditionsNeeded_ConditionsNeededValBefore]                     NVARCHAR (100) NULL,
    [Nanr_CADIS_ROW_ID]                                              INT            NULL,
    [Nanr_NanrValAfter]                                              NVARCHAR (100) NULL,
    [Nanr_NanrValBefore]                                             NVARCHAR (100) NULL,
    [USGovtHighest_CADIS_ROW_ID]                                     INT            NULL,
    [USGovtHighest_USGovtHighestValAfter]                            NVARCHAR (100) NULL,
    [USGovtHighest_USGovtHighestValBefore]                           NVARCHAR (100) NULL,
    [MoneyMkts_CADIS_ROW_ID]                                         INT            NULL,
    [MoneyMkts_InclMoneyMktsAfter]                                   NVARCHAR (100) NULL,
    [MoneyMkts_InclMoneyMktsBefore]                                  NVARCHAR (100) NULL,
    [MaturityCalculatedIn_CADIS_ROW_ID]                              INT            NULL,
    [MaturityCalculatedIn_MaturityCalculatedInValAfter]              NVARCHAR (100) NULL,
    [MaturityCalculatedIn_MaturityCalculatedInValBefore]             NVARCHAR (100) NULL,
    [MaturityFrom_CADIS_ROW_ID]                                      INT            NULL,
    [MaturityFrom_MaturityFromValAfter]                              NVARCHAR (100) NULL,
    [MaturityFrom_MaturityFromValBefore]                             NVARCHAR (100) NULL,
    [MaturityFundRedemptionDate_CADIS_ROW_ID]                        INT            NULL,
    [MaturityFundRedemptionDate_MaturityFundRedemptionDateValAfter]  NVARCHAR (100) NULL,
    [MaturityFundRedemptionDate_MaturityFundRedemptionDateValBefore] NVARCHAR (100) NULL,
    [IssueDateRangeCalculatedIn_CADIS_ROW_ID]                        INT            NULL,
    [IssueDateRangeCalculatedIn_IssueDateRangeCalculatedInValAfter]  NVARCHAR (100) NULL,
    [IssueDateRangeCalculatedIn_IssueDateRangeCalculatedInValBefore] NVARCHAR (100) NULL,
    [CustomField_CADIS_ROW_ID]                                       INT            NULL,
    [CustomField_CustomFieldValAfter]                                NVARCHAR (100) NULL,
    [CustomField_CustomFieldValBefore]                               NVARCHAR (100) NULL,
    [ExpirationCalculatedIn_CADIS_ROW_ID]                            INT            NULL,
    [ExpirationCalculatedIn_ExpirationCalculatedInValAfter]          NVARCHAR (100) NULL,
    [ExpirationCalculatedIn_ExpirationCalculatedInValBefore]         NVARCHAR (100) NULL,
    [ExpirationFrom_CADIS_ROW_ID]                                    INT            NULL,
    [ExpirationFrom_ExpirationFromValAfter]                          NVARCHAR (100) NULL,
    [ExpirationFrom_ExpirationFromValBefore]                         NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]                                          DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__1EF436AC] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                                           DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__1FE85AE5] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                                         NVARCHAR (50)  CONSTRAINT [DF__T_RuleAud__CADIS__20DC7F1E] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                                          INT            CONSTRAINT [DF__T_RuleAud__CADIS__21D0A357] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleAuditTrail_Rule_Revision_Attributes_Attribute_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

