CREATE TABLE [dbo].[T_RuleAuditTrail_Rule_Revision_CheckCompliance_IN] (
    [CADIS_BATCH_ID]                            INT            NOT NULL,
    [CADIS_MSG_ID]                              INT            CONSTRAINT [DF__T_RuleAud__CADIS__7C9F1EA8] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                           INT            NOT NULL,
    [CADIS_ROW_ID]                              INT            NOT NULL,
    [CheckCompliance_CADIS_ROW_ID]              INT            NULL,
    [Severity_CADIS_ROW_ID]                     INT            NULL,
    [Severity_SeverityValAfter]                 NVARCHAR (100) NULL,
    [Severity_SeverityValBefore]                NVARCHAR (100) NULL,
    [OverrideUserGrp_CADIS_ROW_ID]              INT            NULL,
    [OverrideUserGrp_OverrideUserGrpNameAfter]  NVARCHAR (100) NULL,
    [OverrideUserGrp_OverrideUserGrpNameBefore] NVARCHAR (100) NULL,
    [OverrideUserGrp_OverrideUserGrpTypeAfter]  NVARCHAR (100) NULL,
    [OverrideUserGrp_OverrideUserGrpTypeBefore] NVARCHAR (100) NULL,
    [Alert_CADIS_ROW_ID]                        INT            NULL,
    [Alert_AlertTypeAfter]                      NVARCHAR (100) NULL,
    [Alert_AlertTypeBefore]                     NVARCHAR (100) NULL,
    [PostMsgTarget_CADIS_ROW_ID]                INT            NULL,
    [PostMsgTarget_PostMsgTargetNameAfter]      NVARCHAR (100) NULL,
    [PostMsgTarget_PostMsgTargetNameBefore]     NVARCHAR (100) NULL,
    [PostMsgTarget_PostMsgTargetTypeAfter]      NVARCHAR (100) NULL,
    [PostMsgTarget_PostMsgTargetTypeBefore]     NVARCHAR (100) NULL,
    [PreTrade_CADIS_ROW_ID]                     INT            NULL,
    [PreTrade_PreTradeCheckAfter]               NVARCHAR (100) NULL,
    [PreTrade_PreTradeCheckBefore]              NVARCHAR (100) NULL,
    [PostTrade_CADIS_ROW_ID]                    INT            NULL,
    [PostTrade_PostTradeCheckAfter]             NVARCHAR (100) NULL,
    [PostTrade_PostTradeCheckBefore]            NVARCHAR (100) NULL,
    [EndOfDay_CADIS_ROW_ID]                     INT            NULL,
    [EndOfDay_EndOfDayCheckAfter]               NVARCHAR (100) NULL,
    [EndOfDay_EndOfDayCheckBefore]              NVARCHAR (100) NULL,
    [OpenOrders_CADIS_ROW_ID]                   INT            NULL,
    [OpenOrders_InclOpenOrdersAfter]            NVARCHAR (100) NULL,
    [OpenOrders_InclOpenOrdersBefore]           NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]                     DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__7D9342E1] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                      DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__7E87671A] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                    NVARCHAR (50)  CONSTRAINT [DF__T_RuleAud__CADIS__7F7B8B53] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                     INT            CONSTRAINT [DF__T_RuleAud__CADIS__006FAF8C] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleAuditTrail_Rule_Revision_CheckCompliance_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

