CREATE TABLE [dbo].[T_RuleAuditTrail_Rule_Revision_Boundaries_IN] (
    [CADIS_BATCH_ID]                             INT            NOT NULL,
    [CADIS_MSG_ID]                               INT            CONSTRAINT [DF__T_RuleAud__CADIS__75F22119] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                            INT            NOT NULL,
    [CADIS_ROW_ID]                               INT            NOT NULL,
    [Boundaries_CADIS_ROW_ID]                    INT            NULL,
    [Maximum_CADIS_ROW_ID]                       INT            NULL,
    [Maximum_MaxValAfter]                        NVARCHAR (100) NULL,
    [Maximum_MaxValBefore]                       NVARCHAR (100) NULL,
    [Minimum_CADIS_ROW_ID]                       INT            NULL,
    [Minimum_MinValAfter]                        NVARCHAR (100) NULL,
    [Minimum_MinValBefore]                       NVARCHAR (100) NULL,
    [ConditionsNeeded_CADIS_ROW_ID]              INT            NULL,
    [ConditionsNeeded_ConditionsNeededValAfter]  NVARCHAR (100) NULL,
    [ConditionsNeeded_ConditionsNeededValBefore] NVARCHAR (100) NULL,
    [Nanr_CADIS_ROW_ID]                          INT            NULL,
    [Nanr_NanrValAfter]                          NVARCHAR (100) NULL,
    [Nanr_NanrValBefore]                         NVARCHAR (100) NULL,
    [USGovtHighest_CADIS_ROW_ID]                 INT            NULL,
    [USGovtHighest_USGovtHighestValAfter]        NVARCHAR (100) NULL,
    [USGovtHighest_USGovtHighestValBefore]       NVARCHAR (100) NULL,
    [MoneyMkts_CADIS_ROW_ID]                     INT            NULL,
    [MoneyMkts_InclMoneyMktsAfter]               NVARCHAR (100) NULL,
    [MoneyMkts_InclMoneyMktsBefore]              NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]                      DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__76E64552] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                       DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__77DA698B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                     NVARCHAR (50)  CONSTRAINT [DF__T_RuleAud__CADIS__78CE8DC4] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                      INT            CONSTRAINT [DF__T_RuleAud__CADIS__79C2B1FD] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleAuditTrail_Rule_Revision_Boundaries_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

