CREATE TABLE [dbo].[T_RuleSummary_Rule_Boundaries_IN_NEW] (
    [CADIS_BATCH_ID]                       INT            NOT NULL,
    [CADIS_MSG_ID]                         INT            CONSTRAINT [DF__T_RuleSum__CADIS__6531A96B] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                      INT            NOT NULL,
    [CADIS_ROW_ID]                         INT            NOT NULL,
    [Boundaries_CADIS_ROW_ID]              INT            NULL,
    [Maximum_CADIS_ROW_ID]                 INT            NULL,
    [Maximum_MaxVal]                       NVARCHAR (100) NULL,
    [Minimum_CADIS_ROW_ID]                 INT            NULL,
    [Minimum_MinVal]                       NVARCHAR (100) NULL,
    [ConditionsNeeded_CADIS_ROW_ID]        INT            NULL,
    [ConditionsNeeded_ConditionsNeededVal] NVARCHAR (100) NULL,
    [Nanr_CADIS_ROW_ID]                    INT            NULL,
    [Nanr_NanrVal]                         NVARCHAR (100) NULL,
    [USGovtHighest_CADIS_ROW_ID]           INT            NULL,
    [USGovtHighest_USGovtHighestVal]       NVARCHAR (100) NULL,
    [MoneyMkts_CADIS_ROW_ID]               INT            NULL,
    [MoneyMkts_InclMoneyMkts]              NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]                DATETIME       CONSTRAINT [DF__T_RuleSum__CADIS__6625CDA4] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                 DATETIME       CONSTRAINT [DF__T_RuleSum__CADIS__6719F1DD] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]               NVARCHAR (50)  CONSTRAINT [DF__T_RuleSum__CADIS__680E1616] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                INT            CONSTRAINT [DF__T_RuleSum__CADIS__69023A4F] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleSummary_Rule_Boundaries_IN_NEW] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

