CREATE TABLE [dbo].[T_RuleAuditTrail_Rule_Revision_RuleDetails_IN] (
    [CADIS_BATCH_ID]                INT            NOT NULL,
    [CADIS_MSG_ID]                  INT            CONSTRAINT [DF__T_RuleAud__CADIS__38B408AF] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]               INT            NOT NULL,
    [CADIS_ROW_ID]                  INT            NOT NULL,
    [RuleDetails_CADIS_ROW_ID]      INT            NULL,
    [RuleDetails_RuleCurncyAfter]   NVARCHAR (100) NULL,
    [RuleDetails_RuleCurncyBefore]  NVARCHAR (100) NULL,
    [RuleDetails_RuleExprAfter]     NVARCHAR (100) NULL,
    [RuleDetails_RuleExprBefore]    NVARCHAR (100) NULL,
    [RuleDetails_RuleStateAfter]    NVARCHAR (100) NULL,
    [RuleDetails_RuleStateBefore]   NVARCHAR (100) NULL,
    [RuleDetails_RuleTypeAfter]     NVARCHAR (100) NULL,
    [RuleDetails_RuleTypeBefore]    NVARCHAR (100) NULL,
    [RuleDetails_RuleWgtTypeAfter]  NVARCHAR (100) NULL,
    [RuleDetails_RuleWgtTypeBefore] NVARCHAR (100) NULL,
    [RuleDetails_RuleCode]          NVARCHAR (100) NULL,
    [RuleDetails_RuleCodeBefore]    NVARCHAR (100) NULL,
    [RuleDetails_RuleCodeAfter]     NVARCHAR (100) NULL,
    [RuleDetails_RuleNameBefore]    NVARCHAR (100) NULL,
    [RuleDetails_RuleNameAfter]     NVARCHAR (100) NULL,
    [RuleDetails_RuleDescBefore]    NVARCHAR (100) NULL,
    [RuleDetails_RuleDescAfter]     NVARCHAR (100) NULL,
    [RuleDetails_RuleNoteBefore]    NVARCHAR (100) NULL,
    [RuleDetails_RuleNoteAfter]     NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]         DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__39A82CE8] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]          DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__3A9C5121] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]        NVARCHAR (50)  CONSTRAINT [DF__T_RuleAud__CADIS__3B90755A] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]         INT            CONSTRAINT [DF__T_RuleAud__CADIS__3C849993] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleAuditTrail_Rule_Revision_RuleDetails_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

