CREATE TABLE [dbo].[T_RuleAuditTrail_Rule_Revision_Attributes_IN] (
    [CADIS_BATCH_ID]          INT           NOT NULL,
    [CADIS_MSG_ID]            INT           CONSTRAINT [DF__T_RuleAud__CADIS__3F61063E] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]         INT           NOT NULL,
    [CADIS_ROW_ID]            INT           NOT NULL,
    [Attributes_CADIS_ROW_ID] INT           NULL,
    [CADIS_SYSTEM_INSERTED]   DATETIME      CONSTRAINT [DF__T_RuleAud__CADIS__40552A77] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]    DATETIME      CONSTRAINT [DF__T_RuleAud__CADIS__41494EB0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]  NVARCHAR (50) CONSTRAINT [DF__T_RuleAud__CADIS__423D72E9] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]   INT           CONSTRAINT [DF__T_RuleAud__CADIS__43319722] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleAuditTrail_Rule_Revision_Attributes_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

