CREATE TABLE [dbo].[T_RuleSummary_Rule_RuleDefaults_IN_NEW] (
    [CADIS_BATCH_ID]                                               INT            NOT NULL,
    [CADIS_MSG_ID]                                                 INT            CONSTRAINT [DF__T_RuleSum__CADIS__728BA489] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                                              INT            NOT NULL,
    [CADIS_ROW_ID]                                                 INT            NOT NULL,
    [RuleDefaults_CADIS_ROW_ID]                                    INT            NULL,
    [General_CADIS_ROW_ID]                                         INT            NULL,
    [Cash_CADIS_ROW_ID]                                            INT            NULL,
    [Cash_TradeDateCash]                                           NVARCHAR (100) NULL,
    [MarginCash_CADIS_ROW_ID]                                      INT            NULL,
    [MarginCash_MarginCash]                                        NVARCHAR (100) NULL,
    [RatingsDefault_CADIS_ROW_ID]                                  INT            NULL,
    [RatingsDefault_RatingsDefVal]                                 NVARCHAR (100) NULL,
    [Account_CADIS_ROW_ID]                                         INT            NULL,
    [Account_AccountVal]                                           NVARCHAR (100) NULL,
    [Positions_CADIS_ROW_ID]                                       INT            NULL,
    [Positions_PositionsVal]                                       NVARCHAR (100) NULL,
    [IncludeSwapToMaturity_CADIS_ROW_ID]                           INT            NULL,
    [IncludeSwapToMaturity_IncludeSwapToMaturityVal]               NVARCHAR (100) NULL,
    [IncludeFxOptionUntilExp_CADIS_ROW_ID]                         INT            NULL,
    [IncludeFxOptionUntilExp_IncludeFxOptionUntilExpVal]           NVARCHAR (100) NULL,
    [ExcludeFx2Leg_CADIS_ROW_ID]                                   INT            NULL,
    [ExcludeFx2Leg_ExcludeFx2LegVal]                               NVARCHAR (100) NULL,
    [ExcludeFxAtMaturity_CADIS_ROW_ID]                             INT            NULL,
    [ExcludeFxAtMaturity_ExcludeFxAtMaturityVal]                   NVARCHAR (100) NULL,
    [CplmCalculatedOn_CADIS_ROW_ID]                                INT            NULL,
    [CplmCalculatedOn_CplmCalculatedOnVal]                         NVARCHAR (100) NULL,
    [UseAbsLimitsCplm_CADIS_ROW_ID]                                INT            NULL,
    [UseAbsLimitsCplm_UseAbsLimitsCplmVal]                         NVARCHAR (100) NULL,
    [Pricing_CADIS_ROW_ID]                                         INT            NULL,
    [Pricing_PricingVal]                                           NVARCHAR (100) NULL,
    [TSPLLookThrough_CADIS_ROW_ID]                                 INT            NULL,
    [TSPLLookThrough_TSPLLookThroughVal]                           NVARCHAR (100) NULL,
    [SingleViolationForBasket_CADIS_ROW_ID]                        INT            NULL,
    [SingleViolationForBasket_SingleViolationForBasketVal]         NVARCHAR (100) NULL,
    [ViolationWorse_CADIS_ROW_ID]                                  INT            NULL,
    [ViolationWorse_ViolationWorseVal]                             NVARCHAR (100) NULL,
    [ReportingTolerance_CADIS_ROW_ID]                              INT            NULL,
    [ReportingTolerance_RptToleranceVal]                           NVARCHAR (100) NULL,
    [ViolationStorage_CADIS_ROW_ID]                                INT            NULL,
    [ViolationStorage_ViolationStorageVal]                         NVARCHAR (100) NULL,
    [MarketValue_CADIS_ROW_ID]                                     INT            NULL,
    [MarketValue_DenomMktVal]                                      NVARCHAR (100) NULL,
    [MarketValue_MktVal]                                           NVARCHAR (100) NULL,
    [MarketValue_NumerMktVal]                                      NVARCHAR (100) NULL,
    [Derivatives_CADIS_ROW_ID]                                     INT            NULL,
    [FuturesValuation_CADIS_ROW_ID]                                INT            NULL,
    [FuturesValuation_FuturesValDenom]                             NVARCHAR (100) NULL,
    [FuturesValuation_FuturesValNumer]                             NVARCHAR (100) NULL,
    [OptionValuation_CADIS_ROW_ID]                                 INT            NULL,
    [OptionValuation_OptionValDenom]                               NVARCHAR (100) NULL,
    [OptionValuation_OptionValNumer]                               NVARCHAR (100) NULL,
    [SwapsValuation_CADIS_ROW_ID]                                  INT            NULL,
    [SwapsValuation_SwapsValDenom]                                 NVARCHAR (100) NULL,
    [SwapsValuation_SwapsValNumer]                                 NVARCHAR (100) NULL,
    [DerivativesValuation_CADIS_ROW_ID]                            INT            NULL,
    [DerivativesValuation_DervValDenom]                            NVARCHAR (100) NULL,
    [DerivativesValuation_DervValNumer]                            NVARCHAR (100) NULL,
    [ConvertiblesValuation_CADIS_ROW_ID]                           INT            NULL,
    [ConvertiblesValuation_ConvValNumer]                           NVARCHAR (100) NULL,
    [InterestRateFuturesValuation_CADIS_ROW_ID]                    INT            NULL,
    [InterestRateFuturesValuation_IRFValNumer]                     NVARCHAR (100) NULL,
    [ExpirationTable_CADIS_ROW_ID]                                 INT            NULL,
    [ExpirationRange1_CADIS_ROW_ID]                                INT            NULL,
    [ExpirationRange1_Months]                                      NVARCHAR (100) NULL,
    [ExpirationRange1_Op]                                          NVARCHAR (100) NULL,
    [NetIfExpirationDiff1_CADIS_ROW_ID]                            INT            NULL,
    [NetIfExpirationDiff1_Op]                                      NVARCHAR (100) NULL,
    [NetIfExpirationDiff1_Days]                                    NVARCHAR (100) NULL,
    [ExpirationRange2_CADIS_ROW_ID]                                INT            NULL,
    [ExpirationRange2_Month1]                                      NVARCHAR (100) NULL,
    [ExpirationRange2_Month2]                                      NVARCHAR (100) NULL,
    [ExpirationRange2_Op1]                                         NVARCHAR (100) NULL,
    [ExpirationRange2_Op2]                                         NVARCHAR (100) NULL,
    [NetIfExpirationDiff2_CADIS_ROW_ID]                            INT            NULL,
    [NetIfExpirationDiff2_Op]                                      NVARCHAR (100) NULL,
    [NetIfExpirationDiff2_Days]                                    NVARCHAR (100) NULL,
    [ExpirationRange3_CADIS_ROW_ID]                                INT            NULL,
    [ExpirationRange3_Months]                                      NVARCHAR (100) NULL,
    [ExpirationRange3_Op]                                          NVARCHAR (100) NULL,
    [NetIfExpirationDiff3_CADIS_ROW_ID]                            INT            NULL,
    [NetIfExpirationDiff3_Op]                                      NVARCHAR (100) NULL,
    [NetIfExpirationDiff3_Days]                                    NVARCHAR (100) NULL,
    [LookThroughToUnderlyingAttrs_CADIS_ROW_ID]                    INT            NULL,
    [LookThroughToUnderlyingAttrs_LookThroughToUnderlyingAttrsVal] NVARCHAR (100) NULL,
    [NumOfContracts_CADIS_ROW_ID]                                  INT            NULL,
    [NumOfContracts_NumOfContractsVal]                             NVARCHAR (100) NULL,
    [RepoReverse_CADIS_ROW_ID]                                     INT            NULL,
    [CollateralManagement_CADIS_ROW_ID]                            INT            NULL,
    [SecRepoedIN_CADIS_ROW_ID]                                     INT            NULL,
    [SecRepoedIN_InclSecRepoedIN]                                  NVARCHAR (100) NULL,
    [SecRepoedOUT_CADIS_ROW_ID]                                    INT            NULL,
    [SecRepoedOUT_InclSecRepoedOUT]                                NVARCHAR (100) NULL,
    [PledgedCollat_CADIS_ROW_ID]                                   INT            NULL,
    [PledgedCollat_InclPledgedCollat]                              NVARCHAR (100) NULL,
    [RepoValuation_CADIS_ROW_ID]                                   INT            NULL,
    [RepoValuation_RepoVal]                                        NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]                                        DATETIME       CONSTRAINT [DF__T_RuleSum__CADIS__737FC8C2] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                                         DATETIME       CONSTRAINT [DF__T_RuleSum__CADIS__7473ECFB] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                                       NVARCHAR (50)  CONSTRAINT [DF__T_RuleSum__CADIS__75681134] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                                        INT            CONSTRAINT [DF__T_RuleSum__CADIS__765C356D] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleSummary_Rule_RuleDefaults_IN_NEW] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

