CREATE TABLE [dbo].[T_RuleAuditTrail_Rule_Revision_RuleDefaults_IN] (
    [CADIS_BATCH_ID]                                                     INT            NOT NULL,
    [CADIS_MSG_ID]                                                       INT            CONSTRAINT [DF__T_RuleAud__CADIS__034C1C37] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                                                    INT            NOT NULL,
    [CADIS_ROW_ID]                                                       INT            NOT NULL,
    [RuleDefaults_CADIS_ROW_ID]                                          INT            NULL,
    [General_CADIS_ROW_ID]                                               INT            NULL,
    [Cash_CADIS_ROW_ID]                                                  INT            NULL,
    [Cash_TradeDateCashAfter]                                            NVARCHAR (100) NULL,
    [Cash_TradeDateCashBefore]                                           NVARCHAR (100) NULL,
    [RatingsDefault_CADIS_ROW_ID]                                        INT            NULL,
    [RatingsDefault_RatingsDefValAfter]                                  NVARCHAR (100) NULL,
    [RatingsDefault_RatingsDefValBefore]                                 NVARCHAR (100) NULL,
    [Account_CADIS_ROW_ID]                                               INT            NULL,
    [Account_AccountValAfter]                                            NVARCHAR (100) NULL,
    [Account_AccountValBefore]                                           NVARCHAR (100) NULL,
    [Positions_CADIS_ROW_ID]                                             INT            NULL,
    [Positions_PositionsValAfter]                                        NVARCHAR (100) NULL,
    [Positions_PositionsValBefore]                                       NVARCHAR (100) NULL,
    [IncludeSwapToMaturity_CADIS_ROW_ID]                                 INT            NULL,
    [IncludeSwapToMaturity_IncludeSwapToMatAfter]                        NVARCHAR (100) NULL,
    [IncludeSwapToMaturity_IncludeSwapToMatBefore]                       NVARCHAR (100) NULL,
    [IncludeFxOptionUntilExp_CADIS_ROW_ID]                               INT            NULL,
    [IncludeFxOptionUntilExp_IncludeFxOptionUntilExpAfter]               NVARCHAR (100) NULL,
    [IncludeFxOptionUntilExp_IncludeFxOptionUntilExpBefore]              NVARCHAR (100) NULL,
    [ExcludeFx2Leg_CADIS_ROW_ID]                                         INT            NULL,
    [ExcludeFx2Leg_ExcludeFx2LegAfter]                                   NVARCHAR (100) NULL,
    [ExcludeFx2Leg_ExcludeFx2LegBefore]                                  NVARCHAR (100) NULL,
    [ExcludeFxAtMaturity_CADIS_ROW_ID]                                   INT            NULL,
    [ExcludeFxAtMaturity_ExcludeFxAtMaturityAfter]                       NVARCHAR (100) NULL,
    [ExcludeFxAtMaturity_ExcludeFxAtMaturityBefore]                      NVARCHAR (100) NULL,
    [CplmCalculatedOn_CADIS_ROW_ID]                                      INT            NULL,
    [CplmCalculatedOn_CplmCalculatedOnAfter]                             NVARCHAR (100) NULL,
    [CplmCalculatedOn_CplmCalculatedOnBefore]                            NVARCHAR (100) NULL,
    [UseAbsLimitsCplm_CADIS_ROW_ID]                                      INT            NULL,
    [UseAbsLimitsCplm_UseAbsLimitsCplmAfter]                             NVARCHAR (100) NULL,
    [UseAbsLimitsCplm_UseAbsLimitsCplmBefore]                            NVARCHAR (100) NULL,
    [Pricing_CADIS_ROW_ID]                                               INT            NULL,
    [Pricing_PricingValAfter]                                            NVARCHAR (100) NULL,
    [Pricing_PricingValBefore]                                           NVARCHAR (100) NULL,
    [ViolationWorse_CADIS_ROW_ID]                                        INT            NULL,
    [ViolationWorse_ViolationWorseValAfter]                              NVARCHAR (100) NULL,
    [ViolationWorse_ViolationWorseValBefore]                             NVARCHAR (100) NULL,
    [ReportingTolerance_CADIS_ROW_ID]                                    INT            NULL,
    [ReportingTolerance_RptToleranceValAfter]                            NVARCHAR (100) NULL,
    [ReportingTolerance_RptToleranceValBefore]                           NVARCHAR (100) NULL,
    [ViolationStorage_CADIS_ROW_ID]                                      INT            NULL,
    [ViolationStorage_ViolationStorageValAfter]                          NVARCHAR (100) NULL,
    [ViolationStorage_ViolationStorageValBefore]                         NVARCHAR (100) NULL,
    [MarketValue_CADIS_ROW_ID]                                           INT            NULL,
    [MarketValue_DenomMktValAfter]                                       NVARCHAR (100) NULL,
    [MarketValue_DenomMktValBefore]                                      NVARCHAR (100) NULL,
    [MarketValue_MktValAfter]                                            NVARCHAR (100) NULL,
    [MarketValue_MktValBefore]                                           NVARCHAR (100) NULL,
    [MarketValue_NumerMktValAfter]                                       NVARCHAR (100) NULL,
    [MarketValue_NumerMktValBefore]                                      NVARCHAR (100) NULL,
    [MarginCash_CADIS_ROW_ID]                                            INT            NULL,
    [MarginCash_MarginCashAfter]                                         NVARCHAR (100) NULL,
    [MarginCash_MarginCashBefore]                                        NVARCHAR (100) NULL,
    [Derivatives_CADIS_ROW_ID]                                           INT            NULL,
    [FuturesValuation_CADIS_ROW_ID]                                      INT            NULL,
    [FuturesValuation_FuturesValDenomAfter]                              NVARCHAR (100) NULL,
    [FuturesValuation_FuturesValDenomBefore]                             NVARCHAR (100) NULL,
    [FuturesValuation_FuturesValNumerAfter]                              NVARCHAR (100) NULL,
    [FuturesValuation_FuturesValNumerBefore]                             NVARCHAR (100) NULL,
    [OptionValuation_CADIS_ROW_ID]                                       INT            NULL,
    [OptionValuation_OptionValDenomAfter]                                NVARCHAR (100) NULL,
    [OptionValuation_OptionValDenomBefore]                               NVARCHAR (100) NULL,
    [OptionValuation_OptionValNumerAfter]                                NVARCHAR (100) NULL,
    [OptionValuation_OptionValNumerBefore]                               NVARCHAR (100) NULL,
    [SwapsValuation_CADIS_ROW_ID]                                        INT            NULL,
    [SwapsValuation_SwapsValDenomAfter]                                  NVARCHAR (100) NULL,
    [SwapsValuation_SwapsValDenomBefore]                                 NVARCHAR (100) NULL,
    [SwapsValuation_SwapsValNumerAfter]                                  NVARCHAR (100) NULL,
    [SwapsValuation_SwapsValNumerBefore]                                 NVARCHAR (100) NULL,
    [DerivativesValuation_CADIS_ROW_ID]                                  INT            NULL,
    [DerivativesValuation_DervValDenomAfter]                             NVARCHAR (100) NULL,
    [DerivativesValuation_DervValDenomBefore]                            NVARCHAR (100) NULL,
    [DerivativesValuation_DervValNumerAfter]                             NVARCHAR (100) NULL,
    [DerivativesValuation_DervValNumerBefore]                            NVARCHAR (100) NULL,
    [InterestRateFuturesValuation_CADIS_ROW_ID]                          INT            NULL,
    [InterestRateFuturesValuation_IRFValNumerAfter]                      NVARCHAR (100) NULL,
    [InterestRateFuturesValuation_IRFValNumerBefore]                     NVARCHAR (100) NULL,
    [ConvertiblesValuation_CADIS_ROW_ID]                                 INT            NULL,
    [ConvertiblesValuation_ConvValNumerAfter]                            NVARCHAR (100) NULL,
    [ConvertiblesValuation_ConvValNumerBefore]                           NVARCHAR (100) NULL,
    [ExpirationTable_CADIS_ROW_ID]                                       INT            NULL,
    [ExpirationRange1_CADIS_ROW_ID]                                      INT            NULL,
    [ExpirationRange1_MonthAfter]                                        NVARCHAR (100) NULL,
    [ExpirationRange1_MonthBefore]                                       NVARCHAR (100) NULL,
    [ExpirationRange1_OpAfter]                                           NVARCHAR (100) NULL,
    [ExpirationRange1_OpBefore]                                          NVARCHAR (100) NULL,
    [NetIfExpirationDiff1_CADIS_ROW_ID]                                  INT            NULL,
    [NetIfExpirationDiff1_OpAfter]                                       NVARCHAR (100) NULL,
    [NetIfExpirationDiff1_OpBefore]                                      NVARCHAR (100) NULL,
    [NetIfExpirationDiff1_DaysAfter]                                     NVARCHAR (100) NULL,
    [NetIfExpirationDiff1_DaysBefore]                                    NVARCHAR (100) NULL,
    [ExpirationRange2_CADIS_ROW_ID]                                      INT            NULL,
    [ExpirationRange2_Month1After]                                       NVARCHAR (100) NULL,
    [ExpirationRange2_Month1Before]                                      NVARCHAR (100) NULL,
    [ExpirationRange2_Month2After]                                       NVARCHAR (100) NULL,
    [ExpirationRange2_Month2Before]                                      NVARCHAR (100) NULL,
    [ExpirationRange2_Op1After]                                          NVARCHAR (100) NULL,
    [ExpirationRange2_Op1Before]                                         NVARCHAR (100) NULL,
    [ExpirationRange2_Op2After]                                          NVARCHAR (100) NULL,
    [ExpirationRange2_Op2Before]                                         NVARCHAR (100) NULL,
    [NetIfExpirationDiff2_CADIS_ROW_ID]                                  INT            NULL,
    [NetIfExpirationDiff2_OpAfter]                                       NVARCHAR (100) NULL,
    [NetIfExpirationDiff2_OpBefore]                                      NVARCHAR (100) NULL,
    [NetIfExpirationDiff2_DaysAfter]                                     NVARCHAR (100) NULL,
    [NetIfExpirationDiff2_DaysBefore]                                    NVARCHAR (100) NULL,
    [ExpirationRange3_CADIS_ROW_ID]                                      INT            NULL,
    [ExpirationRange3_MonthAfter]                                        NVARCHAR (100) NULL,
    [ExpirationRange3_MonthBefore]                                       NVARCHAR (100) NULL,
    [ExpirationRange3_OpAfter]                                           NVARCHAR (100) NULL,
    [ExpirationRange3_OpBefore]                                          NVARCHAR (100) NULL,
    [NetIfExpirationDiff3_CADIS_ROW_ID]                                  INT            NULL,
    [NetIfExpirationDiff3_OpAfter]                                       NVARCHAR (100) NULL,
    [NetIfExpirationDiff3_OpBefore]                                      NVARCHAR (100) NULL,
    [NetIfExpirationDiff3_DaysAfter]                                     NVARCHAR (100) NULL,
    [NetIfExpirationDiff3_DaysBefore]                                    NVARCHAR (100) NULL,
    [LookThroughToUnderlyingAttrs_CADIS_ROW_ID]                          INT            NULL,
    [LookThroughToUnderlyingAttrs_LookThroughToUnderlyingAttrsValAfter]  NVARCHAR (100) NULL,
    [LookThroughToUnderlyingAttrs_LookThroughToUnderlyingAttrsValBefore] NVARCHAR (100) NULL,
    [NumOfContracts_CADIS_ROW_ID]                                        INT            NULL,
    [NumOfContracts_NumOfContractsValAfter]                              NVARCHAR (100) NULL,
    [NumOfContracts_NumOfContractsValBefore]                             NVARCHAR (100) NULL,
    [RepoReverse_CADIS_ROW_ID]                                           INT            NULL,
    [CollateralManagement_CADIS_ROW_ID]                                  INT            NULL,
    [SecRepoedIN_CADIS_ROW_ID]                                           INT            NULL,
    [SecRepoedIN_InclSecRepoedINAfter]                                   NVARCHAR (100) NULL,
    [SecRepoedIN_InclSecRepoedINBefore]                                  NVARCHAR (100) NULL,
    [SecRepoedOUT_CADIS_ROW_ID]                                          INT            NULL,
    [SecRepoedOUT_InclSecRepoedOUTAfter]                                 NVARCHAR (100) NULL,
    [SecRepoedOUT_InclSecRepoedOUTBefore]                                NVARCHAR (100) NULL,
    [PledgedCollat_CADIS_ROW_ID]                                         INT            NULL,
    [PledgedCollat_InclPledgedCollatAfter]                               NVARCHAR (100) NULL,
    [PledgedCollat_InclPledgedCollatBefore]                              NVARCHAR (100) NULL,
    [RepoValuation_CADIS_ROW_ID]                                         INT            NULL,
    [RepoValuation_RepoValAfter]                                         NVARCHAR (100) NULL,
    [RepoValuation_RepoValBefore]                                        NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]                                              DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__04404070] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                                               DATETIME       CONSTRAINT [DF__T_RuleAud__CADIS__053464A9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                                             NVARCHAR (50)  CONSTRAINT [DF__T_RuleAud__CADIS__062888E2] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                                              INT            CONSTRAINT [DF__T_RuleAud__CADIS__071CAD1B] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleAuditTrail_Rule_Revision_RuleDefaults_IN] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

