CREATE TABLE [dbo].[T_RuleSummary_Rule_Attributes_Attribute_IN_NEW] (
    [CADIS_BATCH_ID]                                           INT            NOT NULL,
    [CADIS_MSG_ID]                                             INT            CONSTRAINT [DF__T_RuleSum__CADIS__7938A218] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]                                          INT            NOT NULL,
    [CADIS_ROW_ID]                                             INT            NOT NULL,
    [Attribute_CADIS_ROW_ID]                                   INT            NULL,
    [Attribute_AttrCode]                                       NVARCHAR (100) NULL,
    [Attribute_AttrDesc]                                       NVARCHAR (100) NULL,
    [Attribute_AttrPercent]                                    NVARCHAR (100) NULL,
    [AttrDetails_CADIS_ROW_ID]                                 INT            NULL,
    [AttrDetails_type]                                         NVARCHAR (100) NULL,
    [AttrDetails_ViolateIfPriceIsNA]                           NVARCHAR (100) NULL,
    [AttrDetails_CheckLimitPrc]                                NVARCHAR (100) NULL,
    [ConditionsNeeded_CADIS_ROW_ID]                            INT            NULL,
    [ConditionsNeeded_ConditionsNeededVal]                     NVARCHAR (100) NULL,
    [Nanr_CADIS_ROW_ID]                                        INT            NULL,
    [Nanr_NanrVal]                                             NVARCHAR (100) NULL,
    [USGovtHighest_CADIS_ROW_ID]                               INT            NULL,
    [USGovtHighest_USGovtHighestVal]                           NVARCHAR (100) NULL,
    [MoneyMkts_CADIS_ROW_ID]                                   INT            NULL,
    [MoneyMkts_InclMoneyMkts]                                  NVARCHAR (100) NULL,
    [MaturityCalculatedIn_CADIS_ROW_ID]                        INT            NULL,
    [MaturityCalculatedIn_MaturityCalculatedInVal]             NVARCHAR (100) NULL,
    [MaturityFrom_CADIS_ROW_ID]                                INT            NULL,
    [MaturityFrom_MaturityFromVal]                             NVARCHAR (100) NULL,
    [MaturityFundRedemptionDate_CADIS_ROW_ID]                  INT            NULL,
    [MaturityFundRedemptionDate_MaturityFundRedemptionDateVal] NVARCHAR (100) NULL,
    [CustomField_CADIS_ROW_ID]                                 INT            NULL,
    [CustomField_CustomFieldVal]                               NVARCHAR (100) NULL,
    [IssueDateRangeCalculatedIn_CADIS_ROW_ID]                  INT            NULL,
    [IssueDateRangeCalculatedIn_IssueDateRangeCalculatedInVal] NVARCHAR (100) NULL,
    [PriceSourcePrecedenceTable_CADIS_ROW_ID]                  INT            NULL,
    [PriceSourcePrecedenceTable_Value]                         NVARCHAR (100) NULL,
    [ExpirationCalculatedIn_CADIS_ROW_ID]                      INT            NULL,
    [ExpirationCalculatedIn_ExpirationCalculatedInVal]         NVARCHAR (100) NULL,
    [ExpirationFrom_CADIS_ROW_ID]                              INT            NULL,
    [ExpirationFrom_ExpirationFromVal]                         NVARCHAR (100) NULL,
    [CADIS_SYSTEM_INSERTED]                                    DATETIME       CONSTRAINT [DF__T_RuleSum__CADIS__7A2CC651] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                                     DATETIME       CONSTRAINT [DF__T_RuleSum__CADIS__7B20EA8A] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                                   NVARCHAR (50)  CONSTRAINT [DF__T_RuleSum__CADIS__7C150EC3] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                                    INT            CONSTRAINT [DF__T_RuleSum__CADIS__7D0932FC] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_RuleSummary_Rule_Attributes_Attribute_IN_NEW] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

