CREATE TABLE [dbo].[T_SALESFORCE_POSTCODE_OVERRIDE] (
    [SfAccountId]               VARCHAR (18)   NOT NULL,
    [AccountName]               VARCHAR (1000) NULL,
    [WF_PRIMARY_BUSINESS]       VARCHAR (1000) NULL,
    [BillingStreet]             VARCHAR (1000) NULL,
    [BillingCity]               VARCHAR (100)  NULL,
    [BillingPostcode]           VARCHAR (100)  NULL,
    [AccountOwnerId]            VARCHAR (18)   NULL,
    [OriginalAccountOwnerId]    VARCHAR (18)   NULL,
    [OverrideStatus]            VARCHAR (10)   NULL,
    [Revert]                    BIT            DEFAULT ((0)) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME       CONSTRAINT [DF_T_SALESFORCE_POSTCODE_OVERRIDE_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME       CONSTRAINT [DF_T_SALESFORCE_POSTCODE_OVERRIDE_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    VARCHAR (50)   CONSTRAINT [DF_T_SALESFORCE_POSTCODE_OVERRIDE_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT            CONSTRAINT [DF_T_SALESFORCE_POSTCODE_OVERRIDE_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION     NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME       CONSTRAINT [DF_T_SALESFORCE_POSTCODE_OVERRIDE_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_SALESFORCE_POSTCODE_OVERRIDE] PRIMARY KEY CLUSTERED ([SfAccountId] ASC) WITH (FILLFACTOR = 90)
);

