CREATE TABLE [dbo].[T_Security_Risk_Metrics] (
    [D_Date]                    DATETIME2 (7)   NOT NULL,
    [C_SECURITY]                NVARCHAR (50)   NOT NULL,
    [PX_LAST]                   FLOAT (53)      NULL,
    [VOLUME]                    INT             NULL,
    [PE_RATIO]                  DECIMAL (18, 4) NULL,
    [PX_TO_BOOK_RATIO]          DECIMAL (18, 4) NULL,
    [FREE_CASH_FLOW_YIELD]      DECIMAL (18, 4) NULL,
    [EQY_DVD_YLD_12M]           DECIMAL (18, 4) NULL,
    [PX_TO_SALES_RATIO]         DECIMAL (18, 4) NULL,
    [6MO_CALL_IMP_VOL]          DECIMAL (18, 4) NULL,
    [12MO_CALL_IMP_VOL]         VARCHAR (50)    NULL,
    [REL_SHR_PX_MOMENTUM]       VARCHAR (50)    NULL,
    [PX_CLOSE_1D]               VARCHAR (50)    NULL,
    [TURNOVER]                  VARCHAR (50)    NULL,
    [VWAP_AUTOMATED_VOLUME]     VARCHAR (50)    NULL,
    [VWAP_LIT_VOLUME]           VARCHAR (50)    NULL,
    [CFWEIAA LN Equity]         VARCHAR (50)    NULL,
    [CWHIAGA LN Equity]         VARCHAR (50)    NULL,
    [WPCT LN Equity]            VARCHAR (50)    NULL,
    [CO1 Comdty]                VARCHAR (50)    NULL,
    [XAU BGN Curncy]            VARCHAR (50)    NULL,
    [HG1 COMB Comdty]           VARCHAR (50)    NULL,
    [RBT1 COMB Comdty]          VARCHAR (50)    NULL,
    [API2YR1 Equity]            VARCHAR (50)    NULL,
    [ASX Equity]                VARCHAR (50)    NULL,
    [CRB RIND Equity]           VARCHAR (50)    NULL,
    [EUCRBRDT Equity]           VARCHAR (50)    NULL,
    [GUKG10 Equity]             VARCHAR (50)    NULL,
    [MCX Index]                 VARCHAR (50)    NULL,
    [NKY Index]                 VARCHAR (50)    NULL,
    [NYM1CNCN Index]            VARCHAR (50)    NULL,
    [SHCOMP Equity]             VARCHAR (50)    NULL,
    [SPX Index]                 VARCHAR (50)    NULL,
    [SX5E Equity]               VARCHAR (50)    NULL,
    [UKX Index]                 VARCHAR (50)    NULL,
    [USGG10YR Equity]           VARCHAR (50)    NULL,
    [GBPUSD Equity]             VARCHAR (50)    NULL,
    [XAG BGN Curncy]            VARCHAR (50)    NULL,
    [XPT BGN Curncy]            VARCHAR (50)    NULL,
    [CURRENT_EV_TO_T12M_EBITDA] VARCHAR (50)    NULL
);

