CREATE TABLE [dbo].[T_SJP_FUND_FLOW_PRE] (
    [ROW_NUMBER]                INT             NOT NULL,
    [TYPE]                      VARCHAR (20)    NOT NULL,
    [FUND_CODE_A]               VARCHAR (50)    NULL,
    [FUND_CODE_B]               VARCHAR (50)    NULL,
    [FUND_NAME]                 VARCHAR (50)    NULL,
    [STATIC_DATA]               VARCHAR (15)    NULL,
    [TRADE_DATE]                DATETIME        NULL,
    [CREATION_CASH_GBP]         DECIMAL (18, 2) NULL,
    [CREATION_CASH_USD]         DECIMAL (18, 2) NULL,
    [CREATION_CASH_EUR]         DECIMAL (18, 2) NULL,
    [CANCELLATION_CASH_GBP]     DECIMAL (18, 2) NULL,
    [CANCELLATION_CASH_USD]     DECIMAL (18, 2) NULL,
    [CANCELLATION_CASH_EUR]     DECIMAL (18, 2) NULL,
    [SETTLE_DATE]               DATETIME        NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__6FD0CA1D] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__70C4EE56] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   CONSTRAINT [DF__T_SJP_FUN__CADIS__71B9128F] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             CONSTRAINT [DF__T_SJP_FUN__CADIS__72AD36C8] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__73A15B01] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_SJP_FU__EED2195912163B4F] PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC, [TYPE] ASC) WITH (FILLFACTOR = 90)
);

