CREATE TABLE [dbo].[T_SJP_FND_FLOW_IN] (
    [ROW_NUMBER]             INT             IDENTITY (1, 1) NOT NULL,
    [FUND_CODE_A]            VARCHAR (50)    NULL,
    [FUND_CODE_B]            VARCHAR (50)    NULL,
    [FUND_NAME]              VARCHAR (50)    NULL,
    [STATIC_DATA]            VARCHAR (15)    NULL,
    [TRADE_DATE]             DATETIME        NULL,
    [CREATION_CASH_GBP]      DECIMAL (18, 2) NULL,
    [CREATION_CASH_USD]      DECIMAL (18, 2) NULL,
    [CREATION_CASH_EUR]      DECIMAL (18, 2) NULL,
    [CANCELLATION_CASH_GBP]  DECIMAL (18, 2) NULL,
    [CANCELLATION_CASH_USD]  DECIMAL (18, 2) NULL,
    [CANCELLATION_CASH_EUR]  DECIMAL (18, 2) NULL,
    [SETTLE_DATE]            DATETIME        NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        CONSTRAINT [DF__T_SJP_FND__CADIS__2C44DB80] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        CONSTRAINT [DF__T_SJP_FND__CADIS__2D38FFB9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   CONSTRAINT [DF__T_SJP_FND__CADIS__2E2D23F2] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT             CONSTRAINT [DF__T_SJP_FND__CADIS__2F21482B] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_SJP_FN__F6D12DF334B0E26E] PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC) WITH (FILLFACTOR = 90)
);

