CREATE TABLE [dbo].[T_SJPHIY_GROSS_FUND_FLOW_IN] (
    [ROW_NUMBER]               INT              IDENTITY (1, 1) NOT NULL,
    [FUND]                     VARCHAR (50)     NULL,
    [TRADE_DATE]               DATETIME         NULL,
    [SETT_DATE]                DATETIME         NULL,
    [UNIT_TYPE]                VARCHAR (50)     NULL,
    [UNITS_CREATED]            DECIMAL (18, 2)  NULL,
    [UNITS_CANCELLED]          DECIMAL (18, 2)  NULL,
    [TOTAL_CREATED]            DECIMAL (18, 2)  NULL,
    [CAPITAL_AMOUNT_CREATED]   DECIMAL (26, 10) NULL,
    [INCOME_AMOUNT_CREATED]    DECIMAL (26, 10) NULL,
    [TOTAL_CANCELLED]          DECIMAL (18, 2)  NULL,
    [CAPITAL_AMOUNT_CANCELLED] DECIMAL (18, 2)  NULL,
    [INCOME_AMOUNT_CANCELLED]  DECIMAL (18, 2)  NULL,
    [CADIS_SYSTEM_INSERTED]    DATETIME         CONSTRAINT [DF__T_SJPHIY___CADIS__2C6EF8B2] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]     DATETIME         CONSTRAINT [DF__T_SJPHIY___CADIS__2D631CEB] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]   NVARCHAR (50)    CONSTRAINT [DF__T_SJPHIY___CADIS__2E574124] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]    INT              CONSTRAINT [DF__T_SJPHIY___CADIS__2F4B655D] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_SJPHIY__F6D12DF36E919F5C] PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC) WITH (FILLFACTOR = 90)
);

