CREATE TABLE [dbo].[T_SJP_FUND_FLOW] (
    [ROW_NUMBER]                INT             NULL,
    [TYPE]                      VARCHAR (20)    NULL,
    [FUND_SHORT_NAME]           VARCHAR (15)    NOT NULL,
    [TRANSACTION_DATE]          DATETIME        NOT NULL,
    [CURRENCY]                  VARCHAR (20)    NOT NULL,
    [FUND_FLOW_TYPE]            VARCHAR (20)    NOT NULL,
    [FLOW_TYPE]                 VARCHAR (100)   NOT NULL,
    [SETTLEMENT_DATE]           DATETIME        NULL,
    [MARKET_VALUE]              DECIMAL (18, 2) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__2252F3A0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__234717D9] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   CONSTRAINT [DF__T_SJP_FUN__CADIS__243B3C12] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             CONSTRAINT [DF__T_SJP_FUN__CADIS__252F604B] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__26238484] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_SJP_FU__E6ED91A87D420953] PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRANSACTION_DATE] ASC, [CURRENCY] ASC, [FUND_FLOW_TYPE] ASC, [FLOW_TYPE] ASC) WITH (FILLFACTOR = 90)
);

