CREATE TABLE [dbo].[T_SJP_FUND_FLOW_POST] (
    [ROW_NUMBER]                INT             NOT NULL,
    [TYPE]                      VARCHAR (20)    NOT NULL,
    [FUND_SHORT_NAME]           VARCHAR (15)    NULL,
    [TRANSACTION_DATE]          DATETIME        NULL,
    [CURRENCY]                  VARCHAR (20)    NULL,
    [FUND_FLOW_TYPE]            VARCHAR (20)    NULL,
    [FLOW_TYPE]                 VARCHAR (100)   NULL,
    [SETTLEMENT_DATE]           DATETIME        NULL,
    [MARKET_VALUE]              DECIMAL (18, 2) NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__6CAB1006] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__6D9F343F] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50)   CONSTRAINT [DF__T_SJP_FUN__CADIS__6E935878] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT             CONSTRAINT [DF__T_SJP_FUN__CADIS__6F877CB1] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME        CONSTRAINT [DF__T_SJP_FUN__CADIS__707BA0EA] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK__T_SJP_FU__EED2195945608569] PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC, [TYPE] ASC) WITH (FILLFACTOR = 90)
);

