CREATE TABLE [dbo].[T_Snapshot_Instruments_Equity_FUNDAPPS_OUT] (
    [CADIS_BATCH_ID]         INT            NOT NULL,
    [CADIS_MSG_ID]           INT            CONSTRAINT [DF__T_Snapsho__CADIS__17B170E9] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]        INT            NOT NULL,
    [CADIS_ROW_ID]           INT            NOT NULL,
    [InstrumentId]           NVARCHAR (MAX) NULL,
    [InstrumentName]         NVARCHAR (MAX) NULL,
    [IssuerId]               NVARCHAR (MAX) NULL,
    [IssuerName]             NVARCHAR (MAX) NULL,
    [ISIN]                   NVARCHAR (MAX) NULL,
    [CountryOfIssue]         NVARCHAR (MAX) NULL,
    [CountryOfIncorporation] NVARCHAR (MAX) NULL,
    [TotalVotingRights]      NVARCHAR (MAX) NULL,
    [ClassSharesOutstanding] NVARCHAR (MAX) NULL,
    [TotalSharesOutstanding] NVARCHAR (MAX) NULL,
    [MarketCap]              NVARCHAR (MAX) NULL,
    [InstrumentCurrency]     NVARCHAR (MAX) NULL,
    [VotesPerShare]          NVARCHAR (MAX) NULL,
    [Market]                 NVARCHAR (MAX) NULL,
    [Price]                  NVARCHAR (MAX) NULL,
    [CUSIP]                  NVARCHAR (MAX) NULL,
    [LotSize]                NVARCHAR (MAX) NULL,
    [Equity_InnerText]       NVARCHAR (MAX) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME       CONSTRAINT [DF__T_Snapsho__CADIS__18A59522] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME       CONSTRAINT [DF__T_Snapsho__CADIS__1999B95B] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)  CONSTRAINT [DF__T_Snapsho__CADIS__1A8DDD94] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT            CONSTRAINT [DF__T_Snapsho__CADIS__1B8201CD] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_T_Snapshot_Instruments_Equity_FUNDAPPS_OUT] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

