CREATE TABLE [dbo].[T_Snapshot_Portfolios_Portfolio_FUNDAPPS_OUT] (
    [CADIS_BATCH_ID]         INT            NOT NULL,
    [CADIS_MSG_ID]           INT            CONSTRAINT [DF__T_Snapsho__CADIS__33598B5E] DEFAULT ((1)) NOT NULL,
    [CADIS_PARENT_ID]        VARCHAR (8000) NOT NULL,
    [CADIS_ROW_ID]           INT            NOT NULL,
    [PortfolioId]            NVARCHAR (MAX) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME       CONSTRAINT [DF__T_Snapsho__CADIS__344DAF97] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME       CONSTRAINT [DF__T_Snapsho__CADIS__3541D3D0] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)  CONSTRAINT [DF__T_Snapsho__CADIS__3635F809] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT            CONSTRAINT [DF__T_Snapsho__CADIS__372A1C42] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_Snapsh__0E1EF4BF8ED2E745] PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC) WITH (FILLFACTOR = 90)
);

