CREATE TABLE [dbo].[T_SYSTEM_TABLE_SIZE_STORE] (
    [LOAD_DATE]              DATETIME        NOT NULL,
    [SCHEMA_NAME]            NVARCHAR (128)  NOT NULL,
    [TABLE_NAME]             NVARCHAR (128)  NOT NULL,
    [ROW_COUNT]              BIGINT          NOT NULL,
    [SIZE_KB]                BIGINT          NULL,
    [SIZE_MB]                DECIMAL (26, 6) NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME        CONSTRAINT [DF__T_SYSTEM___CADIS__40BCDCC6] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME        CONSTRAINT [DF__T_SYSTEM___CADIS__41B100FF] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50)   CONSTRAINT [DF__T_SYSTEM___CADIS__42A52538] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]  INT             CONSTRAINT [DF__T_SYSTEM___CADIS__43994971] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__T_SYSTEM__60BA7653F2730466] PRIMARY KEY CLUSTERED ([LOAD_DATE] ASC, [SCHEMA_NAME] ASC, [TABLE_NAME] ASC) WITH (FILLFACTOR = 90)
);

