CREATE TABLE [dbo].[T_TCA_ITG_RESPONSE_ALLOCATIONS_DEAGGREGATED_STAGING] (
    [FILE_NAME]                            VARCHAR (50)     NULL,
    [FILE_TYPE]                            VARCHAR (20)     NULL,
    [FILE_DATE]                            DATETIME         NULL,
    [IID]                                  BIGINT           IDENTITY (1, 1) NOT NULL,
    [OrderId]                              INT              NULL,
    [Child_Order_Id]                       INT              NULL,
    [Decision_Date_Time]                   DATETIME         NULL,
    [BrokerRouteTime]                      DATETIME         NULL,
    [FirstFill]                            DATETIME         NULL,
    [Release_Date_Time]                    DATETIME         NULL,
    [Trader_Date_Time]                     DATETIME         NULL,
    [Broker_Date_Time]                     DATETIME         NULL,
    [Trade_Date_Time]                      DATETIME         NULL,
    [Order_End_Date_Time]                  DATETIME         NULL,
    [Decision_End_Date_Time]               DATETIME         NULL,
    [5Day_Wtd_Avg_Spread_bps]              DECIMAL (38, 24) NULL,
    [BasePrice]                            DECIMAL (38, 24) NULL,
    [Broker]                               VARCHAR (15)     NULL,
    [5Day_Wtd_avg_Spread_Group]            VARCHAR (63)     NULL,
    [Account]                              VARCHAR (15)     NULL,
    [Commission_bps]                       VARCHAR (255)    NULL,
    [Country]                              VARCHAR (7)      NULL,
    [Currency]                             VARCHAR (7)      NULL,
    [DaysToCompletion]                     INT              NULL,
    [Filled_Percent_of_Daily_Volume]       DECIMAL (38, 24) NULL,
    [Filled_Percent_of_Interval_Volume]    DECIMAL (38, 24) NULL,
    [IntervalVolume]                       DECIMAL (38, 24) NULL,
    [Market_Cap_Group]                     VARCHAR (63)     NULL,
    [Market_Cap_Group_USD]                 DECIMAL (38, 24) NULL,
    [Order_Percent_of_Interval_Volume]     DECIMAL (38, 24) NULL,
    [Order_Percent_of_Median_Daily_Volume] DECIMAL (38, 24) NULL,
    [Order_Date_Volume]                    DECIMAL (38, 24) NULL,
    [OrderShares]                          DECIMAL (38, 24) NULL,
    [Child_Order_Size]                     DECIMAL (38, 24) NULL,
    [Order_Volatility_bps]                 DECIMAL (38, 24) NULL,
    [Orig_Price]                           DECIMAL (38, 24) NULL,
    [PM_Instructions]                      VARCHAR (255)    NULL,
    [PM_Order_Type]                        VARCHAR (255)    NULL,
    [Security_Name]                        VARCHAR (255)    NULL,
    [Side]                                 VARCHAR (7)      NULL,
    [Spreadgroup]                          VARCHAR (31)     NULL,
    [Spread_Percentile]                    INT              NULL,
    [percentSpread]                        DECIMAL (38, 24) NULL,
    [Volatility_Percentile]                INT              NULL,
    [Volume_Percentile]                    INT              NULL,
    [Symbol]                               VARCHAR (31)     NULL,
    [Ticker]                               VARCHAR (15)     NULL,
    [Total_Commission_in_Base_Currency]    VARCHAR (255)    NULL,
    [Total_Value]                          DECIMAL (38, 24) NULL,
    [Trade_Date_Volatility_bps]            DECIMAL (38, 24) NULL,
    [Trade_Date_Volume]                    INT              NULL,
    [Trade_Days]                           INT              NULL,
    [Trade_Shares]                         INT              NULL,
    [Trader]                               VARCHAR (15)     NULL,
    [TradingDesk]                          VARCHAR (255)    NULL,
    [Fees]                                 DECIMAL (38, 24) NULL,
    [origAuthorizationDate]                DATETIME         NULL,
    [origBrokerDate]                       DATETIME         NULL,
    [origDecisionDate]                     DATETIME         NULL,
    [origDecisionEndDate]                  DATETIME         NULL,
    [origOrderEndDateTime]                 DATETIME         NULL,
    [origOrderStartDateTime]               DATETIME         NULL,
    [origReleaseDate]                      DATETIME         NULL,
    [origTradeDateTime]                    DATETIME         NULL,
    [origTraderDate]                       DATETIME         NULL,
    [Dividend]                             VARCHAR (200)    NULL,
    [Dividend_CCY_Client]                  VARCHAR (200)    NULL,
    [Special_Dividend]                     VARCHAR (200)    NULL,
    [Special_Dividend_CCY_Client]          VARCHAR (200)    NULL,
    [Exchange_Fee]                         VARCHAR (200)    NULL,
    [Witholding_Tax]                       VARCHAR (200)    NULL,
    [Transfer_Tax]                         VARCHAR (200)    NULL,
    [Stamp_Duty]                           VARCHAR (200)    NULL,
    [Misc_Fees]                            VARCHAR (200)    NULL,
    [Aggregated_to]                        DECIMAL (38, 24) NULL,
    [Aggregated_from]                      DECIMAL (38, 24) NULL,
    [REASONCODE]                           VARCHAR (50)     NULL,
    [b1AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b1OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b1origCurrencyISO]                    VARCHAR (7)      NULL,
    [b1BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b1DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b1NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b1NetPctCst]                          DECIMAL (38, 24) NULL,
    [b1TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b1NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b1Name]                               VARCHAR (255)    NULL,
    [b1PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b1PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b1PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b1PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b1RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b2AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b2OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b2origCurrencyISO]                    VARCHAR (7)      NULL,
    [b2BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b2DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b2NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b2NetPctCst]                          DECIMAL (38, 24) NULL,
    [b2TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b2NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b2Name]                               VARCHAR (255)    NULL,
    [b2PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b2PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b2PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b2PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b2RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b3AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b3OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b3origCurrencyISO]                    VARCHAR (7)      NULL,
    [b3BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b3DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b3NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b3NetPctCst]                          DECIMAL (38, 24) NULL,
    [b3TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b3NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b3Name]                               VARCHAR (255)    NULL,
    [b3PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b3PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b3PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b3PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b3RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b4AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b4OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b4origCurrencyISO]                    VARCHAR (7)      NULL,
    [b4BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b4DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b4NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b4NetPctCst]                          DECIMAL (38, 24) NULL,
    [b4TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b4NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b4Name]                               VARCHAR (255)    NULL,
    [b4PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b4PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b4PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b4PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b4RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b5AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b5OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b5origCurrencyISO]                    VARCHAR (7)      NULL,
    [b5BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b5DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b5NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b5NetPctCst]                          DECIMAL (38, 24) NULL,
    [b5TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b5NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b5Name]                               VARCHAR (255)    NULL,
    [b5PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b5PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b5PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b5PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b5RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b6AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b6OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b6origCurrencyISO]                    VARCHAR (7)      NULL,
    [b6BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b6DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b6NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b6NetPctCst]                          DECIMAL (38, 24) NULL,
    [b6TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b6NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b6Name]                               VARCHAR (255)    NULL,
    [b6PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b6PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b6PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b6PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b6RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b7AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b7OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b7origCurrencyISO]                    VARCHAR (7)      NULL,
    [b7BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b7DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b7NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b7NetPctCst]                          DECIMAL (38, 24) NULL,
    [b7TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b7NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b7Name]                               VARCHAR (255)    NULL,
    [b7PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b7PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b7PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b7PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b7RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b8AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b8OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b8origCurrencyISO]                    VARCHAR (7)      NULL,
    [b8BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b8DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b8NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b8NetPctCst]                          DECIMAL (38, 24) NULL,
    [b8TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b8NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b8Name]                               VARCHAR (255)    NULL,
    [b8PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b8PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b8PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b8PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b8RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b9AdjBenchPrice]                      DECIMAL (38, 24) NULL,
    [b9OrigBenchPrice]                     DECIMAL (38, 24) NULL,
    [b9origCurrencyISO]                    VARCHAR (7)      NULL,
    [b9BaseBenchPrice]                     DECIMAL (38, 24) NULL,
    [b9DlrPerShrCst]                       DECIMAL (38, 24) NULL,
    [b9NetDlrPerShrCst]                    DECIMAL (38, 24) NULL,
    [b9NetPctCst]                          DECIMAL (38, 24) NULL,
    [b9TotalDlrCost]                       DECIMAL (38, 24) NULL,
    [b9NetRealDollar]                      DECIMAL (38, 24) NULL,
    [b9Name]                               VARCHAR (255)    NULL,
    [b9PreTradeCost]                       DECIMAL (38, 24) NULL,
    [b9PtaMomentumCmp]                     VARCHAR (200)    NULL,
    [b9PtaSprdCmp]                         VARCHAR (200)    NULL,
    [b9PtaVolCmpBps]                       VARCHAR (200)    NULL,
    [b9RealisedCostBps]                    DECIMAL (38, 24) NULL,
    [b10AdjBenchPrice]                     DECIMAL (38, 24) NULL,
    [b10OrigBenchPrice]                    DECIMAL (38, 24) NULL,
    [b10origCurrencyISO]                   VARCHAR (7)      NULL,
    [b10BaseBenchPrice]                    DECIMAL (38, 24) NULL,
    [b10DlrPerShrCst]                      DECIMAL (38, 24) NULL,
    [b10NetDlrPerShrCst]                   DECIMAL (38, 24) NULL,
    [b10NetPctCst]                         DECIMAL (38, 24) NULL,
    [b10TotalDlrCost]                      DECIMAL (38, 24) NULL,
    [b10NetRealDollar]                     DECIMAL (38, 24) NULL,
    [b10Name]                              VARCHAR (255)    NULL,
    [b10PreTradeCost]                      DECIMAL (38, 24) NULL,
    [b10PtaMomentumCmp]                    VARCHAR (200)    NULL,
    [b10PtaSprdCmp]                        VARCHAR (200)    NULL,
    [b10PtaVolCmpBps]                      VARCHAR (200)    NULL,
    [b10RealisedCostBps]                   DECIMAL (38, 24) NULL,
    [CADIS_SYSTEM_INSERTED]                DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                 DATETIME         DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]               NVARCHAR (50)    DEFAULT ('UNKNOWN') NULL,
    [Shares_By_Account]                    INT              NULL,
    PRIMARY KEY CLUSTERED ([IID] ASC) WITH (FILLFACTOR = 80)
);

