CREATE TABLE [dbo].[T_USER_GROUP] (
    [CLIENT]                 VARCHAR (50)  NOT NULL,
    [USER_NAME]              VARCHAR (250) NOT NULL,
    [GROUPNAME]              VARCHAR (150) NOT NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      CONSTRAINT [DF__T_USER_GR__CADIS__78002647] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      CONSTRAINT [DF__T_USER_GR__CADIS__78F44A80] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) CONSTRAINT [DF__T_USER_GR__CADIS__79E86EB9] DEFAULT ('UNKNOWN') NULL,
    CONSTRAINT [PK__T_USER_G__0F787A1AEA2747F4] PRIMARY KEY CLUSTERED ([CLIENT] ASC, [USER_NAME] ASC, [GROUPNAME] ASC) WITH (FILLFACTOR = 80)
);

