CREATE TABLE [dbo].[tmpStagingT_Security_Risk_Metrics] (
    [D_Date]                    DATE         NULL,
    [C_SECURITY]                VARCHAR (50) NULL,
    [PX_LAST]                   FLOAT (53)   NULL,
    [VOLUME]                    INT          NULL,
    [PE_RATIO]                  VARCHAR (50) NULL,
    [PX_TO_BOOK_RATIO]          VARCHAR (50) NULL,
    [FREE_CASH_FLOW_YIELD]      VARCHAR (50) NULL,
    [EQY_DVD_YLD_12M]           VARCHAR (50) NULL,
    [ PX_TO_SALES_RATIO]        VARCHAR (50) NULL,
    [ 3MO_CALL_IMP_VOL]         VARCHAR (50) NULL,
    [6MO_CALL_IMP_VOL]          VARCHAR (50) NULL,
    [REL_SHR_PX_MOMENTUM]       VARCHAR (50) NULL,
    [PX_CLOSE_1D]               VARCHAR (50) NULL,
    [TURNOVER]                  VARCHAR (50) NULL,
    [VWAP_AUTOMATED_VOLUME]     VARCHAR (50) NULL,
    [VWAP_LIT_VOLUME]           VARCHAR (50) NULL,
    [CFWEIAA LN]                VARCHAR (50) NULL,
    [CWHIAGA LN]                VARCHAR (50) NULL,
    [WPCT LN]                   VARCHAR (50) NULL,
    [CO1 Comdty]                VARCHAR (50) NULL,
    [XAU BGN Curncy]            VARCHAR (50) NULL,
    [HG1 COMB Comdty]           VARCHAR (50) NULL,
    [RBT1 COMB Comdty]          VARCHAR (50) NULL,
    [API2YR1]                   VARCHAR (50) NULL,
    [ASX]                       VARCHAR (50) NULL,
    [CRB RIND]                  VARCHAR (50) NULL,
    [EUCRBRDT]                  VARCHAR (50) NULL,
    [GUKG10]                    VARCHAR (50) NULL,
    [MCX]                       VARCHAR (50) NULL,
    [NKY]                       VARCHAR (50) NULL,
    [NYM1CNCN Index]            VARCHAR (50) NULL,
    [SHCOMP]                    VARCHAR (50) NULL,
    [SPX]                       VARCHAR (50) NULL,
    [SX5E]                      VARCHAR (50) NULL,
    [UKX]                       VARCHAR (50) NULL,
    [USGG10YR]                  VARCHAR (50) NULL,
    [GBPUSD]                    VARCHAR (50) NULL,
    [XAG BGN Curncy]            VARCHAR (50) NULL,
    [XPT BGN Curncy]            VARCHAR (50) NULL,
    [CURRENT_EV_TO_T12M_EBITDA] VARCHAR (50) NULL
);

