CREATE TABLE [dbo].[tmpT_Security_Risk_Metrics] (
    [D_DateGB]                  DATE         NULL,
    [D_Date]                    VARCHAR (50) NULL,
    [C_SECURITY]                VARCHAR (50) NULL,
    [PX_LAST]                   VARCHAR (50) NULL,
    [VOLUME]                    VARCHAR (50) NULL,
    [PE_RATIO]                  VARCHAR (50) NULL,
    [PX_TO_BOOK_RATIO]          VARCHAR (50) NULL,
    [FREE_CASH_FLOW_YIELD]      VARCHAR (50) NULL,
    [EQY_DVD_YLD_12M]           VARCHAR (50) NULL,
    [PX_TO_SALES_RATIO]         VARCHAR (50) NULL,
    [3MO_CALL_IMP_VOL]          VARCHAR (50) NULL,
    [6MO_CALL_IMP_VOL]          VARCHAR (50) NULL,
    [REL_SHR_PX_MOMENTUM]       VARCHAR (50) NULL,
    [PX_CLOSE_1D]               VARCHAR (50) NULL,
    [TURNOVER]                  VARCHAR (50) NULL,
    [VWAP_AUTOMATED_VOLUME]     VARCHAR (50) NULL,
    [VWAP_LIT_VOLUME]           VARCHAR (50) NULL,
    [CFWEIAA LN Equity]         VARCHAR (50) NULL,
    [CWHIAGA LN Equity]         VARCHAR (50) NULL,
    [WPCT LN Equity]            VARCHAR (50) NULL,
    [CO1 Comdty]                VARCHAR (50) NULL,
    [XAU BGN Curncy]            VARCHAR (50) NULL,
    [HG1 COMB Comdty]           VARCHAR (50) NULL,
    [RBT1 COMB Comdty]          VARCHAR (50) NULL,
    [API2YR1 Equity]            VARCHAR (50) NULL,
    [ASX Equity]                VARCHAR (50) NULL,
    [CRB RIND Equity]           VARCHAR (50) NULL,
    [EUCRBRDT Equity]           VARCHAR (50) NULL,
    [GUKG10 Equity]             VARCHAR (50) NULL,
    [MCX Index]                 VARCHAR (50) NULL,
    [NKY Index]                 VARCHAR (50) NULL,
    [NYM1CNCN Index]            VARCHAR (50) NULL,
    [SHCOMP Equity]             VARCHAR (50) NULL,
    [SPX Index]                 VARCHAR (50) NULL,
    [SX5E Equity]               VARCHAR (50) NULL,
    [UKX Index]                 VARCHAR (50) NULL,
    [USGG10YR Equity]           VARCHAR (50) NULL,
    [GBPUSD]                    VARCHAR (50) NULL,
    [XAG BGN Curncy]            VARCHAR (50) NULL,
    [XPT BGN Curncy]            VARCHAR (50) NULL,
    [CURRENT_EV_TO_T12M_EBITDA] VARCHAR (50) NULL
);

