CREATE TABLE [dbo].[zzz_T_MATRIX_CONTACT] (
    [SALESFORCE_CONTACT_ID]     VARCHAR (18)   NOT NULL,
    [MX_CONTACT_SIV_ID]         VARCHAR (100)  NOT NULL,
    [AS_AT_DATE]                DATETIME       NOT NULL,
    [SALESFORCE_ACCOUNT_ID]     VARCHAR (18)   NULL,
    [IS_PROSPECT]               VARCHAR (1)    NULL,
    [IS_UPDATE]                 VARCHAR (1)    NULL,
    [WF_MATRIX_CONTACT_ID]      VARCHAR (20)   NULL,
    [WF_CONTACT_SIV_ID]         VARCHAR (100)  NULL,
    [WF_ACCOUNT_SIV_ID]         VARCHAR (100)  NULL,
    [WF_ACCOUNT_FSR_FRN]        VARCHAR (20)   NULL,
    [WF_OWNER_ID]               VARCHAR (18)   NULL,
    [WF_OWNER_NAME]             VARCHAR (200)  NULL,
    [WF_SALUTATION]             VARCHAR (20)   NULL,
    [WF_FIRST_NAME]             VARCHAR (100)  NULL,
    [WF_LAST_NAME]              VARCHAR (100)  NULL,
    [WF_CONTACT_FSR_IRN]        VARCHAR (20)   NULL,
    [WF_TITLE]                  VARCHAR (100)  NULL,
    [WF_PHONE]                  VARCHAR (50)   NULL,
    [WF_MOBILEPHONE]            VARCHAR (50)   NULL,
    [WF_FAX]                    VARCHAR (50)   NULL,
    [WF_EMAIL]                  VARCHAR (128)  NULL,
    [WF_MAILING_STREET]         VARCHAR (1000) NULL,
    [WF_MAILING_CITY]           VARCHAR (100)  NULL,
    [WF_MAILING_STATE]          VARCHAR (100)  NULL,
    [WF_MAILING_POSTCODE]       VARCHAR (100)  NULL,
    [WF_MAILING_COUNTRY]        VARCHAR (100)  NULL,
    [WF_CONTACT_IS_CF1]         VARCHAR (1)    NULL,
    [WF_CONTACT_IS_CF2]         VARCHAR (1)    NULL,
    [WF_CONTACT_IS_CF3]         VARCHAR (1)    NULL,
    [WF_CONTACT_IS_CF4]         VARCHAR (1)    NULL,
    [WF_CONTACT_IS_CF10]        VARCHAR (1)    NULL,
    [WF_CONTACT_IS_CF11]        VARCHAR (1)    NULL,
    [WF_CONTACT_IS_CF30]        VARCHAR (1)    NULL,
    [WF_VERIFIED_BY]            VARCHAR (100)  NULL,
    [MX_MATRIX_CONTACT_ID]      VARCHAR (20)   NULL,
    [MX_ACCOUNT_SIV_ID]         VARCHAR (100)  NULL,
    [MX_ACCOUNT_FSR_FRN]        VARCHAR (20)   NULL,
    [MX_OWNER_ID]               VARCHAR (18)   NULL,
    [MX_OWNER_NAME]             VARCHAR (200)  NULL,
    [MX_SALUTATION]             VARCHAR (20)   NULL,
    [MX_FIRST_NAME]             VARCHAR (100)  NULL,
    [MX_LAST_NAME]              VARCHAR (100)  NULL,
    [MX_CONTACT_FSR_IRN]        VARCHAR (20)   NULL,
    [MX_TITLE]                  VARCHAR (100)  NULL,
    [MX_PHONE]                  VARCHAR (50)   NULL,
    [MX_MOBILE_PHONE]           VARCHAR (50)   NULL,
    [MX_FAX]                    VARCHAR (50)   NULL,
    [MX_EMAIL]                  VARCHAR (128)  NULL,
    [MX_MAILING_STREET]         VARCHAR (1000) NULL,
    [MX_MAILING_CITY]           VARCHAR (100)  NULL,
    [MX_MAILING_STATE]          VARCHAR (100)  NULL,
    [MX_MAILING_POSTCODE]       VARCHAR (100)  NULL,
    [MX_MAILING_COUNTRY]        VARCHAR (100)  NULL,
    [MX_CONTACT_IS_CF1]         VARCHAR (1)    NULL,
    [MX_CONTACT_IS_CF2]         VARCHAR (1)    NULL,
    [MX_CONTACT_IS_CF3]         VARCHAR (1)    NULL,
    [MX_CONTACT_IS_CF4]         VARCHAR (1)    NULL,
    [MX_CONTACT_IS_CF10]        VARCHAR (1)    NULL,
    [MX_CONTACT_IS_CF11]        VARCHAR (1)    NULL,
    [MX_CONTACT_IS_CF30]        VARCHAR (1)    NULL,
    [MX_VERIFIED_BY]            VARCHAR (100)  NULL,
    [MX_FCA_STATUS]             VARCHAR (50)   NULL,
    [MX_MFID_STATUS]            VARCHAR (100)  NULL,
    [FILE_NAME]                 VARCHAR (100)  NOT NULL,
    [FILE_DATE]                 DATETIME       NOT NULL,
    [FILE_TYPE]                 VARCHAR (20)   NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME       NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME       NULL,
    [CADIS_SYSTEM_CHANGEDBY]    VARCHAR (50)   NULL,
    [CADIS_SYSTEM_PRIORITY]     INT            NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION     NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME       NULL
);

