CREATE TABLE [dbo].[zzz_T_REF_TAB_LIST] (
    [TAB_LIST_ID]            INT           IDENTITY (1, 1) NOT NULL,
    [LIST_TYPE]              VARCHAR (50)  NULL,
    [LIST_VALUE]             VARCHAR (50)  NULL,
    [LIST_ORDER]             INT           NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL,
    [CADIS_SYSTEM_PRIORITY]  INT           NULL,
    [CADIS_SYSTEM_TIMESTAMP] ROWVERSION    NOT NULL
);

