CREATE TABLE [dbo].[zzz_T_REF_SALES_FORCE_POST_CODE_OWNER2] (
    [POST_CODE]              VARCHAR (20)  NOT NULL,
    [EmployeeBK]             VARCHAR (15)  NULL,
    [EmployeeIdBK]           VARCHAR (18)  NULL,
    [FullEmployeeBK]         VARCHAR (18)  NULL,
    [CADIS_SYSTEM_INSERTED]  DATETIME      NULL,
    [CADIS_SYSTEM_UPDATED]   DATETIME      NULL,
    [CADIS_SYSTEM_CHANGEDBY] NVARCHAR (50) NULL
);

