CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPPNSTATUS]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @DATA_CHANNEL_ID INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


