CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSVALUESOURCE_UPPREACCBA]
@TargetFieldName NVARCHAR (500), @FUND_SHORT_NAME VARCHAR (15), @POSITION_DATE DATETIME, @ASSET_SUB_CATEGORY VARCHAR (100), @CCY VARCHAR (3)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


