CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPPMFFLOW]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATETIME, @FLOW_TYPE VARCHAR (100), @RECOGNITION_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


