CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSVALUESOURCE_UPMSI]
@TargetFieldName NVARCHAR (500), @FUND_SHORT_NAME VARCHAR (20), @EDM_SEC_ID INT, @FUND_FISCAL_YEAR INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


