CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSVALUESOURCE_UPPMPOS]
@TargetFieldName NVARCHAR (500), @SOURCE VARCHAR (50), @POSITION_TYPE VARCHAR (50), @EDM_SEC_ID INT, @FUND_SHORT_NAME VARCHAR (15), @LONG_SHORT_IND VARCHAR (8), @POSITION_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


