CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPMSTFNDMK]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @SOURCE VARCHAR (50), @POSITION_TYPE VARCHAR (50), @FUND_SHORT_NAME VARCHAR (8000), @POSITION_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


