CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSVALUESOURCE_ENNTPOS]
@TargetFieldName NVARCHAR (500), @TRADE_DATE DATETIME, @POSITION DECIMAL (15, 2), @ACCOUNT VARCHAR (15), @PRICE DECIMAL (18, 2), @UNIQUE_BLOOMBERG_ID VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


