CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPMASACCBA]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @FUND_SHORT_NAME VARCHAR (15), @POSITION_DATE DATETIME, @ASSET_SUB_CATEGORY VARCHAR (100), @CCY VARCHAR (3)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


