CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPNTDVDIRR]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @ACCOUNT_NUMBER VARCHAR (50), @DATE DATETIME, @SEC_DESCRIPTION VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


