CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPDTHWPOS]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @MODEL_CODE VARCHAR (20), @INSTRUMENT_UII VARCHAR (12), @CURRENT_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


