CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPDTEXCEPT]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @SOURCE_TABLE VARCHAR (50), @SOURCE_KEY VARCHAR (50), @SOURCE_COLUMN VARCHAR (50), @EXCEPTION_CODE INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


