CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_OWNTEIFS]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @VALUATION_DATE DATETIME, @FUND_SHORT_NAME VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


