CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_OWNTEISS]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @VALUATION_DATE DATETIME, @FUND_SHORT_NAME VARCHAR (20), @EDM_SEC_ID INT, @FUND_FISCAL_YEAR INT, @FUND_FISCAL_QUARTER INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


