CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPMASDIPS]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @ASSET VARCHAR (10), @ORDER_REF INT, @VALUATION_POINT DATETIME, @ESTIMATED_ BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


