CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UMLGFF]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @FUND_SHORT_NAME VARCHAR (15), @TRADE_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


