CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSVALUESOURCE_OWNTEATYP]
@TargetFieldName NVARCHAR (500), @ACCOUNT_NUMBER VARCHAR (255), @SECURITY_NUMBER VARCHAR (255)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


