CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPPMSCFL]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @VALUATION_POINT_DATE DATETIME, @EXTERNAL_FUND_CODE VARCHAR (50), @FUND_REFERENCE VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


