CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSVALUESOURCE_UPSJPGFF]
@TargetFieldName NVARCHAR (500), @FUND_SHORT_NAME VARCHAR (15), @TRANSACTION_DATE DATETIME, @CURRENCY VARCHAR (20), @FUND_FLOW_TYPE VARCHAR (20), @FLOW_TYPE VARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


