CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPPLNOTIF]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @RUNID INT, @PROCESS_NAME VARCHAR (250), @PROCESS_TYPE VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


