CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPDRGLMSUM]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @ROW_ID BIGINT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


