CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPMFI]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @FUND_SHORT_NAME VARCHAR (20), @VALUATION_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


