CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPSJPHFFST]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @ROW_NUMBER INT, @TYPE VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


