CREATE PROCEDURE [CADIS_PROC].[spDCPROCESSAUDITREPORT_UPPREPRC]
@TargetFieldName NVARCHAR (500), @FromDate DATETIME, @EDM_SEC_ID INT, @PRICE_TYPE VARCHAR (50), @PRICE_DATE DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


