CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION119_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @Stage VARCHAR (50), @Stage_UPDATE BIT, @SummaryDetails VARCHAR (MAX), @SummaryDetails_UPDATE BIT, @ReporterRole VARCHAR (50), @ReporterRole_UPDATE BIT, @AssigneeRole VARCHAR (50), @AssigneeRole_UPDATE BIT, @Description VARCHAR (MAX), @Description_UPDATE BIT, @DueDate DATETIME, @DueDate_UPDATE BIT, @IsActive BIT, @IsActive_UPDATE BIT, @JiraEpicKey VARCHAR (2000), @JiraEpicKey_UPDATE BIT, @Labels VARCHAR (2000), @Labels_UPDATE BIT, @StoryPoints INT, @StoryPoints_UPDATE BIT, @IssueType VARCHAR (50), @IssueType_UPDATE BIT, @ClientTakeOnTasksLastModifiedDatetime DATETIME, @ClientTakeOnTasksLastModifiedDatetime_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


