CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION1_INBOXSELROWNUMBER]
@RowNum INT OUTPUT, @WhereSQL NVARCHAR (MAX), @Username NVARCHAR (250), @Sort NVARCHAR (30), @SOURCE VARCHAR (30), @ENTITY VARCHAR (50), @DESCRIPTION VARCHAR (150), @DIRECTION VARCHAR (3), @CURRENT_SLA_DATE DATETIME, @EXPECTED_DELIVERY_TIME DATETIME
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


