CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION109_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @UnquotedCompanyId INT, @UnquotedCompanyId_UPDATE BIT, @ValuationReviewMeetingDate DATETIME, @ValuationReviewMeetingDate_UPDATE BIT, @BoxUrl NVARCHAR (2000), @BoxUrl_UPDATE BIT, @WorkflowVersionGUID UNIQUEIDENTIFIER, @WorkflowVersionGUID_UPDATE BIT, @JoinGUID UNIQUEIDENTIFIER, @JoinGUID_UPDATE BIT, @ValuationReviewCreatedByPersonId SMALLINT, @ValuationReviewCreatedByPersonId_UPDATE BIT, @ValuationReviewModifiedDate DATETIME, @ValuationReviewModifiedDate_UPDATE BIT, @ValuationReviewLastModifiedByPersonId SMALLINT, @ValuationReviewLastModifiedByPersonId_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


