CREATE PROCEDURE [CADIS_PROC].[SPDG_FUNCTION112_INBOXINS]
@Inserted DATETIME, @ChangedBy NVARCHAR (256), @ValidationInfo NVARCHAR (4000), @UnquotedCompanyId INT, @CADIS_SYSTEM_INSERTED DATETIME, @CADIS_SYSTEM_INSERTED_UPDATE BIT, @CADIS_SYSTEM_UPDATED DATETIME, @CADIS_SYSTEM_UPDATED_UPDATE BIT, @CADIS_SYSTEM_CHANGEDBY NVARCHAR (50), @CADIS_SYSTEM_CHANGEDBY_UPDATE BIT, @ComplianceChecksComplete BIT, @ComplianceChecksComplete_UPDATE BIT, @InvestmentTrustBoardReporting BIT, @InvestmentTrustBoardReporting_UPDATE BIT, @InitialInvestmentDate DATETIME, @InitialInvestmentDate_UPDATE BIT, @CADIS_SYSTEM_LASTMODIFIED DATETIME, @CADIS_SYSTEM_LASTMODIFIED_UPDATE BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


