CREATE TABLE [Sales].[ClientTakeOnEvents] (
    [ClientTakeOnEventId]                   INT              IDENTITY (1, 1) NOT NULL,
    [ClientTakeOnId]                        INT              NOT NULL,
    [EventTypeId]                           SMALLINT         NOT NULL,
    [RFPId]                                 INT              NULL,
    [SubmittedByPersonId]                   SMALLINT         NULL,
    [SubmittedDate]                         DATETIME         NULL,
    [EventDetails]                          VARCHAR (MAX)    NULL,
    [EventDate]                             DATETIME         NULL,
    [ReviewComments]                        VARCHAR (MAX)    NULL,
    [EventTrueFalse]                        BIT              NULL,
    [DepartmentId]                          SMALLINT         NULL,
    [JiraSubTaskKey]                        VARCHAR (128)    NULL,
    [JiraEpicKey]                           VARCHAR (128)    NULL,
    [DocumentationFolderLink]               VARCHAR (2000)   NULL,
    [JoinGUID]                              UNIQUEIDENTIFIER NOT NULL,
    [ClientTakeOnEventCreationDate]         DATETIME         CONSTRAINT [DF_CTOE_CTOECD] DEFAULT (getdate()) NOT NULL,
    [ClientTakeOnEventLastModifiedDatetime] DATETIME         CONSTRAINT [DF_CTOE_CTOELMD] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]                 DATETIME         CONSTRAINT [DF_CTOE_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                  DATETIME         CONSTRAINT [DF_CTOE_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                NVARCHAR (50)    CONSTRAINT [DF_CTOE_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                 INT              CONSTRAINT [DF_CTOE_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]             DATETIME         CONSTRAINT [DF_CTOE_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKClientTakeOnEvents] PRIMARY KEY CLUSTERED ([ClientTakeOnEventId] ASC),
    CONSTRAINT [ClientTakeOnEventsClientTakeOnId] FOREIGN KEY ([ClientTakeOnId]) REFERENCES [Sales].[ClientTakeOnRegister] ([ClientTakeOnId]),
    CONSTRAINT [ClientTakeOnEventsDepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Core].[Departments] ([DepartmentId]),
    CONSTRAINT [ClientTakeOnEventsEventTypeId] FOREIGN KEY ([EventTypeId]) REFERENCES [Sales].[ClientTakeOnEventTypes] ([ClientTakeOnEventTypeId]),
    CONSTRAINT [ClientTakeOnEventsRFPId] FOREIGN KEY ([RFPId]) REFERENCES [Sales].[RFPRegister] ([RFPId]),
    CONSTRAINT [ClientTakeOnEventsSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

