CREATE TABLE [Sales].[ClientBilling] (
    [ClientBillingId]                   INT              IDENTITY (1, 1) NOT NULL,
    [MandateId]                         INT              NOT NULL,
    [InvoiceDueDate]                    DATE             NOT NULL,
    [InvoiceReceivedDate]               DATE             NULL,
    [Amount]                            DECIMAL (19, 2)  NULL,
    [VATAmount]                         DECIMAL (19, 2)  NULL,
    [GrossAmountReceived]               DECIMAL (19, 2)  NULL,
    [SubmittedByPersonId]               SMALLINT         CONSTRAINT [DF_CB_CBSP] DEFAULT ((-1)) NOT NULL,
    [SubmittedDate]                     DATETIME         CONSTRAINT [DF_CB_CBSD] DEFAULT (getdate()) NOT NULL,
    [ReviewedByPersonId]                SMALLINT         CONSTRAINT [DF_CB_CBRP] DEFAULT ((-1)) NOT NULL,
    [ReviewedDate]                      DATETIME         CONSTRAINT [DF_CB_CBRD] DEFAULT (getdate()) NOT NULL,
    [StatusId]                          SMALLINT         NOT NULL,
    [PaymentDueDate]                    DATETIME         NULL,
    [PaymentReceivedDate]               DATETIME         NULL,
    [OpsTaskJiraKey]                    VARCHAR (128)    NULL,
    [ReconTaskJiraKey]                  VARCHAR (128)    NULL,
    [IsActive]                          BIT              NULL,
    [DocumentationFolderLink]           VARCHAR (2000)   NULL,
    [JoinGUID]                          UNIQUEIDENTIFIER NOT NULL,
    [ClientBillingCreationDatetime]     DATETIME         CONSTRAINT [DF_CB_CBCDT] DEFAULT (getdate()) NOT NULL,
    [ClientBillingLastModifiedDatetime] DATETIME         CONSTRAINT [DF_CB_CBLMDT] DEFAULT (getdate()) NOT NULL,
    [ReconParentJiraKey]                VARCHAR (128)    NULL,
    [CADIS_SYSTEM_INSERTED]             DATETIME         CONSTRAINT [DF_CB_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]              DATETIME         CONSTRAINT [DF_CB_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]            NVARCHAR (50)    CONSTRAINT [DF_CB_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]             INT              CONSTRAINT [DF_CB_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]            ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]         DATETIME         CONSTRAINT [DF_CB_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKClientBilling] PRIMARY KEY CLUSTERED ([ClientBillingId] ASC),
    CONSTRAINT [ClientBillingMandateId] FOREIGN KEY ([MandateId]) REFERENCES [Investment].[Mandates] ([MandateId]),
    CONSTRAINT [ClientBillingReviewedByPersonId] FOREIGN KEY ([ReviewedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [ClientBillingStatusId] FOREIGN KEY ([StatusId]) REFERENCES [Sales].[ClientBillingStatuses] ([ClientBillingStatusId]),
    CONSTRAINT [ClientBillingSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

