CREATE TABLE [Sales].[FinancialClarity] (
    [As_at_Date]                                   DATE            NOT NULL,
    [MTX_ACCOUNT_SIV_ID]                           NVARCHAR (256)  NOT NULL,
    [Matrix_Outlet_ID]                             NVARCHAR (15)   NOT NULL,
    [SalesforceAccountId]                          NVARCHAR (18)   NULL,
    [Outlet_Own_Gross_Sales]                       DECIMAL (18, 2) NULL,
    [Outlet_Market_Gross_Sales]                    DECIMAL (18, 2) NULL,
    [Outlet_Own_Net_Sales]                         DECIMAL (18, 2) NULL,
    [Outlet_Market_Net_Sales]                      DECIMAL (18, 2) NULL,
    [UK_Equity_Income_Own_Gross_Sales]             DECIMAL (18, 2) NULL,
    [UK_Equity_Income_Market_Gross_Sales]          DECIMAL (18, 2) NULL,
    [UK_Equity_Income_Own_Net_Sales]               DECIMAL (18, 2) NULL,
    [UK_Equity_Income_Market_Net_Sales]            DECIMAL (18, 2) NULL,
    [Specialist_Own_Gross_Sales]                   DECIMAL (18, 2) NULL,
    [Specialist_Market_Gross_Sales]                DECIMAL (18, 2) NULL,
    [Specialist_Own_Net_Sales]                     DECIMAL (18, 2) NULL,
    [Specialist_Market_Net_Sales]                  DECIMAL (18, 2) NULL,
    [UK_Equity_and_Bond_Income_Own_Gross_Sales]    DECIMAL (18, 2) NULL,
    [UK_Equity_and_Bond_Income_Market_Gross_Sales] DECIMAL (18, 2) NULL,
    [UK_Equity_and_Bond_Income_Own_Net_Sales]      DECIMAL (18, 2) NULL,
    [UK_Equity_and_Bond_Income_Market_Net_Sales]   DECIMAL (18, 2) NULL,
    [UK_All_Companies_Own_Gross_Sales]             DECIMAL (18, 2) NULL,
    [UK_All_Companies_Market_Gross_Sales]          DECIMAL (18, 2) NULL,
    [UK_All_Companies_Own_Net_Sales]               DECIMAL (18, 2) NULL,
    [UK_All_Companies_Market_Net_Sales]            DECIMAL (18, 2) NULL,
    [Global_Equity_Income_Own_Gross_Sales]         DECIMAL (18, 2) NULL,
    [Global_Equity_Income_Market_Gross_Sales]      DECIMAL (18, 2) NULL,
    [Global_Equity_Income_Own_Net_Sales]           DECIMAL (18, 2) NULL,
    [Global_Equity_Income_Market_Net_Sales]        DECIMAL (18, 2) NULL,
    [CADIS_SYSTEM_INSERTED]                        DATETIME        CONSTRAINT [DF_fc_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]                         DATETIME        CONSTRAINT [DF_fc_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]                       NVARCHAR (50)   CONSTRAINT [DF_fc_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]                        INT             CONSTRAINT [DF_fc_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]                       ROWVERSION      NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]                    DATETIME        CONSTRAINT [DF_fc_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKFinancialClarity] PRIMARY KEY CLUSTERED ([As_at_Date] DESC, [Matrix_Outlet_ID] ASC)
);

