CREATE TABLE [Sales].[RFPRegister] (
    [RFPId]                           INT              IDENTITY (1, 1) NOT NULL,
    [ClientId]                        INT              NOT NULL,
    [RFPName]                         VARCHAR (255)    NOT NULL,
    [RelationshipManagerId]           SMALLINT         NULL,
    [FirstDraftDeadlineDate]          DATE             NULL,
    [FinalDraftDeadlineDate]          DATE             NULL,
    [RFPDeadlineDate]                 DATE             NULL,
    [RFPStatus]                       VARCHAR (50)     NULL,
    [FinalDraftLink]                  VARCHAR (2000)   NULL,
    [RelationshipManagerNotes]        VARCHAR (MAX)    NULL,
    [ClientTakeOnYesNo]               BIT              NULL,
    [SubmittedByPersonId]             SMALLINT         CONSTRAINT [DF_RFPR_RFPRSP] DEFAULT ((-1)) NOT NULL,
    [ApprovedByPersonId]              SMALLINT         NULL,
    [JiraTaskKey]                     VARCHAR (128)    NULL,
    [HeadOfSalesPersonId]             SMALLINT         NULL,
    [ProjectId]                       INT              NULL,
    [DocumentationFolderLink]         VARCHAR (2000)   NULL,
    [DocumentationFolderLink2]        VARCHAR (2000)   NULL,
    [JoinGUID]                        UNIQUEIDENTIFIER NOT NULL,
    [RFPRegisterCreationDatetime]     DATETIME         CONSTRAINT [DF_RFPR_RFPRCDT] DEFAULT (getdate()) NOT NULL,
    [RFPRegisterLastModifiedDatetime] DATETIME         CONSTRAINT [DF_RFPR_RFPRLMDT] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PKRFPRegister] PRIMARY KEY CLUSTERED ([RFPId] ASC),
    CONSTRAINT [RFPRegisterApprovedByPersonId] FOREIGN KEY ([ApprovedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [RFPRegisterClientId] FOREIGN KEY ([ClientId]) REFERENCES [Sales].[ClientRegister] ([ClientId]),
    CONSTRAINT [RFPRegisterHeadOfSalesPersonId] FOREIGN KEY ([HeadOfSalesPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [RFPRegisterProjectId] FOREIGN KEY ([ProjectId]) REFERENCES [Organisation].[NewProjectsRegister] ([ProjectId]),
    CONSTRAINT [RFPRegisterRelationshipManagerId] FOREIGN KEY ([RelationshipManagerId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [RFPRegisterSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

