CREATE TABLE [Audit].[ControlLogFrequency] (
    [ControlLogFrequencyId]     SMALLINT      IDENTITY (1, 1) NOT NULL,
    [FrequencyName]             VARCHAR (128) NOT NULL,
    [DisplayOrder]              SMALLINT      NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF_CLF_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF_CLF_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF_CLF_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF_CLF_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF_CLF_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKControlLogFrequency] PRIMARY KEY CLUSTERED ([FrequencyName] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UXIControlLogFrequency]
    ON [Audit].[ControlLogFrequency]([ControlLogFrequencyId] ASC);

