CREATE TABLE [Risk].[RiskProbability] (
    [RiskProbabilityId]         SMALLINT      IDENTITY (1, 1) NOT NULL,
    [ProbabilityName]           VARCHAR (25)  NOT NULL,
    [ProbabilityScore]          SMALLINT      NOT NULL,
    [CreatedDate]               DATETIME      CONSTRAINT [DT_RP_CDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]     DATETIME      CONSTRAINT [DF_RP_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]      DATETIME      CONSTRAINT [DF_RP_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]    NVARCHAR (50) CONSTRAINT [DF_RP_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]     INT           CONSTRAINT [DF_RP_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]    ROWVERSION    NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED] DATETIME      CONSTRAINT [DF_RP_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKRiskProbability] PRIMARY KEY CLUSTERED ([RiskProbabilityId] ASC)
);

