CREATE TABLE [Risk].[RiskRegister] (
    [RiskRegisterId]                     INT              IDENTITY (1, 1) NOT NULL,
    [SubCategoryId]                      SMALLINT         NOT NULL,
    [IdentifiedByPersonId]               SMALLINT         NOT NULL,
    [RiskEvent]                          NVARCHAR (MAX)   NOT NULL,
    [RiskCause]                          NVARCHAR (MAX)   NOT NULL,
    [MitigationAndControls]              NVARCHAR (MAX)   NULL,
    [GrossImpactId]                      SMALLINT         NULL,
    [GrossProbabilityId]                 SMALLINT         NULL,
    [NetImpactId]                        SMALLINT         NULL,
    [NetProbabilityId]                   SMALLINT         NULL,
    [ImpactOnICAAPYesNo]                 BIT              NULL,
    [MonetaryImpact]                     DECIMAL (19, 2)  NULL,
    [Liklihoodfactor]                    DECIMAL (5, 2)   NULL,
    [FrequencyRating]                    INT              NULL,
    [FinLossWorstCaseRating]             INT              NULL,
    [FinLossBaseCaseRating]              INT              NULL,
    [ActionRequired]                     VARCHAR (MAX)    NULL,
    [ActionRoleId]                       SMALLINT         NULL,
    [ActionPersonId]                     SMALLINT         NULL,
    [ActionDeadlineDate]                 DATETIME         NULL,
    [ICAAPComments]                      VARCHAR (MAX)    NULL,
    [RiskReviewed]                       BIT              CONSTRAINT [DT_RR_RR] DEFAULT ((0)) NOT NULL,
    [RiskStatus]                         VARCHAR (128)    NULL,
    [ReviewStatus]                       VARCHAR (128)    NULL,
    [RiskOccurrenceDate]                 DATETIME         NULL,
    [SalesForceThirdPartyServiceIssueID] VARCHAR (25)     NULL,
    [HORJiraKey]                         VARCHAR (128)    NULL,
    [ROJiraKey]                          VARCHAR (128)    NULL,
    [RiskRegisterCreationDate]           DATETIME         CONSTRAINT [DT_RR_RRCDT] DEFAULT (getdate()) NOT NULL,
    [WorkflowVersionGUID]                UNIQUEIDENTIFIER NULL,
    [JoinGUID]                           UNIQUEIDENTIFIER NOT NULL,
    [CADIS_SYSTEM_INSERTED]              DATETIME         CONSTRAINT [DF_RR_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]               DATETIME         CONSTRAINT [DF_RR_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]             NVARCHAR (50)    CONSTRAINT [DF_RR_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]              INT              CONSTRAINT [DF_RR_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]             ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]          DATETIME         CONSTRAINT [DF_RR_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [XPKRiskRegisterId] PRIMARY KEY CLUSTERED ([RiskRegisterId] ASC),
    CONSTRAINT [RiskRegisterActionPersonId] FOREIGN KEY ([ActionPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [RiskRegisterActionRoleId] FOREIGN KEY ([ActionRoleId]) REFERENCES [Core].[Roles] ([RoleId]),
    CONSTRAINT [RiskRegisterGrossImpactId] FOREIGN KEY ([GrossImpactId]) REFERENCES [Risk].[RiskImpact] ([RiskImpactId]),
    CONSTRAINT [RiskRegisterGrossProbabilityId] FOREIGN KEY ([GrossProbabilityId]) REFERENCES [Risk].[RiskProbability] ([RiskProbabilityId]),
    CONSTRAINT [RiskRegisterNetImpactId] FOREIGN KEY ([NetImpactId]) REFERENCES [Risk].[RiskImpact] ([RiskImpactId]),
    CONSTRAINT [RiskRegisterNetProbabilityId] FOREIGN KEY ([NetProbabilityId]) REFERENCES [Risk].[RiskProbability] ([RiskProbabilityId]),
    CONSTRAINT [RiskRegisterPersonId] FOREIGN KEY ([IdentifiedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [RiskRegisterSubCategoryId] FOREIGN KEY ([SubCategoryId]) REFERENCES [Risk].[SubCategories] ([SubCategoryId])
);

