CREATE TABLE [Risk].[RiskLossOccurrence] (
    [LossOccurrenceId]                   INT              IDENTITY (1, 1) NOT NULL,
    [Status]                             VARCHAR (50)     NULL,
    [RiskLossCause]                      VARCHAR (255)    NULL,
    [DateOccurred]                       DATETIME         NULL,
    [DateIdentified]                     DATETIME         NULL,
    [ImpactType]                         VARCHAR (50)     NULL,
    [OccurrenceLocation]                 VARCHAR (50)     NULL,
    [IsActive]                           BIT              NULL,
    [SubmittedByPersonId]                SMALLINT         NOT NULL,
    [ReviewedByPersonId]                 SMALLINT         NULL,
    [MonetaryGainLossAmount]             VARCHAR (50)     NULL,
    [ImpactRecoveries]                   VARCHAR (255)    NULL,
    [ImpactDetails]                      NVARCHAR (MAX)   NULL,
    [FollowUpAction]                     VARCHAR (255)    NULL,
    [RiskRegisterId]                     INT              NULL,
    [BusinessAreasAffected]              NVARCHAR (MAX)   NULL,
    [EventDetails]                       NVARCHAR (MAX)   NULL,
    [ImmediateRemedialAction]            NVARCHAR (MAX)   NULL,
    [JiraTaskKey]                        VARCHAR (128)    NULL,
    [JiraTaskKey2]                       VARCHAR (128)    NULL,
    [IsNearMiss]                         BIT              NULL,
    [DocumentationFolderLink]            VARCHAR (2000)   NOT NULL,
    [JoinGUID]                           UNIQUEIDENTIFIER NOT NULL,
    [LossOccurrenceCreationDatetime]     DATETIME         CONSTRAINT [DF_RLO_RLOCDT] DEFAULT (getdate()) NOT NULL,
    [LossOccurrenceLastModifiedDatetime] DATETIME         CONSTRAINT [DF_RLO_RLOLMDT] DEFAULT (getdate()) NOT NULL,
    [CADIS_SYSTEM_INSERTED]              DATETIME         CONSTRAINT [DF_RLO_CSI] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_UPDATED]               DATETIME         CONSTRAINT [DF_RLO_CSU] DEFAULT (getdate()) NULL,
    [CADIS_SYSTEM_CHANGEDBY]             NVARCHAR (50)    CONSTRAINT [DF_RLO_CSCB] DEFAULT ('UNKNOWN') NULL,
    [CADIS_SYSTEM_PRIORITY]              INT              CONSTRAINT [DF_RLO_CSP] DEFAULT ((1)) NULL,
    [CADIS_SYSTEM_TIMESTAMP]             ROWVERSION       NOT NULL,
    [CADIS_SYSTEM_LASTMODIFIED]          DATETIME         CONSTRAINT [DF_RLO_CSL] DEFAULT (getdate()) NULL,
    CONSTRAINT [PKLossOccurrence] PRIMARY KEY CLUSTERED ([LossOccurrenceId] ASC),
    CONSTRAINT [RiskLossOccurrenceReviewedByPersonId] FOREIGN KEY ([ReviewedByPersonId]) REFERENCES [Core].[Persons] ([PersonId]),
    CONSTRAINT [RiskLossOccurrenceRiskRegisterId] FOREIGN KEY ([RiskRegisterId]) REFERENCES [Risk].[RiskRegister] ([RiskRegisterId]),
    CONSTRAINT [RiskLossOccurrenceSubmittedByPersonId] FOREIGN KEY ([SubmittedByPersonId]) REFERENCES [Core].[Persons] ([PersonId])
);

