CREATE TABLE [CADIS].[DC_EXSFAO_ACCOUNT_CBUF] (
    [SfAccountId]        NVARCHAR (1000) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT             NULL,
    PRIMARY KEY CLUSTERED ([SfAccountId] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID158]
    ON [CADIS].[DC_EXSFAO_ACCOUNT_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

