CREATE TABLE [CADIS].[DC_EXSFAO_ACCOUNT_MX_CBUF] (
    [SfAccountId]        VARCHAR (18) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([SfAccountId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID171]
    ON [CADIS].[DC_EXSFAO_ACCOUNT_MX_CBUF]([CADIS_SYSTEM_RUNID] ASC);

