CREATE TABLE [CADIS].[DC_ISS_CTR_ISS_CTR_CBUF] (
    [ID059]              VARCHAR (250) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT           NULL,
    PRIMARY KEY CLUSTERED ([ID059] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID218]
    ON [CADIS].[DC_ISS_CTR_ISS_CTR_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

