CREATE TABLE [CADIS].[DC_ISS_CTR_ISS_CBUF] (
    [UNIQUE_BLOOMBERG_ID] VARCHAR (30) NOT NULL,
    [CADIS_SYSTEM_RUNID]  INT          NULL,
    PRIMARY KEY CLUSTERED ([UNIQUE_BLOOMBERG_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID219]
    ON [CADIS].[DC_ISS_CTR_ISS_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

