CREATE TABLE [CADIS].[DC_OSTCOV_CONTACT_CBUF] (
    [SfContactId]        NVARCHAR (1000) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT             NULL,
    PRIMARY KEY CLUSTERED ([SfContactId] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID168]
    ON [CADIS].[DC_OSTCOV_CONTACT_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

