CREATE TABLE [CADIS].[DC_OWNTEISS_VALID_CBUF] (
    [VALUATION_DATE]     DATETIME     NOT NULL,
    [FUND_SHORT_NAME]    VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]         INT          NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID256]
    ON [CADIS].[DC_OWNTEISS_VALID_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

