CREATE TABLE [CADIS].[DC_OWNTEISTG_TYPED_CBUF] (
    [ID]                 INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID233]
    ON [CADIS].[DC_OWNTEISTG_TYPED_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

