CREATE TABLE [CADIS].[DC_OWNTEATYP_TYPED_CBUF] (
    [ACCOUNT_NUMBER]     VARCHAR (255) NOT NULL,
    [SECURITY_NUMBER]    VARCHAR (255) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT           NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [SECURITY_NUMBER] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID239]
    ON [CADIS].[DC_OWNTEATYP_TYPED_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

