CREATE TABLE [CADIS].[DC_OVSTPCO_OVERRIDE_CBUF] (
    [SfAccountId]        VARCHAR (18) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([SfAccountId] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID191]
    ON [CADIS].[DC_OVSTPCO_OVERRIDE_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

