CREATE TABLE [CADIS].[DC_OVSTAMO_OVERRIDE_CBUF] (
    [SfAccountId]        VARCHAR (18) NOT NULL,
    [Sector]             VARCHAR (10) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([SfAccountId] ASC, [Sector] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID169]
    ON [CADIS].[DC_OVSTAMO_OVERRIDE_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

