CREATE TABLE [CADIS].[DC_OWNTEISTG_VALID_CBUF] (
    [ACCOUNT NUMBER]     VARCHAR (255) NOT NULL,
    [SECURITY NUMBER]    VARCHAR (255) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT           NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT NUMBER] ASC, [SECURITY NUMBER] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID233]
    ON [CADIS].[DC_OWNTEISTG_VALID_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

