CREATE TABLE [CADIS].[DC_PRESECEQ_SECURITY_CBUF] (
    [UNIQUE_IDENTIFIER]  VARCHAR (30) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([UNIQUE_IDENTIFIER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID39]
    ON [CADIS].[DC_PRESECEQ_SECURITY_CBUF]([CADIS_SYSTEM_RUNID] ASC);

