CREATE TABLE [CADIS].[DC_PMFFLOW_MLFF_CBUF] (
    [FUND_SHORT_NAME]    VARCHAR (15) NOT NULL,
    [TRADE_DATE]         DATETIME     NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [TRADE_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID182]
    ON [CADIS].[DC_PMFFLOW_MLFF_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

