CREATE TABLE [CADIS].[DC_PREMASSEC_HWSEC_CBUF] (
    [EDM_SEC_ID]         INT          NOT NULL,
    [IDENTIFIER]         VARCHAR (50) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC, [IDENTIFIER] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID211]
    ON [CADIS].[DC_PREMASSEC_HWSEC_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

