CREATE TABLE [CADIS].[DC_PREMASSEC_SECURITY_CBUF] (
    [CADIS Id]           INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([CADIS Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID40]
    ON [CADIS].[DC_PREMASSEC_SECURITY_CBUF]([CADIS_SYSTEM_RUNID] ASC);

