CREATE TABLE [CADIS].[DC_PRESECEQ_BPS_CBUF] (
    [IDENTIFIER]         VARCHAR (50) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([IDENTIFIER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID134]
    ON [CADIS].[DC_PRESECEQ_BPS_CBUF]([CADIS_SYSTEM_RUNID] ASC);

