CREATE TABLE [CADIS].[DC_UPPMPOS_NTPOS_CBUF] (
    [TRADE_DATE]          DATETIME        NOT NULL,
    [POSITION]            DECIMAL (15, 2) NOT NULL,
    [ACCOUNT]             VARCHAR (15)    NOT NULL,
    [PRICE]               DECIMAL (18, 2) NOT NULL,
    [UNIQUE_BLOOMBERG_ID] VARCHAR (20)    NOT NULL,
    [CADIS_SYSTEM_RUNID]  INT             NULL,
    PRIMARY KEY CLUSTERED ([TRADE_DATE] ASC, [POSITION] ASC, [ACCOUNT] ASC, [PRICE] ASC, [UNIQUE_BLOOMBERG_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID25]
    ON [CADIS].[DC_UPPMPOS_NTPOS_CBUF]([CADIS_SYSTEM_RUNID] ASC);

