CREATE TABLE [CADIS].[DC_UPMSTFX_PREMASTER_CBUF] (
    [FXRATE_ID]          VARCHAR (16) NOT NULL,
    [DATE]               DATETIME     NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([FXRATE_ID] ASC, [DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID15]
    ON [CADIS].[DC_UPMSTFX_PREMASTER_CBUF]([CADIS_SYSTEM_RUNID] ASC);

