CREATE TABLE [CADIS].[DC_UPFNDEXCEP_STAGE_CBUF] (
    [SOURCE_TABLE]       VARCHAR (50) NOT NULL,
    [SOURCE_KEY_1]       VARCHAR (50) NOT NULL,
    [SOURCE_KEY_2]       VARCHAR (20) NOT NULL,
    [SOURCE_COLUMN]      VARCHAR (50) NOT NULL,
    [EXCEPTION_CODE]     INT          NOT NULL,
    [EXCEPTION_DATE]     DATETIME     NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([SOURCE_TABLE] ASC, [SOURCE_KEY_1] ASC, [SOURCE_KEY_2] ASC, [SOURCE_COLUMN] ASC, [EXCEPTION_CODE] ASC, [EXCEPTION_DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID84]
    ON [CADIS].[DC_UPFNDEXCEP_STAGE_CBUF]([CADIS_SYSTEM_RUNID] ASC);

