CREATE TABLE [CADIS].[DC_UPPRNOTIF_EXISTING_CBUF] (
    [DATA_CHANNEL_ID]    INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([DATA_CHANNEL_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID4]
    ON [CADIS].[DC_UPPRNOTIF_EXISTING_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

