CREATE TABLE [CADIS].[DC_UPBPSDIVHA_STAGE_CBUF] (
    [STOCK]              VARCHAR (20) NOT NULL,
    [ROW_ID]             INT          NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([STOCK] ASC, [ROW_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID178]
    ON [CADIS].[DC_UPBPSDIVHA_STAGE_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

