CREATE TABLE [CADIS].[DC_UPPMFI_NT_FND_INC_CBUF] (
    [VALUATION_DATE]     DATETIME     NOT NULL,
    [FUND_SHORT_NAME]    VARCHAR (20) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_SHORT_NAME] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID250]
    ON [CADIS].[DC_UPPMFI_NT_FND_INC_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

