CREATE TABLE [CADIS].[DC_UPPMSCFL_LOAD_CBUF] (
    [VALUATION_POINT_DATE] DATETIME     NOT NULL,
    [EXTERNAL_FUND_CODE]   VARCHAR (50) NOT NULL,
    [FUND_REFERENCE]       VARCHAR (20) NOT NULL,
    [CADIS_SYSTEM_RUNID]   INT          NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_POINT_DATE] ASC, [EXTERNAL_FUND_CODE] ASC, [FUND_REFERENCE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID67]
    ON [CADIS].[DC_UPPMSCFL_LOAD_CBUF]([CADIS_SYSTEM_RUNID] ASC);

