CREATE TABLE [CADIS].[DC_UPPMPTY_BBG_PTY_CBUF] (
    [CADIS Id]           INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([CADIS Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID8]
    ON [CADIS].[DC_UPPMPTY_BBG_PTY_CBUF]([CADIS_SYSTEM_RUNID] ASC);

