CREATE TABLE [CADIS].[DC_UPPMFFLOW_FLOW_CBUF] (
    [FUND_SHORT_NAME]    VARCHAR (15)    NOT NULL,
    [THROUGH_DATE]       DATETIME        NOT NULL,
    [NTRANCATG]          VARCHAR (100)   NOT NULL,
    [NET_AMOUNT_BASE]    DECIMAL (38, 6) NOT NULL,
    [RECOGNITION_DATE]   DATETIME        NOT NULL,
    [CADIS_SYSTEM_RUNID] INT             NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [THROUGH_DATE] ASC, [NTRANCATG] ASC, [NET_AMOUNT_BASE] ASC, [RECOGNITION_DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID69]
    ON [CADIS].[DC_UPPMFFLOW_FLOW_CBUF]([CADIS_SYSTEM_RUNID] ASC);

