CREATE TABLE [CADIS].[DC_UPNTDVDIRR_EIARPT_STK_CBUF] (
    [CUR_DATE]           DATE         NOT NULL,
    [ACCOUNT_NUMBER]     VARCHAR (50) NOT NULL,
    [SEC_DESCRIPTION]    VARCHAR (50) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([CUR_DATE] ASC, [ACCOUNT_NUMBER] ASC, [SEC_DESCRIPTION] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID146]
    ON [CADIS].[DC_UPNTDVDIRR_EIARPT_STK_CBUF]([CADIS_SYSTEM_RUNID] ASC);

