CREATE TABLE [CADIS].[DC_UPPREACCBA_NTACCBAL_CBUF] (
    [ACCOUNT_NUMBER]      VARCHAR (20)  NOT NULL,
    [VALUATION_DATE]      DATETIME      NOT NULL,
    [ASSET_SUB_CATEGORY]  VARCHAR (100) NOT NULL,
    [LOCAL_CURRENCY_CODE] VARCHAR (3)   NOT NULL,
    [CADIS_SYSTEM_RUNID]  INT           NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [VALUATION_DATE] ASC, [ASSET_SUB_CATEGORY] ASC, [LOCAL_CURRENCY_CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID77]
    ON [CADIS].[DC_UPPREACCBA_NTACCBAL_CBUF]([CADIS_SYSTEM_RUNID] ASC);

