CREATE TABLE [CADIS].[DC_UPOMTGFFS_RED_CBUF] (
    [ROW_NUMBER]         INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID100]
    ON [CADIS].[DC_UPOMTGFFS_RED_CBUF]([CADIS_SYSTEM_RUNID] ASC);

