CREATE TABLE [CADIS].[DC_UPMSTFNDMK_RESET_CBUF] (
    [SOURCE]             VARCHAR (50)   NOT NULL,
    [POSITION_TYPE]      VARCHAR (50)   NOT NULL,
    [FUND_SHORT_NAME]    VARCHAR (8000) NOT NULL,
    [POSITION_DATE]      DATETIME       NOT NULL,
    [CADIS_SYSTEM_RUNID] INT            NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [FUND_SHORT_NAME] ASC, [POSITION_DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID118]
    ON [CADIS].[DC_UPMSTFNDMK_RESET_CBUF]([CADIS_SYSTEM_RUNID] ASC);

