CREATE TABLE [CADIS].[DC_UPBBMSTBRK_MST_BROK_CBUF] (
    [MASTER_BROKER_NUMBER] VARCHAR (40) NOT NULL,
    [CADIS_SYSTEM_RUNID]   INT          NULL,
    PRIMARY KEY CLUSTERED ([MASTER_BROKER_NUMBER] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID7]
    ON [CADIS].[DC_UPBBMSTBRK_MST_BROK_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

