CREATE TABLE [CADIS].[DC_UPDSCOPE_UPDREGLMT_CBUF] (
    [ROW_ID]             BIGINT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT    NULL,
    PRIMARY KEY CLUSTERED ([ROW_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID199]
    ON [CADIS].[DC_UPDSCOPE_UPDREGLMT_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

