CREATE TABLE [CADIS].[DC_UPMSTPOS_OVERRIDE_CBUF] (
    [SOURCE]             VARCHAR (50)    NOT NULL,
    [POSITION_TYPE]      VARCHAR (50)    NOT NULL,
    [EDM_SEC_ID]         INT             NOT NULL,
    [LONG_SHORT_IND]     VARCHAR (8)     NOT NULL,
    [POSITION_DATE]      DATETIME        NOT NULL,
    [QUANTITY]           DECIMAL (20, 6) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT             NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [EDM_SEC_ID] ASC, [LONG_SHORT_IND] ASC, [POSITION_DATE] ASC, [QUANTITY] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID42]
    ON [CADIS].[DC_UPMSTPOS_OVERRIDE_CBUF]([CADIS_SYSTEM_RUNID] ASC);

