CREATE TABLE [CADIS].[DC_UPPREFF_DIPS_CBUF] (
    [TRANSACTION_DATE]   DATETIME      NOT NULL,
    [FLOW_TYPE]          VARCHAR (100) NOT NULL,
    [FUND_SHORT_NAME]    VARCHAR (50)  NOT NULL,
    [SOURCE_TYPE]        VARCHAR (11)  NOT NULL,
    [CADIS_SYSTEM_RUNID] INT           NULL,
    PRIMARY KEY CLUSTERED ([TRANSACTION_DATE] ASC, [FLOW_TYPE] ASC, [FUND_SHORT_NAME] ASC, [SOURCE_TYPE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID80]
    ON [CADIS].[DC_UPPREFF_DIPS_CBUF]([CADIS_SYSTEM_RUNID] ASC);

