CREATE TABLE [CADIS].[DC_UPNTDVDIRR_SUMMARY_CBUF] (
    [ACCOUNT_NUMBER]     VARCHAR (50) NOT NULL,
    [CUR_DATE]           DATE         NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([ACCOUNT_NUMBER] ASC, [CUR_DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID141]
    ON [CADIS].[DC_UPNTDVDIRR_SUMMARY_CBUF]([CADIS_SYSTEM_RUNID] ASC);

