CREATE TABLE [CADIS].[DC_UPBPSDVHIS_STAGE_CBUF] (
    [STOCK]              VARCHAR (20) NOT NULL,
    [ROW_ID]             INT          NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([STOCK] ASC, [ROW_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID137]
    ON [CADIS].[DC_UPBPSDVHIS_STAGE_CBUF]([CADIS_SYSTEM_RUNID] ASC);

