CREATE TABLE [CADIS].[DC_UPNTEISS_CBUF] (
    [FUND_SHORT_NAME] VARCHAR (20) NOT NULL,
    [EDM_SEC_ID]      INT          NOT NULL,
    [VALUATION_DATE]  DATETIME     NOT NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [VALUATION_DATE] ASC) WITH (FILLFACTOR = 80)
);

