CREATE TABLE [CADIS].[DC_UPMSTFX_OVR_APP_CBUF] (
    [FXRATE_ID]          VARCHAR (6) NOT NULL,
    [DATE]               DATETIME    NOT NULL,
    [CADIS_SYSTEM_RUNID] INT         NULL,
    PRIMARY KEY CLUSTERED ([FXRATE_ID] ASC, [DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID17]
    ON [CADIS].[DC_UPMSTFX_OVR_APP_CBUF]([CADIS_SYSTEM_RUNID] ASC);

