CREATE TABLE [CADIS].[DC_UPPREDVDFC_BBG_CBUF] (
    [FundShortName]      VARCHAR (50) NOT NULL,
    [EDM_SEC_ID]         INT          NOT NULL,
    [CalendarYear]       INT          NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([FundShortName] ASC, [EDM_SEC_ID] ASC, [CalendarYear] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID229]
    ON [CADIS].[DC_UPPREDVDFC_BBG_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

