CREATE TABLE [CADIS].[DC_UPPLNOTIF_PROCESS_CBUF] (
    [RUNID]              INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([RUNID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID2]
    ON [CADIS].[DC_UPPLNOTIF_PROCESS_CBUF]([CADIS_SYSTEM_RUNID] ASC);

