CREATE TABLE [CADIS].[DC_UPDTEXCEPT_EXISTING_CBUF] (
    [EXCEPTION_CODE]     INT          NOT NULL,
    [SOURCE_COLUMN]      VARCHAR (50) NOT NULL,
    [SOURCE_KEY]         VARCHAR (50) NOT NULL,
    [SOURCE_TABLE]       VARCHAR (50) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([EXCEPTION_CODE] ASC, [SOURCE_COLUMN] ASC, [SOURCE_KEY] ASC, [SOURCE_TABLE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID13]
    ON [CADIS].[DC_UPDTEXCEPT_EXISTING_CBUF]([CADIS_SYSTEM_RUNID] ASC);

