CREATE TABLE [CADIS].[DC_UPPMSCV_NT_CBUF] (
    [EDM_SHARECLASS_ID]  INT      NOT NULL,
    [VALUATION_DATE]     DATETIME NOT NULL,
    [CADIS_SYSTEM_RUNID] INT      NULL,
    PRIMARY KEY CLUSTERED ([EDM_SHARECLASS_ID] ASC, [VALUATION_DATE] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID248]
    ON [CADIS].[DC_UPPMSCV_NT_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

