CREATE TABLE [CADIS].[DC_UPPMFNDMKT_FUND_CBUF] (
    [SOURCE]             VARCHAR (2)  NOT NULL,
    [POSITION_TYPE]      VARCHAR (8)  NOT NULL,
    [D_VALN_OUT_DATE]    DATETIME     NOT NULL,
    [FUND_SHORT_NAME]    VARCHAR (15) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [POSITION_TYPE] ASC, [D_VALN_OUT_DATE] ASC, [FUND_SHORT_NAME] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID30]
    ON [CADIS].[DC_UPPMFNDMKT_FUND_CBUF]([CADIS_SYSTEM_RUNID] ASC);

