CREATE TABLE [CADIS].[DC_UPNTEIFS_STAGE_CBUF] (
    [VALUATION_DATE]     DATETIME        NOT NULL,
    [FUND_NET_INCOME]    DECIMAL (18, 4) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT             NULL,
    PRIMARY KEY CLUSTERED ([VALUATION_DATE] ASC, [FUND_NET_INCOME] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID257]
    ON [CADIS].[DC_UPNTEIFS_STAGE_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

