CREATE TABLE [CADIS].[DC_UPPREMSTIN_BBG_CBUF] (
    [FUND_SHORT_NAME]     VARCHAR (50) NOT NULL,
    [EDM_SEC_ID]          INT          NOT NULL,
    [FUND_FISCAL_YEAR]    INT          NOT NULL,
    [FUND_FISCAL_QUARTER] INT          NOT NULL,
    [CADIS_SYSTEM_RUNID]  INT          NULL,
    PRIMARY KEY CLUSTERED ([FUND_SHORT_NAME] ASC, [EDM_SEC_ID] ASC, [FUND_FISCAL_YEAR] ASC, [FUND_FISCAL_QUARTER] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID232]
    ON [CADIS].[DC_UPPREMSTIN_BBG_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

