CREATE TABLE [CADIS].[DC_UPSJPHFFST_GBPRED_CBUF] (
    [ROW_NUMBER]         INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([ROW_NUMBER] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID112]
    ON [CADIS].[DC_UPSJPHFFST_GBPRED_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 90);

