CREATE TABLE [CADIS].[DC_UPPREPRC_BPS_HIST_CBUF] (
    [ID_BB_UNIQUE]       VARCHAR (50) NOT NULL,
    [PX_DATE]            DATETIME     NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([ID_BB_UNIQUE] ASC, [PX_DATE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID131]
    ON [CADIS].[DC_UPPREPRC_BPS_HIST_CBUF]([CADIS_SYSTEM_RUNID] ASC);

