CREATE TABLE [CADIS].[DI_ISSCTR_ISSCTR_CBUF] (
    [PortfolioGroup]     VARCHAR (250) NOT NULL,
    [ReportDate]         DATETIME      NOT NULL,
    [Security]           VARCHAR (250) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT           NULL,
    PRIMARY KEY CLUSTERED ([PortfolioGroup] ASC, [ReportDate] ASC, [Security] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID220]
    ON [CADIS].[DI_ISSCTR_ISSCTR_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

