CREATE TABLE [CADIS].[DI_VLREGLMTDT_REGLMTDT_CBUF] (
    [ROW_ID]             BIGINT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT    NULL,
    PRIMARY KEY CLUSTERED ([ROW_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID198]
    ON [CADIS].[DI_VLREGLMTDT_REGLMTDT_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

