CREATE TABLE [CADIS].[DI_VITGTAR_IN_CBUF] (
    [ORDERID]            INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([ORDERID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID173]
    ON [CADIS].[DI_VITGTAR_IN_CBUF]([CADIS_SYSTEM_RUNID] ASC);

