CREATE TABLE [CADIS].[DI_VANTEIT_TYPED_CBUF] (
    [ID]                 INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID258]
    ON [CADIS].[DI_VANTEIT_TYPED_CBUF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

