CREATE TABLE [CADIS].[DI_VTMASSEC_MASTER_CBUF] (
    [EDM_SEC_ID]         INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([EDM_SEC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID152]
    ON [CADIS].[DI_VTMASSEC_MASTER_CBUF]([CADIS_SYSTEM_RUNID] ASC);

