CREATE TABLE [CADIS].[DI_VABPSREQA_REQUEST_CBUF] (
    [SOURCE]             VARCHAR (50) NOT NULL,
    [SOURCE_ID]          VARCHAR (50) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([SOURCE] ASC, [SOURCE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID153]
    ON [CADIS].[DI_VABPSREQA_REQUEST_CBUF]([CADIS_SYSTEM_RUNID] ASC);

