CREATE TABLE [CADIS].[DI_VTRXML_POS_CBUF] (
    [CADIS_BATCH_ID]     INT NOT NULL,
    [CADIS_MSG_ID]       INT NOT NULL,
    [CADIS_PARENT_ID]    INT NOT NULL,
    [CADIS_ROW_ID]       INT NOT NULL,
    [CADIS_SYSTEM_RUNID] INT NULL,
    PRIMARY KEY CLUSTERED ([CADIS_BATCH_ID] ASC, [CADIS_MSG_ID] ASC, [CADIS_PARENT_ID] ASC, [CADIS_ROW_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID175]
    ON [CADIS].[DI_VTRXML_POS_CBUF]([CADIS_SYSTEM_RUNID] ASC);

