CREATE TABLE [CADIS].[DM_PARTY_BBG_MASTER_CBUFF] (
    [MASTER_BROKER_NUMBER] VARCHAR (40) NOT NULL,
    [CADIS_SYSTEM_RUNID]   INT          NULL,
    PRIMARY KEY CLUSTERED ([MASTER_BROKER_NUMBER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID6]
    ON [CADIS].[DM_PARTY_BBG_MASTER_CBUFF]([CADIS_SYSTEM_RUNID] ASC);

