CREATE TABLE [CADIS].[DM_PARTY_BBG_BROKER_CBUFF] (
    [BROKER]             VARCHAR (40) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([BROKER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID5]
    ON [CADIS].[DM_PARTY_BBG_BROKER_CBUFF]([CADIS_SYSTEM_RUNID] ASC);

