CREATE TABLE [CADIS].[DM_SECURITY_CURRENCY_CBUFF] (
    [CCY_CODE]           VARCHAR (20) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([CCY_CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID21]
    ON [CADIS].[DM_SECURITY_CURRENCY_CBUFF]([CADIS_SYSTEM_RUNID] ASC);

