CREATE TABLE [CADIS].[DM_SECURITY_HUBWISE_CBUFF] (
    [INSTRUMENT_UII]     VARCHAR (12) NOT NULL,
    [CADIS_SYSTEM_RUNID] INT          NULL,
    PRIMARY KEY CLUSTERED ([INSTRUMENT_UII] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_CADIS_SYSTEM_RUNID243]
    ON [CADIS].[DM_SECURITY_HUBWISE_CBUFF]([CADIS_SYSTEM_RUNID] ASC) WITH (FILLFACTOR = 80);

