CREATE TABLE [CADIS].[ILLUSTRATION_TYPE_TEMPLATE] (
    [TYPENAME]        NVARCHAR (50)  NOT NULL,
    [FIELDNAME]       NVARCHAR (100) NOT NULL,
    [ILLUSTRATEDNAME] NVARCHAR (100) NOT NULL
);


GO
CREATE CLUSTERED INDEX [IDXILTTID]
    ON [CADIS].[ILLUSTRATION_TYPE_TEMPLATE]([TYPENAME] ASC, [FIELDNAME] ASC, [ILLUSTRATEDNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IDXTYPENAME]
    ON [CADIS].[ILLUSTRATION_TYPE_TEMPLATE]([TYPENAME] ASC);

