CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION57]
(@INPUT0 VARCHAR (50), @INPUT1 DATETIME)
RETURNS DECIMAL (18, 2)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

