CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION10]
(@INPUT0 VARCHAR (20), @INPUT1 VARCHAR (150), @INPUT2 VARCHAR (20))
RETURNS TABLE 
WITH ENCRYPTION
AS
RETURN 
    
--The script body was encrypted and cannot be reproduced here.
    SELECT NULL AS [NullColumn]


