CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION99]
(@INPUT0 VARCHAR (50), @INPUT1 VARCHAR (100))
RETURNS VARCHAR (255)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

