CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION204]
(@INPUT0 DECIMAL (24, 10), @INPUT1 DECIMAL (24, 10))
RETURNS DECIMAL (24, 10)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

