CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION191]
(@INPUT0 VARCHAR (100), @INPUT1 INT, @INPUT2 INT, @INPUT3 INT, @INPUT4 DATETIME, @INPUT5 VARCHAR (20))
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

