CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION65]
(@INPUT0 VARCHAR (100), @INPUT1 VARCHAR (5))
RETURNS VARCHAR (255)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

