CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION123]
(@INPUT0 VARCHAR (50), @INPUT1 VARCHAR (50))
RETURNS INT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

