CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION77]
(@INPUT0 VARCHAR (18), @INPUT1 VARCHAR (20))
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

