CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION125]
(@INPUT0 INT, @INPUT1 INT, @INPUT2 VARCHAR (50), @INPUT3 VARCHAR (50), @INPUT4 DATETIME, @INPUT5 VARCHAR (50), @INPUT6 VARCHAR (50))
RETURNS VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

