CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION196]
(@INPUT0 DATETIME, @INPUT1 DECIMAL (20, 6), @INPUT2 VARCHAR (50), @INPUT3 INT, @INPUT4 INT, @INPUT5 INT)
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

