CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION58]
(@INPUT0 VARCHAR (400))
RETURNS VARCHAR (400)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

