CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION66]
(@INPUT0 BIT, @INPUT1 VARCHAR (10))
RETURNS VARCHAR (10)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

