CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION76]
(@INPUT0 VARCHAR (2000), @INPUT1 VARCHAR (10))
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

