CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION192]
(@INPUT0 DATETIME, @INPUT1 INT, @INPUT2 INT, @INPUT3 VARCHAR (50))
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

