CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION115]
(@INPUT0 VARCHAR (30), @INPUT1 VARCHAR (30))
RETURNS VARCHAR (50)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

