CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION147]
(@INPUT0 VARCHAR (18), @INPUT1 VARCHAR (18), @INPUT2 VARCHAR (10))
RETURNS VARCHAR (10)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

