CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION170]
(@INPUT0 INT, @INPUT1 VARCHAR (500))
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

