CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION21]
(@INPUT0 VARCHAR (100), @INPUT1 VARCHAR (100))
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

