CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION75]
(@INPUT0 VARCHAR (50), @INPUT1 VARCHAR (2000))
RETURNS BIT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

