CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION42]
(@INPUT0 VARCHAR (20), @INPUT1 VARCHAR (20), @INPUT2 VARCHAR (20), @INPUT3 VARCHAR (20))
RETURNS VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

