CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION173]
(@INPUT0 NVARCHAR (20))
RETURNS NVARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

