CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION28]
(@INPUT0 VARCHAR (50), @INPUT1 VARCHAR (50), @INPUT2 VARCHAR (50))
RETURNS TABLE 
WITH ENCRYPTION
AS
RETURN 
    
--The script body was encrypted and cannot be reproduced here.
    SELECT NULL AS [NullColumn]


