CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION117]
(@INPUT0 VARCHAR (255), @INPUT1 INT)
RETURNS VARCHAR (255)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

