CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION11]
(@INPUT0 VARCHAR (20))
RETURNS DECIMAL (18, 2)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

