CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION68]
(@INPUT0 VARCHAR (2000))
RETURNS VARCHAR (10)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

