CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION174]
(@INPUT0 VARCHAR (100))
RETURNS VARCHAR (1000)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

