CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION184]
(@INPUT0 DATETIME, @INPUT1 DATETIME, @INPUT2 DECIMAL (20, 6), @INPUT3 DECIMAL (20, 6), @INPUT4 DATETIME, @INPUT5 DATETIME, @INPUT6 DECIMAL (20, 6), @INPUT7 DECIMAL (20, 6), @INPUT8 DATETIME, @INPUT9 DATETIME, @INPUT10 DECIMAL (20, 6), @INPUT11 DECIMAL (20, 6), @INPUT12 DATETIME, @INPUT13 DATETIME, @INPUT14 DECIMAL (20, 6), @INPUT15 DECIMAL (20, 6))
RETURNS VARCHAR (20)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

