CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION36]
(@INPUT0 VARCHAR (1000))
RETURNS NVARCHAR (100)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

