CREATE FUNCTION [CADIS_PROC].[RB_FUNCTION194]
(@INPUT0 VARCHAR (50), @INPUT1 INT, @INPUT2 INT, @INPUT3 DECIMAL (20, 6))
RETURNS DECIMAL (24, 10)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN NULL
END

