CREATE PROCEDURE [dbo].[usp_MergeBrokerTouchTypes]
AS
SET XACT_ABORT ON;

BEGIN TRY
BEGIN TRANSACTION;

--UPDATE TOUCH TYPE TO Low Touch where Broker conatains  LNTX
UPDATE [dbo].[T_BBG_BROKER]
SET [MASTER_BROKER_TOUCH_TYPE] = 'Low Touch'
WHERE [BROKER] LIKE '%LNTX%'  

UPDATE [dbo].[T_BBG_BROKER]
SET [MASTER_BROKER_TOUCH_TYPE] = 'Low Touch'
WHERE [BROKER] LIKE '%ITGEQ%'  


UPDATE [dbo].[T_BBG_BROKER]
SET [MASTER_BROKER_TOUCH_TYPE] = 'Low Touch'
WHERE [BROKER] LIKE '%ITGI%'  

--UPDATE TOUCH TYPE TO Low Touch where Broker conatains ALGO 
UPDATE [dbo].[T_BBG_BROKER]
SET [MASTER_BROKER_TOUCH_TYPE] = 'Low Touch'
WHERE  [BROKER] LIKE  '%ALGO%'


--UPDATE TOUCHTYPE TO High Touch where TouchType is Null
UPDATE [T_BBG_BROKER]
SET [MASTER_BROKER_TOUCH_TYPE] = 'High Touch'
WHERE [MASTER_BROKER_TOUCH_TYPE] IS NULL


--POPULATE/Update REFERENCE TABLE 
MERGE  dbo.T_REF_TOUCH_TYPE AS TARGET
USING [dbo].[T_BBG_BROKER] AS SOURCE
ON (TARGET.TouchTypeName = SOURCE.[BROKER]) 

--When records are matched, update 
--the records if there is any change
WHEN MATCHED AND 
TARGET.TouchTypeName <> SOURCE.[BROKER] 
OR TARGET.[TouchType] <> SOURCE.[MASTER_BROKER_TOUCH_TYPE]
THEN 
UPDATE SET TARGET.TouchTypeName = SOURCE.[BROKER], 
TARGET.[TouchType] = SOURCE.[MASTER_BROKER_TOUCH_TYPE]
--When no records are matched, insert
--the incoming records from source
--table to target table
WHEN NOT MATCHED BY TARGET 
THEN
INSERT ([TouchTypeName], [TouchType])
VALUES (SOURCE.[BROKER], SOURCE.[MASTER_BROKER_TOUCH_TYPE]);

COMMIT TRANSACTION;
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRANSACTION;

DECLARE
@ERROR_SEVERITY INT,
@ERROR_STATE INT,
@ERROR_NUMBER INT,
@ERROR_LINE INT,
@ERROR_MESSAGE NVARCHAR(4000);

SELECT
@ERROR_SEVERITY = ERROR_SEVERITY(),
@ERROR_STATE = ERROR_STATE(),
@ERROR_NUMBER = ERROR_NUMBER(),
@ERROR_LINE = ERROR_LINE(),
@ERROR_MESSAGE = ERROR_MESSAGE();

RAISERROR('Msg %d, Line %d, :%s',
@ERROR_SEVERITY,
@ERROR_STATE,
@ERROR_NUMBER,
@ERROR_LINE,
@ERROR_MESSAGE);
END CATCH

-- DO NOT REMOVE
IF (XACT_STATE()) IN (1, -1) 
BEGIN 
PRINT 
N'The transaction has not been committed.' + 
'Rolling back transaction.' 
ROLLBACK TRANSACTION; 
END;



