CREATE PROCEDURE usp_Update_MasterSEC_Issuer

AS


--Update t_master_sec Issuers to match Issuers table
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Mediclinic International PLC' WHERE ISSUER  =  'Al Noor Hospitals Group PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Amigo Holdings PLC' WHERE ISSUER  =  'Amigo Holdings PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Barclays PLC' WHERE ISSUER  =  'Barclays Bank PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Bioverativ Inc' WHERE ISSUER  =  'Bioverativ Inc'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Crystal Amber Asset Management' WHERE ISSUER  =  'Crystal Amber Fund Ltd'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Draper Fisher Jurvetson Intern' WHERE ISSUER  =  'Draper Esprit PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HEALTH HOLDCO LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HEALTH HOLDCO LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HEALTH HOLDCO LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HEALTH HOLDCO LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HEALTH HOLDCO LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HOLDCO2 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HOLDCO2 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HOLDCO2 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HOLDCO2 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HOLDCO2 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HOLDCO2 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON HOLDCO2 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Econic Technologies' WHERE ISSUER  =  'ECONIC TECH'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Econic Technologies' WHERE ISSUER  =  'ECONIC TECH'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Hostelworld Group Plc' WHERE ISSUER  =  'Hostelworld Group Plc'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'IH Holdings International Ltd' WHERE ISSUER  =  'IH HOLDINGS INTL'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'IH Holdings International Ltd' WHERE ISSUER  =  'IND HEAT'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'IH Holdings International Ltd' WHERE ISSUER  =  'IND HEAT'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Juno Therapeutics Inc' WHERE ISSUER  =  'Juno Therapeutics Inc'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'NewRiver REIT PLC' WHERE ISSUER  =  'NewRiver'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'NewRiver REIT PLC' WHERE ISSUER  =  'NewRiver Retail Ltd'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Oakley Capital Ltd' WHERE ISSUER  =  'Oakley Capital Investments Ltd'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Oxford Sciencs Innovation' WHERE ISSUER  =  'OXFORD PHARMA'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Oxford Sciencs Innovation' WHERE ISSUER  =  'OXFORD PHARMA'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'P2P Global Investments PLC' WHERE ISSUER  =  'P2P Global Investments PLC/Fun'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Raven Property Group Ltd' WHERE ISSUER  =  'RAVEN RUSSIA LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Reynolds American Inc' WHERE ISSUER  =  'Reynolds American Inc'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Royal Bank of Scotland Group P' WHERE ISSUER  =  'Royal Bank of Scotland Group P'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Sphere Medical Holding PLC' WHERE ISSUER  =  'SPHERE MED LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Sphere Medical Holding PLC' WHERE ISSUER  =  'SPHERE MED LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Syncona Investments LP Inc' WHERE ISSUER  =  'Syncona Ltd'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Touchstone Innovations PLC' WHERE ISSUER  =  'Touchstone Innovations PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'USL Pharma International UK Lt' WHERE ISSUER  =  'USL PHARMA'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Metalysis Ltd' WHERE ISSUER  =  'WATH'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Metalysis Ltd' WHERE ISSUER  =  'WATH'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Metalysis Ltd' WHERE ISSUER  =  'WATH'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Metalysis Ltd' WHERE ISSUER  =  'WATH'

UPDATE T_MASTER_SEC SET  
ISSUER  = 'Metalysis Ltd' WHERE ISSUER  =  'Metalysis'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Accelerated Digital Ventures ' WHERE ISSUER  =  'ADV'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Mediclinic International PLC' WHERE ISSUER  =  'Al Noor Hospitals Group PLC '
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Welsh Carson Anderson & Stowe' WHERE ISSUER  =  'Abzena PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Halosource Corp' WHERE ISSUER  =  'Halosource Inc'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Ligand Pharmaceuticals Inc' WHERE ISSUER  =  'Vernalis PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Time out Group PLC' WHERE ISSUER  =  'Time out Group Ltd'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Royal Dutch Shell PLC' WHERE ISSUER  =  'BG Group Ltd'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Aston Martin Lagonda Global Ho' WHERE ISSUER  =  'MS Amlin PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Public Storage' WHERE ISSUER  =  'Public Storage INC'

UPDATE T_MASTER_SEC SET  
ISSUER  = 'Accelerated Digital Ventures ' WHERE ISSUER  =  'ADV'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'American Financial Exchange' WHERE ISSUER  =  'AFX'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'AJ Bell Holdings' WHERE ISSUER  =  'AJ BELL'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Arix Bioscience Plc' WHERE ISSUER  =  'ARIX BIO'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Autolus Therapeutics PLC' WHERE ISSUER  =  'AUTOLUS'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Beazley PLC' WHERE ISSUER  =  'Beazley Ireland Holdings PLC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Bodle Technologies' WHERE ISSUER  =  'BODLE'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Brandon Point Enterprises 1' WHERE ISSUER  =  'BRAN POINT'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Carrick Therapeutics' WHERE ISSUER  =  'CARRICK THERAP'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Cell Medica' WHERE ISSUER  =  'CELLMEDICA'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Cambridge Innovation Capital' WHERE ISSUER  =  'CIC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Cosmederm Bioscience' WHERE ISSUER  =  'COSMEDERM'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'DDF Parallel' WHERE ISSUER  =  'DDF'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Drayson Technologies' WHERE ISSUER  =  'DRAYSON'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Eve Sleep PLC' WHERE ISSUER  =  'EVE SLEEP'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Evofem Biosciences Inc' WHERE ISSUER  =  'EVOFEM'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Evofem Biosciences Inc' WHERE ISSUER  =  'EVOFEM BIOSCIENCES'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Evofem Biosciences Inc' WHERE ISSUER  =  'EVOFEM D'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Federated Wireless' WHERE ISSUER  =  'FED WIRELESS INC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Federated Wireless' WHERE ISSUER  =  'FEDERATED WIRELESS INC'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Fibre 7 UK ' WHERE ISSUER  =  'FIBRE 7'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'HawkEye 360' WHERE ISSUER  =  'HAWKEYE'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Kind Consumer Holdings' WHERE ISSUER  =  'KIND'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Kymab Group' WHERE ISSUER  =  'KYMAB'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Literacy Capital' WHERE ISSUER  =  'LITERACY CAP'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Mafic' WHERE ISSUER  =  'MAFIC S.A.'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Malin J1' WHERE ISSUER  =  'MALIN J1 LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Mereo Biopharma Group PLC' WHERE ISSUER  =  'MEREO'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Mission Therapeutics' WHERE ISSUER  =  'MISSION'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Ombu Group Ltd' WHERE ISSUER  =  'OMBU'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Oxford Nanopore Technologies' WHERE ISSUER  =  'OXFORD NANO'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Oxford Sciencs Innovation' WHERE ISSUER  =  'Oxford Pharmascience LTD'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Oxford Sciencs Innovation' WHERE ISSUER  =  'OXFORD SCIENCES'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Phoenix Group Holdings' WHERE ISSUER  =  'PHOENIX'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Precision Biopsy' WHERE ISSUER  =  'PRECISION BIO'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Proton Partners International' WHERE ISSUER  =  'PROTON PARTNERS'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'PsiOxus Therapeutics' WHERE ISSUER  =  'PSIOXUS'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Retail Money Market' WHERE ISSUER  =  'RATESETTER'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'RM2 International SA' WHERE ISSUER  =  'RM2 INTERNATIONAL'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Royal Bank of Scotland Group' WHERE ISSUER  =  'Royal Bank of Scotland Group P'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Sabina Estates Ltd' WHERE ISSUER  =  'SABINA'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'SciFluor Life Sciences' WHERE ISSUER  =  'SCIFLUOR LIFE'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Sphere Medical Holding PLC' WHERE ISSUER  =  'SPHERE MEDICAL HOLDINGS'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Spin Transfer Technologies ' WHERE ISSUER  =  'SPIN TRANSFER'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Ultrahaptics Holdings' WHERE ISSUER  =  'ULTRAHAPTICS'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'USL Pharma International UK Lt' WHERE ISSUER  =  'USL Pharma International UK Lt'
UPDATE T_MASTER_SEC SET  
ISSUER  = 'Yoyo Wallet' WHERE ISSUER  =  'YOYO'