CREATE VIEW [dbo].[POSITION_SECURITY_VIEW]
AS
select
	p.SOURCE,
	p.POSITION_TYPE,
 	p.EDM_SEC_ID,
	p.FUND_SHORT_NAME,
	p.LONG_SHORT_IND,
	p.POSITION_DATE,
	p.QUANTITY,
	s.SECURITY_NAME,
	s.SECURITY_DESCRIPTION,
	s.SECURITY_SHORTNAME,
	s.ASSET_TYPE,
	s.SECURITY_TYPE,
	s.CUSIP,
	s.ISIN,
	s.SEDOL,
	s.TICKER,
	s.VALOREN,
	s.WERTPAPIER,
	s.SECURITY_ISO_CCY,
	s.RISK_ISO_CCY,
	s.FIXED_ISO_CCY,
	s.INCORPORATION_ISO_CTY,
	s.DOMICILE_ISO_CTY,
	s.ISSUE_COUNTRY_ISO,
	s.RISK_ISO_CTY,
	s.MIC_EXCHANGE_CODE,
	s.BBG_EXCHANGE_CODE,
	s.STATE_CODE,
	s.ACTIVE_TRADE_INDICATOR,
	s.[144A_INDICATOR],
	s.PRIVATE_PLACEMENT_INDICATOR,
	s.ILLIQUID,
	s.QUOTE_TYPE,
	s.DAYS_TO_SETTLE,
	s.TRADE_SETTLEMENT_CALENDAR_CODE,
	s.UNIQUE_BLOOMBERG_ID,
	s.BBG_SECTOR,
	s.BBG_SUBSECTOR,
	s.BBG_GROUP,
	s.IS_IPO,
	s.PARSEKEYABLE_DESCRIPTION,
	s.SECURITY_IDENTIFIER,
	s.IRISH_SEDOL_NUMBER,
	s.ISSUER,
	s.CUR_MAR_CAP,
	s.PRIMARY_EXCHANGE_NAME,
	s.SECURITY_HAS_ADRS,
	s.WITHHOLDING_TAX
from 
	dbo.T_MASTER_POS P
join 
	dbo.T_MASTER_SEC s
	on p.EDM_SEC_ID = s.EDM_SEC_ID
where
	FUND_SHORT_NAME IN ('WIMEIF', 'WIMIFF')

