
CREATE VIEW [dbo].[T_BPS_SECURITY_VIEW]
AS

----/******************************
----** Desc:
----** Auth: R.Dixon
----** Date: 09/08/2018
----**************************
----** Change History
----**************************
----** JIRA		  Date		  Author	Description 
----** ----		  ----------  -------	------------------------------------
----** DAP-2210     09/08/2018  R.Dixon	Added VOL_AVG_5D and VOL_AVG_20D fields. 
----** DAP-2379     04/01/2019  Olu		Added ISSUER fields.
----** DAP-2385		30/01/2019	S.Burns	Changed [ALL_BROKERS_ADV_TOT_AGGR_VOL] to [ADV_TOTAL_VOLUME]
----*******************************/
WITH CTE_CORE AS (
  SELECT [FILE_NAME], [DATE], [IDENTIFIER], 
		[SECURITY_NAME] AS [SECURITY_NAME]
      ,[SECURITY_DES] AS [SECURITY_DESCRIPTION]
      ,[SHORT_NAME] AS [SECURITY_SHORTNAME]
      ,map.Target_Code AS [ASSET_TYPE]
      ,[SECURITY_TYP] AS [SECURITY_TYPE]
      ,[TICKER] AS [TICKER]
      ,[QUOTED_CRNCY] AS [SECURITY_ISO_CCY]
	  ,[PARSEKYABLE_DES] AS [PARSEKEYABLE_DESCRIPTION]
	  ,[VOLUME_AVG_5D] AS [VOLUME_AVG_5D]
	  ,[VOLUME_AVG_20D] AS [VOLUME_AVG_20D]
	  ,[ISSUER] AS [ISSUER_NAME]
	  ,ID_CUSIP as [CUSIP]
	  ,ID_ISIN AS ISIN
	  ,ID_VALOREN AS VALOREN
	  ,ID_WERTPAPIER AS WERTPAPIER
	  ,ADV_TOTAL_VOLUME AS ADV_TOTAL_VOLUME
	  ,CNTRY_OF_DOMICILE AS  DOMICILE_ISO_CTY
	  ,ISSUE_COUNTRY_ISO AS ISSUE_COUNTRY_ISO
	  ,TRADE_STATUS AS ACTIVE_TRADE_INDICATOR
	  ,CNTRY_OF_INCORPORATION AS [INCORPORATION_ISO_CTY]
	  ,CUR_MKT_CAP AS CUR_MAR_CAP
	  ,PVT.CADIS_SYSTEM_UPDATED
	  

	  FROM 
(SELECT [FILE_NAME] AS [FILE_NAME]
      ,CONVERT(DATE, [DATE]) AS [DATE]
      ,[IDENTIFIER]
      ,[FIELD]
	  ,[VALUE]
	  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
FROM [dbo].[T_BPS_SECURITY]) p
PIVOT
(
	MIN([VALUE])
FOR [FIELD] IN
( 
	   [SECURITY_NAME]
	  ,[MARKET_SECTOR2]
      ,[SECURITY_DES]
      ,[SHORT_NAME]
      ,[SECURITY_TYP]
      ,[TICKER]
      ,[QUOTED_CRNCY]
	  ,[PARSEKYABLE_DES]
	  ,[VOLUME_AVG_5D]
	  ,[VOLUME_AVG_20D]
	  ,[ISSUER]
	  ,ID_CUSIP 
	  ,ID_ISIN
	  ,ID_VALOREN
	  ,ID_WERTPAPIER
	  ,TRADE_STATUS
	  ,ADV_TOTAL_VOLUME
	  ,FIXED_ISO_CCY
	  ,CNTRY_OF_DOMICILE
	  ,ISSUE_COUNTRY_ISO
	  ,CNTRY_OF_INCORPORATION
	  ,CUR_MKT_CAP
)
) AS pvt
LEFT JOIN [dbo].[T_REF_GENERAL_MAP] map ON map.[SOURCE_CODE] = [MARKET_SECTOR2] AND map.FIELD_NAME = 'Market Sector Two'
 WHERE 
  FILE_NAME LIKE 'BPS_CORE%'

)
SELECT 
	MAX([FILE_NAME]) AS [FILE_NAME]
			, MAX([DATE]) AS [DATE]
			, [IDENTIFIER]
			,[SECURITY_NAME]
			  ,[SECURITY_DESCRIPTION]
			  ,[SECURITY_SHORTNAME]
			  ,[ASSET_TYPE]
			  ,[SECURITY_TYPE]
			  ,[CUSIP]
			  ,[ISIN]
			  ,[SEDOL] 
			  ,[TICKER]
			  ,[VALOREN]
			  ,[WERTPAPIER]
			  ,[SECURITY_ISO_CCY]
			  ,[RISK_ISO_CCY]
			  ,[FIXED_ISO_CCY]
			  ,[INCORPORATION_ISO_CTY]
			  ,[DOMICILE_ISO_CTY]
			  ,[ISSUE_COUNTRY_ISO]
			  ,[RISK_ISO_CTY]
			  ,[MIC_EXCHANGE_CODE]
			  ,[BBG_EXCHANGE_CODE]
			  ,[STATE_CODE]
			  ,[ACTIVE_TRADE_INDICATOR]
			  ,[144A_INDICATOR]
			  ,[PRIVATE_PLACEMENT_INDICATOR]
			  ,[ILLIQUID]
			  ,[QUOTE_TYPE]
			  ,[DAYS_TO_SETTLE]
			  ,[TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,[UNIQUE_BLOOMBERG_ID]
			  ,[BBG_SECTOR]
			  ,[BBG_SUBSECTOR]
			  ,[BBG_GROUP]
			  ,[IS_IPO]
			  ,[PARSEKEYABLE_DESCRIPTION]
			  ,[SECURITY_IDENTIFIER]
			  ,[IRISH_SEDOL_NUMBER]
			  ,[ISSUER]
			  ,[CUR_MAR_CAP]
			  ,[PRIMARY_EXCHANGE_NAME]
			  ,[SECURITY_HAS_ADRS]
			  ,[VOLUME_AVG_5D]
			  ,[VOLUME_AVG_20D]
			  ,[ADV_TOTAL_VOLUME]
			  ,MAX(CADIS_SYSTEM_UPDATED) AS CADIS_SYSTEM_UPDATED
FROM 
	(
		SELECT
		pvt.[FILE_NAME], pvt.[DATE], pvt.[IDENTIFIER], 
				core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST(NULL AS VARCHAR(9)) AS [CUSIP]
			  ,CAST(NULL AS VARCHAR(12)) AS [ISIN]
			  ,CAST(NULL AS VARCHAR(7)) AS [SEDOL] 
			  ,core.[TICKER]
			  ,CAST(NULL AS VARCHAR(12)) AS [VALOREN]
			  ,CAST(NULL AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST([CNTRY_OF_INCORPORATION] AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST([CNTRY_ISSUE_ISO] AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST(NULL AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST([ID_MIC_PRIM_EXCH] AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST([EXCH_CODE] AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST(NULL AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST([PRPL] AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST(NULL AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST(NULL AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST(NULL AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST([ID_BB_UNIQUE] AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST(NULL AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST(NULL AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST([SEC_ID_FLAG] AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST([ISSUER] AS VARCHAR(80)) AS [ISSUER]
			  ,CAST([CUR_MKT_CAP] AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST([PRIMARY_EXCHANGE_NAME] AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST([HAS_ADRS] AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED			  
		FROM 
		(SELECT [FILE_NAME] AS [FILE_NAME]
			  ,CONVERT(DATE, [DATE]) AS [DATE]
			  ,[IDENTIFIER]
			  ,[FIELD]
			  ,[VALUE]
			  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
		FROM [dbo].[T_BPS_SECURITY]) p
		PIVOT
		(
			MIN([VALUE])
		FOR [FIELD] IN
		( 
			[SECURITY_NAME]
			,[MARKET_SECTOR2]
			  ,[SECURITY_DES]
			  ,[SHORT_NAME]
			  ,[SECURITY_TYP]
			  ,[TICKER]
			  ,[QUOTED_CRNCY]
			  ,[CNTRY_OF_INCORPORATION]
			  ,[CNTRY_ISSUE_ISO]
			  ,[ID_MIC_PRIM_EXCH]
			  ,[EXCH_CODE]
			  ,[PRPL]
			  ,[ID_BB_UNIQUE]
			  ,[PARSEKYABLE_DES]
			  ,[SEC_ID_FLAG]
			  ,[ISSUER]
			  ,[CUR_MKT_CAP]
			  ,[PRIMARY_EXCHANGE_NAME]
			  ,[HAS_ADRS]
		)
		) AS pvt
		LEFT JOIN [dbo].[T_REF_GENERAL_MAP] map ON map.[SOURCE_CODE] = [MARKET_SECTOR2] AND map.FIELD_NAME = 'Market Sector Two'
		LEFT JOIN CTE_CORE core ON core.IDENTIFIER = pvt.IDENTIFIER AND core.DATE = PVT.DATE
		  WHERE --map.FIELD_NAME = 'Market Sector Two' AND 
		  pvt.FILE_NAME LIKE 'EQ_CLOSED_END%'
		UNION ALL
		SELECT
			  pvt.[FILE_NAME], pvt.[DATE], pvt.[IDENTIFIER], 
			  core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST([ID_CUSIP] AS VARCHAR(9)) AS [CUSIP]
			  ,CAST([ID_ISIN] AS VARCHAR(12)) AS [ISIN]
			  ,CAST([ID_SEDOL1] AS VARCHAR(7)) AS [SEDOL]
			  ,core.[TICKER]
			  ,CAST([ID_VALOREN] AS VARCHAR(12)) AS [VALOREN]
			  ,CAST([ID_WERTPAPIER] AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST([CNTRY_OF_INCORPORATION] AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST([CNTRY_OF_DOMICILE] AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST([CNTRY_ISSUE_ISO] AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST([CNTRY_OF_RISK] AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST([ID_MIC_PRIM_EXCH] AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST([EXCH_CODE] AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST([STATE_CODE2] AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST([TRADE_STATUS] AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST([144A_FLAG] AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST([PRPL] AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST([SSR_LIQUIDITY_INDICATOR] AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST([QUOTE_TYP] AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST([DAYS_TO_SETTLE] AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST([CDR_SETTLE_CODE] AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST([ID_BB_UNIQUE] AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST([SECTOR] AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST([SUBSECTOR] AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST([CGROUP_NAME] AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST([TR_IPO_TRADE] AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST([SEC_ID_FLAG] AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST([ISSUER] AS VARCHAR(80)) AS [ISSUER]
			  ,CAST([CUR_MKT_CAP] AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST([PRIMARY_EXCHANGE_NAME] AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST([HAS_ADRS] AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED
		FROM 
		(SELECT [FILE_NAME] AS [FILE_NAME]
			  ,CONVERT(DATE, [DATE]) AS [DATE]
			  ,[IDENTIFIER]
			  ,[FIELD]
			  ,[VALUE]
			  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
		FROM [dbo].[T_BPS_SECURITY]) p
		PIVOT
		(
			MIN([VALUE])
		FOR [FIELD] IN
		( 
			[ID_BB_UNIQUE],
			[ID_CUSIP],
			[ID_ISIN],
			[ID_SEDOL1],
			[ID_VALOREN],
			[ID_WERTPAPIER],
			[CNTRY_OF_RISK],
			[CNTRY_OF_INCORPORATION],
			[CNTRY_OF_DOMICILE],
			[CNTRY_ISSUE_ISO],
			[ID_MIC_PRIM_EXCH],
			[EXCH_CODE],
			[STATE_CODE2],
			[TRADE_STATUS],
			[144A_FLAG],
			[SSR_LIQUIDITY_INDICATOR],
			[QUOTE_TYP],
			[DAYS_TO_SETTLE],
			[CDR_SETTLE_CODE],
			[SECTOR],
			[SUBSECTOR],
			[TR_IPO_TRADE],
			[ID_IRISH_SEDOL],
			[SEC_ID_FLAG],
			[ISSUER],
			[CUR_MKT_CAP],
			[PRIMARY_EXCHANGE_NAME],
			[CGROUP_NAME],
			[PRPL],
			[HAS_ADRS] 
		)
		) AS pvt
		LEFT JOIN CTE_CORE core ON core.IDENTIFIER = pvt.IDENTIFIER AND core.DATE = PVT.DATE
		  WHERE --map.FIELD_NAME = 'Market Sector Two' AND 
		  pvt.FILE_NAME LIKE 'EQ_COMMON_STO%'
		  UNION ALL
		  /*
		  MISC
		  */
		  SELECT
			  pvt.[FILE_NAME], pvt.[DATE], pvt.[IDENTIFIER], 
			  core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST([ID_CUSIP] AS VARCHAR(9)) AS [CUSIP]
			  ,CAST(NULL AS VARCHAR(12)) AS [ISIN]
			  ,CAST(NULL AS VARCHAR(7)) AS [SEDOL]
			  ,core.[TICKER]
			  ,CAST([ID_VALOREN] AS VARCHAR(12)) AS [VALOREN]
			  ,CAST([ID_WERTPAPIER] AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST([CNTRY_ISSUE_ISO] AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST(NULL AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST([EXCH_CODE] AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST(NULL AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST([PRPL] AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST(NULL AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST(NULL AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST(NULL AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST([ID_BB_UNIQUE] AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST(NULL AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST(NULL AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST(NULL AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST(NULL AS VARCHAR(80)) AS [ISSUER]
			  ,CAST(NULL AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST(NULL AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST(NULL AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED			  
		FROM 
		(SELECT [FILE_NAME] AS [FILE_NAME]
			  ,CONVERT(DATE, [DATE]) AS [DATE]
			  ,[IDENTIFIER]
			  ,[FIELD]
			  ,[VALUE]
			  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
		FROM [dbo].[T_BPS_SECURITY]) p
		PIVOT
		(
			MIN([VALUE])
		FOR [FIELD] IN
		( 
			[ID_BB_UNIQUE],
			[ID_CUSIP],
			[ID_VALOREN],
			[ID_WERTPAPIER],
			[CNTRY_ISSUE_ISO],
			[ISSUER],
			[PRPL],
			[EXCH_CODE]
		)
		) AS pvt
		LEFT JOIN CTE_CORE core ON core.IDENTIFIER = pvt.IDENTIFIER AND core.DATE = PVT.DATE
		  WHERE --map.FIELD_NAME = 'Market Sector Two' AND 
		  pvt.FILE_NAME LIKE 'EQ_MISC%'
		  UNION ALL

		  /*
		  Equity Private Company
		  */
			SELECT
			  pvt.[FILE_NAME], pvt.[DATE], pvt.[IDENTIFIER], 
			  core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST(NULL AS VARCHAR(9)) AS [CUSIP]
			  ,CAST(ID_ISIN AS VARCHAR(12)) AS [ISIN]
			  ,CAST(NULL AS VARCHAR(7)) AS [SEDOL]
			  ,core.[TICKER]
			  ,CAST(NULL AS VARCHAR(12)) AS [VALOREN]
			  ,CAST(NULL AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST(CNTRY_OF_INCORPORATION AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST([CNTRY_ISSUE_ISO] AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST(CNTRY_OF_RISK AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST([ID_MIC_PRIM_EXCH] AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST([EXCH_CODE] AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST(NULL AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST([PRPL] AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST(NULL AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST(NULL AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST(NULL AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST([ID_BB_UNIQUE] AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST(NULL AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST(NULL AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST(NULL AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST(ISSUER AS VARCHAR(80)) AS [ISSUER]
			  ,CAST(NULL AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST(NULL AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST(NULL AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED			  
		FROM 
		(SELECT [FILE_NAME] AS [FILE_NAME]
			  ,CONVERT(DATE, [DATE]) AS [DATE]
			  ,[IDENTIFIER]
			  ,[FIELD]
			  ,[VALUE]
			  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
		FROM [dbo].[T_BPS_SECURITY]) p
		PIVOT
		(
			MIN([VALUE])
		FOR [FIELD] IN
		( 
			[ID_BB_UNIQUE],
			[ID_ISIN],
			[CNTRY_OF_INCORPORATION],
			[CNTRY_OF_RISK],
			[CNTRY_ISSUE_ISO],
			[ID_MIC_PRIM_EXCH],
			[ISSUER],
			[PRPL],
			[EXCH_CODE]
		)
		) AS pvt
		LEFT JOIN CTE_CORE core ON core.IDENTIFIER = pvt.IDENTIFIER AND core.DATE = PVT.DATE
		  WHERE --map.FIELD_NAME = 'Market Sector Two' AND 
		  pvt.FILE_NAME LIKE 'EQ_PRIVATE_CO%'
		  UNION ALL
		/*
			EQ_PRIVATE_EQ
		*/
		SELECT
			  pvt.[FILE_NAME], pvt.[DATE], pvt.[IDENTIFIER], 
			  core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST(ID_CUSIP AS VARCHAR(9)) AS [CUSIP]
			  ,CAST(NULL AS VARCHAR(12)) AS [ISIN]
			  ,CAST(NULL AS VARCHAR(7)) AS [SEDOL]
			  ,core.[TICKER]
			  ,CAST(NULL AS VARCHAR(12)) AS [VALOREN]
			  ,CAST(NULL AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST([CNTRY_ISSUE_ISO] AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST(NULL AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST([EXCH_CODE] AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST(NULL AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST([PRPL] AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST(NULL AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST(NULL AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST(NULL AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST(COALESCE([ID_BB_UNIQUE],pvt.[IDENTIFIER]) AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST(NULL AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST(NULL AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST(NULL AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST(ISSUER AS VARCHAR(80)) AS [ISSUER]
			  ,CAST(NULL AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST(NULL AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST(NULL AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED			  
		FROM 
		(SELECT [FILE_NAME] AS [FILE_NAME]
			  ,CONVERT(DATE, [DATE]) AS [DATE]
			  ,[IDENTIFIER]
			  ,[FIELD]
			  ,[VALUE]
			  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
		FROM [dbo].[T_BPS_SECURITY]) p
		PIVOT
		(
			MIN([VALUE])
		FOR [FIELD] IN
		( 
			[ID_BB_UNIQUE],
			[CNTRY_ISSUE_ISO],
			[ISSUER],
			[PRPL],
			[EXCH_CODE],
			ID_CUSIP
		)
		) AS pvt
		LEFT JOIN CTE_CORE core ON core.IDENTIFIER = pvt.IDENTIFIER AND core.DATE = PVT.DATE
		  WHERE --map.FIELD_NAME = 'Market Sector Two' AND 
		  pvt.FILE_NAME LIKE 'EQ_PRIVATE_EQ%'
		  UNION ALL

		  /*
		  EQ_REIT
		  */
		  SELECT
			  pvt.[FILE_NAME], pvt.[DATE], pvt.[IDENTIFIER], 
			  core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST(ID_CUSIP AS VARCHAR(9)) AS [CUSIP]
			  ,CAST(ID_ISIN AS VARCHAR(12)) AS [ISIN]
			  ,CAST(ID_SEDOL1 AS VARCHAR(7)) AS [SEDOL]
			  ,core.[TICKER]
			  ,CAST(ID_VALOREN AS VARCHAR(12)) AS [VALOREN]
			  ,CAST(ID_WERTPAPIER AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST(CNTRY_OF_INCORPORATION AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST(CNTRY_OF_DOMICILE AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST([CNTRY_ISSUE_ISO] AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST(CNTRY_OF_RISK AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST(STATE_CODE2 AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST(NULL AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST([PRPL] AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST(NULL AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST(NULL AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST(NULL AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST(COALESCE([ID_BB_UNIQUE],pvt.[IDENTIFIER]) AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST(NULL AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST(NULL AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST(NULL AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST(ISSUER AS VARCHAR(80)) AS [ISSUER]
			  ,CAST(NULL AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST(PRIMARY_EXCHANGE_NAME AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST(NULL AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED			  
		FROM 
		(SELECT [FILE_NAME] AS [FILE_NAME]
			  ,CONVERT(DATE, [DATE]) AS [DATE]
			  ,[IDENTIFIER]
			  ,[FIELD]
			  ,[VALUE]
			  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
		FROM [dbo].[T_BPS_SECURITY]) p
		PIVOT
		(
			MIN([VALUE])
		FOR [FIELD] IN
		( 
			[ID_BB_UNIQUE],
			[BBG_EXCHANGE_CODE],
			[CNTRY_ISSUE_ISO],
			[CNTRY_OF_DOMICILE],
			[CNTRY_OF_INCORPORATION],
			[CNTRY_OF_RISK],
			[ID_BB_SECURITY],
			[ID_CUSIP],
			[ID_IRISH_SEDOL],
			[ID_ISIN],
			[ID_MIC_PRIM_EXCH],
			[ID_SEDOL1],
			[ID_VALOREN],
			[ID_WERTPAPIER],
			[ISSUER],
			[PRIMARY_EXCHANGE_NAME],
			[PRPL],
			[STATE_CODE2]
		)
		) AS pvt
		LEFT JOIN CTE_CORE core ON core.IDENTIFIER = pvt.IDENTIFIER AND core.DATE = PVT.DATE
		  WHERE --map.FIELD_NAME = 'Market Sector Two' AND 
		  pvt.FILE_NAME LIKE 'EQ_REIT%'
		UNION ALL
		/*
			EQ_RIGHT
		*/

		SELECT
			  pvt.[FILE_NAME], pvt.[DATE], pvt.[IDENTIFIER], 
			  core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST(ID_CUSIP AS VARCHAR(9)) AS [CUSIP]
			  ,CAST(NULL AS VARCHAR(12)) AS [ISIN]
			  ,CAST(NULL AS VARCHAR(7)) AS [SEDOL]
			  ,core.[TICKER]
			  ,CAST(ID_VALOREN AS VARCHAR(12)) AS [VALOREN]
			  ,CAST(ID_WERTPAPIER AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST([CNTRY_ISSUE_ISO] AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST(NULL AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST(NULL AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST([PRPL] AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST(NULL AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST(NULL AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST(NULL AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST(COALESCE([ID_BB_UNIQUE],pvt.[IDENTIFIER]) AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST(NULL AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST(NULL AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST(NULL AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST(ISSUER AS VARCHAR(80)) AS [ISSUER]
			  ,CAST(NULL AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST(NULL AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST(NULL AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED			  
		FROM 
		(SELECT [FILE_NAME] AS [FILE_NAME]
			  ,CONVERT(DATE, [DATE]) AS [DATE]
			  ,[IDENTIFIER]
			  ,[FIELD]
			  ,[VALUE]
			  ,[CADIS_SYSTEM_UPDATED] AS CADIS_SYSTEM_UPDATED
		FROM [dbo].[T_BPS_SECURITY]) p
		PIVOT
		(
			MIN([VALUE])
		FOR [FIELD] IN
		( 
			[ID_BB_UNIQUE],
			[BBG_EXCHANGE_CODE],
			[CNTRY_ISSUE_ISO],
			[ID_CUSIP],
			[ID_VALOREN],
			[ID_WERTPAPIER],
			[ISSUER],
			[PRPL]
		)
		) AS pvt
		LEFT JOIN CTE_CORE core ON core.IDENTIFIER = pvt.IDENTIFIER AND core.DATE = PVT.DATE
		  WHERE
		  pvt.FILE_NAME LIKE 'EQ_RIGHT%'
		UNION ALL

		SELECT 
		core.[FILE_NAME], core.[DATE], core.[IDENTIFIER], 
				core.[SECURITY_NAME]
			  ,core.[SECURITY_DESCRIPTION]
			  ,core.[SECURITY_SHORTNAME]
			  ,core.[ASSET_TYPE]
			  ,core.[SECURITY_TYPE]
			  ,CAST([CUSIP] AS VARCHAR(9)) AS [CUSIP]
			  ,CAST([ISIN] AS VARCHAR(12)) AS [ISIN]
			  ,CAST(NULL AS VARCHAR(7)) AS [SEDOL] 
			  ,core.[TICKER]
			  ,CAST([VALOREN] AS VARCHAR(12)) AS [VALOREN]
			  ,CAST([WERTPAPIER] AS VARCHAR(12)) AS [WERTPAPIER]
			  ,core.[SECURITY_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [RISK_ISO_CCY]
			  ,CAST(NULL AS VARCHAR(3)) AS [FIXED_ISO_CCY]
			  ,CAST([INCORPORATION_ISO_CTY] AS VARCHAR(4)) AS [INCORPORATION_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [DOMICILE_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [ISSUE_COUNTRY_ISO]
			  ,CAST(NULL AS VARCHAR(4)) AS [RISK_ISO_CTY]
			  ,CAST(NULL AS VARCHAR(4)) AS [MIC_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_EXCHANGE_CODE]
			  ,CAST(NULL AS VARCHAR(8)) AS [STATE_CODE]
			  ,CAST([ACTIVE_TRADE_INDICATOR] AS VARCHAR(1)) AS [ACTIVE_TRADE_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [144A_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [PRIVATE_PLACEMENT_INDICATOR]
			  ,CAST(NULL AS VARCHAR(1)) AS [ILLIQUID]
			  ,CAST(NULL AS VARCHAR(8)) AS [QUOTE_TYPE]
			  ,CAST(NULL AS INT) AS [DAYS_TO_SETTLE]
			  ,CAST(NULL AS VARCHAR(4)) AS [TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,CAST(core.[IDENTIFIER] AS VARCHAR(30)) AS [UNIQUE_BLOOMBERG_ID]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SECTOR]
			  ,CAST(NULL AS VARCHAR(20)) AS [BBG_SUBSECTOR]
			  ,CAST(NULL AS VARCHAR(40)) AS [BBG_GROUP]
			  ,CAST(NULL AS VARCHAR(20)) AS [IS_IPO]
			  ,core.[PARSEKEYABLE_DESCRIPTION]
			  ,CAST(NULL AS VARCHAR(20)) AS [SECURITY_IDENTIFIER]
			  ,CAST(NULL AS VARCHAR(20)) AS [IRISH_SEDOL_NUMBER]
			  ,CAST([ISSUER_NAME] AS VARCHAR(80)) AS [ISSUER]
			  ,CAST(NULL AS VARCHAR(20)) AS [CUR_MAR_CAP]
			  ,CAST(NULL AS VARCHAR(30)) AS [PRIMARY_EXCHANGE_NAME]
			  ,CAST(NULL AS VARCHAR(4)) AS [SECURITY_HAS_ADRS]
			  ,core.[VOLUME_AVG_5D]
			  ,core.[VOLUME_AVG_20D]
			  ,core.[ADV_TOTAL_VOLUME]
			  ,CADIS_SYSTEM_UPDATED 			  
		FROM CTE_CORE core
		WHERE NOT EXISTS (
			SELECT 1 FROM [dbo].[T_BPS_SECURITY] s WHERE s.Identifier = core.Identifier AND CONVERT(DATE,s.Date) = core.Date
			AND s.FILE_NAME NOT LIKE 'BPS_CORE%'
	
		)
) Data
GROUP BY 
			[IDENTIFIER]
			,[SECURITY_NAME]
			  ,[SECURITY_DESCRIPTION]
			  ,[SECURITY_SHORTNAME]
			  ,[ASSET_TYPE]
			  ,[SECURITY_TYPE]
			  ,[CUSIP]
			  ,[ISIN]
			  ,[SEDOL] 
			  ,[TICKER]
			  ,[VALOREN]
			  ,[WERTPAPIER]
			  ,[SECURITY_ISO_CCY]
			  ,[RISK_ISO_CCY]
			  ,[FIXED_ISO_CCY]
			  ,[INCORPORATION_ISO_CTY]
			  ,[DOMICILE_ISO_CTY]
			  ,[ISSUE_COUNTRY_ISO]
			  ,[RISK_ISO_CTY]
			  ,[MIC_EXCHANGE_CODE]
			  ,[BBG_EXCHANGE_CODE]
			  ,[STATE_CODE]
			  ,[ACTIVE_TRADE_INDICATOR]
			  ,[144A_INDICATOR]
			  ,[PRIVATE_PLACEMENT_INDICATOR]
			  ,[ILLIQUID]
			  ,[QUOTE_TYPE]
			  ,[DAYS_TO_SETTLE]
			  ,[TRADE_SETTLEMENT_CALENDAR_CODE]
			  ,[UNIQUE_BLOOMBERG_ID]
			  ,[BBG_SECTOR]
			  ,[BBG_SUBSECTOR]
			  ,[BBG_GROUP]
			  ,[IS_IPO]
			  ,[PARSEKEYABLE_DESCRIPTION]
			  ,[SECURITY_IDENTIFIER]
			  ,[IRISH_SEDOL_NUMBER]
			  ,[ISSUER]
			  ,[CUR_MAR_CAP]
			  ,[PRIMARY_EXCHANGE_NAME]
			  ,[SECURITY_HAS_ADRS]
			  ,[VOLUME_AVG_5D]
			  ,[VOLUME_AVG_20D]
			  ,[ADV_TOTAL_VOLUME]
