
CREATE VIEW [dbo].[T_BPS_CORE_VIEW]
AS
  SELECT [FILE_NAME], [DATE], [IDENTIFIER]
      ,map.Target_Code AS [ASSET_TYPE]
      ,[SECURITY_TYP] AS [SECURITY_TYPE]
	  ,pvt.CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED
FROM 
(SELECT [FILE_NAME]
      ,[DATE]
      ,[IDENTIFIER]
      ,[FIELD]
	  ,[VALUE]
	  ,CADIS_SYSTEM_UPDATED AS CADIS_SYSTEM_UPDATED
FROM [dbo].[T_BPS_CORE_IN]) p
PIVOT
(
	MIN([VALUE])
FOR [FIELD] IN
( 
	[MARKET_SECTOR2],
	[SEC_ID_FLAG],
	[SECURITY_TYP]
 )
) AS pvt
LEFT JOIN [dbo].[T_REF_GENERAL_MAP] map ON map.[SOURCE_CODE] = [MARKET_SECTOR2]
  WHERE map.FIELD_NAME = 'Market Sector Two'
