
CREATE VIEW V_NT_FAILED_TRADES_BROKER_MAPPING_EXCEPTIONS
AS
SELECT DISTINCT T.BROKER		as [NT Broker Name]
FROM T_NT_FAILED_TRADE_REPORT T
LEFT OUTER JOIN T_REF_BROKER_MAPPING B
ON T.BROKER = B.NT_BROKER_NAME
WHERE B.BROKER_ID IS NULL
--AND DATEPART(YEAR, T.TRADE_DATE) >= 2017
