


CREATE VIEW [dbo].[V_REF_UNQUOTED_ISSUER_LOOKUP] AS

SELECT
	  sec.ISSUER 									AS	NAME
	 ,CONCAT(sec.ISSUER, ' - ',SECURITY_ISO_CCY)	AS	VALUE

FROM "dbo"."T_MASTER_sec"  sec

WHERE sec.SECURITY_TYPE = 'Private Synthetic Equity Secur'
GROUP BY sec.ISSUER, SECURITY_ISO_CCY

UNION 

SELECT
	  iss.NEW_ISSUER 									AS	NAME
	 ,CONCAT(iss.NEW_ISSUER, ' - ',SECURITY_ISO_CCY)	AS	VALUE

FROM T_UNQUOTED_NEW_ISSUER iss
WHERE  isnull(TECH_STATUS,'') <> 'COMPLETE'
	

