

CREATE VIEW [dbo].[V_SLA_PROCESS_MONITOR] AS

  SELECT 
  		 pm.[PLATFORM]
		,pm.SOURCE
		,pm.ENTITY
		,pm.SUB_ENTITY
		,pr.DESCRIPTION
		,pr.DIRECTION
		,pm.RUN_DATE
		,pm.ROW_COUNT
		,pm.PREVIOUS_ROW_COUNT
		,pm.PROCESS_STATUS
		,pm.RUN_STATUS
		,pm.TIME_STATUS
		,pr.RECORDS
		,pr.TOLERANCE_PRECENT
		,pr.SOLUTION
		,pr.TABLE_NAME
		,pr.EXPECTED_TIME_GMT
		,pr.EXPECTED_TIME_TOLERANCE_MINUTES
		,pr.[OWNER]
		,pr.EMAIL_RECIPIENT
		,pm.ALERT_SENT
		,pr.IS_ACTIVE


  FROM			T_SLA_PROCESS_MONITOR pm
  LEFT JOIN		T_SLA_PARAM pr on pr.SOURCE = pm.SOURCE and pr.[PLATFORM] = pm.[PLATFORM] and pr.ENTITY = pm.ENTITY and pr.SUB_ENTITY = pm.SUB_ENTITY
 
