CREATE VIEW [dbo].[VW_MASTER_FUND_FLOW]
AS

SELECT	FF.FUND_SHORT_NAME, 
		FF.TRANSACTION_DATE, 
		FF.CURRENCY, 
		CASE ISNULL(FT.FUND_SHORT_NAME, '0') WHEN '0' THEN 'NET' ELSE 'GROSS' END AS FUND_FLOW_TYPE,
		FF.FLOW_TYPE, 
		FF.SOURCE_TYPE, 
		FF.MARKET_VALUE, 
		FF.CADIS_SYSTEM_INSERTED, 
		FF.CADIS_SYSTEM_UPDATED, 
		FF.CADIS_SYSTEM_CHANGEDBY, 
		FF.CADIS_SYSTEM_PRIORITY, 
		FF.CADIS_SYSTEM_LASTMODIFIED, 
		FF.SOURCE, 
		FF.DATA_SOURCE
FROM	T_MASTER_FUND_FLOW FF
LEFT	OUTER  JOIN
		(
        SELECT FUND_SHORT_NAME, TRANSACTION_DATE, CURRENCY, FUND_FLOW_TYPE, SOURCE_TYPE
        FROM   T_MASTER_FUND_FLOW
        GROUP  BY FUND_SHORT_NAME, TRANSACTION_DATE, CURRENCY, FUND_FLOW_TYPE, SOURCE_TYPE
        HAVING COUNT(*) > 1
        ) FT
ON      FT.FUND_SHORT_NAME = FF.FUND_SHORT_NAME
AND     FT.TRANSACTION_DATE = FF.TRANSACTION_DATE
AND     FT.CURRENCY = FF.CURRENCY
AND     FT.FUND_FLOW_TYPE = FF.FUND_FLOW_TYPE
AND     FT.SOURCE_TYPE = FF.SOURCE_TYPE
